.github/CODEOWNERS, PULL_REQUEST_TEMPLATE.md
Copy CODEOWNERS and PULL_REQUEST_TEMPLATE from master branch
=> Add CODEOWNERS and PULL_REQUEST_TEMPLATE

test/ElmSharp.Test/ElmSharp.Test.csproj, test/ElmSharp.Test/TC/ImageTest5.cs
Update ElmSharp.Test.csproj and clean up.
None
None
None
=> [ElmSharp] Update ElmSharp.Test.csproj and clean up.

src/Tizen.Multimedia.MediaCodec/MediaCodec/BufferStatusChangedEventArgs.cs, src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs, src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecErrorOccurredEventArgs.cs
Added feature tags on the related classes and methods.
- ACR: http://suprem.sec.samsung.net/jira/projects/TCSACR/issues/TCSACR-121
=> [MediaCodec] Added feature tags.

src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaContentError.cs
Added NotSupportedException to be thrown when the feature is not supported.
- ACR: ttp://suprem.sec.samsung.net/jira/projects/TCSACR/issues/TCSACR-125
=> [MediaContent] Added NotSupportedException to be thrown when the feature is not supported.

src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Added feature tag on the ApplyAudioStreamPolicy method.
- ACR: http://suprem.sec.samsung.net/jira/projects/TCSACR/issues/TCSACR-122
=> [MediaPlayer] Added feature tag on the ApplyAudioStreamPolicy method.

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Layer.cs
Fix sibling issue : Layer.cs, View.cs
=> Tizen.nui fix sibling

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Layer.cs
=> [NUI]Fix children property

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs, src/Tizen.Multimedia.MediaPlayer/Player/EqualizerBand.cs, src/Tizen.Multimedia.MediaPlayer/Player/MediaBufferSource.cs, src/Tizen.Multimedia.MediaPlayer/Player/MediaStreamConfiguration.cs, src/Tizen.Multimedia.MediaPlayer/Player/MediaStreamSource.cs, src/Tizen.Multimedia.MediaPlayer/Player/MediaUriSource.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.ErrorHandler.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.Events.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerDisplaySettings.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerTrackInfo.cs, src/Tizen.Multimedia.MediaPlayer/Player/StreamInfo.cs
ErrorHandler can be registered from inherited classes.
It is for product extension,
Added:
- Player.AddErrorHandler
- Player.RemoveErrorHandler
=> [MediaPlayer] Added ErrorHandler registration methods for internal use.

src/Tizen.Multimedia.Recorder/Recorder/AudioRecorder.cs, src/Tizen.Multimedia.Recorder/Recorder/Recorder.Capabilities.cs, src/Tizen.Multimedia.Recorder/Recorder/RecorderFeatures.cs, src/Tizen.Multimedia.Recorder/Recorder/VideoRecorder.Capabilities.cs, src/Tizen.Multimedia.Recorder/Recorder/VideoRecorder.cs
Change recorder feature
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-129
Change feature of recorder API
: "http://tizen.org/feature/microphone" -> "http://tizen.org/feature/media.audio_recording"
"http://tizen.org/feature/camera" -> "http://tizen.org/feature/media.video_recording"
=> [Recorder] Change recorder feature

src/Tizen.NUI/src/internal/ManualPINVOKE.cs, src/Tizen.NUI/src/internal/NDalic.cs, src/Tizen.NUI/src/internal/NDalicPINVOKE.cs, src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/NUIConstants.cs, src/Tizen.NUI/src/public/VisualMaps.cs
- Added playback (i.e. Play, Pause, Stop) support for the animated GIF
- Loop count support for animated GIF
=> [NUI] Support for animated GIF

src/Tizen.Messaging/Tizen.Messaging.Messages/MessagesManager.cs, src/Tizen.Messaging/Tizen.Messaging.Messages/MessagesManagerImpl.cs
change a property to a method for exception handling 
C# TCT is failed
http://mosaic.sec.samsung.net/kms/comty.do?comtyId=3158147&menuId=3158203&postId=6730646&page=view&type=LIST
=> [Message]change a property to a method for exception handling

src/ElmSharp/ElmSharp/Background.cs
Remove internal layout for Background because bg theme have opacity part in all profile efl theme
=> [ElmSharp] Remove layout for Background

src/ElmSharp/ElmSharp/GenItemClass.cs, src/ElmSharp/ElmSharp/GestureLayer.cs, src/ElmSharp/ElmSharp/Image.cs
Apply fixes based on static analysis results
1. Kona WorkItemID : DF180112-00947
- Checker: DEREF_AFTER_AS.INSTANT
- File: /ElmSharp/ElmSharp/GenItemClass.cs
- Line:  220
2. Kona WorkItemID : DF180112-01032
- Checker: HANDLE_LEAK
- File: /ElmSharp/ElmSharp/Image.cs
- Line:  621
3. Kona WorkItemID : DF180112-01386
- Checker: NO_LOCK.STAT
- File: /ElmSharp/ElmSharp/GestureLayer.cs
- Line:  562
=> [ElmSharp] Fixed svace issue

src/ElmSharp/ElmSharp/EvasObject.cs
Add global dictionary for map for every EvasObject and native handle
Add explicit converter can be used to get managed EvasObject from native handle
Change-Id: I253ffeaa3599b885862bb10054627f500854e2d1
Add global dictionary for map for every EvasObject and native handle
Add explicit converter can be used to get managed EvasObject from native handle
--
Add Explicit converter to EvasObject from IntPtr
Added
public static explicit operator EvasObject(IntPtr handle)
--
=> [ElmSharp] Add explicit operator for native handle

src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
Add SetProperty for VerticalLineAlignment
=> [NUI] Add SetProperty for VerticalLineAlignment

src/Tizen.System/Device/Battery.cs, src/Tizen.System/Device/Led.cs
Apply fixes based on static analysis results
Bugs about thread safety were detected
Bugs Fixed
Kona WorkItemID : DF180112-01404
Checker: NO_LOCKSTAT
File: /Device/Battery.cs
Line: 285
Kona WorkItemID : DF180112-01407
Checker: NO_LOCKSTAT
File: /Device/Led.cs
Line: 216
=> [Device] add lock for global variable of led and battery

src/Tizen.System.Information/RuntimeInfo/RuntimeInfoEventHandler.cs
Signed-off-by: kichankwon <k_c.kwon@samsung.com>
- Fix that delegate is freed by garbage collector
=> [Information] Fix delegate lifetime issue

src/Tizen.Messaging.Push/Tizen.Messaging.Push/PushImpl.cs
=> Fixed svace issue

src/Tizen.Messaging.Push/Tizen.Messaging.Push/PushImpl.cs
Fixed svace issue; Possible missing lock before accessing to the _instance variable.
moved "return _instance;" into lock (_lock) block.
- Kona DF180112-01393
- ACR: 
None
=> [Push] Fixed svace issue

src/Tizen.Pims.Contacts/Tizen.Pims.Contacts/ContactsDatabase.cs, src/Tizen.Pims.Contacts/Tizen.Pims.Contacts/ContactsManager.cs
fix svace issues (add lock statement)
- fix svace issues (add lock statement)
=> [Contacts]fix svace issues

src/Tizen.Uix.Stt/Interop/Interop.Stt.cs, src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs, src/Tizen.Uix.SttEngine/Interop/Interop.SttEngine.cs, src/Tizen.Uix.Tts/Interop/Interop.Tts.cs, src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs, src/Tizen.Uix.TtsEngine/Interop/Interop.TtsEngine.cs, src/Tizen.Uix.VoiceControl/Interop/Interop.VoiceControl.cs
Fix some wrong indentation and lock.
=> [Tts/Stt/VoiceControl] Fix indent and lock issue

src/Tizen.Pims.Calendar/Tizen.Pims.Calendar/CalendarDatabase.cs, src/Tizen.Pims.Calendar/Tizen.Pims.Calendar/CalendarStructs.cs
[Calendar] Fix svace issue
- DF180112-01238
DF180112-01307
=> [Calendar] Fix svace issue

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Layer.cs, test/NUITestSample/NUITestSample/examples/ref-cnt-error-memory-leak.cs
Signed-off-by: dongsug.song <dongsug.song@samsung.com>
[NUI]fix memory leak problem caused by wrong increased ref-cnt
[NUI]fix memory leak problem caused by wrong increased ref-cnt
Non-ACR
N/A
=> [NUI]fix memory leak problem caused by wrong increased ref-cnt

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Layer.cs
=> [NUI]Revert sibling patch

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Layer.cs
=> [NUI] Apply sibling patch

src/Tizen.Security.TEEC/Tizen.Security.TEEC/Libteec.cs
Prevent multiple destruction of inernal objects.
- N/A
None
None
No info in log file about context not fount or session_imp is null
=> [TEEC] Guard session close in destructor, apply 'Dispose Pattern'

src/Tizen.Telephony/Tizen.Telephony/ChangeNotificationEventArgs.cs
Fix call notification numbering
=> [Telephony] Fix call notification numbering

src/Tizen.Multimedia.Camera/Camera/CameraDisplaySettings.cs, src/Tizen.Multimedia.Camera/Camera/CameraSettings.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerDisplaySettings.cs, src/Tizen.Multimedia.MediaPlayer/Player/StreamInfo.cs, src/Tizen.Multimedia.Vision/MediaVision/BarcodeDetectionConfiguration.cs, src/Tizen.Multimedia.Vision/MediaVision/BarcodeGenerationConfiguration.cs, src/Tizen.Multimedia.Vision/MediaVision/BarcodeGenerator.cs, src/Tizen.Multimedia.Vision/MediaVision/BarcodeImageConfiguration.cs, src/Tizen.Multimedia.Vision/MediaVision/FaceRecognitionConfiguration.cs, src/Tizen.Multimedia/Common.Internal/ValdiationUtil.cs
This is used in the ArgumentException constructor which is thrown from the method.
=> [Multimedia] Added paramName to every ValidateEnum call.

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Layer.cs
Add protected codes for SiblingOrder
=> [NUI] Add protected codes for SiblingOrder

src/Tizen.Multimedia/Common.Internal/MediaBufferBase.cs
Implementation was wrong, the 'IsReadOnly' property should be initialized from the argument.
=> [Multimedia] Fixed wrong implementation of MediaBufferBase.

src/Tizen.NUI/src/internal/FrameBuffer.cs, src/Tizen.NUI/src/internal/ViewWrapperImpl.cs, src/Tizen.NUI/src/public/BaseComponents/TableView.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/FocusManager.cs, src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/Renderer.cs, src/Tizen.NUI/src/public/TextureSet.cs, src/Tizen.NUI/src/public/Touch.cs, src/Tizen.NUI/src/public/UIComponents/Popup.cs
=> [NUI] Fix memory leak problem

src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Fix Parent crash error

src/Tizen.NUI/src/public/BaseComponents/View.cs
[NUI] fix Parent property memory leak
[NUI] fix Parent property memory leak
N/A
N/A
=> [NUI] fix Parent property memory leak

src/Tizen.System.Storage/Storage/Storage.cs, src/Tizen.System.Storage/Storage/StorageArea.cs, src/Tizen.System.Storage/Storage/StorageDevice.cs, src/Tizen.System.Storage/Storage/StorageManager.cs
Fix api and enum version
N/A
http://suprem.sec.samsung.net/jira/browse/TCSACR-127
Changed:
- api, property, and enum version is changed
N/A
=> [Storage]Fix api and enum version

src/Tizen.NUI/src/internal/FrameBuffer.cs, src/Tizen.NUI/src/internal/ViewWrapperImpl.cs, src/Tizen.NUI/src/public/BaseComponents/TableView.cs, src/Tizen.NUI/src/public/FocusManager.cs, src/Tizen.NUI/src/public/Renderer.cs, src/Tizen.NUI/src/public/TextureSet.cs, src/Tizen.NUI/src/public/Touch.cs, src/Tizen.NUI/src/public/UIComponents/Popup.cs
[NUI] memory leak issue, rollback changes except View and Layer
[NUI] memory leak issue, rollback changes except View and Layer
N/A
N/A
=> [NUI] memory leak issue, rollback changes except View and Layer

src/Tizen.NUI/src/public/BaseComponents/View.cs
[NUI] Fix TCT crash issue - Parent crash
=> [NUI] Fix TCT crash issue - Parent crash

src/Tizen.Multimedia.MediaPlayer/Player/Player.ErrorHandler.cs
Restored the GetException internal api of Player.
=> [Multimedia] Restored the GetException internal api of Player.

src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs
Fixed wrong implementation of GetException of MediaPlayer.
Exceptions must be returned, not thrown.
=> [Multimedia] Fixed wrong implementation of GetException of MediaPlayer.

src/Tizen.NUI/src/internal/FrameBuffer.cs, src/Tizen.NUI/src/internal/ViewWrapperImpl.cs, src/Tizen.NUI/src/public/Animation.cs, src/Tizen.NUI/src/public/BaseComponents/TableView.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/FocusManager.cs, src/Tizen.NUI/src/public/NUIConstants.cs, src/Tizen.NUI/src/public/Renderer.cs, src/Tizen.NUI/src/public/TextureSet.cs, src/Tizen.NUI/src/public/Touch.cs, src/Tizen.NUI/src/public/UIComponents/Popup.cs, src/Tizen.NUI/src/public/VisualMaps.cs, test/NUITestSample/NUITestSample/examples/ref-cnt-error-memory-leak-2.cs
[NUI] Fix memory leak
[NUI] Fix memory leak
None
None
=> [NUI] Fix memory leak

src/Tizen.NUI/src/internal/Registry.cs
[NUI] Change Registry as concurrent collection for protection code
[NUI] Change Registry as concurrent collection for protection code
None
None
=> [NUI] Change Registry as concurrent collection for protection code

src/Tizen.NUI/src/internal/Registry.cs
=> [NUI] Delete NUI Log

src/Tizen.Messaging.Push/Tizen.Messaging.Push/PushImpl.cs
Fixed delegator reference holding issue (state cb, noti cb, register result cb, unregister result cb)
-> Crash issue fix
- N/A
- N/A
- N/A
=> [Push] fixed delegator reference holding issue

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.ErrorHandler.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.Events.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs
Modify MediaPlayer to archive product requirements
=> [Multimedia] Modify MediaPlayer for product reuse

src/Tizen.Telephony/Tizen.Telephony/ChangeNotificationEventArgs.cs
Revert "[Telephony] Fix call notification numbering (#91)"
=> [Telephony] Revert "[Telephony] Fix call notification numbering (#91)"

src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
Signed-off-by: sungrae jo <seongrae.jo@samsung.com>
Fix lock issue
Possible missing lock before accessing to the _handle variable.
=> [Stt] Fix lock issue

src/Tizen.Network.Connection/Interop/Interop.Connection.cs, src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs, src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Change Interop functions to init/deinit native capis for thread handling
Related link
https://review.tizen.org/gerrit/#/c/170914/
https://review.tizen.org/gerrit/#/c/170934/
https://review.tizen.org/gerrit/#/c/170833/
=> [WiFi][Connection] Apply CAPIs for thread handling

src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Consumer.cs
Fixed a bug for checking if IntPtr is null
Fixed a bug for checking if IntPtr is null
N/A
N/A
=> [Tizen.Applications.DataControl] Fixed a bug for checking if IntPtr is null

src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationStyleBinder.cs
- regardless of IsAutoRemove
- ACR: 
Added:
Changed:
=> [Notification] Save the hidetime, deletetime value

src/Tizen.Security.TEEC/Tizen.Security.TEEC/Libteec.cs
Manage shared memory, so C# programmer don't have to Release it manually.
- none
- implements IDisposable interface
SharedMemory will be released when GC call finalizer.
=> [TEEC] Make SharedMemory disposable

src/Tizen.Network.Connection/Tizen.Network.Connection.csproj, src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs, src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi.csproj, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Registering events should be executed in main thread.
Behavioral Changes
All events are registered in main thread.
As a result, they are delivered to main thread.
=> [Connection][WiFi]Apply TizenSynchronizationContext for event handling

src/Tizen.NUI/src/public/BaseComponents/View.cs
Signed-off-by: huiyu <huiyu@huiyu-linux.tn.corp.samsungelectronics.net>
=> [NUI] Fix parent get issue

src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiConfiguration.cs
Unmanaged resources should be always released in Dispose
=> [WiFi] Fix Dispose

src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs, src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Exception within Event add/remove should be ignored
=> [Connection][WiFi] Ignore exception within event add/remove

src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
In order to deliver exceptions in TizenSynchronizationContext.Post() to the caller, Task.SetException is used.
=> [Connection][WiFi] Fix exception handling in async methods

src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiConfiguration.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Handling exception for event and async methods
ref: #150 #153 #154
=> [Connection][WiFi] Handling exception for event and async methods

src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs, src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
[Connection][Network] Change Debug to Info for some Logs
=> [Connection][Network] Change Debug to Info for some Logs

packaging/csapi-tizenfx.spec
Add build option for spec file for the asan(sanitizer) build.
=> Add build option for asan

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Container.cs, src/Tizen.NUI/src/public/Layer.cs
=> [NUI] Make GetParent() protected

packaging/csapi-tizenfx.spec.in
Update csapi-tizenfx.spec.in to support asan build
- N/A
- N/A
- N/A
=> Update csapi-tizenfx.spec.in to support asan

src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Consumer.cs
Fix issue for multithreads
- Add locking mutex codes for register/unregister callback
- Check key if it is contained in dtor
=> Fix issue for multithreads

src/ElmSharp/ElmSharp/ItemObject.cs, src/ElmSharp/Interop/Interop.Elementary.Item.cs, test/ElmSharp.Test/TC/ItemEvasObjectTest.cs
This PR is for fixing track object issue (#152)
Once TrackObject is deleted with disappearing of ItemObject , it is not restored.
N/A
TrackObject will be restored whenever ItemObject appears on the screen.
=> [ElmSharp] Fix TrackObject issue 

src/ElmSharp/ElmSharp/EvasObject.cs
This PR is for fixing issue (#151 )
Modified to call "Deleted" event when EvasObject unrealized
=> [ElmSharp] Modified to call Deleted event when EvasObject Unrealized

src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Consumer.cs
- Add locking mutex codes for register/unregister callback
- Check key if it is contained in dtor
=> [Tizen.Applications.DataControl] Fix issue for multithreads

src/Tizen.System.Information/RuntimeInfo/TvProductHelper.cs
Signed-off-by: Kichan Kwon <k_c.kwon@samsung.com>
Consider AV device as TV product
=> [Information] Consider AV device as TV product

src/ElmSharp/ElmSharp/GestureLayer.cs, src/ElmSharp/ElmSharp/Image.cs, src/ElmSharp/ElmSharp/Naviframe.cs, src/ElmSharp/ElmSharp/Panel.cs, src/ElmSharp/ElmSharp/Table.cs
fixed to parent.Handle for preventing potential bug
=> [ElmSharp] fixed to parent.Handle for preventing potential bug

src/Tizen.Multimedia.MediaPlayer/Player/PlayerDisplaySettings.cs
Modify the precondition of SetRoi method. Now, we can call SetRoi method before setting roi mode.
ACR was accepted and it was merged already in API4.
ACR: TCSACR-135 (http://suprem.sec.samsung.net/jira/browse/TCSACR-135)
=> [MediaPlayer] Modify the precondition of SetRoi method

src/ElmSharp/ElmSharp/Background.cs, src/ElmSharp/ElmSharp/GenItemClass.cs, src/ElmSharp/ElmSharp/GestureLayer.cs, src/ElmSharp/ElmSharp/Image.cs
commit 00386ed3dac74fa506b94b8f744bca3a18cef474
Author: arosis78 <35049857+arosis78@users.noreply.github.com>
Date:   Thu Jan 25 09:44:03 2018 +0900
[ElmSharp] Changed Background Color property internal implementation to Widget BackgroundColor property (#58)
commit ebe359bc46d9bb6c3a8a92f005b096c83e73b0a8
Author: Chungryeol Lim <darkleem@naver.com>
Date:   Thu Jan 18 13:21:22 2018 +0900
[ElmSharp] fix svace issue (#42)
Add an optional extended descriptionâ€¦
commit 021dd64019d89ac5796e2399f9e7045251bc54b0
Author: arosis78 <35049857+arosis78@users.noreply.github.com>
Date:   Thu Jan 18 13:10:08 2018 +0900
[ElmSharp] Remove layout for Background (#28)
=> [ElmSharp] cherry-pick from API4 (#28)(#42)(#58)

src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationStyleBinder.cs
- Value style, is compared with null
- ACR: 
Added:
Changed:
=> Fix wrong code

src/Tizen.NUI/src/internal/Size.cs, src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/FocusManager.cs, src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/NUIConstants.cs, src/Tizen.NUI/src/public/VisualFactory.cs, src/Tizen.NUI/src/public/Window.cs
This reverts commit 776217fb9d9689f4705b00a0d3ef3c6e6cfb52ed.
- ACR: 
Added:
Changed:
=> Revert "[NUI] Delete deprecated APIs (#143)"

src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut/ShortcutManager.cs
- It is a temporary fix to avoid crashing.
Will add new code for Result Reply.
- ACR: 
Added:
Changed:
=> Remove callback function exception handling

packaging/makespec.sh
Remove unused option from the packaging script
=> Remove unused option from the packaging script

build.cmd, build.sh, build/build.proj, build/pack.csproj
Use donet-cli instead of nuget.exe to remove mono dependency.
=> [Build] Remove mono dependency

src/ElmSharp/ElmSharp/EvasObject.cs, src/ElmSharp/ElmSharp/Layout.cs, src/ElmSharp/Interop/Interop.Elementary.cs, src/ElmSharp/Interop/Interop.Eo.cs, test/ElmSharp.Test/TC/Wearable/ButtonTest1.cs
eo_class_get and eo_class_name_get are modified to efl_class_get and efl_class_name_get in efl 1.2.0
Additionally, added elm_object_color_class_del and used this api instead of edje_object_color_class_del in Layout
=> [ElmSharp] modified eo api name according to efl 1.2.0 api name

src/ElmSharp/ElmSharp/GestureLayer.cs, src/ElmSharp/ElmSharp/Image.cs, src/ElmSharp/ElmSharp/Naviframe.cs, src/ElmSharp/ElmSharp/Panel.cs, src/ElmSharp/ElmSharp/Table.cs
fixed to parent.Handle for preventing potential bug
=> [ElmSharp] fixed to parent.Handle for preventing potential bug (#173)

src/Tizen.NUI/src/internal/Registry.cs, src/Tizen.NUI/src/public/NUIWidgetApplication.cs
=> [NUI] Add thread id in NUIWidgetApplication for avoid crash

src/ElmSharp/ElmSharp/Layout.cs, src/ElmSharp/ElmSharp/Popup.cs
Added remarks for Popup and Layout.
=> [ElmSharp] Added remarks for Popup and Layout

src/Tizen.Multimedia.Camera/Camera/Camera.cs, src/Tizen.Multimedia.Camera/Camera/CameraCapabilities.cs, src/Tizen.Multimedia.Camera/Camera/CameraEnums.cs, src/Tizen.Multimedia.Camera/Camera/CameraSettings.cs, src/Tizen.Multimedia.Camera/Camera/Location.cs, src/Tizen.Multimedia.Camera/Interop/Interop.CameraSettings.cs
Add new enum(camera device) and APIs(hue)
API Changes
ACR: TCSACR-136 (http://suprem.sec.samsung.net/jira/browse/TCSACR-136)
=> [Camera] Add new enum(camera device) and properties(hue)

src/Tizen.Multimedia.MediaCodec/Interop/Interop.Libraries.cs, src/Tizen.Multimedia.MediaCodec/Interop/Interop.MediaCodec.cs, src/Tizen.Multimedia.MediaCodec/Interop/Interop.MediaTool.cs, src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs, src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecError.cs, src/Tizen.Multimedia.Recorder/Interop/Interop.Recorder.cs
Add exception handling class to get proper exception.
=> [MediaCodec] Add exception handling code

src/ElmSharp.Wearable/doc/api/ElmSharp.Wearable.md, src/ElmSharp/doc/api/ElmSharp.md
This PR adds ElmSharp and ElmSharp.Wearable namespace summary.
None
None 
None
=> [ElmSharp] Add namespace summary

src/ElmSharp/ElmSharp/EvasObject.cs, src/ElmSharp/ElmSharp/ItemObject.cs, src/ElmSharp/ElmSharp/Layout.cs, src/ElmSharp/ElmSharp/Popup.cs, src/ElmSharp/Interop/Interop.Elementary.Item.cs, test/ElmSharp.Test/TC/ItemEvasObjectTest.cs
Merge bug fix commits into API4 branch
https://github.com/Samsung/TizenFX/pull/209
https://github.com/Samsung/TizenFX/pull/170
https://github.com/Samsung/TizenFX/pull/162
None
None
=> [ElmSharp] Merge bug fix commit from master to API4

src/Tizen.System.Information/RuntimeInfo/TvProductHelper.cs
Signed-off-by: Kichan Kwon <k_c.kwon@samsung.com>
- Fix invalid mapping key for TV product
=> [Information] Fix invalid mapping key for TV product

src/ElmSharp/ElmSharp/EvasObject.cs, src/ElmSharp/Interop/Interop.Evas.cs, test/ElmSharp.Test/TC/RenderOpTest.cs
Add RenderOperation property in EvasObject to change rendering opreation
None
Added:
- EvasObject.RenderOperation { get; set; } // Property
- enum RenderOp
User can change rendering operation to wanted
=> [ElmSharp] Add RenderOperation property in EvasObject

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs, src/Tizen.NUI/src/public/NUIConstants.cs, src/Tizen.NUI/src/public/VisualMaps.cs
Add new NUI APIs
[NUI][TCSACR-130]  version upgrade nui 0.2.66 to nui 0.2.83
http://suprem.sec.samsung.net/jira/browse/TCSACR-130
=> [NUI][TCSACR-130] Add new NUI APIs

src/Tizen.Multimedia.Camera/Camera/Camera.cs
Dispose MediaPacket after callback is completed.
=> [Camera] Dispose MediaPacket after callback is completed

src/Tizen.Multimedia.Camera/Camera/Camera.cs, src/Tizen.Multimedia.Camera/Camera/CameraCapabilities.cs, src/Tizen.Multimedia.Camera/Camera/CameraDisplaySettings.cs, src/Tizen.Multimedia.Camera/Camera/CameraError.cs, src/Tizen.Multimedia.Camera/Camera/CameraSettings.cs
=> [Camera] refactoring

src/ElmSharp.Wearable/doc/api/ElmSharp.Wearable.md, src/ElmSharp/doc/api/ElmSharp.md
Update namespace summary correctly
None
None
None
=> [ElmSharp] Update namespace summary

src/Tizen.NUI/src/public/Window.cs
Enable Window's mouse wheel event. 
Add wheel event binding into root layer (this means in Window)
N/A
None
The native dali stage mouse wheel event is not working now, so this is kind of workaroud solution in NUI side. the native issue is currently under investigation.
=> [NUI] Enable Window's mouse wheel event

src/Tizen.NUI/src/public/BaseComponents/TextField.cs
=> [NUI] Fix TextField GetInputMethodContext issue

src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecError.cs
Add native error type related resource error.
=> [MediaCodec] Add error type

docs/template/tizen/styles/docfx.css, docs/template/tizen/styles/docfx.vendor.css
- Change width of TOC sidebar to 320 from 280.
- Change font-size of TOC Level1 to 14 from 16
=> [Docs] Fix document css styles

src/Tizen.NUI/src/public/Xaml/ViewExtensions.cs, src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs, src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs, src/Tizen.NUI/src/public/XamlBinding/BindablePropertyKey.cs, src/Tizen.NUI/src/public/XamlBinding/BindingBase.cs, src/Tizen.NUI/src/public/XamlBinding/BindingMode.cs, src/Tizen.NUI/src/public/XamlBinding/Command.cs, src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs, src/Tizen.NUI/src/public/XamlBinding/ControlTemplate.cs, src/Tizen.NUI/src/public/XamlBinding/Effect.cs, src/Tizen.NUI/src/public/XamlBinding/Element.cs, src/Tizen.NUI/src/public/XamlBinding/ElementTemplate.cs, src/Tizen.NUI/src/public/XamlBinding/IConfigElement.cs, src/Tizen.NUI/src/public/XamlBinding/IConfigPlatform.cs, src/Tizen.NUI/src/public/XamlBinding/IEffectControlProvider.cs, src/Tizen.NUI/src/public/XamlBinding/INavigation.cs, src/Tizen.NUI/src/public/XamlBinding/IPlatformElementConfiguration.cs, src/Tizen.NUI/src/public/XamlBinding/NavigationEventArgs.cs, src/Tizen.NUI/src/public/XamlBinding/NavigationPage.cs, src/Tizen.NUI/src/public/XamlBinding/Page.cs, src/Tizen.NUI/src/public/XamlBinding/SizeRequest.cs, src/Tizen.NUI/src/public/XamlBinding/TemplatedPage.cs, src/Tizen.NUI/src/public/XamlBinding/Thickness.cs
Add [EditorBrowsable(EditorBrowsableState.Never)] for public class in nui xaml.
To make all the nui xaml APIs as inhouse-APIs.
None
None
None
=> [NUI] Add EditorBrowsable Attribute

src/Tizen.NUI/src/internal/Registry.cs
Fix TCT fail issue, remove debugging code
None
None
None
=> [NUI] Fix TCT fail issue, remove debugging code

pkg/PlatformFileList.txt
Add account manager in PlatformFileList
Fix account C# all fail issue
N/A
N/A
=> Add account-manager for TV profile

src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs, src/Tizen.NUI/src/internal/Xaml/MarkupExtensionParser.cs, src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs, src/Tizen.NUI/src/internal/XamlBinding/Interactivity/EventTrigger.cs, src/Tizen.NUI/src/internal/XamlBinding/ObservableWrapper.cs, src/Tizen.NUI/src/public/CustomViewRegistry.cs, src/Tizen.NUI/src/public/XamlBinding/Element.cs
fix SVACE issues 2nd trial
None
None
None
=> [NUI] fix SVACE issues 2nd trial

src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs, src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
Added tizen.org/feature/systemsetting.font feature in Tizen 5.
Hence, C# APIs of Tizen.System.SystemSettings also need to be updated.
=> Modify feature for font classes.

src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs, src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
[Tizen.System.SystemSettings] Add feature telephoney for AutomaticTimeUpdate and its EventArgs.
=> [Tizen.System.SystemSettings] Add feature telephoney for AutomaticTimeUpdate and its EventArgs.

src/Tizen.System.Information/RuntimeInfo/RuntimeInfoEventHandler.cs, src/Tizen.System.Information/RuntimeInfo/TvProductHelper.cs
Signed-off-by: Kichan Kwon <k_c.kwon@samsung.com>
Sync with API4 branch
=> [Information] Sync with API4 branch

src/Tizen.NUI/src/internal/Xaml/ExpandMarkupsVisitor.cs, src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs, src/Tizen.NUI/src/public/Property.cs
Fix SVACE issue, 3rd trial
None
None
None
=> [NUI] Fix SVACE issue, 3rd trial

src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs
Fix SVACE issue, 4th trial
None
None
None
=> [NUI] Fix SVACE issue, 4th trial

src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs
Fix SVACE issue, 5th trial
None
None
None
=> [NUI] Fix SVACE issue, 5th trial

src/Tizen.Applications.Alarm/Tizen.Applications/AlarmManager.cs
=> [Tizen.Applications.Alarm] Update doxygen

src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetwork.cs
Free IntPtr to prevent memory leak
=> [WiFi] Free IntPtr

src/Tizen.Uix.InputMethodManager/Interop/Interop.InputMethodManager.cs, src/Tizen.Uix.InputMethodManager/Tizen.Uix.InputMethodManager/InputMethodManager.cs
Add a new API  to pre-launch the IME in On-demand mode.
- N/A
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-147
=> [Inputmethod Manager][TCSACR-147] Add API to launch IME

src/Tizen.NUI/src/internal/Layouting/LayoutGroup.cs, src/Tizen.NUI/src/internal/Layouting/LayoutGroupWrapperImpl.cs, src/Tizen.NUI/src/internal/Layouting/LayoutItem.cs, src/Tizen.NUI/src/internal/Layouting/LayoutItemPtr.cs, src/Tizen.NUI/src/internal/Layouting/LayoutItemWrapperImpl.cs
from =>
Layouting support in NUI
Change-Id: I3d6f688d869faa81c34385db37feceb1d8c1d0c0
m.umar@partner.samsung.com
None
ACR will be done
None
=> [NUI] Add NUI-Layout 2nd patch

src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetwork.cs
Revert freeing IntPtr to avoid crash
=> Revert freeing IntPtr

src/Tizen.NUI/src/internal/ManualPINVOKE.cs, src/Tizen.NUI/src/public/Touch.cs
Add GetMouseButton in Touch
None
ACR will be done later.
Added:
public MouseButtonType GetMouseButton(uint point)
public enum MouseButtonType
None
=> [NUI] Add GetMouseButton in Touch

src/Tizen.NUI/src/public/BaseComponents/View.cs
Add width/height specification property
None
ACR will be done later
None
=> [NUI] Add width/height specification property

src/Tizen.NUI/src/internal/Layouting/LayoutSize.cs
Fix crash error when setting LinearLayout's CellPadding
None
None
None
=> [NUI] Fix crash error when setting LinearLayout's CellPadding

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/AdaptiveVariants.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs, src/Tizen.Multimedia.MediaPlayer/Player/SphericalVideo.cs
[MediaPlayer] add class to set/get adaptive variants and property for buffering time
1.add APIs for setting buffering time
2.add AdaptiveVariants class and APIs to set values
API Changes
•ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-151
Added:
public StreamingBufferingTime BuffTime
public VariantInfo(int bandwidth, int width, int height)
public void SetMaxLimit(int bandwidth, int width, int height)
public VariantInfo GetMaxLimit()
public IEnumerable AvailableAdaptiveVariants
=> [MediaPlayer] add class to set/get adaptive variants and property for buffering time

src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/Window.cs, test/NUITestSample/NUITestSample/examples/layouting/custom-layout-root-layer-test.cs, test/NUITestSample/NUITestSample/examples/layouting/custom-layout-test-2.cs, test/NUITestSample/NUITestSample/examples/layouting/flex-layout-test.cs, test/NUITestSample/NUITestSample/examples/layouting/linear-layout-test.cs, test/NUITestSample/NUITestSample/examples/layouting/root-problem-fix-adding-several-layers.cs
- All Layers have an Absolute layout
From:
agnelo.vaz@samsung.com
Change-Id: I08281a25b2b73822b45f5c6a567b574b5af74fb4
- add and revise sample apps for testing
None
None
None
=> [NUI] All Layers have an Absolute layout

src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
CancelWps() cancels all requests to connect by WPS.
Awaiting methods to connect by WPS should be cancelled.
=> [WiFi] Cancel tasks for WPS connection in CancelWps()

src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
CancelWps() cannot thrown ObjectDisposedException
=> [WiFi] Fix description of exception

src/Tizen.System.Feedback/Feedback/Feedback.cs, src/Tizen.System/Device/Haptic.cs
Signed-off-by: pr.jung <pr.jung@samsung.com>
Add new vibration feature : http://tizen.org/feature/feedback.vibration
- N/A
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-153
Create NotSupportedException when vibration feature is not supported.
=> [Feedback][Device][Add new vibration feature]

src/Tizen.NUI/src/internal/ManualPINVOKE.cs, src/Tizen.NUI/src/public/InputMethodContext.cs
Add PredictionAllow Api For InputMethodContext.
None
http://suprem.sec.samsung.net/jira/browse/TCSACR-152
None
=> [NUI] Add AllowTextPrediction/IsTextPredictionAllowed Api For InputMethodContext

src/Tizen.NUI/src/internal/ManualPINVOKE.cs, src/Tizen.NUI/src/public/Window.cs
- Added SetKeyboardRepeatInfo / GetKeyboardRepeatInfo to Window class
N/A
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-152
Added:
bool Window.SetKeyboardRepeatInfo(double rate, double delay)
bool Window.GetKeyboardRepeatInfo(out double rate, out double delay)
N/A
=> [NUI] Add KeyboardRepeatInfo APIs to Window

src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetwork.cs
Methods which have no parameter cannot throw ArgumentException
=> [WiFi] Remove ArgumentException (2)

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
- ACR: 
Added:
- bool Replaygain { set; get; } // Property
=> [MediaPlayer] add API to set/get replaygain

src/Tizen.NUI/src/internal/Application.cs, src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs, src/Tizen.NUI/src/internal/XamlBinding/Application.cs, src/Tizen.NUI/src/internal/XamlBinding/ResourcesExtensions.cs, src/Tizen.NUI/src/internal/XamlBinding/StyleSheets/StyleSheetExtensions.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs, src/Tizen.NUI/src/public/XamlBinding/IResourcesProvider.cs
=> [NUI] Modify Resources to XamlResources

src/Tizen.NUI/src/public/NUIApplication.cs
[NUI] Add window size/position setting into NUIApplication constructor
N/A
ACR will be done.
Added:
1) public NUIApplication(Size2D windowSize, Position2D windowPosition)
2) public NUIApplication(string styleSheet, Size2D windowSize, Position2D windowPosition)
3) public NUIApplication(string styleSheet, WindowMode windowMode, Size2D windowSize, Position2D windowPosition)
N/A
=> [NUI] Add window size/position setting into NUIApplication constructor

src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiEap.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiEapConfiguration.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetwork.cs
Methods which have no parameter cannot throw ArgumentException.
Therefore ArgumentException description of those APIs need to be removed.
TCSACR-155
http://suprem.sec.samsung.net/jira/browse/TCSACR-155
=> [WiFi][TCSACR-155] Remove ArgumentException descriptions

src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Fix NUI nested layout issue

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/SphericalVideo.cs
- ACR: 
http://suprem.sec.samsung.net/jira/browse/TCSACR-158
Added:
- public void SetZoomWithFieldOfView(float level, FieldOfView fieldOfView) //Method
Changed:
- the description of APIs
=> [MediaPlayer] add API to set zoom with field of view for spherical video

src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationReplyAction.cs
Dispose unused handle
Bugs Fixed
Handle leak
Behavioral Changes
Dispose unused handle
=> Fix handle leak

src/Tizen.Applications.Common/Interop/Interop.Libraries.cs, src/Tizen.Applications.Common/Interop/Interop.RPCPort.cs, src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Exceptions.cs, src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs, src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Port.cs, src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs, src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
- ACR: 
Added:
- public class Parcel
- public class Port
- public class ProxyBase
- public class StubBase
- public class InvalidIOException
- public class InvalidIDException
- public class PermissionDeniedException
- public class InvalidProtocolException
- public class NotConnectedSocketException
- public class InvalidCallbackException
Changed:
=> [Appfw] Add APIs for RPC

src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
Add asynchronous API for forgetting access point.
=> [Wifi] [TCSACR-160] Add ForgetAPAsync

src/Tizen.Uix.InputMethod/Interop/Interop.InputMethod.cs, src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Add a new API to hide the IME.
Bugs Fixed
N/A
API Changes
ACR : http://suprem.sec.samsung.net/jira/browse/TCSACR-161
=> [Inputmethod][TCSACR-161] Add API to hide IME

src/Tizen.Uix.InputMethod/Interop/Interop.InputMethod.cs, src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Sets the floating mode and moves the input panel on floating mode.
Bugs Fixed
N/A
API Changes
ACR : http://suprem.sec.samsung.net/jira/browse/TCSACR-163
=> [Inputmethod][TCSACR-163] Add APIs for floating keyboard

src/ElmSharp/ElmSharp/Entry.cs
Fix the description of API `Entry.DisableSelection(bool disable)`
N/A
N/A
N/A
=> [ElmSharp] Fix description of API

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.ErrorHandler.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerDisplaySettings.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerTrackInfo.cs, src/Tizen.Multimedia.MediaPlayer/Player/StreamInfo.cs
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-164
Added:
- public async Task SetPlayPositionAsyncNanos(long position, bool accurate)
- public long GetPlayPositionNanos()
- public long GetDurationNanos()
=> [MediaPlayer] add API about playback time to set/get in nonoseconds

pkg/Tizen.NET.nuspec
Bump Tizen.NET.API4 to version 4.0.1.14146
=> [Build] Rollup Tizen.NET.API4

src/Tizen.System.Storage/Interop/Interop.Storage.cs, src/Tizen.System.Storage/Storage/Storage.cs
Signed-off-by: pr.jung <pr.jung@samsung.com>
Get DeviceType using StorageGetTypeDev(storage_get_type_dev)
N/A
N/A
Get DeviceType using StorageGetTypeDev
=> [Storage][Get DeviceType using StorageGetTypeDev]

src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
- ACR: 
Modified:
- added PLAYING state at precondition of Start() for resuming during buffering.
- modified the param description of PlayerBufferingTime not to be confused with player state.
=> [MediaPlayer] modify the precondition of Start method

src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
Signed-off-by: Junghoon Park <jh9216.park@samsung.com>
Fixed a bug
- Wrong API was used
=> [Tizen.Applications.Common] [RPCPort] Fix a bug about calling wrong native API

src/Tizen.System.Storage/Storage/Storage.cs
Signed-off-by: pr.jung <pr.jung@samsung.com>
Deprecate AvaliableSpace property and add AvailableSpace property.
N/A
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-166
Deprecate AvaliableSpace property and add AvailableSpace property.
=> Add AvailableSpace property and deprecate AvaliableSpace

src/Tizen.NUI/src/public/BaseComponents/View.cs
This reverts commit 46a9f168184028f9bdff0fec79006b39f3cb1e88.
=> Revert "[NUI] NUI Integration (#361)"

src/ElmSharp/ElmSharp/EvasImage.cs
Add new API(`Save`) in EvasImage class
None
Added:
- void EvasImage.Save(string file, string key, string flags)
None
=> [ElmSharp] Add Save method in EvasImage

src/Tizen.Network.Connection/Interop/Interop.Libraries.cs, src/Tizen.Network.Connection/Tizen.Network.Connection/IAddressInformation.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAddressInformation.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiErrorFactory.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Remove duplicate codes and replace them with a method.
Fix typo
=> [Connection][WiFi] Remove duplicate codes

src/Tizen.System.Storage/Storage/Storage.cs
Fix wrong api version
N/A
- ACR: N/A
N/A
=> [Storage][Fix api version]

src/Tizen.Content.Download/Tizen.Content.Download/DownloadErrorFactory.cs, src/Tizen.Content.Download/Tizen.Content.Download/Notification.cs, src/Tizen.Content.Download/Tizen.Content.Download/Request.cs
Fix issues detected by codacy
N/A
N/A
=> Fix issues detected by codacy

src/Tizen.System/Device/Display.cs, src/Tizen.System/Device/Power.cs, src/Tizen.System/Interop/Interop.Device.cs
- Add set function for State property in Display class
- Add PowerLock enumeration in Power class
- Add RequestLock and ReleaseLock in Power class
- Deprecate RequestCpuLock and ReleaseCpuLock in Power class
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-168
- Add set function for State property in Display class
- Add PowerLock enumeration in Power class
- Add RequestLock and ReleaseLock in Power class
- Deprecate RequestCpuLock and ReleaseCpuLock in Power class
=> [Device]Add new apis

src/Tizen.System/Device/Power.cs
Deprecate RequestCpuLock and ReleaseCpuLock
N/A
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-170
Deprecate RequestCpuLock and ReleaseCpuLock
=> [Device][Deprecate RequestCpuLock and ReleaseCpuLock]

src/Tizen.NUI/src/internal/ManualPINVOKE.cs, src/Tizen.NUI/src/public/FontClient.cs
=> [NUI] Support software styling

src/ElmSharp/ElmSharp/Window.cs, src/ElmSharp/Interop/Interop.Eutil.WindowProperty.cs, src/ElmSharp/Interop/Interop.Libraries.cs, test/ElmSharp.Test/TC/WindowUtilTest.cs, test/ElmSharp.Test/tizen-manifest.xml
Add new APIs for efl-util window property APIs in ElmSharp
None
Added:
- NotificationLevel Window.NotificationLevel { get; set; } // Property
- ScreenMode Window.ScreenMode { get; set; } // Property
- int Window.Brightness { get; set; } // Property
- void Window.SetOpaqueState();
- void Window.UnsetOpaqueState();
None
=> [ElmSharp] Add efl_util window property APIs in ElmSharp

src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Consumer.cs
Fix wrong intprt check
- N/A
- N/A
- N/A
=> [Tizen.Applications.DataControl] Fix wrong intprt check

src/ElmSharp/ElmSharp/AccessibleObject.cs, src/ElmSharp/ElmSharp/Background.cs, src/ElmSharp/ElmSharp/Calendar.cs, src/ElmSharp/ElmSharp/Color.cs, src/ElmSharp/ElmSharp/ColorSelector.cs, src/ElmSharp/ElmSharp/Container.cs, src/ElmSharp/ElmSharp/EdjeObject.cs, src/ElmSharp/ElmSharp/FlipSelector.cs, src/ElmSharp/ElmSharp/GenGrid.cs, src/ElmSharp/ElmSharp/GenList.cs, src/ElmSharp/ElmSharp/Hoversel.cs, src/ElmSharp/ElmSharp/Index.cs, src/ElmSharp/ElmSharp/ItemObject.cs, src/ElmSharp/ElmSharp/MultiButtonEntry.cs, src/ElmSharp/ElmSharp/NamedHint.cs, src/ElmSharp/ElmSharp/Naviframe.cs, src/ElmSharp/ElmSharp/Toolbar.cs, src/ElmSharp/ElmSharp/Transit.cs, src/ElmSharp/Interop/Interop.Ecore.cs, src/ElmSharp/Interop/Interop.Elementary.Bg.cs, src/ElmSharp/Interop/Interop.Elementary.Image.cs, src/ElmSharp/Interop/Interop.Libdl.cs
Clean-up code to fix issues detected by codacy.
=> [ElmSharp] Cleanup code of ElmSharp

src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
Signed-off-by: Junghoon Park <jh9216.park@samsung.com>
- Add exception handler for constructor of class Parcel
=> Add exception handler for rpc-port-parcel

src/Tizen.NUI/src/public/BaseComponents/View.cs
[NUI] Gallery App button position issue
N/A
N/A
N/A
=> [NUI] Gallery App button position issue

src/Tizen.Multimedia/AudioManager/AudioDevice.cs, src/Tizen.Multimedia/AudioManager/AudioDeviceRunningChangedEventArgs.cs, src/Tizen.Multimedia/AudioManager/AudioDeviceStateChangedEventArgs.cs, src/Tizen.Multimedia/AudioManager/AudioManager.cs, src/Tizen.Multimedia/Interop/Interop.Device.cs
Added new APIs for device running state
- TCSACR-175
(It's related native ACR-1147.)
Added:
- public bool IsRunning
- public static event EventHandler DeviceRunningChanged
Deprecated:
- public AudioDeviceState State
- public static event EventHandler DeviceStateChanged
=> [AudioManager] Add new APIs for device running changed event

src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs, src/Tizen.NUI/src/public/NUIApplication.cs
[NUI] Make vulkan constructor as InhouseAPI, Fix Codacy errors
N/A
N/A
N/A
=> [NUI] Make vulkan constructor as InhouseAPI, Fix Codacy errors

src/Tizen.Multimedia/AudioManager/AudioDevice.cs
Content of ToString() of AudioDevice class is changed.
(new value of IsRunning is applied)
=> [AudioManager] Revise ToString() of AudioDevice class

src/Tizen.System/Device/Power.cs
Remove unused exception
N/A
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-168
N/A
=> [Device][Remove unused exception]

src/Tizen.Multimedia.Camera/Camera/CameraEnums.cs, src/Tizen.Multimedia.Camera/Camera/CameraException.cs, src/Tizen.Multimedia.Camera/Camera/DepthPlane.cs, src/Tizen.Multimedia.Camera/Camera/PreviewFrame.cs, src/Tizen.Multimedia.Camera/Interop/Interop.Camera.cs
Added new camera preview format and type.
- TCSACR-173
(It's related to native ACR-1279.)
Added:
- CameraPixelFormat.Invz  // enum
- PlaneType.DepthPlane    // enum
- DepthPlane                     // class
=> [Camera] Add new preview data format and type

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Container.cs, src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/Window.cs, test/NUITestSample/NUITestSample/examples/RaiseToTopTest.cs
[NUI] Fix RaiseToTop error
N/A
N/A
N/A
=> [NUI] Fix RaiseToTop error

src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs, src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs
Remove the unused resource-change callback.
Fix CSFS memory leak problem
N/A
N/A
=> [NUI] Remove the unused resource-change callback.

src/Tizen.Applications.Common/Interop/Interop.Glib.cs, src/Tizen.Applications.Common/Tizen.Applications/TizenSynchronizationContext.cs
- The native source should be removed before GC
=> [Tizen.Applications] Add finalizer in TizenSyncronizationContext

src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfoFilter.cs
Did language review, in line 44, 50, 56, 
Changed: "This values means" to  "This values indicates"
**Question:**
In Line 38, can we rephrase the sentence as:
This class defines the possible values to use in the InstalledApplicationFilter.
-NA
-NA
-NA
=> English review for ApplicationInfoFilter.cs

src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfo.cs
Change-Id: I103570f02ec843bb2d78f3828aeef3f1c97e79fc
Signed-off-by: Semun Lee <semun.lee@samsung.com>
Add description of shared/data policy.
=> Add description of shared/data policy

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Container.cs, src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/Window.cs, test/NUITestSample/NUITestSample/examples/RaiseToTopTest.cs
=> [NUI] Fix raise top issue

src/Tizen.System.Storage/Storage/Storage.cs, src/Tizen.System.Storage/Storage/StorageArea.cs, src/Tizen.System.Storage/Storage/StorageDevice.cs, src/Tizen.System.Storage/Storage/StorageManager.cs
**Storage.cs**
Line 194:  /// The StorageDevice 
Can this be elaborated further to provide more info?
Line 220 to 225:
if (!information_set) 
{ 
Log.Error(LogTag, string.Format("Doesn't know fstype.")); 
throw new InvalidOperationException("Doesn't know type of file system"); 
} 
return _fstype;
Question: 
Can we edit line number 222 to "Does not know the fstype"
Can we edit line number 223 to "Does not know the type of file system"
Line 248  /// Information whether this is a primary partition.
Can this be elaborated further for clarity?
- NA
- NA
- NA
=> Review of Storage

src/Tizen.Multimedia/AudioManager/AudioManager.cs
In Audio manager:
Have made changes in lines: 230-235.
Please review the rephrase and check whether the meaning of the content is not changed.
- NA
- NA
- NA
=> English review

src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Exceptions.cs, src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs, src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Port.cs, src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs, src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
Minor grammar changes done.
**Exception.cs:**
Question:
Line 46:
The exception occurs, if a socket is not connected or when a non connected socket is used.
**Parcel.cs**
Minor grammar changes done according to Native API reference.
Question:
1.  Can we use <c></c> tags to emphasize data types instead of ' '?
For example,
/// Writes a 'byte' value into parcel object.
**StubBase.cs**
Question:
Line 89:
Whether stub allows only trusted proxy or not.
Can we rephrase as:
If stub allows only trusted proxy then <c>true</c>, <c>false</c> otherwise .
Or do we mention 'true' or 'false' only for return values.
-NA
-NA
-NA
=> English review for RPCPort

src/Tizen.System/Device/Power.cs
Minor grammar modifications.
- NA
- NA
- NA
=> Review of power.cs

src/Tizen.System.Usb/Usb/UsbInterface.cs
Minor grammar changes done.
- NA
- NA
- NA
=> English Review UsbInterface.cs

src/Tizen.Applications.Common/Tizen.Applications/TizenSynchronizationContext.cs
Signed-off-by: Junghoon Park <jh9216.park@samsung.com>
- Revert TizenSynchronizationContext.cs
=> [Tizen.Applications.Common] Revert TizenSynchronizationContext.cs

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/TableView.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs
Minor language changes.
Have few questions:
**File: BaseComponents/TableView.cs**
1.	Should this be removed or shall we review the following:
/// This will be public opened in tizen_5.0 after ACR done. Before ACR, need to be hidden as inhouse API.
2.	Line 499 to 502:
Missing Missing /// <since_tizen> <version> </since_tizen> tag.
**File: TextLabel.cs**
1.	Line: 1239
/// The vertical line alignment of the text.File: ImageView.cs
This description is not clear, can we say:
The vertical alignment of the text.
**File: TextField.cs**
1.	Line 2299
Should this be removed or shall we review the following:
/// This will be released at Tizen.NET API Level 5, so currently this would be used as inhouse API.
**File: View.cs**
1.	Line 1250
/// Added child View at moment.
Can the summary be further …
=> English Review: NUI_BaseComponents

src/Tizen.NUI/src/public/BaseHandle.cs, src/Tizen.NUI/src/public/FontClient.cs, src/Tizen.NUI/src/public/ImageLoading.cs, src/Tizen.NUI/src/public/ImfManager.cs, src/Tizen.NUI/src/public/InputMethodContext.cs, src/Tizen.NUI/src/public/LongPressGestureDetector.cs, src/Tizen.NUI/src/public/NUIApplication.cs, src/Tizen.NUI/src/public/NUIConstants.cs, src/Tizen.NUI/src/public/PanGestureDetector.cs, src/Tizen.NUI/src/public/PinchGestureDetector.cs, src/Tizen.NUI/src/public/PixelBuffer.cs, src/Tizen.NUI/src/public/PixelData.cs, src/Tizen.NUI/src/public/Property.cs, src/Tizen.NUI/src/public/StyleManager.cs, src/Tizen.NUI/src/public/TapGestureDetector.cs, src/Tizen.NUI/src/public/Touch.cs, src/Tizen.NUI/src/public/VisualMaps.cs, src/Tizen.NUI/src/public/Window.cs
As there are 18 files under Tizen.NUI/src/public, the comments and questions are given in the Comments section.
- Not Applicable
Not Applicable
Not Applicable
=> English Review: NUI public files

test/NUITestSample/NUITVSample/AnimationSample/src/AnimationSample.cs, test/NUITestSample/NUITVSample/FlexContainerSample/src/Devices.cs, test/NUITestSample/NUITVSample/UIControlSample/src/IExample.cs, test/NUITestSample/NUITVSample/UIControlSample/src/MainSample.cs
=> [DevelNUI]

src/Tizen.Multimedia.AudioIO/AudioIO/AudioCapture.cs, src/Tizen.Multimedia.AudioIO/AudioIO/AudioIOEnums.cs, src/Tizen.Multimedia.AudioIO/AudioIO/AudioPlayback.cs
Add new sample type for signed 24bit types.
Change maximum sample rate (48000Hz -> 192000Hz).
- TCSACR-178
=> [AudioIO] Add new sample type and change maximum sample rate

src/Tizen.Multimedia/AudioManager/AudioDevice.cs, src/Tizen.Multimedia/AudioManager/AudioDeviceOptions.cs, src/Tizen.Multimedia/AudioManager/AudioDeviceState.cs
Deprecate Deprecate device state enums
TCSACR-177
Deprecated enums:
- AudioDeviceState
- AudioDeviceOptions.Deactivated
- AudioDeviceOptions.Activated
=> [AudioManager] Deprecate device state enums

src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs
[NUI] Fix SVACE issue
http://suprem.sec.samsung.net/svace_tizen/page/review#PRJID=46&WGID=358074
N/A
N/A
=> [NUI] Fix SVACE issue

build.sh, build/build.proj, build/common.props
Add a property to enable NETCore.Analyzer.
Usages:
./build.sh build [module] /p:BuildWithAnalyzer=True
./build.sh full /p:BuildWithAnalyzer=True
=> [Build] Add BuildWithAnalyzer property

src/Tizen.NUI/src/public/BaseComponents/View.cs
- NUI Margin property is supported by NUI Layout system. So, added a description to Margin property.
- N/A
- N/A
- If the user wants to use Margin property, then user should Set Layout to View.
=> [NUI] Add a note to Margin property

src/Tizen.Applications.MessagePort/Tizen.Applications.Messages/RemotePort.cs
[Tizen.Applications.MessagePort] 
Change how to remove registration callback
=> [Tizen.Applications.MessagePort] Change how to remove registration callback

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Size.cs
[NUI] Make Size and NaturalSize as public API
for your reference =>
http://suprem.sec.samsung.net/confluence/display/GFX/Tizen+5.0+NUI+Inhouse+API+list
N/A
http://suprem.sec.samsung.net/jira/browse/TCSACR-179
N/A
=> [NUI] Make Size and NaturalSize as public API

src/Tizen.NUI/src/public/VisualMaps.cs
[NUI] Add getter property for VisualFittingMode
Change-Id: I1ee389dd4a84f153e4a5d063fe3331a9525757eb
N/A
http://suprem.sec.samsung.net/jira/browse/TCSACR-181
N/A
=> [NUI] Add getter property for VisualFittingMode

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/ScaleRectangle.cs
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-183
Added:
- public struct ScaleRectangle
- public void SetVideoRoi(ScaleRectangle scaleRectangle)
- public ScaleRectangle GetVideoRoi()
=> [MediaPlayer] add new API to set/get the video roi area

src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Minor language modifications.
Question:
In line number: 2093 to 2091
For the sentence:
If the floating mode is deactivated, calling this function has no effect.
Are we referring to the SetFloatingMode method here? If yes, can we rephrase to:
If the floating mode is set to off, calling this function has no effect.
- Not applicable
Not applicable
Not applicable
=> English review: InputMethodEditor

src/Tizen.Uix.InputMethodManager/Tizen.Uix.InputMethodManager/InputMethodManager.cs
Minor language
- Not applicable
Not applicable
Not applicable
=> English review: InputMethodManager

src/ElmSharp/ElmSharp/InputGenerator.cs, src/ElmSharp/Interop/Interop.Eutil.InputGenerator.cs
Add new APIs for efl-util input generator APIs in ElmSharp
None
Added:
- void InputGenerator.GenerateKeyEvent(string key, int pressed);
- void InputGenerator.GenerateMouseEvent(int buttons, InputPointerType type, int x, int y)
- void InputGenerator.GenerateTouchEvent(int index, InputTouchType type, int x, int y)
None
=> [ElmSharp] Add efl_util input generator APIs in ElmSharp

src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs, src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
Minor grammar modifications.
- NA
- NA
- NA
=> Review of SystemSettings

src/Tizen.Multimedia.Camera/Camera/CameraEnums.cs, src/Tizen.Multimedia.Camera/Camera/PreviewFrame.cs, src/Tizen.Multimedia.Camera/Camera/RgbPlane.cs, src/Tizen.Multimedia.Camera/Interop/Interop.Camera.cs
Add new preview plane for RGB format.
- TCSACR-185
List of API changes
[classes]
RgbPlane
[Added] public byte[] Data { get; }
[enums]
PlaneType
[Added] RgbPlane
=> [Camera] Add new preview format - RGB

src/Tizen.NUI/src/internal/Layouting/LayoutPINVOKE.cs, src/Tizen.NUI/src/internal/Layouting/LinearLayout.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs
Change-Id: I0ed3010fd27f8f4cb26126efc5547a301c69cf38
- Add LinearLayout Alignment and Weight properties
- N/A
- This will be public opened in tizen_5.0 after ACR done. Before ACR, need to be hidden as inhouse API.
- Add LinearLayout Alignment and Weight.
=> [NUI] Add LinearLayout Alignment and Weight

src/ElmSharp/ElmSharp/Point.cs, src/ElmSharp/ElmSharp/Point3D.cs, src/ElmSharp/ElmSharp/Rect.cs, src/ElmSharp/ElmSharp/Size.cs
Fix documentaion errata in ElmSharp
=> [ElmSharp] Fix document errata

tools/scripts/CodeChecker/main.py
Update warning message on CodeChecker to include the warning code
- N/A
- N/A
- N/A
=> [Tools] Update warning message on CodeChecker

tools/scripts/CodeChecker/PRManager.py
Add exception handling which occurs when the file patch type is `None`.
- N/A
- N/A
- N/A
=> [Tools] Update code checker

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/Window.cs
[NUI] Fix RenderingBehavior issue 
[NUI] Support Resource path when using xaml
N/A
N/A
N/A
=> [NUI] Fix RenderingBehavior issue, Support Resource path when using xaml

src/Tizen.NUI/src/internal/NDalicPINVOKE.cs, src/Tizen.NUI/src/internal/WebView.cs, src/Tizen.NUI/src/internal/WebViewSignal.cs
=> [NUI] Add WebView APIs

pkg/PlatformFileList.txt
Add Nlp feature dll into TizenFx platform
None
None
=> [Nlp] Add Nlp feature dll into platform binary

src/Tizen.NUI/src/public/Animation.cs, src/Tizen.NUI/src/public/BaseComponents/TableView.cs, src/Tizen.NUI/src/public/NUIApplication.cs
[NUI] Public some apis of TableView,Animation,NUIApplication
Change-Id: I280e6389cb9d2aa537d72c183b1547ee807fcfd6
N/A
http://suprem.sec.samsung.net/jira/browse/TCSACR-144
N/A
=> [NUI] Public some apis of TableView,Animation,NUIApplication

src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Consumer.cs
Use Mutex lock for thread safety
N/A
N/A
N/A
=> [Tizen.Applications.DataControl] Use Mutex lock for thread safety

src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerPlaylist.cs, src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlCommand.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlEnums.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlPlaylist.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlSearchCondition.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.Events.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControllerManager.Events.cs
Add APIs to create playlist
- TCSACR-188
=> [MediaController] Add APIs to create playlist

src/Tizen.NUI/src/public/NUIConstants.cs, src/Tizen.NUI/src/public/VisualMaps.cs
VisualMaps revising continue
Here are some changes:
public VisualFittingModeType VisualFittingMode
public bool Atlasing
public PropertyMap Shadow
public PropertyMap Underline
public PropertyMap Outline
public PropertyMap Background
public bool RenderIfTransparent
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-181
=> [NUI] VisualMaps revising continue

src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Add MediaPacket helper method.
=> [MediaPlayer] Add MediaPacket helper

src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
- There's a possibility of collecting callback by garbage collector.
=> [MultimediaUtil] Prevent collecting callback before it's called.

src/Tizen.Pims.Calendar/Interop/Interop.Filter.cs, src/Tizen.Pims.Calendar/Interop/Interop.Record.cs, src/Tizen.Pims.Calendar/Tizen.Pims.Calendar/CalendarFilter.cs, src/Tizen.Pims.Calendar/Tizen.Pims.Calendar/CalendarRecord.cs
Fix for local time difference in Tizen emulators.
=> [Pims.Calendar] Fix for local time difference in Tizen emulators

src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs, src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Fix lifetime of callback delegate
The callback delegate which is passed to unmanaged code can be
garbage-collected before invoked. So we need to save delegate
in managed code until invoked.
None
None
=> [Packagemanager] Fix lifetime of callback delegate

src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut/ShortcutManager.cs, src/Tizen.Applications.Shortcut/interop/Interop.Shortcut.cs
- use sync api
Change the native API to sync.
shortcut_add_to_home -> shortcut_add_to_home_sync
shortcut_add_to_home_widget -> shortcut_add_to_home_widget_sync
shortcut_remove_from_home -> shortcut_remove_from_home_sync
Bugs Fixed
•Crash occured when native code is abnormal.
There was a problem with DotNet_TCT.
=> [Shortcut] Update add, delete func

build/GlobalSuppressions.cs, build/analyzers.props, packaging/csapi-tizenfx.spec, packaging/csapi-tizenfx.spec.in, packaging/makespec.sh, packaging/version.txt
Cleanup build and packaging files.
=> [Build] Cleanup build and packaging files

src/ElmSharp/ElmSharp/Window.cs
=> [ElmSharp] Fix typo

src/Tizen.NUI/src/internal/NDalicPINVOKE.cs, src/Tizen.NUI/src/public/ImageLoading.cs
[NUI] Remove APIs which should not be public-opened
N/A
These were InhouseAPIs, so no need ACR
N/A
=> [NUI] Remove APIs which should not be public-opened

src/Tizen.NUI/src/NUI-added-for-ubuntu-this-should-be-removed-after-tizen-stub-is-fixed/NUIApplication.cs
=> [DevelNUI] Add application Dispose

src/Tizen.NUI/src/public/Widget.cs
Just remove an incorrect line in the license section.
=> [NUI] Remove an incorrect comment in the license.

src/Tizen.NUI/src/internal/EnvironmentVariable.cs, src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
=> [WIP][NUI] Add EnvironmentVariable interface (internal API)

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
[NUI] Fix to make null assigning to ResourceUrl possible
N/A
=> [NUI] Fix to make null assigning to ResourceUrl possible

src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Fix VD CSFS crash issue

src/Tizen.NUI/src/internal/Layouting/LayoutGroup.cs, src/Tizen.NUI/src/internal/Layouting/LayoutItem.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/PinchGesture.cs, src/Tizen.NUI/src/public/ScrollViewPagePathEffect.cs, src/Tizen.NUI/src/public/TypeRegistry.cs, src/Tizen.NUI/src/public/UIComponents/ScrollBar.cs
[NUI] Sync dalihub/TizenFX and Samsung/TizenFX
=> [NUI] Sync dalihub/TizenFX and Samsung/TizenFX

src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Fix SizeWidth/Height issue

src/Tizen.NUI/src/internal/Application.cs, src/Tizen.NUI/src/internal/DisposeQueue.cs, src/Tizen.NUI/src/internal/NUICoreBackend.cs, src/Tizen.NUI/src/internal/WatchApplication.cs
=> [NUI] Remove using keyword

src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/ScanStateChangedEventArgs.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiEnumerations.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
[TCSACR-192] Add new API to check wifi scan state
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-192
=> [Tizen.Network.WiFi][TCSACR-192] Add new API to check wifi scan state

src/Tizen.NUI/src/internal/Application.cs, src/Tizen.NUI/src/internal/NUICoreBackend.cs
=> [NUI] Fix e.Application null issue

src/Tizen.Applications.DataControl/Interop/Interop.DataControl.cs, src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Provider.cs
[Tizen.Applications.DataControl] Fix the issue for native handle
N/A
=> [Tizen.Applications.DataControl] Fix the issue for native handle

src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
The 'disposing' parameter of Dispose() virtual method is also
used for its implementation according to the common usage.
=> [MediaPlayer] Apply GC.SuppressFinalize()

pkg/PlatformFileList.txt, src/Tizen.Nlp/Tizen.Nlp.csproj, src/Tizen.Nlp/Tizen.Nlp.sln, src/Tizen.Nlp/Tizen.Nlp/NaturalLanguageProcess.cs
- Add new nlp feature : http://tizen.org/feature/nlp
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-193
- Create NotSupportedException when nlp feature is not supported.
=> [NLP] Add new nlp feature

src/Tizen.NUI/src/internal/Application.cs, src/Tizen.NUI/src/internal/NUICoreBackend.cs
[NUI] Remove version check, temporary workaround for VK app crash issue
N/A
=> [NUI] Remove version check, temporary workaround for VK app crash issue

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, test/NUITestSample/NUITestSample/examples/ImageViewResourceUrlSetNullTest.cs
This reverts commit 66ae1948186c30b4131116ebc664e7b59b1f78b6.
Revert "[NUI] Fix to make null assigning to ResourceUrl possible (#538)"
- need to keep the behavior with previous version of API
- comment added to make clear the null-setting
N/A
=> Revert "[NUI] Fix to make null assigning to ResourceUrl possible (#538)"

src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
This patch is to restrict concurrent access.
- ACR: N/A
=> [Tizen.Applications.Common] Restrict concurrent access

src/Tizen.Multimedia/Interop/Interop.MediaTool.cs, src/Tizen.Multimedia/MediaTool/MediaPacket.cs, src/Tizen.Multimedia/MediaTool/VideoMediaFormat.cs
Add Duration and MaxBps
- TCSACR-191
=> [MediaTool] Add duration and maxBps

src/Tizen.NUI/src/internal/NUICoreBackend.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Fix layout issue

src/Tizen.Applications.WidgetControl/Interop/Interop.WidgetService.cs, src/Tizen.Applications.WidgetControl/Tizen.Applications/WidgetControl.cs
Add MainAppId, PackageId properties and modify required feature
- ACR: TCSACR-202
Added:
- string MainAppId {get;} // Property
- string PackageId {get;} // Property
Modified:
Required feature is added.
+ IsNoDisplay : bool <<readonly>>
feature: N/A --> feature: http://tizen.org/feature/shell.appwidget
+ CreateAll(pkgId) : WidgetControl[]
feature: N/A --> feature: http://tizen.org/feature/shell.appwidget 
+ GetWidgetIds(pkgId) : string[]
feature: N/A --> feature: http://tizen.org/feature/shell.appwidget 
+ GetIconPath(lang) : string
feature: N/A --> feature: http://tizen.org/feature/shell.appwidget 
+ GetInstances() : IEnumerable<WidgetControl.Instance>
feature: N/A --> feature: http://tizen.org/feature/shell.appwidget 
+ GetName(lang) : string
feature: N/A --> feature: …
=> [WidgetControl] Add MainAppId, PackageId properties and modify required feature

src/Tizen.NUI/src/internal/EnvironmentVariable.cs, src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
=> [NUI] Add EnvironmentVariable interface (internal API) (#533)

src/Tizen.Multimedia/MediaTool/VideoMediaFormat.cs
Add ctor for VideoMediaFormat
- TCSACR-199
=> [MediaTool] Add ctor for VideoMediaFormat

src/Tizen.Applications.Common/Interop/Interop.AppControl.cs, src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs, src/Tizen.Applications.Common/Tizen.Applications/AppControlResult.cs
Add a new method to support launch request API asynchronoulsy
- ACR: TCSACR-198
Added:
- Task<AppControlResult> AppControl.SendLaunchRequestAsync(AppControl launchRequest, AppControlReplyCallback replyAfterLaunching);
- AppControlResult // enumeration
=> [Tizen.Applications.Common] Add SendLaunchRequestAsync Method

src/Tizen.Applications.WidgetApplication/Tizen.Applications/WidgetBase.cs
Modify WidgetBase internal Id memeber to property.
Support widget_app_get_id.
Changed: TCSACR-200
intertnal string id => string attribute
=> [WidgeApplication] Modify WidgetBase internal Id memeber to property

src/Tizen.Applications.UI/Interop/Interop.Application.cs, src/Tizen.Applications.UI/Tizen.Applications/CoreUIApplication.cs
Add missing APIs
app_get_device_orientation
API Changes
ACR: TCSACR-194
DeviceOrientation CurrentDeviceOrientation {get;} // Property
=> [Application] Add CurrentDeviceOrientation property on CoreUIApplication

src/Tizen.Applications.UI/Interop/Interop.Application.cs, src/Tizen.Applications.UI/Tizen.Applications/CoreUIApplication.cs
=> Revert "[Application] Add CurrentDeviceOrientation property on CoreUIApplication"

src/Tizen.Applications.UI/Interop/Interop.Application.cs, src/Tizen.Applications.UI/Tizen.Applications/CoreUIApplication.cs
Add device orientation property
app_get_device_orientation
API Changes
ACR: TCSACR-194
DeviceOrientation CurrentDeviceOrientation {get;} // Property
=> [Application] Add device orientation property

src/Tizen.NUI/src/internal/NUICoreBackend.cs
revert workaround for vulkan
- remove temporary fix of vulkan app crash
None
=> [NUI] revert workaround for vulkan

src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs, src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs
Signed-off-by: sooyeon.kim <sooyeon.kim@samsung.com>
Fix desctructor to call dispose in STT/TTS
=> [STT/TTS] Fix desctructor to call dispose

src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
Use ConfigureAwait(false) when await a Task
Prevent unwanted deadlock issue.
N/A
=> [Application] Use ConfigureAwait(false) when await a Task

src/Tizen.Uix.InputMethod/Interop/Interop.InputMethod.cs, src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/EditorWindow.cs, src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
- Add new API to update input panel event
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-195
=> Add new APIs to update input panel event

docs/api/index.md, src/Tizen.Applications.WatchfaceComplication/doc/api/Tizen.Applications.WatchfaceComplication.md
Add Tizen.Applications.WatchfaceComplication namespace to the documentation index page.
None
=> [doc] Add WatchfaceComplication to the doc index

src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
- Fix the crash issue when marshalling Intptr with a string
=> Fix the crash issue when marshalling Intptr with a string

src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcManager.cs
=> [NFC] fix typo

src/Tizen.Multimedia.MediaPlayer/Player/Player.Events.cs, src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerClient.cs, src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.Events.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Replace native api with new one for PlaybackCommand.
=> [MediaController] Replace native api with new one

src/Tizen.NUI/src/internal/Application.cs, src/Tizen.NUI/src/internal/DisposeQueue.cs, src/Tizen.NUI/src/internal/Layouting/LayoutGroup.cs, src/Tizen.NUI/src/internal/NDalicPINVOKE.cs, src/Tizen.NUI/src/internal/NUICoreBackend.cs, src/Tizen.NUI/src/internal/WatchApplication.cs, src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticExtension.cs, src/Tizen.NUI/src/internal/XamlBinding/Binding.cs, src/Tizen.NUI/src/internal/XamlBinding/SynchronizedList.cs, src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Window.cs
=> [NUI] Sync with API5

src/ElmSharp/ElmSharp/EvasObject.cs
Fix crash issue for GetTextBlockGeometryByLineNumber()
=> [ElmSharp] Fix crash issue for GetTextBlockGeometryByLineNumber()

src/ElmSharp/ElmSharp/Elementary.cs, src/ElmSharp/ElmSharp/EvasObject.cs, test/ElmSharp.Test/TestRunner.cs
Add new property and events for ElmSharp app UI automation test
Added:
public string EvasObject.AutomationId { get; set; } // Property
public event EventHandler Elementary.EvasObjectRealized // Event
public event EventHandler EvasObject.Shown // Event
public event EventHandler EvasObject.Hidden // Event
=> [ElmSharp] Add new APIs for automation test

src/Tizen.Applications.Alarm/Interop/Interop.Alarm.cs, src/Tizen.Applications.Alarm/Tizen.Applications/Alarm.cs
Add property setter for WeekFlag, Period, ScheduledDate
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-206
=> [Alarm] Add property setter for WeekFlag, Period, ScheduledDate

src/Tizen.NUI/src/internal/ManualPINVOKE.cs, src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
Change-Id: I5af8ba898cd8ad3a609fbc737d794c4593a7da08
=> [NUI] Add C# binding for MatchSystemLanguageDirection

src/Tizen.Multimedia.MediaPlayer/Player/DownloadProgress.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs
Add descriptions for preparing state
=> [MediaPlayer] Add descriptions for preparing state

src/Tizen.NUI/src/internal/NDalicPINVOKE.cs, src/Tizen.NUI/src/internal/VersionCheck.cs, src/Tizen.NUI/src/public/NUIApplication.cs
[NUI] Workaround of Vulkan backend csfs crash issue
None
=> [NUI] Workaround of Vulkan backend csfs crash issue

src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/Account.cs, src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/AccountService.cs, src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/SafeAccountHandle.cs
Signed-off-by: Abhishek Vijay <abhishek.v@samsung.com>
Resource handling issues fixed for AccountManager. 
These fixes are with respect to following issues:
- fixes #67 
- fixes #68
- fixes #69
=> [AccountManager] Improving resource handling - Issues 67,68 & 69

src/Tizen.NUI/src/internal/Application.cs
=> [NUI] Remove version check

src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/EditorWindow.cs, src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
=> [Inputmethod] Fix API description

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs, src/Tizen.NUI/src/public/BaseComponents/TableView.cs, src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs, src/Tizen.NUI/src/public/BaseComponents/VideoView.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs
[NUI] Improve the performance when firstly create the View
=> [NUI] Improve the performance when firstly create the View

src/Tizen.Multimedia.Metadata/MetadataExtractor/Metadata.cs, src/Tizen.Multimedia.Metadata/MetadataExtractor/MetadataExtractorAttr.cs
Add `Composer` property and deprecate `Author` property
- TCSACR-209
=> [Metadata] Add new API and deprecate old one

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothOppImpl.cs
Fill the code to remove the event handler in OPP functionality
- ACR: N/A
=> Remove OPP Event handler (#645)

src/Tizen.Uix.InputMethod/Interop/Interop.InputMethod.cs, src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs, src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/MimeTypeUpdateRequestedEventArgs.cs, src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/PredictionHintDataUpdatedEventArgs.cs, src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/PredictionHintUpdatedEventArgs.cs
- Add missing APIs
- ACR: TCSACR-212
=> [Inputmethod][TCSACR-212] Add missing APIs

src/Tizen.NUI/src/internal/Application.cs, src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs, src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StyleSheetExtension.cs, src/Tizen.NUI/src/internal/Xaml/PruneIgnoredNodesVisitor.cs, src/Tizen.NUI/src/internal/Xaml/XamlParser.cs, src/Tizen.NUI/src/internal/XamlBinding/Application.cs, src/Tizen.NUI/src/internal/XamlBinding/ResourcesExtensions.cs, src/Tizen.NUI/src/public/Window.cs, src/Tizen.NUI/src/public/XamlBinding/ResourceDictionary.cs
Change-Id: I032ed4e562603441be4d26be68e29e0081e8c917
=> [NUI] Fix VD Svace issue

src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationButtonActionArgsBinder.cs, src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationReplyActionArgsBinder.cs
Fix Deref after as.instant issue
- ACR: Not necessary
=> [Notification] Fix Deref after as.instant issue

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapter.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudio.cs
[Bluetooth] Fix API document during ACR
=> [Bluetooth] Fix API document

src/Tizen.Applications.WatchApplication/Tizen.Applications.CoreBackend/WatchCoreBackend.cs, src/Tizen.Applications.WidgetApplication/Tizen.Applications.CoreBackend/WidgetCoreBackend.cs
- Set SynchronizationContext on WidgetCoreBackend Run
- Set SynchronizationContext on WatchCoreBackend Run
=> Fix SynchronizationContext issue

src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
IME does not need to consider multi-threading.
=> [InputMethod] Remove lock from InputMethodEditor

src/Tizen.Pims.Calendar/Tizen.Pims.Calendar/CalendarStructs.cs
=> [Calendar] Fix svace defect WGID#14567

README.md
=> Readme: Fix Travis Build Status badge

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
Add new API to destroy Gatt server
**API Changes**
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-216
=> [Bluetooth] Add new API to destroy Gatt server

packaging/PlatformFileList.txt
Signed-off-by: yeji kim <yeji01.kim@samsung.com>
- ACR: TCSACR-211
=> Add Tizen.Security.DevicePolicyManager.dll

src/Tizen.NUI/src/internal/AdaptorSignalType.cs, src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs, src/Tizen.NUI/src/internal/SWIGTYPE_p_bundle.cs, src/Tizen.NUI/src/internal/WidgetViewSignal.cs, src/Tizen.NUI/src/public/Animation.cs, src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs, src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs, src/Tizen.NUI/src/public/PropertyBuffer.cs, src/Tizen.NUI/src/public/PropertyNotification.cs, src/Tizen.NUI/src/public/PropertyNotifySignal.cs, src/Tizen.NUI/src/public/Renderer.cs, src/Tizen.NUI/src/public/Shader.cs, src/Tizen.NUI/src/public/UIComponents/ScrollView.cs, src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
[NUI] Make some apis as inhouse, will be internal later
Change-Id: I0fc398a3b33eaab5fd12df5e8f183d9c94ab7049
ACR will be done soon.
=> [NUI] Make some apis as inhouse, will be internal later

docs/api/index.md
The newly added module - Tizen.Security.PrivacyPrivilegeManager - has been added to the documentation index page.
None
=> Add Tizen.Security.PrivacyPrivilegeManager to doc index page

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
Add missing feature tag on document
=> [Bluetooth][TCSACR-216] Add missing feature tag on document

src/Tizen.NUI/src/internal/Application.cs, src/Tizen.NUI/src/public/Window.cs
=> [NUI] Fix NUI Manual TCT issue

src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
=> [NUI] Fix PropertyMap setting issue

src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
=> [Inputmethod] Remove useless exception

src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
- Once apps receive low memory events, GC collection will happen at the
same time.
- This patch is for distribution of GC collection event.
=> [Tizen.Applications.Common] Add a timer for handling GC collection

install.sh, src/Tizen.Network.WiFi/Tizen.Network.WiFi/InvalidKeyException.cs, src/Tizen.Network.WiFi/Tizen.Network.WiFi/NowInProgressException.cs
Change description of InvalidKeyException and NowInProgressException.
=> Change class description

src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs, src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEnums.cs, src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
- AccessibilityGrayscale
- AccessibilityNegativeColor
=> [SystemSettings][TCSACR-215] Add properties

src/Tizen.NUI/src/internal/Layouting/LayoutLength.cs, src/Tizen.NUI/src/internal/Layouting/LayoutMeasureSpec.cs, src/Tizen.NUI/src/internal/Layouting/MeasuredSize.cs, src/Tizen.NUI/src/public/Position.cs, src/Tizen.NUI/src/public/Position2D.cs, src/Tizen.NUI/src/public/RelativeVector2.cs, src/Tizen.NUI/src/public/RelativeVector3.cs, src/Tizen.NUI/src/public/RelativeVector4.cs, src/Tizen.NUI/src/public/Size.cs, src/Tizen.NUI/src/public/Size2D.cs, src/Tizen.NUI/src/public/Vector2.cs, src/Tizen.NUI/src/public/Vector3.cs, src/Tizen.NUI/src/public/Vector4.cs
=> [NUI] Fix GetHashCode Crash issue

src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs, test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/SystemSettings.UnitTest.cs, test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/SystemSettings.UnitTest.csproj, test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSSystemSettings.cs
Add set for AccessibilityTtsEnabled and update test case
=> [SystemSetting] Add setter for AccessibilityTtsEnabled

src/ElmSharp.Wearable/ElmSharp.Wearable/CircleDatetimeSelector.cs, src/ElmSharp.Wearable/ElmSharp.Wearable/CircleSpinner.cs
Add remarks of marker properties. 
If device or emulator does not support marker. Mark related properties is not supported.
- ACR: N/A
=> [Elmsharp.Wearable]add remarks of marker properties

src/ElmSharp.Wearable/ElmSharp.Wearable/CircleDatetimeSelector.cs, src/ElmSharp.Wearable/ElmSharp.Wearable/CircleSpinner.cs
Add remarks of marker properties.
If device or emulator does not support marker. Mark related properties is not supported.
- ACR: N/A
=> [Elmsharp.Wearable] add remarks of marker properties

src/Tizen.NUI/src/internal/DaliEnumConstants.cs, src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs, src/Tizen.NUI/src/internal/SWIGTYPE_p_bundle.cs, src/Tizen.NUI/src/internal/WidgetViewSignal.cs, src/Tizen.NUI/src/public/Animation.cs, src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs, src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/NUIConstants.cs, src/Tizen.NUI/src/public/PropertyBuffer.cs, src/Tizen.NUI/src/public/PropertyNotification.cs, src/Tizen.NUI/src/public/PropertyNotifySignal.cs, src/Tizen.NUI/src/public/Renderer.cs, src/Tizen.NUI/src/public/Shader.cs, src/Tizen.NUI/src/public/UIComponents/ScrollView.cs, src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
[NUI] Fix ABI break
revert hidden APIs to public ones
=> [NUI] Fix ABI break

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudio.cs
=> [Bluetooth][Non-ACR] Fix Bluetooth api document

src/Tizen.NUI/src/internal/DaliEnumConstants.cs, src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs, src/Tizen.NUI/src/public/NUIConstants.cs, src/Tizen.NUI/src/public/Position.cs, src/Tizen.NUI/src/public/Position2D.cs, src/Tizen.NUI/src/public/RelativeVector2.cs, src/Tizen.NUI/src/public/RelativeVector3.cs, src/Tizen.NUI/src/public/RelativeVector4.cs, src/Tizen.NUI/src/public/Size.cs, src/Tizen.NUI/src/public/Size2D.cs, src/Tizen.NUI/src/public/Vector2.cs, src/Tizen.NUI/src/public/Vector3.cs, src/Tizen.NUI/src/public/Vector4.cs
TCSACR-214 Change name of text related properties
http://suprem.sec.samsung.net/jira/browse/TCSACR-214
=> [NUI] TCSACR-214 Change name of text related properties

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Window.cs
Added new ViewAdded event on Window
=> [NUI] Added new ViewAdded event on Window

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
Add BluetoothGattClient APIs
ACR: TCSACR-221
=> [Bluetooth][TCSACR-221] Add BluetoothGattClient APIs

src/ElmSharp/ElmSharp/AnimationView.cs, src/ElmSharp/Interop/Interop.Eina.cs, src/ElmSharp/Interop/Interop.Elementary.AnimationView.cs, test/ElmSharp.Test/TC/AnimationViewTest1.cs
Added some new APIs for AnimationView
Changed:
AnimationView.KeyFrame -> AnimationView.Progress
Added:
public enum AnimationViewState
AnimationView.Frame { get; set; } // Property
AnimationView.DefaultSize { get; } // Property
AnimationView.State { get; } // Property
AnimationView.IsReversePlaying { get; } // Property
AnimationView.FrameCount { get; } // Property
AnimationView.MinProgress { get; set; } // Property
AnimationView.MaxProgress { get; set; } // Property
AnimationView.MinFrame { get; set; } // Property
AnimationView.MaxFrame { get; set; } // Property
=> [ElmSharp] Added some new APIs for AnimationView

src/ElmSharp/ElmSharp/Widget.cs
=> [ElmSharp] modified wrong description

src/ElmSharp/ElmSharp/AnimationView.cs, src/ElmSharp/Interop/Interop.Elementary.AnimationView.cs
=> [ElmSharp] Fixed typo in AnimationView

src/Tizen.Account.AccountManager/Tizen.Account.AccountManager.csproj, src/Tizen.Account.AccountManager/Tizen.Account.AccountManager.sln, src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/Account.cs, src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/AccountErrorFactory.cs, src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/AccountService.cs
- new exception added for account feature not supported.
- added feature enable(true/false) in service API's
- improved exception message creation logic
=> [Account Manager] added feature not supported exception

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Renderer.cs, src/Tizen.NUI/src/public/TextureSet.cs
=> [NUI] Fix Renderer null issue

src/Tizen.Applications.EventManager/Interop/Interop.AppEvent.cs, src/Tizen.Applications.EventManager/Interop/Interop.Libraries.cs, src/Tizen.Applications.EventManager/Tizen.Applications.EventManager.csproj, src/Tizen.Applications.EventManager/Tizen.Applications.EventManager.sln, src/Tizen.Applications.EventManager/Tizen.Applications/ApplicationEventManager.cs, src/Tizen.Applications.EventManager/Tizen.Applications/ErrorFactory.cs, src/Tizen.Applications.EventManager/Tizen.Applications/EventManagerEventArgs.cs, src/Tizen.Applications.EventManager/Tizen.Applications/EventReceiver.cs, src/Tizen.Applications.EventManager/Tizen.Applications/SystemEvents.cs
[Tizen.Applications.EventManager] Add new apis for event system
- ACR: http://suprem.sec.samsung.net/jira/projects/TCSACR/issues/TCSACR-227
=> [Tizen.Applications.EventManager] Add new apis for event system

src/Tizen.Applications.PackageManager/Interop/Interop.PackageArchive.cs, src/Tizen.Applications.PackageManager/Tizen.Applications/PackageArchive.cs, src/Tizen.Applications.PackageManager/Tizen.Applications/PackageFilter.cs, src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Add new Application API for package archive info
[APIs]
1. PackageManager
- PackageArchive GetPackageArchive(string archivePath)
2. PackageArchive
- string Id {get;}
- string Type {get;}
- string Version {get;}
- string ApiVersion {get;}
- string Description {get;}
- string Label {get;}
- string Author {get;}
- byte[] Icon {get;}
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-228
=> [Tizen.Applications.PackageManager] Add API for package archive info

src/Tizen.Applications.PackageManager/Interop/Interop.Package.cs, src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs
Add new Application API for package info
[APIs]
1. Package
- ApplicationInfo MainApplication {get;}
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-229
=> [Tizen.Applications.PackageManager] Add new API for package info

src/Tizen.NUI/src/public/NUIConstants.cs
[NUI] Add ImageVisual property index to use VectorAnimationVisual
None
=> [NUI] Add ImageVisual property index to use VectorAnimationVisual

src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
[MediaPlayer] Modify the range of parameter for buffering API
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-231
Changed:(descriptions)
- PlayerBufferingTime
=> [MediaPlayer] Modify the range of parameter for buffering API

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapter.cs
Deprecated LeDevice based Gatt APIs
- ACR : http://suprem.sec.samsung.net/jira/projects/TCSACR/issues/TCSACR-235
=> [Bluetooth] Deprecated LeDevice based Gatt APIs

src/ElmSharp/ElmSharp/Panel.cs, test/ElmSharp.Test/TC/AnimationViewTest1.cs, test/ElmSharp.Test/TC/PanelTest2.cs
Added new Scrolled event in Panel
=> [ElmSharp] Added new Scrolled event in Panel

src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/AccountProvider.cs
- proper check added for feature not supported.
=> [Account Manager] added feature not supported exception in account-provider

src/Tizen.NUI/src/internal/NDalicPINVOKE.cs, src/Tizen.NUI/src/public/Key.cs
[NUI] Add to get LogicalKey and KeyPressed
ACR will be done, currently it will be InhouseAPI
=> [NUI] Add to get LogicalKey and KeyPressed

src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerPlaylist.cs, src/Tizen.Multimedia.Remoting/MediaController/InternalEnums.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlMetadata.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlPlaylist.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
Add new API for Season, Episode, Resolution
- TCSACR-236
=> [MediaController] Add new API for Season, Episode, Resolution

src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapter.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
Add BluetoothLeDevice APIs
- ACR(Add): http://suprem.sec.samsung.net/jira/browse/TCSACR-237
- ACR(Deprecated): http://suprem.sec.samsung.net/jira/browse/TCSACR-238
=> [Bluetooth][TCSACR-237] Add BluetoothLeDevice APIs

src/Tizen.NUI/src/public/BaseComponents/View.cs
Window.Instance is null on WatchApplication.
=> [NUI] Fix WatchApplication crash issue

src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
Bug Fix.
- Added missed description of supporting image mime type.
- Added exception handling code to throw more proper exception.
=> [MediaContent] Add missing description and its related code

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
If no data from scan result, return null instead of exception.
=> [Bluetooth][Non-ACR] Fix no data exception issue

src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
Changed p/invoke function for Delete() method.
Throw InvalidOperationException if file still exists before calling Delete() method.
(PM confirmed for this change)
- TCSACR-239
=> [MediaContent] Add exception and change p/invoke function

src/Tizen.Location/Tizen.Location/Locator.cs
- Improved calling of StopBatch() instead of Stop() within batch period.
=> [Location]Modified Stop() for StopBatch() functionality

src/Tizen.WebView/Interop/Interop.ChromiumEwk.BackForwardList.cs, src/Tizen.WebView/Interop/Interop.ChromiumEwk.View.cs, src/Tizen.WebView/Interop/Interop.Eina.cs, src/Tizen.WebView/Tizen.WebView/BackForwardList.cs, src/Tizen.WebView/Tizen.WebView/WebView.cs
[WebView] [TCSACR-219] Adds WebView.BackForwardList
Signed-off-by: basavarajps <basavaraj.ps@samsung.com>
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-219
=> [WebView] [TCSACR-219] Adds WebView.BackForwardList

src/Tizen.WebView/Interop/Interop.ChromiumEwk.Context.cs, src/Tizen.WebView/Tizen.WebView/Context.cs
[WebView] [TCSACR-219] Add Context API
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-219
=> [WebView] [TCSACR-219] Add Context API

src/Tizen.WebView/Interop/Interop.ChromiumEwk.ContextMenu.cs, src/Tizen.WebView/Tizen.WebView/ContextMenu.cs, src/Tizen.WebView/Tizen.WebView/WebView.cs
[WebView] [TCSACR-219] Add Context Menu API
Signed-off-by: basavarajps <basavaraj.ps@samsung.com>
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-219
=> [WebView] [TCSACR-219] Add Context Menu API

src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerPlaylist.cs, src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Change P/Invoke function of Playlist instead of deprecated CAPI.
=> [MediaController] Change P/Invoke function of playlist

src/Tizen.Multimedia.Camera/Camera/PreviewFrame.cs
=> [Camera] Fix preview buffer size

src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs, src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs
[STT/TTS] Fix desctructor to call dispose
=> [STT/TTS] Fix desctructor to call dispose (#596)

src/Tizen.Content.MediaContent/Tizen.Content.MediaContent.csproj, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Columns.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Folder.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfo.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/QueryArguments.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Storage.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/StorageCommand.cs
Deprecate storage APIs
- TCSACR-243
=> [MediaContent] Deprecate Storage API

src/Tizen.NUI/src/internal/Registry.cs, src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
[NUI] Add VectorAnimationView (DALi Lottie)
ACR will be done and link will be updated here
=> [NUI] Add VectorAnimationView (DALi Lottie)

src/Tizen.NUI/src/internal/XamlBinding/NavigationPage.cs, src/Tizen.NUI/src/internal/XamlBinding/RotationTypeConverter.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
=> [NUI] Fix build warnings

src/Tizen.NUI/src/public/NUIConstants.cs
[NUI] Make DrawModeType.Stencil deprecated
http://suprem.sec.samsung.net/jira/browse/TCSACR-214
=> [NUI] Make DrawModeType.Stencil deprecated

packaging/PlatformFileList.txt
Request to add EventManager dll
=> [Tizen.Applications.EventManager] Request to add EventManager dll

src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs
Removed 'mc_server_get_playlist' function, which is not used anymore.
=> [MediaController] Removed p/invoke function, which is not used anymore

src/Tizen.NUI/src/internal/XamlBinding/BindableProperty.cs, src/Tizen.NUI/src/internal/XamlBinding/PositionTypeConverter.cs, src/Tizen.NUI/src/internal/XamlBinding/SizeTypeConverter.cs, src/Tizen.NUI/src/internal/XamlBinding/Style.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/FocusManager.cs, src/Tizen.NUI/src/public/GraphicsTypeConverter.cs, src/Tizen.NUI/src/public/GraphicsTypeManager.cs, src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/Position2D.cs
[NUI] Add GraphicsTypeManager for Density Independent Pixel
[NUI] Fix KeyboardFocusManager custom algorithm reset
N/A
=> [NUI] Add GraphicsTypeManager for Density Independent Pixel

src/Tizen.NUI/src/public/GraphicsTypeConverter.cs, src/Tizen.NUI/src/public/GraphicsTypeManager.cs
Signed-off-by: Seungho, Baek <sbsh.baek@samsung.com>
- ACR:
=> [NUI] Comment modifying in GraphicsTypeManager

src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
following the comments, I changed the documentation for streaming APIs
https://github.com/Samsung/TizenFX/pull/748
=> [MediaPlayer] Change documentation for streaming APIs

src/Tizen.Multimedia.Remoting/MediaController/MediaControlMetadata.cs
Changed description of SeriesInformation and EncodedSeason.
=> [MediaController] Fix description

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapter.cs
=> [Bluetooth][Non-ACR] Fix API document

src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs, src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs
change codes to support multi handle according to issues-65. 
- ACR:
=> [STT/TTS] support multi handle for event

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
[NUI] Change name of VectorAnimationView, Fix VD build error
N/A
=> [NUI] Change name of VectorAnimationView, Fix VD build error

src/Tizen.NUI/src/internal/WebView.cs
=> [NUI] Add EditorBrowableState.Never attribute to NUI.WebView properties

src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Fix View.HasFocus crash issue

src/Tizen.Messaging/Tizen.Messaging.Messages/MessagesManagerImpl.cs
Removed the exception during object creation. Which sporadically results in failure C# TCs.
=> Fix messaging exception

src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
=> [NUI] Fix LayoutController Crash issue

src/Tizen.NUI/src/internal/Registry.cs
=> [NUI] Delete throw from Registry

src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Columns.cs
Deprecate filter keyword, which is not used frequently.
- TCSACR-244
=> [MediaContent] Deprecate filter keyword

src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs, src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
Signed-off-by: SukHyung, Kang <shine.kang@samsung.com>
Fix API reference descrpitions for RPC port API
=> Fix API reference for RPC port

src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
Fix description of Delete method
=> [MediaContent] Fix description of Delete method

packaging/PlatformFileList.txt
[NUI] Add NUI.Xaml into Platform binary
None
=> [NUI] Add NUI.Xaml into Platform binary

src/Tizen.Account.SyncManager/Tizen.Account.SyncManager/SyncAdapter.cs, src/Tizen.Multimedia.MediaPlayer/Player/SphericalVideo.cs, src/Tizen.Nlp/Tizen.Nlp/NaturalLanguageProcess.cs, src/Tizen.Uix.InputMethodManager/Tizen.Uix.InputMethodManager/InputMethodManager.cs, src/Tizen.WebView/Tizen.WebView/WebView.cs
=> [Doc] Fix documentation warnings

src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
Changed descriptions of audio pitch APIs according to comments.
http://suprem.sec.samsung.net/jira/browse/TCSACR-240
=> [MediaPlayer] Change descriptions of audio pitch APIs

src/Tizen.NUI/src/internal/Interop/Interop.Renderer.cs, src/Tizen.NUI/src/public/Renderer.cs
=> [NUI] Add Renderer Ranges

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/VisualMaps.cs
AlphaMaskURL
CropToMask
FittingMode
DesiredWidth
DesiredHeight
WrapModeU
WrapModeV
=> [NUI] Add ImageView APIs

src/Tizen.NUI/src/public/Renderer.cs
=> [NUI] Modify PropertyRanges name

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs, src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/NUIApplication.cs, src/Tizen.NUI/src/public/Window.cs
[NUI] Add API for NUI Multi WIndow
=> [NUI] Add API for NUI Multi WIndow

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Container.cs, src/Tizen.NUI/src/public/Layer.cs
=> [NUI] Fix ConvertIdToView

src/Tizen.NUI/src/public/NUIApplication.cs
this api for get Default Window.
- ACR:
=> [NUI] Add GetDefaultWindow()

src/Tizen.NUI.Xaml/src/public/Forms/BaseComponents/View.cs, src/Tizen.NUI.Xaml/src/public/XamlBinding/ContentPage.cs
=> [NUI] Add inherit binding context support

src/Tizen.NUI/src/public/Window.cs
=> [NUI] Revert Key & touch Event for Multi Window

src/Tizen.NUI/src/public/Window.cs
[NUI] Add Key & touch Event for Multi Window
This reverts commit 2e033fcc714b92b71a036b9aab66693556e75dab.
None
=> [NUI] Add Key & touch Event for Multi Window

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Container.cs, src/Tizen.NUI/src/public/Layer.cs
This reverts commit cd93540791a0740bc85259e10f33b0959b94d5dc.
=> Revert "[NUI] Fix ConvertIdToView (#877)"

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Container.cs, src/Tizen.NUI/src/public/Layer.cs
[NUI] Fix ConvertidToView issue
+ If we can;t find the parent's children, find in the top layer.
=> [NUI] Fix ConvertidToView issue

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
1. Fix ImageView issue : not updated when using ImageMap
2. clean ImageView code
=> [NUI] Clean ImageView code

src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs, src/Tizen.NUI/src/public/Xaml/ViewExtensions.cs, src/Tizen.NUI/src/public/XamlBinding/NameScopeExtensions.cs
[NUI] Add LoadFromXamlFile()
None
=> [NUI] Add LoadFromXamlFile()

src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
[NUI] Add TextFit in TextLabel
None
=> [NUI] Add TextFit in TextLabel

src/Tizen.NUI/src/public/NUIApplication.cs
=> [NUI] Change GetDefaultWindow() to static func

packaging/PlatformFileList.txt
[NUI.CommonUI]Add CommonUI to rpm
None
=> [NUI] Add CommonUI to rpm

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs, src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
[NUI] Add AnimatedVectorImageView
None
=> [NUI] Add AnimatedVectorImageView

src/Tizen.NUI/src/internal/AuthenticationSignalType.cs, src/Tizen.NUI/src/internal/Interop/Interop.AuthenticationSignalType.cs, src/Tizen.NUI/src/internal/Interop/Interop.AutofillContainer.cs, src/Tizen.NUI/src/internal/Interop/Interop.ListEventSignalType.cs, src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs, src/Tizen.NUI/src/internal/ListEventSignalType.cs, src/Tizen.NUI/src/public/AutofillContainer.cs
Change-Id: Ifc219498c53577e6560b84a8065c22c3b03e2859
- Autofill is a feature that allows the user to fill out commonly-entered information, such as email, account and address previously saved.
- Added AutofillContainer class to set TextField enabled to use Autofill function.
- Currently, AutofillContainer class and APIs are supported internally.
ACR process would be proceeded later.
=> [NUI] Add AutofillContainer and autofill implementation

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
=> [NUI] Fix ImageView bug

src/Tizen.Multimedia.Util/ImageUtil/ImageDecoder.cs, src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Decode.cs
Crash was occurred when local variable is set for output buffer.
=> [ImageUtil] Fix crash issue

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/NUIApplication.cs
[NUI] Add View.Color property and SetRenderRefreshRate method
Will be done soon
=> [NUI] Add View.Color property and SetRenderRefreshRate method

src/Tizen.NUI/src/public/BaseComponents/View.cs
[NUI] Change BackgroundImageSynchronosLoading property as public
ACR will be done soon
=> [NUI] Change BackgroundImageSynchronosLoading property as public

src/Tizen.Multimedia.Util/ImageUtil/ColorSpaceTransform.cs, src/Tizen.Multimedia.Util/ImageUtil/CropTransform.cs, src/Tizen.Multimedia.Util/ImageUtil/FlipTransform.cs, src/Tizen.Multimedia.Util/ImageUtil/ImageDecoder.cs, src/Tizen.Multimedia.Util/ImageUtil/ImageEncoder.cs, src/Tizen.Multimedia.Util/ImageUtil/ImageTransform.cs, src/Tizen.Multimedia.Util/ImageUtil/ImageTransformGroup.cs, src/Tizen.Multimedia.Util/ImageUtil/ImageUtil.cs, src/Tizen.Multimedia.Util/ImageUtil/ResizeTransform.cs, src/Tizen.Multimedia.Util/ImageUtil/RotateTransform.cs, src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Decode.cs, src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Encode.cs, src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Transform.cs, src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.cs
Replace deprecated native decode pinvoke function to new one.
=> [ImageUtil] Replace deprecated decode pinvoke func.

src/Tizen.Content.MediaContent/Interop/Interop.Face.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/FaceInfoCommand.cs
Add face insert method
- TCSACR-249
=> [MediaContent] Add face Insert API

src/Tizen.Multimedia.Util/Interop/Interop.ThumbnailExtractor.cs, src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractionResult.cs, src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
Add thumbnail API which extract thumbnail synchronously.
- TCSACR-250
=> [ImageUtil] Add sync thumbnail extract API

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/AudioDataDecodedEventArgs.cs, src/Tizen.Multimedia.MediaPlayer/Player/AudioFrameDecodedEventArgs.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.Events.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-251
Added:
public class AudioDataDecodedEventArgs
public event EventHandler<AudioDataDecodedEventArgs> AudioDataDecoded
public void EnableExportingAudioData(AudioMediaFormat format, PlayerAudioExtractOption option)
public void DisableExportingAudioData()
public enum PlayerAudioExtractOption
{
Default,
NoSyncWithClock,
Deinterleave,
NoSyncAndDeinterleave
}
=> [MediaPlayer] Add API to export audio PCM data

src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
fix it to not try getting handle when format is null
=> [MediaPlayer] fix it to not try getting handle when format is null

src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs, src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractorError.cs
Add description for Extract method related changing resolution of generated thumbnail image.
- TCSACR:
=> [ThumbnailExtractor] Add description for Extract method

src/Tizen.NUI.CommonUI/Attributes/PopupAttributes.cs, src/Tizen.NUI.CommonUI/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.CommonUI/Controls/Switch.cs, src/Tizen.NUI.CommonUI/Utils/Selector.cs
(1)Fix issues
(2)Add style change event for FlexibleView
Signed-off-by: Feng Jin <feng16.jin@samsung.com>
- ACR:
=> [NUI] Update CommonUI

src/Tizen.Multimedia.MediaCodec/Interop/Interop.MediaCodec.cs, src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
Fix the bug of callback registration
=> [MediaCodec] Fix the bug of callback registration

src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/AlbumCommand.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/BookmarkCommand.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/FaceInfoCommand.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/FolderCommand.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaCommand.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaDatabase.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/PlaylistCommand.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/StorageCommand.cs, src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/TagCommand.cs
Fix grammatical error in description
=> [MediaContent] Fix grammatical error in description

src/Tizen.NUI/src/internal/DaliEnumConstants.cs, src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs, src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs, src/Tizen.NUI/src/public/NUIConstants.cs
[NUI] Add StopBehavior, LoopingMode of AnimatedVectorImageView
None
=> [NUI] Add StopBehavior, LoopingMode of AnimatedVectorImageView

src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs, src/Tizen.NUI/src/public/Accessibility.cs, test/NUITestSample/NUITestSample/examples/AtspiTest.cs
[NUI] Add Say, PauseResume of Dali-ATSPI
None
=> [NUI] Add Say, PauseResume of Dali-ATSPI

packaging/PlatformFileList.txt
Signed-off-by: SukHyung, Kang <shine.kang@samsung.com>
Add WidgetApplication, WidgetControl, RemoteView to common profile
None
Changed:
- Add WidgetApplication, WidgetControl, RemoteView to common profile
=> Add WidgetApplication, WidgetControl, RemoteView to common profile

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.Events.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-253
Added:
- public event EventHandler<EventArgs> Prepared;
- public async Task PrepareAsync(CancellationToken cancellationToken)
=> [MediaPlayer] Add API to be able to cancel preparing it

src/Tizen.NUI/src/internal/Application.cs
=> [NUI]Change GetWindowList() to static

src/Tizen.NUI/src/public/Window.cs
=> [NUI] Change API for Window Creation

src/Tizen.Multimedia.MediaPlayer/Player/Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs
=> [MediaPlayer] fix descriptions

src/Tizen.Multimedia.Remoting/MediaController/MediaControlSearchCondition.cs
Add constructor of MediaControlSearchCondition
- TCSACR-255
=> [MediaController] Add constructor of MediaControlSearchCondition

src/Tizen.NUI/src/public/Window.cs
=> [NUI] Add method to destroy a window

src/Tizen.NUI/src/internal/GaussianBlurView.cs, src/Tizen.NUI/src/internal/Interop/Interop.Button.cs, src/Tizen.NUI/src/internal/Interop/Interop.ImageView.cs, src/Tizen.NUI/src/internal/Interop/Interop.PushButton.cs, src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs, src/Tizen.NUI/src/internal/Interop/Interop.ViewInternal.cs, src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs, src/Tizen.NUI/src/internal/Layouting/LayoutData.cs, src/Tizen.NUI/src/internal/Layouting/LayoutTransition.cs, src/Tizen.NUI/src/internal/ViewImpl.cs, src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/UIComponents/Button.cs
=> [NUI] Sync with dalihub

src/Tizen.NUI/src/public/BaseComponents/View.cs
[NUI] Fix TV Gallary crash
None
=> [NUI] Fix TV Gallary crash

src/Tizen.Multimedia.MediaCodec/MediaCodec/BufferStatusChangedEventArgs.cs, src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecErrorOccurredEventArgs.cs
Remove feature description and tag in EventArgs class
- TCSACR-256
=> [MediaCodec] Remove feature description and tag in EventArgs class

src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
- Prints application ID and operation for debugging
=> [Applications.Common] Fix exception messages

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/MediaStreamSource.cs
fix APIs to get the list of really supported formats
=> [MediaPlayer] fix APIs to get the list of really supported formats

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs, src/Tizen.NUI/src/public/Window.cs
Add SetParent, GetParent and Unparent interface.
It is to support transient_for function.
None
=> [NUI] Add SetParent interface

src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
fix descriptions to reflect comments
=> [MediaPlayer] fix descriptions to reflect comments

src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerClient.cs, src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs, src/Tizen.Multimedia.Remoting/MediaController/InternalEnums.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControllerManager.Events.cs
Replace deprecated pinvoke function.
(Related ACR-1428)
=> [MediaController] Replace deprecated pinvoke function

src/Tizen.NUI/src/public/Window.cs
=> [NUI] Add Window Creation API for setting name

src/Tizen.Applications.PackageManager/Interop/Interop.Package.cs, src/Tizen.Applications.PackageManager/Interop/Interop.PackageArchive.cs, src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs, src/Tizen.Applications.PackageManager/Tizen.Applications/PackageArchive.cs, src/Tizen.Applications.PackageManager/Tizen.Applications/PackageDependencyInformation.cs
Add api for get dependency from package and package archive
=> [Tizen.Applications.PackageManager][TCSACR-272][Add] Add Dependency Info APIs

src/Tizen.Multimedia/AudioManager/AudioDucking.cs, src/Tizen.Multimedia/AudioManager/AudioDuckingStateChangedEventArgs.cs, src/Tizen.Multimedia/Interop/AudioDuckingHandle.cs, src/Tizen.Multimedia/Interop/Interop.Ducking.cs
- Added class
: AudioDucking
: AudioDuckingStateChangedEventArgs
: AudioDuckingHandle
- API Changes
: TCSACR-271 (http://suprem.sec.samsung.net/jira/browse/TCSACR-271)
Signed-off-by: Jeongmo Yang <jm80.yang@samsung.com>
=> [AudioManager] Add new class for audio ducking

src/Tizen.NUI/src/internal/Camera.cs, src/Tizen.NUI/src/internal/ItemView.cs, src/Tizen.NUI/src/internal/LinearConstrainer.cs, src/Tizen.NUI/src/internal/Model3dView.cs, src/Tizen.NUI/src/internal/PageTurnView.cs, src/Tizen.NUI/src/internal/PathConstrainer.cs, src/Tizen.NUI/src/internal/RenderTask.cs, src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs, src/Tizen.NUI/src/public/PanGestureDetector.cs, src/Tizen.NUI/src/public/Renderer.cs, src/Tizen.NUI/src/public/Shader.cs, src/Tizen.NUI/src/public/UIComponents/ScrollView.cs, src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
[NUI] Integration from dalihub (DALi 1.4.34)
- http://suprem.sec.samsung.net/jira/browse/TCSACR-264
- http://suprem.sec.samsung.net/jira/browse/TCSACR-267
=> [NUI] Integration from dalihub (DALi 1.4.34)

src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
[NUI] Open VectorAnimationView API
None
=> [NUI] Open VectorAnimationView API

packaging/PlatformFileList.txt
Adds:
- Tizen.Applications.ComponentBased.ComponentManager.dll
- Tizen.Applications.ComponentBased.Default.dll
- Tizen.Applications.ComponentBased.dll
=> [ComponentBased] Update PlatformFileList

src/Tizen.Applications.ComponentBased.Default/Interop/Interop.Libraries.cs, src/Tizen.Applications.ComponentBased/Interop/Interop.Libraries.cs
Fix libraries of Interop
The file extension of libraries should include major version.
=> [ComponentBased] Fix interop libraries

src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
Revert "[NUI] Open VectorAnimationView API (#1003)"
This reverts commit b1e88135350e5f595bad974fc9ee7d0665ab4c38.
None
=> Revert "[NUI] Open VectorAnimationView API (#1003)"

src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerClient.cs, src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs, src/Tizen.Multimedia.Remoting/MediaController/DisplayModeCapabilityUpdatedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/DisplayModeCommandReceivedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/DisplayModeUpdatedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/DisplayRotationCapabilityUpdatedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/DisplayRotationCommandReceivedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/DisplayRotationUpdatedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/InternalEnums.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlCommand.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlEnums.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlPlaylist.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.Events.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaController.Events.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControllerManager.Events.cs, src/Tizen.Multimedia.Remoting/MediaController/Mode360CommandReceivedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/Mode360UpdatedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/RepeatModeCapabilityUpdatedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/RepeatModeCommandReceivedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/ShuffleModeCapabilityUpdatedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/SubtitleModeCommandReceivedEventArgs.cs, src/Tizen.Multimedia.Remoting/MediaController/SubtitleModeUpdatedEventArgs.cs
Add new APIs for subtitle, 360 mode, display mode, display rotation
- TCSACR-273
=> [MediaController] Add new APIs for subtitle, 360 mode, display mode/rotation

src/Tizen.Multimedia/Interop/Interop.MediaTool.cs, src/Tizen.Multimedia/MediaTool/AudioMediaFormat.cs, src/Tizen.Multimedia/MediaTool/MediaFormatChannelPosition.cs, src/Tizen.Multimedia/MediaTool/MediaPacket.Lock.cs, src/Tizen.Multimedia/MediaTool/MediaPacket.cs, src/Tizen.Multimedia/MediaTool/MediaPacketVideoPlane.cs
Add audio channel mapping APIs for PCM format
- TCSACR-275
=> [MediaTool] Add audio channel mapping APIs for PCM format

src/Tizen.Multimedia.AudioIO/AudioIO/AudioChannel.cs, src/Tizen.Multimedia.AudioIO/AudioIO/AudioSampleType.cs
Add new APIs for Sample and channel type
- TCSACR-276
=> [AudioIO] Add new APIs for Sample and channel type

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs, src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
[NUI] Temporal fix of not animating dali-lottie when the URL is only changed
None
=> [NUI] Temporal fix of not animating dali-lottie when the URL is only changed

src/Tizen.Multimedia.MediaPlayer/Player/Player.Events.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-266
Added:
- public void EnableExportingVideoFrame()
- public void DisableExportingVideoFrame()
=> [MediaPlayer] add API to export video frames

src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs, src/Tizen.NUI/src/public/Accessibility.cs
[NUI] Add dali-atspi getState(), say(), say_callback() and pauseResume() as HiddenAPI
None
=> [NUI] Add dali-atspi

src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs, src/Tizen.Multimedia.MediaPlayer/Player/AudioOffload.cs, src/Tizen.Multimedia.MediaPlayer/Player/EqualizerBand.cs
[MediaPlayer] Update descriptions according to the guideline
=> [MediaPlayer] Update descriptions according to the guideline

src/Tizen.Multimedia.Camera/Camera/Camera.cs
Fixed missing exception description and exception check code.
=> [Tizen.Multimedia.Camera] Fixed exception bug

src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerClient.cs, src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs
=> [MediaController] Changed pinvoke function

src/Tizen.Multimedia.AudioIO/WavPlayer/WavPlayer.cs
=> [AudioIO] Fix crash issue

src/Tizen.NUI/src/public/Window.cs
[NUI] Changed the APIs related to MultiWIndow to public
http://suprem.sec.samsung.net/jira/browse/TCSACR-279
=> [NUI] Changed the APIs related to MultiWIndow to public

src/Tizen.Multimedia.AudioIO/WavPlayer/WavPlayer.cs
Add ConfigureAwait() to tcs.Task
=> [AudioIO] Add ConfigureAwait to task

src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs, src/Tizen.NUI/src/internal/Layouting/LayoutController.cs, src/Tizen.NUI/src/internal/Layouting/LayoutItem.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Touch.cs
[NUI] Integration from dalihub
N/A
=> [NUI] Integration from dalihub

src/Tizen.NUI/src/internal/Interop/Interop.InputMethodContext.cs, src/Tizen.NUI/src/public/InputMethodContext.cs
- Add SetInputPanelPosition API to set the position of input panel
N/A
- This API is provided as a hidden API.
=> [NUI] Add to set the position of input panel

src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs, src/Tizen.NUI/src/internal/SWIGTYPE_p_bundle.cs, src/Tizen.NUI/src/internal/WidgetViewSignal.cs, src/Tizen.NUI/src/public/Animation.cs, src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/PropertyBuffer.cs, src/Tizen.NUI/src/public/PropertyNotification.cs, src/Tizen.NUI/src/public/PropertyNotifySignal.cs, src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
[NUI] TCSACR-226 code change
http://suprem.sec.samsung.net/jira/browse/TCSACR-226
=> [NUI] TCSACR-226 code change

src/Tizen.NUI/src/public/Window.cs
=> [NUI] Fix Bug in GetParent()

src/Tizen.Messaging/Tizen.Messaging.Email/EmailSender.cs
Email Emulator TCT were getting failed , proper handling of the callback result is achieved in the async function.
NA
=> Patch for Email Emulator TCT issues

src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs, src/Tizen.Multimedia.MediaPlayer/Player/Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-281
Added:
- public enum CodecType
- public CodecType AudioCodec
- public class NotAvailableException : InvalidOperationException
=> [MediaPlayer] Add API for setting audio codec type

src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs, src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEnums.cs, src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs, test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/SystemSettings.UnitTest.csproj, test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSSystemSettings.cs
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-247
=> [SystemSettings][TCSACR-247][Add] Add RotaryEventEnabled

src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs, src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
Add feature about RotaryEventEnabled.
<feature>http://tizen.org/feature/input.rotating_bezel</feature>
http://suprem.sec.samsung.net/jira/browse/TCSACR-247
=> [SystemSettings]Add feature RotaryEventEnabled

src/Tizen.Multimedia/MediaTool/AudioMediaFormat.cs
Add missed exception code and description for bitDepth
- TCSACR-275
=> [MediaTool] Add missed exception for bitDepth

src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Add capability method for subtitle, 360 mode
- TCSACR-283
=> [MediaController] Add capability method for subtitle, 360 mode

src/Tizen.NUI/src/public/UIComponents/Button.cs, src/Tizen.NUI/src/public/UIComponents/CheckBoxButton.cs, src/Tizen.NUI/src/public/UIComponents/Popup.cs, src/Tizen.NUI/src/public/UIComponents/ProgressBar.cs, src/Tizen.NUI/src/public/UIComponents/PushButton.cs, src/Tizen.NUI/src/public/UIComponents/RadioButton.cs, src/Tizen.NUI/src/public/UIComponents/ScrollBar.cs, src/Tizen.NUI/src/public/UIComponents/ScrollView.cs, src/Tizen.NUI/src/public/UIComponents/Slider.cs, src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
[NUI] Deprecate Tizen.NUI.UIComponents
http://suprem.sec.samsung.net/jira/browse/TCSACR-280
=> [NUI] Deprecate Tizen.NUI.UIComponents

src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Enable View.ScaleBy (#33)

src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommand.cs, src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommandsGroup.cs, src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceControlManagerClient.cs
Add tags for missing feature and privilege of the below mentioned ACR.
http://suprem.sec.samsung.net/jira/browse/TCSACR-213
=> [VoiceControlManager] Add tags for missing feature and privilege

src/Tizen.NUI.Components/Attributes/DropDownAttributes.cs, src/Tizen.NUI.Components/Attributes/LoadingAttributes.cs, src/Tizen.NUI.Components/Attributes/PaginationAttributes.cs, src/Tizen.NUI.Components/Attributes/TabAttributes.cs, src/Tizen.NUI.Components/Attributes/ViewAttributes.cs, src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/Control.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs, src/Tizen.NUI.Components/Controls/Loading.cs, src/Tizen.NUI.Components/Controls/Pagination.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/SelectButton.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs, src/Tizen.NUI/src/public/Position.cs, src/Tizen.NUI/src/public/Size.cs
[NUI] Open public apis of NUI.Components for TCSACR-248
this is merge patch of "https://github.com/Samsung/TizenFX/pull/1028" to fix merge conflict
http://suprem.sec.samsung.net/jira/browse/TCSACR-248
=> [NUI] Open public apis of NUI.Components for TCSACR-248

src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Fix typo
GetDisplayRotationapability() -> GetDisplayRotationCapability()
=> [MediaController] Fix typo

src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
Add new exception to the doxygen of ApplyStreamRouting() in AudioStreamPolicy class.
TCSACR-285
=> [AudioManager] Add new exception to the doxygen of ApplyStreamRouting()

src/Tizen.NUI/src/internal/Interop/Interop.WindowEffectEventSignal.cs, src/Tizen.NUI/src/internal/WindowEffectSignal.cs, src/Tizen.NUI/src/public/Window.cs
[NUI] Add Window.TransitionEffect event
will be updated later
=> [NUI] Add Window.TransitionEffect event

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs, src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
[NUI] some change in VectorAnimationViewTBD
Not needed
=> [NUI] some change in VectorAnimationViewTBD

internals/src/EflSharp/EflSharp/Circle/CircleGenlist.cs, internals/src/EflSharp/EflSharp/Circle/CircleScroller.cs, internals/src/EflSharp/EflSharp/Circle/RotarySelector.cs, internals/src/EflSharp/EflSharp/efl/efl_access_object.eo.cs, internals/src/EflSharp/EflSharp/efl/efl_ui_animation_view.eo.cs
Circle and efl cs files are updated based on the latest efl.
Documentation warnings are fixed.
Efl.Ui.AnimationView class is included.
- ACR:
=> [EflSharp] Update Circle and efl cs files

src/Tizen.NUI/src/internal/Interop/Interop.WindowEffectEventSignal.cs, src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs, src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs, src/Tizen.NUI/src/public/Window.cs
[NUI] Change WindowTransitionEffect interface
None
=> [NUI] Change WindowTransitionEffect interface

src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Update documentation on View class

src/Tizen.Multimedia/AudioManager/AudioDucking.cs, src/Tizen.Multimedia/AudioManager/AudioDuckingStateChangedEventArgs.cs
Signed-off-by: Jeongmo Yang <jm80.yang@samsung.com>
=> [AudioManager] Update description suggested by ducoment team

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs, src/Tizen.NUI/src/public/VisualConstants.cs
[NUI] Add GetContentInfo() to get lottie file's layer information
None
=> [NUI] Add GetContentInfo() to get lottie file's layer information

src/Tizen.NUI/src/public/Window.cs, src/Tizen.NUI/src/public/WindowEvent.cs
fix Document related the part of window
Not required
=> [NUI] fix Document related the part of window

src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Fix Gallery Crash issue

src/Tizen.Multimedia/MediaTool/MediaPacket.cs
=> [MediaTool] specify the unit

src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.Events.cs, src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
=> [MediaController] Fix build warning

src/Tizen.Multimedia.MediaPlayer/Player/Player.cs, src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs
=> [MediaPlayer] Fix build warning

src/Tizen.Network.Connection/Interop/Interop.Connection.cs, src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs, src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
=> Revert "[Tizen.Network.Connection] Init/deinit without ManagedThreadId"

src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/AccessToken.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/AuthenticationScheme.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/AuthorizationRequest.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/AuthorizationResponse.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/Authorizer.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ClientCredentials.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ClientCredentialsAuthorizer.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ClientCredentialsTokenRequest.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/CodeGrantAuthorizationRequest.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/CodeGrantAuthorizer.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/CodeGrantTokenRequest.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ImplicitGrantAuthorizationRequest.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ImplicitGrantAuthorizer.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/OAuth2ErrorResponse.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/RefreshToken.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/RefreshTokenRequest.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ResourceOwnerPwdCredentialsAuthorizer.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ResourceOwnerPwdCredentialsTokenRequest.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/TokenRequest.cs, src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/TokenResponse.cs
ACR link : http://suprem.sec.samsung.net/jira/browse/TCSACR-289
=> Deprecate of Tizen.Account.OAuth2

src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
Fix descriptions as the comment of document team.
=> [ImageUtil] Fix descriptions

src/Tizen.Network.Stc/Tizen.Network.Stc/StcError.cs, src/Tizen.Network.Stc/Tizen.Network.Stc/StcManager.cs, src/Tizen.Network.Stc/Tizen.Network.Stc/StcManagerImpl.cs
Signed-off-by: Lokesh <l.kasana@samsung.com>
Fix to provide proper exceptions
=> [Network.Stc] [Fix] Correct exception handling

src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs
=> [PackageManager] Modify description for DependencyTo/From properties

src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
=> [NUI] revert the patch for flexibleview animation

src/Tizen.Multimedia.MediaPlayer/Player/AudioOffload.cs
[MediaPlayer] change the error code following the API's change
=> [MediaPlayer] change the error code following the API's change

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs, src/Tizen.NUI/src/public/Color.cs, src/Tizen.NUI/src/public/Extents.cs, src/Tizen.NUI/src/public/Rectangle.cs, src/Tizen.NUI/src/public/RelativeVector4.cs, src/Tizen.NUI/src/public/Vector2.cs, src/Tizen.NUI/src/public/Vector3.cs, src/Tizen.NUI/src/public/Vector4.cs, test/NUITestSample/NUITestSample/examples/PropertyCascadeCheckTest.cs, test/NUITestSample/NUITestSample/examples/PropertyCascadeSpeedTest.cs
[NUI] Property setter is changed
N/A
=> [NUI] Property setter is changed

src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
[NUI] Add VectorAnimationView
Nothing
=> [NUI] Add VectorAnimationView

src/Tizen.NUI.Components/Attributes/DropDownAttributes.cs, src/Tizen.NUI.Components/Attributes/SelectButtonAttributes.cs, src/Tizen.NUI.Components/Attributes/TabAttributes.cs, src/Tizen.NUI.Components/Attributes/TextFieldAttributes.cs, src/Tizen.NUI.Components/Attributes/ViewAttributes.cs, src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/SelectButton.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs, src/Tizen.NUI/src/public/Extents.cs
=> [NUI] Use new Extents in Tizen.NUI.Compoents

src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs, src/Tizen.NUI/src/public/Position.cs, src/Tizen.NUI/src/public/Position2D.cs, src/Tizen.NUI/src/public/Size.cs, src/Tizen.NUI/src/public/Size2D.cs
[NUI] Add implicit conversion for Size, Size2D, Position and Position2D
http://vdcosmos-hub.sec.samsung.net/build/4257802
- implicit conversions are added, so no build error.
- user can use Size/Size2D and Position/Position2D freely. (no type casting)
- ACR is not required, I think.
=> [NUI] Add implicit conversion for Size, Size2D, Position and Position2D

src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
=> [NUI] fix layout issue when flexibleview animation is canceled

src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs, src/Tizen.NUI/src/public/Extents.cs
[NUI] Fix the crash when setting MinimumSize, MaximumSize
Nothing
=> [NUI] Fix the crash when setting MinimumSize, MaximumSize

src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs, src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs, src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs, src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs, src/Tizen.NUI/src/public/InputMethodContext.cs, src/Tizen.NUI/src/public/NUIConstants.cs, src/Tizen.NUI/src/public/UIComponents/ScrollViewEvent.cs, src/Tizen.NUI/src/public/VisualConstants.cs, src/Tizen.NUI/src/public/Window.cs
1. Optimize enum code snippets;
2. Refactor InputMethodContext.EventData, InputMethodContext.CallbackData and ScrollView.SnapEvent to inherit Disposable class.
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-292
=> [NUI] Refine codes to reduce code duplicaton

src/Tizen.NUI/src/public/RelativeVector2.cs, src/Tizen.NUI/src/public/RelativeVector3.cs, src/Tizen.NUI/src/public/RelativeVector4.cs
=> [NUI] Remove ValueCheck function

src/ElmSharp/ElmSharp/PreloadedWindow.cs, src/ElmSharp/ElmSharp/Window.cs
This PR provides `PreloadedWindow` for internal use only. So, there are no public API changes.
None.
=> [ElmSharp] Adds PreloadedWindow

src/Tizen.Multimedia.Camera/Camera/CameraCapabilities.cs
=> [Camera] Fux null reference bug

src/Tizen.NUI/src/internal/Layouting/Interop/Interop.FlexLayout.cs, src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Applying patch to API6 branch that was merged into master
https://github.com/Samsung/TizenFX/pull/1134 (merged into master)
- ACR:
=> [NUI] FlexLayout Interop and Undefined fixes (#1134)

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
[NUI] Publish LottieAnimationView : TCSACR-293
http://suprem.sec.samsung.net/jira/browse/TCSACR-293
=> [NUI] Publish LottieAnimationView : TCSACR-293

src/Tizen.NUI/src/internal/CustomAlgorithmInterface.cs, src/Tizen.NUI/src/internal/Interop/Interop.ImageLoading.cs, src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs, test/NUITestSample/NUITestSample/examples/GetOriginalImageSizeTest.cs
https://code.sec.samsung.net/jira/browse/TCSACR-293
=> [NUI] Sync master branch

src/Tizen.NUI/src/internal/Interop/Interop.VideoView.cs, src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
=> [NUI] Binding VideoView::New with swCodec parameter

src/Tizen.Applications.ComponentBased/AssemblyAttr.cs, src/Tizen.NUI/Tizen.NUI.csproj, src/Tizen.NUI/Tizen.NUI.sln, src/Tizen.NUI/src/internal/ComponentApplication.cs, src/Tizen.NUI/src/internal/Interop/Interop.ComponentApplication.cs, src/Tizen.NUI/src/internal/Interop/Interop.Window.cs, src/Tizen.NUI/src/internal/NUIComponentCoreBackend.cs, src/Tizen.NUI/src/internal/NUIWindowInfo.cs, src/Tizen.NUI/src/public/NUIComponentApplication.cs, src/Tizen.NUI/src/public/NUIFrameComponent.cs, src/Tizen.NUI/src/public/Window.cs
* Add component
* Change Bug
* [NUI]Modify Last
* Add to mange frame component
* Change Sln file
* Change mod
* Change sln
* [NUI] fix comment
- ACR:
=> [NUI] Add Component Application (#1148)

src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/LayoutScroller.cs, src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Squashed:
Now uses NUI Layouting for the drop downbox
DropDown API fixes Delete/Select
LayoutScroller immediate positioning
Applied LayoutScoller updates
LayoutScroller now a CustomLayout with OnMeasure and OnLayout implemented
Velocity of flick not throttled hence can be fast.
Updates after Style refactor
Features:
Persistant selection Icon/Checkbox
Highlight for touched selection
Scrolling list
Styled using ControlStyle system.
Change-Id: I656bc978331df5f38e1885635ba50b6b5e178976
- ACR:
=> [NUI] DropDownButton to use Layout scrolling

src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/LayoutScroller.cs, src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
DropDownButton to use LayoutScroller.
Match API6 branch to master which has these commits merged.
- ACR:
=> [NUI.Components] Api6 drop down uses layout scroller

src/Tizen.NUI/src/internal/Interop/Interop.VideoView.cs, src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
=> [NUI] Binding VideoView::New with swCodec parameter (#1155)

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/ImageControl.cs, src/Tizen.NUI.Components/Controls/InputField.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/SelectButton.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs
=> [NUI] Fix NUI.Components svace issue

src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs
Modify the code which like other open source code.
- ACR:
=> [NUI] To fix OSV check

src/Tizen.NUI.Components/Attributes/DropDownAttributes.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Tizen.NUI.Components.sln
1. Refine DropDown control
- ACR:
=> [NUI.Components] Refine DropDown control

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/ImageControl.cs, src/Tizen.NUI.Components/Controls/InputField.cs, src/Tizen.NUI.Components/Controls/Loading.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/SelectButton.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs
=> [NUI.Components]Fix svace issue

src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Fix wrong API comments in xml

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI/src/public/Extents.cs
Fixed the NUI.Components TCT failed issues such as Extents, StringSelector, ColorSelector and some type conversion errors
=> [NUI] Fixed TCT failed issues

src/Tizen.Sensor/Tizen.Sensor/EventArgs/AutoRotationSensorDataUpdatedEventArgs.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs, src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
Fix invalid value matching between native and csharp API 
- ACR:
=> [Sensor] Fix invalid value matching between native and csharp API

src/Tizen.NUI/src/public/Timer.cs
[NUI] Add checking if the Timer is used in main thread
Nothing
=> [NUI] Add checking if the Timer is used in main thread

src/Tizen.NUI/Tizen.NUI.sln, src/Tizen.NUI/src/public/LongPressGestureDetector.cs, src/Tizen.NUI/src/public/PanGestureDetector.cs, src/Tizen.NUI/src/public/PinchGestureDetector.cs, src/Tizen.NUI/src/public/RotationGestureDetector.cs, src/Tizen.NUI/src/public/TapGestureDetector.cs
Developer now can add more than one callback to Gesture Detected Event
none
=> [NUI] Upgrade gesture handler

src/ElmSharp/Interop/Interop.Evas.Image.cs
Adds internal EvasImage API
No changes public API
=> [ElmSharp] Add internal Evas Image APIs

src/Tizen.NUI/src/public/FocusManager.cs
[NUI] Fix ICustomFocusAlgorithm exception
Nothing
=> [NUI] Fix ICustomFocusAlgorithm exception

src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
Fix crash issue when create popup.
- ACR:
=> [NUI] Fix crash issue when create popup

src/Tizen.Sensor/Interop/Interop.Sensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/Accelerometer.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/FaceDownGestureDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/GravitySensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/Gyroscope.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/GyroscopeRotationVectorSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/HumiditySensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/InVehicleActivityDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/LightSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/LinearAccelerationSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/Magnetometer.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/MagnetometerRotationVectorSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/OrientationSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/Pedometer.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/PickUpGestureDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/PressureSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/ProximitySensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/RotationVectorSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/RunningActivityDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/SleepMonitor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/StationaryActivityDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/TemperatureSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/UltravioletSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/UncalibratedGyroscope.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/UncalibratedMagnetometer.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/WalkingActivityDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/WristUpGestureDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Sensor.cs
Updating initial data values of all the sensors
=> [Sensor] Addition of initial sensor values

src/Tizen.Sensor/Tizen.Sensor/EventArgs/AutoRotationSensorDataUpdatedEventArgs.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs, src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
=> [Sensor] Fix type on auto rotation sensor property

src/Tizen.NUI.Components/Attributes/ToastAttributes.cs, src/Tizen.NUI.Components/Controls/Toast.cs
1.Remove Toast from the Window after hidden
2.Refine the logic of displaying background
=> [NUI] Refine Toast and Remove Toast from the Window after hidden

src/Tizen.NUI.Components/Attributes/ToastAttributes.cs, src/Tizen.NUI.Components/Controls/Toast.cs
1.Remove Toast from the Window after hidden
2.Refine the logic of displaying background
=> [NUI]Merge master#1199 to API6

src/Tizen.NUI.Components/Controls/Toast.cs, src/Tizen.NUI.Components/Style/ToastStyle.cs
1.Remove Toast from the Window after hidden
2.Refine the logic of displaying background
=> [NUI] Merge master#1199 to API7

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/ButtonGroup.cs, src/Tizen.NUI.Components/Controls/Control.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs, src/Tizen.NUI.Components/Controls/InputField.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Style/PopupStyle.cs, src/Tizen.NUI.Components/Utils/StyleManager.cs, src/Tizen.NUI/src/internal/ViewWrapperImpl.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
Sync the whole codes:
1.Refine Popup, added ButtonGroup
2.Fixed BindableProperty issues
3.Changed the name from attribute to style
4.Fixed FlexibleView display issues
=> [NUI] Sync the whole codes to master

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/ButtonGroup.cs, src/Tizen.NUI.Components/Controls/Control.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs, src/Tizen.NUI.Components/Controls/InputField.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Style/PopupStyle.cs, src/Tizen.NUI.Components/Utils/StyleManager.cs, src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
1.Refine Popup, added ButtonGroup
2.Fixed BindableProperty issues
3.Changed the name from attribute to style
4.Fixed FlexibleView display issues
=> [NUI] Merge mater#1206 to API6

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/ButtonGroup.cs, src/Tizen.NUI.Components/Controls/Control.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs, src/Tizen.NUI.Components/Controls/InputField.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Style/PopupStyle.cs, src/Tizen.NUI.Components/Utils/StyleManager.cs, src/Tizen.NUI/src/internal/ViewWrapperImpl.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
1.Refine Popup, added ButtonGroup
2.Fixed BindableProperty issues
3.Changed the name from attribute to style
4.Fixed FlexibleView display issues
=> [NUI] Merge master#1206 to API7

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
[NUI] Add SetMinMaxFrameByMarker() in LottieAnimationView
Nothing
=> [NUI] Add SetMinMaxFrameByMarker() in LottieAnimationView

src/Tizen.NUI.Components/Controls/InputField.cs, src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs, src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
1. Fix textfield color convert issue
- ACR:
=> [NUI] Fix textfield color issue

src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
Fix crash issue when create Popup.
- ACR:
=> [NUI] Fix crash issue when creat popup

src/Tizen.NUI.Components/Controls/DropDown.cs
Fix run-time error in Dropdown
NONE
=> [NUI] Fix Dropdown runtime error

src/Tizen.Multimedia.Camera/Camera/CameraCapabilities.cs
=> [Camera] Fix null reference bug

src/Tizen.NUI/src/internal/Interop/Interop.PropertyMap.cs, src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs, src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs, src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs, src/Tizen.NUI/src/public/PropertyMap.cs, src/Tizen.NUI/src/public/PropertyValue.cs, src/Tizen.NUI/src/public/Rectangle.cs, src/Tizen.NUI/src/public/Size.cs, src/Tizen.NUI/src/public/Vector2.cs, src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs, src/Tizen.NUI/src/public/ViewProperty/Shadow.cs, src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
=> [NUI] Implement shadow in View

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/ButtonGroup.cs, src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs, src/Tizen.NUI.Components/Controls/Control.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/InputField.cs, src/Tizen.NUI.Components/Controls/Loading.cs, src/Tizen.NUI.Components/Controls/Pagination.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs, src/Tizen.NUI.Components/Controls/ScrollableBase.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/SelectGroup.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs, src/Tizen.NUI.Components/Style/ButtonStyle.cs, src/Tizen.NUI.Components/Style/DropDownStyle.cs, src/Tizen.NUI.Components/Style/SliderStyle.cs, src/Tizen.NUI.Components/Style/ToastStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
=> [NUI.Components] Fix build warnings

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/ButtonGroup.cs, src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs, src/Tizen.NUI.Components/Controls/Control.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/InputField.cs, src/Tizen.NUI.Components/Controls/Loading.cs, src/Tizen.NUI.Components/Controls/Pagination.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs, src/Tizen.NUI.Components/Controls/ScrollableBase.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/SelectGroup.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs, src/Tizen.NUI.Components/Style/ButtonStyle.cs, src/Tizen.NUI.Components/Style/DropDownStyle.cs, src/Tizen.NUI.Components/Style/SliderStyle.cs, src/Tizen.NUI.Components/Style/ToastStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
=> [NUI.Components] Fix build warnings (#1233)

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/ButtonGroup.cs, src/Tizen.NUI.Components/Controls/CheckBox.cs, src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs, src/Tizen.NUI.Components/Controls/Control.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/ImageControl.cs, src/Tizen.NUI.Components/Controls/InputField.cs, src/Tizen.NUI.Components/Controls/Loading.cs, src/Tizen.NUI.Components/Controls/Pagination.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/RadioButton.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/SelectButton.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs
1. Fix BackgroundImage doesn't works issue
- ACR:
=> [NUI.Components] Fix BackgroundImage doesn't works issue

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/ButtonGroup.cs, src/Tizen.NUI.Components/Controls/CheckBox.cs, src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs, src/Tizen.NUI.Components/Controls/Control.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/ImageControl.cs, src/Tizen.NUI.Components/Controls/InputField.cs, src/Tizen.NUI.Components/Controls/Loading.cs, src/Tizen.NUI.Components/Controls/Pagination.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/RadioButton.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/SelectButton.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs
1. Fix BackgroundImage doesn't works issue
- ACR:
=> [NUI.Components] Fix BackgroundImage doesn't works issue (#1240)

src/Tizen.NUI.Components/Style/ButtonStyle.cs, src/Tizen.NUI.Components/Style/ControlStyle.cs, src/Tizen.NUI.Components/Style/DropDownStyle.cs, src/Tizen.NUI.Components/Style/ImageControlStyle.cs, src/Tizen.NUI.Components/Style/InputFieldStyle.cs, src/Tizen.NUI.Components/Style/LoadingStyle.cs, src/Tizen.NUI.Components/Style/PaginationStyle.cs, src/Tizen.NUI.Components/Style/PopupStyle.cs, src/Tizen.NUI.Components/Style/ProgressStyle.cs, src/Tizen.NUI.Components/Style/ScrollbarStyle.cs, src/Tizen.NUI.Components/Style/SliderStyle.cs, src/Tizen.NUI.Components/Style/SwitchStyle.cs, src/Tizen.NUI.Components/Style/TabStyle.cs, src/Tizen.NUI.Components/Style/ToastStyle.cs
1. Fix Background Image not works issue
- ACR:
=> [NUI.Components] Fix Background Image not works issue

src/Tizen.NUI.Components/Style/ButtonStyle.cs, src/Tizen.NUI.Components/Style/ControlStyle.cs, src/Tizen.NUI.Components/Style/DropDownStyle.cs, src/Tizen.NUI.Components/Style/ImageControlStyle.cs, src/Tizen.NUI.Components/Style/InputFieldStyle.cs, src/Tizen.NUI.Components/Style/LoadingStyle.cs, src/Tizen.NUI.Components/Style/PaginationStyle.cs, src/Tizen.NUI.Components/Style/PopupStyle.cs, src/Tizen.NUI.Components/Style/ProgressStyle.cs, src/Tizen.NUI.Components/Style/ScrollbarStyle.cs, src/Tizen.NUI.Components/Style/SliderStyle.cs, src/Tizen.NUI.Components/Style/SwitchStyle.cs, src/Tizen.NUI.Components/Style/TabStyle.cs, src/Tizen.NUI.Components/Style/ToastStyle.cs
1. Fix Background Image not works issue
- ACR:
=> [NUI.Components] Fix Background Image not works issue (#1246)

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs, src/Tizen.NUI/src/public/Window.cs
Add the API to get current window orientation.
It is to return the logical orientation
Nothing
=> [NUI] Add to get current window orientation.

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CubeTransitionEffectSample.cs
=> [NUI] fix crash when cube transition effect sample is launched.

src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Fix the issue that the property binding in View are not working properly. (#1259)

src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs
=> [NUI] Fix the issue that the property binding in View are not working properly. (#1259) 

src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs, src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs, src/Tizen.NUI/src/public/Rectangle.cs
=> [NUI] Enable BackgroundImageBorder in View

src/Tizen.NUI/src/public/Color.cs, src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs, src/Tizen.NUI/src/public/ViewProperty/Shadow.cs, src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
=> [NUI] Update Shadow property : add Clone method

src/Tizen.NUI.Components/Controls/Scrollbar.cs
Fixed the type conversion issue which cause TCT failed
=> [NUI] Fixed the type conversion issue which cause TCT failed

src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs, src/Tizen.NUI/src/public/ViewProperty/ICloneable.cs, src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs, src/Tizen.NUI/src/public/ViewProperty/Shadow.cs, src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
=> [NUI] Add Shadow properties to ViewStyle

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
Fix background blank issue of Switch
=> [NUI] Fix background blank issue of Switch

src/Tizen.NUI.Components/Controls/Switch.cs
Implement switch's Old background API
=> [NUI] Implement switch's Old background API

src/Tizen.NUI.Components/Style/ButtonStyle.cs, src/Tizen.NUI.Components/Style/ControlStyle.cs, src/Tizen.NUI.Components/Style/DropDownStyle.cs, src/Tizen.NUI.Components/Style/ImageControlStyle.cs, src/Tizen.NUI.Components/Style/LoadingStyle.cs, src/Tizen.NUI.Components/Style/PaginationStyle.cs, src/Tizen.NUI.Components/Style/PopupStyle.cs, src/Tizen.NUI.Components/Style/ProgressStyle.cs, src/Tizen.NUI.Components/Style/ScrollbarStyle.cs, src/Tizen.NUI.Components/Style/SliderStyle.cs, src/Tizen.NUI.Components/Style/SwitchStyle.cs, src/Tizen.NUI.Components/Style/TabStyle.cs, src/Tizen.NUI.Components/Style/ToastStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
1. Fix extents issue
2. Unified style format
- ACR:
=> [NUI] Fix extents issue and unified style format

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs, src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedVectorImageViewTest.cs
[NUI] Fix SetMinMaxFrameByMarker()'s not working issue in AnimatedVectorImageView
nothing
=> [NUI] Fix SetMinMaxFrameByMarker()'s not working issue in AnimatedVectorImageView

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Initialize pan direction to Vertical in constructor of ScrollableBase.
NONE
=> [NUI] Initialize pan direction of ScrollableBase to Vertical

src/Tizen.Sensor/Tizen.Sensor/EventArgs/AutoRotationSensorDataUpdatedEventArgs.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs, src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
[Tizen.Sensor][Add] Add auto rotation sensor
https://code.sec.samsung.net/jira/browse/TCSACR-297
- ACR:
=> [Sensor] Add auto rotation sensor

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Add ScrollEnabled property to ScrollableBase.
User can disable / enable scrolling using this property.
NONE
=> [NUI] Add ScrollEnabled property to ScrollableBase

src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Remove default LayoutTransition.
NONE
=> [NUI] Remove default LayoutTransition

src/Tizen.NUI.Components/Controls/Control.cs
=> [NUI] Control handle state `Pressed`

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
=> [NUI] Fix FittingMode bug

src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/Popup.cs
=> [NUI.Components] Fix svace issues

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
ScrollStartDragEvent      - Emitted when panning is start
ScrollEndDragEvent        - Emitted when panning is end
ScrollAnimationStartEvent - Emitted when scroll animation is start
ScrollAnimationEndEvent   - Emitted when scroll animation is end
NONE
=> [NUI] Add/change scroll event

src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs, src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs, src/Tizen.NUI/src/public/ViewProperty/ICloneable.cs, src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs, src/Tizen.NUI/src/public/ViewProperty/Shadow.cs, src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs
=> [NUI] Support Shadow Size Extents

src/Tizen.NUI/src/public/Key.cs
=> [NUI] Add dispose checking in key state

src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
=> [NUI] Fix NUI svace issue

src/Tizen.NUI/src/internal/GaussianBlurView.cs
Add GaussianBlurView.
For now user can use this class internally, because APIs are all hidden.
NONE
=> [NUI] Add GaussianBlurView

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Scrolls to the item at the specified index.
NONE
=> [NUI] Add ScrollToIndex to ScrollableBase

src/Tizen.Network.Smartcard/Tizen.Network.Smartcard/SmartcardManagerImpl.cs, src/Tizen.Network.Smartcard/Tizen.Network.Smartcard/SmartcardSession.cs
Signed-off-by: Jihoon Jung <jh8801.jung@samsung.com>
Because exception of Interop call, the TC was failed.
Internal implementation change
=> [NFC] Fix TC failed issue : the SEH exception occurs

src/Tizen.NUI/src/internal/Application.cs, src/Tizen.NUI/src/internal/ComponentApplication.cs, src/Tizen.NUI/src/internal/WatchApplication.cs, src/Tizen.NUI/src/internal/WidgetApplication.cs, src/Tizen.NUI/src/public/NUIFrameComponent.cs, src/Tizen.NUI/src/public/Widget.cs, src/Tizen.NUI/src/public/Window.cs
=> [NUI] Modify Instance bug of Application

src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationBinder.cs
- DateTimeKind.Local -> DateTimeKind.Utc
- ACR:
=> [Notification] Change TimeStamp of SafeHanlde

src/Tizen.Sensor/Interop/Interop.Sensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/Accelerometer.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/FaceDownGestureDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/GravitySensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/Gyroscope.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/GyroscopeRotationVectorSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/HumiditySensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/InVehicleActivityDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/LightSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/LinearAccelerationSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/Magnetometer.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/MagnetometerRotationVectorSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/OrientationSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/Pedometer.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/PickUpGestureDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/PressureSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/ProximitySensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/RotationVectorSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/RunningActivityDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/SleepMonitor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/StationaryActivityDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/TemperatureSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/UltravioletSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/UncalibratedGyroscope.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/UncalibratedMagnetometer.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/WalkingActivityDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/WristUpGestureDetector.cs, src/Tizen.Sensor/Tizen.Sensor/Sensor.cs
* sensor_listener_set_events_cb, sensor_listener_unset_events_cb
- ACR:
=> [Sensor] Modify implementation using new native API

src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/BaseComponent.cs
Adds:
- ContextHandle
Add a property on BaseComponent class
=> [ComponentBased] Add a property on BaseComponent

src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ComponentBasedApplication.cs
- Check if a component ID exists or not
=> [ComponentBased] Fix RegisterComponent Method

src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothData.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothSocket.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
Add new SendData API
ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-301
=> [Bluetooth][TCSACR-301] Add new SendData API

src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs, src/Tizen.NUI/src/internal/WidgetViewSignal.cs, src/Tizen.NUI/src/public/ImfManager.cs, src/Tizen.NUI/src/public/PropertyNotifySignal.cs
[NUI] Add removed API as hidden API to pass the tizen_5.5 TCT
nothing
=> [NUI] Add removed API as hidden API to pass the tizen_5.5 TCT

src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs, src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Commons.cs, src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/SingleShot.cs, src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsData.cs, src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsInfo.cs
This PR adds more functionality for `SingleShot` class and revises its related `TensorsData` and `TensorsInfo` classes.  Detailed items are as below.
* SingleShot class
- Support various Neural Network framework such as TensorFlow,
TensorFlowLite, Custom Filter or NNFW (default: Any)
- Support various HW resources such as CPU, GPU or NPU (default: Any)
- Load neural network model without Input / Output TensorsInfo
(Dynamic mode or model file has input/output information)
- Newly adds SetTimeout() to set the maximum amount of time to wait for an output
- Newly adds `Input` property for Input tensors information
- Newly adds `Output` property for Output tensors information
- Remove `IOException` since it does not occur
* TensorsData class
- Newly adds static Allocate() for TensorsData …
=> [MachineLearning.Inference] Update SingleShot and its related classes

src/Tizen.NUI.Components/PreloadStyle/DefaultStyle.cs, src/Tizen.NUI.Components/PreloadStyle/DefaultTabStyle.cs, src/Tizen.NUI.Components/Utils/StyleManager.cs
=> [NUI] Apply default style to Tab and Button component

src/Tizen.NUI.Components/PreloadStyle/DefaultStyle.cs, src/Tizen.NUI.Components/PreloadStyle/DefaultTabStyle.cs, src/Tizen.NUI.Components/Utils/StyleManager.cs
=> [NUI] Apply default style to Tab and Button component (#1401)

src/Tizen.NUI/src/public/Animation.cs
[NUI] Fix TCT crash issue
nothing
=> [NUI] Fix TCT crash issue

src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs
[Bundle] Separate exceptions for invalid handle
=> [Bundle] Separate exceptions for invalid handle

src/Tizen.Applications.MessagePort/Tizen.Applications.Messages/MessagePort.cs
To avoid throwing an exception in the callback function, this patch adds
an exception handling about Creating Bundle().
=> [MessagePort] Fix Listen Method

src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs, src/Tizen.Multimedia.MediaCodec/Tizen.Multimedia.MediaCodec.sln
Add missing registration code for EosReached event.
Add Tizen.Applications.ComponentBased project into MediaCodec solution.
=> [MediaCodec] Register EosReached event

src/Tizen.NUI/src/internal/Layouting/LayoutController.cs, src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs, src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Not every developer wants default transition effect in Layout.
For them, make property which can enable or disable transition effect.
Currently, default is false but can be changed.
This property only effects to chilren of Layout Owner.
NONE
=> [NUI] Add property LayoutWithTransition to LayoutItem

src/ElmSharp/ElmSharp/GestureLayer.cs, src/ElmSharp/Interop/Interop.Elementary.GestureLayer.cs
Fix internal implementation related with GetstureLayer native callback
- ACR: None
=> [ElmSharp] Fix GestureLayer native callback return type

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
To listen scroll changing, add ScrollEvent to ScrollableBase and
add Position param to ScrollEventArgs.
Now user can get current position of scrolling child via ScrollEventArgs.
NONE
=> [NUI] Add ScrollEvent to ScrollableBase

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs, src/Tizen.NUI/src/public/Window.cs
Add to set Available Orientations.
It is for adding several orientations one time.
=> [NUI] Add to set Available Orientations

src/Tizen.Multimedia/AudioManager/AudioDevice.cs, src/Tizen.Multimedia/AudioManager/AudioDeviceOptions.cs, src/Tizen.Multimedia/AudioManager/AudioDeviceState.cs, src/Tizen.Multimedia/AudioManager/AudioDeviceStateChangedEventArgs.cs, src/Tizen.Multimedia/AudioManager/AudioManager.cs, src/Tizen.Multimedia/Interop/Interop.Device.cs
=> Revert "[AudioManager] Remove deprecated symbols"

src/Tizen.Applications.Alarm/Tizen.Applications/Alarm.cs
[Applications.Alarms] Update doxygen
=> [Applications.Alarms] Update doxygen

packaging/csapi-tizenfx.spec
=> [Build] Set smack labels of symbol files

src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs, src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs, src/Tizen.NUI/src/public/WindowEvent.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DimTest.cs
[NUI] Fix to get bezel wheel event on wearable device by WheelEvent
nothing
=> [NUI] Fix to get bezel wheel event on wearable device by WheelEvent

packaging/csapi-tizenfx.spec, packaging/csapi-tizenfx.spec.in, packaging/makerid.py, packaging/makespec.sh, pkg/Tizen.NET/runtime.json
=> [Build] Add RIDs of Tizen.6.0.0 and Set RIDs to vconf automatically

packaging/csapi-tizenfx.spec, packaging/csapi-tizenfx.spec.in, packaging/makerid.py, packaging/makespec.sh, pkg/Tizen.NET/runtime.json
=> [WIP][Build] Add RIDs of Tizen.6.0.0 and Set RIDs to vconf automatically

src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs, src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs, src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs, src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs, src/Tizen.NUI/src/public/VisualConstants.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ControlSample.cs
=> [NUI] Apply CornerRadius to View

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedImageViewTest.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedVectorImageViewTest.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ButtonSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CheckBoxSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCard.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCardLayouter.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCardsSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ControlSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CubeTransitionEffectSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliTableView.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DropDownSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FlexibleViewSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ItemViewDemo/ItemViewSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LoadingSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationTest.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PaginationSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ProgressSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RadioButtonSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollBarSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SliderSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SwitchSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TabSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ToastSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VideoViewTest.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
=> [NUI] Remove Window.Instance from the sample code

src/Tizen.NUI/src/internal/EnumHelper.cs, src/Tizen.NUI/src/internal/Extensions.cs, src/Tizen.NUI/src/internal/XamlBinding/ExtentsTypeConverter.cs, src/Tizen.NUI/src/internal/XamlBinding/PositionTypeConverter.cs, src/Tizen.NUI/src/internal/XamlBinding/RectangleTypeConverter.cs, src/Tizen.NUI/src/internal/XamlBinding/RotationTypeConverter.cs, src/Tizen.NUI/src/internal/XamlBinding/VectorTypeConverter.cs, src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs, src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs, src/Tizen.NUI/src/public/Window.cs, src/Tizen.NUI/src/public/XamlBinding/ColorTypeConverter.cs, src/Tizen.NUI/src/public/XamlBinding/SizeTypeConverter.cs, src/Tizen.NUI/src/public/XamlBinding/TypeConverter.cs
1. Add ojbect dump fucntion for NUI.
2. Call clear backgound when setting Backgound.
- ACR:
=> [NUI] Add object dump function

src/Tizen.NUI/src/internal/Interop/Interop.WindowVisibilityChangedSignal.cs, src/Tizen.NUI/src/internal/WindowVisibilityChangedEvent.cs, src/Tizen.NUI/src/public/WindowEvent.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples.sln, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisibilityChangedTest.cs
[NUI] Add Window VisibilityChanged Event
nothing
=> [NUI] Add Window VisibilityChanged Event

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs, src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
When changing sibling order of view, layout sibling order should be changed
to apply new position of order changed view.
Add API for changing layout sibling order and call it when changing view sibling order.
NONE
=> [NUI] Add API for changing layout sibling order

src/Tizen.NUI/src/internal/Layouting/GridLocations.cs, src/Tizen.NUI/src/public/Layouting/GridLayout.cs
=> [NUI] Add Horizontal Grid

src/Tizen.Applications.Alarm/Tizen.Applications/AlarmManager.cs
[Applications.Alarm] Add a new Enum for standard period
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-309
=> [Applications.Alarm] Add a new Enum for standard period

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GridLayoutSample.cs
=> [NUI] Add GridLaoyt Sample

src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs, src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/SingleShot.cs
In SingleShot class, add new API to set/get the property.
The property is related with the tensor information, a model may not support the change after open the model.
Added:
- void SetValue(string name, string value);
- string GetValue(string name);
ACR
- [TCSACR-308](https://code.sec.samsung.net/jira/browse/TCSACR-308)
Signed-off-by: Jaeyun <jy1210.jung@samsung.com>
=> [MachineLearning.Inference] new API to set/get the property

packaging/PlatformFileList.txt
Add common for Tizen.MachineLearning.Inference dll
ML APIs may be included in RPI4.
Signed-off-by: Jaeyun <jy1210.jung@samsung.com>
=> [Build] [MachineLearning.Inference] update PlatformFileList

packaging/csapi-tizenfx.spec.in
* Set smack labels of symbol files in spec.in (debug package)
Original PR: #1449
=> [Build] Set smack labels of symbol files in .spec.in

src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
If true, set position by layouting result.
If false, will not set position in SetFrame because it means it's parent like
RecyclerList will set position.
NONE
=> [NUI] Add SetPositionByLayout Property

src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
=> [API6][Applications] Update CurrentUICulture when Locale was changed

src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
=> [API7][Application] Update CurrentUICulture when Locale was changed

src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
=> [Applications] Update CurrentUICulture when Locale was changed

src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/SingleShot.cs
Change repo url, link to nnstreamer project.
Signed-off-by: Jaeyun <jy1210.jung@samsung.com>
=> [MachineLearning.Inference] change repo url

src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapter.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEnumerations.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapter.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
BluetoothLeAdapter.SetScanMode
https://code.sec.samsung.net/jira/browse/TCSACR-311
=> [Bluetooth][TCSACR-311] Add SetScanMode API

src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs, src/Tizen.NUI/src/public/ViewProperty/TextShadow.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ButtonSample.cs
=> [NUI] Support text shadow

src/Tizen.NUI/src/internal/NUIWidgetCoreBackend.cs, src/Tizen.NUI/src/internal/WidgetApplication.cs, src/Tizen.NUI/src/public/NUIWidgetApplication.cs
=> [NUI] Add API for adding WidgetInfo in runtime

src/Tizen.System.Information/Common/Information.cs
* dotnet-launcher calls the preload method of the information.
Origin PR : #1492
=> [Information] Added preload method for optimization

src/Tizen.NUI/src/internal/Application.cs, src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs, src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs, src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs, src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs, src/Tizen.NUI/src/public/GraphicsTypeConverter.cs, src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs, src/Tizen.NUI/src/public/Layouting/LayoutItem.cs, src/Tizen.NUI/src/public/NUIApplication.cs, src/Tizen.NUI/src/public/WindowEvent.cs, src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs
=> [NUI] Change Window.Instance to NUIApplication.GetDefaultWindow()

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GridLayoutSample.cs
- 'LinearOrientation' of GridLayout changed to 'GridOrientation'.
- Changed API name in the sample.
- N/A
=> [NUI] Fix GridLayoutSample

src/ElmSharp/ElmSharp/Window.cs, src/ElmSharp/Interop/Interop.Elementary.Win.cs
Add internal Window auxiliary hint APIs
Added:
- int AddAuxiliaryHint(string hint, string value)
- bool DeleteAuxiliaryHint(int id)
- bool SetAuxiliaryHintValue(int id, string value)
- string GetAuxiliaryHintValue(int id)
- int GetAuxiliaryHintId(string hint)
=> [ElmSharp] Add internal Window auxiliary hint APIs

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapter.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
Fix app crash issue during free
=> [Tizen.Network.Bluetooth][Non-ACR] Fix app crash issue during free

src/Tizen.NUI/src/internal/Interop/Interop.NativeImageSource.cs, src/Tizen.NUI/src/internal/NativeImageInterface.cs, src/Tizen.NUI/src/public/NativeImageSource.cs, src/Tizen.NUI/src/public/Texture.cs
[NUI] Add NativeImageSource
nothing
=> [NUI] Add NativeImageSource

src/Tizen.NUI.Components/PreloadStyle/WearableTheme.cs
=> [NUI] Update wearable button style by UX guide

test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSFontTypeChangedEventArgs.cs, test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSSystemSettings.cs
Fix unit test to process about "Not supported case"
=> Fix unit test for Tizen.System.SystemSettings

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VideoViewTest.cs
[NUI] Fix VideoView sample
nothing
=> [NUI] Fix VideoView sample

src/Tizen.NUI.Components/Utils/StyleManager.cs
[NUI] Fix NUI.Components TCT fail
nothing
=> [NUI] Fix NUI.Components TCT fail

src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Do not catch the exception thrown by event handler of app
The applications should be responsible its exception, they should
determine handle or not the exception.
N/A
=> [Packagemanager] Do not catch the exception thrown by event handler of app

src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
=> [Applications.Common] Remove unnecessary lock

src/Tizen.NUI/src/internal/Camera.cs, src/Tizen.NUI/src/internal/FrameBuffer.cs, src/Tizen.NUI/src/internal/RenderTask.cs
Some class need to be changed for internal purpose.
Add Never tag to hide API.
NONE
=> [NUI] Add hidden class for internal purpose

src/Tizen.NUI.Components/Style/ToastStyle.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
[NUI] Add Color in ViewStyle
nothing
=> [NUI] Add Color in ViewStyle

src/Tizen.NUI/src/internal/Application.cs, src/Tizen.NUI/src/internal/Interop/Interop.Application.cs, src/Tizen.NUI/src/public/Layouting/LayoutItem.cs, src/Tizen.NUI/src/public/NUIApplication.cs
=> [NUI] Add dotnet pre-initiailze

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Tab.cs
[NUI] Fix TCT fail issues by adding null check
nothing
=> [NUI] Fix TCT fail issues by adding null check

src/Tizen.NUI/src/public/PropertyNotification.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PropertyNotificationTest.cs
[NUI] Fix PropertyNotification.GetTarget() error
nothing
=> [NUI] Fix PropertyNotification.GetTarget() error

src/Tizen.Multimedia.Camera/Camera/CameraEnums.cs, src/Tizen.Multimedia.Camera/Camera/EncodedPlane.cs, src/Tizen.Multimedia.Camera/Camera/PreviewFrame.cs, src/Tizen.Multimedia.Camera/Interop/Interop.Camera.cs
Add new preview format for MJPEG.
- TCSACR-312
=> [Camera] Add new preview format

src/Tizen.NUI/src/internal/Layouting/LayoutController.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
We used LayoutItem and LayoutGroup as default layout but many developer wants to use AbsoluteLayout as default.
So changed default layout to AbsoluteLayout.
NONE
=> [NUI] Change default layout to AbsoluteLayout

src/Tizen.NUI.Components/Controls/ButtonGroup.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Style/PopupStyle.cs, src/Tizen.NUI.Components/Utils/StyleManager.cs, src/Tizen.NUI/src/public/BaseComponents/Style/Constants.cs, src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs, src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs, src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs, src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs, src/Tizen.NUI/src/public/Rectangle.cs, src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs, src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs, src/Tizen.NUI/src/public/ViewProperty/Shadow.cs, src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs, src/Tizen.NUI/src/public/VisualConstants.cs
=> [NUI] Add Shadow BlurRadius and lighten View size

src/Tizen.System.PowerUsage/Interop/Interop.Libraries.cs, src/Tizen.System.PowerUsage/Interop/Interop.PowerUsage.cs, src/Tizen.System.PowerUsage/PowerUsage/PowerUsage.cs, src/Tizen.System.PowerUsage/PowerUsage/PowerUsageExceptionFactory.cs, src/Tizen.System.PowerUsage/Tizen.System.PowerUsage.csproj, src/Tizen.System.PowerUsage/Tizen.System.PowerUsage.sln
ACR : https://code.sec.samsung.net/jira/browse/TCSACR-310
pull request in API7 : #1512
=> [System.PowerUsage] Introduce Tizen.System.PowerUsage

src/Tizen.NUI/src/internal/Interop/Interop.InputMethodContext.cs, src/Tizen.NUI/src/public/InputMethodContext.cs
- Added SetInputPanelLanguage and GetInputPanelLanguage.
- Opened some InputMethodContext APIs as public.
- ACR: TCSACR-315 (https://code.sec.samsung.net/jira/browse/TCSACR-315)
=> [NUI] Add InputMethodContext public APIs

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs, src/Tizen.NUI/src/public/Layer.cs, src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
=> [NUI] Make some API to public and fill missing comments.

packaging/PlatformFileList.txt
ACR : https://code.sec.samsung.net/jira/browse/TCSACR-310
pull request : #1512
=> Addition of Tizen.System.PowerUsage.dll

src/Tizen.WebView/Interop/Interop.ChromiumEwk.View.cs, src/Tizen.WebView/Tizen.WebView/WebView.cs
Signed-off-by: yh106.jung <yh106.jung@samsung.com>
Add new WebView API, Tizen.WebView.EvalAsync
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-316
Added:
- async Task<string> EvalAsync(string script)
=> [WebView] Add new WebView API, Tizen.WebView.EvalAsync

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs, src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
=> [NUI] Apply CornerRadius to ImageView

packaging/PlatformFileList.txt
Change-Id: I399054d5f80d1d8c00afc79fffa08d833fba3b93
Fix `PlatformFileList.txt` to reflect filename chagne
No API Changes
=> [Build] Fix `PlatformFileList.txt` to reflect filename chagne

src/Tizen.NUI.Components/Controls/Notification.cs
=> [NUI] Introduce Notification

src/Tizen.System.PowerUsage/Interop/Interop.PowerUsage.cs, src/Tizen.System.PowerUsage/PowerUsage/PowerUsage.cs
changed data type of time for compatibility with native layer
=> [PowerUsage] Fix to change data type of time

src/Tizen.NUI.Components/Controls/Notification.cs, src/Tizen.NUI/src/public/WindowEvent.cs
=> [NUI] Make instanceSet to hold notification windows and fix Window.TouchEvent bug

src/Tizen.Sensor/Tizen.Sensor/BatchSensor.cs
=> [Sensor] Initialize data for batch type sensor

src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs, src/Tizen.Multimedia.Vision/MediaVision/InferenceType.cs, src/Tizen.Multimedia.Vision/Tizen.Multimedia.Vision.sln
Signed-off-by: Tae-Young Chung <ty83.chung@samsung.com>
Add and deprecate enumerations.
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-318
=> [MediaVision] Add and deprecate enumerations

src/Tizen.Network.Stc/Tizen.Network.Stc/StcManagerImpl.cs
Fixed the crash when timeout exception was occurring.
=> Returned the code on exception

src/Tizen.NUI.Wearable/src/public/Title.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TitleSample.cs
The Title inherits TextLabel.
The Title can has a fadeOut effects on the left and right side.
- ACR: NONE
=> [NUI] Add Title in Wearable component

src/Tizen.NUI.Wearable/src/internal/NUIWatchCoreBackend.cs
Get language from device.
- ACR:
=> [NUI.Wearable] Modify LanguageChanged bug

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs, src/Tizen.NUI/src/public/Window.cs
[NUI] Add GetWindowId()
nothing
=> [NUI] Add GetWindowId()

src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
A callback declared in a method can be collected by garbage collector.
Add a Dictionary to keep callbacks to be used in each method.
=> [Tizen.Network.Connection] Make callbacks to member variable

src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs, src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
=> [NUI] Modify to use NDalicPINVOKE.Lib

src/Tizen.Multimedia.Vision/Interop/Interop.Libraries.cs, src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.BarCode.cs, src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Common.cs, src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Face.cs, src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Image.cs, src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Inference.cs, src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Surveillance.cs
libcapi-media-vision.so.0 is replaced by sub-libraries.
Signed-off-by: Kwang Son <k.son@samsung.com>
=> [Vision] Change DLLImport file

src/Tizen.Sensor/Tizen.Sensor/EventArgs/AutoRotationSensorDataUpdatedEventArgs.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitorBatch.cs, src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
=> [Sensor] Update sensor description for better understanding.

src/Tizen.NUI.Components/Controls/ImageScrollBar.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/ScrollbarBase.cs, src/Tizen.NUI.Components/Style/ImageScrollBarStyle.cs, src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs, src/Tizen.NUI.Wearable/src/public/WearableStyle/CircularScrollbarStyle.cs, src/Tizen.NUI/src/public/VisualConstants.cs, src/Tizen.NUI/src/public/VisualMaps.cs, src/Tizen.NUI/src/public/Visuals/ArcVisual.cs, src/Tizen.NUI/src/public/Visuals/ColorVisual.cs
* Implement Arc Visual to support arc shapes used in CircularScrollbar
* Move previous ScrollBar class code from Scrollbar.cs to ImageScrollBar.cs.
* Implement new Scrollbar class based on a ScrollbarBase class.
* Implement new CircularScrollbar class based on a ScrollbarBase class.
- ACR:
=> [NUI] Add Scrollbar and CircularScrollbar

src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
=> [NUI] Make a color visual of View's shadow to center aligned

src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/ScrollbarBase.cs, src/Tizen.NUI.Components/Style/ScrollbarStyle.cs, src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs, src/Tizen.NUI.Wearable/src/public/WearableStyle/CircularScrollbarStyle.cs
* Previously, viewSize represents viewport size, but in some cases they are not the same value.
* View size : Implement OnRelayout of Scrollbar to respond to response to size changes.
* Viewport size : Receive by user when initialize.
- ACR:
=> [NUI] Scrollbar : Separate the concept of viewport size and view size.

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CircularPaginationSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs
- Removed WindowMode.Transparent in DaliDemo.cs.
- Not be able to see the sample table because of transparent value.
- Updated CircularPagination position.
- N/A
=> [NUI] Update Tizen.NUI.Samples slightly

src/Tizen.NUI.Components/Controls/RecyclerView/LayoutManager.cs, src/Tizen.NUI.Components/Controls/RecyclerView/LinearLayoutManager.cs, src/Tizen.NUI.Components/Controls/RecyclerView/RecycleAdapter.cs, src/Tizen.NUI.Components/Controls/RecyclerView/RecycleItem.cs, src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs, src/Tizen.NUI.Components/Controls/ScrollableBase.cs, src/Tizen.NUI.Wearable/src/internal/FishEyeLayoutManager.cs, src/Tizen.NUI.Wearable/src/public/WearableList.cs, src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
First version of RecyclerView.
RecyclerView is a component that can improve performance by reusing user-defined child.
User can define what the child will look like through creating function in RecycleAdapter.
RecyclerView creates its children using this function and bind data with child if child is ready to shown.
NONE
=> [NUI] First version of RecyclerView

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Scrollbar.cs, src/Tizen.NUI.Components/Controls/ScrollbarBase.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs
(a) Provide APIs to access sub-components of the component (e.g. Button.ButtonIcon)
=> [NUI] Provide APIs to access sub-components

src/ElmSharp/ElmSharp/EcoreKeyEventArgs.cs
This PR fix internal EcoreEventKey struct to synchronize with native struct
None
=> [ElmSharp] Update internal EcoreEventKey struct

src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/PreloadStyle/DefaultTheme.cs, src/Tizen.NUI.Components/Style/Theme.cs
Add default DropDown item style
=> [NUI] Add default DropdownItemStyle

src/Tizen.NUI/src/public/BaseComponents/View.cs, src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Made the value of Size be consistent with Specification for the defect of adding layout
=> [NUI] Made the value of Size be consistent with Specification

src/Tizen.Applications.Notification/Tizen.Applications.Notifications/Notification.cs
Fix wrong comments for API reference documents.
There are incorrect property name and syntax error.
- ACR:
=> [Notification] Fix wrong example code comments

src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs, src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs, src/Tizen.NUI/src/public/BaseComponents/TextField.cs
TextField Add support for:
1- SeletedText property.
2- SelectNone function.
=> [NUI]TextField: SelectNone and SelectedText

src/Tizen.NUI.Components/Controls/RecyclerView/LinearLayoutManager.cs, src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
Change Layout and Recycle rule for linear layout.
NONE
=> [NUI] Fix LinearListLayoutManager

src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
- No need to be transparent in minimum value
- N/A
=> [NUI] Remove unnecessary opacity in CircularProgress

src/Tizen.NUI.Components/Controls/Pagination.cs
Add the function of ApplyStyle for Pagination
=> [NUI] Add ApplyStyle for Pagination

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Program.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/SampleMain.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ButtonSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CheckBoxSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCardLayouter.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCardsSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactData.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/MaskedImage.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CubeTransitionEffectSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DropDownSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FlexibleViewSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ItemViewDemo/ItemViewSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LoadingSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PaginationSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ProgressSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RadioButtonSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollBarSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SliderSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SwitchSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TabSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ToastSample.cs
1.Refine codes because APIs changed 
https://github.com/Samsung/TizenFX/pull/1568
2.Add layouts for samples
=> [NUI]Add layouts and refine codes for Samples

src/Tizen.NUI.Wearable/src/public/CircularProgress.cs, src/Tizen.NUI.Wearable/src/public/WearableStyle/CircularPaginationStyle.cs, src/Tizen.NUI.Wearable/src/public/WearableStyle/CircularProgressStyle.cs
- Added default indicator size to CircularPagination.
- Changed the names of bindable properties.
- Added Stop() before creating Animation with visual.
- N/A
=> [NUI] Update Wearable default style

src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
Add MIN_LINE_SIZE property at TextLabel
- ACR: NONE
=> [NUI] Add MIN_LINE_SIZE property at TextLabel

src/Tizen.NUI.Wearable/src/public/CircularSlider.cs, src/Tizen.NUI.Wearable/src/public/WearableStyle/CircularSliderStyle.cs
-  Add CircularSlider class to Tizen.NUI.Wearable
- N/A
=> [NUI] Add CircularSlider to Wearable Component

src/Tizen.NUI.Components/Controls/Pagination.cs
Replace paginationStyle with Style
=> [NUI] Replace paginationStyle with Style

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Previously, we calculated max scroll distance in begining of pan gesture.
It made user cannot use ScrollTo API until panning.
For now, calculate MaxScrollDistance when scrolling container is relayouted.
NONE
=> [NUI] Calculate MaxScrollDistance in Relayout

src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/PrivacyPrivilegeManager.cs
Refer : https://github.com/Samsung/TizenFX/pull/1650
- ACR:
=> [API7][Security] Fix PrivacyPrivilegeManager.RequestPermissions crash issue

src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/PrivacyPrivilegeManager.cs
This PR fix PrivacyPrivilegeManager.RequestPermissions crash issue
None
=> [Security] Fix PrivacyPrivilegeManager.RequestPermissions crash issue

src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
Since child position property and dali position property that decides
real position of controls are shared as same property(View.Position),
AbsoluteLayout cannot respect margin, padding for child position. so,
we don't need to calculate size with margin, padding.
- ACR:
=> [NUI] remove margin, padding calculation for AbsoluteLayout child size

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/Control.cs, test/NUITestSample/NUIXAMLTestSample/CommandDemo/CommandDemo.xaml, test/NUITestSample/NUIXAMLTestSample/CommandDemo/CommandDemo.xaml.cs, test/NUITestSample/NUIXAMLTestSample/CommandDemo/CommandDemoApplication.cs, test/NUITestSample/NUIXAMLTestSample/NUIXAMLTestSample.cs, test/NUITestSample/NUIXAMLTestSample/NUIXAMLTestSample.csproj
=> [NUI] Add command for button

src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs, src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
This reverts commit b949a3d1015a0ce1ad9831ca91c58b13437d4cef.
- ACR:
=> Revert "[NUI] Add MIN_LINE_SIZE property at TextLabel (#1619)"

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
=> [Bluetooth][Non-ACR] Fix Native callback GC issue

src/Tizen.NUI.Components/Controls/RecyclerView/GridRecycleLayoutManager.cs, src/Tizen.NUI.Components/Controls/RecyclerView/LinearRecycleLayoutManager.cs, src/Tizen.NUI.Components/Controls/RecyclerView/RecycleLayoutManager.cs, src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs, src/Tizen.NUI.Components/Controls/ScrollableBase.cs, src/Tizen.NUI.Wearable/src/internal/FishEyeLayoutManager.cs, src/Tizen.NUI.Wearable/src/public/WearableList.cs
Grid Layout for RecyclerView.
When user set Orientation, GridRecycleLayoutManager will lay out items using only one factor between Row and Column.
Horizontal => Row
Vertical => Column
NONE
=> [NUI] Add GridRecycleLayotManager

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
=> [Bluetooth][Non-ACR] Fix Native callback GC issue (#1678)

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/CheckBox.cs, src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs, src/Tizen.NUI.Components/Controls/Control.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/ImageScrollBar.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/RadioButton.cs, src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs, src/Tizen.NUI.Components/Controls/ScrollableBase.cs, src/Tizen.NUI.Components/Controls/SelectButton.cs, src/Tizen.NUI.Components/Controls/SelectGroup.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs, src/Tizen.NUI.Components/Utils/StyleManager.cs, src/Tizen.NUI.Wearable/src/public/WearableList.cs
This would fix CA1051 warnings which indicates that
"Do not declare visible instance fields".
- ACR:
=> [NUI] replace field declaration with property

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/CheckBox.cs, src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs, src/Tizen.NUI.Components/Controls/Control.cs, src/Tizen.NUI.Components/Controls/DropDown.cs, src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs, src/Tizen.NUI.Components/Controls/ImageScrollBar.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/RadioButton.cs, src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs, src/Tizen.NUI.Components/Controls/ScrollableBase.cs, src/Tizen.NUI.Components/Controls/SelectButton.cs, src/Tizen.NUI.Components/Controls/SelectGroup.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs, src/Tizen.NUI.Components/Controls/Toast.cs, src/Tizen.NUI.Components/Utils/StyleManager.cs, src/Tizen.NUI.Wearable/src/public/WearableList.cs
=> Revert "[NUI] replace field declaration with property"

src/Tizen.NUI/src/internal/Layouting/GridLocations.cs, src/Tizen.NUI/src/public/Layouting/GridLayout.cs, src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
[NUI] GridLayout Refactoring to support column, row, spacing, weight, align
1) Add `ColumnSpacing`, `RowSpacing` (GridLayout Property)
This is GridLayout properties for the distance between columns, rows.
2) Add `Column`, `ColumnSpan`, `Row`, `RowSpan` (Child Property)
This is child properties for specific cell index to layout. `SetChildValue` is
added to support child property using Attached Bindable Property.
If the Column(Row) isn't defined, it is automatically assigned left to right or
top to bottom depending on `GridOrientation`(RTL is not supported yet).
The main axis count(Columns on Horizontal mode, Rows otherwise) won't be
exceeded explicit column(row) count which is assigned by
Property(`Columns`(`Rows`)). otherwise, cross axis count(row(column))
can be increased.
Children with …
=> [NUI] GridLayout Refactoring to support column, row, spacing, weight, align

src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcTag.cs
This PR fix https://github.com/Samsung/TizenFX/issues/1670
- ACR:
=> [NFC] Fix Native callback GC issue

src/Tizen.NUI.Components/Controls/Button.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ButtonSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CheckBoxSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DropDownSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RadioButtonSample.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TabSample.cs
Change the button APIs' names and modify the related Samples for it.
=> [NUI] Change button APIs and modify related Samples

src/Tizen.NUI.Components/Controls/Loading.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LoadingSample.cs
Remove the Loading API of Images and replace it with ImageArray
=> [NUI] Remove the Loading API of Images

src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SliderSample.cs
Remove 
1. LowIndicatorText of Slider
2. HighIndicatorText of Slider
3. TrackPadding of Slider
4. SwitchBackgroundImageURL of Switch
=> [NUI] Remove deprecated APIs in Slider and Switch

src/Tizen.NUI.Components/Controls/ScrollableBase.cs, src/Tizen.NUI.Wearable/src/public/WearableList.cs
Add Scrollbar Property to ScrollableBase.
Currently, Scrollbar is always hidden but show if set HideScrollBar to true.
NONE
=> [NUI] Add Scrollbar Proprety to ScrollableBase

src/Tizen.Sensor/Tizen.Sensor/BatchData/BatchData.cs, src/Tizen.Sensor/Tizen.Sensor/BatchData/HeartRateMonitorBatchData.cs, src/Tizen.Sensor/Tizen.Sensor/BatchData/HeartRateMonitorLEDGreenBatchData.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitorBatch.cs, src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitorLEDGreenBatch.cs, src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
=>  [Sensor] Update sensor description regarding batch sensor.

src/Tizen.NUI.Components/Controls/Control.cs
=> [NUI] remove unused parameter from Control.Initialize

src/Tizen.NUI/src/public/BaseComponents/View.cs
Fixes CA1051
Depends on #1679
- ACR:
=> [NUI] make viewStyle field private

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
=> [NUI] fix c&p error

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapter.cs
=> [Bluetooth][Non-ACR] Fix GattConnection event not occured issue

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
=> [Bluetooth][Non-ACR] Fix NULL reference exception issue

src/Tizen.NUI/src/internal/ComponentApplication.cs, src/Tizen.NUI/src/internal/NUIComponentCoreBackend.cs, src/Tizen.NUI/src/public/NUIFrameComponent.cs
=> [NUI] Modify Component-application window

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudio.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudioImpl.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothOpp.cs, src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothOppImpl.cs
=> [Bluetooth][Non-ACR] Fix invalid sender issue

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs, src/Tizen.NUI/src/internal/NUIWindowInfo.cs, src/Tizen.NUI/src/public/Window.cs
=> [NUI] Change to use GetNativeId()

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
[NUI] Modify comments
apply document review of https://github.com/Samsung/TizenFX/pull/1129
none
=> [NUI] Modify comments

src/Tizen.NUI.Wearable/Tizen.NUI.Wearable.csproj
[NUI] Fix NUI.Wearable build install fail
none
=> [NUI] Fix NUI.Wearable build install fail

src/Tizen.NUI/src/public/NUIConstants.cs, src/Tizen.NUI/src/public/VisualMaps.cs
=> [Docs] Fix documentation warnings

src/Tizen.Applications.WidgetControl/Interop/Interop.WidgetService.cs, src/Tizen.Applications.WidgetControl/Tizen.Applications/WidgetControl.cs
Signed-off-by: SukHyung, Kang <shine.kang@samsung.com>
Add new property for setup app id
- ACR: https://code.sec.samsung.net/jira/browse/TSACR-325
Changed:
- Add
public string SetupAppId
=> [WidgetControl] Add property for setup app id

src/Tizen.Multimedia.Camera/Camera/Camera.cs, src/Tizen.Multimedia.Camera/Interop/Interop.CameraDisplay.cs
Support NUI window for preivew
=> [Camera] Support NUI window for preview

src/Tizen.NUI.Components/Utils/StyleManager.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-330
=> [NUI] Hide NUI.Component.StyleManager

src/Tizen.NUI.Components/Controls/ImageScrollBar.cs, src/Tizen.NUI.Components/Style/ImageScrollBarStyle.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-332
=> [NUI] Hide legacy ScrollBar and corresponding style class

src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs, src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.Internal.cs, src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs, src/Tizen.NUI.Components/Controls/RecyclerView/GridRecycleLayoutManager.cs, src/Tizen.NUI.Components/Controls/RecyclerView/LinearRecycleLayoutManager.cs, src/Tizen.NUI.Components/Controls/RecyclerView/RecycleLayoutManager.cs, src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs, src/Tizen.NUI.Wearable/src/internal/FishEyeLayoutManager.cs, src/Tizen.NUI.Wearable/src/public/WearableList.cs
=> [NUI] change to protected property from field

src/Tizen.NUI.Components/Controls/Button.Internal.cs, src/Tizen.NUI.Components/Controls/Popup.cs, src/Tizen.NUI.Components/Controls/Progress.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs, src/Tizen.NUI.Components/Controls/Tab.cs
=> [NUI] Remove OnThemeChangedEvent from controls

src/Tizen.Applications.Common/Tizen.Applications/TizenSynchronizationContext.cs
This patch removes using ContainsKey() of ConcurrentDictionary.
This patch removes using ContainsKey() of ConcurrentDictionary.
To check the action existence, checking the return value of TryRemove() is added.
=> [Applications.Common] Fix Handler of GSourceManager

src/Tizen.NUI.Components/Controls/Button.cs, src/Tizen.NUI.Components/Controls/CheckBox.cs, src/Tizen.NUI.Components/Controls/RadioButton.cs, src/Tizen.NUI.Components/Controls/Slider.cs, src/Tizen.NUI.Components/Controls/Switch.cs
Open the APIs of Button/CheckBox/RadioButton/Slider/Switch
- ACR:https://code.sec.samsung.net/jira/browse/TCSACR-327
=> [NUI] Open the APIs of Button/CheckBox/RadioButton/Slider/Switch

src/Tizen.System.Feedback/Feedback/Feedback.cs
[Feedback][refactor] Change struct array to Dictionary<string, int>
=> [Feedback] Change struct array to Dictionary<string, int>

src/Tizen.NUI.Components/Controls/Notification.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-331
=> [NUI] Make Notification APIs public and fix CA warnings.

src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs, src/Tizen.Multimedia.Vision/MediaVision/InferenceType.cs
Support new inference backend engine - MLApi, One
- TCSACR-
=> [MediaVision] Support new inference backend engine - MLApi, One

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
vectorImageVisualIndex is wrong.
Get property value index from dali(ImageView.Property.IMAGE)
=> [NUI] Fix lottie animation bug
