- src/Tizen.Multimedia.Remoting/MediaController/MediaControlMetadata.cs
Fix metadata bug when native handle is null.
> [MediaController] Fix metadata bug

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Controls/Tab.cs
- src/Tizen.NUI.Components/Controls/Toast.cs
- src/Tizen.NUI.Components/Style/PopupStyle.cs
- src/Tizen.NUI.Components/Style/TabStyle.cs
- src/Tizen.NUI.Components/Style/ToastStyle.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-335
> [NUI] Hide classes that will be move to specific tizen profile

- src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
> [NUI] Support implicit value in Xaml

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Page will be changed when velocity of pan is over PageFlickThreshold.
And user can change alphafunction of scroll animation.
NONE
> [NUI] Add PageFlickThreshold and ScrollAlphaFunction

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpControl.cs
> [Bluetooth][TCSACR-323] Fix AvrcpControl methods document

- src/Tizen.Multimedia/MediaTool/MediaFormatAudioMimeType.cs
- src/Tizen.Multimedia/MediaTool/MediaFormatVideoMimeType.cs
Add new audio, video mimetypes
- TCSACR-337
> [MediaTool] Add new audio/video mimetype

- src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs
- src/Tizen.Multimedia.Vision/MediaVision/InferenceType.cs
Update some descriptions to clarify the meaning of sentence.
- requested in https://github.com/Samsung/TizenFX/pull/1580
> [MediaVision] Update descriptions

- src/Tizen.NUI.Components/Controls/Loading.cs
Fix Loading size property not work
- None
> [NUI] Fix Loading size property not work

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Add ReleasePolicy to allow the application to determine the release policy of the image
- ACR:
> [NUI] Add ReleasePolicy for ImageView

- src/Tizen.NUI.Components/Utils/StyleManager.cs
> [NUI] Fix the issue that theme could not be changed

- src/Tizen.Multimedia.Metadata/MetadataEditor/MetadataEditor.cs
Supports WAV, FLAC and OGG file format in MetadataEditor.
- TCSACR-339
> [MetadataEditor] Supports new file formats - WAV, FLAC and OGG

- src/Tizen.Multimedia.AudioIO/AudioIO/AudioCapture.cs
- src/Tizen.Multimedia.AudioIO/Interop/Interop.AudioIO.cs
Add new volume property to set/get recording volume
- TCSACR-336
> [AudioIO] Add new volume property to set/get recording volume

- src/Tizen.Multimedia.Metadata/MetadataEditor/MetadataEditor.cs
- src/Tizen.Multimedia.Metadata/MetadataEditor/MetadataEditorError.cs
Update exception description for malformed file and internal error
> [MetadataEditor] Update exception description

- src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
- src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs
add missing error code
https://code.sec.samsung.net/jira/browse/TCSACR-342
> [MediaPlayer] add missing error code

- src/Tizen.Multimedia.Remoting/MediaController/InternalEnums.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaControlEnums.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Add the result code for Response and playback state enum
- TCSACR-340
> [MediaController] Add the result code for Response and playback state enum

- src/Tizen.NUI.Components/Controls/Pagination.cs
- src/Tizen.NUI.Components/PreloadStyle/DefaultTheme.cs
- src/Tizen.NUI.Components/PreloadStyle/WearableTheme.cs
- src/Tizen.NUI.Components/Style/PaginationStyle.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PaginationSample.cs
- Change Pagination APIs  to public ones and fix CA warnings.
- ACR: TCSACR-338
(https://code.sec.samsung.net/jira/browse/TCSACR-338)
> [NUI] Make Pagination class public and fix CA warnings

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Cell padding shouldn't be added to last item.
Skip addition at last item.
NONE
> [NUI] Skip adding cell padding to last LinearLayout item

- packaging/PlatformFileList.txt
Add Tizen.Uix.VoiceControlManager.dll into PlatformFileList.txt to include this dll into platform binary.
> [VoiceControlManager] Add VoiceControlManager dll into platform binary

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Open ScrollalbleBase APIs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-343
> [NUI] Open ScrollableBase APIs

- packaging/makerid.py
Fix parsing errors of arm64 and x64 archs
- ACR:
> [Build] Fix rid generation error

- src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
- src/Tizen.Multimedia.MediaCodec/MediaCodec/SupportedCodecType.cs
Add new codec type - Opus
- TCSACR-344
> [MediaCodec] Add new codec type - Opus

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
When velocity is 0, fomular cannot be working.
Skip deceleration when velocity is 0.
NONE
> [NUI] Fix ScrollableBase when velocity is 0

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleViewLayoutManager.cs
- src/Tizen.NUI.Components/Controls/ImageScrollBar.cs
- src/Tizen.NUI.Components/Utils/StyleManager.cs
> [NUI] Fix some typos.

- src/Tizen.NUI/src/internal/Disposable.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Capture.cs
- src/Tizen.NUI/src/public/BaseHandle.cs
- src/Tizen.NUI/src/public/Capture.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CaptureTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DimTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
Capture binding
- This will be provided as hidden API first
- internal CaptureSignal class will be moved to a single file
- CaptureFinishStateEventArgs, this name will be changed (following c# naming rule)
- try to apply TDD in CaptureTest.cs, but it make runtime Exception which seems to be related with Nunit.Framework
- paired with https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/238500/
none
> [NUI] Add Capture

- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent.sln
- src/Tizen.Multimedia.AudioIO/Tizen.Multimedia.AudioIO.sln
- src/Tizen.Multimedia.Camera/Tizen.Multimedia.Camera.sln
- src/Tizen.Multimedia.MediaPlayer/Tizen.Multimedia.MediaPlayer.sln
- src/Tizen.Multimedia.Metadata/Tizen.Multimedia.Metadata.sln
- src/Tizen.Multimedia.Radio/Tizen.Multimedia.Radio.sln
- src/Tizen.Multimedia.Recorder/Tizen.Multimedia.Recorder.sln
- src/Tizen.Multimedia.Remoting/Tizen.Multimedia.Remoting.sln
- src/Tizen.Multimedia.StreamRecorder/Tizen.Multimedia.StreamRecorder.sln
- src/Tizen.Multimedia.Util/Tizen.Multimedia.Util.sln
> [Multimedia] Update solution files

- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
> [NUI] Remove Style from View

- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
- src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
To enable and disable scrolling of scrollbar, ScrollEnabled is added.
- ACR:
> [NUI] Add ScrollEnabled to ScrollbarBase

- src/Tizen.NUI/src/public/Utility/TextPageUtil.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TextPageSample.cs
Change TextPageUtil to Tizen.NUI.Utility namespace.
- ACR: NONE
> [NUI] Change TextPageUtil to Tizen.NUI.Utility namespace.

- src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
- src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
- src/Tizen.NUI.Wearable/src/public/CircularSlider.cs
> [NUI] Fix wearable style issues

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
Add exception and null check for Button/Slider/Switch to fix the TCT failed issues
> [NUI] Add exception and null check for Button/Slider/Switch

- packaging/PlatformFileList.txt
- packaging/preload/30.Tizen.NUI.preload
> [Build] Add the Tizen.NUI.preload file

- src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerClient.cs
- src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs
- src/Tizen.Multimedia.Remoting/MediaController/CommandCompletedEventArgs.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaControlCommand.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaControlEnums.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaController.Events.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaControllerManager.Events.cs
Add new request command method
- TCSACR-353
> [MediaController] Add new request method

- src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
- src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs
[MediaPlayer] remove NotSupportedFormat exception
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-351
> [MediaPlayer] remove NotSupportedFormat exception

- src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.SoftkeyClient.cs
- src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.SoftkeyService.cs
- src/Tizen.NUI.WindowSystem/src/public/ShellEnums.cs
- src/Tizen.NUI.WindowSystem/src/public/SoftkeyClient.cs
- src/Tizen.NUI.WindowSystem/src/public/SoftkeyService.cs
- test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.cs
- test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.sln
- test/Tizen.NUI.WindowSystem.Samples/tizen-manifest.xml
Add Softkey APIs to Tizen.NUI.WindowSystem
SoftkeyClient and SoftkeyService are created and these are hidden APIs.
- ACR: NON-ACR
Added:
- SoftkeyClient(TizenShell tzShell, Window win);
- ~SoftkeyClient();
- void SoftkeyClient.Dispose();
- void SoftkeyClient.Show();
- void SoftkeyClient.Hide();
- SoftkeyClient.VisibleState SoftkeyClient.Visible { get; } // Property
- SoftkeyClient.ExpandState SoftkeyClient.Expand { get; set; } // Property
- SoftkeyClient.OpacityState SoftkeyClient.Opacity { get; set; } // Property
- enum SoftkeyClient.VisibleState.Unknown;
- enum SoftkeyClient.VisibleState.Shown;
- enum SoftkeyClient.VisibleState.Hidden;
- enum SoftkeyClient.ExpandState.Unknown;
- enum SoftkeyClient.ExpandState.On;
- enum SoftkeyClient.ExpandState.Off;
- enum …
> [NUI] Add WindowSystem softkey APIs

- .github/workflows/pull_request.yaml
Add a github actions workflow for pull request checks
> [Build] Add github actions workflow for pull request

- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Open new GridLayout APIs and Properties
https://code.sec.samsung.net/jira/browse/TCSACR-352
> [NUI] Open new GridLayout APIs and Properties

- src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
Add  CAPTURE_ALL_TOUCH_AFTER_START property
- ACR: NONE
> [NUI] Add  CAPTURE_ALL_TOUCH_AFTER_START property

- src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
This reverts commit 44638c8717f71c947a43fcbf273f728b0a820017.
none
> Revert "[NUI] Add CAPTURE_ALL_TOUCH_AFTER_START property (#1852)"

- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/XamlBinding/Page.cs
> [NUI] Fix svace issues.

- src/Tizen.NUI/src/public/BaseComponents/TextFieldSelectorData.cs
Meet the convert error: InputField->TextLabel
> [NUI] Fix the type convert issue when new InputField

- src/Tizen.Applications.Alarm/Tizen.Applications/AlarmManager.cs
[Applications.Alarm] Handle null parameter for AppControl
Changed:
- Add codes for handling null parameter
> [Applications.Alarm] Handle null parameter for AppControl

- src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
Change Text to TextSelector for Textfield
> [NUI] Change Text to TextSelector for Textfield

- src/Tizen.NUI.Components/Controls/RecyclerView/GridRecycleLayoutManager.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/LinearRecycleLayoutManager.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecycleLayoutManager.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
Support default focus chain.
Focus logic can vary depending on the type of LayoutManager.
NONE
> [NUI] Support default focus logic for RecyclerView

- src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
…52)" (#1868)"
This reverts commit 4bddf6f2de84375eee9f6bdadf221262cd891a3a.
- ACR: NONE
> [NUI] Add CAPTURE_ALL_TOUCH_AFTER_START property

- src/Tizen.NUI.Components/Controls/Loading.cs
Loading uses AnimatedImageVisual.
We can Play/Pause/Stop using visual actions.
Add Play/Pause/Stop APIs.
NONE
> [NUI] Add Play/Pause/Stop APIs to Loading

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
> [Bluetooth][Non-ACR] Supplement API document

- src/Tizen.Applications.PackageManager/Interop/Interop.PackageManager.cs
- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Add APIs for installing multiple packages
Added:
- static bool Install(List<string> packagePaths, InstallationMode installMode = InstallationMode.Normal)
- static bool Install(List<string> packagePaths, RequestEventCallback eventCallback, InstallationMode installMode = InstallationMode.Normal)
> [Packagemanager] Add APIs for installing multiple packages

- src/Tizen.Multimedia.Vision/MediaVision/BarcodeType.cs
Signed-off-by: Tae-Young Chung <ty83.chung@samsung.com>
Add new barcode types (Native ACR:  https://code.sec.samsung.net/jira/browse/ACR-1564)
- ACR: [TCSACR-361](https://code.sec.samsung.net/jira/browse/TCSACR-361)
> [MediaVision] Add new barcode types

- src/Tizen.NUI/src/public/Events/GestureDetectorManager.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TouchGestureSample.cs
- Detect supported gestures.
: To receive Gesture, you can inherit and implement GestureDetectorManager.GestureListener.
Then you can implement the necessary callback.
sample)
TextLabel backView = new TextLabel
{
Size2D = new Size2D(300, 300),
Text = "Back View",
Position2D = new Position2D(50, 70),
PointSize = 11,
BackgroundColor = new Color(1.0f, 1.0f, 0.0f, 1.0f),
};
mGestureDetector = new GestureDetectorManager(backView, new MyGestureListener());
backView.TouchEvent += OnBackTouchEvent;
private bool OnBackTouchEvent(object source, View.TouchEventArgs e)
{
Tizen.Log.Error("NUI", $"OnBackTouchEvent {e.Touch.GetState(0)}\n");
mGestureDetector.FeedTouchEvent(source, e);
return false;
}
class MyGestureListener : GestureDetectorManager.GestureListener
{
public override void OnTap(object …
> [NUI] Add GestureDetectorManager

- src/Tizen.NUI/src/internal/Interop/Interop.FrameCallbackInterface.cs
- src/Tizen.NUI/src/public/FrameCallbackInterface.cs
- src/Tizen.NUI/src/public/Window.cs
Binding FrameCallbackInterface
- ACR:
> [NUI] Binding FrameCallbackInterface

- build.sh
- build/analyzers.props
- build/common.props
Fix bug of build script about BuildWithAnalyzer flag
- ACR:
> [Build] Fix to enable Analyzer

- src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.QuickPanelClient.cs
- src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.QuickPanelService.cs
- src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.SoftkeyClient.cs
- src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.SoftkeyService.cs
- src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.TizenRegion.cs
- src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.TizenShell.cs
- src/Tizen.NUI/src/internal/FriendAssembly.cs
Fix conflicts of internal types between friends assemblies to suppress the warning CS0436.
- ACR:
> [NUI] Resolve conflicts types between friends assemblies

- src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
- value not set issue on WriteRequested callback
- SendIndication failed issue
> [Bluetooth][Non-ACR] Fix GATT issues

- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Check the package list is empty.
N/A
> [Packagemanager] Check the package list is empty

- src/Tizen.NUI/src/internal/Interop/Interop.TextUtils.cs
- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
- src/Tizen.NUI/src/public/Utility/TextPageUtil.cs
> [NUI] Add MinLineSize in RendererParameters

- src/Tizen.NUI/src/internal/CustomActorImpl.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ActorSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.CustomActorImpl.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ViewImplSignal.cs
- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
Rename OnStage signal related internal methods
- ACR: N/A
No public API has been changed.
> [NUI] Rename OnStage signal related internal methods

- packaging/csapi-tizenfx.spec
- packaging/csapi-tizenfx.spec.in
It is referenced by other meta packages. They should be fixed first.
- ACR:
> Restore csapi-tizenfx-dummy rpm package

- src/Tizen.Multimedia.Util/ImageUtil/ImageDecoder.cs
- src/Tizen.Multimedia.Util/ImageUtil/ImageEncoder.cs
- src/Tizen.Multimedia.Util/ImageUtil/ImageFormat.cs
- src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Encode.cs
Supports WebP encoder and decoder
- TCSACR-358
> [ImageUtil] Supports WebP encoder and decoder

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Check boundary for
ScrollDuration      -  value >= 0
DecelerationRate    -  value < 1 && value > 0
PageFlickThreshold  -  value >= 0
Invalid value will be ignored.
NONE
> [NUI] Boundary check for properties in ScrollableBase

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- To get Accessibility Activated signal to Button components, added and connected OnAccessibilityActivated in Button.
- To get Accessibility Pan signal to ScrollableBase, added OnAccessibilityPan method to be overridden.
- N/A
> [NUI] Add Accessibility override functions to components

- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleViewLayoutManager.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.Internal.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Fix the issue of Open source check.
- ACR:
> [NUI] Fix osv issue

- src/Tizen.NUI/src/internal/Interop/Interop.Hover.cs
- src/Tizen.NUI/src/public/Hover.cs
[NUI] Provide binding after HoverEvent class pimpling
- ACR: N/A
> [NUI] Provide binding after HoverEvent class pimpling

- src/Tizen.NUI/src/internal/Interop/Interop.Capture.cs
- src/Tizen.NUI/src/public/Capture.cs
Add new Start and SetImageQuality methods to capture sub-scene.
> [NUI] Fix capture issue of to capture sub-scene.

- src/Tizen.Multimedia.Radio/Radio/Radio.cs
The property and method already return `ObjectDisposedException` but it's missed in description.
It's not newly added exception.
> [Radio] Add missing descriptions

- src/Tizen.Multimedia.Camera/Camera/CameraDisplaySettings.cs
> [Camera] Fix document bug

- .github/workflows/build-branches.yml
- .github/workflows/build-pull-request.yml
> [Build] Use cached api spec in check-api of Pull Request workflow

- src/Tizen.NUI.Components/Controls/Progress.cs
> [NUI] proper BindableProperty name for Componenets.Progress

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Change default value of notification step and add new property to modify it.
NONE
> [NUI] change amount of Notificaion step

- src/Tizen.NUI.Components/Style/Extension/LottieButtonStyle.cs
- src/Tizen.NUI.Components/Style/Extension/LottieSwitchStyle.cs
> [NUI] simplify code of LottieXXXStyle by using 'is' operator

- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
When installing multiple packages, callback information should be
released when all completed event received.
N/A
> [Packagemanager] Fix releasing callback information

- README.md
> Fix status badges of README

- src/Tizen.NUI/src/internal/GLWindowResizedSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.GLWindow.cs
- src/Tizen.NUI/src/internal/Interop/Interop.GLWindowFocusChangeSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.GLWindowResizedSignal.cs
- src/Tizen.NUI/src/internal/Interop/interop.GLWindowVisibilityChangedSignal.cs
- src/Tizen.NUI/src/public/GLWindow.cs
- src/Tizen.NUI/src/public/GLWindowEvent.cs
- src/Tizen.NUI/src/public/GLWindowVisibilityChangedEvent.cs
GlWindow allows you to render scenes with OpenGL ES.
- ACR:
> [NUI] Add GlWindow

- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
AddRoute/RemoveRoute require http://tizen.org/privilege/network.route privilege.
> [Connection]Use the changed privilege to check Exception

- src/Tizen.NUI/src/public/NUIWidgetApplication.cs
Register current thread on WidgetApplication
- ACR:
> [NUI] Fix NUIWidget View thread error message

- src/Tizen.NUI/src/public/Window.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SubWindowTest.cs
[NUI] Fix exception error when sub Window is disposed
- https://code.sec.samsung.net/jira/browse/GRE-2009
- Add null check for Layers and LayoutContainer
- Add sample and test case for sub Window's Dispose()
none
> [NUI] Fix exception error when sub Window is disposed

- src/Tizen.NUI/src/internal/CustomActorImpl.cs
- src/Tizen.NUI/src/internal/Interop/Interop.CustomActorImpl.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ViewImplSignal.cs
- src/Tizen.NUI/src/internal/ViewImpl.cs
Removed OnWheelEvent() and OnHoverEvent()
> [NUI] Removed OnHoverEvent() and OnWheelEvent()

- src/Tizen.Multimedia.Camera/Camera/CameraCapabilities.cs
Fix ObjectDisposedException bug
> [Camera] Fix ObjectDisposedException bug

- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Pipeline.cs
This patch fixes the bug for double type of GetValue<T> method.
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>
* No ACR since it is bugfix.
> [MachineLearning.Inference] Fix the bug for double type of GetValue<T>

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
These documentation are from yoga docs.
(https://yogalayout.com/docs)
- ACR:
> [NUI] enhance FlexLayout documentation

- src/Tizen.NUI/src/internal/Interop/Interop.Gesture.cs
- src/Tizen.NUI/src/public/Gesture.cs
- src/Tizen.NUI/src/public/Hover.cs
- src/Tizen.NUI/src/public/Key.cs
- src/Tizen.NUI/src/public/LongPressGesture.cs
- src/Tizen.NUI/src/public/PanGesture.cs
- src/Tizen.NUI/src/public/PinchGesture.cs
- src/Tizen.NUI/src/public/RotationGesture.cs
- src/Tizen.NUI/src/public/TapGesture.cs
- src/Tizen.NUI/src/public/Wheel.cs
[NUI] Change parent class of Hover, Key, Wheel and Gesture to BaseHandle
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-375
> [NUI] Change parent class of Hover, Key, Wheel and Gesture to BaseHandle

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapterImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudioImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothHidDeviceImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothOppImpl.cs
> [Bluetooth][Non-ACR] Define Interop callback to global variable

- packaging/csapi-tizenfx.spec
- packaging/csapi-tizenfx.spec.in
> [Build] Fix directory permissions of csapi-tizen-full.rpm

- internals/src/Tizen.Peripheral/Interop/Adc.cs
- internals/src/Tizen.Peripheral/Interop/Gpio.cs
- internals/src/Tizen.Peripheral/Interop/I2c.cs
- internals/src/Tizen.Peripheral/Interop/Libraries.cs
- internals/src/Tizen.Peripheral/Interop/Pwm.cs
- internals/src/Tizen.Peripheral/Interop/Spi.cs
- internals/src/Tizen.Peripheral/Interop/Uart.Enum.cs
- internals/src/Tizen.Peripheral/Interop/Uart.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral.csproj
- internals/src/Tizen.Peripheral/Tizen.Peripheral.sln
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Adc.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/ExceptionFactory.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Gpio.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/I2c.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/PinUpdatedEventArgs.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Pwm.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Spi.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Uart.cs
TizenFX integration prepared by Wiktor Gerstenstein
Original authors:
- Jakub Sobczuk
- Michal Lesniak
- Michal Kolodziejski
- Marcin Romaniuk
- Kamil Stepaniuk
This commit adds new Peripheral IO API.
Added:
- `public class Tizen.Peripheral.Adc : IDisposable` (class):
-  `public Adc(int device, int channel)` (constructor);
-  `public uint ReadValue()` (method);
-  `public void Close()` (method);
-  `public void Dispose()` (method);
<br/>
- `public enum Tizen.Peripheral.Gpio.GpioPinDriveMode` (enum);
- `public enum Tizen.Peripheral.Gpio.GpioPinValue` (enum);
- `public enum Tizen.Peripheral.Gpio.GpioChangePolarity` (enum);
- `public class Tizen.Peripheral.Gpio.Gpio` (class):
- `public Gpio(int pinNumber, GpioPinDriveMode mode)` (constructor);
- `public event …
> Add Tizen.Peripheral API

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/FocusManager.cs
- src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs
- To clarify null check, modify conditionals clearly like this
: if (a != null)
- N/A
> [NUI] Fix Svace issues

- internals/docs/guides/toc.md
- internals/docs/toc.md
> [Docs] Add toc files for internal modules

- src/Tizen.NUI.Components/Controls/Pagination.cs
Add an API LastIndicatorImageUrl.
- ACR:
> [NUI] Add experimental API to Pagination

- .github/workflows/build-branches.yml
- .github/workflows/build-pull-request.yml
- .github/workflows/check-api-level.yml
> [Build] Add workflow files to API7 branch

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudioImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothHidDeviceImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothHidImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothOppImpl.cs
> [Bluetooth][Non-ACR] Add the exception handling logic

- internals/src/Tizen.Inspections/Tizen.Inspections/EventReceivedEventArgs.cs
Changed API description.
No changes.
> [Internal] Change API ref for Inspections

- src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
Signed-off-by: JinWang An <jinwang.an@samsung.com>
> [SystemSettings] Add lock for EventHandler

- .github/workflows/build-branches.yml
- .github/workflows/build-pull-request.yml
setup-dotnet issue: https://github.com/actions/setup-dotnet/issues/128
- ACR:
> [Build] Fix build errors in github actions

- src/Tizen.NUI/src/public/NUIApplication.cs
delete to precreate NUIApplication on NUI.
but Application class is created in dali-backend
- ACR:
> [NUI] Modify preload

- src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
* Change feature of AutoRotationSensor
`http://tizen.org/feature/sensor.accelerometer` -> `http://tizen.org/feature/screen.auto_rotation`
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-377
> [Sensor] Change tizen feature of AutoRotationSensor

- internals/src/Tizen.Peripheral/Tizen.Peripheral/Gpio.cs
- src/ElmSharp/ElmSharp.csproj
- src/Tizen.Account.OAuth2/Tizen.Account.OAuth2.csproj
- src/Tizen.NUI.Components/Tizen.NUI.Components.csproj
- src/Tizen.NUI.Wearable/Tizen.NUI.Wearable.csproj
- src/Tizen.NUI/Tizen.NUI.csproj
- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
- src/Tizen.NUI/src/public/Position2D.cs
- src/Tizen.NUI/src/public/Size2D.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpControl.cs
- src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager.csproj
- src/Tizen.Sensor/Tizen.Sensor/Sensor.cs
> [Build] Suppress build warnings

- src/Tizen.Messaging/Tizen.Messaging.Messages/MessagesManagerImpl.cs
Native GC callback fix of Messaging
> [Messaging] Native GC callback fix

- src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
* AutoRotationSensor is an algorithmic sensor, whether it is supported or not must be determined through the key.
- ACR:
> Check if the feature key is supported at AutoRotationSensor.

- src/Tizen.NUI/src/public/BaseHandle.cs
vd kona - DF200925-00594
Check if the swigCptr value is correct after the dispose.
- ACR:
> [NUI] Add defense code for BaseHandle

- src/Tizen.NUI/src/public/BaseComponents/View.cs
> [NUI] Delete unnecessary log

- .github/workflows/build-branches.yml
- .github/workflows/build-pull-request.yml
- .github/workflows/check-api-level.yml
> [Build] Add workflow files for actions

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Remove duplicate code
- ACR: NONE
> [NUI] Remove duplicate code

- src/Tizen.System/Device/Display.cs
- src/Tizen.System/Device/Power.cs
Add comments in DisplayState and PowerLock
> [System] Add comments in DisplayState and PowerLock

- src/Tizen.System/Device/Display.cs
- src/Tizen.System/Device/Power.cs
Change comments in DisplayState and PowerLock
> [System][Non-ACR] Change comments in DisplayState and PowerLock

- src/Tizen.Sensor/Tizen.Sensor/BatchSensor.cs
- src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitorBatch.cs
- src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitorLEDGreenBatch.cs
…nSensor. (#2068)" & Remove document wranning
* This reverts commit 6ea6f9d4424c97c52d0bb43a5ba8760860c470f0.
- ACR:
> [Sensor] Remove document warning.

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpControlImpl.cs
> [Bluetooth][Non-ACR] Fix TrackInfoChanged not invoked issue

- src/ElmSharp/ElmSharp/Elementary.cs
Added vd theme file path in ThemeOverlay for product tv
None
> [ElmSharp] Added vd theme file path in ThemeOverlay for product tv

- src/Tizen.Multimedia.Camera/Camera/Camera.cs
> [Camera] Remove feature check

- pkg/Tizen.NET.API7/Tizen.NET.API7.nuspec
> [Build] Fix typo in Tizen.NET.API7.nuspec

- src/Tizen.NUI.Components/Controls/Slider.cs
Typos in comments have been fixed.
- ACR: None
> [NUI] Fix typo in comments

- .github/branch-metadata.yml
- .github/workflows/build-branches.yml
- .github/workflows/build-pull-request.yml
> [Build] Add DevelNUI branch to workflows

- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
- src/Tizen.NUI/src/public/Capture.cs
[NUI] Fix build warning: CS0105
none
> [NUI] Fix build warning: CS0105

- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
[NUI] Fix build warning CS1573
none
> [NUI] Fix build warning CS1573

- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/Capture.cs
[NUI] Integration from DevelNUI to master
none
> [NUI] Integration from DevelNUI to master

- src/Tizen.NUI/src/internal/Disposable.cs
- src/Tizen.NUI/src/internal/DisposeQueue.cs
- src/Tizen.NUI/src/internal/FrameBroker/FrameData.cs
- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/KeyValue.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Layouting/LayoutTransition.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
- src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
- src/Tizen.NUI/src/public/ViewProperty/TextShadow.cs
- src/Tizen.NUI/src/public/VisualMaps.cs
This reverts commit 00ffabd0eb3ea4f57f1172d466737d25f0bc79c9.
This patch causes tct fail. a problem is occurring in Dispose.
-> https://dashboard.tizen.org/index.code?sr=submit/tizen/20201029.005223
- ACR:
> Revert "[NUI] Fix Dispose warning error[CA1001] (#2130)"

- src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
- src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
> [NUI] Handle null inputs in shadow

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/DaliEnumConstants.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
- Fix OnMeasure callback in LinearLayout.(handling margin and padding)
- Fix to handle only layout of ContentContainer to measure and layout of scrollableBase
- Fix LayoutGroup to do not assert when the child view has no layout in RemoveChildFromLayoutGroup method
> [NUI] Fix ScrollableBase Size Issue

- src/Tizen.NUI/src/internal/ViewSignal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- Add defensive code for ViewSignal Disconnect()
- This has been merged in API6, so sync with API7 and API8
none
> [NUI] Add defensive code for ViewSignal Disconnect()

- src/Tizen.NUI/src/public/TransitionAnimations/TransitionAnimations.cs
fix virtual to override
- ACR:
> [NUI] Fix default animation bug of seamless

- src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
This reverts commit 4a36f8f08fe9d580b35d740b8462a9a75fabd401.
- ACR:
> Revert "[NUI] Add TouchArea property. (#2105)"

- src/Tizen.NUI/src/public/Gesture.cs
- src/Tizen.NUI/src/public/Hover.cs
- src/Tizen.NUI/src/public/Key.cs
- src/Tizen.NUI/src/public/LongPressGesture.cs
- src/Tizen.NUI/src/public/PanGesture.cs
- src/Tizen.NUI/src/public/PinchGesture.cs
- src/Tizen.NUI/src/public/RotationGesture.cs
- src/Tizen.NUI/src/public/TapGesture.cs
- src/Tizen.NUI/src/public/Wheel.cs
> [NUI] No need to do Registry.GetManagedBaseHandleFromNativePtr().

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
Issues:
- NO_LOCK.STAT
This patch adds lock() to consider thread safety.
> Fix static analysis issues

- src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
- src/Tizen.NUI/src/internal/FrameProvider/FrameProvider.cs
fixed build warning CS1574
- ACR:
> fixed build warning CS1574

- src/Tizen.NUI/src/internal/XamlBinding/Internals/ResourceLoader.cs
- src/Tizen.NUI/src/public/Theme/Theme.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ThemeResourceSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/res/SampleTheme.xaml
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/res/SampleThemeResourceDark.xaml
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/res/SampleThemeResourceDefault.xaml
You can define resources(e.g. color, image etc.) of theme in seperate files.
ThemeResource can be changed in runtime without changing theme file.
- ACR:
> [NUI] Introduce ThemeResource

- src/Tizen.NUI/src/public/GLWindow.cs
Revert "[NUI] change orientation angle in GLWindow"
Because this patch should be only submitted to API9.
It is only internal APIs
> Revert "[NUI] change orientation angle in GLWindow"

- src/Tizen.NUI/src/public/Visuals/PrimitiveVisual.cs
- src/Tizen.NUI/src/public/Visuals/VisualAnimator.cs
Fixed svace defects of Visuals
> [NUI] Fixed svace defects of Visuals

- src/Tizen.NUI.Components/Controls/DropDown.DropDownListBridge.cs
- src/Tizen.NUI.Components/Controls/DropDown.cs
- src/Tizen.NUI.Components/Controls/Pagination.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/GridRecycleLayoutManager.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/LinearRecycleLayoutManager.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Components/Utils/StyleManager.cs
- src/Tizen.NUI.Wearable/src/internal/FishEyeLayoutManager.cs
- src/Tizen.NUI.Wearable/src/public/CircularPagination.cs
- src/Tizen.NUI.Wearable/src/public/WearableList.cs
- src/Tizen.NUI/src/internal/BackKeyManager.cs
- src/Tizen.NUI/src/internal/EnumHelper.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
- src/Tizen.NUI/src/internal/PropertyRangeManager.cs
- src/Tizen.NUI/src/internal/WidgetApplication.cs
- src/Tizen.NUI/src/internal/XamlBinding/BindingExpression.cs
- src/Tizen.NUI/src/internal/XamlBinding/MergedStyle.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/NUIFrameComponent.cs
- src/Tizen.NUI/src/public/Visuals/PrimitiveVisual.cs
- src/Tizen.NUI/src/public/Visuals/VisualAnimator.cs
> [NUI] Fixed Svace issues

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
> Fix static analysis issues (#2190)

- packaging/500.tizenfx_upgrade.sh
- packaging/csapi-tizenfx.spec
- packaging/csapi-tizenfx.spec.in
> [Build] Add FOTA script for TizenFX

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/GLWindow.cs
Fix CA2000 warning issues of GLWindow / ViewInternal.
- ACR:
> [NUI] Fix CA2000 warning issues of GLWindow / ViewInternal.

- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
> [NUI] Support theme for TV profile

- pkg/Tizen.NET/Tizen.NET.nuspec
> [Build] Fix wrong dependency of Tizen.NET nuget package

- src/Tizen.NUI/src/internal/XamlBinding/Device.cs
fixed build warning CA1802
- ACR:
> [NUI] fixed build warning CA1802

- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
This reverts commit 7fcc392ce08112253b2b43194117a58a7aa4cd97.
- ACR:
> Revert "[NUI] NUI has a default theme in TV profile"

- src/Tizen.NUI/src/internal/EnumHelper.cs
- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
- src/Tizen.NUI/src/internal/Xaml/ExpandMarkupsVisitor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/FocusManager.cs
- src/Tizen.NUI/src/public/Xaml/StaticResourceExtension.cs
- src/Tizen.NUI/src/public/Xaml/XamlServiceProvider.cs
- src/Tizen.NUI/src/public/XamlBinding/BindingBase.cs
fixed build warning CA2208
- ACR:
> [NUI] fixed build warning CA2208

- src/Tizen.NUI/src/internal/Interop/Interop.RenderTask.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Renderer.cs
- src/Tizen.NUI/src/internal/RenderTask.cs
- src/Tizen.NUI/src/internal/RenderTaskList.cs
- src/Tizen.NUI/src/internal/RenderTaskSignal.cs
- src/Tizen.NUI/src/public/Renderer.cs
> [NUI] fixed build warning CA1707

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
- If ExcludeLayouting property is false, the view is not affected by parent layout.
- Even the property is false, the children Views are affected by layout of current View.
- This ExcludeLayouting property is changed synchronously with SetPositionByLayout of its Layout.
- Children of AbsoluteLayout can freely be animated.
> [NUI] Add ExcludeLayouting to View

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
1- Add SelectWholeText method
2- Add SelectNone method
3- add SELECTED_TEXT property
- ACR:
> [NUI] Text: Add more selection functinality into TextEditor

- src/Tizen.NUI/src/public/Color.cs
- src/Tizen.NUI/src/public/Extents.cs
- src/Tizen.NUI/src/public/Position.cs
- src/Tizen.NUI/src/public/Position2D.cs
- src/Tizen.NUI/src/public/Rectangle.cs
- src/Tizen.NUI/src/public/RelativeVector2.cs
- src/Tizen.NUI/src/public/RelativeVector3.cs
- src/Tizen.NUI/src/public/RelativeVector4.cs
- src/Tizen.NUI/src/public/Size.cs
- src/Tizen.NUI/src/public/Size2D.cs
- src/Tizen.NUI/src/public/Vector2.cs
- src/Tizen.NUI/src/public/Vector3.cs
- src/Tizen.NUI/src/public/Vector4.cs
[NUI] Remove [Obsolete()] attribute
https://code.sec.samsung.net/jira/browse/TCSACR-391
> [NUI] Remove [Obsolete()] attribute

- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
> [NUI] Unsubscribe theme changed event when the view is not on window

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
[NUI] fixed bug about set desired size type to FittingModeType.Fill
none
> [NUI] fixed bug about set desired size 

- src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
> [NUI] Correct the meaning of ExcludeLayouting.

- packaging/500.tizenfx_upgrade.sh
- packaging/csapi-tizenfx.spec
- packaging/csapi-tizenfx.spec.in
- pkg/Tizen.NET/Tizen.NET.nuspec
> [NUI] sync with master

- src/Tizen.NUI/src/internal/DaliEnumConstants.cs
- src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBaseErrorFactory.cs
- src/Tizen.NUI/src/internal/FrameProvider/FrameProviderErrorFactory.cs
- src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
- src/Tizen.NUI/src/internal/Xaml/ExpandMarkupsVisitor.cs
- src/Tizen.NUI/src/internal/Xaml/NamescopingVisitor.cs
- src/Tizen.NUI/src/internal/XamlBinding/BindingExpression.cs
- src/Tizen.NUI/src/internal/XamlBinding/Device.cs
- src/Tizen.NUI/src/internal/XamlBinding/StyleSheets/Style.cs
- src/Tizen.NUI/src/internal/XamlBinding/TemplateUtilities.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/Events/GestureDetectorManager.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Rectangle.cs
- src/Tizen.NUI/src/public/Xaml/StaticResourceExtension.cs
- src/Tizen.NUI/src/public/Xaml/XamlFilePathAttribute.cs
- src/Tizen.NUI/src/public/XamlBinding/Element.cs
Fix CA1801 build warnings except auto-generated code by SWIG.
> [NUI] fix CA1801 build warnings

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
[NUI] Revert Layout patches
none
> [NUI] Revert Layout patches

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
> [Bluetooth][Non-ACR] Fix svace issue

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
> [Bluetooth][Non-ACR] Fix svace issue (#2270)

- src/Tizen.NUI/src/public/NUIApplication.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
> [NUI] Load default theme in preload

- src/Tizen.NUI.Components/Controls/Pagination.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Fix Svace issues for Components
> [NUI] Fix Svace issues for Components

- src/Tizen.NUI.Components/Controls/DropDown.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleViewLayoutManager.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/Tab.cs
- src/Tizen.NUI.Components/Controls/Toast.cs
- src/Tizen.NUI.Wearable/src/public/CircularPagination.cs
- src/Tizen.NUI.Wearable/src/public/Title.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Color.cs
- src/Tizen.NUI/src/public/VisualMaps.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ViewSizeWidthPropertySetTest.cs
Setter is deprecated in API8.(Size/Scale/Color/Position)
An unnecessary log comes out and causes performance degradation.
- ACR:
> [NUI] Change setter of property

- src/Tizen.NUI/src/internal/Interop/Interop.AccessibilityManager.cs
- src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
- Added EnableAccessibility and IsEnabled to AccessibilityManager
- dali-csharp-binder : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/248417/
- N/A
> [NUI] Add some APIs to make Accessibility enabled / disabled

- packaging/500.tizenfx_upgrade.sh
> [Build] Fix a security warning of FOTA script

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableBaseOutOfBoundSample.cs
This reverts commit bd6e9d90575a3f6f6daebd4f1ca716fe86a24843.
- ACR:
> Revert "[NUI] Add direction & displacement into ScrollOutOfBound event."

- packaging/500.tizenfx_upgrade.sh
> Fix a security warning of FOTA script (#2302)

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Utils/NUIWindowExtensions.cs
To provide default navigator of window, Window extension method
GetDefaultNavigator is added.
- ACR:
> [NUI] Add Window extension method GetDefaultNavigator

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
> [NUI] Let scroll again when displacement for OutOfBound effect become 0

- src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommandsGroup.cs
Signed-off-by: sooyeon.kim <sooyeon.kim@samsung.com>
* Fix svace issue
http://168.219.245.206:12000/sb2/main/review#PRJID=7&WGID=57932
(DF201102-01250)
> [Uix/VoiceControlManager] Fix svace issue

- src/Tizen.NUI/src/internal/Interop/Interop.TextUtils.cs
- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
- src/Tizen.NUI/src/public/Utility/TextPageUtil.cs
> [NUI] Add Padding parameter for TextPageUtil

- src/Tizen.NUI/src/internal/Interop/Interop.Capture.cs
- src/Tizen.NUI/src/internal/Interop/Interop.NativeImageSource.cs
- src/Tizen.NUI/src/internal/Interop/Interop.PixelData.cs
- src/Tizen.NUI/src/public/Capture.cs
- src/Tizen.NUI/src/public/NativeImageSource.cs
- src/Tizen.NUI/src/public/PixelData.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CaptureTest.cs
> [NUI] Add Url property to convert image buffer to URL for ImageView

- src/Tizen.NUI/src/internal/PropertyRangeManager.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
> [NUI] Fixed svace issue for API8

- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI.Components/Tizen.NUI.Components.csproj
- src/Tizen.NUI.Components/Tizen.NUI.Components.sln
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SwitchSample.cs
Add sound feedback for Control
> [NUI] Add sound feedback for Control

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliTableView.cs
> Change SCROLL_FINAL_X to ScrollFinalX

- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
- src/Tizen.NUI.Components/Style/ControlStyle.cs
- src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeWearable.cs
- src/Tizen.NUI.Components/Tizen.NUI.Components.csproj
- src/Tizen.NUI.Components/Utils/StyleManager.cs
- src/Tizen.NUI.Components/res/Theme/Tizen.NUI.Components_Tizen.NUI.Theme.Wearable.xaml
- src/Tizen.NUI.Wearable/Tizen.NUI.Wearable.csproj
- src/Tizen.NUI.Wearable/src/internal/Theme/DefaultTheme.cs
- src/Tizen.NUI.Wearable/src/public/CircularPagination.cs
- src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
- src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
- src/Tizen.NUI.Wearable/src/public/CircularSlider.cs
- src/Tizen.NUI/Tizen.NUI.csproj
- src/Tizen.NUI/src/public/NUIApplication.cs
- src/Tizen.NUI/src/public/Theme/DefaultTheme.cs
- src/Tizen.NUI/src/public/Theme/DefaultThemeWearable.cs
- src/Tizen.NUI/src/public/Theme/Theme.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
* Provide default theme in C#: Xaml file IO and parsing time reduced
* Provide on demand theme loading for packages: This enables to avoid unnecessary package load
- ACR:
> [NUI] Improve Theme load

- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI.Components/Tizen.NUI.Components.csproj
- src/Tizen.NUI.Components/Tizen.NUI.Components.sln
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableBaseOutOfBoundSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SwitchSample.cs
Add sound feedback and fix scroll build errors
> [NUI] Add sound feedback and fix scroll build errors

- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
- src/Tizen.NUI/src/public/Xaml/ViewExtensions.cs
- src/Tizen.NUI/src/public/XamlBinding/Binding.cs
- https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1724
- This warning requires to discuss to fix the name of the Class.
> [NUI] Fix build warning CA1724

- src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
- src/Tizen.NUI/src/internal/DisposeQueue.cs
- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/KeyValue.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Layouting/LayoutTransition.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
- src/Tizen.NUI/src/public/TransitionAnimations/TransitionAnimations.cs
- src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
- src/Tizen.NUI/src/public/ViewProperty/TextShadow.cs
- src/Tizen.NUI/src/public/VisualMaps.cs
This reverts commit 4cef848feaaefe4abac0b5f7890b8402e37fbcf6.
Need to TCT test.
- ACR:
> Revert "[NUI] Fix build warning[CA1000]"

- src/Tizen.NUI.Components/Controls/Control.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SwitchSample.cs
[NUI] Change "IsTapGestureFeedback" as "Feedback"
none
> [NUI] Change "IsTapGestureFeedback" as "Feedback"

- src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
> [NUI] fix svace issue for texture

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Controls/Tab.cs
- src/Tizen.NUI.Components/Controls/Toast.cs
- src/Tizen.NUI/src/public/UIComponents/ScrollViewEvent.cs
Add SuppressMessage code to the API to be deleted.
Signed-off-by: huiyu <huiyu.eun@samsung.com>
- ACR:
> [NUI] Delete warning messages

- src/Tizen.NUI/src/public/UIComponents/Button.cs
- src/Tizen.NUI/src/public/UIComponents/Popup.cs
- src/Tizen.NUI/src/public/UIComponents/ProgressBar.cs
- src/Tizen.NUI/src/public/UIComponents/ScrollBar.cs
- src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
- src/Tizen.NUI/src/public/UIComponents/ScrollViewEvent.cs
- src/Tizen.NUI/src/public/UIComponents/Slider.cs
Fix CA2000 issues of UIComponents.
- ACR:
> [NUI] Fix CA2000 issues of UIComponents.

- src/Tizen.NUI/src/internal/NUICoreBackend.cs
- src/Tizen.NUI/src/internal/Xaml/XamlParser.cs
- src/Tizen.NUI/src/internal/XamlBinding/BindingExpression.cs
- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
**CA1820: Test for empty strings using string length**
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1820
**CA2213: Disposable fields should be disposed**
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2213
> [NUI] Fix build warning CA1820, CA2213

- src/Tizen.Log/Tizen/Log.cs
> [Log] Modify documentation about dlog priorities 

- src/Tizen.NUI.Components/Controls/Control.cs
> [NUI] Initialize feedback only when the Feedback property is true

- src/Tizen.NUI/src/public/WidgetView.cs
Fix CA2000 issues in WidgetView.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2000
- ACR:
> [NUI] Fix CA2000 issues in WidgetView(Dispose objects before losing scope)

- src/Tizen.NUI/src/internal/DisposeQueue.cs
- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
- src/Tizen.NUI/src/public/Timer.cs
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1821
> [NUI] Fix the empty finalizers(CA1821)

- src/Tizen.NUI/src/internal/Application.cs
- src/Tizen.NUI/src/internal/Builder.cs
Fix CA2000 issue for Application Builder(disposed)
> [NUI] Fix CA2000 issue for Application Builder(disposed)

- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
> [NUI] Add an exception when deleting a view that is not child

- src/Tizen.NUI/src/public/Window.cs
- src/Tizen.NUI/src/public/WindowEvent.cs
Fix CA2000 warning for Window
- ACR:
> [NUI] Fix CA2000 warning for Window

- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
Fix CA2000 issue in DefaultTheme
- ACR:
> [NUI] Fix CA2000 issue in DefaultTheme(Dispose object before losing scope)

- src/Tizen.NUI/src/public/VisualMaps.cs
- src/Tizen.NUI/src/public/Visuals/AnimatedImageVisual.cs
- src/Tizen.NUI/src/public/Visuals/ArcVisual.cs
- src/Tizen.NUI/src/public/Visuals/BorderVisual.cs
- src/Tizen.NUI/src/public/Visuals/ColorVisual.cs
- src/Tizen.NUI/src/public/Visuals/GradientVisual.cs
- src/Tizen.NUI/src/public/Visuals/VisualAnimator.cs
Modify CA2000 warnings for Visual
CA2000: Dispose objects before losing scope
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2000
- ACR:
> [NUI] Modify CA2000 warnings for Visual

- src/Tizen.NUI/src/public/VisualMaps.cs
- src/Tizen.NUI/src/public/Visuals/AnimatedImageVisual.cs
- src/Tizen.NUI/src/public/Visuals/ArcVisual.cs
- src/Tizen.NUI/src/public/Visuals/BorderVisual.cs
- src/Tizen.NUI/src/public/Visuals/ColorVisual.cs
- src/Tizen.NUI/src/public/Visuals/GradientVisual.cs
- src/Tizen.NUI/src/public/Visuals/VisualAnimator.cs
Reverts Samsung/TizenFX#2455
From the dali-csharp-binder code, if the value is null, calling new PropertyValue throws an excpetion.
> Revert "[NUI] Modify CA2000 warnings for Visual"

- src/Tizen.NUI/src/public/VisualMaps.cs
Modify CA2000 Warnings for VisualMap
- ACR:
> [NUI] Modify CA2000 Warnings for VisualMap

- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/Style/LoadingStyle.cs
> [NUI] Add ImageList property

- src/Tizen.NUI/src/public/Visuals/TextVisual.cs
- src/Tizen.NUI/src/public/Visuals/VisualAnimator.cs
Modify CA2000 Warnings for TextVisual and VisualAnimator
- ACR:
> [NUI] Modify CA2000 Warnings for TextVisual and VisualAnimator

- src/Tizen.NUI/src/internal/Model3dView.cs
- src/Tizen.NUI/src/internal/RenderTask.cs
Fix CA2000 issues in Model3dView and RenderTask.
- ACR:
> [NUI] Fix CA2000 issues in Model3dView and RenderTask.

- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
> [NUI] remove needless null validation in LayoutItem.SetFrame

- src/Tizen.System/Device/Power.cs
- src/Tizen.System/Interop/Interop.Device.cs
Add internal APIs for power off and reboot
- System.Power.PowerOff
- System.Power.Reboot
> [System] Add internal APIs for power off and reboot

- src/Tizen.System/Device/Power.cs
- src/Tizen.System/Interop/Interop.Device.cs
Add internal APIs for power off and reboot
- System.Power.Poweroff
- System.Power.Reboot
> Add internal APIs for power off and reboot

- src/Tizen.NUI/src/public/Visuals/ArcVisual.cs
- src/Tizen.NUI/src/public/Visuals/BorderVisual.cs
- src/Tizen.NUI/src/public/Visuals/ColorVisual.cs
- src/Tizen.NUI/src/public/Visuals/ImageVisual.cs
- src/Tizen.NUI/src/public/Visuals/NPatchVisual.cs
- src/Tizen.NUI/src/public/Visuals/SVGVisual.cs
Fix CA2000 issues for Visuals
- ACR:
> [NUI] Fix CA2000 issues for Visuals

- test/Tizen.NUI.Samples/Tizen.NUI.Samples.sln
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliTableView.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
[NUI] Fix build error and large text size issue
none
> [NUI] Fix build error and large text size issue

- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
> Revert "[Packagemanager] Fix registering internal event callback"

- src/Tizen.NUI/src/public/Size2D.cs
> [NUI] remove unnecessary using in Size2D.cs

- src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AppBarSample.cs
AppBar shows title text and provides navigation and action functions on
Page.
- ACR:
> [NUI] Add AppBar class

- src/Tizen.NUI/src/public/Visuals/AnimatedImageVisual.cs
- src/Tizen.NUI/src/public/Visuals/GradientVisual.cs
- src/Tizen.NUI/src/public/Visuals/MeshVisual.cs
- src/Tizen.NUI/src/public/Visuals/PrimitiveVisual.cs
Fix CA2000 issues for Visual
- ACR:
> [NUI] Fix CA2000 issues for Visual

- src/Tizen.NUI/src/public/Window.cs
[NUI] fixed memory leak
- ACR:
> [NUI] fixed memory leak

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AccessibilityManagerSample.cs
- Updated the sample to fit the size and make it easier to read.
- N/A
> [NUI] Update AccessibilitySample for readability

- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
Changed files:
src/Tizen.NUI/src/internal/ViewImpl.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
- ACR:
> [NUI] Fix CA2000 warning issues of View and ViewImpl.

- src/Tizen.NUI/src/public/XamlBinding/SizeTypeConverter.cs
- Change to `SizeTypeConverter` for the correct compiledVersion
- N/A
> [NUI] Fix the incorrect parameter for XamlBinding

- src/Tizen.NUI/src/public/Renderer.cs
- src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
- src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
- src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
Fix CA2000 issues for Render Shadow
- ACR:
> [NUI] Fix CA2000 issues for Render Shadow

- src/Tizen.NUI/src/public/LongPressGestureDetector.cs
- src/Tizen.NUI/src/public/PanGestureDetector.cs
- src/Tizen.NUI/src/public/PinchGestureDetector.cs
- src/Tizen.NUI/src/public/PropertyNotification.cs
- src/Tizen.NUI/src/public/RotationGestureDetector.cs
- src/Tizen.NUI/src/public/Shader.cs
- src/Tizen.NUI/src/public/StyleManager.cs
- src/Tizen.NUI/src/public/TTSPlayer.cs
- src/Tizen.NUI/src/public/TapGestureDetector.cs
- src/Tizen.NUI/src/public/Timer.cs
- src/Tizen.NUI/src/public/Utility/TextPageUtil.cs
> [NUI] Fix CA2000 Warnings

- src/Tizen.NUI/src/public/TransitionAnimations/TransitionAnimations.cs
- src/Tizen.NUI/src/public/TransitionData.cs
- src/Tizen.NUI/src/public/TransitionOptions/TransitionOptions.cs
> [NUI] Update description of Transition classes

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
> [Bluetooth][Non-ACR] Fix BluetoothDevice.Name converting issue

- src/Tizen.NUI/src/public/LongPressGestureDetector.cs
- src/Tizen.NUI/src/public/PanGestureDetector.cs
- src/Tizen.NUI/src/public/PinchGestureDetector.cs
- src/Tizen.NUI/src/public/PropertyNotification.cs
- src/Tizen.NUI/src/public/RotationGestureDetector.cs
- src/Tizen.NUI/src/public/Shader.cs
- src/Tizen.NUI/src/public/StyleManager.cs
- src/Tizen.NUI/src/public/TTSPlayer.cs
- src/Tizen.NUI/src/public/TapGestureDetector.cs
- src/Tizen.NUI/src/public/Timer.cs
- src/Tizen.NUI/src/public/Utility/TextPageUtil.cs
> Revert "[NUI] Fix CA2000 Warnings"

- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
Reverts Samsung/TizenFX#2495
There is a critical issue in the patch.
> Revert "[NUI] Fix CA2000 warning issues of View and ViewImpl."

- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
- src/Tizen.System/Device/Power.cs
- src/Tizen.System/Interop/Interop.Device.cs
> Rebase master branch

- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
[NUI] Fix runtime exception in TV target
none
> [NUI] Fix runtime exception

- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
> [NUI] fix a c&p error in RelativeLayout

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapterImpl.cs
> [Bluetooth][Non-ACR] GetBondedDevice converting issue

- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FindChildByIDTest.cs
[NUI] Add View.FindChildByID() as hidden API
- Will raise ACR after being merged in master branch
none
> [NUI] Add View.FindChildByID() as hidden API

- src/Tizen.NUI/src/public/Accessibility/AccessibilityManagerEvent.cs
- Changed the old-fashioned code of event handler
- N/A
> [NUI] Fix AccessibilityManager Event handler

- src/Tizen.NUI/src/public/Accessibility/AccessibilityManagerEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FindChildByIDTest.cs
Integration work (2021-01-19)
none
> [NUI] Integration

- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
- src/Tizen.NUI/src/public/ViewWrapper.cs
Override Dispose function
- ViewWrapperImpl
- ViewImpl
- ViewWrapper
- ACR:
> [NUI] Override Dispose to release native memory

- src/Tizen.NUI.Components/Controls/Control.cs
[NUI] Change Feedback as working on TouchEvent
none
> [NUI] Change Feedback as working on TouchEvent

- src/Tizen.NUI/src/public/Window.cs
[NUI] Fix TV AmbientMode empty screen
none
> [NUI] Fix TV AmbientMode empty screen

- src/Tizen.NUI/src/public/CustomViewRegistry.cs
- src/Tizen.NUI/src/public/InputMethod.cs
- src/Tizen.NUI/src/public/KeyFrames.cs
- src/Tizen.NUI/src/public/Layer.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/PanGestureDetector.cs
- src/Tizen.NUI/src/public/Path.cs
- src/Tizen.NUI/src/public/Shader.cs
- src/Tizen.NUI/src/public/Utility/TextPageUtil.cs
fix CA2000 Warning for proterty
- ACR:
> [NUI] fix CA2000 Warning for proterty

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Interop/Interop.AccessibilityManager.cs
- src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
Need to delete object of accessibility
C# binder : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/251888/
- ACR:
> [NUI] Add DeleteAccessibilityAttribute(Fix Button memory leak)

- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
- src/Tizen.NUI/src/public/ViewWrapper.cs
refer this patch
https://github.com/Samsung/TizenFX/pull/2536
https://github.com/Samsung/TizenFX/pull/2534
- ACR:
> [NUI] Fix memory leak, Add Dispose

- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
> [NUI] Sync unmanaged or managed data type to csharp-binder

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Interop/Interop.AccessibilityManager.cs
- src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
> [NUI] Add DeleteAccessibilityAttribute

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Interop/Interop.AccessibilityManager.cs
- src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
This reverts commit d6a57e870b299c228b5ac11d4d2970758906e49c.
- ACR:
> Revert "[NUI] Add DeleteAccessibilityAttribute"

- src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldSelectorData.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelSelectorData.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
> [NUI] Support selector for PixelSize in TextLabelStyle and TextEditorStyle

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/CustomView/Spin.cs
Fix CA2000 Warnings for View
- ACR:
> [NUI] Fix CA2000 Warnings for View

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView.cs
- src/Tizen.NUI/src/internal/WebViewScrollEdgeReachedEventArgs.cs
- src/Tizen.NUI/src/internal/WebViewScrollEdgeReachedSignal.cs
1) ScrollPosition, ScrollSize, ContentSize properties are added.
2) ScrollBy is added.
3) ScrollEdgeReached events are notified when scrolled to edge.
- ACR:
> [NUI] Support scroll in WebView.

- src/Tizen.Applications.MessagePort/Tizen.Applications.Messages/MessagePort.cs
Fix bug for getting remote value
> [MessagePort] Fix bug for getting remote value

- src/Tizen.Applications.MessagePort/Tizen.Applications.Messages/MessagePort.cs
[MessagePort] Add defensive code for null string
> [MessagePort] Add defensive code for null string

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
[NUI] Change Feedback default as false in Control
- Change Feedback default as false in Control
- Change Feedback as true in each Components (ex: Switch, Button)
none
> [NUI] Change Feedback default as false in Control

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView.cs
Title, Favicon, ClearAllTilesResources are added.
Meanwhile WebView can be created by arguments argc & args
that will be delivered into web engine.
- ACR:
> [NUI] Add some APIs into WebView.

- src/Tizen.NUI/src/internal/WebView.cs
> [NUI] Update WebView constructor with program arguments

- src/Tizen.NUI.Components/Theme/DefaultThemeMobile.cs
> [NUI] Change button default style in common profile

- src/Tizen.NUI/src/internal/Interop/Interop.ImageLoading.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/ImageLoading.cs
> [NUI] Add GetOriginalImageSize() considering rotation

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
> [Tizen.Applications] Make exception safe codes

- src/Tizen.Applications.ComponentBased.Port/Tizen.Applications.ComponentBased.Port/ComponentPort.cs
> [Applications.ComponentBased.ComponentPort] Add a missing exception

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ItemViewDemo/ItemViewSample.cs
SetMinimumSwipeDistance and SetMinimumSwipeSpeed were removed.
- ACR:
> [NUI] Fix a bug related to CA1721

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
- src/Tizen.Applications.ComponentBased.Port/Tizen.Applications.ComponentBased.Port/ComponentPort.cs
> Rebase master

- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
[NUI] Fix AnimatedVectorImageView pagination visual defect
none
> [NUI] Fix AnimatedVectorImageView pagination visual defect

- src/Tizen.NUI.Wearable/src/internal/FishEyeLayoutManager.cs
- src/Tizen.NUI/src/public/Theme/Theme.cs
Modify svace issues for NUI and wearable
- ACR:
> [NUI] Modify svace issues for NUI and wearable

- src/Tizen.NUI/src/internal/Common/Disposable.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
- src/Tizen.NUI/src/public/CustomView/CustomViewRegistry.cs
- src/Tizen.NUI/src/public/Visuals/VisualMaps.cs
Rmove build warning CA1051.
It is aleady deprecated by TCSACR-396
https://code.sec.samsung.net/jira/browse/TCSACR-396
- ACR:
> [NUI] Add obsolete tag

- internals/src/Tizen.Applications.ThemeManager/Interop/Interop.Libraries.cs
- internals/src/Tizen.Applications.ThemeManager/Interop/Interop.ThemeManager.cs
- internals/src/Tizen.Applications.ThemeManager/Tizen.Applications.ThemeManager/Theme.cs
A new API added:
- Tizen.Applications.Theme.HasKey(string key)
This module is for internal.
> [ThemeManager] Add new internal API for ThemeManager

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- src/Tizen.NUI.Components/res/Theme/Tizen.NUI.Components_Tizen.NUI.Theme.Common.xaml
> [NUI] ScrollableBase supports Scrollbar properly

- src/Tizen.NUI.Components/Controls/Scrollbar.cs
> [NUI] Prevent svace issues in Scrollbar

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Position.cs
Remove force casting at LayoutItem.cs
just change `Owner.GetParent() as View;`
+
tiny typo error fix
> [NUI] Remove wrong force casting, Layer as View

- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Style/SliderStyle.cs
Added some properties for warning status.
-  WarningStartValue (The default would be MaxValue)
-  WarningTrackColor
-  WarningSlidedTrackColor
-  WarningThumbImageUrl
-  WarningThumbImageUri
-  WarningThumbColor
Added `ThumbImageUri` property for thumb image.
- N/A
> [NUI] Add Slider warning properties

- src/Tizen.NUI/Tizen.NUI.csproj
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
> [NUI] NUI ThemeManager works with TizenThemeManager

- src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentType.cs
Add ComponentType enum value at ComponentType in Tizen.Application.ComponentBased
- ACR: TCSACR-401
Added:
- public enum ComponentType::Widget
> [Tizen.Applications.ComponentBased.ComponentManager][TCSACR-401] Add ComponentType enum value at ComponentType

- src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentType.cs
- src/Tizen.Applications.ComponentBased/Interop/Interop.CBApplication.cs
- src/Tizen.Applications.ComponentBased/Interop/Interop.Libraries.cs
- src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ComponentBasedApplication.cs
- src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/IWindowProxy.cs
- src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/WidgetComponent.cs
- src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/WidgetComponentStateManager.cs
> Rebas master

- src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
- src/Tizen.NUI/src/internal/Interop/Interop.View.cs
- src/Tizen.NUI/src/public/Animation/Animation.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
This enables animation of
* CornerRadius
* BackgroundColor
* BoxShadow.Color
* BoxShadow.BlurRadius
* etc.
- ACR:
> [NUI] Enables animation of view visual properties

- src/Tizen.NUI/src/internal/Interop/Interop.NDalicColor.cs
- src/Tizen.NUI/src/internal/NativeBinding/NDalic.cs
- src/Tizen.NUI/src/public/Common/Color.cs
> [NUI] Make hidden for un-ACR-ed Color APIs

- src/Tizen.NUI/src/public/Common/Color.cs
> [NUI] remove empty space

- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
> [NUI] Delete exception of View.Remove

- src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
Fix xaml issue,
Add property null check
- ACR:
> [NUI] Fix Xaml issue

- src/Tizen.NUI.Components/Tizen.NUI.Components.csproj
- src/Tizen.NUI.Components/Tizen.NUI.Components.preload
- src/Tizen.NUI/src/internal/Application/Application.cs
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
- Add Tizen.NUI.Components.preload
- Change PreLoad to Preload
- ACR:
> [NUI] Add Tizen.NUI.Components.preload

- src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CulledTest.cs
[NUI] Add Culled property as Hidden-API
- pair with https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/253893/
- should be merged after https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/253893/ is applied
none
> [NUI] Add Culled property as Hidden-API

- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
- src/Tizen.NUI/src/public/Common/StyleManager.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-404
> [NUI] Deprecate Tizen.NUI.StyleManager (#2641)

- src/Tizen.NUI.Wearable/src/internal/FishEyeLayoutManager.cs
- src/Tizen.NUI/src/internal/XamlBinding/SynchronizedList.cs
Fix NUI and wearable svace issues
- ACR:
> [NUI] Fix NUI and wearable svace issues

- src/Tizen.NUI.Wearable/src/internal/FishEyeLayoutManager.cs
- src/Tizen.NUI/src/internal/XamlBinding/SynchronizedList.cs
Fix Svace defects for NUI and wearable
- ACR:
> [NUI] Fix Svace defects for NUI and wearable

- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
> [NUI] Create TextLayout when parent has layout

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CulledTest.cs
- In CulledTest.cs, 'OnKeyEvent' is missed for Window KeyEvent
- N/A
> [NUI] Fix build error of Tizen.NUI.Samples

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/CheckBox.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
- src/Tizen.NUI.Components/Controls/ImageScrollBar.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/RadioButton.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI.Components/Controls/Tab.cs
- src/Tizen.NUI.Components/Controls/Toast.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Template/DataTemplate.cs
> [NUI] Delete Tizen.NUI.Components build warnings

- src/Tizen.NUI.Wearable/src/internal/FishEyeLayoutManager.cs
Fix svace issue for wearable
- ACR:
> [NUI] Fix svace issue for wearable

- src/Tizen.NUI.Wearable/src/internal/FishEyeLayoutManager.cs
[NUI] Fix svace issues for wearable
- ACR:
> [NUI] Fix svace issues for wearable

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
> [NUI] Remove theme resource update sample

- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewSelectorData.cs
This can leads application launching time improvement.
- ACR:
> [NUI] Remove rarely used properties from the Style class

- coverage.sh
> [Cov] Fix coverage.sh

- coverage.sh
[NUI] rebase from master to DevelNUI
> [NUI] rebase from master to DevelNUI

- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
Fix some warning messages.
- CA1066 : Implemented `IEquatable` interface to GestureInfoType structure.
- CA1034 : Added public types to replace nested types of events.
- N/A
> [NUI] Fix Accessibility warning messages

- src/Tizen.NUI/src/public/Theme/ExternalThemeManager.cs
> [NUI] Catch DllNotFound exception for capi-appfw-tizen-theme.so

- src/Tizen.NUI/src/public/Theme/ExternalThemeManager.cs
> [NUI] Catch all exceptions from tizen theme manager

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldSelectorData.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelSelectorData.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewSelectorData.cs
- src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
> [NUI] Improve performance in theme and styles

- src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AppBarSample.cs
Unused namespace System.Windows.Input is removed.
AppBar constructors with parameters are removed to reduce complexity by
adding constructors with style parameters.
private Initialize() is added to remove duplicate codes in constructors.
DefaultTitleContent and DefaultActionContent are added like
DefaultNavigationContent.
SetTitle() is added to set title text to DefaultTitleContent.
AddActions() and RemoveActions() are added to add and remove action
views to DefaultActionContent.
- ACR:
> [NUI] AppBar code refactoring to introduce AppBarStyle

- src/Tizen.NUI/src/public/Widget/WidgetViewManager.cs
CA1065: Do not raise exceptions in unexpected locations
- ACR:
> [NUI] Fix a Warning in WidgetView

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapterImpl.cs
Co-authored-by: dh79pyun <31202060+dh79pyun@users.noreply.github.com>
> Sync Mater to DevelNui

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapterImpl.cs
> [Bluetooth][Non-ACR] Fix GetLocalOobData memory leak

- src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldSelectorData.cs
[TextField] PlaceholderTextFoused can set the SID value by this patch
ex) textField.TranslatablePlaceholderTextFocused = "TextField";
> [NUI] Support TranslatablePlaceholderTextFocused to TextField

- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
> [NUI] Delete unuused code

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/DropDown.cs
- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
[NUI] Fix TV TCT fails
- FeedKey and Accessibility are FHUB(mobile) feature
- TV doesn't use Feedkey nor NUI Accessibility
- Need to be seperated by profile when building
none
> [NUI] Fix TV TCT fails

- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
> [NUI] Clean up MeasureAndLayout of LayoutController

- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
> [NUI] change type from Size2D to Size at TouchArea api

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
- src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
> [NUI] Scrollbar uses View instead Visual since blinking issue

- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
This patch causes issue that TextLabel margin to become zero.
Revert this patch to fix issue.
we need to fix layout performance issue later.
This reverts commit b78d9bf284c27e065b7d194ae9124e34258d18b9.
> Revert "[NUI] Create TextLayout when parent has layout"

- src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Signed-off-by: Jihoon Kim <jihoon48.kim@samsung.com>
Fix typo in inputmethod function
N/A
> [Tizen.Uix.InputMethod] Fix typo in function

- src/Tizen.System.Information/Interop/Interop.Libc.cs
- src/Tizen.System.Information/Interop/Interop.RuntimeInfo.cs
- src/Tizen.System.Information/Usage/ProcessMemoryUsage.cs
Add new API for internal apps.
Add below 3 APIs.
Tizen.System.ProcessMemoryUsage.GetGPU(int pid)
Tizen.System.ProcessMemoryUsage.GetGemRss(int pid)
Tizen.System.ProcessMemoryUsage.GetSwap(int pid)
> [Tizen.System.Information][Non-ACR] Add API for internal

- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Remove to improve performance of layout
- ACR:
> [NUI] Remove Debug.WritelineIf

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
This reverts commit c0df2f273c77d7655df2d9c15d005a72d71431d7.
to fix NUI App crash defect
none
> Revert "[NUI] Clean up View's Events"

- src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Co-authored-by: InHong Han <inhong1.han@samsung.com>
[NUI] sync from master to DevelNUI
none
> [Inputmethod] Fix the crash issue due to double free (#2756)

- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/Controls/Pagination.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
> [NUI] Fix TCT fails

- src/Tizen.NUI/src/public/BaseComponents/View.cs
> [NUI] Fix layout null crash issue

- src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
> [Bluetooth][Non-ACR] Add MTU functionalities

- src/Tizen.Uix.VoiceControl/Tizen.Uix.VoiceControl/VoiceControlClient.cs
This patch makes event handler support multi handles and add thread locks for these event handlers
- No ACR
> [VoiceControl] Support multi handle for event and add thread lock for these handles

- src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
- src/Tizen.NUI/src/internal/WebView/WebSettings.cs
Add APIs of WebView Settings, the link of csharp-binder patch as follow:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/254348/
- ACR:
> [NUI] Add Apis of Webview Settings.

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
> [NUI] Change button theme to show Focused+Pressed state well.

- src/Tizen.Applications.ComponentBased.Port/Tizen.Applications.ComponentBased.Port/ComponentPort.cs
This patch adds to check whether the result parcel is nullptr or not.
> [Applications.ComponentBased] Fix static analysis issue

- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/SingleShot.cs
This patch fixes the svace issue.
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>
> [MachineLearning.Inference] Fix the Svace issue

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
- src/Tizen.NUI/src/internal/Common/PropertyRangeManager.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
> [NUI] Fix NUI svace issue (#2817)

- src/Tizen.NUI.Components/Controls/Picker.cs
WGID: 458476
Fix anlaysishub issue (https://analysishub.sec.samsung.net/service/analyses/431347)
No API Changes
> [NUI] Picker fix a defect that could refer to null pointer

- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
[NUI] Fix "View Inside Fridge" App npatch visual defect
- Rollback the Text's Layout patches
- npatch visual image was broken
none
> [NUI] Fix "View Inside Fridge" App npatch visual defect

- src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
Required DALi patches:
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/256189/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/256190/
- ACR: None
> [NUI][AT-SPI] Add Accessibility.StopReading()

- src/Tizen.NUI.Components/Controls/TimePicker.cs
- src/Tizen.NUI.Components/Style/TimePickerStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TimePickerSample.cs
Introduce TimePicker
https://code.sec.samsung.net/confluence/display/GFX/Picker
No API Changes
> [NUI] Introduce NUI TimePicker

- src/Tizen.NUI.Components/Style/PickerStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
> [NUI] Picker style update

- src/Tizen.NUI.Components/Controls/DatePicker.cs
- src/Tizen.NUI.Components/Style/DatePickerStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DatePickerSample.cs
Introduce DatePicker
https://code.sec.samsung.net/confluence/display/GFX/Picker
none
> [NUI] Introduce NUI DatePicker

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
This reverts commit 86409caf7bffd2b7b3e0aa7a827a51b449938b1e.
- ACR:
> Revert "[NUI] Button text ellipsis enabled and etc. (#2772)"

- src/Tizen.NUI/src/public/Utility/Palette.cs
Fix incorrectly caclulated color values
none
> [NUI] Palette Fix incorrectly caclulated color values

- src/Tizen.NUI/src/internal/Common/RenderTask.cs
- src/Tizen.NUI/src/internal/Common/RenderTaskList.cs
- src/Tizen.NUI/src/public/Window/Window.cs
- RenderTaskList.cs
internal class RenderTaskList : BaseHandle --> public class RenderTaskList : BaseHandle
- RenderTask.cs
internal void RenderTask::SetCamera(Camera camera) --> public void RenderTask::SetCamera(Camera camera)
internal Camera RenderTask::GetCamera() --> publicCamera RenderTask::GetCamera()
- Window.cs
internal RenderTaskList GetRenderTaskList() --> public RenderTaskList GetRenderTaskList()
> [NUI] Apply to use RenderTaskList

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
> [Bluetooth][Non-ACR] Fix BluetoothDevice data converting issue

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AlertDialogSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AppBarSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DialogSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/NavigatorSample.cs
Page and Dialog code refactoring.
- ACR:
> [NUI] Page and Dialog code refactoring

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Style/AlertDialogStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
To apply the latest AlertDialog UX, AlertDialogStyle class is added.
- ACR:
> [NUI] Add AlertDialogStyle class with the latest AlertDialog UX

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Animation/TSAnimatablePropertyComponentRegistration.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Animation/TSAnimatablePropertyRegistration.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Animation/TSAnimationSignal.cs
[NUI] Add Animation(internal) TCs
- ACR:
> [NUI] Add Animation(Internal) TCs

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TransitionItem.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TransitionItemBase.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TransitionSet.cs
- src/Tizen.NUI/src/internal/Transition/TransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/TransitionItemBase.cs
- src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
- src/Tizen.NUI/src/internal/Transition/TransitionSetSignal.cs
- src/Tizen.NUI/src/public/Animation/TransitionOptions.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Common/TimePeriod.cs
- src/Tizen.NUI/src/public/Transition/Transition.cs
- src/Tizen.NUI/src/public/Transition/TransitionBase.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PageTransitionSample.cs
Adds View Transition which make smooth motion between two View.
This transition is generated and played during page switching by using navigator
> [NUI] View Transition with page switching

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
This patch is to add some new APIs such as PageZoomFactor,
GetScreenshotAsynchronously, etc
- ACR:
> [NUI] Implement some new APIs of web view.

- src/Tizen.NUI.Components/Theme/ThemeDark.cs
- src/Tizen.NUI/src/public/Theme/ThemeDark.cs
> [NUI] Add dark theme temporarily

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- src/Tizen.NUI.Components/Style/AlertDialogStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AlertDialogSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AppBarSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DialogSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/NavigatorSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PageTransitionSample.cs
> [NUI] Revert revert DialogPage and ContentPage

- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
[NUI] Do not show navigation transition effect for DialogPage
The current navigation transition effect is not displayed when
DialogPage is pushed or popped.
[NUI] Set EnableDismissOnScrim true by default
To pop DialogPage when DialogPage's Scrim is touched by default,
EnableDismissOnScrim is set to be true by default.
[NUI] Add ScrimColor to DialogPage
To set color of Scrim, ScrimColor is added to DialogPage.
- ACR:
> [NUI] Dialog code refactoring

- src/Tizen.NUI/src/internal/Interop/Interop.WebContext.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebPasswordDataList.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebSecurityOriginList.cs
- src/Tizen.NUI/src/internal/WebView/WebContext.cs
- src/Tizen.NUI/src/internal/WebView/WebPasswordDataList.cs
- src/Tizen.NUI/src/internal/WebView/WebSecurityOriginList.cs
This patch is to implement some new APIs of webcontext, such as
GetWebStorageOrigins, GetFormPasswordList, etc.
- ACR:
> [NUI] Implement some new APIs of webcontext.

- src/Tizen.NUI.Components/Controls/TabBar.cs
- src/Tizen.NUI.Components/Controls/TabButton.cs
- src/Tizen.NUI.Components/Controls/TabButtonGroup.cs
- src/Tizen.NUI.Components/Controls/TabContent.cs
- src/Tizen.NUI.Components/Controls/TabView.cs
- src/Tizen.NUI.Components/Style/TabButtonStyle.cs
> [NUI] Fix license year information for TabView classes

- src/Tizen.NUI/src/public/Theme/ThemeDark.cs
This patch only changes the color of Text and Selection on Dark theme.
Note: SelectionPopup's dark theme is currently not supported due to technical limitations.
The goal is to provide this in the next release.
> [NUI] Add dark theme for Text components

- internals/src/Tizen.Peripheral/Tizen.Peripheral/Adc.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Gpio.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/I2c.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Pwm.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Spi.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Uart.cs
Signed-off-by: Ernest Borowski <e.borowski@samsung.com>
Fix Dispose pattern in Tizen.Peripheral API.
None, This is private API, so there is no need for ACR.
> [Peripheral] Fix Dispose pattern in Tizen.Peripheral

- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Style/ProgressStyle.cs
- src/Tizen.NUI.Components/Style/SliderStyle.cs
- Progress : IndeterminateImageUrl
- ProgressStyle : IndeterminateImageUrl
- Slider : ThumbImageUrl, IsValueShown, ValueIndicatorText,
ValueIndicatorSize, ValueIndicatorUrl, IsDiscrete, DiscreteValue
- SliderStyle : ValueIndicatorText, ValueIndicatorImage
- ACR: TCSACR-408
- https://code.sec.samsung.net/jira/browse/TCSACR-408
> [NUI] Make some of Progress and Slider public methods

- src/Tizen.NUI.Components/Controls/Loading.cs
> [NUI][ATSPI] Accessibility added to Loading component

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
> [NUI] Fix ImageView Dispose crash

- src/Tizen.NUI/src/internal/EXaml/Operation/SetProperty.cs
- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
> [NUI] Fix svace issues in EXaml and Accessibility

- src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Theme/Theme.cs
- src/Tizen.NUI/src/public/Theme/ThemeChangedEventArgs.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
- src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
- src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-410
> [NUI] Open NUI.ThemeManager and related APIs

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
This issues are detected by self-diagnosis.
- ACR:
> [NUI] Fix null reference check in CollectionViews.

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- To avoid confusion of using some `View` properties,
added remarks to use them for `TableView` class.
- N/A
> [NUI] Update some descriptions of View properties

- src/Tizen.NUI/src/internal/Interop/Interop.WebContext.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebCookieManager.cs
- src/Tizen.NUI/src/internal/WebView/WebContext.cs
- src/Tizen.NUI/src/internal/WebView/WebCookieManager.cs
The patch is base on the dali-csharp-binder patches:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/255352/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/256681
- ACR:
> [NUI] Add webview context and cookiemanager apis

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
> [NUI] Fix null reference check in CollectionViews. (#2942)

- src/Tizen.NUI/src/internal/WebView/WebContext.cs
- src/Tizen.NUI/src/internal/WebView/WebCookieManager.cs
- src/Tizen.NUI/src/internal/WebView/WebSettings.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebViewUrlChangedEventArgs.cs
This patch is to raname some properties to follow naming rule.
- ACR:
> [NUI] Rename some properties of WebView, WebSettings, etc.

- src/Tizen.NUI.Components/Controls/Scrollbar.cs
> [NUI] Scrollbar does not change theme style

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Notification.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-411
> [NUI] Open newly added APIs in Button and Notification

- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- src/Tizen.NUI/src/public/Animation/Animation.cs
- src/Tizen.NUI/src/public/Animation/TransitionOptions.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Common/TimePeriod.cs
- src/Tizen.NUI/src/public/Transition/Transition.cs
- src/Tizen.NUI/src/public/Transition/TransitionBase.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PageTransitionSample.cs
This is ACR patch to make Page Transition as public API
This pull request include new class of TransitionOptions, Navigator, Transition and TransitionBase.
And some property and methods for new APIs.
- ACR: TCSACR-416
> [NUI] Make Transition public API

- src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Style/Navigation/AppBarStyle.cs
This is ACR patch to make AppBar APIs public.
This pull request includes properties and methods of AppBar and
ContentPage classes.
- ACR: TCSACR-418
> [NUI] Make AppBar APIs public

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Animation/TSAlphaFunction.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Animation/TSAnimatable.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Animation/TSAnimation.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Animation/TSKeyFrames.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Animation/TSPath.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Animation/TSTransitionAnimations.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Animation/TSTransitionData.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Animation/TSTransitionOptions.cs
> [NUI] Add Animation(Public) TCs.

- src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
- src/Tizen.NUI/src/public/Visuals/VisualMaps.cs
> [NUI] Apply Vector4 corner radius internally.

- src/Tizen.NUI.Components/Controls/Progress.cs
[NUI][AT-SPI] Basic accessibility support for Tizen.NUI.Components.Progress
- ACR: none
> [NUI][AT-SPI] Default accessibility support for Tizen.NUI.Components.Progress

- src/Tizen.NUI/src/public/Theme/DefaultTheme.cs
> [NUI] Fix default theme id

- src/Tizen.NUI/src/internal/EXaml/LoadEXaml.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GetObjectByProperty.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/SetProperty.cs
> [EXaml] Fix SVACE issue

- src/Tizen.NUI/src/internal/Xaml/XamlParser.cs
Fix issue that can't load theme in Tizen.NUI
- ACR:
> [Xaml] Fix issue that can't load theme in Tizen.NUI

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
> [NUI] Remove prevent theme overwrite

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/ICollectionChangedNotifier.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/ObservableGroupedSource.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/ItemsLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/CollectionViewGridSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/CollectionViewLinearSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Gallery.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewGridGroupSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewLinearGroupSample.cs
When Collection is updated,
View can pick the notify event with updated info.
this patch implement normal collection updates including
- single item inserted
- single item removed
- single item moved
- group insrted
- group removed
- group moved
and apply samples regarding new implemented feature.
- ACR:
> [NUI] Implements view update on NotifyCollectionChanged in collectionView.

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
if scrolling direction is changed,
all layout need to be updated and initialized.
- ACR:
> [NUI] Initialize CollectionView when scrolling direction changed.

- src/Tizen.Multimedia/Interop/Interop.MediaTool.cs
- src/Tizen.Multimedia/MediaTool/AudioMediaFormat.cs
- Change pinvoke method
- Don't try to get AudioChannelMap when Channel is 0
> [MediaTool] Change pinvoke method

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultTitleItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
items and container is not cleared after view disposed.
fix collectionView and item dispose properly.
- ACR:
> [NUI] Fix dispoing collectionView and related classes.

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
> [NUI] Set FittingMode only when value has changed

- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Drawable.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
src/public/BaseComponents/VectorGraphics/CanvasView.cs
CanvasView
[Add] CanvasView(Size2D viewBox)
[Add] void AddDrawable(Drawable drawable)
src/public/BaseComponents/VectorGraphics/Drawable.cs
Drawable
[Add] float Opacity { get; set; }
[Add] bool Rotate(float degree)
[Add] bool Scale(float factor)
[Add] bool Transform(float[] matrix)
[Add] bool Translate(float x, float y)
src/public/BaseComponents/VectorGraphics/Shape.cs
Shape
[Add] Shape()
[Add] enum FillRuleType { Winding, EvenOdd }
[Add] enum StrokeCapType { Square, Round, Butt }
[Add] enum StrokeJoinType { Bevel, Round, Miter }
[Add] Color FillColor { get; set; }
[Add] FillRuleType FillRule { get; set; }
[Add] float StrokeWidth { get; set; }
[Add] Color StrokeColor { get; set; }
[Add] StrokeCapType StrokeCap { get; set; }
[Add] …
> [NUI] Open newly added APIs in VectorGraphics

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs
- src/Tizen.NUI.Components/Style/AlertDialogStyle.cs
This is ACR patch to make Dialog APIs public.
This pull request includes properties and methods of DialogPage, Dialog,
AlertDialog and AlertDialogStyle classes.
- ACR: TCSACR-419
> [NUI] Make Dialog APIs public

- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- For Slider, split some descriptions from summary according to a review.
: https://github.com/Samsung/TizenFX/pull/2872/files/512b187da7425c5a33feb7218cfd897b2b3174b1#r615520236
- For ViewEvent, fix the build warning : CS1570
"<" is "&lt;" and ">" is "&gt;" in XML comments.
- N/A
> [NUI] Update some descriptions

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/ItemSelectionMode.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/ItemsLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/SelectionChangedEventArgs.cs
- src/Tizen.NUI.Components/Style/DefaultLinearItemStyle.cs
- src/Tizen.NUI.Components/Style/DefaultTitleItemStyle.cs
- src/Tizen.NUI.Components/Style/RecyclerViewItemStyle.cs
- src/Tizen.NUI/src/public/Template/DataTemplate.cs
- src/Tizen.NUI/src/public/Template/DataTemplateSelector.cs
- src/Tizen.NUI/src/public/Template/ElementTemplate.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/CollectionViewGridSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewGridGroupSample.cs
This is ACR Patch to make CollectionView APIs public.
This pull request includes properties and methods of
DataTemplate
DataTemplateSelector
ElementTemplate
RecyclerView
CollectionView
ItemsLayouter
LinearLaouter
GridLayouter
RecyclerViewItem
~~DefaultLinearItem~~
~~DefaultGridItem~~
~~DefaultTitleItem~~
SelectionChangedEventArgs
ItemSelectdionMode
RecyclerViewItemStyle
~~DefaultLinearItemStyle~~
~~DefaultGridItemStyle~~
~~DefaultTitleItemStyle~~
- ACR: TCSACR-421
> [NUI] Make CollectionView APIs public

- src/Tizen.NUI.Components/Controls/TabBar.cs
- src/Tizen.NUI.Components/Controls/TabButton.cs
- src/Tizen.NUI.Components/Controls/TabContent.cs
- src/Tizen.NUI.Components/Controls/TabView.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TabViewSample.cs
This is ACR patch to make TabView APIs public.
This pull request includes properties and methods of TabView, TabBar,
TabButton, TabButtonstyle and TabContent classes.
- ACR: TCSACR-420
> [NUI] Make TabView APIs public

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSApplicationControlSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSApplicationSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSComponentApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSNUIComponentCoreBackend.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSNUICoreBackend.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSNUIWidgetCoreBackend.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSWatchApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSWatchBoolSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSWatchTimeSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Application/TSNUIApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Application/TSNUIComponentApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Application/TSNUIFrameComponent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Application/TSNUIWidgetApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Application/TSWatchTime.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Common/TSProperty.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Common/TSPropertyArray.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Common/TSPropertyNotifySignal.cs
1. Add Application(Internal & Public) TCs.
2. Fix some other issues for /public/common/Property*.
- ACR:
> [NUI] Add Application(Internal & Public) TCs.

- src/Tizen.Multimedia/Common.Internal/ValidationUtil.cs
Add Validation util and rename filename
> [Multimedia] Add Validation util and rename filename

- src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
- src/Tizen.NUI/src/internal/WebView/WebSettings.cs
> [NUI] Fix issue that a symbol is not found.

- src/Tizen.NUI/src/public/Utility/Palette.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PaletteSample.cs
Palette APIs public
https://code.sec.samsung.net/jira/browse/TCSACR-409
> [NUI] Make Palette APIs public

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/ICollectionChangedNotifier.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultTitleItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/ItemSelectionMode.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/ItemSizingStrategy.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/ObservableGroupedSource.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/ItemsLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/SelectionChangedEventArgs.cs
- src/Tizen.NUI.Components/Style/DefaultGridItemStyle.cs
- src/Tizen.NUI.Components/Style/DefaultLinearItemStyle.cs
- src/Tizen.NUI.Components/Style/DefaultTitleItemStyle.cs
- src/Tizen.NUI.Components/Style/RecyclerViewItemStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
- src/Tizen.NUI/src/public/Template/DataTemplate.cs
- src/Tizen.NUI/src/public/Template/DataTemplateSelector.cs
- src/Tizen.NUI/src/public/Template/ElementTemplate.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/CollectionViewGridSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/CollectionViewLinearSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Gallery.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewGridGroupSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewLinearGroupSample.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-421
> Make public CollectionView and Related Classes in Master

- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelEvent.cs
Signed-off-by: Bowon Ryu bowon.ryu@samsung.com
- AnchorClickedEventArgs
- string Href {get; set;}
TextLabel
- event EventHandler AnchorClicked
TextField
- event EventHandler AnchorClicked
TextEditor
- event EventHandler AnchorClicked
- ACR: TCSACR-415
- https://code.sec.samsung.net/jira/browse/TCSACR-415
> [NUI] Make AnchorClicked event public

- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SliderSample.cs
- Updated Slider sample to test touch event.
- To move the exact position of slided track and thumb by touch event,
TouchEvent should be connected with Slider control.
- N/A
> [NUI] Update Slider sample to test touch event

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Common/TimePeriod.cs
> [NUI] Fix some typo and grammar mistake

- src/Tizen.NUI/src/internal/Interop/Interop.WebPolicyDecisionMaker.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebPolicyDecisionMaker.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebViewResponsePolicyDecidedEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewResponsePolicyDecidedSignal.cs
This patch is related to the patch at csharp-binder side:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/257751/
- ACR:
> [NUI] Rename functions, variables, etc related to policy decision.

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSAnimatedImageVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSArcVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSBorderVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSColorVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSGradientVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSImageVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSMeshVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSNPatchVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSPrimitiveVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSSVGVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSTextVisual.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSVisualAnimator.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSVisualBase.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSVisualFactory.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Visuals/TSVisualMaps.cs
Add public/Visuals/* TCs.
- ACR:
> [NUI] Add Visuals(Public) TCs.

- src/Tizen.NUI.Components/Controls/Notification.cs
- src/Tizen.NUI/src/public/Window/Window.cs
> [NUI] Notification throws a proper exception when the device does not support it.

- src/Tizen.NUI/src/public/Common/NUIConstants.cs
Add Hyphenation ,Mixed to LineWrapMode enum.
dali patches are already merged, so this can be supported in NUI.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/254278/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/254279/
> [NUI] Add Hyphenation, Mixed to LineWrapMode

- src/Tizen.NUI/src/internal/WebView/WebView.cs
> [NUI] Fix issue that default value of BindableProperty is incorrect.

- src/Tizen.Telephony/Interop/Interop.Call.cs
> [Telephony][Non-ACR] Fix ReleaseCallList crash issue

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSAbsoluteLayout.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSFlexLayout.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSGridLayout.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSILayoutParent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSLayoutGroup.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSLayoutItem.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSLayoutLength.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSLayoutTransition.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSLinearLayout.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSMeasureSpecification.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSMeasuredSize.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSPaddingType.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSRelativeLayout.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Layouting/TSRelayoutContainer.cs
Add public/Layouting/* TCs.
- ACR:
> [NUI] Add Layouting(public) TCs.

- .github/workflows/deploy-documents-for-tizen-docs.yml
Add a workflow to deploy documents for https://docs.tizen.org
> [Build] Add a github workflow to deploy tizen docs

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
1. delay ScrollTo action till CollectionView is ready to scroll.
2. checking param index in ScrollTo().
3. override(new) ScrollToIndex(int index) to
ScrollTo(int index, bool anim, ItemScrollTo align).
- ACR:
> [NUI] refactoring ScrollTo.

- .github/workflows/deploy-packages.yml
Initial version of the deployment workflow for testing
> [Build] Add a workflow for package deployment

- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Layer.cs
- src/Tizen.NUI/src/public/Window.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FindChildByIDTest.cs
[NUI] Add FindLayerByID(), FindChildByID()
- FindLayerByID() in Window and FindChildByID() in View are added.
- These are all Hidden-APIs.
none
> [NUI] Add FindLayerByID(), FindDescendantByID()

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
1. delay ScrollTo action till CollectionView is ready to scroll.
2. checking param index in ScrollTo().
3. override(new) ScrollToIndex(int index) to
ScrollTo(int index, bool anim, ItemScrollTo align).
- ACR:
> [NUI] refactoring ScrollTo. (#3042)

- .github/workflows/deploy-packages.yml
- .github/workflows/nightly-release.yml
- Update `deploy-packages` workflow to deploy NuGet packages and submit changes to the Tizen gerrit server. 
- Update `nightly-release` workflow to trigger events for the `deploy-packages` workflow.
> [Build] Update workflow for release process

- src/Tizen.NUI/src/internal/Interop/Interop.Touch.cs
> [NUI] Change ulong to uint at Interop.Touch.GetMouseButton

- src/Tizen.NUI/src/internal/Xaml/XamlParser.cs
Support nest type in xaml
Sample:
`  <l:XamlPage-TestView Size="300,200" BackgroundColor="Red"/>`
C# code:
```
public partial class XamlPage : View
{
public class TestView : View
{
}
......
}
```
- ACR:
> [NUI][Xaml] Support nest type in Xaml

- src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
> [Bluetooth][Non-ACR] Add MTU functionalities (#2790)

- .github/workflows/deploy-documents-for-tizen-docs.yml
- .github/workflows/deploy-documents.yml
- .github/workflows/deploy-packages.yml
- .github/workflows/nightly-release.yml
- internals/src/Tizen.Inspections/Interop/Interop.Inspections.cs
- internals/src/Tizen.Inspections/Interop/Interop.Libraries.cs
- internals/src/Tizen.Inspections/Tizen.Inspections.csproj
- internals/src/Tizen.Inspections/Tizen.Inspections/DataRequestReceivedEventArgs.cs
- internals/src/Tizen.Inspections/Tizen.Inspections/Inspections.cs
- internals/src/Tizen.Peripheral/Interop/Gpio.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Gpio.cs
- packaging/csapi-tizenfx.spec
- pkg/Tizen.NET/runtime.json
- src/ElmSharp/ElmSharp/EcoreEvent.cs
- src/Tizen.Multimedia/Common.Internal/ValidationUtil.cs
- src/Tizen.Multimedia/Interop/Interop.MediaTool.cs
- src/Tizen.Multimedia/MediaTool/AudioMediaFormat.cs
- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
- src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
- src/Tizen.Telephony/Interop/Interop.Call.cs
integration from master to DevelNUI (2021-05-21)
none
> [NUI] integration from master to DevelNUI

- src/Tizen.NUI.Components/Controls/TabView.cs
In the latest UX of TabView, TabBar is located at the bottom of the
TabView.
- ACR:
> [NUI] Apply the latest UX of TabView

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
These properties are already supported in TextField.
And it should also be supported in TextEditor.
* Below patch should be applied first.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/258383/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/258408/
> [NUI] Add EnableGrabHandle, EnableGrabHandlePopup to TextEditor

- src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
> [NUI][AT-SPI] Fix DllImport typo in Interop.Accessibility.SuppressScreenReader

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
> [NUI] Fix item position to apply collectionView Padding

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
> [Bluetooth][Non-ACR] Add device name null check logic

- src/Tizen.NUI.Components/Controls/DatePicker.cs
- src/Tizen.NUI.Components/Controls/Picker.cs
- src/Tizen.NUI.Components/Controls/TimePicker.cs
Add accessibility information for Picker components to support UI Automation.
no changes
> [NUI][ATSPI] Default accessibility support for Picker components

- src/Tizen.NUI/src/internal/Interop/Interop.WebContext.cs
- src/Tizen.NUI/src/internal/WebView/WebContext.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
This patch is to rename some functions in WebContext too.
- ACR:
> [NUI] Fix crash when background color of webview is set.

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
> [NUI] Change interruptView to InterceptTouchEvent

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
item sizing on MeasureFirst need to reuse pre-calculated result.
- ACR:
> [NUI] fix CollecitonView item sizing on MeasureFirst

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
Page color is applied based on the latest UX.
- ACR:
> [NUI] Apply Page color

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Images/TSImageLoading.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Images/TSNativeImageSource.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Images/TSPixelBuffer.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Images/TSPixelData.cs
Add TCs for public/Images/* .
- ACR:
> [NUI] Add Images(public) TCs.

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSGesture.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSGestureDetector.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSGestureDetectorManager.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSHover.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSLongPressGesture.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSLongPressGestureDetector.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSPanGesture.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSPanGestureDetector.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSPinchGesture.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSPinchGestureDetector.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSRotationGesture.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSRotationGestureDetector.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSTapGesture.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSTapGestureDetector.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSTouch.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSWheel.cs
> [NUI] Add TCs for Event

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
- src/Tizen.NUI.Components/Theme/ThemeDark.cs
> [NUI] Fix not to apply DialogPage color

- src/Tizen.NUI/src/public/Common/Layer.cs
- src/Tizen.NUI/src/public/Window/Window.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FindChildByIDTest.cs
[NUI] Add FindLayerByID(), FindChildByID()
- FindLayerByID() in Window and FindChildByID() in View are added.
- These are all Hidden-APIs.
none
> [NUI] Add FindLayerByID(), FindChildByID()

- README.md
[NUI] sync from master to DevelNUI (2021-05-28)
"ACR Required" tag could be existed, but those are not NUI changes, so this PR is acceptable.
> [NUI] sync from master to DevelNUI

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
> [NUI] updating InternalItemsSource when header/footer is updated

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/ItemsLayouter.cs
> [NUI] fix contentcontainer size initalize

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
fix bug that touch highlight remaining when touch is not stable.
> [NUI] Cancel pressed state properly on touch events

- src/Tizen.NUI/src/internal/Interop/Interop.Capture.cs
- src/Tizen.NUI/src/public/Utility/Capture.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CaptureTest.cs
This patch must be merged after the dali-sharp-binder patch is merged.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/258849/
> [NUI] Add GetCapturedBuffer api for Capture

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSGestureDetector.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Events/TSGestureDetectorManager.cs
Add TCs for Public Events
- ACR:
> [NUI] Add TCs for Public Events

- src/Tizen.NUI/src/internal/EXaml/Action/GetValueAction.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
- src/Tizen.NUI/src/public/XamlBinding/Binding.cs
> [NUI] Fix issue that NUI will crash when load the boolean of "False" of EXaml. (Fix Jira 2295)

- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
Support for SetTextContents and InsertText (part of ATSPI text interface)
Requires:
https://review.tizen.org/gerrit/256956
https://review.tizen.org/gerrit/256957
https://review.tizen.org/gerrit/256963
NONE
> [NUI][AT-SPI] Support for SetTextContents and InsertText

- src/Tizen.Multimedia.Camera/Camera/Camera.Properties.cs
- src/Tizen.Multimedia.Camera/Camera/Camera.cs
- src/Tizen.Multimedia.Camera/Interop/Interop.Camera.cs
> [Camera] Add ctor for network camera

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
> [NUI] fix CollectionView scroll block issue.

- src/Tizen.NUI.Components/Controls/Picker.cs
Fix value change is not invoke when animation finished
no changes
> [NUI] Fix Picker value changed not invoked when align animation ended

- src/Tizen.NUI/src/public/Theme/Theme.cs
> [NUI] Theme constructor throws XamlParseException

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
…hen they can effect each other in Binding
Sample:
Xaml:
```
<?xml version="1.0" encoding="UTF-8" ?>
<View x:Class="Tizen.NUI.Examples.RelatedBindablePropertyPage"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
BackgroundColor = "Cyan" SizeWidth="1920" SizeHeight="1080">
<View x:Name="view" Position="100, 100" Size="300, 200" BackgroundColor="Blue"/>
<TextLabel x:Name="text1" Text="123" PositionX="{Binding Source={x:Reference view}, Path=PositionX, Mode=TwoWay}" PositionY="300"/>
<TextLabel x:Name="text2" Text="456" PositionY="{Binding Source={x:Reference view}, Path=PositionY, Mode=TwoWay}" PositionX = "800"/>
<View x:Name="view2" Position = "300, 500" BackgroundColor = "Green" SizeWidth="{Binding Source={x:Reference view}, …
```
> [NUI] Provide method so that user can register properties to group (JIRA 2301)

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/ItemsLayouter.cs
> [NUI] fix layouter null exception while clearing it

- src/Tizen.NUI/src/public/BaseHandle.cs
[NUI] Add hidden Disposed field for BaseHandle.
- ACR:
> [NUI] Add hidden  Disposed field for BaseHandle

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
> [NUI] Make BindableProperty of ItemsSource

- src/Tizen.Multimedia.Camera/Camera/Camera.Events.cs
- src/Tizen.Multimedia.Camera/Camera/Camera.cs
- src/Tizen.Multimedia.Camera/Camera/CameraDeviceManager.cs
> [Camera] Hide CDM interface from user

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
> [NUI] Fix button CellPadding policy and default CornerRadius

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewGridGroupSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewLinearGroupSample.cs
[NUI] make IsGrouped setter internal as only the GroupHeaderTemplate can enable it
none
> [NUI] make IsGrouped setter internal as only the GroupHeaderTemplate can enable it

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Input/TSAutofillContainer.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Input/TSFocusManager.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Input/TSInputMethod.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Input/TSInputMethodContext.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Input/TSKey.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Input/TSKeyValue.cs
Add TCs of public input
- ACR:
> [NUI] Add TCs of public input

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewGridGroupSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewLinearGroupSample.cs
…e can enable it"
This reverts commit 9ab325a08818ec3d492f91fe5bd70f4aaee3f614.
- ACR:
> Revert "make IsGrouped setter internal as only the GroupHeaderTemplate can enable it

- src/Tizen.NUI/src/internal/EXaml/Action/CreateInstanceAction.cs
- src/Tizen.NUI/src/internal/EXaml/Block/GatherMethodsBlock.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/CreateInstance.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GatherMethod.cs
- src/Tizen.NUI/src/internal/EXaml/Utility/GetBaseType.cs
Associated with the link https://github.com/nui-dali/Tizen.NUI.XamlBuild/pull/8。
Support factory method, so that user can create object by singleton method.
Sample
Xaml:
```
<?xml version="1.0" encoding="UTF-8" ?>
<View x:Class="Tizen.NUI.Examples.XFactoryMethodPage"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
BackgroundColor="White">
<WidgetView x:FactoryMethod="CreateWidgetView">
<x:Arguments>
<x:String>widget-efl.example</x:String>
<x:String></x:String>
<x:Int32>450</x:Int32>
<x:Int32>700</x:Int32>
<x:Single>-1</x:Single>
</x:Arguments>
</WidgetView>
</View>
```
C#:
User can define the method CreateWidgetView in the type of object which need to be created
```
public class WidgetView : View
{
public static WidgetView …
```
> [NUI][EXaml] Support FactoryMethod in EXaml (JIRE 2305)

- src/Tizen.NUI/src/internal/EXaml/Action/CreateInstanceAction.cs
- src/Tizen.NUI/src/internal/EXaml/Block/GatherMethodsBlock.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/CreateInstance.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GatherMethod.cs
- src/Tizen.NUI/src/internal/EXaml/Utility/GetBaseType.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
[NUI] selective integration from DevelNUI to master (2021-06-09)
none
> [NUI] selective integration from DevelNUI to master

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
> [NUI] fix initialize layouter on empty count source insertion

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/EXaml/TSEXamlExtensions.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/ViewProperty/TSBackgroundExtraData.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/ViewProperty/TSImageShadow.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/ViewProperty/TSShadow.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/ViewProperty/TSShadowBase.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/ViewProperty/TSTextShadow.cs
Add ViewProperty and EXaml(public) TCs.
- ACR:
> Add ViewProperty and EXaml(public) TCs.

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Transition/TSTransitionItem.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Transition/TSTransitionItemBase.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Transition/TSTransitionSet.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Transition/TSTransitionSetSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Transition/TSTransition.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Transition/TSTransitionBase.cs
Add Transition(internal & public) TCs.
- ACR:
> [NUI] Add Transition(internal & public) TCs.

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Theme/TSDefaultTheme.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Theme/TSDictionaryExternalTheme.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Theme/TSExternalThemeKeyList.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Theme/TSExternalThemeManager.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Theme/TSTheme.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Theme/TSThemeChangedEventArgs.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Theme/TSThemeManager.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Theme/TSTizenExternalTheme.cs
> [NUI] Add public theme TCs

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultTitleItem.cs
> [NUI] fix bug in item's content set

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
> [NUI] ThemeManager.GetStyle returns integrate style and fix some bugs. 

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
> [NUI] Update button components text size

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
> [NUI] enable groups regardless of groupHeader

- src/Tizen.NUI/src/internal/EXaml/Action/CreateInstanceAction.cs
- src/Tizen.NUI/src/internal/EXaml/Action/GetValueAction.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GatherStaticInstance.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
> [NUI][EXaml] 1.Support static instance in EXaml 2.Support BindableProperty Group

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
> [Bluetooth][Non-ACR] Fix GattConnectonStateChanged not occured issue

- src/Tizen.NUI.Components/Controls/DatePicker.cs
- src/Tizen.NUI.Components/Controls/TimePicker.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DatePickerSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TimePickerSample.cs
Changed the internal implementation to use the DateTime class supported by C# instead of specifying each year/month/day.
no changes
> [NUI] Change date/time picker param to formal C# DateTime

- src/Tizen.NUI.Components/Controls/Picker.cs
Fix picker scroll issue.
no changes
> [NUI] Fix Picker scroll issue with 4 or fewer items

- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
> [NUI][Xaml] Support create element in Xaml with default params

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
IsSelected Property defaultValue need to be false not true.
> [NUI] fix IsSelected default value true to false

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Accessibility/TSAccessibilityDoGestureSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/internal/Application/TSComponentApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Animation/TSPath.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Application/TSNUIWidgetApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Common/TSColor.cs
Fix errors of NUI line coverage TCs.
- ACR:
> [NUI] Fix errors of NUI line coverage TCs.

- src/Tizen.NUI.Components/Controls/DatePicker.cs
- src/Tizen.NUI.Components/Controls/Picker.cs
- src/Tizen.NUI.Components/Controls/TimePicker.cs
picker components does not need value interface.
picker works like container so it does not need highlightable.
no changes
> [NUI][ATSPI] Modify Accessbility for picker components

- src/Tizen.Multimedia.Camera/Camera/Camera.Events.cs
- src/Tizen.Multimedia.Camera/Camera/Camera.cs
- src/Tizen.Multimedia.Camera/Camera/CameraDeviceConnectionChangedEventArgs.cs
- src/Tizen.Multimedia.Camera/Camera/CameraDeviceManager.cs
- src/Tizen.Multimedia.Camera/Interop/Interop.Camera.cs
- Renamed `CameraDeviceListChanged` event to `DeviceListChanged` event
- Added `DeviceConnectionChanged` event
- Added `IsExternalCameraConnected` property
> [Camera] Add DeviceConnectionChanged event

- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Window/TSGLWindow.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Window/TSGLWindowEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Window/TSGLWindowVisibilityChangedEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Window/TSWindow.cs
> [NUI] Add public window TCs

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSAnimatedImageView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSAnimatedVectorImageView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSCameraView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSControlState.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSCustomView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSFlexContainer.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSImageView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSLottieAnimationView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextEditor.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextField.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextLabelEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextLabelSelectorData.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextUtils.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSViewAccessibility.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSViewPublicMethods.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSViewSelectorData.cs
Add BaseComponents(public) TCs.
- ACR:
> [NUI] Add BaseComponents(public) TCs.

- src/Tizen.Multimedia.Camera/Camera/Camera.Events.cs
- src/Tizen.Multimedia.Camera/Camera/Camera.cs
- src/Tizen.Multimedia.Camera/Camera/CameraDeviceConnectionChangedEventArgs.cs
- src/Tizen.Multimedia.Camera/Camera/CameraDeviceManager.cs
- src/Tizen.Multimedia.Camera/Interop/Interop.Camera.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
[NUI] sync from master to DevelNUI (2021-06-23)
> [NUI] sync from master to DevelNUI 

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/ItemsLayouter.cs
> [NUI] Fix itemslayouter nullable value checking.

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- src/Tizen.NUI/src/internal/Interop/Interop.FadeItem.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TransitionItemBase.cs
- src/Tizen.NUI/src/internal/Transition/FadeItem.cs
- src/Tizen.NUI/src/internal/Transition/TransitionItemBase.cs
- src/Tizen.NUI/src/public/Transition/Fade.cs
- src/Tizen.NUI/src/public/Transition/TransitionBase.cs
Add Fade Transition for the appearing/disappearing transition of Page
> [NUI] Add fade transition

- src/Tizen.NUI/src/internal/Interop/Interop.ImageLoading.cs
- src/Tizen.NUI/src/public/Images/ImageLoading.cs
Allow to load image from c# Stream class
> [NUI] API for load image from System.IO.Stream

- src/Tizen.NUI/src/internal/Application/Application.cs
- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
- src/Tizen.NUI/src/public/XamlBinding/Element.cs
1.Remove disposed instance from XamlResource.
2.Support BindingContext in EXaml.
- ACR:
> [NUI] Fix Issue of JIRA2301

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Widget/TSWidgetApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Widget/TSWidgetImpl.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Widget/TSWidgetImplPtr.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Widget/TSWidgetViewSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Widget/TSWidget.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Widget/TSWidgetView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Widget/TSWidgetViewManager.cs
Add Widget(internal & public) TCs.
- ACR:
> [NUI] Add Widget(internal & public) TCs.

- src/Tizen.NUI/src/internal/EXaml/Action/CallAddMethodAction.cs
- src/Tizen.NUI/src/internal/EXaml/Action/OtherActions.cs
- src/Tizen.NUI/src/internal/EXaml/Block/GatherAssembliesBlock.cs
- src/Tizen.NUI/src/internal/EXaml/Block/GatherEventsBlock.cs
- src/Tizen.NUI/src/internal/EXaml/Block/GatherMethodsBlock.cs
- src/Tizen.NUI/src/internal/EXaml/Block/GatherPropertiesBlock.cs
- src/Tizen.NUI/src/internal/EXaml/Block/GatherTypesBlock.cs
- src/Tizen.NUI/src/internal/EXaml/GlobalDataList.cs
- src/Tizen.NUI/src/internal/EXaml/LoadEXaml.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/CallAddMethod.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/CreateArrayInstance.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/SetProperty.cs
- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
- src/Tizen.NUI/src/internal/Xaml/XamlParser.cs
- src/Tizen.NUI/src/public/EXaml/EXamlExtensions.cs
Fix JIRA https://code.sec.samsung.net/jira/browse/GRE-2307
Relate to https://github.com/nui-dali/Tizen.NUI.XamlBuild/pull/20
1. Support Array in EXaml.
2. Rewrite the method of load examl, now user can put .xaml files every where.
- ACR:
> [NUI][EXaml] Support Array in EXaml

- src/Tizen.NUI/src/internal/WebView/WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebViewPageLoadEventArgs.cs
> [NUI] Change WebView namespace to Tizen.NUI.BaseComponents

- src/Tizen.Multimedia.Camera/Camera/CameraDeviceManager.cs
Change the way to invoke CDM event
> [Camera] Change the way to invoke CDM event

- src/Tizen.NUI.Components/Controls/Switch.cs
> [NUI] Switch icon includes track and thumb for aligning

- src/Tizen.NUI.Components/Controls/Button.cs
> [NUI] Add API Button.IconSize

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSBuilder.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSCamera.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSColorCutQuantizer.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSColorHistogram.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSColorUtils.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSConnectionTracker.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSConnectionTrackerInterface.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSCreateWidgetFunction.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSEnvironmentVariable.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSGaussianBlurViewSignal.cs.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItem.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItemCollection.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItemFactory.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItemIdCollection.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItemLayout.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItemRange.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItemView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSPageFactory.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSPagePanSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSPageTurnLandscapeView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSPageTurnPortraitView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSPageTurnSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSPageTurnView.cs
Add Utility(internal) TCs.
- ACR:
> [NUI] Add Utility(internal) TCs.

- src/Tizen.Multimedia.Camera/Camera/Camera.cs
Don't dispose CameraDeviceManager instance when Camera instance is disposing.
> [Camera] Change the dispose timing of CameraDeviceManager

- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
RelativeLayout sets its children's size in OnLayout().
Therefore, the children's MeasuredWidth/Height are not the same with the
children's size.
This causes that the grand children's MeasuredWidth/Height are calculated
incorrectly.
To resolve the above, RelativeLayout updates its children's MeasuredWidth/Height
based on the children's actual size on RelativeLayout after the RelativeLayout's
MeasuredWidth/Height are calculated.
e.g.
Let parent have RelativeLayout and parent's size be 1920x1080.
Let child have WrapContent with SetFillHorizontal/Vertical true.
Let grand child have MatchParent.
Then, child's size is 1920x1080 but child's MeasuredWidth/Height is 0x0.
Then, grand child's MeasuredWidth/Height is 0x0 and size is 0x0.
- ACR:
> [NUI] Fix to calculate RelativeLayout's children MeasuredWidth/Height correctly

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSComponentApplication.cs
Application.AddResourceChangedCallback was removed , so remove related TCs.
- ACR:
> [NUI] Fix build error of Devel.NUI.Tests

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
> [NUI] Fix Navigator Transition issue

- src/Tizen.Multimedia.Camera/Camera/Camera.cs
- src/Tizen.Multimedia.Camera/Camera/CameraDeviceManager.cs
Consider there's no connected camera device.
> [Camera] Handle GetDeviceInformation returns null

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
> [NUI] Fix Dialog Transition issue

- src/Tizen.NUI/src/internal/XamlBinding/VectorTypeConverter.cs
> [NUI][Xaml] Support different params in Vector Converter

- src/Tizen.NUI/src/internal/Interop/Interop.Capture.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ImageUrl.cs
- src/Tizen.NUI/src/internal/Interop/Interop.NativeImageSource.cs
- src/Tizen.NUI/src/internal/Interop/Interop.PixelData.cs
- src/Tizen.NUI/src/internal/WebView/WebHitTestResult.cs
- src/Tizen.NUI/src/public/Images/ImageUrl.cs
- src/Tizen.NUI/src/public/Images/NativeImageSource.cs
- src/Tizen.NUI/src/public/Images/PixelData.cs
ImageUrl is a class for wrapping url that is get from external buffer.
it is used for lifecycle management of external buffers.
- ACR:
> [NUI] Add ImageUrl

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- this patch is hotfix to fix problem derived by transition order.
> [NUI] fix transition order

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView.cs
> [NUI] Add WebView.SetTtsFocus API

- src/Tizen.NUI/src/internal/Interop/Interop.WebContext.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebContextMenu.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebContext.cs
- src/Tizen.NUI/src/internal/WebView/WebContextMenu.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebViewContextMenuHiddenEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewContextMenuHiddenSignal.cs
- src/Tizen.NUI/src/internal/WebView/WebViewContextMenuShownEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewContextMenuShownSignal.cs
- test/Tizen.NUI.WebViewTest/SimpleWebViewApp.cs
- test/Tizen.NUI.WebViewTest/tizen-manifest.xml
This patch is related to the patch of dali-csharp-binder:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/260245/
- ACR:
> [NUI] Rename APIs related to context menu.

- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
> [NUI] Fix ThemeManager to return valid platform theme Id

- src/Tizen.NUI/src/internal/EXaml/Action/CreateInstanceAction.cs
- src/Tizen.NUI/src/internal/EXaml/Action/GetObjectByPropertyAction.cs
- src/Tizen.NUI/src/internal/EXaml/GlobalDataList.cs
- src/Tizen.NUI/src/internal/EXaml/LoadEXaml.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/CreateInstance.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GatherStaticInstance.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/RegisterXName.cs
Fix JIRA https://code.sec.samsung.net/jira/browse/GRE-2336.
Relative to patch https://github.com/nui-dali/Tizen.NUI.XamlBuild/pull/26.
- ACR:
> [XamlBuild] Remove static member in EXaml Operation

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSImageLoading.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSNativeImageSource.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSPixelBuffer.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSPixelData.cs
1. Chage "Url" to "GenerateUrl()"
2. New TCs for ImageUrl.
- ACR:
> [NUI] Fix build erros of Devel.NUI.Tests.

- src/Tizen.NUI/src/internal/Interop/Interop.EncodedImageBuffer.cs
- src/Tizen.NUI/src/public/Images/EncodedImageBuffer.cs
This patch will make some simple way to upload image from C# Stream to View.
- EncodedImageBuffer will create by C# Stream.
EncodedImageBuffer buffer = new EncodedImageBuffer(stream);
- Generate ImageUrl
ImageUrl url = buffer.GenerateUrl();
- You can use this ImageUrl as image's url
ImageView view = new ImageView(url.GetUrl());
This patch required below dali patches
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/261019/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/259415/
> [NUI] Add EncodedImageBuffer class (Load image frome Stream)

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/FrameBroker/TSDefaultFrameBroker.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/FrameBroker/TSFrameData.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/FrameBroker/TSSafeFrameBrokerHandle.cs
Add TCs of FrameBroker(internal).
- ACR:
> [NUI] Add TCs of FrameBroker(internal).

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
> [NUI] Change InterceptTouchEvent.

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultTitleItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
> [NUI] Rectoring items layout

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
> [Bluetooth][Non-ACR] Add log for converting devcie info

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
> [NUI] Change shouldIntercept value

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
> [NUI] Revert shouldIntercept check

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
> [Bluetooth][Non-ACR] Add log for converting devcie info (#3303)

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs
> [NUI] Supports moving focus of items in ScrollableBase

- src/Tizen.NUI/src/internal/Interop/Interop.PixelBuffer.cs
- src/Tizen.NUI/src/public/Images/PixelBuffer.cs
> [NUI] Add GetBrightness()

- src/Tizen.NUI/src/internal/Interop/Interop.FocusManager.cs
- src/Tizen.NUI/src/public/Input/FocusManager.cs
> [NUI] Add EnableDefaultAlgorithm and IsDefaultAlgorithmEnabled

- src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
Add missed Exception description and code clean.
> [ThumbnailExtractor] Add missed description

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
> [NUI] Reset transition order to match scene tree order

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSBuilder.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItemCollection.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItemIdCollection.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Animation/TSTransitionOptions.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextUtils.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSNativeImageSource.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Input/TSInputMethodContext.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Input/TSKeyValue.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Utility/TSCapture.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Utility/TSScrollView.cs
> [NUI] Fix fail issues of NUI.Devel.Test .

- src/Tizen.NUI/src/internal/Interop/Interop.Rotation.cs
- src/Tizen.NUI/src/public/Common/Rotation.cs
- Adds new Rotation Constructor that uses two Vector3
> [NUI] Add new rotation constructor

- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- Added `IsEnabled` property in Slider and Progress components
- N/A
> [NUI] Add Enabled property to Slider and Progress

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI/src/internal/Common/KeyboardRepeatSettingsChangedSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Rotation.cs
- src/Tizen.NUI/src/internal/Window/WindowEffectSignal.cs
- src/Tizen.NUI/src/internal/Window/WindowVisibilityChangedEvent.cs
- src/Tizen.NUI/src/public/Common/Rotation.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples.sln
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CaptureTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/NavigatorSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowEventsTest.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSBuilder.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItemCollection.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Utility/TSItemIdCollection.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Animation/TSTransitionOptions.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextUtils.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSNativeImageSource.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Input/TSInputMethodContext.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Input/TSKeyValue.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Utility/TSCapture.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Utility/TSScrollView.cs
[NUI] sync from DevelNUI to master
none
> [NUI] sync from DevelNUI to master

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
> [NUI] Implement WebView.GetPlainTextAsynchronously method

- src/Tizen.NUI/src/public/BaseComponents/View.cs
> [NUI] Add some comment about Animatable property of View

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView.cs
> [NUI] Implement WebView.GetPlainTextAsynchronously method (#3344)

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
> [Bluetooth][Non-ACR] Fix DeviceName converting issue

- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
> [NUI] Fix bugs in ViewStyle.CopyFrom

- test/Tizen.NUI.WebViewTest/SimpleWebViewApp.cs
> [NUI] Update webview sample code.

- src/Tizen.NUI/src/internal/EXaml/Action/OtherActions.cs
- src/Tizen.NUI/src/internal/EXaml/Block/GatherLongStringsBlock.cs
- src/Tizen.NUI/src/internal/EXaml/GlobalDataList.cs
- src/Tizen.NUI/src/internal/EXaml/LoadEXaml.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/AddToCollectionInstance.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/CreateDataTemplate.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/CreateInstance.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GatherType.cs
- src/Tizen.NUI/src/public/EXaml/EXamlExtensions.cs
Support DataTemplate in EXaml.
Relate to patch https://github.com/nui-dali/Tizen.NUI.XamlBuild/pull/30.
Sample code of Xaml:
in CollectionViewCustomItemTestPage.xaml
```
<?xml version="1.0" encoding="UTF-8" ?>
<ContentPage
xmlns:local="clr-namespace:NUITizenGallery" x:Class="NUITizenGallery.CollectionViewCustomItemTestPage"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
WidthSpecification="{Static LayoutParamPolicies.MatchParent}"
HeightSpecification="{Static LayoutParamPolicies.MatchParent}">
<ContentPage.XamlResources>
<DataTemplate x:Key="Template">
<local:CollectionViewCustomItem />
</DataTemplate>
</ContentPage.XamlResources>
<ContentPage.AppBar>
<AppBar x:Name="appBar" Title="CollectionViewCustomItemTestPage"/> …
```
> [NUI][EXaml] Support DataTemplate in EXaml

- src/Tizen.NUI/src/internal/Interop/Interop.GestureOptions.cs
- src/Tizen.NUI/src/public/Events/GestureOptions.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TouchGestureSample.cs
> [NUI] GestureOptions Binding

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
> Rebase DevelNUI

- src/Tizen.NUI/src/internal/Interop/Interop.RiveAnimationView.cs
- src/Tizen.NUI/src/public/BaseComponents/RiveAnimationView.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveAnimationTest.cs
> [NUI] RiveAnimationView: refines the function and parameter names

- src/Tizen.NUI/src/internal/Interop/Interop.RiveAnimationView.cs
- src/Tizen.NUI/src/public/BaseComponents/RiveAnimationView.cs
> [NUI] RiveAnimationView: Add SetAnimationElapsedTime API

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
> [NUI] Unparent view when Dispose() is called explicitly

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
Text input filter based on regular expressions.
This should be merged with the patch below.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/258630/
> [NUI] Add InputFilter to TextField, TextEditor

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
> [NUI] Fix wrong code of initialize style in View

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
FlexLayout calculated child view's size in OnLayout() without
considering child layout's measured size unlike other layouts'
OnLayout().
This caused that the grand child view's size was calculated incorrectly
if the child and grand child had MatchParent Width/HeightSpecification.
To resolve this issue, child layout's measured size is set with the
child view's size calculated by dali-toolkit's YOGA APIs.
- ACR:
> [NUI] Fix FlexLayout to measure its child correctly

- src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
Signed-off-by: JinWang An <jinwang.an@samsung.com>
Change to call lock( ) about event handler
> Add and change lock about event handler

- src/Tizen.NUI/src/internal/Interop/Interop.Gradient.cs
- src/Tizen.NUI/src/internal/Interop/Interop.LinearGradient.cs
- src/Tizen.NUI/src/internal/Interop/Interop.RadialGradient.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Shape.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Gradient.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/LinearGradient.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/RadialGradient .cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CanvasViewSamsple.cs
Add Gradient, LinearGradient, and RadialGradient classes that
implement Linear and Radial Gradient features.
Each Gradient can be applied to Fill and Stroke of Shape after
setting Bounds and ColorStop suitable for style.
- ACR:no
dependency patch : 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/261217/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/262262/
> [NUI] VectorGraphics: Add Gradient feature

- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
Changes viewbox interface method to property.
- ACR: no
> [NUI] CanvasView: Change viewBox method to property

- src/Tizen.Nlp/Tizen.Nlp/NaturalLanguageProcess.cs
Signed-off-by: Jihoon Kim <jihoon48.kim@samsung.com>
Prevent crash due to exception when bundle does not have contain item
N/A
> [NLP] Fix crash issue

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
Add struct to Tizen.NUI.Text namespace :
Underline, Shadow, Outline, TextFit
The added structure is available through the Set/Get methods :
Set/GetUnderline, Set/GetShadow, Set/GetOutline, Set/GetTextFit
> [NUI] Add struct Underline, Shadow, Outline, TextFit to Text Components

- src/Tizen.NUI.Components/Controls/Menu.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI/src/internal/EXaml/Action/GetObjectByPropertyAction.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/SetBinding.cs
- src/Tizen.NUI/src/internal/XamlBinding/WeakEventManager.cs
> [NUI] Fix svace defects

- src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
Signed-off-by: JinWang An <jinwang.an@samsung.com>
> [Tizen.System.SystemSettings] Remove lock about invoking event

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
Accidentally merged before the related dali-csharp-binder patch was merged.
This reverts commit d0e0dc427d0ff7a1d01cec085cb5dda7824a6111.
> Revert "[NUI] Add SelectionChanged Event (#3397)"

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSComponentApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Common/TSBaseObject.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Common/TSCustomActorImpl.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Common/TSDaliException.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Layouting/TSLayoutController.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/NativeBinding/TSNDalic.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/NativeBinding/TSintp.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/NativeBinding/TSuintp.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/NativeBinding/TSushortp.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Transition/TSFadeItem.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Transition/TSTransitionItem.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Transition/TSTransitionItemBase.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Transition/TSTransitionSet.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Accessibility/TSAccessibility.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Accessibility/TSAccessibilityManager.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Accessibility/TSAccessibilityManagerEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Accessibility/TSAccessibilityManagerEventArgs.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSAnimatedImageView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextEditorEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSViewAccessibilityEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSViewInternal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSImageLoading.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSImageUrl.cs
1. New TCs of NativeBinding(internal),  Accessibility(public) mainly.
2. Update some other TCs , include Transition(internal),  BaseComponents(public),  Images(public)
- ACR:
> [NUI] Add TCs of Accessibility(public) & NativeBinding(internal) .

- src/Tizen.NUI/src/internal/Interop/Interop.Shape.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/VectorGraphicsConstants.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CanvasViewSamsple.cs
Adds an API that adds a large path information.
The PathCommands has a PathCommandType array, a Point array
and the number of each array.
- ACR:no
dependency patch
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/262530/
> [NUI] VectorGraphics: Add Shape.AddPath API

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
This reverts commit 3cdf1f2609b3dd00a4ca2fee04927e7cd0cba070.
DALi related patches are ready.
So this commit can be activated.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/262091/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/262372/
> [NUI] Add SelectionChanged Event (#3397)

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
[NUI] Adding the Copy, Cut and paste public APIs to NUI.
Added:
- string CopyText() //Copy and return the selected text.
This function will copy the previously selected string into the clipboard and will return it.
- string CutText() //Cut and return the selected text.
This function will cut the previously selected string into the clipboard and will return it.
- void PasteText() //Paste the most recently copied/cut text.
This function will paste the most recent string in the clipboard stack into the text control.
> [NUI] Copy, Paste & Cut Public APIs

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- src/Tizen.NUI/src/internal/Interop/Interop.FadeTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/FadeTransitionItem.cs
- src/Tizen.NUI/src/public/Transition/FadeTransition.cs
- src/Tizen.NUI/src/public/Transition/Transition.cs
- src/Tizen.NUI/src/public/Transition/TransitionBase.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PageTransitionSample.cs
> [NUI] Refactoring FadeTransition

- src/Tizen.NUI/src/internal/Interop/Interop.ActorInternal.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FocusFinderSample.cs
> [NUI] Add FocusableChildren

- src/Tizen.NUI/src/internal/WebView/WebBackForwardList.cs
- src/Tizen.NUI/src/internal/WebView/WebContext.cs
- src/Tizen.NUI/src/internal/WebView/WebPasswordDataList.cs
- src/Tizen.NUI/src/internal/WebView/WebSecurityOriginList.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
> [NUI] Replace XXXList with IList<XXX>.

- src/Tizen.Multimedia.Remoting/Interop/Interop.WebRTC.cs
- src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
- src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.Events.cs
- src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs
Fix destroy bug and code clean
> [WebRTC] Fix destroy bug and code clean

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Pagination.cs
- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Controls/SelectButton.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- Added `Enabled` to check accessibility state
- N/A
> [NUI][ATSPI] Add a function to check whether accessibility is enabled

- src/Tizen.NUI/Properties/AssemblyInfo.cs
- src/Tizen.NUI/src/internal/EXaml/Action/CreateInstanceAction.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GatherTypeObject.cs
- src/Tizen.NUI/src/public/XamlBinding/Setter.cs
- src/Tizen.NUI/src/public/XamlBinding/TriggerBase.cs
Support Trigger in EXaml
relate to https://github.com/nui-dali/Tizen.NUI.XamlBuild/pull/33
- ACR:
> [NUI] Support trigger in EXaml

- src/Tizen.NUI/src/internal/Interop/Interop.Gradient.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Shape.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Gradient.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
int -> uint(unsigned int)
dali-csharp-binder patch : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/262968/
- ACR:no
> [NUI] CanvasView: Change parameter and return type of binder function

- src/Tizen.Multimedia.Remoting/WebRTC/MediaPacketSource.cs
> [WebRTC] Remove wrong state check code

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI/src/internal/Interop/Interop.SlideTransitionDirection.cs
- src/Tizen.NUI/src/internal/Interop/Interop.SlideTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/SlideTransitionItem.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
- src/Tizen.NUI/src/public/Transition/SlideTransition.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PageTransitionSample.cs
Do not merge before https://github.com/Samsung/TizenFX/pull/3425 is merged.
> [NUI] Add Slide transition

- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
Use MediaContent internal free method
> [MediaContent] Use MediaContent internal free method

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Common/TSBaseObject.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Common/TSCustomActorImpl.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Common/TSDaliEnumConstants.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Common/TSExtensions.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Common/TSFontMetrics.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Layouting/TSLayoutController.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSActionSheetArguments.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSAlertArguments.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSBindingExpression.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSContentPropertyAttribute.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSDependencyService.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSDevice.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSMessagingCenter.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSNUIConstantExtension.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSUriTypeConverter.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSVectorTypeConverter.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/MarkupExtensions/TSApplicationResourcePathExtension.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/MarkupExtensions/TSArrayExtension.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/MarkupExtensions/TSReferenceExtension.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/MarkupExtensions/TSResourcePathExtension.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/MarkupExtensions/TSStaticExtension.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/MarkupExtensions/TSThemeResourcePathExtension.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/MarkupExtensions/TSTypeExtension.cs
Major changes: 
1. Add TCs for internal/XamlBinding
2. Update TCs of public/Xaml, internal/Common ...
- ACR:
> [NUI] Update TCs of NUI.Devel.

- src/Tizen.NUI/src/internal/Interop/Interop.GestureOptions.cs
- src/Tizen.NUI/src/public/Events/GestureOptions.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TouchGestureSample.cs
Add SetTapMaximumAllowedTime binding
> [NUI] Add SetDoubleTapTimeout binding

- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
TextField
event EventHandler SelectionChanged
TextEditor
event EventHandler SelectionChanged
ACR : TCSACR-451
https://code.sec.samsung.net/jira/browse/TCSACR-451
> [NUI] Make SelectionChanged event for TextField & TextEditor public

- src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
- src/Tizen.Multimedia.MediaPlayer/Player/PlayerDisplayType.cs
- src/Tizen.Multimedia/Common/Display.cs
Support Video and UI sync mode
- TCSACR-447
> [MediaPlayer] Support Video and UI sync mode

- src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroring.cs
Fix exception bug
- TCSACR-440
> [ScreenMirroring] Fix exception bug

- src/Tizen.Multimedia.Remoting/Interop/Interop.WebRTC.cs
- src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs
Add CreateOffer/AnswerAsync method
- TCSACR-430
> [WebRTC] Add CreateOffer/AnswerAsync method

- src/Tizen.NUI/src/internal/WebView/WebContext.cs
- src/Tizen.NUI/src/internal/WebView/WebContextMenuItem.cs
- src/Tizen.NUI/src/internal/WebView/WebHitTestResult.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
- test/Tizen.NUI.WebViewTest/SimpleWebViewApp.cs
1) Renaming some private variables.
- ACR:
> [NUI] Fix issue that objects are disposed outside callback.

- src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
> [MediaPlayer] Fix svace issue

- src/Tizen.NUI/src/internal/Interop/Interop.ScaleTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/ScaleTransitionItem.cs
- src/Tizen.NUI/src/public/Transition/ScaleTransition.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PageTransitionSample.cs
Do not merge before https://github.com/Samsung/TizenFX/pull/3399 is merged.
> [NUI] Add Scale transition

- src/Tizen.NUI/src/public/BaseComponents/CameraView.cs
[NUI] Open newly added APIs in CameraView
https://code.sec.samsung.net/jira/browse/TCSACR-431
> [NUI] Open newly added APIs in CameraView

- src/Tizen.NUI/src/internal/Application/Application.cs
- src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
- src/Tizen.NUI/src/public/Window/Window.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Application/TSNUIApplication.cs
Support IME Keyboard application and window.
1. Unnecessary interfaces are removed.
2. Change method name.
3. Add test case.
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-436
> [NUI] Support public ime window

- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Drawable.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/DrawableGroup.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Gradient.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/LinearGradient.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Picture.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/RadialGradient .cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/VectorGraphicsConstants.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CanvasViewSample.cs
[Add ACR]
src/public/BaseComponents/VectorGraphics/CanvasView.cs
[Add] public CanvasView()
[Add] public Size2D ViewBox { get; set; }
[Add] public void RemoveDrawable(Drawable drawable)
[Add] public void RemoveAllDrawables()
src/public/BaseComponents/VectorGraphics/Drawable.cs
[Add] public Vector4 BoundingBox { get; }
[Add] public void ClipPath(Drawable clip)
[Add] public void Mask(Drawable mask, MaskType type)
src/public/BaseComponents/VectorGraphics/Shape.cs
[Add] public Gradient FillGradient { get; set; }
[Add] public Gradient StrokeGradient { get; set; }
[Add] public void AddPath(PathCommands pathCommands)
src/public/BaseComponents/VectorGraphics/DrawableGroup.cs
[Add] public DrawableGroup()
[Add] public void AddDrawable(Drawable drawable)
[Add] public void RemoveDrawable(Drawable …
> [NUI] VectorGraphics:Open added APIs(DrawableGroup, Picture, Gradient)

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
> [NUI] Fix typo from synchronos to synchronous

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
The setter of this properties can be replaced with the SelectText(int start, int end) method.
> [NUI] Change SelectedTextStart, SelectedTextEnd to read-only

- src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObjectExtensions.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
- src/Tizen.NUI/src/public/XamlBinding/Binding.cs
Remove Obsolete methods.
- ACR:
> [NUI] Remove Obsolete methods

- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
Signed-off-by: Shrouq Sabah s.sabah@samsung.com
- TextUtils.cs
-  public static string CopyToClipboard(TextView textView) //API
-  public static string CutToClipboard(TextView textView) //API
-  public static void PasteTo(TextView textView) //API
- ACR: TCSACR-455
https://code.sec.samsung.net/jira/browse/TCSACR-455
> [NUI] Make Copy, Cut and Paste APIs public

- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
Reverts Samsung/TizenFX#3501
sorry, ACR has not been accepted.
> Revert "[NUI] Make Copy, Cut and Paste APIs public"

- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
TextField
event EventHandler CursorPositionChanged
TextEditor
event EventHandler CursorPositionChanged
ACR : TCSACR-452
https://code.sec.samsung.net/jira/browse/TCSACR-452
> [NUI] Make CursorPositionChanged event for TextField & TextEditor public

- src/Tizen.NUI/src/public/Common/NUIConstants.cs
Open the following members of LineWrapMode to public
-Hyphenation
-Mixed
ACR : TCSACR-450
https://code.sec.samsung.net/jira/browse/TCSACR-450
> [NUI] Make Hypenation & Mixed line wrap modes public

- src/Tizen.NUI/src/public/WebView/WebPageLoadError.cs
- src/Tizen.NUI/src/public/WebView/WebView.cs
- src/Tizen.NUI/src/public/WebView/WebViewPageLoadErrorEventArgs.cs
- src/Tizen.NUI/src/public/WebView/WebViewPageLoadEventArgs.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-434
> [NUI] Make APIs of WebView editor-browsable

- src/Tizen.NUI.Components/Controls/DatePicker.cs
- src/Tizen.NUI.Components/Controls/Picker.cs
- src/Tizen.NUI.Components/Controls/TimePicker.cs
Make Picker APIs public
- ACR: TCSACR-429
https://code.sec.samsung.net/jira/projects/TCSACR/issues/TCSACR-429?filter=allopenissues
> [NUI] Make Picker APIs public

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Window/Window.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SubWindowTest.cs
- test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/public/Window/TSWindow.cs
Add new SetParent in Window.
This method has the input flag is whether the child is located above or below of the parent.
> [NUI] Add new SetParent in Window

- src/Tizen.Multimedia.Camera/Camera/Camera.cs
- src/Tizen.Multimedia.Camera/Camera/CameraEnums.cs
Change Default CameraDevice value and Camera ctor code clean
> [Camera] Change Default CameraDevice value

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CircularTextSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CubeTransitionEffectSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FindChildByIDTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PaletteSample.cs
- This is related with https://github.com/Samsung/TizenFX/pull/3385
- some APIs have been changed by https://code.sec.samsung.net/jira/browse/TCSACR-438
none
> [NUI] Fix Tizen.NUI.Samples build error

- src/Tizen.NUI.Extension/Interop/Interop.RiveAnimationView.cs
- src/Tizen.NUI.Extension/Properties/AssemblyInfo.cs
- src/Tizen.NUI.Extension/RiveAnimation/RiveAnimationView.cs
- src/Tizen.NUI.Extension/Tizen.NUI.Extension.csproj
- src/Tizen.NUI.Extension/Tizen.NUI.Extension.sln
- src/Tizen.NUI/src/internal/Common/FriendAssembly.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveAnimationFollowTouch.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveAnimationRollInOut.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveAnimationTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveAnimationUniverse.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
- RiveAnimationView is added that supports rive-tizen
- ACR:
> [NUI][TSCACR-454] Add RiveAnimationView APIs 

- src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObjectExtensions.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
- src/Tizen.NUI/src/public/XamlBinding/Binding.cs
> [NUI] Roll back to fix build error of TCT code

- src/Tizen.NUI/src/internal/images/ImageLoading.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- by https://github.com/Samsung/TizenFX/commit/5e6a5476cc2fb4058825cdd85c926b0122e9211c#diff-c25dc46367b0c7780310d5cc10e3687b5ce460795cd7d4839a56595d2f977def, TCT failed.
- Add previously used hidden API first and then will fix TCT not to use ACRed API.
none
> [NUI] Fix TCT error

- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
- Move Animating to Process()
Reduce animation calling count.
- ACR:
> [NUI] Layout Transition Performance Improvement

- src/Tizen.NUI/src/public/Transition/ScaleTransition.cs
> [NUI] Change Default value of Scale Transition

- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
TextField
event EventHandler SelectionCleared
TextEditor
event EventHandler SelectionCleared
ACR : TCSACR-453
https://code.sec.samsung.net/jira/browse/TCSACR-453
> [NUI] Make SelectionCleared event for TextField & TextEditor public

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
Signed-off-by: Shrouq Sabah s.sabah@samsung.com
- NUIConstants
-  EllipsisPosition {End, Start, Middle}   // Enum
- TextLabel
-  EllipsisPosition { get; set; } // Property
- TextField
-  EllipsisPosition { get; set; }      // Property
- TextEditor
-  EllipsisPosition { get; set; }    // Property
-  Ellipsis { get; set; }   
- ACR: TCSACR-444
- https://code.sec.samsung.net/jira/browse/TCSACR-444
> [NUI] Make EllipsisPosition property public

- src/Tizen.NUI/src/public/Utility/GraphicsTypeManager.cs
> [NUI] Read ScalingFactor from environment.

- src/Tizen.Applications.Cion/Tizen.Applications/ClientBase.cs
- src/Tizen.Applications.Cion/Tizen.Applications/ServerBase.cs
Fix dereferencing null value.
N/A
> [Applications.Cion] Fix svace issue

- src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodContext.cs
[Inputmethod] Fix enum values to get InputHint correctly
- ACR:
> [Inputmethod] Fix enum values to get InputHint correctly

- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutTransitionManager.cs
Separate class to help understanding for layout process.
- ACR:
> [NUI] Separate the LayoutTransition from LayoutController

- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
> [NUI] apply scaling factor to point size

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
> [NUI] Prevent zero division of item StepCandidate

- src/Tizen.NUI/src/public/Common/TimePeriod.cs
> [NUI] fix to use static converter in timeperiod

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Xaml/TSReflectionExtensions.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Xaml/TSXamlLoader.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Xaml/TSXamlParser.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/Interactivity/TSMultiCondition.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/XamlBinding/TSTemplateBinding.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/TSViewExtensions.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/TotalSample/FactoryMethodMissingMethod.xaml.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/TotalSample/XStaticException.xaml.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/XamlBinding/Interactivity/TSBehavior.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/XamlBinding/TSBindingBase.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/XamlBinding/TSElement.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/XamlBinding/TSResourceDictionary.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/XamlBinding/TSTriggerBase.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/XamlBinding/TSXamlStyle.cs
1. Add xaml & xamlbinding testcases
- ACR:
> [NUI] Add xaml & xamlbinding testcases

- src/Tizen.NUI/src/internal/Utility/Camera.cs
- src/Tizen.NUI/src/internal/Utility/CameraBindableProperty.cs
- src/Tizen.NUI/src/internal/Utility/ItemView.cs
- src/Tizen.NUI/src/internal/Utility/ItemViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/AnimatedImageViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
- src/Tizen.NUI/src/public/BaseComponents/LottieAnimationViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityProperties.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/CustomView/Spin.cs
- src/Tizen.NUI/src/public/WebView/WebView.cs
- src/Tizen.NUI/src/public/WebView/WebViewBindableProperty.cs
- src/Tizen.NUI/src/public/Widget/WidgetView.cs
> [NUI] Add BindableProperties to all public Properties

- src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs
Remove invalid exception description that does not generated by this property
- No acr
> [Tts] Remove exception description that does not generated by this property

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
> [NUI] Add CreateDefaultLayout function

- src/Tizen.NUI/src/internal/WebView/WebBackForwardList.cs
- src/Tizen.NUI/src/internal/WebView/WebCertificate.cs
- src/Tizen.NUI/src/internal/WebView/WebContext.cs
- src/Tizen.NUI/src/internal/WebView/WebContextMenu.cs
- src/Tizen.NUI/src/internal/WebView/WebContextMenuItem.cs
- src/Tizen.NUI/src/internal/WebView/WebCookieManager.cs
- src/Tizen.NUI/src/internal/WebView/WebFormRepostPolicyDecisionMaker.cs
- src/Tizen.NUI/src/internal/WebView/WebHitTestResult.cs
- src/Tizen.NUI/src/internal/WebView/WebHttpAuthHandler.cs
- src/Tizen.NUI/src/internal/WebView/WebHttpRequestInterceptor.cs
- src/Tizen.NUI/src/internal/WebView/WebPasswordData.cs
- src/Tizen.NUI/src/internal/WebView/WebPasswordDataList.cs
- src/Tizen.NUI/src/internal/WebView/WebPolicyDecisionMaker.cs
- src/Tizen.NUI/src/internal/WebView/WebSecurityOriginList.cs
- src/Tizen.NUI/src/internal/WebView/WebSettings.cs
- src/Tizen.NUI/src/internal/WebView/WebViewUrlChangedEventArgs.cs
- src/Tizen.NUI/src/public/WebView/WebView.cs
And update some comments.
- ACR:
> [NUI] Replace PropertyMap with Dictionary in HitTest.

- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
- src/Tizen.NUI/src/internal/Xaml/TypeConversionExtensions.cs
- src/Tizen.NUI/src/internal/XamlBinding/ExtentsTypeConverter.cs
- src/Tizen.NUI/src/internal/XamlBinding/RectangleTypeConverter.cs
> [NUI] Apply dp converting in xaml float, int, extents, rectangles

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/XamlBinding/IntDpTypeConverter.cs
1. Support dp converter for Width/Height specification
```cs
<View WidthSpecification="100dp" HeightSpecification="100dp"/>
```
- ACR:
> [NUI] Support dp converter for Width/Height specification

- .github/workflows/deploy-packages.yml
Use the notice command of the workflow command.
https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-a-notice-message
This makes the SR Tag more easily exposed.
submit/20210927.091225 <- test message, ignore it :)
- ACR:no
> [Build] Print SubmitRequest Tag to Annotations

- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] Fix tct exception block issues
none
> [NUI] Fix tct exception block issues

- src/Tizen.NUI/src/internal/EXaml/Action/RootAction.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/CreateDPObject.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GatherAssembly.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GatherMethod.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/SetProperty.cs
- src/Tizen.NUI/src/internal/EXaml/Utility/EXamlOperationType.cs
> [NUI][EXaml] Support DP and PX in EXaml

- src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
This reverts commit 7006d62a55a69b5366b078bfbfcfbe3a346998ff.
- ACR:
> Revert "[NUI] Apply Padding and Margin in AbsoluteLayout"

- src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
Fix some description.
- Non ACR
> [Tizen.Applications.RPCPort] Fix description

- src/Tizen.NUI/src/public/Common/TimePeriod.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-468
> [NUI] Change ACR argument type of TimePeriod

- src/Tizen.NUI/Tizen.NUI.csproj
- src/Tizen.NUI/Tizen.NUI.sln
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/PropertyValue.cs
- src/Tizen.NUI/src/public/Common/Size2D.cs
[NUI] Change for Size2D property to own internalSize2D which is cashed to prevent making repeated Size2D instance
- https://code.sec.samsung.net/jira/browse/GRE-2368
none
> [NUI] Change for Size2D property to own internalSize2D which is cashed to prevent making repeated Size2D instance

- src/Tizen.NUI/src/internal/Interop/Interop.ImageView.cs
> [NUI] Make use image property again

- src/Tizen.Nlp/Tizen.Nlp/NaturalLanguageProcess.cs
Method Int.Parse is recommended to use with IFormatProvider argument.
- ACR:
> [Nlp] Fix parse method to add IFormatProvider arg

- src/Tizen.NUI/src/internal/Transition/FadeTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/ScaleTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/SlideTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/TransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/TransitionItemBase.cs
- src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
- src/Tizen.NUI/src/public/Transition/FadeTransition.cs
- src/Tizen.NUI/src/public/Transition/ScaleTransition.cs
- src/Tizen.NUI/src/public/Transition/SlideTransition.cs
- src/Tizen.NUI/src/public/Transition/Transition.cs
- src/Tizen.NUI/src/public/Transition/TransitionBase.cs
> [NUI] Move 'using's outside of namespace

- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/FlexibleView/TSFlexibleView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/FlexibleView/TSFlexibleViewLayoutManager.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/FlexibleView/TSFlexibleViewViewHolder.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/FlexibleView/TSGridLayoutManager.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/FlexibleView/TSLinearLayoutManager.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/FlexibleView/UtilityOfFlexView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/Item/TSDefaultGridItem.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/Item/TSDefaultLinearItem.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/Item/TSDefaultTitleItem.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/Item/TSRecyclerViewItem.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/ItemSource/TSEmptySource.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/ItemSource/TSListSource.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/ItemSource/TSMarshalingObservableCollection.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/ItemSource/TSObservableGroupedSource.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/ItemSource/TSObservableItemSource.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/Layouter/TSGridLayouter.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/Layouter/TSItemSource.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/Layouter/TSLinearLayouter.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/TSCollectionView.cs
Add TCs of FlexibleView and RecyclerView (Control).
- ACR:
> [NUI] Add TCs for NUI.Components.Devel.

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowBorderTest.cs
Add Window Border sample for testing.
> [NUI] Add WindowBorder Sample

- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
Update SelectionChanged event description based on comments from ACR.
https://github.com/Samsung/TizenFX/pull/3492#pullrequestreview-796067549
> [NUI] Update SelectionChanged event description

- src/Tizen.NUI/Tizen.NUI.csproj
- src/Tizen.NUI/Tizen.NUI.sln
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/PropertyValue.cs
- src/Tizen.NUI/src/public/Common/Size2D.cs
[NUI] Change for Size2D property to own internalSize2D which is cached to prevent making repeated Size2D instance 
https://code.sec.samsung.net/jira/browse/GRE-2368
none
> [NUI] Change for Size2D property to own internalSize2D which is cached to prevent making repeated Size2D instance 

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AccessibilityManagerSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DimTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RemoveAllChildrenTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveAnimationFollowTouch.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveAnimationRollInOut.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveAnimationTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveAnimationUniverse.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveMusicApp.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RiveMusicBoxApp.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SwitchSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VideoViewTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/ShowErrorPage.cs
[NUI] Fix some crash when NUI.Samples' running on Ubuntu
- No NUI code change, Only Sample changes.
none
> [NUI] Fix some crash when NUI.Samples' running on Ubuntu

- src/Tizen.NUI/src/internal/Transition/FadeTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/ScaleTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/SlideTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/TransitionGroupItem.cs
- src/Tizen.NUI/src/internal/Transition/TransitionItemBase.cs
- src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
- src/Tizen.NUI/src/public/Transition/ScaleTransition.cs
- src/Tizen.NUI/src/public/Transition/SlideTransition.cs
- src/Tizen.NUI/src/public/Transition/TransitionBase.cs
- src/Tizen.NUI/src/public/Transition/TransitionGroup.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PageTransitionSample.cs
> [NUI] Add Transition Group

- src/Tizen.Applications.Cion/Interop/Interop.CionServer.cs
- src/Tizen.Applications.Cion/Tizen.Applications.Cion/ServerBase.cs
The data from unmanaged code should be marshalled.
- ACR: N/A
> [Applications.Cion] Fix bug of sending data

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/Color.cs
- src/Tizen.NUI/src/public/Common/Extents.cs
- src/Tizen.NUI/src/public/Common/Position.cs
- src/Tizen.NUI/src/public/Common/Position2D.cs
- src/Tizen.NUI/src/public/Common/Size.cs
- src/Tizen.NUI/src/public/Common/Size2D.cs
[NUI] Change Color, Position2D, and etc properties to own only one instance
none
> [NUI] Change Color, Position2D, and etc properties to own only one instance

- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
> [NUI] Add ValueGetter to BindableObject

- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
Navigator should be Role.PageTabList
ContentPage should be Role.PageTab
- ACR:
> [NUI][ATSPI] Set Navigator, ContentPage role

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PageTransitionSample.cs
> [NUI] Fix method to gether Views for transition

- src/Tizen.NUI/src/internal/Common/Disposable.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] Add some debug log to check reference count of disposed object
none
> [NUI] Add some debug log to check reference count of disposed object

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
> [NUI] sync ATSPI patches

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] Add some debugging code to check if the object,which has no body, is used
none
> [NUI] Add some debugging code to check if the object,which has no body, is used

- src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
> [NUI] Make image visual actions protected

- src/Tizen.NUI/src/public/Transition/TransitionGroup.cs
> [NUI] Adds some description for the TransitionGroup

- src/Tizen.NUI/src/internal/Interop/Interop.WindowAuxiliaryMessageSignal.cs
- src/Tizen.NUI/src/internal/Window/WindowAuxiliaryMessageSignal.cs
- src/Tizen.NUI/src/public/Window/WindowAuxiliaryMessageEvent.cs
- src/Tizen.NUI/src/public/Window/WindowEvent.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowEventsTest.cs
Auxiliary message is sent by display server.
When client application added the window's auxiliary hint and if the auxiliary is changed, display server send the auxiliary message.
Auxiliary message has the key, value and options.
> [NUI] Add window auixiliary message event

- src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TextFitChangedSample.cs
> [NUI] Binding TextFitChanged event

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/res/Test_Theme.xaml
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/res/layout/BaseXamlSample.xaml
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/res/layout/BaseXamlSample3.xaml
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/res/layout/TotalSample.xaml
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/res/layout/XamlStyleSample.xaml
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Animation/TSAnimation.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSViewPublicMethods.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Common/TSPosition2D.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Common/TSSize.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Common/TSSize2D.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSPixelData.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Utility/TSPalette.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/ViewProperty/TSTextShadow.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/WebView/TSWebView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Widget/TSWidgetView.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Widget/TSWidgetViewManager.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Window/TSGLWindow.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Window/TSGLWindowEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Window/TSGLWindowVisibilityChangedEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Window/TSWindow.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/TSViewExtensions.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/TotalSample/BindingsCompiler.xaml.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/TotalSample/TotalSample.xaml.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Xaml/TotalSample/XReference.xaml
1. TCs failed in public/Theme, because lack of resource file.
2. Optimize some cases to fix block and crash issues.
- ACR:
> [NUI] Fix failed & block & crash TCs of NUI.Devel(API10).

- src/Tizen.NUI/src/internal/Common/Disposable.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] clean up debugging logs
none
> [NUI] clean up debugging logs

- src/Tizen.NUI/src/public/Utility/GraphicsTypeExtensions.cs
- src/Tizen.NUI/src/public/Utility/GraphicsTypeManager.cs
- src/Tizen.NUI/src/public/Utility/PointTypeConverter.cs
- src/Tizen.NUI/src/public/Utility/SpTypeConverter.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GraphicsTypeTest.cs
> [NUI] refactoring GraphicsType classes and Dp. Add new Type Sp

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/ButtonBindableProperty.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Controls/SliderBindableProperty.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
> [NUI] Add bindable properties

- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
[NUI] Remove redundant debug msg, No logic change
none
> [NUI][SVACE] Remove redundant debug msg, No logic change

- src/Tizen.NUI/src/public/XamlBinding/Element.cs
http://168.219.243.174:12000/sb2/main/review#PRJID=1&WGID=38820
- ACR:
> [NUI] Fix null pointer svace issue

- src/Tizen.Multimedia.Camera/Camera/Camera.Events.cs
[Camera] Fix UnsetExtraPreviewCallback bug
> [Camera] Fix UnsetExtraPreviewCallback bug

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- Update API reference of TextEditor / TextField / TextLabel
to match native C++ DALi descriptions.
- N/A
> [NUI] Update Text controls API reference

- src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
- src/Tizen.NUI/src/public/EXaml/EXamlExtensions.cs
- src/Tizen.NUI/src/public/XamlBinding/Element.cs
- src/Tizen.NUI/src/public/XamlBinding/Internals/NameScope.cs
1. Add XamlLoaded event for NUIApplication
2. Add XNames for Element
- ACR:
> Add xaml loaded and XNames 

- src/Tizen.NUI/src/public/Application/NUIApplication.cs
1. Add EditableBrowsable.Never for CurrentLoadedXaml
- ACR:
> [NUI] Add EditableBrowsable.Never for CurrentLoadedXaml

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Actor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ActorInternal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.FocusManager.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TapGesture.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Touch.cs
- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/FocusManager.cs
- src/Tizen.NUI/src/public/LongPressGestureDetector.cs
- src/Tizen.NUI/src/public/NUIConstants.cs
- src/Tizen.NUI/src/public/PanGestureDetector.cs
- src/Tizen.NUI/src/public/PinchGestureDetector.cs
- src/Tizen.NUI/src/public/RotationGestureDetector.cs
- src/Tizen.NUI/src/public/TapGesture.cs
- src/Tizen.NUI/src/public/TapGestureDetector.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FocusFinderSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TouchGestureSample.cs
1. [NUI] Add TouchArea property.
Default touchable area is view's size.
TouchArea can reset the view's touchable area.
This is usefull when the view is small, but it should have a larger touch area.
for example
View view = new View();
view.Size = new Size(10, 10);
view.TouchEvent += OnTouchEvent;
view.TouchArea = new Size2D(200, 200);
The view is small, If you want to set the touch area to a larger area,
you can use the TouchArea property.
2. [NUI] change type from Size2D to Size at TouchArea api
3. [NUI] Change  TouchArea to TouchAreaOffset (#2948)
You can expand the touch area.
for example)
View view = new View();
view.Size = new Size(10, 10);
view.TouchEvent += OnTouch;
view.TouchAreaOffset = new Offset(-100, 100, 100, -100); // left, right, bottom, top
then touch area is 210x210.
this …
> [NUI] Integrate Touch, Gesture and Focus patches

- src/Tizen.NUI/src/internal/Interop/Interop.GLView.cs
- src/Tizen.NUI/src/public/BaseComponents/GLView.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
This PR was supposed to merge into API9. But It is only in master.
So I'd like to apply this commit to API9.
GLView will be public in API10.
The original PR
https://github.com/Samsung/TizenFX/pull/3605
> [NUI] Add GLView

- src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-459
* src/Tizen.NUI/src/public/Common/NUIConstants.cs
* struct Tizen.NUI.Text.InputFilter
* string Accepted {get; set;}
* string Rejected {get; set;}
* enum InputFilterType
* Accept
* Reject
* src/Tizen.NUI/src/public/BaseComponents/TextField.cs
* void SetInputFilter(InputFilter inputFilter)
* InputFilter GetInputFilter()
* src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
* void SetInputFilter(InputFilter inputFilter)
* InputFilter GetInputFilter()
* src/Tizen.NUI/src/public/BaseComponents/TextEvent.cs
* InputFilteredEventArgs
* InputFilterType Type {get; set;}
* src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
* event EventHandler<InputFilteredEventArgs> InputFiltered
* …
> [NUI] Open Text InputFilter APIs

- src/Tizen.NUI/Tizen.NUI.sln
[NUI] Fix VS solution file to build the project
none
> [NUI] Fix VS solution file to build the project

- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
[NUI] Fix StopFinal(EndAction) not working defect on lite model
none
> [NUI] Fix StopFinal(EndAction) not working defect on lite model

- src/Tizen.NUI/src/internal/Common/VectorVector2.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
- src/Tizen.NUI/src/internal/Interop/Interop.VectorVector2.cs
- src/Tizen.NUI/src/public/BaseComponents/TextGeometry.cs
Add two API's to get rendered text geometry
-List<Size2D> GetTextSize(start, end)
-List<Position2D> GetTextPosition(start, end)
related patch : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/266891
> [NUI] Add support for text geometry API's

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextMapHelper.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextMapHelper.cs
- remove duplicate code through function extraction for better readability.
- simplified the code to get the map value from placdeholder property using TextMapHelper
- reduce memory waste by calling Dispose() or using Add() from PropertyMapSetterHelper
- add test cases for newly added internal apis of TextMapHelper
> [NUI] refactoring TextMapHelper

- src/Tizen.NUI/src/public/Utility/GraphicsTypeExtensions.cs
> [NUI] change function name for match others in GraphicsTypeExtensions.

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/Tizen.NUI.Devel.Tests.csproj
> [NUI] Fix build errors of NUI.Devel.Tests.

- src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
Fix description error.
https://github.com/Samsung/TizenFX/pull/3510#discussion_r741595090
- TCSACR-447
> [MediaPlayer] Fix description error

- src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
Fix description error.
https://github.com/Samsung/TizenFX/pull/3510#discussion_r741595090
- TCSACR-447
> [MediaPlayer] Fix description error(API9)

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextField.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextMapHelper.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextUtils.cs
- remove duplicate code from function extraction
- reduce loc & make better readability
- fix dispose warning CA2000 for prevent waste of memory
> [NUI] text testcase improvement

- src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs
> [WebRTC] Prevent cb instance from GC

- src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityProperties.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
Dependencies:
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/266918/ (merged)
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/266919/ (merged)
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/266921/ (merged)
- ACR: None
> [NUI][AT-SPI] Add AccessibilityHidden property

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextEditor.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextField.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextLabel.cs
for current, FontSizeScale is applied to all text.
Add EnableFontSizeScale to selectively apply FontSizeScale from SystemSettings
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/268999/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/269000/
> [NUI] Add EnableFontSizeScale to Text components

- src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
1. Fix issue if application info is null
- ACR:
> [NUI] Fix issue if application info is null

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/MultiWindowLayoutSample.cs
Previously, Layouts in the default Window were supported.
Now, to support Layout in Multi-Window, Layouts in all Windows are supported.
- ACR:
> [NUI] Support Layout for Multi-Window

- src/Tizen.NUI/src/internal/Common/ProcessorController.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ProcessorController.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
backport patch of PR #3829
- ACR:
> [NUI] Update ImageView properties lazy

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- src/Tizen.NUI/src/public/Utility/GraphicsTypeExtensions.cs
- src/Tizen.NUI/src/public/Utility/PointTypeConverter.cs
- src/Tizen.NUI/src/public/XamlBinding/PointSizeTypeConverter.cs
> [NUI] Apply Font scalable converter for sp, dp size.

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/ItemsLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
> [NUI] fix non-initialized exception on layout notifier

- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
1. Fix equals issue of Selector
- ACR:
> [NUI] Fix equals issue of Selector

- CODEOWNERS
> [NUI] Add NUI Code Onwers

- .github/CODEOWNERS
> [NUI] move codeowners under the github directories and fix typo.

- .github/CODEOWNERS
> [NUI] change individual code owners from team.

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Window/Window.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest.cs
Add IsWindowRotationg function.
It is return with true when window is rotating.
- ACR:
> [NUI] Add IsWindowRotating()

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SubWindowTest.cs
[NUI] Clean up SubWindowTest.cs
- change testcase methods' names.
- change case's variable as constant.
none
> [NUI] Clean up SubWindowTest.cs

- src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
override Eqauls, GetHashCode
overloaded == operator
> [NUI] Fix warnings for TextConstants

- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
- src/Tizen.Uix.InputMethod/Interop/Interop.InputMethod.cs
- src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputHintSetEventArgs.cs
- src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
> [NUI] Rebase master (master only patches --> DevelNUI)

- src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
added missing tag [EditorBrowsable(EditorBrowsableState.Never)]
Fixed equals, hash for newly added fields
> [NUI] fix text underline struct

- src/Tizen.Multimedia.Camera/Camera/Camera.Events.cs
- src/Tizen.Multimedia.Camera/Camera/Camera.cs
- src/Tizen.Multimedia.Camera/Camera/DepthPlane.cs
- src/Tizen.Multimedia.Camera/Camera/DoublePlane.cs
- src/Tizen.Multimedia.Camera/Camera/EncodedPlane.cs
- src/Tizen.Multimedia.Camera/Camera/PinnedPreviewBuffer.cs
- src/Tizen.Multimedia.Camera/Camera/PreviewFrame.cs
- src/Tizen.Multimedia.Camera/Camera/RgbPlane.cs
- src/Tizen.Multimedia.Camera/Camera/SinglePlane.cs
- src/Tizen.Multimedia.Camera/Camera/TriplePlane.cs
> [Camera] Fix preview gc issue

- src/Tizen.Multimedia.Camera/Camera/Camera.Events.cs
- src/Tizen.Multimedia.Camera/Camera/CameraDeviceManager.cs
- src/Tizen.Multimedia.Camera/Camera/PreviewFrame.cs
> [Camera] Remove useless logs

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextEditorEvent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextFieldEvent.cs
Add SelectionStarted event
editor.SelectionStarted += (s, e) =>
{
};
> [NUI] Add SelectionStarted event

- src/Tizen.Multimedia.Remoting/WebRTC/MediaFileSource.cs
Add new MediaFileSource APIs
- TCSACR-479
> [WebRTC] Add new MediaFileSource APIs

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
Added state change notifications for Insert() and Remove() methods when inserting/removing Page on top of Navigator.
- ACR: none
> [NUI][AT-SPI] Fixed A11y support for Navigator

- src/Tizen.NUI/src/public/XamlBinding/PointSizeTypeConverter.cs
1. Fix PointSizeTypeConverter error
- ACR:
> [NUI] Fix PointSizeTypeConverter error

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebViewPolicyDecidedEventArgs.cs
- src/Tizen.NUI/src/public/WebView/WebView.cs
- test/Tizen.NUI.WebViewTest/SimpleWebViewApp.cs
Related patch for csharp binder:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/268484/
- ACR:
> [NUI] Add callback for navigation policy decision.

- src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
ACR-1655 : https://code.sec.samsung.net/jira/browse/ACR-1655
- SENSOR_GYROSCOPE_ORIENTATION : orientation sensor based on gyroscope_rotation_vector
- SENSOR_GEOMAGNETIC_ORIENTATION: orientation sensor based on geomagnetic_rotation_vector
> [Sensor] Add orientation sensor type

- src/Tizen.Multimedia.Camera/Camera/Camera.Events.cs
- src/Tizen.Multimedia.Camera/Camera/Camera.cs
- src/Tizen.Multimedia.Camera/Camera/PinnedPreviewBuffer.cs
- src/Tizen.Multimedia.Camera/Camera/PreviewFrame.cs
> [Camera] Support variable buffer size

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/KeyFrameAnimationTest.cs
[NUI] Add KeyFrameAnimationTest sample
none
> [NUI] Add KeyFrameAnimationTest sample

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Window/Window.cs
[NUI] Add FeedTouch and FeedWheel
- ACR:
> [NUI] Add FeedTouch and FeedWheel

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/XamlBinding/FloatGraphicsTypeConverter.cs
- src/Tizen.NUI/src/public/XamlBinding/IntGraphicsTypeConverter.cs
- test/NUITizenGallery/Examples/GraphicsTypeTest/GraphicsTypeTest.cs
- test/NUITizenGallery/Examples/GraphicsTypeTest/GraphicsTypeTestPage.xaml
- test/NUITizenGallery/Examples/GraphicsTypeTest/GraphicsTypeTestPage.xaml.cs
- test/NUITizenGallery/NUITizenGallery.cs
- test/NUITizenGallery/NUITizenGallery.csproj
[NUI] Add FloatGraphicsTypeConverter and support converter in PixelSize in Text.
none
> [NUI] Add FloatGraphicsTypeConverter and support converter in PixelSize in Text.

- test/Tizen.NUI.StyleGuide/Examples/ButtonExample.cs
- test/Tizen.NUI.StyleGuide/Examples/ScrollableBase/ScrollableBaseDirectionExample.cs
- test/Tizen.NUI.StyleGuide/Examples/ScrollableBase/ScrollableBaseExample.cs
- test/Tizen.NUI.StyleGuide/Tizen.NUI.StyleGuide.cs
> [NUI] Apply focusable features and Automatic Focus algorithm

- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
Add `Forward` and `Backward` focus direction type on `FocusDirection`
Now, You can get Forward type by pressing Tab key and Backward type by pressing Shift-Tab key.
``` c#
public override View GetNextFocusableView(View currentFocusedView, View.FocusDirection direction, bool loopEnabled)
{
if (direction == View.FocusDirection.Forward)
{
// Tab
}
else if (direction == View.FocusDirection.Backward)
{
// Shift-Tab
}
} 
```
- ACR:
Added : 
``` c#
public enum FocusDirection {
Forward,
Backward,
}
```
> [NUI] Add forward and backward direction type on FocusDirection

- src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs
> [Tts] Fix the description of Repeat() (#3953)

- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TouchGestureSample.cs
[NUI] Integrate from DevelNUI to API9
- ACR:
> [NUI] Integrate from DevelNUI to API9

- src/Tizen.NUI.Components/Controls/Picker.cs
- src/Tizen.NUI.Components/Controls/TimePicker.cs
https://github.sec.samsung.net/dotnet/NUIBackend/issues/108
Fix ampm time calc logic.
No API Changes
> [NUI] Fix timePicker ampm internal logic

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
The CollectionView has role of list.
> [NUI][AT-SPI] Set CollectionView role to List

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- test/NUITestSample/NUITestSample/examples/AtspiTest.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Accessibility/TSAccessibility.cs
This class serves as a collection of unrelated methods, which are all static in DALi anyway, and as such is a good candidate for migration to a C# `static class`.
Complementary dali-csharp-binder patch (merge at the same time):
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/271723
- ACR: None
> [NUI][AT-SPI] Static class Accessibility

- test/NUITizenGallery/Examples/XamlIndexerTest/XamlIndexerTest.cs
- test/NUITizenGallery/Examples/XamlIndexerTest/XamlIndexerTest.xaml
- test/NUITizenGallery/Examples/XamlIndexerTest/XamlIndexerTest.xaml.cs
[NUI][Test] xaml indexer sample
- this is just a sample code to test xaml indexer by using markup extension
none
> [NUI][Test] xaml indexer sample

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
> [NUI] Prevent to call button up event when button is not pressed

- .github/workflows/deploy-packages.yml
- Bug: https://github.com/NuGet/Home/issues/11607
> [Build] Use dotnet sdk 6.0.102 in release workflow

- .github/workflows/deploy-packages.yml
- Bug: https://github.com/NuGet/Home/issues/11607
NUI weekly integration
doesn't matter
integrating master branch's PR
> [Build] Use dotnet sdk 6.0.102 in release workflow (#4012)

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
To show MenuItem's Selected theme, MenuItem's Selected theme color has
been added.
- ACR:
> [NUI] Add Selected theme color to MenuItem

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Window/Window.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest.cs
Add NUI Window's minimize and maximize feature.
It is for window border.
> [NUI] Add window min max feature

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
sync from master to DevelNUI
- ACR:
> [Bluetooth] Fix svace issues (#4025) 

- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
> [NUI][SVACE]Fix SVACE issue of 483571

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Wearable/src/public/CircularPagination.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
> [NUI][SVACE] Fix SVACE issues

- src/Tizen.NUI/src/public/BaseComponents/VisualView.cs
Due to the empty array issue, we change that we don't create visual when
UrlList is empty.
But current NUI.VisualView don't consider that visual failure case.
This patch consider case when we fail to create visual, so visual is null in VisualView.
- ACR:
> [NUI] Fix crash issue when visual create failed

- src/Tizen.NUI/src/internal/Common/DebugFileLogging.cs
- src/Tizen.NUI/src/internal/Common/Disposable.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] Fix test-hub crash issue
- make DisposeDebugging() as conditional code
- check the native handle's body so that avoid the crash when empty body's method is called
- https://github.com/Samsung/TizenFX/pull/4047/files#diff-bee9e6985a8752a86eb35fe2c89984d1fc9713e7b566ea7e576dc6df0979e0a8R119 
this fix is temporary fix, this will be recovered and resolved later. 
- https://github.com/Samsung/TizenFX/pull/4047/files#diff-8422e3bdf486b60a482770b2eb36b4e26cb591255ef4c0be7cd923f6b1ca0111R355
this fix is temporary fix, this will be recovered and resolved later. 
none
> [NUI] Fix test-hub crash issue
