- src/Tizen.NUI.Components/Controls/AlertDialog.cs
To show AlertDialog's Content at the center of AlertDialog,
AlertDialog's LinearLayout is center aligned.
- ACR:
> [NUI] Set AlertDialog's LinearLayout center aligned

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
Page's Appeared event is invoked when the Navigator's animation is
finished and the page becomes visible.
Page's Disappeared event is invoked when the Navigator's animation is
finished and the page becomes invisible.
- ACR:
> [NUI] Add Page's Appeared and Disappeared events

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Actor.cs
- src/Tizen.NUI/src/public/Events/LongPressGestureDetector.cs
- src/Tizen.NUI/src/public/Events/PanGestureDetector.cs
- src/Tizen.NUI/src/public/Events/PinchGestureDetector.cs
- src/Tizen.NUI/src/public/Events/RotationGestureDetector.cs
- src/Tizen.NUI/src/public/Events/TapGestureDetector.cs
This is used when the parent view wants to listen to gesture events.
- ACR:
> [NUI] Add NeedGesturePropagation

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
Previously, 2 descendant sizes and positions calculation problems
exitsted on RelativeLayout as follows.
1. MatchParent grand children's sizes and positions were not calculated.
- RelativeLayout set its children's sizes and positions but it did not
set its children's MeasuredWidth/Height.
- If children's MeasuredWidth/Height are not set, then the MatchParent
grand children's sizes and positions are not calculated.
2. MatchParent children's sizes fill to the RelativeLayout by default.
- MatchParent children's sizes should not fill to the RelativeLayout by
default because children's sizes and positions should be calculated
by RelativeLayout's APIs.
Now, the above problems have been fixed as follows.
1. RelativeLayout sets its children's MeasuredWidth/Height, so its
MatchParent grand …
> [NUI] Fix RelativeLayout's descendant size and position calculations

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
`ScrollToChild()` is used by `GrabHighlight()` to ensure that the item to be highlighted is visible on the screen (if it is inside a scrollable container). An override for `CollectionView` is also provided.
Dependencies:
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/255698/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/255699/
- ACR: None
> [NUI][AT-SPI] Bindings for ScrollToChild

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
[NUI] Fix implicit dispose exception defect
- when implicit dispose is done by DisposeQueue, the view which has empty body of dali gives exception.
- the "in Children" => this.Children give null reference exception.
none
> [NUI] Fix implicit dispose exception defect

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
SpaceAround distributes the equal space to before, and after each item.
Therefore, the space between adjacent items is twice bigger than the
space between the beginning edge and the first item.
To distribute the equal space to before, between, and after each item,
SpaceEvenly is added to FlexJustification.
Requires:
https://review.tizen.org/gerrit/259554/
- ACR:
> [NUI] Add SpaceEvenly to FlexJustification

- src/Tizen.NUI/src/internal/Interop/Interop.TransitionItem.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TransitionItemBase.cs
- src/Tizen.NUI/src/internal/Transition/TransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/TransitionItemBase.cs
Some internal properties of Transition are not used.
This patch remove the unused property
> [NUI] Remove unused property of Transition

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
The buttons in the ActionContent of AlertDialog are flickering because
the CellPadding of ActionContent's LinearLayout did not set initially.
To resolve this issue, the CellPadding of ActionContent's LinearLayout
is set initially.
However, this should be updated to apply CellPadding from
AlertDialogStyle.
- ACR:
> [NUI] Fix flickering buttons in ActionContent of AlertDialog

- src/Tizen.NUI/src/internal/Interop/Interop.ActorInternal.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
This is a property that allows you to have focus even when touched.
If Focusable is false, FocusableInTouchMode is disabled.
If you want to have focus on touch in touch mode, you need to set both settings to true.
focusable = true,
focusableInTouch = true,
- ACR:
> [NUI] Add FocusableInTouch property

- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
- If Progress size is set as relative properties, such as MatchParent or WrapContent,
the size of progress track is not drawn properly.
- Fixed to get the correct size of progress.
- Updated Progress theme.
- N/A
-
> [NUI] Fix Progress size issue

- src/Tizen.NUI/src/internal/XamlBinding/BindingExpression.cs
> [NUI] fix property binding error message

- src/Tizen.NUI/src/internal/XamlBinding/NUIConstantExtension.cs
- src/Tizen.NUI/src/public/Visuals/MeshVisual.cs
- src/Tizen.NUI/src/public/Visuals/PrimitiveVisual.cs
- src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
frustrum -> frustum
MaterialtURL -> MaterialURL
We need to change name 'ConicalFrsutrum' and delete 'MaterialtURL'.
but this process is required ACR.
I will upload ACR and change it.
- ACR:
> [NUI] Fix wrong name

- src/Tizen.NUI/src/internal/Interop/Interop.TapGesture.cs
- src/Tizen.NUI/src/public/Events/TapGesture.cs
This is similar to MouseButton in TouchEvent.
Now, you can see from which input the tap was made.
- ACR:
> [NUI] Add source type to TapGesture.

- src/Tizen.NUI/src/internal/Interop/Interop.Rotation.cs
- src/Tizen.NUI/src/public/Common/Rotation.cs
- NUI Rotation is based on Quaternion theoretically.
- This patch adds Rotate method to rotate vector3 or vector4 with the quaternion.
> [NUI] Add Rotate API in Rotation to rotate vector

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
In the case of NUI PropertyMap, it is difficult for users to understand the name, type, and meaning of key and value.
This PR added description to all PropertyMap of Text Components and added some examples.
> [NUI] Add description for Text component's PropertyMap.

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
LinearLayout.CellPadding is Size2D, so it is not nullable type.
Therefore, if null is assigned to LinearLayout.CellPadding, then it
returns Size2D(0, 0).
- ACR:
> [NUI] Fix not to make LinearLayout.CellPadding nullable

- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
[NUI] Add Add GetHeightForWidth(), GetWidthForHeight()
- In https://code.sec.samsung.net/jira/browse/TCSACR-402, the GetHeightForWidth() and GetWidthForHeight() were deprecated, and the ACR had explained that those can be replaced by HeightForWidth and WidthForHeight.
- But this was wrong, HeightForWidth and WidthForHeight are related to ResizePolicy to determine width and heigh dependency, so that those APIs which have different purpose and behavior can not be replaced.
Therefore, the deprecated methods , GetHeightForWidth() and GetWidthForHeight(), need be added again. 
https://code.sec.samsung.net/jira/browse/TCSACR-428
> [NUI] Add GetHeightForWidth(), GetWidthForHeight()

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Window/Window.cs
Fix SetAvaiableOrienation() in Window.
Previous the related functions were implemented incorrect both dali-csharp-binder and TizenFX.
They need the count of list.
This patch is for that.
> [NUI]Fix SetAvailableOrientation

- src/Tizen.NUI/src/internal/Xaml/XamlParser.cs
Previously, XamlParser referenced a xamlns list that is created based on the root assembly of previously parsed xaml file.
That leads wrong result of searching types for the next xaml parsing.
- ACR:
> [NUI] Reset XamlParser's xamlns definitions whenever it starts to parse

- src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs
- src/Tizen.NUI.Components/Controls/SelectButton.cs
- src/Tizen.NUI.Components/Controls/SelectGroup.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
* Fix default SelectGroup.SelectedIndex value to -1.
* Add event SelectGroup.SelectedChanged.
* Add method SelectGroup.AddAllToView().
* Add method RadioButtonGroup.GetSelectedItem().
* Add attached property RadioButtonGroup.IsGroupHolder. View can make a RadioButtonGroup for its radio button children.
```xaml
<View x:Name="rootView" RadioButtonGroup.IsGroupHolder="true">
<RadioButton Text="1"/>
<RadioButton Text="2"/>
</View>
```
```cs
RadioButtonGroup.GetRadioButtonGroup(rootView).SelectedChanged += (s, e) => {
// TODO
};
```
- ACR:
> [NUI] Add SelectedChanged event to the SelectGroup and etc.

- src/Tizen.NUI/src/public/XamlBinding/ColorTypeConverter.cs
In NUI Color, the color hex format is defined as #RRGGBBAA but in xaml it is #AARRGGBB.
This can cause mess confusing to user so we decided to make them same: #RRGGBBAA
- ACR:
> [NUI] Fix color format to #RRGGBBAA from #AARRGGBB

- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
This reverts a part of d5ac94d24b3ca635034b57324e527e253e2ed789 to
support simple MatchParent in RelativeLayout.
For easier use, child fills its parent if child has MatchParent without
using RelativeLayout APIs.
- ACR:
> [NUI] Fix to support simple MatchParent in RelativeLayout

- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
This reverts commit 426fc56baad122973dad5bca42073a3394e5dd6d.
Since some ResizePolicyTypes are not fully covered, ResizePolicyType is
not deprecated for now.
- ACR:
> Revert "[NUI] Deprecate ResizePolicyType"

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSApplicationControlSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSApplicationSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSComponentApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSNUIComponentCoreBackend.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSNUICoreBackend.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSNUIWidgetCoreBackend.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSWatchApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSWatchBoolSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Application/TSWatchTimeSignal.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Application/TSNUIApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Application/TSNUIComponentApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Application/TSNUIFrameComponent.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Application/TSNUIWidgetApplication.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Application/TSWatchTime.cs
1. Remove IsWearable() from  internal/WatchApplication ，WatchBoolSignal ， WatchTimeSignal  and public/WatchTime.
2. Add TCs to improve line coverage.    
ps: Some cases are commented  out because they would throw similar exceptions, such as:
Unable to find an entry point named 'CSharp_Dali_delete_WatchBoolSignal' in shared library 'libdali2-csharp-binder.so', 
Unable to find an entry point named 'CSharp_Dali_WatchTime_GetDayOfWeek' in shared library 'libdali2-csharp-binder.so'
......, and so on, 
after these issues are fixed, we can open them. 
- ACR:
> [NUI] Update Application(internal & public) TCs.

- src/Tizen.NUI/src/internal/Application/Application.cs
- src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
- src/Tizen.NUI/src/public/Window/Window.cs
1. Supports IME window and application.
It is only for internal IME window and application.
These new APIs should be not public.
2. Supports floating window mode.
3. Supports window resized/moved by display server.
> [NUI] Add new features for window

- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
[NUI] Fix issue of SetValue to the property which hasn't DefaultValue Create delegate
- ACR:
> [NUI] Fix issue of SetValue to the property which hasn't DefaultValue Create delegate

- src/Tizen.NUI.Components/Controls/DatePicker.cs
- src/Tizen.NUI.Components/Controls/Picker.cs
- src/Tizen.NUI.Components/Controls/TimePicker.cs
ViewStyle is the last applied style which is not same as the current style.
Hence it is not recommanded to use ViewStyle inside components code.
(Please note that View.ViewStyle is deprecated and better not to use.)
- ACR:
> [NUI] Fix picker not to use ViewStyle.

- src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
- src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
When we set view.BoxShadow.Color = new Color(~~);
BoxShadow.Color have same reference with noColor.
So noColor also become changed
We make another refernce when setup Color by noColor.
Now Color doesn't have same reference with noColor.
(Same jobs doing for noOffset and noExtents)
> [NUI] Fix Shadow issue when we set BoxShadow = null

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
ViewStyle is the last applied style which is not the same as the current style.
Hence it is not recommanded to use ViewStyle inside components code.
(Please note that View.ViewStyle is deprecated and better not to use.)
- ACR:
> [NUI] Fix AlertDialog not to use ViewStyle.

- src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
ViewStyle is the last applied style which is not the same as the current style.
Hence it is not recommanded to use ViewStyle inside components code.
(Please note that View.ViewStyle is deprecated and better not to use.)
- ACR:
> [NUI] Fix AppBar not to use ViewStyle.

- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- Both DALi and NUI use 'cursor' term more than 'caret'.
- The patches below should be applied together.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/260281/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/260282/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/260322/
- N/A
> [NUI][ATSPI] Change 'Caret' for binding name to 'Cursor'

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Window/Window.cs
In some case, The view needs to know which window it is added to.
we can using this api in this case.
- ACR:
> [NUI] Add Api for getting window from view

- src/Tizen.NUI/src/internal/EXaml/Operation/CreateInstance.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/SetBindalbeProperty.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/SetProperty.cs
- src/Tizen.NUI/src/public/Widget/WidgetView.cs
- src/Tizen.NUI/src/public/Xaml/MarkupExtensions/ResourcePathExtension.cs
Fix JIRA: https://code.sec.samsung.net/jira/browse/GRE-2334
now user can set the relative path to Url in Xaml
sample:
`<ImageView x:Name="imageView" ResourceUrl="{ResourcePath FilePath=images/a.jpg}" />`
when the xaml is loaded, the path "Tizen.Applications.Application.Current.DirectoryInfo.Resource + "images/a.jpg"" will be set to the ResourceUrl.
- ACR:
> [NUI][EXaml] Support ResourcePath in Xaml

- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
Previously, the actual spec size is given to MeasureChild() and MeasureChild()
subtracts Padding size from the actual spec size.
Now, the actual spec size with Padding size is given to MeasureChild() to
display child with the actual spec size.
Moreover, since child's MeasuredWidth/Height are calculated in MeasureChild(),
duplicate MeasureWidth/Height assigning codes are removed.
- ACR:
> [NUI] Fix RelativeLayout Measure size calculation

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CaptureTest.cs
CaptureTest need to use ImageUrl
So i apply it
- ACR:
> [NUI] Apply ImageUrl in CaptureTest

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
Default Navigator Animation is changed not to show the background behind the
pages.
During Push(), alpha animation is not applied to the current page.
During Pop(), alpha animation is not applied to the previous page.
- ACR:
> [NUI] Change default Navigator Animation

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
This API sets/unsets the tts focus to the webview.
- ACR:
> [NUI] Add WebView.SetTtsFocus(bool) method

- src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
Since LinearLayout's size calculation logic has been fixed, AppBar Content's
Layout properties are fixed to calculate size correctly.
After fixing LinearLayout's size calculation logic, Weight is valid only if
Width/HeightSpecification is MatchParent.
AppBarStyle's ActionView and ActionButton's default size is fixed to show its
own size.
- ACR:
> [NUI] Fix AppBar Content's Layout properties

- src/Tizen.NUI.Components/Controls/Menu.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
Menu covers the window size to dismiss Menu when outside of Menu is touched.
Therefore, Menu's BackgroundColor should be transparent and Menu Content's
BackgroundColor should be set instead.
- ACR:
> [NUI] Fix Menu's BackgroundColor

- src/Tizen.NUI.Components/Controls/Slider.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SliderSample.cs
- Override OnKey() method and make Slider itself handle KeyEvent.
- Now, Slider Thumb can be moved using "Left" and "Right" key.
- N/A
> [NUI] Enable Slider value to be updated using both touch and key event

- src/Tizen.NUI/src/internal/EXaml/Action/AddExistInstanceAction.cs
- src/Tizen.NUI/src/internal/EXaml/Action/CreateInstanceAction.cs
- src/Tizen.NUI/src/internal/EXaml/Action/GetObjectByPropertyAction.cs
- src/Tizen.NUI/src/internal/EXaml/Action/GetValueAction.cs
- src/Tizen.NUI/src/internal/EXaml/Action/OtherActions.cs
- src/Tizen.NUI/src/internal/EXaml/GlobalDataList.cs
- src/Tizen.NUI/src/internal/EXaml/LoadEXaml.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/AddEvent.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/AddToCollectionProperty.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/CreateInstance.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GatherBindableProperties.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GatherStaticInstance.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/RemoveEvent.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/SetBindalbeProperty.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/SetProperty.cs
- src/Tizen.NUI/src/public/EXaml/EXamlExtensions.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
- src/Tizen.NUI/src/public/XamlBinding/Binding.cs
To fix https://code.sec.samsung.net/jira/browse/GRE-2306.
Provide method so that user can dispose all xaml object.
After this is released, the patch https://github.com/nui-dali/Tizen.NUI.XamlBuild/pull/27 could be merged.
Sample:
C#
```
public partial class CustomExtension
{
public CustomExtension()
{
InitializeComponent();
}
protected override void Dispose(bool disposing)
{
ExitXaml(); //This is generated by XamlBuild.
base.Dispose(disposing);
}
}
```
- ACR:
> [NUI][Xaml] Provide method so that user can dispose all xaml objects

- src/Tizen.NUI/src/internal/Layouting/RelativeLayout.cs
- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
Previously, TextLabel and TextField's Ellipsis were not displayed in
RelativeLayout, because TextLabel and TextField's size always covers the full
text string.
Now, if TextLabel and TextField support Ellipsis, then RelativeLayout sets the
exact space size to the TextLabel and TextField. So if the assigned size does
not cover the full text string, then Ellipsis is displayed.
Previously, redundant Meausre() was called again in OnMeasure().
Now, Measure() is called again only for FillHorizontal/Vertical cases to set the
filled size to the MeasuredWidth/Height to calculate grand children's size
correctly.
- ACR:
> [NUI] Fix to measure RelativeLayout's children sizes correctly

- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
To refer the parent layout's area by default, RightRelativeOffset and
BottomRelativeOffset are changed from 0.0f to 1.0f.
- ACR:
> [NUI] Change RelativeLayout's default offset values

- test/NUITizenGallery/NUITizenGallery.csproj
- test/NUITizenGallery/README.md
[NUI] Fix the build error when referencing to NUI.XamlBuild of which version is higher than 1.0.11
none
> [NUI] Fix the build error when referencing to NUI.XamlBuild of which version is higher than 1.0.11

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
> [NUI] Fix gridlayouter find wrong visible item

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/NavigatorSample.cs
Popped event is added to Navigator.
Popped event passes Page handle popped by Navigator.
By using Popped event, for example, user can dispose the popped page.
- ACR:
> [NUI] Add Popped event to Navigator

- src/Tizen.NUI/src/internal/Common/KeyboardRepeatSettingsChangedSignal.cs
- src/Tizen.NUI/src/internal/Window/WindowEffectSignal.cs
- src/Tizen.NUI/src/internal/Window/WindowVisibilityChangedEvent.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples.sln
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CaptureTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowEventsTest.cs
[NUI] Fix the Window.VisibilityChanged event's crash issue
- Because the signals which binds dali, contain signals as member variables, the cMemoryOwn should be false.
- Without this fix, the WindowEventsTest.cs gets crash when continously pushing left,right direction key.
none
> [NUI] Fix the Window.VisibilityChanged event's crash issue

- src/Tizen.Applications.Common/Interop/Interop.ApplicationManager.cs
- src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
The AttachWindowBelow() method is added for inhouse applications.
The method is to attach the window of the child application below the
window of the parent application.
Added: 
- ApplicationManager.AttachWindowBelow()
> [Tizen.ApplicationManager] Add a new internal method

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
Previously, base.Initialize() of LinearLayouter and GridLayouter was not
called if source was empty.
This caused Container to be null and caused null reference in
RequestLayout().
Now, it is guaranteed that base.Initialize() of LinearLayouter and
GridLayouter is called.
- ACR:
> [NUI] Fix to call base.Initialize() of LinearLayouter and GridLayouter

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/NavigatorSample.cs
Since PoppedEventArgs provides Page, page is replaced to Page to fix
build error.
- ACR:
> [NUI] Fix Navigator sample build error

- src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
- src/Tizen.NUI/src/public/Images/NativeImageQueue.cs
When the application uses several buffers in NativeImageQueue,
the application can get buffer directly using these APIs.
- ACR:
> [NUI] Add NativeImageQueue

- src/Tizen.NUI/src/public/Images/EncodedImageBuffer.cs
```
var imageBuffer = new EncodedImageBuffer(stream);
var imageUrl = imageBuffer.GenerateUrl(); ///< Get reference of mCachedImageUrl
imageBuffer.Dispose(); ///< ...and imageUrl disposed!
var img0 = new ImageView
{
ResourceUrl = imageUrl.ToString()
};
Add(img0);
```
There was some problems when we get cached ImageUrl's reference.
Generated ImageUrl must not have any dependency with original encoded image buffer (in app side).
and ImageUrl is only for Engine-side class. (NUI should not control this class's reference)
So I just remove cached data of ImageUrl.
It will works fine.
> [NUI] Remove cached ImageUrl at EncodedImageBuffer

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
The Placeholder map use string key to set value in NUI.
But, user must use the index key to get value.
This causes confusion and inconvenience to users.
This patch allows users to get value using string key.
> [NUI] Added string key to Placeholder PropertyMap

- src/Tizen.Applications.Common/Interop/Interop.ApplicationManager.cs
- src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
The AttachWindowBelow() method is added for inhouse applications.
The method is to attach the window of the child application below the
window of the parent application.
Adds:
- ApplicationManager.AttachWindowBelow()
- ACR:
> Rebase DevelNUI

- src/Tizen.NUI/src/internal/Interop/Interop.Drawable.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Drawable.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CanvasViewSamsple.cs
Shape and DrawableGroup, which inherit drawable class,
can clipping and masking using ClipPath and Mask methods.
- ACR:no
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/261672/
> [NUI] CanvasView: Add ClipPath and Mask feature for Drawable

- src/Tizen.NUI/src/internal/Interop/Interop.CanvasView.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
Add a method to selectively remove the added drawable or remove all.
- ACR: no
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/261935/
> [NUI] CanvasView: Add RemoveDrawable/RemoveAllDrawables method

- src/Tizen.NUI/src/internal/Interop/Interop.CanvasView.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
Add a constructor so that it can be created without viewBox argument.
- ACR:no
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/261876/
> [NUI] CanvasView: Add constructor that can be created without viewbox

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/TextEditorStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
Bind EllipsisPosition Property with DALi. 
**Patches:** 
- Support Ellipsis Position Property: https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/259560 
- [NUI] Support Ellipsis Position Property: https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/260614
Added new property Ellipsis to TextEditor
Added new property Ellipsis_Position to TextLabel, TextField and TextEditor
Handled Ellipsis location for below cases:
- Locations: END, START and MIDDLE
- TextController: TextLabel, TextField and TextEditor
- SingleLine and Muilt-lines with different LineWrap modes
- Text direction LTR and RTL
- ACR: None
**Added:**
- EllipsisPosition TextLabel.EllipsisPosition { get; set; } // Property
- EllipsisPosition TextField.EllipsisPosition { get; set; } // …
> [NUI] Support Ellipsis Position Property 

- src/Tizen.NUI/src/internal/Interop/Interop.DrawableGroup.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/DrawableGroup.cs
Since the method name of the same concept in CanvasView is used as
'RemoveAllDrawables', change it to maintain the concept.
- ACR:No
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/262039/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/262040/
> [NUI] CanvasView: Change name DrawableGroup::Clear() to RemoveAllDrawables()

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Add missing implements about borderline.
```
roundImageView = new ImageView();
roundImageView.CornerRadius = 50;
roundImageView.BackgroundColor = Color.Blue;
roundImageView.BorderlineWidth = 5;
roundImageView.ResourceUrl = IMAGE_PATH;
```
Previous version doesn't make borderline like upper samples.
Cause there was some implement missing when we setup `ResoureUrl` first time.
It is fixed now
+
Previous version don't apply borderline to it's background.
But when we use both `Background~~~` and `ResourceUrl`, 
there will occur some logical error
(`CornerRadius` calculated from outer-line of borderline. but when we don't setup `BorderlineWidth` at `Background` layer, gap occured between inner-line of borderline and `Background`.)
So now, we also apply borderline to background of `ImageView` …
> [NUI] Apply BorderlineWidth to ImageView and ImageView.Background

- src/Tizen.NUI/src/internal/Interop/Interop.CanvasView.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
Add a property that can change the viewbox value of CanvasView.
If the viewbox is smaller than the view size, the canvas will appear larger.
Conversely, if the viewbox is large, the canvas will look small.
- ACR:No
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/261995/
> [NUI] CanvasView:: Add ViewBox Property

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
The AttachWindowBelow() method has to use AppManagerAttachWindowBelow().
> [Applications] Fix wrong implementation of AttachWindowBelow method

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
[Applications] Fix wrong implementation of AttachWindowBelow method (#3384)
The AttachWindowBelow() method has to use AppManagerAttachWindowBelow().
- ACR:
> [NUI] sync from master to DevelNUI

- src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
- src/Tizen.NUI/src/public/Images/NativeImageQueue.cs
ColorDepth was changed to ColorFormat in Dali.
- ACR:
> [NUI] Change ColorDepth enum to ColorFormat

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
Select text from start to end index.
This API works in the same way as SelectWholeText().
When this is called, a SelectText event is added to the event queue.
So this can guarantee the behavior even if called before the text is rendered.
// example
textField.SelectText(2, 10);
Relative patches:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/261509/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/261951/
> [NUI] Add SelectText to TextField, TextEditor

- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
When CornerRadiusPolicy is Relative, the maximum value is 0.5f.
If value is bigger than 0.5f, it will be clamped internally.
But we cannot notificate that informations only by documents.
Now fix it.
And more, We add some more informations about borderline color;
It will be affected by view opacity
- ACR:
> [NUI] Fix comments of CornerRadiusPolicy and Borderline

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- If a View is insensitive, the children are also not hittable.
- This patch adds that at the sensitive property comment.
> [NUI] Add a comment about SENSITIVE.

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Previously, FlexLayout filled its parent even if it had WrapContent
Width/HeightSpecification.
Because FlexLayout's width and height always referred its parent's size.
(If Width/HeightSpecification is WrapContent, then Mode becomes AtMost.)
Now, FlexLayout does not fill its parent if it has WrapContent
Width/HeightSpecification.
- ACR:
> [NUI] Fix FlexLayout not to fill its parent with WrapContent

- src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
- src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs
- src/Tizen.NUI.Components/Controls/SelectGroup.cs
Add attached bindable property CheckBoxGroup.IsGroupHolder to the View.
In NUI, the parent View that holds checkboxes does not related with CheckBoxGroup.
Which means user must create CheckBoxGroup manually and then add all checkbox to the group.
```
var check1 = new CheckBox();
var check2 = new CheckBox();
var check3 = new CheckBox();
parent.Add(check1);
parent.Add(check2);
parent.Add(check3);
var group = new CheckBoxGroup();
group.Add(check1);
group.Add(check2);
group.Add(check3);
```
In this structure, user can not make a group in XAML code.
This patch introduce attached property to the View for the CheckBoxGroup:
```
<View CheckBoxGroup.IsGroupHolder="True">
<CheckBox Text="Check1"/>
<CheckBox Text="Check2"/>
<CheckBox Text="Check3"/>
</View>
```
And then the user can access check box …
> [NUI] Add attached bindable property CheckBoxGroup.IsGroupHolder

- src/Tizen.NUI/src/internal/Common/Disposable.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
It fixes `Dispose(true)` issue
Current Implementation use `DisposeQueue` to release object on main thread
When `Dispose(false)` was called on GC thread, object was added in `DisposeQueue` 
and called on main thread with `Dispose()`
`Dispose()` it call `Dispose(disposing:true)` but current state is disposing false, 
disposing false means "all managed object are invalid so do not access to your field and property that are object types"
So, if API user extend a View class and override `void Dispose(bool disposing)` and access field or property when disposing was true but actually was not, It could be cause undefined behavior
this changes fixes it
Dispose() method was changed but code analyzer make warning to use original code. so this changes increasing compiler warning .
- ACR:
> [NUI] Fix Dispose(true) issue

- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Drawable.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Gradient.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/VectorGraphicsConstants.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CanvasViewSamsple.cs
Move enums to VectorGraphicsConstants.cs to avoid nested types.
And add a warning message to FillRuleType, StrokeCapType,
and StrokeJoinType enums of the Shape class that have become ACR.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types
- ACR:no
> [NUI] VectorGraphics: Move enums out of class

- src/Tizen.NUI/src/public/Rendering/Renderer.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples.sln
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs
[NUI] fix for a owner object to maintain the reference of owned objects
- Renderer maintains the references of Geometry and Shader
- The references are automatically released when Renderer object is disposed by DisposeQueue
- Tested by test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs
none
> [NUI] fix for a owner object to maintain the reference of owned objects

- src/Tizen.NUI.Wearable/src/public/Title.cs
- src/Tizen.NUI/src/internal/Interop/Interop.PixelData.cs
- src/Tizen.NUI/src/public/Images/PixelData.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSPixelData.cs
PixelData buffer's allocate / release function is only need for C++ side memory.
And C# cannot control that allocation method.
So ReleaseFunction enum is unneccesary arguments at NUI.
relative patch : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/262756/
Changed:
- public PixelData(..., PixelFormat, ReleaseFunction) -> public PixelData(..., PixelFormat);
> [NUI] Remove ReleaseFunction enum at PixelData

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
Add CursorPositionChanged event, 
which will be called every time the cursor moves.
editor.CursorCursorPositionChanged += (s, e) =>
{
e.OldCursorPosition; //cursor position before the change
};
related patch : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/262362
> [NUI] Add CursorPositionChanged Event

- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] Make Unparent() in Dispose() be executed early
- Unparent() needs to be excuted in explicit dispose() which is also same as disposing = true.
- Also it should be called prior to before the derived class of View deletes the native handle, otherwise when doing Unparent(), the child itself has empty body (native object has been deleted already).
none
> [NUI] Make Unparent() in Dispose() be executed early

- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
There is an ambiguous reference problem,
because the newly added SelectionChangedEventArgs for Text
has the same name as the existing SelectionChangedEventArgs.
The SelectionChangedEventArgs for Text is not yet an opened API,
so temporarily renaming it to fix the issue.
> [NUI] Change SelectionChangedEventArgs to TextSelectionChangedEventArgs

- src/Tizen.Multimedia.Remoting/Interop/Interop.ScreenMirroring.cs
- src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroring.cs
- src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
Reverts Samsung/TizenFX#3453
During the integration process, the patches are squashed into one. 
Will integration again.
> Revert "Rebase master"

- src/Tizen.NUI.Wearable/src/public/Title.cs
- src/Tizen.NUI/src/internal/Interop/Interop.PixelData.cs
- src/Tizen.NUI/src/public/Images/PixelData.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSPixelData.cs
This reverts commit c2951987b9232e1fe24c8d2d98334fbb3ed03327.
- ACR: no
> Revert "Remove ReleaseFunction enum at PixelData (#3436)"

- src/Tizen.NUI/src/internal/Common/ProcessorController.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ProcessorController.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
- Follow C# Coding rule
1) reposition the type of class
2) delete unusued using state
3) follow event naming rule
- ACR:
> [NUI] Fix to follow coding rule

- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Layout Process should be registered only once.
- ACR:
> [NUI] Fix Layout Performance Issue

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
Add a Placeholder struct to pass data of DALi Placeholder PropertyMap.
The Placeholder struct can be used as an argument to
SetPlaceholder and GetPlaceholder methods.
// example
var placeholder = new Tizen.NUI.Text.Placeholder();
placeholder.Text = "placeholder text";
placeholder.TextFocused = "placeholder textFocused";
placeholder.Color = new Color("#45B39D");
placeholder.FontFamily = "BreezeSans";
placeholder.FontStyle = new Tizen.NUI.Text.FontStyle()
{
Width = FontWidthType.Expanded,
Weight = FontWeightType.ExtraLight,
Slant = FontSlantType.Italic,
};
placeholder.PointSize = 25.0f;
//placeholder.PixelSize = 50.0f;
placeholder.Ellipsis = true;
field.SetPlaceholder(placeholder);
> [NUI] Add struct Placeholder, HiddenInput to Text Components

- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
[NUI] Fix testhub NUI.Components coredump issue
- there was no fail but coredumps are remained after finishing NUI.Components test.
- native crash occured when empty native object handle is accessed and the TouchEvent signal is tried to be gotten.
- https://code.sec.samsung.net/jira/browse/TSDF-2266
none
> [NUI] Fix testhub NUI.Components coredump issue

- src/Tizen.NUI/src/internal/Utility/GaussianBlurView.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
- src/Tizen.NUI/src/public/XamlBinding/BindablePropertyConverter.cs
1. Fix SetValue to use default value not null as old value.
2. Make XamlStyle to use Setter directly.
```
<XamlStyle x:Key="baseStyle" TargetType="View">
<Setter Property="SizeWidth" Value="100" />
<Setter Property="SizeHeight" Value="10" />
</XamlStyle>
```
3. Change GaussianBlurViewProperty to BlurStrengthProperty.
- ACR:
> [NUI] Fix setvalue and xamlstyle issues

- src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Previously, if child's measured size is 0, then GridLayout does not
update the child's measured size when the child's size is set by using
GridLayout APIs.
e.g.
SetHorizontalStretch(child, GridLayout.StretchFlags.ExpandAndFill);
Moreover, if child has its own size and ExpandAndFill is set, then
child's size is set to be its own size (its measured size) plus its
expanded size.
e.g.
parent size is 100.
child1's measured size is 50 and ExpandAndFill.
child2's measured size is 0 and ExpandAndFill.
Then, child1's size is 50 + 25 = 75 and child2's size is 25.
To resolve the above, GridLayout updates child's measured size in
OnLayout() and child's size is set to be the bigger one between its
measured size and its expanded size.
- ACR:
> [NUI] Fix to measure GridLayout's children sizes correctly

- src/Tizen.NUI/src/internal/EXaml/Operation/SetProperty.cs
> [NUI] Fix svace issue of dereferencing null handle in SetProperty

- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
Since PropertyMap.Find can return null, Find().Get() should be replaced with
Find()?.Get().
- ACR:
> [NUI] Fix svace issue of dereferencing possible null handle in TextUtils

- src/Tizen.Applications.Common/Interop/Interop.Libc.cs
- src/Tizen.Applications.Common/Tizen.Applications.Common.csproj
- src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
nint is not supported by current version.
This patch Changes TimeStamp's member attribute type
to IntPtr.
- Non ACR:
> [Tizen.Applications.RPCPort] Change internal TimeStamp's type to IntPtr

- build/common.props
Set `ProduceReferenceAssemblyInOutDir` to true as default.
> [Build] Fix common.props to drop ref assemblies

- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
Currently the borderline color affected by View Opacity
But by check internally, we check it is just kind of bugs.
So during ACR, we don't tell it this is one of feature.
Bugfix will done in DALi side internally.
> [NUI] Fix comments of BorderlineColor

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
SelectedTextStart and SelectedTextEnd properties are int.
Change the parameter of SelectText() to int for cosistency.
> [NUI] Change the parameter of SelectText from uint to int

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Up to now, although the position and size of image resource of ImageView
is set by FittingMode, but there is no way to set the size of ImageView
to respect the aspect ratio of its image resource.
If AdjustViewSize is true, then ImageView respects the aspect ratio of
its image resource when it determines its size.
AdjustViewSize works only if the ImageView is added to a View having Layout.
Otherwise, use can set ImageView's size to respect the aspect ratio of its image
resource by using ResizePolicyType.DimensionDependency.
- ACR:
> [NUI] Add AdjustViewSize to ImageView

- src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
- Change ItereLayoutChildren()
- Get stored window size
- Fix SetPositionByLayout setting bug when reset the layout
Test View 1000 items (ms)
- AbsoluteLayout : 71  -> 32
- LinearLayout   : 88  -> 71
- GridLayout     : 73  -> 46
- FlexLayout     : 90  -> 56
- RelativeLayout : 103 -> 73
- ACR:
> [NUI] Layout Performance improvement

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Previously, LinearLayout calculated MatchParent children's positions
incorrectly when the LinearAlignment was Center.
Because the MatchParent children's sizes were not added to the sum of
all children's sizes.
Now, the MatchParent children's sizes are added to the sum of all
children's sizes and it leads that MatchParent children's positions are
calculated correctly when the LinearAlignment is Center.
- ACR:
> [NUI] Fix MatchParent child position with LinearLayout Center Alignment

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
- src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
Previously, LinearAlignment of LinearLayout could not support the
combination of horizontal and vertical alignments.
e.g. could not support CenterHorizontal with Bottom
Now, HorizontalAlignment and VerticalAlignment have been added to
support the combination of horizontal and vertical alignments.
To use the enum types Tizen.NUI.Horizontal/VerticalAlignment for
LinearLayout.Horizontal/VerticalAlignment, the documentation of
Tizen.NUI.Horizontal/VerticalAlignment has been updated.
- ACR:
> [NUI] Add Horizontal/VerticalAlignment to LinearLayout

- src/Tizen.NUI/src/internal/Application/Application.cs
- src/Tizen.NUI/src/internal/Common/ViewImpl.cs
- src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs
- src/Tizen.NUI/src/internal/FrameBroker/DefaultFrameBroker.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Input/FocusManager.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
> [NUI] Remove redundant DALi object reference check code

- src/Tizen.NUI/src/internal/Interop/Interop.StyleManager.cs
- src/Tizen.NUI/src/public/Common/StyleManager.cs
- src/Tizen.NUI/src/public/Theme/Theme.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
Add brokenImageUrl for setting broken image
users can use three Types BrokenImage from ThemeManger
the broken images are automatically changed internally considering the size of broken image and view.
- ACR:
> [NUI] Add brokenImageUrl

- src/Tizen.NUI/src/internal/images/ImageLoading.cs
Some applications call this function outside the main thread and this is a problem.
so i delete it temporary
- ACR:
> [NUI] Delete dispose() in GetOriginalImageSize

- src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples.sln
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeWithoutEventUnsubscribedTest.cs
- Add Exception when NUI instance's method or property is used after object itself has been disposed already. (requested by GBM)
- All NUI object will throw an ObjectDisposedException when it is tried to be used after disposed.
- BaseHandle's internal SwigCPtr has setter and getter, but setter seems to be dangerous so it is changed to be getter only. (requested by GBM)
- SwigCPtr becomes only getter, so DisconnectFromSignals() has been changed accordingly.
none
> [NUI] Clean up DisconnectFromSignals(). and Add Exception when NUI object is used after disposed

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/ItemsLayouter.cs
> [NUI] fix Item measure specification to be largable as much as they need

- src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObjectExtensions.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
- src/Tizen.NUI/src/public/XamlBinding/Binding.cs
This reverts commit 57b9a87490bfd7fccdc92370ef0dee8834c5e4c4.
1. Remove obsolete apis of XAML.
- ACR:
> Revert "[NUI] Roll back to fix build error of TCT code"

- src/Tizen.Applications.Common/Interop/Interop.Libc.cs
- src/Tizen.Applications.Common/Interop/Interop.RPCPort.cs
- src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
- src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Port.cs
Adds:
class:
- Tizen.Applications.RPCPort.Parcel.Header
Operation:
- Tizen.Applications.RPCPort.Disconnect()
- Tizen.Applications.RPCPort.Parcel.GetHeader()
- Tizen.Applications.RPCPort.Parcel.Header.SetTag()
- Tizen.Applications.RPCPort.Parcel.Header.GetTag()
- Tizen.Applications.RPCPort.Parcel.Header.SetSeqNum()
- Tizen.Applications.RPCPort.Parcel.Header.GetSeqNum()
- Tizen.Applications.RPCPort.Parcel.Header.GetTimeStamp()
Add internal APIs
- Non ACR
> [Tizen.Applications.RPCPort] Add RPCPort ParcelHeader internal APIs

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Previously, if ScrollableBase size changed, Scrollbar was not updated.
So some children was not displayed when ScrollableBase size changed.
Now, when ScrollableBase size changes, Scrollbar is updated in the
ScrollableBase's Relayout callback.
So all children are displayed correctly when ScrollableBase size changes.
- ACR:
> [NUI] Fix to update Scrollbar when ScrollableBase size changes

- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
> [NUI] Avoid creating BindablePropertyContext for the special cases

- src/Tizen.NUI/Tizen.NUI.csproj
- src/Tizen.NUI/src/internal/Common/DaliEnumConstants.cs
- src/Tizen.NUI/src/internal/Common/Registry.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
- Fix View.DisConnectFromSignals() to return when the native object has no body
- Add debugging log which comes only when the NUI_DEBUG_ON is defined
none
> [NUI] Fix View.DisConnectFromSignals() to return when the native object has no body

- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
after optimizing layout in this pull request : https://github.com/Samsung/TizenFX/pull/2841
a crash started to appear when entering double enter in TextEditor while its TextChanged event set text to a TextLabel, and these controls are inside parent with layout (example View with LinearLayout).
the crash happens because an extra calls to OnMeasure (compared to before the above optimization pull request), which seems to call GetNaturalSize which is not stable, and in this case it cause a crash.
these extra calls happens because we have moved the condition that check if layout is needed to the LayoutController, and the Measure function in LayoutItem does not check if layout is needed anymore.
so If Measure function of LayoutItem is called from anywhere other than the LayoutController (in …
> [NUI] fix crash with double enter in TextEditor with TextLabel

- src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
Previously, Padding and Margin was not applied in AbsoluteLayout.
So AbsoluteLayout's Padding and its children's Margin did not work.
Now, Padding and Margin are applied by AbsoluteLayout.
So AbsoluteLayout's children are positioned based on AbsoluteLayout's
Padding and children's Margin.
- ACR:
> [NUI] Apply Padding and Margin in AbsoluteLayout

- src/Tizen.Applications.Common/Interop/Interop.BaseUtilsi18n.cs
- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
The system locale of Tizen uses POSIX locale.
Currently, there is a problem when the system language is "uz_UZ@cryillic".  The CultureInfo is created that is 'uz-UZ-CYRILLIC'.  In this case, the CultureInfo should be created by "uz-Cyrl-UZ" locale.
For .NET applications, we should set CurrentCultureInfo and CurrentUICultureInfo properly.
After this patch is applied, we uses LCID instread of loclae of ULocale class to create CultureInfo.
> [Applications] Set CultureInfo using LCID instread of locale

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
This fixes a bug about getting fallback CultureInfo. 
While getting the fallback CultureInfo with Language, the CultureInfo existence was not checked.
This patch uses GetCultureInfo() with locale variables.
> [Applications] Fix Getting Fallback CultureInfo

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
If the CultureInfo is null when setting CurrentUICultureInfo, it throws ArgumentNullException.
The value of set_CurrentUICultureInfo(CultureInfo value) cannot be null.
This patch adds exception handlings for setting CultureInfo.
log.cpp: stdErrRedirect(98) > System.ArgumentNullException: Value cannot be null. (Parameter 'value')
at System.Globalization.CultureInfo.set_CurrentUICulture(CultureInfo value)
at Tizen.Applications.CoreApplication.OnCreate() in /home/abuild/rpmbuild/BUILD/csapi-tizenfx-9.0.0.16756+nui22045/src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs:line 146
at Tizen.NUI.NUIApplication.OnCreate() in /home/abuild/rpmbuild/BUILD/csapi-tizenfx-9.0.0.16756+nui22045/src/Tizen.NUI/src/public/Application/NUIApplica …
> [Applications.Common] Add exception handlings for setting CultureInfo

- src/Tizen.NUI/src/public/Widget/WidgetView.cs
when WidgetView is disposed, RemoveWidget must be called.
so i added this patch
- ACR:
> [NUI] Call RemoveWidget when WidgetView is disposed

- src/Tizen.NUI/src/internal/Interop/Interop.ImageView.cs
> [NUI] Make use some ImageView interop method again

- src/Tizen.NUI/src/public/Common/NUIConstants.cs
Update LineWrapMode enum description based on comments from ACR.
https://github.com/Samsung/TizenFX/pull/3490#pullrequestreview-796077471
> [NUI] Use present tense for LineWrapMode enum description

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Previously, ChangeLayoutSiblingOrder was provided by LayoutGroup.
So, any layout class inherited from LayoutItem could not use it.
Now, ChangeLayoutSiblingOrder is moved from LayoutGroup to LayoutItem.
So, all layout classes inherited from LayoutItem can use it.
This PR has been made to resolve the following issue.
https://github.sec.samsung.net/dotnet/NUIBackend/issues/87
- ACR:
> [NUI] Move ChangeLayoutSiblingOrder from LayoutGroup to LayoutItem

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
null value is abnormal in collectionview,
but adding null value check for code management.
- ACR:
> [NUI] add null check in collectionview

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
View's Weight is considered in LinearLayout's calculation only if the
View's Specification is MatchParent.
Because Weight is used to divide the parent's space to each child.
Previously, WrapContent View's Weight was also added to the sum of
Weights.
This caused the weighted View's size was calculated incorrectly.
Now, only MatchParent View's Weight is added to the sum of Weights.
As a result, the weighted View's size is calculated correctly.
When a View's Specification was WrapContent, the View's LinearLayout did
not consider its child size correctly.
This caused that the View's Size became 0 incorrectly.
To resolve the above, LinearLayout always considers its child size and
the LinearLayout uses its child size when it calculates its own size.
- ACR:
> [NUI] Fix Weight and size calculation in LinearLayout

- src/Tizen.NUI/src/public/Window/WindowEvent.cs
when signal is disconnected, signal pointer need to be null.
so i added this patch
- ACR:
> [NUI] make a null pointer when signal is disconnected

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
> [NUI] Fix wrong prev size assigning on scroll relayout.

- src/Tizen.NUI/src/public/Window/WindowEvent.cs
i create this patch to fix the crash issue.
it will be avoid the crash issue.
- ACR:
> [NUI] Fix crash issue when signal is disposed

- src/Tizen.NUI/src/internal/Common/KeyInputFocusSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.KeyInputFocusManager.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] Check if event handler of the DisposeQueued object is valid
- The objects that are waiting in disposeQueue are not yet signal disconnected, and their states are implict disposed.
- When dali callback comes and the obeject is in the queue, it seems that the problem will occur.
- User event callback checks IsDisposeQueued before Invoked, and if Dispose == False, IsDisposeQueued == true, then event callback is not invoked.
- when Dispose == True, User callback != NULL, throw exception.
none
> [NUI] Check if event handler of the DisposeQueued object is valid

- src/Tizen.NUI/src/internal/Common/KeyInputFocusSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.KeyInputFocusManager.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] Check if event handler of the DisposedQueued object is valid
- The objects that are waiting in disposeQueue are not yet signal disconnected, and their states are implict disposed.
- When dali callback comes and the obeject is in the queue, it seems that the problem will occur.
- User event callback checks IsDisposeQueued before Invoked, and if Dispose == False, IsDisposeQueued == true, then event callback is not invoked.
- when Dispose == True, User callback != NULL, throw exception.
none
> [NUI] Check if event handler of the DisposedQueued object is valid

- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
- src/Tizen.NUI/src/public/Animation/TransitionOptions.cs
- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
1. CS0414 : The field 'tag' is assigned but its value is never used
- Accessibility.cs and AnimatedVectorImageView.cs
2. CS1574 : XML comment has cref attribute 'TransitionOptions' that could not be resolved
- TransitionOptions.cs
3. CS0419 : Ambiguous reference in cref attribute: 'SetImage'
- ImageView.cs
- N/A
> [NUI] Remove build warning messages

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSAlertDialog.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSDialog.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSSwitch.cs
We do not have to same job calculating states.
This patch sets make the View use DALi states.
If there is NUI specific state, then it will be overwritten.
This depends on following change.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/266577/
- ACR:
> [NUI][ATSPI] Calculate states based on DALi

- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSDialog.cs
we do not use variable name starts with "_".
- ACR:
> [NUI][ATSPI] clean code

- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Previously, View.BackgroundImage is set, PropertyValue constructor can
be called with null pointer and this causes crash.
Now, it has been fixed not to pass null pointer to PropertyValue
constructor.
- ACR:
> [NUI] Fix crash when View.BackgroundImage is set

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
The 1st generation child ContentContainer is always showing. So
it was not able to show highlighted descendant by AccessibilityScrollToChild.
The child is a descendant of CollectionView from following patch.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/266414/
With this patch set, It is possible to show highlighted descendant.
- ACR:
> [NUI][ATSPI] CollectionView - Show highlighed descendant

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
When new page appears, we need to inform it to the screen-reader to read
its name as a default label.
And we need to inform the currently highlighted component's state on the
disappeared page. If the currently highlighted component is not visible
then it will be cleared by screen-reader.
- ACR:
> [NUI][ATSPI] Navigator - emit accessibility event

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-461
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- string SelectedText {get;}
- int SelectedTextStart {get;}
- int SelectedTextEnd {get;}
- void SelectWholeText()
- void SelectText(int start, int end)
- void SelectNone()
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- string SelectedText {get;}
- int SelectedTextStart {get;}
- int SelectedTextEnd {get;}
- void SelectWholeText()
- void SelectText(int start, int end)
- void SelectNone()
> [NUI] Make Text selection APIs public

- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/Window/WindowEvent.cs
When signal disconnected and signal become empty, let callback as null.
- ACR:
> [NUI][API9] Set null if callback removed

- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/Window/WindowEvent.cs
When signal disconnected and signal become empty, let callback as null.
- ACR:
> [NUI] Set null if callback removed

- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
Previously, ContentPage's Layout was AbsoluteLayout so the height of
Content was calculated to the same with the height of ContentPage,
although AppBar existed at the top of ContentPage.
Now, ContentPageLayout has been introduced and ContentPageLayout
calculates the height of Content except the height of AppBar.
Consequently, OnRelayout() is no longer required because
ContentPageLayout calculates the size and position of Content.
- ACR:
> [NUI] Add ContentPageLayout to calculate Content size correctly

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
From this patch, it is able to set highlight to the DefaultLinearItem.
- ACR:
> [NUI][ATSPI] set RecyclerViewItem role 

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
(1) "LabelledBy" relation makes DefaultLinearItem use its TextLabel
as accessibility name.
(2) when user does 1 finger single tap on the TextLabel, then the
DefaultLinearItem will have highlighted by "ControlledBy" relation.
This changed could be set on application side.
- ACR:
> [NUI][ATSPI] Make DefaultLinearItem use its TextLabel

- src/Tizen.NUI/src/public/Common/Container.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
- src/Tizen.NUI/src/public/XamlBinding/Internals/NameScope.cs
To support Beholder, add the API so that Beholder can copy new View to old View without dispose the elements which has xName.
- ACR:
> [NUI] Add API so that user can copy properties, bindings from other container

- src/Tizen.NUI/src/public/Common/Size2D.cs
Since Size2D converts Width/Height from float to int internally,
Width/Height values may be greater than int.MaxValue or less than
int.MinValue.
To resolve the above issue, Width/Height values are checked if they
are greater than int.MaxValue or less than int.MinValue.
- ACR:
> [NUI] Fix Size2D not greater than int.MaxValue or less than int.MinValue

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSViewAccessibility.cs
Replaces existing API RegisterPopup()/RemovePopup() by RegisterDefaultLabel()/UnregisterDefaultLabel()
The "Default label" is a text that could be read by screen-reader immediately after
the navigation context has changed (window activates, popup shows up, tab changes)
and before first UI element is highlighted.
New API names better describe the wider applicability of this feature, which is not only for popup.
- ACR: None
Changed:
- void RegisterPopup() => void RegisterDefaultLabel()
- void RemovePopup() => void UnregisterDefaultLabel()
Related changes in DALi:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/267321/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/267323/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/ …
> [NUI][ATSPI] Fix for DefaultLabel

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Interop/Interop.FocusManager.cs
- src/Tizen.NUI/src/public/Input/FocusManager.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/NestedScrollViewSamle.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableFocusSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableFocusSample2.cs
[NUI] Improves GetNextFocusableView
Currently, GetNextFocusableView of FocusableBase was Index-based of ContentContainer Child.
This is a problem.
Changes the search for the next focus view from index-based to position-based.
> [NUI] Improves GetNextFocusableView

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextMapHelper.cs
Property of InputFilter and Placeholder returns PropertyMap of index base.
So GetHiddenInputStruct() and GetPlaceholderStruct() can parse the index base map.
> [NUI] fix tc fail for TextMapHelper

- src/Tizen.NUI.Components/Controls/Menu.cs
- src/Tizen.NUI.Components/Controls/MenuItem.cs
Added AT-SPI2 support to Menu control.
Now in A11y mode the UI context is rebuilt and proper navigation provided.
- ACR: none
> [NUI][AT_SPI] Added Accessibility support to Menu control

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Pagination.cs
- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Controls/SelectButton.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
These events are triggered whenever the value of `Accessibility.IsEnabled` is about to change. In particular, and by design, no event is delivered on application startup or shutdown. Users are encouraged to continue using `IsEnabled` to synchronously query the current accessibility state, and listen to these two events to detect and dynamically react to any later changes of this state if required.
Dependencies:
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/266049/ (merged)
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/266314/ (merged)
- ACR: None
> [NUI][AT-SPI] Enabled and Disabled events for Accessibility

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Menu.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEnum.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSViewAccessibility.cs
The different semantics of the second (`bool`) parameter of `EmitAccessibilityStatesChangedEvent` and `NotifyAccessibilityStatesChange` can cause confusion, since it represents the new value of the state in the former method, and the notification strategy in the latter.
- ACR: None
> [NUI][AT-SPI] Add AccessibilityStatesNotifyMode

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Due to the DALi's visual policy, we always create new visual
when some properties sensitive with visual's data.
Here, We make visual can change CornerRadius / Borderline
without destroy/create new visual.
- ACR:
> [NUI] Use ActionUpdateProperty for CornerRadius and Borderline

- src/Tizen.NUI/src/internal/Common/ProcessorController.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ProcessorController.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
Current Implementation create/destroy visual whenever properties changed.
This patch hold visual-sensitive properties and
create/destroy visual before next EventProcess called.
This patch required this dali code : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/268723/
Also, this patch required this NUI code : https://github.com/Samsung/TizenFX/pull/3827
> [NUI] Update ImageView properties lazy

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- There were too many dispose warnings in the legacy code.
- Fix warnings to avoid wasting memory.
- Changed some variables to meaningful names
CA2000 :
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2000
> [NUI] fix warning for text components

- src/Tizen.NUI/src/public/BaseComponents/View.cs
Currently, View.cs 's BackgroundImageLoadingSynchronously use string key, instead of index key.
But all other properties about visuals use index key only.
(Instead of animatable properties)
This patch just sync up with standard frame
This patch required to merge this dali code : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/268756/
> [NUI] Make SynchronousLoading use index key

- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
1. Add Xaml line info for bindable object.
- ACR:
> [NUI] Add Xaml line info for bindable object

- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
[NUI] Fix the defect that CurrentFrame is not updated properly when AnimatedVectorImageView stops
- this is additional fix for DF211211-00439.
- checking the EndAction of Stop() and set innerCurrentFrame and base.CurrentFrame properly.
- test sample : https://github.com/nui-dali/NUITizenGallery/pull/51
none
> [NUI] Fix the defect that CurrentFrame is not updated properly when AnimatedVectorImageView stops

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
The ScrollToChild is working for that the scrollable brings its child in
the view port to make the child show.
The ScrollableBase also needs to show its child if the child gets the
accessibility highlight.
So this patch is overriding the AccessibilityScrollToChild.
> [NUI][ATSPI] Make ScrollableBase work for ScrollToChild

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Previous code unregist visual when ResourceUrl use empty URL string.
After #3829, this action was changed.
So I fix this bug
This patch required below dali codes:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/269231/
> [NUI] Fix bug when ResourceUrl is empty string

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextMapHelper.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextEditor.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextField.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextLabel.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextMapHelper.cs
Add Strikethrough Set/Get methods to NUI
Strikethrough is a typographical presentation of words with a horizontal line through their center
The strikethrough map contains the following keys:
- enable (bool): Whether the strikethrough is enabled (the default value is false)
- color (Color): The color of the strikethrough (If not provided then the color of the text is used)
- height (float): The height in pixels of the strikethrough (the default value is 1.f)
**Added**: 
- public void SetStrikethrough(Strikethrough strikethrough) // Method to TextLabel, TextEditor & TextField
- public Strikethrough GetStrikethrough() // Method to TextLabel, TextEditor & TextField
**Related patches on DALi**:
- Add Strikethrough Property : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binde …
> [NUI] Add Strikethrough Set/Get methods 

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TextEditorLayoutTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TextFieldLayoutTest.cs
In DALi, the default HeightResizePolicy of TextField and TextEditor is
FillToParent.
Because of this, TextField and TextEditor fill their parent's height by
default although text is null string.
If TextField and TextEditor's parent has Layout, then their sizes should
be calculated based on their Width/HeightSpecification.
To calculate TextField and TextEditor's size based on their
Width/HeightSpecification, TextFieldLayout and TextEditor are added.
- ACR:
> [NUI] Add TextFieldLayout and TextEditorLayout

- src/Tizen.NUI/src/internal/Interop/Interop.GLWindow.cs
- src/Tizen.NUI/src/public/Window/GLWindow.cs
It copied the naming style from GLView.
It depends on 
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/268653
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/268654
> [NUI] Modify GLWindow's method names

- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Common/Layer.cs
- src/Tizen.NUI/src/public/Window/Window.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/MultiWindowLayoutSample.cs
Previously, Layouts in the default Window were supported.
Now, Layouts in all Windows are supported.
To enable Multi-Window, Window.IsSupportedMultiWindow() should be true
and the following code should not be executed.
Information.TryGetValue("http://tizen.org/feature/opengles.surfaceless_context", out isSupported);
- ACR:
> [NUI] Support Layout for Multi-Window

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
This change fixes a bug where it was impossible to activate a `RecyclerViewItem` in Accessibility mode.
Because the implementation of `RecyclerViewItem.OnAccessibilityActivated` would look identical to `Button.OnAccessibilityActivated`, to avoid code duplication, accessibility activation is reimplemented in terms of `OnKeyboardEnter` for all controls, just like it is done in DALi.
- ACR: None
> [NUI][AT-SPI] Fix accessibility activation for RecyclerViewItem

- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
When Lazy is used, if an exception occurs when a singleton object (ConnectionInternalManager) is created, the exception is cached and thrown continuously.
> [Connection] Do not use Lazy for Singleton

- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
This interop was unused. The `GetBoundAccessibilityObject` API duplicates `Accessible::Get` in DALi, but both functions would be equally useless in NUI, because NUI does not have the concept of `Accessible` objects, so there is no point in obtaining an `IntPtr` to such an object.
Related patches which remove `GetBoundAccessibilityObject` from DALi:
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/269912/
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/269910/
- ACR: None
> [NUI][AT-SPI] Remove unused interop for GetBoundAccessibilityObject

- src/Tizen.NUI.Components/Controls/DatePicker.cs
- src/Tizen.NUI.Components/Controls/TimePicker.cs
[NUI] Use CurrentCulture to prevent exception
A crash is occurring because the Date, Time picker are requesting a date format with the wrong formatted string from LC_TIME.
To fix it to use "CurrentCulture" according to .NET guide.
No changes
> [NUI] Use CurrentCulture to prevent exception

- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
Previously, View proceeded Remove() after printing error log although
the given argument was not a child of the view.
Now, View returns Remove() after printing error log if the given
argument is not a child of the view.
- ACR:
> [NUI] Fix View not to proceed Remove() if argument is not child

- src/Tizen.NUI/src/public/Common/Layer.cs
View have some safe-guard when we try to child.Unparent() && Remove(child) dual times.
(child will have null parent after one of them.)
But Layer.Remove didn't have any defence code about that situation.
Tizen.NUI.Components.Menu.Dispose call layer.Remove(this) in Dispose function.
But before Dispose function call, we already called Unparented function somewhere.
This patch will guard that case,
and also guard some null & reference issue.
> [NUI] Fix duplicated unparent issue at Layer

- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Fixed issues detected by static analyzer.
Add missing lock condition before accessing to the _callback_map variable
Same as https://github.com/Samsung/TizenFX/pull/3882
> [WiFi] Add missing lock condition

- src/Tizen.NUI/src/public/Common/Color.cs
- I want to know if there is a reason why the == operator overloading is not in the Color class.
- I found that GetHashCode() of Color class always returns hashDummy .
I wonder if there is a reason.
This makes the hash of all Color objects the same.
```
private readonly bool hashDummy; 
...
public override int GetHashCode()
{
return hashDummy.GetHashCode();
}
```
> [NUI] Overloading == operator in Color class and fix GetHashCode

- src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
When we try to get cached property map for animated image,
It will not return internal-updated values
something like "CurrentFrame" for animated image.
This patch make we return Current PropertyMap always
instead of cached property map.
Actually, the best way to fix is, create some flags when we
try to get time-sensitive values.
But it need to fixup some codes and test. So just make hot-fix.
- ACR:
> [NUI] Get native image PropertyMap instead of cached.

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
Focus movement follows the GetNextFocusableView() method of ScrollableBase
refer : https://github.com/Samsung/TizenFX/pull/3814
> [NUI] Focus movement follows the GetNextFocusableView() method of ScrollableBase

- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
This should eliminate error messages similar to this one:
```
E/NUI     ( 1540): BaseHandle.cs: Dispose(580) > [ERR] reference count is over than 2. Could be a memory leak. Need to check! 
E/NUI     ( 1540):  process:1540 thread:1, isDisposed:False, isDisposeQueued:False, me:Tizen.NUI.BaseComponents.View 
E/NUI     ( 1540):  disposeType:Explicit, name:, daliID:11, hash:61494432, refCnt:6
```
Previous code had two major issues:
1. It created a new `View` instance for the same `Dali::Actor`, so really `operator==` was the only method that worked correctly for it.
2. `Actor` handles created in dali-csharp-binder were not freed (unless the `using` idiom was used). `GetInstanceSafely<T>` takes care of that.
- ACR: None
> [NUI][AT-SPI] Fix memory management issues

- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
The HIGHLIHGTED state is calculated on parent class ControlAccessible
The get of IsHighlighted is doing exactly same calculation.
- ACR:
> [NUI][ATSPI] remove duplicated calculation for states

- src/Tizen.NUI.Components/Controls/DatePicker.cs
Previously, DatePicker don't consider last day of month when month change.
It makes crash issue when create DateTime.
No API Changes
> [NUI] Support last day of month when month change in DatePicker

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
Check if groupInfo is null. It can be null when count = 0.
> [NUI] Fix svace issue of RecyclerView LinearLayouter

- src/Tizen.NUI/src/public/Window/Window.cs
To support multi-window, creating a new Window calls
Window.IsSupportedMultiWindow().
Since libcapi-system-info.so.0 is not installed by default on desktop
environment, calling Window.IsSupportedMultiWindow() causes crash by
DllNotFoundException.
Not to cause crash by calling Window.IsSupportedMultiWindow() on
desktop, DllNotFoundException is caught.
- ACR:
> [NUI] Catch DllNotFoundException in IsSupportedMultiWindow() for desktop

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextEditor.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextField.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextLabel.cs
Add CharacterSpacing property to NUI
The spaces between characters.
A positive value will make the characters far apart (expanded) and a negative value will bring them closer (condensed).
Added:
- public float CharacterSpacing { get; set; } // Property to  TextLabel, TextEditor & TextField
Related patches on DALi:
- NUI] Add CharacterSpacing Property : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/262388
- Adding Character Spacing : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/260890
> [NUI] Add CharacterSpacing property 

- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Fixed issues detected by static analyzer.
Add missing lock condition before accessing to the _callback_map variable
> [WiFi] Add missing lock condition (2)

- src/Tizen.NUI/src/internal/Common/ProcessorController.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ProcessorController.cs
Allow to call ProcessorOnceEvent after all relayout events finished.
This patch must merged after below dali patch
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/270339/
> [NUI] Call ProcessorOnceEvent after all event finished

- src/Tizen.NUI/src/internal/Interop/Interop.WebHttpRequestInterceptor.cs
- src/Tizen.NUI/src/internal/WebView/WebHttpRequestInterceptor.cs
- test/Tizen.NUI.WebViewTest/SimpleWebViewApp.cs
The patch related in dali csharp binder side is
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/269640/
This patch is to add some APIs for setting response body in binary format when
http request is intercepted.
- ACR:
> [NUI]Set response body in binary format when intercepting http request.

- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Previously, RequestLayout() was not supported if it was called while
main loop was in idle state.
Now, RequestLayout() calls Awake() to awake main loop again and Layout
can be re-calculated correctly.
- ACR:
> [NUI] Support RequestLayout() while main loop is in idle state

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FlexLayoutTest.cs
Previously, if FlexLayout had Padding, then child's and grand child's sizes
were calculated incorrectly.
Because in FlexLayout's OnLayout(), child's size was given with applying
Padding. But Padding was applied in FlexLayout's OnLayout() again.
As a result, child's size became smaller by Padding size than it had to be.
Now, if FlexLayout has Padding, then child's and grand child's sizes are
calculated correctly.
The Padding is not applied duplicately while child's size is calculated.
- ACR:
> [NUI] Fix FlexLayout size calculation with Padding

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Menu.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/SelectButton.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEnum.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSViewAccessibility.cs
This PR:
1. Restores the division into `enum AccessibilityState` (enumeration of possible states) and `class AccessibilityStates` (a collection of states), which was wrongly removed. DALi makes the same distinction between `Accessibility::State` and `Accessibility::States`.
2. Restores the AT-SPI standard-compliant values for  `AccessibilityState` enumeration (the same values as in the `at-spi2-core` library and in DALi `accessibility.h`).
3. Adds a convenient indexing syntax (e.g. `states[AccessibilityState.Modal] = true`) for manipulating the states collection without having to perform bitwise operations like `&` and `|` (because using a high level toolkit like `NUI` should not require performing bit operations) or using the cumbersome and roundabout way via `FlagSetter` (e.g. …
> [NUI][AT-SPI] Clean up APIs related to AccessibilityStates

- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Fixed issues detected by static analyzer.
Add missing lock condition before accessing to the _callback_map variable
> [WiFi] Add missing lock condition (3)

- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TouchGestureSample.cs
Previously, Rotary Event(CustomWheel type) could always be received only on window.
So, If WheelEvent is registered in View, Rotary Event is first received from window and delivered to all Views that registered WheelEvent.
Now, We removed the part that the window receives and passes it to the View, and changed it so that the focused View can receive the event.
So, User can receive Rotary Event in focused View as well.
It is also possible to propagate events to the parent view.
If there is no focused View, the window will receive the event.
This only applies to Rotary Event(CustomWheel type).
- ACR:
> [NUI] Rotary Event (Custom Wheel Type) improvement

- src/Tizen.NUI/src/internal/EXaml/Operation/GatherProperty.cs
1. Fix GetProperty ambiguousmatch exception
- ACR:
> [NUI] Fix GetProperty ambiguousmatch exception

- src/Tizen.NUI/src/internal/Application/Application.cs
- src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
- src/Tizen.NUI/src/internal/Xaml/FillResourceDictionariesVisitor.cs
- src/Tizen.NUI/src/internal/Xaml/IResourcesLoader.cs
- src/Tizen.NUI/src/internal/Xaml/ResourcesLoader.cs
- src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
- src/Tizen.NUI/src/internal/XamlBinding/Internals/ResourceLoader.cs
- src/Tizen.NUI/src/internal/XamlBinding/MergedStyle.cs
- src/Tizen.NUI/src/internal/XamlBinding/ResourcesExtensions.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
- src/Tizen.NUI/src/public/Common/Container.cs
- src/Tizen.NUI/src/public/Common/Layer.cs
- src/Tizen.NUI/src/public/Xaml/XamlFilePathAttribute.cs
- src/Tizen.NUI/src/public/Xaml/XamlParseException.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
- src/Tizen.NUI/src/public/XamlBinding/Element.cs
- src/Tizen.NUI/src/public/XamlBinding/IValueConverter.cs
- src/Tizen.NUI/src/public/XamlBinding/ResourceDictionary.cs
- src/Tizen.NUI/src/public/XamlBinding/XamlStyle.cs
1. Optimize codes of xaml parser.
2. Split resources from Application, each view can has its own resources. Previously only use application resources, it costs more time to lookup.
3. Migrate XamlStyle/XamlResources from View/Layer to Container. Previously both Layer and View have XamlStyle and XamlResources properties, it is redundant.
4. Optimize inherited binding context.
5. This change does not change the previous use.
- ACR:
> [NUI]Fix ResourcesDictionary & BindingContext issues

- src/Tizen.NUI/src/public/WebView/WebView.cs
- test/Tizen.NUI.WebViewTest/SimpleWebViewApp.cs
Add EvaluateJavaScript method on WebView class
It evaluate javascript code with web engine and asynchronously returning result as string through callback.
``` c#
WebView webview = new WebView();
...
webview.EvaluateJavaScript("2+3", (result) => Console.WriteLine($"Eval : {result}"));
```
Add :
``` c#
class WebView {
public void EvaluateJavaScript(string script, JavaScriptMessageHandler handler)
}
```
- ACR:
> [NUI] Add an API for evaluating js with callback in WebView.

- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEnum.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
This patch adds `GetInterfaces` to `AccessibilityDelegate` which will allow to report any number of AT-SPI interfaces in any combinations back to DALi. Complementary changes to DALi make the AT-SPI bridge use `GetInterfaces` instead of `dynamic_cast` (which stops at the C++ language boundary).
Note however, that it is not yet possible to declare more than one AT-SPI interface for a given `Control` in NUI. There are more changes needed, such as removing `SetAccessibilityConstructor` and switching to native C# interfaces, and they will be done in separate PRs.
Related changes (merge everything at the same time, together with this PR):
1. https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/270772/
2. https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+ …
> [NUI][AT-SPI] Support multiple AT-SPI interfaces for View

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
The Seperator of DefaultLinearItem would be not necessary to AT-Client.
This patch is removing Seperator accessible nodes from A11Y tree.
> [NUI][ATSPI] Set AccessibilityHidden for DefaultLinearItem Seperator

- src/Tizen.NUI/src/public/Events/Touch.cs
[NUI] Update the touch description.
'actor' is the wrong term. Change to 'view'.
Point means the touched point.
If there is one touch point, the point index is 0.
If there are two touch points, the point index has 0 and 1.
> [NUI] Update the touch description.

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
- src/Tizen.Applications.Common/Tizen.Applications/CultureInfoHelper.cs
In globalization-invariant mode, creating a new CultureInfo() throws a CultureNotFoundException exception. 
If the process runs in invariant mode, the CoreApplication doesn't set CultureInfos. And, the CultureInfoHelper uses ToLowerInvaraint() instead of ToLower() with CultureInfo("en-US");
Issue: https://github.com/Samsung/TizenFX/issues/3994
> [Applications.Common] Add Globalization-invariant mode check

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
- src/Tizen.Applications.Common/Tizen.Applications/CultureInfoHelper.cs
In globalization-invariant mode, creating a new CultureInfo() throws
a CultureNotFoundException exception. If the process runs in invariant
mode, the CoreApplication doesn't set CultureInfos. And, the
CultureInfoHelper uses ToLowerInvaraint() instead of ToLower() with CultureInfo("en-US");
- ACR:
> [Applications.Common] Add Globalization invariant mode check (#3998)

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliTableView.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/style/demo-theme.json
Due to the DaliDemo.cs is just copycat of dali-demo,
it's local environment is not matched with NUI.
So, `{APPLICATION_RESOURCE_PATH}` is not matched as
`Tizen.Applications.Application.Current.DirectoryInfo.Resource`.
Therefore, when we try to SetStyle with image url, we fail to find that image.
That's why Tizen.NUI.Samples show so many error messages.
So I remove that url in demo style file.
Signed-off-by: Eunki Hong <h.pichulia@gmail.com>
> [NUI][Samples] Remove error message on Tizen.NUI.Samples

- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEnum.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
This interface will be used for getting MBR(Minimum Bounding Rectangle)
with following usage on the AT client side.
cc = atspi_text_get_character_count(text, NULL);
rect = atspi_text_get_range_extents(text, 0, cc, ATSPI_COORD_TYPE_WINDOW, NULL);
This patch depends on
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/271782/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/271761/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/271759/
> [NUI][AT-SPI] text: add "GetRangeExtents" interface

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Previous code only allow to setup BorderlineWidth after set BackgroundColor,
or BackgroundImage.
But some case, user want to setup Borderline-only view.
This patch make BackgroundColor default as Translate
so user can setup borderlin only without setting Background.
Signed-off-by: Eunki Hong <h.pichulia@gmail.com>
- ACR:
> [NUI] Allow BorderlineWidth without BackgroundColor setup.

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
Fix the mismatch between the selected state and clicked event.
Changes the selected state when the clicked event is called.
- ACR: N/A
> [NUI] Fix the mismatch between the selected state and clicked event.

- src/Tizen.NUI/src/internal/Interop/Interop.ActorSignal.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/EventPropagationSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/HitTestSample.cs
[NUI] Add a protected virtual bool HitTest(Touch touch) method.
In the case of TouchEvent or Gesture, there is no way to propagate the event to the view below that is not related.
So, in the hit-test process, called the virtual HitTest method to check whether it was hit or not.
User can override whether hit or not in HitTest.
If it returns false, it means that it will not be hit, and the hit-test continues to the next view.
If it returns true, it means that it was hit, and the touch/gesture event is called from the view as before.
> For example)
Override HitTest as below.
HitTest() is called when the View is hit.
If returned false, This means it will not be hit. Then the hit-test goes to the next view.
``` c#
class MyView : View
{
protected override bool HitTest(Touch touch)
{
return …
```
> [NUI] Add a virtual bool HitTest(Touch touch) method

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- src/Tizen.NUI.Components/Controls/TimePicker.cs
- src/Tizen.NUI/src/public/Input/FocusManager.cs
- test/Tizen.NUI.StyleGuide/Examples/ButtonExample.cs
- test/Tizen.NUI.StyleGuide/Examples/PickerExample.cs
- test/Tizen.NUI.StyleGuide/Examples/ScrollableBase/ScrollableBaseDirectionExample.cs
- test/Tizen.NUI.StyleGuide/Examples/ScrollableBase/ScrollableBaseExample.cs
- test/Tizen.NUI.StyleGuide/Tizen.NUI.StyleGuide.cs
0. https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/272165/ 가 반영되어야 합니다.
1. Button class : 생성자에 Focusable=ture 추가 했습니다. (user 가 사용할때 key focus 를 그대로 사용 가능)
2. ContentPage class : RestoreKeyFocus() 재정의, SaveKeyFocus() 는 Page 것을 그대로 사용, AppBar 가 있으면 최초에 show 될 때 AppBar 에 key focus 주도록 했습니다.
3. Navigator class : Push(), Pop() 에 대해서 SaveKeyFocus(), RestoreKeyFocus() 를 추가했습니다. vs code 의 ctrl+shift+i 단축키로 auto intendation 맞췄습니다.
4. Page class : protected internal virtual 로 SaveKeyFocus(), RestoreKeyFocus() 를 추가 했습니다. default algorithm enabled 시에만 동작하고, Page 의 derived class (예: ContentPage) 에서 상황에 맞게 재정의 할 수 있도록 했습니다.
5. TimePicker class : GetNextFocusableView 를 재정의하여 내부 콤포넌트들의 key navigation 이 가능하게 했습니다. vs code 의 ctrl+shift+i 단축키로 auto intendation 맞췄습니다.
6. FocusManager …
> [NUI] Change Button, TimePicker 's Focusable property as true

- src/Tizen.NUI.Components/Controls/SelectButton.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CheckBoxSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/MenuSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RadioButtonSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TabViewSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
Previously, SelectedChanged was not invoked when IsSelected is changed
by IsSelected's setter.
e.g. checkBox.IsSelected = true;
The issue occurred due to the logic that checked mouse up and key up.
Now, the incorrect logic has been removed and SelectedChanged is invoked
when IsSelected is changed by ISelected's setter.
- ACR:
> [NUI] Fix to invoke SelectedChanged when IsSelected is changed by setter

- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
The method name `SetAccessibilityConstructor()` in NUI has always been misleading, because it actually never had an `accessibilityConstructor` parameter in the first place. With the recent addition of bindings for `Accessible::GetInterfaces()`, all NUI controls use the same `Accessible` implementation (`NUIViewAccessible`) anyway. However, as this method is currently used in many places, it is kept as a wrapper for setting `AccessibilityRole` (and interface flags) and will be removed if/when we decide to switch to AT-SPI interfaces as native C# interfaces. Then, all usages of `SetAccessibilityConstructor()` would be replaced by simply setting `AccessibilityRole` (and interface flags won't be needed).
Merge together with:
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp- …
> [NUI][AT-SPI] Remove interops for SetAccessibilityConstructor()

- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
- src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
- src/Tizen.NUI/src/public/EXaml/EXamlExtensions.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
- src/Tizen.NUI/src/public/XamlBinding/Element.cs
- src/Tizen.NUI/src/public/XamlBinding/Internals/NameScope.cs
1. Add XamlLoaded event for NUIApplication
2. Add Xaml line info for bindable object
These changes to make beholder more useful.
This patch include the changes of the following patches:
https://github.com/Samsung/TizenFX/pull/3790 (merged in DevelNUI)
https://github.com/Samsung/TizenFX/pull/3808 (merged in DevelNUI)
https://github.com/Samsung/TizenFX/pull/3824 (merged in DevelNUI)
- ACR: None (It won't affect previously function)
> [NUI] Apply xaml loaded event for NUIApplication

- pkg/Tizen.NET.API9/xamlbuild/Tizen.NUI.XamlBuild.targets
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlCTask.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlGTask.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlGenerator.cs
1. Add XamlOptimization to use xaml/injection/examl. If this patch included in target, then NeedInjection can be replaced by XamlOptimization.
Usage:
\<XamlOptimization>0\</XamlOptimization>  //Use Xaml
\<XamlOptimization>1\</XamlOptimization> //Use Injection
\<XamlOptimization>2\</XamlOptimization> //Use EXaml.
Note: NeedInjection is still in maintain, but it will be deprecated later. Default we use EXaml, so XamlOptimization default is 2.
- ACR:  None (It won't affect previously function)
> [XamlBuild] Add XamlOptimization to use xaml/injection/examl

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Style/ButtonStyle.cs
- src/Tizen.NUI.Components/Style/RecyclerViewItemStyle.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ActorInternal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/TSView.cs
- test/Tizen.NUI.StyleGuide/Examples/ButtonExample.cs
- test/Tizen.NUI.StyleGuide/Examples/ProgressExample.cs
- test/Tizen.NUI.StyleGuide/Examples/SliderExample.cs
NUI View object can disable touch by set Senstive, key focus by Focusable, and touch focus by FocusableInTouch property individually but we never had unified control property of disabling.
This work is pulling up IsEnabled property from to Button,
so every view object can handle Enable/Disable over the sestivity and  focusability
and automated handle of controlState.
Inherited class can override enabled action in OnEnabled() protected virtual method,
```
protected override bool OnEnabled(bool enabled)
{
base.OnEnabled(enabled);
/// Fill user class specific actions.
/// you can changed enablity value here, but not recommanded.
return enabled;
}
```
See also,
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/271115
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csha …
> [NUI] Add IsEnabled Property in View class for controling user interaction.

- src/Tizen.NUI/src/internal/Interop/Interop.WidgetImpl.cs
- src/Tizen.NUI/src/internal/Widget/WidgetImpl.cs
- src/Tizen.NUI/src/public/Widget/Widget.cs
When a widget consumes a keyEvent, the WidgetView must also consume that keyEvent.
the API called SetUsingKeyEvent() allows the WidgetApplication to set this flag.
i added related patches:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/271970/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/widget-viewer-dali/+/271972/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/271973/
- ACR:
> [NUI] Add API for consuming keyEvent in Widget

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Fix typo in FlexLayout size calculation logic.
This typo was caused by https://github.com/Samsung/TizenFX/pull/4032
- ACR:
> [NUI] Fix FlexLayout size calculation issue caused by typo

- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlGenerator.cs
Support use root node inheirt nest type
Sample
xaml:
`<l:CustomForNestView-CustomView x:Class="Tizen.NUI.Examples.NestedTypeTestPage"`
c#:
`public partial class NestedTypeTestPage : CustomForNestView.CustomView`
- ACR:
> [NUI][XamlBuild] Support use root node inheirt nest type

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Style/ButtonStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
LinearLayout.LinearAlignment is deprecated, and HorizontalAlignment and
VerticalAlignment are added.
To replace Button.ItemAlignment, whose type is LinearAlignment,
ItemHorizontalAlignment and ItemVerticalAlignment are added.
- ACR:
> [NUI] Add Button ItemHorizontalAlignment and ItemVerticalAlignment

- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ThemeChangeSample.cs
Originally although property value of a view is set, if theme is
changed, the value would be restored to the default value.
This is not expected.
This patch is to check if the value has been set already or not,
if set, do not set the value again.
- ACR:
> [NUI] Do not set value of property again when theme is changed.

- src/Tizen.NUI/src/internal/Common/CustomAlgorithmInterface.cs
- src/Tizen.NUI/src/internal/Interop/Interop.CustomAlgorithmInterface.cs
- src/Tizen.NUI/src/public/Input/FocusManager.cs
- src/Tizen.NUI/src/public/Input/ICustomAwareDeviceFocusAlgorithm.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GetNextFocusSample.cs
[NUI] Add a new Tizen.NUI.ICustomAwareDeviceFocusAlgorithm.
This interface takes an additional deviceName argument to GetNextFocusableView().
The deviceName is the name of the device where the key event occurred.
A new deviceName added to GetNextFocusableView() should not affect the current app.
Current apps are using the FocusManager.ICustomFocusAlgorithm interface.
So I created a new Tizen.NUI.ICustomAwareDeviceFocusAlgorithm interface.
for example)
Currently
``` c#
class CustomInterface : FocusManager.ICustomFocusAlgorithm
{
public View GetNextFocusableView(View current, View proposed, View.FocusDirection direction)
{
return proposed;
}
}
```
If you wnat to do GetNextFocusableView() with deviceName, you can inherit ICustomAwareDeviceFocusAlgorithm.
``` c#
class CustomInterface : …
```
> [NUI] Add a new Tizen.NUI.ICustomAwareDeviceFocusAlgorithm.

- src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CustomWheelEventSample.cs
Clockwise and CounterClockwise are rotary wheel event directions.
There is also a requirement that the focus be moved with a rotary wheel as well.
So, you can set the FocusableView according to the clockwise and counterclockwise directions of the rotary wheel.
```C#
var viewA = new View { Focusable = true };
var ViewB = new View { Focusable = true };
viewA.ClockwiseFocusableView = viewB;
ViewB.CounterClockwiseFocusableView = ViewA;
```
In ViewA, if the rotary wheel is in the Clockwise direction, ViewB is focused.
When the rotary wheel in ViewB is in the CountClockwise direction, ViewA is focused.
Dependency
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/272040/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/272137/
- ACR:
> [NUI] Supports Clockwise and CounterClockwise focus movement.

- src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
ScreenReaderEnabled should be distinguished from IsEnabled.
This is because there are things to do only when the screen reader is enabled.
Dependencies:
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/272349
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/272348
> [NUI][AT-SPI] Add ScreenReaderEnabled, Disabled

- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlGenerator.cs
This requirement comes from VD to avoid memory leaks.
After modification, all nodes generated by XAML will be automatically as null.
- ACR:
> [NUI][XamlBuild] Set node as null when calling ExitXaml().

- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/Constants.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSSlider.cs
- Remove some Slider events which have been deprecated since API level 8.
- ACR:  TCSACR-483
https://code.sec.samsung.net/jira/browse/TCSACR-483
Removed :
public event EventHandler<ValueChangedArgs> ValueChangedEvent
public event EventHandler<SlidingFinishedArgs> SlidingFinishedEvent
public event EventHandler<StateChangedArgs> StateChangedEvent
public class ValueChangedArgs
public float ValueChangedArgs.CurrentValue
public class SlidingFinishedArgs
public float SlidingFinishedArgs.CurrentValue
public class StateChangedArgs
public ControlStates StateChangedArgs.CurrentState
> [NUI][TCSACR-483] Remove Slider deprecated events and eventArgs

- src/Tizen.NUI.Components/Controls/DatePicker.cs
- src/Tizen.NUI.Components/Controls/Picker.cs
- src/Tizen.NUI.Components/Controls/TimePicker.cs
[NUI] propose a way to change the value of Picker by up/down direction key
@lwc0917 
안녕하세요.
DatePicker 와 TimePicker 에서 KeyEvent 와 GetNextFocusableView 를 이용해서 내부의 Picker 들을 navigation 하고 값을 변경 할 수 있는 방법을 제안 드립니다.
GetNextFocusableView 로 내부의 picker 들을 방향키로 navigation 할 수 있게 했고, KeyEvent 로 enter key(Return) 가 눌리면 edit mode 에서 up/down 키로 값을 바꿀수 있게 했습니다. (다시 enter key 를 누르면 edit mode 가 해제 됩니다.)
UX 스팩이 있다면 확인 부탁드리고, 제가 단순하게 제안드리는 것이고 이게 best practice 라고 말씀드리는것은 아닙니다. 
이점 감안하시어 확인 부탁드립니다.
감사합니다.
Hello.
In DatePicker and TimePicker, using KeyEvent and GetNextFocusableView, we propose a way to navigate and change values of Pickers inside.
With GetNextFocusableView, internal pickers can be navigated with arrow keys, and when the enter key (Return) is pressed with KeyEvent, the value can be changed …
> [NUI] propose a way to change the value of Picker by up/down direction key

- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionViewBindableProperty.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
fix buildwarnings in NUI Components.
_Controls/RecyclerView/Item/RecyclerViewItem.cs(33,49): warning CS0108: 'RecyclerViewItem.IsEnabledProperty' hides inherited member 'View.IsEnabledProperty'. Use the new keyword if hiding was intended. [/home/sh10233lee/dev/Branch/TizenFX/src/Tizen.NUI.Components/Tizen.NUI.Components.csproj]_
=>
**add new key.**
_Controls/RecyclerView/CollectionView.cs(107,49): warning CS0108: 'CollectionView.ItemsSourceProperty' hides inherited member 'RecyclerView.ItemsSourceProperty'. Use the new keyword if hiding was intended. [/home/sh10233lee/dev/Branch/TizenFX/src/Tizen.NUI.Components/Tizen.NUI.Components.csproj]_
=>
**remove ItemsSourceProperty and use RecyclerView's.
also change private internalItemsSource to internal virtual to override.** …
> [NUI] remove warning messages with refactoring collectionView bindableProperties

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
If GrabTouchAfterLeave is true, Button Up will result in Finished rather than Interrupted even if it is out of the button area.
So, it is necessary to check whether it is Button Up in the button area.
- ACR:
> [NUI] Checks the button area if GrabTouchAfterLeave is true.

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DefaultGrabTouchAfterLeaveSample.cs
1. Add SetDefaultGrabTouchAfterLeave(bool enable) in View
```c#
// If this is set to true, all views are created with GrabTouchAfterLeave set to true.
View.SetDefaultGrabTouchAfterLeave(true);
```
> [NUI] Add SetDefaultGrabTouchAfterLeave api.

- src/Tizen.NUI.Components/Controls/Picker.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEnum.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AtspiSample.cs
The AtspiEvents can be used for the event mask to suppress
specific event.
This is the second version to provide AtspiEvents.
The first version is
https://github.com/Samsung/TizenFX/pull/4019
Dependency:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/272794/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/272184/
> [NUI][AT-SPI] Introduce AtspiEvents

- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Like other APIs in LayoutGroup, exception should occur if LayoutItem
argument "child" is null.
- ACR:
> [NUI] Fix warning by checking null argument in LayoutGroup

- src/Tizen.NUI/src/public/Application/NUIApplication.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
[NUI] Fix to disable ThemeManager in tv profile
- in some place, `ExternalThemeEnabled` macro has to be inserted to avoid appfw-tizen-theme so loading.
none
> [NUI] Fix to disable ThemeManager in tv profile

- src/Tizen.Uix.Sticker/Interop/Interop.Libraries.cs
- src/Tizen.Uix.Sticker/Interop/Interop.StickerConsumer.cs
- src/Tizen.Uix.Sticker/Interop/Interop.StickerData.cs
- src/Tizen.Uix.Sticker/Interop/Interop.StickerProvider.cs
- src/Tizen.Uix.Sticker/Tizen.Uix.Sticker.csproj
- src/Tizen.Uix.Sticker/Tizen.Uix.Sticker.sln
- src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/DeletedEventArgs.cs
- src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/ExceptionFactory.cs
- src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/GroupImage.cs
- src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/InsertedEventArgs.cs
- src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/StickerConsumer.cs
- src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/StickerData.cs
- src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/StickerProvider.cs
- src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/UpdatedEventArgs.cs
Add Sticker APIs to manage sticker information
Using Sticker library, a sticker application can provide sticker information to applications that want to read the sticker information as the standard specification.
StickerProvider APIs are used when sticker application creates/updates/deletes sticker information.
StickerConsumer APIs are used when application that use stored sticker search for sticker information.
- ACR: [TCSACR-481](https://code.sec.samsung.net/jira/browse/TCSACR-481)
> [Sticker] Add Sticker APIs

- src/Tizen.NUI.Components/Controls/Slider.cs
- 'editModeIndicator' of Slider class is not created all the time.
So, added Null check for this variable when Dispose() is called.
- N/A
> [NUI] Add Null check in Slider Dispose

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
TextField and TextEditor have Focusable set to true.
If Focusable is true, it can receive focus when moved to the keyboard.
> [NUI] TextField and TextEditor have Focusable set to true.

- src/Tizen.NUI/src/internal/Application/Application.cs
The GetWindow increases reference count of the Dali Window.
So there was no chance to call the Window destructor.
> [NUI] application: remove unnecessary reference count increments

- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlGenerator.cs
This requirement comes from VD.
Before modification:
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Tizen.NUI.Xaml.Build.Tasks.XamlG", "1.0.6.0")]
**_private_** void ExitXaml() {
......
}
After modification:
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Tizen.NUI.Xaml.Build.Tasks.XamlG", "1.0.6.0")]
**_internal_** void ExitXaml() {
......
}
- ACR:
> [NUI][XamlBuild] Set ExitXaml() as internal method.

- src/Tizen.NUI/src/public/Common/PropertyNotification.cs
- src/Tizen.NUI/src/public/Window/Window.cs
Some Interop API required Delete pairwisely.
This is cause IntPtr have same role as Native size's BaseHandle.
It mean, they increase Native side reference count of BaseObject,
and should decrease the reference by delete it self.
But that IntPtr created in c++ side, so also should delete in c++ side.
Registry.cs use IntPtr as Key so, some API us it as wrong way.
If someone find matched value in Registry, it is just one of BaseHandle.
inputed IntPtr required to delete but some API didn't delete it!
This patch find that case, and make them remove well.
> [NUI] Remove some potential of memory leak

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/TextEditorStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextEditor.cs
editor.VerticalAlignment = VerticalAlignment.Top;
editor.VerticalAlignment = VerticalAlignment.Center;
editor.VerticalAlignment = VerticalAlignment.Bottom;
dali patches:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/273039/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/273582/
> [NUI] Add VerticalAlignment in TextEditor

- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlGenerator.cs
This issue was reported by VD, If XamlOptimization set as 0, call ExitXaml would throw the exception : Error CS0103 The name 'ExitXaml' does not exist in the current context.
The reason:
Because the option 0  will not generate the method ExitXaml, so it will cause the build error.
Solution:
Generate an empty 'ExitXaml' method in the *.g.cs file.
After modification:
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Tizen.NUI.Xaml.Build.Tasks.XamlG", "4.0.0.0")]
**internal void ExitXaml() {
}**
- ACR:
> [NUI][XamlBuild] Fix build error when calling ExitXaml() if XamlOptimization set as 0.

- src/Tizen.NUI/src/internal/XamlBinding/ExtentsTypeConverter.cs
- src/Tizen.NUI/src/internal/XamlBinding/ListStringTypeConverter.cs
- src/Tizen.NUI/src/internal/XamlBinding/PositionTypeConverter.cs
- src/Tizen.NUI/src/internal/XamlBinding/RectangleTypeConverter.cs
- src/Tizen.NUI/src/internal/XamlBinding/RotationTypeConverter.cs
- src/Tizen.NUI/src/internal/XamlBinding/VectorTypeConverter.cs
- src/Tizen.NUI/src/public/XamlBinding/ColorTypeConverter.cs
- src/Tizen.NUI/src/public/XamlBinding/SizeTypeConverter.cs
- src/Tizen.NUI/src/public/XamlBinding/TypeConverter.cs
This requirement comes from 'develop mode'
For TypeConverter, ConvertFromInvariantString() & ConvertToString() use ',' and ' ' as delimiter respectively.
SizeTypeConveter, for example:
public override object ConvertFromInvariantString(string value)
{
......
string[] parts = value.Split(',');
......
}
public override string ConvertToString(object value)
{
......
return size.Width.ToString() + ' ' + size.Height.ToString() + ' ' + size.Depth.ToString();
......
}
Now we use ',' as delimiter, after modification:
public override object ConvertFromInvariantString(string value)
{
......
string[] parts = value.Split(TypeConverter.UnifiedDelimiter);
......
}
public override string ConvertToString(object value)
{
......
return size.Width.ToString() + TypeConverter.UnifiedDelimiter + …
> [NUI][XamlBinding] Unifying the delimiter for TypeConverter.

- src/Tizen.NUI/src/public/EXaml/EXamlExtensions.cs
[NUI][Xaml] Fix issue that the Xaml element which has the created-in-csharp parent will not be disposed when exit xaml
none
> [NUI][Xaml] Fix issue that the Xaml element which has the created-in-csharp parent will not be disposed when exit xaml

- src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
The latest DialogPage's Scrim UX has been applied.
The Scrim's BackgroundColor has been defined in Theme.
- ACR:
> [NUI] Apply DialogPage's Scrim UX - BackgroundColor

- src/Tizen.NUI.Components/Controls/Picker.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEnum.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AtspiSample.cs
This commit changes the syntax used to modify the collection of suppressed AT-SPI events (D-Bus signals) to match the indexing syntax used in DALi:
```c#
view.SetAccessibilityEventSuppressed(AccessibilityEvent.MovedOut, true); // old C# syntax
```
```c#
view.AccessibilitySuppressedEvents[AccessibilityEvent.MovedOut] = true; // new C# syntax
```
```c++
accessible->GetSuppressedEvents()[Accessibility::AtspiEvent::MOVED_OUT] = true; // C++ syntax
```
Interops are unchanged (i.e. there are no related DALi patches).
- ACR: None
> [NUI][AT-SPI] Add indexable AccessibilitySuppressedEvents

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Horizontal oriented LinearLayout decides max height among children.
Vertical oriented LinearLayout decides max width among children.
Previously, the max height and width might be calculated before all
children sizes were measured.
So the max height and width might be calculated with children's previous
height and width.
Now, the max height and width should be calculated after all children
sizes are measured.
So the max height and width are calculated with children's current
height and width.
e.g. problem case
var window = NUIApplication.GetDefaultWindow();
var parent = new View()
{
Layout = new LinearLayout(),
WidthSpecification = LayoutParamPolicies.MatchParent,
HeightSpecification = LayoutParamPolicies.WrapContent,
BackgroundColor = Color.Red,
};
window.Add(parent);
var child = new …
> [NUI] Fix LinearLayout to update max height and width correctly

- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Originally, CustomView.GetNaturalSize() returned size set by user
explicitly.
It was changed by https://github.com/Samsung/TizenFX/pull/2515.
By the above PR, CustomView.GetNaturalSize() returned Size2D which can
be set by both user and Layout.
Since the current CustomView.GetNaturalSize() cannot distinguish the
size set by user from the size set by Layout, the size set by Layout
previously can be preserved incorrectly and the size is not updated
incorrectly.
To resolve the above issue, CustomView.GetNaturalSize() returns Size2D
set by user explicitly to make Layout preserve the size only set by user
explicitly.
e.g. problem case
var window = NUIApplication.GetDefaultWindow();
var parent = new Control()
{
Layout = new AbsoluteLayout(),
WidthSpecification = LayoutParamPolicies.MatchParent, …
> [NUI] Fix CustomView.GetNaturalSize() to return Size2D set by user

- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
Svace issue occurs because null check of BorderWindow is done after
BorderWindow is accessed in DefaultBorder.Dispose().
When close button in DefaultBorder is clicked, BorderWindow is disposed.
When BorderWindow is disposed, DisposeBorder() is called.
In DisposeBorder(), DefaultBorder is disposed.
When DefaultBorder is disposed, BorderWindow is under disposed but
BorderWindow is not set to be null yet.
Therefore, it is not necessary to do null check of BorderWindow in
DefaultBorder.Dispose() to resolve the Svace issue.
- ACR:
> [NUI] Fix Svace issue not to do unnecessary null check in DefaultBorder

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
- Some NUI Components have text parts and they need to be connected with
Accessibillity features.
(`AccessibilityName` and `AccessibiityDescription`)
- N/A
> [NUI][AT-SPI] Add to set AccessibilityName and Description in some components

- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- AT-SPI2 tree shows Scrollbar, Control, and ImageView when Scrollbar
class is just created.
- `Control` is trackView in Scrollbar, but is not necessary for at-spi
tree. So, it can be hidden in the tree.
- Applied AccessibilityHidden property to a View.
- N/A
-
> [NUI][AT-SPI] Apply AccessibilityHidden for Scrollbar

- src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs
Fix dllimport lib since capi-nnstreamer  is separated to
* capi-ml-common <- capi-ml-inference-single <- capi-nnstreamer.
This patch fixes dotnet test failure.
Tested with tizen-unified_20220420.1_mobile-wayland-armv7l-tm1 image.
Signed-off-by: gichan <gichan2.jang@samsung.com>
> [MachineLearning.Inference] Change interop

- src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs
Fix dllimport lib since MachineLearning package separated as below:
capi-nnstreamer -> capi-ml-common, capi-ml-inference-single and
capi-nnstreamer.
Signed-off-by: gichan <gichan2.jang@samsung.com>
- ACR:
> [MachineLearning.Inference] Change interop (#4168)

- src/Tizen.NUI.Components/Controls/TabButton.cs
Check null pointer of tabButtonStyle and its properties in TabButton to
resolve Svace issue.
- ACR:
> [NUI] Fix Svace issue on TabButton by null check

- src/Tizen.NUI/src/public/Common/Layer.cs
- src/Tizen.NUI/src/public/Window/Window.cs
Since Layer.Dispose updates LayoutController.LayoutCount,
LayoutController.Dispose should be called after all layers' Dispose are
called in Window.Dispose.
When a layer's LayoutCount is set, it should update its
LayoutController.LayoutCount by the difference between new and current
LayoutCount.
- ACR:
> [NUI] Fix Window.Dispose and Layer.LayoutCount

- src/Tizen.NUI/src/internal/Interop/Interop.DragAndDrop.cs
- src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
- src/Tizen.NUI/src/public/DragAndDrop/DragEvent.cs
- test/NUIDnDSource/NUIDnDSource.cs
Implements drag source event to receive the drag window status
- start :  drag and drop is started. (when dragging is started)
- cancel : drag and drop is cancelled (when drag window is dropped outside of target view)
- accept : drag data is accepted. (when target received drag data )
- finish : drag and drop is finished. (when drag and drop is finished without cancellation, this event does not occur in the cancelled state.)
The events aboves are matched with window server drag and drop events.
- ACR: N/A
> [NUI] DragAndDrop: Implements drag source events.

- pkg/Tizen.NET.API10/xamlbuild/Tizen.NUI.XamlBuild.targets
- src/Tizen.NUI.XamlBuild/src/public/EXamlBuild/EXamlSetPropertiesVisitor.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/CreateObjectVisitor.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/NUIXamlCTask.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/NUIXamlGTask.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/SetNamescopesAndRegisterNamesVisitor.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/SetPropertiesVisitor.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlGenerator.cs
This requirements comes from the build error:
The "ValidateOnly" parameter is not supported by the "XamlCTask" task loaded from assembly: Tizen.NUI.XamlBuild.
Because NUI XamlCTask makes Xamarin, which is already existed in Tizen, so change XamlCTask into NUIXamlCTask, to avoid confusing.
- ACR:
> [NUI][XamlBuild] Change XamlCTask / XamlGTask into NUIXamlCTask / NUIXamlGTask.

- pkg/Tizen.NET.API9/xamlbuild/Tizen.NUI.XamlBuild.targets
- src/Tizen.NUI.XamlBuild/src/public/EXamlBuild/EXamlSetPropertiesVisitor.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/CreateObjectVisitor.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/NUIXamlCTask.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/NUIXamlGTask.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/SetNamescopesAndRegisterNamesVisitor.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/SetPropertiesVisitor.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlGenerator.cs
**Sync code from API10.**
This requirements comes from the build error:
The "ValidateOnly" parameter is not supported by the "XamlCTask" task loaded from assembly: Tizen.NUI.XamlBuild.
Because NUI XamlCTask makes Xamarin, which is already existed in Tizen, so change XamlCTask into NUIXamlCTask, to avoid confusing.
- ACR:
> [NUI][XamlBuild] Change XamlCTask / XamlGTask into NUIXamlCTask /  NUIXamlGTask.

- src/Tizen.NUI/src/public/Window/Window.cs
Previously, Window.Add and Remove did not use Layer.Add and Remove.
This caused LayoutCount was updated duplicately.
e.g.
- Calling window.Remove(view) twice decreases LayoutCount duplicately.
Moreover, users could not get ChildAdded and ChildRemoved events from
Window's RootLayer.
Now, Window.Add and Remove use Layer.Add and Remove directly.
- ACR:
> [NUI] Fix Window.Add and Remove to use Layer.Add and Remove directly

- src/Tizen.NUI/src/internal/Widget/WidgetApplication.cs
As the widget passes a string to use the creation function, string types makes crash.
To avoid this problem, we use Intptr instead of string when widget sender its Id.
- ACR:
> [NUI] Fix crash issue in widget

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- test/Tizen.NUI.LayoutSamples/Tizen.NUI.LayoutSamples/ObjectView.cs
View.Margin and Padding refers View.Layout.Margin and Padding.
So if View.Margin and Padding are set with Layout, then
View.Layout.Margin and Padding are set and View.Margin and Padding
become Extents(0, 0, 0, 0).
Previously, the problem was that View.MarginProperty and PaddingProperty
did not support the above logic properly.
Now, to resolve the above issue, View.MarginProperty and PaddingProperty
support the above logic properly.
i.e. Setting View.MarginProperty and PaddingProperty with Layout set
value to View.Layout.Margin and Padding and also set
Extents(0, 0, 0, 0) to View.Margin and Padding.
- ACR:
> [NUI] Fix MarginProperty and PaddingProperty with Layout

- src/Tizen.NUI/src/internal/Interop/Interop.WindowAccessibilityHighlightSignal.cs
- src/Tizen.NUI/src/internal/Window/WindowAccessibilityHighlightEvent.cs
- src/Tizen.NUI/src/public/Window/WindowEvent.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AtspiSample.cs
The Window will highlight itself on NUI side.
The GrabHighlight emits the Highlight signal.
This signal will be used for changing window border color or others
to indicate the NUI window is selected on the multi-window environment.
This is NOT used for the screen-reader.
Dependency:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/273682/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/273683/
> [NUI][AT-SPI] Window: add highlight signal

- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
It is commonly used that child view is positioned with its size from
line target in RelativeLayout.
If ellipsis text was positioned from line target in RelativeLayout, then
it was not positioned to the place where users intended.
e.g. Position textLabel at the bottom of parent.
The target is the bottom line of the parent.
RelativeLayout.SetTopTarget(textLabel, parent);
RelativeLayout.SetTopRelativeOffset(textLabel, 1.0f);
RelativeLayout.SetBottomTarget(textLabel, parent);
RelativeLayout.SetBottomRelativeOffset(textLabel, 1.0f);
RelativeLayout.SetVerticalAlignment(textLabel, RelativeLayout.Alignment.End);
Previously, in the above situation, RelativeLayout could not position
ellipsis text at the bottom of the parent.
Instead, the ellipsis text was positioned outside of the parent.
Now, in …
> [NUI] Fix RelativeLayout to calculate ellipsis text from line target

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
When calculating position coordinates, it should be calculated based on the nextFocusedView.
Fixed a bug that was calculated based on the wrong View.
- ACR:
> [NUI] When calculating position coordinates, it should be calculated based on the nextFocusedView.

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
Since CheckBox.Text size can be increased, CheckBox size should not be
set in theme.
CheckBox.ItemSpacing is set to be 8px.
Since Button.Icon is able not to be set, Button.Icon size should not be
set in theme.
- ACR:
> [NUI] Fix CheckBox and Button.Icon sizes in theme

- src/Tizen.NUI/src/internal/Interop/Interop.FocusManager.cs
- src/Tizen.NUI/src/public/Input/FocusManager.cs
If you enable DefaultAlgorithm of FocusManager, you can automatically move the focus to the nearest View.
However, this is always root based on Window.
We want to change this root.
So I add two apis
1. SetFocusFinderRootView(View root)
- This will only look for focusable Views within that View tree when looking for the next focus.
2. ResetFocusFinderRootView()
- the root becomes the window again.
Dependency
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/274424/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/274422/
- ACR:
> [NUI] Add SetFocusFinderRootView() and ResetFocusFinderRootView() api

- src/Tizen.NUI/src/public/Window/WindowEvent.cs
Guess what happens if atspi highlight callback is called for a window
after the window is diposed.
> [NUI][AT-SPI] window disconnect highlight signal

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
[NUI] There was a problem calculating the scroll position.
It caused unnecessary scrolling even when it wasn't necessary.
Change it to scroll only when needed.
- ACR:
> [NUI] There was a problem calculating the scroll position. Change it to scroll only when needed.

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
ContentPage.Content becomes hidden when push/pop were finished to
unregister accessibility.
i.e. Show() registers accessibility.
Hide() unregisters accessibility.
Previously, ContentPage.Content was invisible when push/pop were
started because the invisible state remained since the previous
push/pop were finished.
e.g. PageTransitionSample in Tizen.NUI.Samples
Now, ContentPage.Content is visible when push/pop are started.
i.e. SetVisible(true) is called for ContentPage.Content to make it
visible but not to register accessibility at that time.
- ACR:
> [NUI] Fix Navigator not to make ContentPage.Content hide

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
CheckBox and RadioButton has Padding around the Icon based on the latest
UX.
Due to the Padding, CheckBox and RadioButton sizes are increased.
Since CheckBox and RadioButton's sizes are increased,
DefaultLinearItem's Padding and Margin are updated.
- ACR:
> [NUI] Set Padding to CheckBox and RadioButton based on the latest UX

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Fix typo ScreenPosition.Y to ScreenPosition.X in #4238.
- ACR:
> [NUI] Fix typo in ScrollableBase

- src/Tizen.NUI/src/internal/Layouting/Interop/Interop.FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
FlexLayout is not BaseHandle.
We don't need to follow up API pattern of BaseHandle.
- ACR:
> [NUI] Remove useless API in FlexLayout

- src/Tizen.NUI.Components/Controls/Slider.cs
- Currently, when the user sets ThumbColor, the background color of
thumb is changed.
- Fixed to change the thumb color itself, not the background color.
- N/A
> [NUI] Fix ThumbColor property to change its own color

- src/Tizen.NUI/src/public/Common/PropertyMap.cs
[NUI] Replace the part that throws an exception with an error message to keep the behavior of previous version
- related to http://jira.vd.sec.samsung.net/browse/UNI-3344
- throwing an exception has been added in API10 first, this would cause backward compatibility violation, so the exception is replaced by error message
none
> [NUI] Replace the part that throws an exception with an error message to keep the behavior of previous version

- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
`GetAccessibilityRelations()` used to return an `AddressCollection`, however the `Address` type is useless in NUI, because (1) it is not possible to convert an `Address` to a `View`, and (2) it is not possible to obtain an `Address` of a `View`. This PR makes `GetAccessibilityRelations()` return a dictionary mapping `AccessibilityRelationType` to a collection of `View`. `Address` and `AddressCollection` are removed altogether with this PR.
Dependencies (merge together with this PR):
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/275033/
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/275035/
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/275034/
- ACR: None
> [NUI][AT-SPI] Make GetAccessibilityRelations() usable

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
This method originated as a hack to cut the AT-SPI tree at a specific node in the case of compound controls (i.e. composed of multiple views overlaid on top of each other), so that there is only one leaf node (instead of a subtree) for `Button`, `Slider`, `Progress` (cf. https://github.com/Samsung/TizenFX/pull/2852) etc. When the AT-SPI infrastructure was developed for DALi, there were no "compound controls" which would need to be handled this way, hence the addition of `AccessibilityShouldReportZeroChildren()` specifically for NUI controls.
However, the `AccessibilityHidden` property was introduced in January 2022 (https://github.com/Samsung/TizenFX/pull/3765) to allow for controlling which nodes should be removed from the AT-SPI tree, and has since become the recommended solution over …
> [NUI][AT-SPI] Remove AccessibilityShouldReportZeroChildren()

- src/Tizen.NUI/src/public/Application/NUIApplication.cs
- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/BorderWindowTest.cs
IsMaximized() is false even if the app runs at full size without Maximized(true).
So, do Maximize(true) when launched in full size.
> [NUI] Supprot border for apps launched in full size.

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Components/Controls/ScrollableBaseBindableProperty.cs
- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSScrollableBase.cs
scrollbar is now automatically fade in/out when it stay long enough to threshold time.
Scrollablebase :
FadeScollbar boolean Property is enabling scrollbar fading.
default value is true.
ScrollbarBase :
FadeOutThreshold is internal unsigned integar value threshold time for fading out. 500ms is default value.
FadeDuration is internal integar value duration for fading animation. 200ms is default value.
FadeIn(): internal method for fade in animation.
FadeOut(): internal method for fade out animation. fade out will be excuted on delay of FadeOutThreshold.
You can test this on
Tizen.NUI.StyleGuide -> ScrollableBaseExample->Vertical or Horizontal
**
Known Issue : Scroll Animation is too long in some cases even they reach the destination.
it seems animation still exist on floating point for a …
> [NUI] Support fade scrollbar feature.

- src/Tizen.Applications.Common/Interop/Interop.AppControl.cs
- src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
Add a new internal API for inhouse applications.
The method is for setting auto restart option at runtime.
The functionality of the method only applies to the caller application.
Added:
- void AppControl.SetAutoRestart(AppControl appControl);
> Add AppControl.SetAutoRestart method

- src/Tizen.Multimedia.Remoting/Interop/Interop.WebRTC.DataChannel.cs
- src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.Events.cs
- src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.cs
Add new DataChannel buffered amount APIs
User can set threshold value using `BufferedAmountLowThreshold` property and the amount of buffered data is lower than threshold value, `BufferedAmountLow` event will be raised.
- TCSACR-480
> [WebRTC] Add new DataChannel buffered amount APIs

- src/Tizen.NUI/src/public/Input/FocusManager.cs
- src/Tizen.NUI/src/public/Input/FocusManagerArgs.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FocusManagerEventTest.cs
[NUI] Change key focus related event's name
- PreFocusChange 를 FocusChanging, FocusChanged 의 EventArgs 를 아래와 같이 수정 및 ACR 예정 입니다.
PreFocusChange => FocusChanging, 
PreFocusChangeEventArgs.CurrentView => FocusChangingEventArgs.Current,
PreFocusChangeEventArgs.ProposedView => FocusChangingEventArgs.Proposed,
FocusChangedEventArgs.CurrentView => FocusChangedEventArgs.Previous,
FocusChangedEventArgs.NextView => FocusChangedEventArgs.Current,
- 기존에 사용되던 event 들은 deprecated ACR 을 할 예정입니다. (remove ACR 은 진행하지 않을 예정입니다.)
- sample app 입니다. https://github.com/Samsung/TizenFX/pull/4080/files#diff-d6197236cdfc0cfaf0ec0813cfb79496c2ba9c595f9464bf04fa7624c97950e0R96
https://code.sec.samsung.net/jira/browse/TCSACR-486
> [NUI][TCSACR-486] Change key focus related event's name

- src/Tizen.NUI.Components/Controls/MenuItem.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
Previously, MenuItem added TextLabel and Icon only if their properties
were set properly.
e.g. Icon is added only if IconURL is set properly.
Now, MenuItem adds TextLabel and Icon regardless of their properties
like Button does.
Because TextLabel and Icon are MenuItem's default feature so they
should always be added to MenuItem.
Icon's default size in theme is removed until Button has a proper way
to support default Icon size.
- ACR:
> [NUI] Fix MenuItem to add TextLabel and Icon always

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
To separate GUI code from Control logic code, Layout property is
supported by ViewStyle.
Now, Layout property can be set in Theme cs file.
In this PR, Tizen.NUI.Components.Button's Theme supports Layout
property.
After applying this PR, all other Controls' Themes can support Layout
property.
- ACR:
> [NUI] Support Layout property by ViewStyle

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
- test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/TSImageView.cs
Due to the PreMultipliedAlpha property used
both ImageView and ImageVisual internally,
(+ This property don't required re-create new Visual)
We need to make some new way to send this changness
news into ImageVisual.
> [NUI] Fix bug that PreMultipliedAlpha not applied to Visual

- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
1. Make context as manually set in SetValue function of BindableObject.
2. Revert first use own binding context changes.
- ACR: None
> [NUI] Add manually set api10 20220530

- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
Set LowIndicatorImageURL and HighIndicatorImageURL for slider, but could not be shown, because the ImageView was not be added , 
// in Slider.cs
public override void ApplyStyle(ViewStyle viewStyle)
{
......
if (null != sliderStyle?.LowIndicatorImage)
{
CreateLowIndicatorImage().ApplyStyle(sliderStyle.LowIndicatorImage);
}
if (null != sliderStyle?.HighIndicatorImage)
{
CreateHighIndicatorImage().ApplyStyle(sliderStyle.HighIndicatorImage);
}
......
}
// added in Slider.Internal.cs
private ImageView CreateLowIndicatorImage()
{
if (lowIndicatorImage == null)
{
lowIndicatorImage = new ImageView()
{
WidthResizePolicy = ResizePolicyType.Fixed,
HeightResizePolicy = ResizePolicyType.Fixed,
AccessibilityHidden = true,
};
this.Add(lowIndicatorImage);
}
return lowIndicatorImage;
}
private ImageView …
> [NUI.Components] Fix issue of LowIndicatorImage & HighIndicatorImage could not shown normally

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Window/Window.cs
1. Add GetLastKeyEvent and GetLastTouchEvent api for Window.
- ACR: None.
> [NUI] Add GetLastKeyEvent and GetLastTouchEvent api for Window

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
- src/Tizen.NUI/src/public/Window/IBorderInterface.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/BorderWindowTest.cs
[NUI] Add border resizing policy and add api to show/hide border when OverlayMode is true.
1. It can be proportionally resized or fixed according to the border resizing policy.
2. If OverlayMode is true, you can show/hide the border through api.
Through this, you can show/hide the border by touch or specific key event.
> [NUI] Add border resizing policy and add api to show/hide border when OverlayMode is true.

- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
[NUI] Apply SetFocusFinderRootView() to DialogPage only when DefaultAlgorithm Enabled
- related to https://github.sec.samsung.net/dotnet/NUIBackend/issues/130#issuecomment-1494887
none
> [NUI] Apply SetFocusFinderRootView() to DialogPage only when DefaultAlgorithm Enabled

- src/Tizen.NUI/src/public/Application/NUIApplication.cs
- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
When closing, it is necessary to distinguish between the application case and the window case.
So, in the case of Application, we add a delegate so that it can be properly closed through the delegate.
> [NUI] Add CloseDelegate for closing the application by the border.

- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
remove GetDescription() for better performance.
and there is no need to convert string to enum.
because the HORIZONTAL_ALIGNMENT and VERTICAL_ALIGNMENT properties of DALi
can be set to an integer or string, and there is no burden if it is an integer(enum).
https://code.sec.samsung.net/confluence/pages/viewpage.action?pageId=269926545&focusedCommentId=269928026
> [NUI] Remove GetDescription() in TextLabelBindableProperty

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
- src/Tizen.NUI/src/public/Window/IBorderInterface.cs
BorderHeight is the default setting.
After the initial height is set as the BorderHeight value, the user can set the height of the border as SizeHeight.
- ACR:
> [NUI] Allows user to set the height of the top and bottom borders respectively

- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
Horizontal/VerticalAlignment of TextLabelBindableProperty calls
GetValueByDescription to convert DALi property to NUI property.
To improve performance, GetValueByDescription in TextLabel Alignment has
been replaced with string compare.
- ACR:
> [NUI] Replace GetValueByDescription in TextLabel Alignment

- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- Until now, `ValueChanged` event emits on Touch / Mouse moving.
- Update to invoke the event when the thumb moves
with not only touch event but also key event.
- N/A
> [NUI] Fix to invoke ValueChanged event when changing the value to Key

- src/Tizen.NUI/src/public/Window/Window.cs
[NUI] Fix Key constructor's `cMemoryOwn` as false
- dali returns `Key` or `Touch`'s `IntPtr`and dali keeps and maintains the `Key` or `Touch`'s instance so the nui's wrapping `Key` class should not `delete` or not `free` the `IntPtr`
- `cMemoryOwn = true` causes native crash, so it needs be fixed as `false`
none
> [NUI] Fix Key constructor's cMemoryOwn as false

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
- src/Tizen.Applications.Common/Tizen.Applications/CoreTask.cs
This request is for UIThread model. To get the result from the Post() method asynchronously, Post() methods are added.
Added [internal]:
- async Task<T> CoreApplication.Post<T>(Func<T> runner);
- async Task<T> CoreTask.Post<T>(Func<T> runner);
> Add new internal APIs for UIThread model

- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
Due to the track touch didn't apply offset of track,
the track touch didn't make correct value.
This patch apply the offset of bg track to the touch position.
Now the positions become correct value.
- ACR:
> [NUI] Slider track make correct value.

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
- src/Tizen.NUI/src/public/Window/IBorderInterface.cs
When in overlay mode, the border layer is raised to the top.
In this case, a touch is received from the border layer, and the touch event is not received from the lower root layer.
So let's pass the hittest of the border layer.
> [NUI] If window is in overlay mode, pass the hittest so that the lower layer can be hit.

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SwitchSample.cs
- test/Tizen.NUI.StyleGuide/Examples/SwitchExample.cs
[NUI] Fix not to use PROFILE_MOBILE
- remove 'PROFILE_MOBILE` macro. (can cover all profiles)
- tested locally and checked to run normally on RPI4, TV, and Ubuntu.
none
> [NUI] Fix not to use PROFILE_MOBILE

- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
- src/Tizen.NUI.Components/Tizen.NUI.Components.preload
[NUI] Fix not to do NUI.Components preloading on TV target
- NUI.Components preloading is not required in TV target because TV doesn't use NUI.Components.
- change Preload() method from Control class' to DefaultThemeCreator class'.
- tested in tv target and checked it works normally.
none
> [NUI] Fix not to do NUI.Components preloading on TV target

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableFocus/ScrollableFocusAllChildrenSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableFocus/ScrollableFocusNoneChildrenSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableFocus/ScrollableFocusSparseChildrenSample.cs
fix several issue on focus of scrollableBase.
1. fix wrong focus fallback when next focused children is invisble.
- if current focused object is children of scrollableBase,
keep focus to current focused object.
- if current focused object is out of scrollableBase,
to keep focus within the scrollableBase, set focus on scrollableBase.
2. fix wrong next focus returns on next find failed case.
if next focus find is failed, we can move scroll when key can move
foward and backward only not other directions.
In other direction inputs, escape the scrollableBase.
3. fix wrong escape condition of EOS(end of scroll).
we escape scrollableBase in EOS, but we need to reached EOS firstly,
and escape scrollableBase on next key input to move out.
4. add conditional debugging log.
5. fix focus samples.
add …
> [NUI] Fix scrollableBase focus issue.

- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI/src/internal/Interop/Interop.PanGestureDetector.cs
- src/Tizen.NUI/src/public/Events/PanGestureDetector.cs
When event spend so long time, a lot of events are queued.
Ecore cannot skip these event, so we make some heuristic
threshold of discard motion events on pan gesture.
Default age is UINT_MAX ms, (~= 49 days)
Currently, we make maximum age as hard-coded value
in NUI.Component.Slider.Internal
These patches are required to be merged :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/276378/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/276380/
- ACR:
> [NUI] Add maximum motion age of pan motion gesture

- src/Tizen.NUI.Components/Controls/Slider.cs
Previous code can move only 1 units when we try to change value
by Key event.
This patch make the value moved for 1%. It will change as same rates
even min/max value difference is big, or small.
TODO : Currently, we make it as const value 1%.
Should we need to make this value as property?
> [NUI] Make the velocity of slider as 1% at key event

- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
1. Use IsSet to replace changedPropertiesSet
- ACR: None
> [NUI] Use IsSet replace changedPropertiesSet

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Window/Window.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest.cs
It is to set the maximized size when window is maximized or the size is increased by RequestResizeToServer.
Although the limitation is set by this function, window's size can be over the limitation by SetPositionSize() or SetSize().
The Set minimum size is similar to set maximum size.
Also it is only useful for tizen world.
> [NUI] Add function to set maximum/minimum size

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextEditor.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextField.cs
Signed-off-by: Shrouq Sabah s.sabah@samsung.com
- TextField
-  PrimaryCursorPosition{ get; set; }      // Property
- TextEditor
-  PrimaryCursorPosition{ get; set; }    // Property
- ACR: TCSACR-482
- https://code.sec.samsung.net/jira/browse/TCSACR-482
> [NUI][TCSACR-482] Make PrimaryCursorPosition property public

- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
Public open API of SelectionStarted
- TextField: event EventHandler SelectionStarted
- TextEditor: event EventHandler SelectionStarted
- ACR: TCSACR-484:
https://code.sec.samsung.net/jira/browse/TCSACR-484
> [NUI] [TCSACR-484] Make SelectionStarted event public

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Window/WindowEvent.cs
Intercepts KeyEvents in the window before dispatching KeyEvents to the View.
If a KeyEvent is consumed, no KeyEvent is delivered to the View.
```c#
Window win = NUIApplication.GetDefaultWindow();
win.InterceptKeyEvent += OnInterceptKeyEvent;
private bool OnInterceptKeyEvent(object sender, Window.KeyEventArgs e)
{
return false;   //If it returns true, other views and windows do not receive KeyEvents.
}
```
> [NUI] Add InterceptKeyEvent

- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
When hiding the overlaid border, the timer is also initialized.
If the timer is not initialized, the border will not be visible when OverlayBorderShoew is performed again while the timer is alive.
> [NUI] When hiding the overlaid border, the timer is also initialized.

- src/Tizen.Applications.Common/Tizen.Applications/TizenSynchronizationContext.cs
- src/Tizen.Applications.Common/Tizen.Applications/TizenUISynchronizationContext.cs
To dispose ManualResetEvent handle after it is used, using is used.
- ACR:
> [Applications.Common] Use using to dispose ManualResetEvent handle

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Menu.cs
- src/Tizen.NUI.Components/Controls/Pagination.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityProperties.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
Having a modifiable attribute dictionary in NUI removes the performance penalty of having to go through interops on every modification. A new override for `GetAttributes` in `NUIViewAccessible` will now collect the attributes stored in NUI (through `AccessibilityDelegate.GetAttributes`). Moreover, the `class` attribute is now calculated lazily in order to reduce the creation cost of `View`.
Merge together with (ABI change):
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/277288/
- ACR: None
> [NUI][AT-SPI] Store AccessibilityAttributes in NUI

- src/Tizen.NUI/src/public/Images/NativeImageQueue.cs
Due to the endian problem, RGBA8888 use Blue Green Red Alpha as byte order.
So, We make another enum as BGRA8888 which matched as byte order.
TODO : Until other library fixed, RGBA and BGRA will show same result.
It will be fixed some days
> [NUI] Add NativeImageQueue.ColorFormat for BGR~~~

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Due to the LazyUpdate for ImageView's property,
sometimes ResourceReady signal comes even resource is not ready.
This patch make if we have some LazyUpdate properties, skip current signal
and wait next valid ResourceReady signal
> [NUI] Delay old ResourceReady signal

- src/Tizen.NUI/src/public/Theme/DefaultThemeCommon.cs
NUI TextLabel no longer use dali-theme.
So set default values in NUI theme.
This values are the same as the values in prev dali-theme.
> [NUI] set default value for AutoScroll in TextLabel

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
For windows launched in full size, we need to calibrate the window as much as the border size for Maximized to work well.
Otherwise, the border area will be located outsize of screen.
- ACR:
> [NUI] Fixed border behavior of windows launched at full size

- packaging/csapi-tizenfx.spec
- packaging/csapi-tizenfx.spec.in
To depend on the latest dali2-csharp-binder, dali2-csharp-binder is
added to BuildRequires in spec.
- ACR:
> [Build] Add dali2-csharp-binder to BuildRequires

- src/Tizen.NUI/src/internal/Interop/Interop.PropertyValue.cs
- src/Tizen.NUI/src/public/Common/PropertyValue.cs
- test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/TSPropertyValue.cs
Add operation to compare the value of PropertyValue.
> [NUI] PropertyValue.EqualTo()

- src/Tizen.NUI.Components/Properties/AssemblyInfo.cs
- src/Tizen.NUI.Extension/Properties/AssemblyInfo.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/CompiledConverters/BindablePropertyConverter.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/SetPropertiesVisitor.cs
src/Tizen.NUI.XamlBuild/src/public/XamlBuild/SetPropertiesVisitor.cs
before:
yield return Instruction.Create(OpCodes.Callvirt, module.ImportPropertySetterReference((NUIXamlCTask.bindingAssemblyName, NUIXamlCTask.**bindingNameSpace**, "BindingExtension"), propertyName: "TypedBinding"));
after:
yield return Instruction.Create(OpCodes.Callvirt, module.ImportPropertySetterReference((NUIXamlCTask.bindingAssemblyName, NUIXamlCTask.**xamlNameSpace**, "BindingExtension"), propertyName: "TypedBinding"));
_BindingExtension 's name space is Tizen.NUI.Xaml, not Tizen.NUI.Binding, or will throw "error : Value cannot be null. (Parameter 'type')"_
=====================
src/Tizen.NUI.XamlBuild/src/public/XamlBuild/CompiledConverters/BindablePropertyConverter.cs
line 60:
before:        || …
> [NUI][XamlBuild] Fix issues of xamlbuild.

- src/Tizen.NUI/src/internal/Common/DebugFileLogging.cs
- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] fix the defect that an wrong image is shown when async loading of the AnimatedVectorImageView
- AnimatedVectorImageView has been added as hidden APIs for GBM usage only.
- `TotalFrame` is NOT read sometimes when the async loading of the Lottie file takes long time.
- remove the part of using `TotalFrame` where `TotalFrame` is not read properly.
- done the test locally in GBM target.
none
> [NUI] fix the defect that an wrong image is shown when async loading of the AnimatedVectorImageView

- src/Tizen.NUI/src/internal/Utility/ColorCutQuantizer.cs
Fix crash issue when user want to analyze 4ch image
no API Changes
> [NUI] Palette: Add an exception for 4ch(ARGB) image processing

- src/Tizen.Log/Tizen/Log.cs
This enhances speed up to 5x faster than using library functions when
it comes to a burst call.
Signed-off-by: Youngjae Cho <y0.cho@samsung.com>
- ACR:
> Replace getting filename with a primitive way

- src/Tizen.Log/Tizen/Log.cs
This enhances speed up to 5x faster than using library functions when
it comes to a burst call.
Signed-off-by: Youngjae Cho <y0.cho@samsung.com>
- ACR:
> [Tizen.Log] Replace getting filename with a primitive (fast) way

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
- src/Tizen.NUI.Components/Controls/SelectButton.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- test/Tizen.NUI.StyleGuide/Examples/DefaultLinearItemExample.cs
Previously, IsSelected property was not changed when its ControlState
was changed between Normal and Selected.
Now, IsSelected property is also changed when ControlState is changed.
So, SelectedChanged event's IsSelected is synchronized with its look.
- ACR:
> [NUI] Fix to change IsSelected when ControlState is changed

- src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityProperties.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
Due to an oversight in https://github.com/Samsung/TizenFX/pull/4389, the `automationId` attribute disappeared from the AT-SPI tree for some `View`s, causing multiple regressions in Aurum tests. This PR fixes this bug.
The `"automationId"` key set in `AccessibilityAttributes` is ignored for controls not backed by a `NUIViewAccessible` (e.g. `BaseComponents`, `FluxView` etc.), because `NUIViewAccessible::GetAttributes` is never called for such controls. The value of `AutomationId` should be propagated to `dali-toolkit` instead, so that is it visible to `ControlAccessible::GetAttributes`, therefore having an effect for all types of `View`s (`NUIViewAccessible::GetAttributes` calls `ControlAccessible::GetAttributes` first, and then collects any additional attributes stored in …
> [NUI] Propagate AutomationId value to DALi

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
currently we do not check item can be moved focus to next candidate,
so when scrollableBase is non-scrollable,
it directly move next object not the item.
here I add to next focusable item existence.
note : this code makes unfocusable in none-focusable - non-scrollable case,
but not sure we can call normal behavior.
need to more discuss about this.
- ACR:
> [NUI] fix ScrollableBase focus moving bug on non-scrollable case

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
1. Make the Border property updatable.
For now, it only applies when set in the constructor.
Modify so that the property can be applied when the property is set again.
2. revert "https://github.com/Samsung/TizenFX/pull/4398"
> [NUI] Add UpdateProperty() api and revert "Fixed border behavior of windows launched at full size" patch

- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
[NUI] fix AnimatedVectorImageView's current frame set defect
- AnimatedVectorImageView is hidden API and used only for VD
- CurrentFrame should be possible to set at out of the min/max range
- The CSFS's setting icon should be white color outline when losing the focus => this is fixed
none
> [NUI] fix AnimatedVectorImageView's current frame set defect

- src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
1. If the AllowOnlyOwnTouch property is true, view will only receive touch events that started from itself.
```c#
var view = new View()
{
AllowOnlyOwnTouch = true,
}
```
2. Add SetDefaultAllowOnlyOwnTouch(bool enable) in View
```c#
// If this is set to true, all views are created with AllowOnlyOwnTouch set to true.
View.SetDefaultiAllowOnlyOwnTouch(true);
```
dependency
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/276632/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/276656/
> [NUI] Add AllowOnlyOwnTouch property and SetDefaultAllowOnlyOwnTouch api

- src/Tizen.NUI/src/public/WebView/WebView.cs
`Context` / `CookieManager` change to instance property
Why I change to instance property, It originally could be have a different value on each webview.
- ACR:
> [NUI] Fix API/ABI break on WebView

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
This determines whether touch events are emitted or not.
If DispatchTouchEvents is set to false
The View will not receive a TouchEvent and its parents will not receive the TouchEvent.
This works without adding a TouchEvent callback in the View.
> [NUI] Add DispatchTouchEvents

- src/Tizen.NUI/src/internal/Application/NUIWidgetCoreBackend.cs
- src/Tizen.NUI/src/internal/Widget/WidgetApplication.cs
WidgetAppcation need to delete it's BaseHandle when it is termianted.
- ACR:
> [NUI] Call Dispose when WidgetApplication is terminated

- src/Tizen.NUI/src/public/Common/BaseHandle.cs
I got a exception if rhs of IsEquals was disposed 
``` 
E/STDERR  (12260): Unhandled exception. System.ArgumentNullException: Exception of type 'System.ArgumentNullException' was thrown. (Parameter 'Dali::BaseHandle const & type is null Inner Exception: FATAL: Exception e is null, numExceptionsPending : 0')
E/STDERR  (12260):    at Tizen.NUI.BaseHandle.IsEqual(BaseHandle rhs) in Tizen.NUI.dll:token 0x6000dd6+0xa
E/STDERR  (12260):    at Tizen.NUI.BaseHandle.op_Equality(BaseHandle x, BaseHandle y) in Tizen.NUI.dll:token 0x6000dc6+0x29
```
This PR fixes it
- ACR:
> [NUI] Fix IsEqual

- src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
Change the property name and the type to Vector4 to support offset also
- ACR:
> [NUI] (Partial Update) Change UpdateSizeHint to UpdateAreaHint

- src/Tizen.Multimedia.Remoting/WebRTC/WebRTCSignalingEventArgs.cs
- src/Tizen.Multimedia.Remoting/WebRTC/WebRTCSignalingServer.cs
- Common : Remove useless <since_tizen> tag for internal APIs
- Client : Connect to SignalingServer when Connect() method is called and return its ID.
> [WebRTC] Change private SignalingServer/Client internal APIs

- src/Tizen.NUI/src/public/Widget/WidgetView.cs
When WidgetView uses its callback, WidgetView gets a crash problem because of referencing object.
To avoid this problem, WidgetView uses ManageBadeHandle.
- ACR:
> [NUI] Modify GetWidgetViewFromPtr to use ManagedBaseHandle

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
Registering the FocusChanged event at the time of OnCreate only in the emulator causes a crash.
Temporarily use InterceptTouchEvents until emulator problem is fixed.
This is a patch that will be reverted back once the emulator fix is ​​complete.
- ACR:
> [NUI] Temporarily use InterceptTouchEvent instead of FocusChanged.

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
This PR adds if conditions for registering the GC timer.
If the LowMemoryStatus of the LowMemoryEventArgs of the OnLowMemory is
SoftWarning or HardWarning, the timer will be registered.
> [Applications.Common] Fix OnLowMememory

- src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
- src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
There was some mis-bind API and typo error in FrameUpdateCallbackInterface.cs.
This patch fix this error, and also some API (like BakeColor, GetColor)
bind correctly.
> [NUI] Fix typo & bind error at FrameUpdateCallbackInterface

- src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
- src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
There was some mis-bind API and typo error in FrameUpdateCallbackInterface.cs.
This patch fix this error, and also some API(like BakeColor, GetColor)
bind correctly.
> [NUI][API9] Fix typo & bind error at FrameUpdateCallbackInterface

- src/Tizen.NUI/src/internal/Interop/Interop.AccessibilityManager.cs
- src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
- src/Tizen.NUI/src/public/Accessibility/AccessibilityManagerEvent.cs
- In Accessibility, One finger double tap and hold gesture is to pass
the event to the application.
- For the application, it can get the signal using
ActionForward event.
- Dependencies :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/278951/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/278952/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/278953/
- N/A
> [NUI] Add ActionForward event for Accessibility

- src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
- src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
This patch changes ModelView class to Model class.
And, unnecessary APIs have been removed.
And, default value of pivotPoint and parentOrigin of the Model are set to Center.
- ACR:
> [NUI] Changes ModelView to Model

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
Marshal's bool is mapped to 4byte in default.
So if native-code return boolean type, the datasize is mismatched and make problems
This patch will fix this problem
- ACR:
> [NUI] Make sure that Interop return type is bool

- src/Tizen.NUI/src/public/Widget/WidgetView.cs
HandleControlStateOnTouch is overridden by WidgetView with return value
true not to propagate touch event to the below.
- ACR:
> [NUI] Make WidgetView not propagate touch event to the below

- src/Tizen.NUI/src/public/Window/WindowEvent.cs
When user add window.FocusChanged in emulator it crashes.
So changed from StdCall to Cdecl at WindowFocusChangedEventCallbackType
- ACR:
> [NUI] Changed from StdCall to Cdecl at WindowFocusChangedEventCallbackType

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
- src/Tizen.NUI/src/public/Window/IBorderInterface.cs
[NUI] Added API to know when border window starts moving and ends moving
```c#
public virtual void OnRequestMove() {}
public virtual void OnMoved(int x, int y) {}
```
> [NUI] Added API to know when border window starts moving and ends moving

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
Changing the BorderView's SizeHeight should also change the Window size.
For this, we add an UpdateProperty() api.
> [NUI] Add UpdateProperty api for BorderWindow

- src/Tizen.NUI/src/internal/Interop/Interop.WebHttpRequestInterceptor.cs
- src/Tizen.NUI/src/internal/WebView/WebHttpRequestInterceptor.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WebViewInterceptTest.cs
- test/Tizen.NUI.WebViewTest/SimpleWebViewApp.cs
This patch is to add a new API for getting WebView in which http request is intercepted.
And it depends on the patch in csharp-binder:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/278806/
- ACR:
> [NUI] Add an API for getting web view when request is intercepted.

- packaging/csapi-tizenfx.spec
- packaging/csapi-tizenfx.spec.in
- Fix csapi-tizenfx.spec to enable aarch64 build
> [Build] Enable aarch64 build for API8

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
[NUI] Use FocusChanged in BorderWindow because it fixed an issue with Emulator's FocusChanged.
refer https://github.com/Samsung/TizenFX/pull/4498
> [NUI] Use FocusChanged in BorderWindow because it fixed an issue with Emulator's FocusChanged.

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
When the window is full size, the content area should be full size. So it makes the border line disappear.
When it becomes partial size again, the border line is visible.
- ACR:
> [NUI] Border lines make the window invisible when maximized.

- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
Content's height is calculated correctly after AppBar's height is
calculated.
Therefore, AppBar is measured and then Content is measured.
- ACR:
> [NUI] Fix ContentPageLayout to measure AppBar prior to Content

- test/NUISettings/NUISettings/NUISettings.cs
- test/NUISettings/NUISettingsReset/NUISettingsReset.cs
To pass data between Widgets, data is passed from Widget to Main app and
Main app passes the data to another Widget.
Since this is difficult to support, NUISettings guides how to use
Navigator in Widget.
By using Widget's own Navigator, Widget knows its Navigator and its
Pages. So Widget can pass data between its Pages easily.
- ACR:
> [NUI] Update NUISettings to guide how to use Navigator in Widget

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
- test/Tizen.NUI.StyleGuide/Examples/OutlinedButtonExample.cs
- test/Tizen.NUI.StyleGuide/Examples/TextOnlyButtonExample.cs
The latest Tizen 7.0 UX introduces Outlined and TextOnly style Buttons.
Outlined style Button has transparent background and colored borderline.
TextOnly style Button has a text and transparent background.
- ACR:
> [NUI] Add Outlined and TextOnly Button styles

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewSelectorData.cs
To support Selector<Color> for BorderlineColor, BorderlineColorSelector
has been added.
BorderlineColorSelector is applied to Outlined Button style.
- ACR:
> [NUI] Add BorderlineColorSelector to ViewStyle

- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
If touchData is null, GetTouchFromPtr throws an exception.
- ACR:
> [NUI] prevent the case when touchData is null

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
According to the test result about calling GC.Collect(), it mostly takes 100 ms.
This PR removes the GC timer. 
- ACR:
> [Applications.Common] Remove GC Timer from OnLowMemory()

- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
The typo in BorderlineColorSelectoryProperty has been fixed. This typo causes crash by the following test code.
var slider = new Slider();
var style = slider.Style;
- ACR:
> [NUI] Fix typo in BorderlineColorSelectorProperty

- src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
Due to the Scene3D.SceneView's default camera didn't created in NUI side, we need to Regist this camera information into Registry.
If we already register it into Registry, use that.
Else, register new Camera into Registry.
> [NUI.Scene3D] Create and Register Scene3D.Camera

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
ViewStyle.BorderlineColorSelector did not work properly because View.BorderlineColorSelector property was not added.
Like BackgroundColor, color selector typed BorderlineColor should be used in ViewStyle only.
So View.BorderlineColorSelector is internally used only.
- ACR:
> [NUI] Fix ViewStyle.BorderlineColorSelector to work

- src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
- src/Tizen.NUI/src/public/Window/BorderWindow.cs
NULL dereference codes have been fixed.
- ACR:
> [NUI] Fix svace NULL dereference issues

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
- test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/TSView.cs
Previously, we can only change whole color components (RGBA) or change Opacity (A).
If we change only RGB values without change Opacity value, we need to get opacity property first, and make new Color().
To change each components without create new Color class, We make new property to change each components.
> [NUI] Add View.ColorRed / ColorBlue / ColorGreen Property

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
When return true, panGestureEvent is consumed.
When return false, panGestureEvent is propagated to the parent.
> [NUI] Modify the return value of OnAccessibilityPan()

- src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/EditorWindow.cs
- src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Signed-off-by: Jihoon Kim <jihoon48.kim@samsung.com>
[NUI][TCSACR-514] Deprecated some Inputmethod APIs related to ElmSharp
- TCSACR-514
> [Inputmethod] Deprecated some Inputmethod APIs related to ElmSharp

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Accessibiliy call OnPanGesture directly without check ScrollEnabled variable.
this patch fix to check ScrollEnabled value before sending OnPanGesture.
- ACR:
> [NUI] disable acessibilityPanGesture when scroll disabled.

- src/Tizen.NUI/Tizen.NUI.csproj
- src/Tizen.NUI/src/internal/Interop/Interop.Actor.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/Common/PropertyValue.cs
- src/Tizen.NUI/src/public/Window/Window.cs
[NUI] Change property get/set not to use PropertyValue
- this should be merged with https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/281975/
- this is the first patch and it will be continuously changed and modified.
- `NUI_PROPERTY_CHANGE_1` this macro will be deleted after all changes are completed.
- start with View and expand it to ImageView, Text, etc.
- local testing has been done on NikeM2 target.
none
> [NUI] Change property get/set not to use PropertyValue

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
BorderLineThickness should be taken into account when setting MimimumSize and MaximumSize.
If BorderLineThickness is not calculated, there will be a problem with window resize when it is reduced by MimimumSize.
> [NUI] BorderLineThickness should be taken into account when setting MimimumSize and MaximumSize.

- src/Tizen.Multimedia.Camera/Camera/EncodedPlane.cs
- src/Tizen.Multimedia.Camera/Interop/Interop.Camera.cs
By default bool in C# is marshaled as if there was BOOL on native side, which has 4 bytes size. 
So, type of EncodedPlaneStruct.IsDeltaFrame should be changed to byte.
> [Camera] Change bool to byte for 64bit union struct marshaling

- src/Tizen.NUI/src/internal/Common/ProcessorController.cs
Instead of register PostProcess,
We'd better invoke ProcessorOnceEvent one more time after LayoutProcessorEvent finished.
> [NUI] Remove useless PostProcess callback

- src/Tizen.Multimedia.Camera/Camera/CameraDeviceManager.cs
Remove wrong feature tag.
`CameraDeviceManager` is not related to camera feature directly.
> [Camera] Remove wrong feature tag

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Events/LongPressGestureDetector.cs
- src/Tizen.NUI/src/public/Events/PanGestureDetector.cs
- src/Tizen.NUI/src/public/Events/PinchGestureDetector.cs
- src/Tizen.NUI/src/public/Events/RotationGestureDetector.cs
- src/Tizen.NUI/src/public/Events/TapGestureDetector.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
This determines whether gesture events are emitted or not.
If DispatchGestureEvents is set to false, then itself and parents will not receive all gesture event signals.
If DispatchParentGestureEvents is set to false, then parents will not receive all gesture event signals.
> [NUI] Add DispatchGestureEvents and DispatchParentGestureEvents

- src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
- src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
NUI.Scene3D.Model don't have any method to access
it's children nodes. So, it will be always false now.
required DALi patches :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/280680/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/281062/
> [NUI.Scene3D] Add private property ChildrenSensitive

- src/Tizen.MachineLearning.Train/Tizen.MachineLearning.Train/Commons.cs
[MachineLearning.Train] Remove dot at the end of enum value description
- Remove dot at the end of enum value description
Signed-off-by: hyunil park <hyunil46.park@samsung.com>
> [MachineLearning.Train] Remove dot at the end of enum value description

- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Rotation don't use Vector3. It use Quaternion internally.
> [NUI] Fix Rotation Property set/get usage

- src/Tizen.Applications.Service/Interop/Interop.Service.cs
- src/Tizen.Applications.Service/Tizen.Applications/ServiceApplication.cs
To exit the main loop without restarting, the method is added.
Adds:
- ServiceApplication.ExitWithoutRestarting()
> [Applications.Service] Add a new internal API

- src/Tizen.NUI/src/public/Window/WindowEvent.cs
[NUI] Change Window's events to follow View's event pattern
- remove warnings by delete unused variables
- SVACE self test (no defect): https://analysishub.sec.samsung.net/service/analyses/1618490#defects
none
> [NUI] Change Window's events to follow View's event pattern

- src/Tizen.NUI/src/internal/Common/RenderTask.cs
- src/Tizen.NUI/src/internal/Utility/Camera.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
[NUI][TCSACR-503] Camera class and CameraType enum, which are not used, are deprecated
https://code.sec.samsung.net/jira/browse/TCSACR-503
> [NUI][TCSACR-503] Camera class and CameraType enum, which are not used, are deprecated

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
- src/Tizen.NUI.Components/Controls/Pagination.cs
- src/Tizen.NUI.Wearable/src/public/RecyclerView/RecyclerView.cs
- src/Tizen.NUI/src/internal/EXaml/Operation/GetStaticObject.cs
- src/Tizen.NUI/src/internal/FrameBroker/DefaultFrameBroker.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/Common/Container.cs
Svace issues of dereferenced nullable variables have been fixed.
- ACR:
> [NUI] Fix Svace issues of dereferenced nullable variables

- src/Tizen.Multimedia.Remoting/WebRTC/MediaPacketSource.cs
- src/Tizen.Multimedia/MediaTool/MediaPacket.cs
Disable MediaPacket native handle destroy when Native FW destroys native media packet handle.
> [WebRTC] Disable MediaPacket native handle destroy

- coverage.sh
Support '--exclude-sources' option to exclude cs files from coverage result.
e.g.
```
TizenFx $ ./coverage.sh -i Tizen.Multimedia.Camera src/Tizen.Multimedia.Camera/Camera/CameraError.cs,src/Tizen.Multimedia.Camera/Camera/CameraException.cs
```
> [Coverage] Support --exclude-sources option

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/Layer.cs
When the view is unparented, the focus is not cleared. So, when app re-add the view and SetCurrentFocusView, app do not receiving the FocusGained event.
> [NUI] If the view had focus when it was unparented, the focus is cleared.

- src/Tizen.NUI.Components/Controls/Picker.cs
Expand default scroll area to support app requirment.
but we guide do not use more than 100 selections for picker.
Picker not designed for many items. it's not ListView.
Fix scroll area height calc logic
picker size -> itemHeight * 5
Picker size can change by user.
No API Changes
> [NUI] Picker: Fix scroll area height calc logic and Expand default scroll area

- src/Tizen.NUI/Tizen.NUI.csproj
- src/Tizen.NUI/src/internal/Interop/Interop.ActorInternal.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Window/Window.cs
[NUI] Change property get/set not to use PropertyValue (patch set4)
- this should be merged with https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/282909/
- NUI_PROPERTY_CHANGE_X this macro will be deleted after all changes are completed.
- local testing has been done on NikeM2 target.
none
> [NUI] Change property get/set not to use PropertyValue (patch set4)

- src/Tizen.NUI/src/internal/Common/Object.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
[NUI] Add null checking in InternalSet/GetPropertyXXX(), Change to use internalName
- make the InternalSet/GetPropertyXXX() same as the Object.PropertySet/Get() pattern.
- change for `View.Name` property to use `View.internalName`.
- tested locally with NikeM2 target
none
> [NUI] Add null checking in InternalSet/GetPropertyXXX(), Change to use internalName

- src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
[NUI] Add null checking in internalSet/GetPropertyXXX()
- Add null checking in internalSet/GetPropertyXXX() in ViewInternal, ImageViewBindableProperty and TextLabel/TextField/TextEditor BindableProperty.
- tested with NikeM2 locally
none
> [NUI] Add null checking in internalSet/GetPropertyXXX()

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
i### Description of Change ###
1. Linear Layouter get crashed when group has no children.
2. Linear, Grid Layouter update is not working well because delayed
update timer is not started.
3. remove spaces.
- ACR:
> [NUI] Fix Linear Layouter crash and update issue

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
- src/Tizen.Applications.Common/Tizen.Applications/CoreTask.cs
The static keyword is added to the methods.
The runner of the CoreApplication.Post() method will be delivered to the UI thread if the application uses the UI thread App Model. The runner of the CoreTask.Post() method will be delivered to the main thread.
> [Applications.Common] Modify Post method of CoreApplication and CoreTask

- test/NUIDnDSource/tizen-manifest.xml
- test/NUIDnDTarget/tizen-manifest.xml
- test/NUISettings/NUISettings/tizen-manifest.xml
- test/NUISettings/NUISettingsReset/tizen-manifest.xml
- test/NUITestSample/NUITestSample/tizen-manifest.xml
- test/Tizen.NUI.ComponentApplication/NUIComponentApplication/tizen-manifest.xml
- test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/tizen-manifest.xml
- test/Tizen.NUI.LayoutSamples/Tizen.NUI.LayoutSamples/tizen-manifest.xml
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/tizen-manifest.xml
- test/Tizen.NUI.SeamlessSamples/BrokerSample/tizen-manifest.xml
- test/Tizen.NUI.SeamlessSamples/ProviderSample/tizen-manifest.xml
- test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/tizen-manifest.xml
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/tizen-manifest.xml
- test/Tizen.NUI.UIThread/tizen-manifest.xml
- test/Tizen.NUI.WidgetViewTest/0.Template/Tizen.NUI.WidgetTest/tizen-manifest.xml
- test/Tizen.NUI.WidgetViewTest/0.Template/Tizen.NUI.WidgetViewTest/tizen-manifest.xml
- test/Tizen.NUI.WidgetViewTest/1.SendInfo/Tizen.NUI.WidgetTest/tizen-manifest.xml
- test/Tizen.NUI.WidgetViewTest/1.SendInfo/Tizen.NUI.WidgetViewTest/tizen-manifest.xml
- test/Tizen.NUI.WindowSystem.Samples/tizen-manifest.xml
NUI apps have to set dotnet-nui app type in tizen-manifest.xml. Then the apps are preloaded from dotnet-loader.
It improves the launching performance.
- ACR:
> [NUI] Apply dotnet-nui type

- src/Tizen.Applications.ThemeManager/Interop/Interop.ThemeManager.cs
- src/Tizen.Applications.ThemeManager/Tizen.Applications.ThemeManager/ThemeLoader.cs
Signed-off-by: Ilho Kim <ilho159.kim@samsung.com>
change return type of theme loader add event callback from void to int to match with c api.
it's for internal code.
- ACR:None
> [Applications.ThemeManager] Fix return type of theme loader add event callback for internal.

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
- test/NUITizenGallery/Examples/CollectionViewTest/CollectionViewObservableTestPage.xaml
- test/NUITizenGallery/Examples/CollectionViewTest/CollectionViewObservableTestPage.xaml.cs
After Item Insertion,
Previous index of visible item is not updated properly,
so unrealization goes wrong.
it fix visible indexes most cases except rangemove.
range move is to complex for re-calculate indexes,
so it unrealize every items and reset the visible item indexes.
- ACR:
> [NUI] Fix issue item is not unrealized after insertion.

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
DefaultLinearItem sometimes layouting text in wrong position and upadated later.
this issue occurs relativeLayouting is set after object relayout is done.
now it fix to set relativeLayout right after the chlidren generation.  
- ACR:
> [NUI] Fix relative layout issue on DefaultLinearItem

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
In ScrollableBase.Dispose(), propertyNotification is disposed as well. To dispose propertyNotification, RemovePropertyNotifications was called inappropriately and it caused crash.
To resolve the above, RemovePropertyNotification is called by ContentContainer with propertyNotification like AddPropertyNotification is called by ContentContainer with propertyNotification.
- ACR:
> [NUI] Fix crash on ScrollableBase.Dispose()

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/DefaultBorder.cs
1. Move the Transparency setting to OnMaximize().
2. Fixed the wrong condition when resizing.
3. backgroundImage and backgroundColor are exclusive.
So if the user has set the backgroundImage then the backgroundColor should not be reset.
4. BorderLineThickness can be changed dynamically.
> [NUI] 1. Move the Transparency setting to OnMaximize().

- src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
- src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
- src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs
To prevent the common language runtime from reclaiming memory used by a handle, this patch adds calling DangerousAddRef() before calling DangerousGetHandle().
> [Applications.Common] Increment the reference counter on SafeHandle instances

- src/Tizen.NUI.Components/Controls/Menu.cs
To help application to customize Menu, Menu's size calculation should be modified not to set its size to its Content's size.
- ACR:
> [NUI] Modify Menu to help customizing class

- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Menu.cs
- src/Tizen.NUI.Components/Controls/MenuItem.cs
- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Components/Controls/TabBar.cs
- src/Tizen.NUI.Components/Controls/TabContent.cs
- src/Tizen.NUI.Components/Controls/TabView.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
To customize and apply app's own style instance, constructor with style
instance should be added.
For now, ApplyStyle() modifies the given properties only based on the
default style unlike applying style in constructor.
e.g. Let default style contain properties A, B, C.
Let custom style contain properties B, C.
Then ApplyStyle(custom style) contain default style's A and custom
style's B and C.
Consequently, to apply custom style without applying default style,
constructor with style instance is required.
- ACR:
> [NUI] Add constructor with style instance

- src/Tizen.NUI/src/internal/Interop/Interop.Gesture.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TapGesture.cs
- src/Tizen.NUI/src/public/Events/Gesture.cs
- src/Tizen.NUI/src/public/Events/TapGesture.cs
This is similar to MouseButton in TouchEvent.
Now, you can see from which input the gesture was made.
```c#
longPressGestureDetector.Detected += (s, e) =>
{
if (e.LongPressGesture.Source == Gesture.SourceType.Mouse)
{
}
if (e.LongPressGesture.SourceData == Gesture.SourceDataType.MousePrimary)
{
}
}
```
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/283368/ 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/283369/
> [NUI] Add input source type to Gesture.

- src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
1. Add nullcheck when NUI_VISUAL_PROPERTY_CHANGE_1 not defined.
2. Fix compile error when NUI_ANIMATION_PROPERTY_CHANGE_1 not defined.
> [NUI] Fix some errors when we remove NUI_PROPERTY_CHANGE tag

- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Add lock() to WiFi API
- ACR: none
> [WiFi] Add lock to _callback_map

- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/Tizen.NUI.Devel.Tests.csproj
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Window/TSBorderWindow.cs
- test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Window/TSDefaultBorder.cs
- test/Tizen.NUI.Tests/nunit.framework/nunit.framework.csproj
Reason:
Did not implement interface member 'IBorderInterface.OnMoved(int, int).
Solution:
Implement the interface member.
- ACR:
> [NUI][NUI.Devel] Fix build errors of NUI.Devel.

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfo.cs
To prevent removing delegate objects by GC, this patch adds private member variables.
> [Applications.Common] Keep delegate objects

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
DF221104-01088
[Reported] Value ItemsLayouter, which is result of method invocation with possible null return value, is dereferenced in method call ItemsLayouter.CaculateLayoutOrientationSize()
Solution:
Add the null check operator '?.'
- ACR:
> [NUI][NUI.Components] Fix SVACE issue in CollectionView.

- src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
This PR don't make FocusableChildren as false in default. Now we can add focusable children under the Model as default.
> [API10][NUI.Scene3D] Remove useless default property setter on Model

- src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
This PR don't make FocusableChildren as false in default. Now we can add focusable children under the Model as default.
> [NUI.Scene3D] Remove useless default property setter on Model

- src/Tizen.NUI/src/internal/Application/Application.cs
- src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
- src/Tizen.NUI/src/internal/Application/NUIWidgetCoreBackend.cs
- src/Tizen.NUI/src/internal/Common/DeviceOrientationChangedSignalType.cs
- src/Tizen.NUI/src/internal/Interop/Interop.DeviceOrientationChangedSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WindowOrientationChangedSignal.cs
- src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
- src/Tizen.NUI/src/internal/Window/WindowOrientationChangedSignal.cs
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
- src/Tizen.NUI/src/public/Application/NUIWidgetApplication.cs
- src/Tizen.NUI/src/public/Window/WindowEvent.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowEventsTest.cs
- test/Tizen.NUI.UIThread/Tizen.NUI.UIThread.cs
Supporting  Device orientation and Window Orienation event when device orientation is changed or window orientation is changed. Window orientation event is emitted by display server. To emit the Window Orientation event, AddAvailableOrientation() or SetPreferredOrientation() should be called before the device is rotated. Otherwise, Device Orientation event is emitted by Application framework and any condition is not needed.
This PR should be sync merged with the below patches.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/283622/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/283830/
> [NUI] Support device and window orientation event

- src/Tizen.NUI/src/internal/Interop/Interop.Matrix.cs
- src/Tizen.NUI/src/public/Common/Matrix.cs
- src/Tizen.NUI/src/public/Common/Matrix3.cs
- test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/Program.cs
- test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/Common/TSMatrix.cs
- test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/Common/TSMatrix3.cs
Add and bind some matrix operator + remove useless items
And also, move this matrix class under public
so normal NUI Apps also can use this feature
Removed :
* AsFloat() : Due to ignore unsafe float point accesser.
Added :
* operator * override.
* MultiplyAssign (static Matrix.Multiply API cannot do something like this.)
* Value setter/getter by index (mat[9] == mat.ValueOfIndex(9) == mat.ValueOfIndex(1, 2). Set by mat.SetValueAtIndex(1, 2, 3.0f)
* Since NUI.Matrix system is column-major, we need to some help for App developer to know the row/column index.
More detail : https://github.com/dalihub/dali-core/blob/master/dali/public-api/math/matrix.h#L38-L58
TODO : Apply comments on this classes. It might be doing on another patches. …
> [NUI] Move Matrix API as public (hidden)

- src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
Adds CameraTransitionFinished signal to notice whether the Camera Transition is finished or not.
Signed-off-by: seunghobaek <sbsh.baek@samsung.com>
- ACR:
> [NUI] Add CameraTransitionFinished in SceneView

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/TextEditorStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- src/Tizen.NUI/src/public/Theme/DefaultThemeCommon.cs
Setting FontSizeScale to UseSystemSetting in Theme, the default font scale follows the properties of system.
- Added new argument to New(bool hasStlye)
- If true, DALi's json is no longer used in Text components
- If false, use DALi's json.
- Fixed previous incorrect bindable property structure.
- This must be sync merged with patches below.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/284113/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/284127/
> [NUI] Add FontSizeScale in TextStyle

- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageViewBindableProperty.cs
[NUI] fix to be able to set null to AnimatedVectorImageView.ResoureUrl property
none
> [NUI] fix to be able to set null to AnimatedVectorImageView.ResoureUrl property

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
If we create empty group it gets crash and moreover,
if we add more items in the group item didn't show correctly.
this patch will fix by re-initialize when new item added.
- ACR:
> [NUI] Fix Layouter to handle empty group case.

- src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
- To do not cull fragments during camera transition
Signed-off-by: seungho baek <sbsh.baek@samsung.com>
- ACR:
> [NUI] Use smaller NearPlaneDistance and bigger FarPlaneDistance during Camera Transition

- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageType.cs
ToLower can cause unexpected error when system is busy.
- ACR: N/A
> [Packagemanager] Use ToLowerInvariant instead of ToLower

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
when Nth empty item group is removed,
we didn't restore parentIndex while searching group item,
so N+1 group is not updated, as it changed Nth.
- ACR:
> [NUI] fix group remove error.

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
Previously, pages order was not kept correctly when a page was inserted. Because of that, inserted page overlaps the next page's page transition. e.g.
- Let page1 be pushed.
- Let page2 be inserted before page1.
- Pop page1. Then page1's page transition is hidden by page2 because page2 is added later so page2 overlaps page1.
Now, to resolve the above issue, the order of the inserted page is updated based on its page index value.
- ACR:
> [NUI] Fix Navigator Insert to keep pages order correctly

- src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- src/Tizen.NUI.Components/Utils/NUIWindowExtensions.cs
- test/NUITizenGallery/NUITizenGallery.cs
- test/Tizen.NUI.StyleGuide/Examples/NavigatorExample.cs
- test/Tizen.NUI.StyleGuide/Tizen.NUI.StyleGuide.cs
To support back navigation, EnableBackNavigation and OnBackNavigation of Navigator and Page are added.
Moreover, for better usage, back navigation has been modified as follows.
If navigator has more than one page, then the peek page is popped when back navigation proceeds.
Otherwise, the current program is exited when back navigation proceeds.
- ACR:
> [NUI] Support back navigation

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfo.cs
Recently, as the callback is changed to a member variable, it is overwritten when the callback is a race condition.
This patch solves this by adding lock.
> [Applications.Common] Fix race condition issue

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
A popped page is removed in the Pop() animation's Finished callback.
Previously, Navigator could not support multiple Pop().
Because Pop() simply stopped the previous Pop() animation without
calling the animation's Finished callback.
Now, Pop() stops the previous Pop() animation with calling the
animation's Finished callback by emitting FinishedSignal().
Consequently, Navigator can support multiple Pop() now.
- ACR:
> [NUI] Fix Navigator to enable multiple Pop()

- src/Tizen.NUI/src/internal/Interop/Interop.FontClient.cs
- src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
- src/Tizen.NUI/src/public/Theme/DefaultThemeCommon.cs
- src/Tizen.NUI/src/public/Utility/FontClient.cs
user can get a list of system fonts
sample code:
https://github.com/wonrst/NUI-Test/blob/main/text-font-list/font_list.cs
dali-csharp-binder:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/284941/
> [NUI] Add GetSystemFonts in FontClient

- src/Tizen.NUI/src/internal/Application/Application.cs
- src/Tizen.NUI/src/public/Common/StyleManager.cs
[NUI] FocusIndicator is not used in TV profile so it can be removed to reduce launching delay
none
> [NUI] FocusIndicator is not used in TV profile so it can be removed to reduce launching delay

- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
When view's size animated, the DALi known size and NUI stored size (mean, userSizeWidth and widthPolicy like) will not be matched.
If NUI use fixed size policy (mean, It "May" not use NUI.Layout system so can use animation feature.) Let we make NUI keep dali-side size's information and keep it.
- ACR:
> [NUI][API10] Animated view's size cache into NUI

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
We don't need to change the width value when we try to set the height. Also, widthPolicy might not matched with SizeWidth when we use NUI.Animation
- ACR:
> [NUI] Fix WidthSpecification and HeightSpecification not to set Size2D

- src/Tizen.NUI/src/internal/Common/Registry.cs
- src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
This reverts commit 0017dd0e49ffbc78d8c51c6f068afd6e8fdbc8d0.
- the root cause of this defect was VirtualRemote App had misused BaseHandle.Reset()
- BaseHandle.Reset() will be deprecated because it is not proper for nui. (it resets native dali BaseHandle's ref count)
none
> Revert "[NUI] fix the defect that the focus of VitualRemote App is stuck very rarely"

- src/Tizen.NUI/src/internal/Layouting/RelativeLayout.cs
Currently RelativeLayout only fill the children when its size is smaller than parent area.
the patch fix to fill regardless of children size.
- ACR:
> [NUI] fix relative layout to fill regardless of children size.

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItemBindableProperty.cs
Add ImageUrl Property on DefaultGridItem.
DefaultGridItem Image is readonly property,
so in XAML ResourceUrl is unaccessible.
this patch will fix those issue by directly binding resourceUrl on ImageUrl of DefaultGridItem.
- ACR:
> [NUI] add ImageUrl property on DefaultGridItem.

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
DefaultGridItem need to fill image on availableArea by default.
- ACR:
> [NUI] fix DefaultGridItem image to fill available area.

- src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
- src/Tizen.NUI/src/public/Animation/Animation.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
This patch allows to access to the child Actor of View to animate Properties.
e.g., animation.AnimateTo(bicycle.FindChildAnimatableByName("soundbar_off"), "positionY", -50);
- ACR:
> [NUI] Support sub node's Animation

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/AlertDialogBindableProperty.cs
- test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestDialogPage.xaml
- test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestDialogPage.xaml.cs
- test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestPage.xaml
- test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestPage.xaml.cs
To support Actions property of AlertDialog in xaml, the bindable property ActionsProperty has been added to AlertDialog.
The AlertDialog example with xaml has been added to NUITizenGallery.
- ACR:
> [NUI] Add ActionsProperty to AlertDialog to support xaml

- src/Tizen.NUI/src/internal/Interop/Interop.BaseHandle.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] make BaseHandle.Reset() not work
- this came from native dali and it is not suitable for nui.
- it makes BaseHandle's reference count as 0, but this action could cause memory leak in nui side.
- in nui side, calling Dispose() explicitly or doing nothing to delegate disposing action to the DisposeQueue is recommended.
none
> [NUI] make BaseHandle.Reset() not work

- src/Tizen.NUI/src/public/Animation/Animatable.cs
Added SetProperty method to change its property, for the children those are not created in NUI. (e.g., Dali::Actor).
Signed-off-by: seungho baek <sbsh.baek@samsung.com>
- ACR:
> [NUI] Support SetProperty by using string name for Animatable

- src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
[NUI] Add Enable/DisableDirectInputEvent() and GetRenderThreadId() as hidden API
- dependencies : 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/286016/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/286010/
none
> [NUI] Add GetRenderThreadId() as hidden API

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- test/NUITizenGallery/Examples/CollectionViewTest/AnimalGridPage.xaml
- test/NUITizenGallery/Examples/CollectionViewTest/AnimalListPage.xaml
- test/NUITizenGallery/Examples/CollectionViewTest/Animals.cs
In SelectionChangedCommand,
SelectionChangedCommandParamater is the only accessible value for changing selection.
if user sets SelectionChangedCommandParamater to SelectedItem of CollectionView,
Parameter will be updated after SelectedItemProperty is updated,
So SelectionChangedCommand which calls in the SelectedItemProperty,
cannot get updated SelectedItem value.
Here is a simple solution for that.
If nothing exist in SelectionChangedCommandParameter,
CollectionView will pass SelectionChangedEventArgs by default.
So user can get PreviousSelection and CurrentSelection in the model.
This change makes the model dependent on SelectionChangedEventArgs,
which I wish to avoid but we don't have a proper solution for now.
- ACR:
> [NUI] Pass SelectionChangedEventArgs by default as SelectionChangedCommandParameter.

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
This allows the user to know scrollable object scroll is started or finished.
Requires:
https://review.tizen.org/gerrit/284124/
https://review.tizen.org/gerrit/284126/
> [NUI] Add EmitScrollStartedEvent and EmitScrollFinishedEvent

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- test/Tizen.NUI.StyleGuide/Examples/DialogAndAlertDialogExample.cs
Previously, the measured size of FlexLayout with WrapContent could be calculated like MatchParent.
The above issue happened in the following case.
Tizen.NUI.Components.DialogPage.ShowAlertDialog("Title", "Message", null);
To resolve the above issue without breaking backward compatibility, FlexLayout OnMeasure has been fixed to use ResolveSizeAndState() instead of GetDefaultSize() when calculating the measured size.
To test the issue, showing a dialog without action button case has been added to Tizen.NUI.StyleGuide.
- ACR:
> [NUI] Fix FlexLayout OnMeasure to calculate size correctly

- src/Tizen.NUI/src/internal/Interop/Interop.BaseHandle.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
Now HasBody() become false during DeleteBaseHandle() emitted signals
> [NUI][API10] Reorder DeleteBaseHandle and SwigCPtrCopy = null;

- src/Tizen.NUI/src/internal/Interop/Interop.BaseHandle.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
Now HasBody() become false during DeleteBaseHandle() emitted signals
> [NUI] Reorder DeleteBaseHandle and SwigCPtrCopy = null;

- src/Tizen.Applications.Common/Interop/Interop.AppControl.cs
- src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
This patch adds the API below to set the timeout interval when sending an app launch request.
Adds:
- `AppControl.SendLaunchRequest(appControl, timeout)`
- `AppControl.SendLaunchRequest(appControl, timeout, replyAfterLaunching)`
> [Applications.AppControl] Add new internal APIs

- src/Tizen.NUI/src/internal/Application/Application.cs
- src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
- src/Tizen.NUI/src/internal/Application/NUIWidgetCoreBackend.cs
- src/Tizen.NUI/src/internal/Common/DeviceOrientationChangedSignalType.cs
- src/Tizen.NUI/src/internal/Interop/Interop.DeviceOrientationChangedSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WindowOrientationChangedSignal.cs
- src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
- src/Tizen.NUI/src/internal/Window/WindowOrientationChangedSignal.cs
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
- src/Tizen.NUI/src/public/Application/NUIWidgetApplication.cs
- src/Tizen.NUI/src/public/Window/WindowEvent.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowEventsTest.cs
- test/Tizen.NUI.UIThread/Tizen.NUI.UIThread.cs
Supporting  Device orientation and Window Orienation event
when device orientation is changed or window orientation is changed.
Window orientation event is emitted by display server.
To emit the Window Orientation event, AddAvailableOrientation()
or SetPreferredOrientation() should be called before the device is rotated.
Otherwise, Device Orientation event is emitted by Application framework
and any condition is not needed.
> [NUI] Support Device orientation and window orientation event.

- src/Tizen.Applications.PackageManager/Interop/Interop.PackageManager.cs
- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Adds:
- ClearUserData(packageId, filePath)
PackageManager has an API that removes all user data from a specific package.
There is a requirement to remove only certain file or directory
Data management becomes more detailed because only specific data can be removed by adding this API.
- ACR: TCSACR-522
> [Applications.PackageManager] Add ClearUserData(package, path)

- src/Tizen.NUI/src/public/Common/Container.cs
- test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/TSImageView.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs
Previous Container.cs can dispose recursively only if it is created by xaml. (DisposeIncludeChildren)
And also, that API only for internal.
Now we add some useful API that user can dispose all connected children recursively by one button.
```
View a = new View();
View b = new View();
a.Add(b);
a.DisposeRecursively();
// Now both a and b are disposed.
```
Signed-off-by: Eunki Hong <h.pichulia@gmail.com>
> [NUI] Add method to DisposeRecursively. + Fix DisposeTest demo works

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/public/WebView/WebView.cs
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/285622/
- ACR:
> [NUI] Add an API for create,window event.

- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/NUIXamlCTask.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlGenerator.cs
Fix conflicts of PR:4825
==========
During the task of replace Xamarin.Forms with NUI.Xaml of Tizen-CSharp-Samples, The samples' namespace always contains "Tizen", and we would got the error : "NUI" could not be found in Tizen. The solution is, add global when constructing related parameters, such as ：
new CodeAttributeDeclaration(new CodeTypeReference($"global::{NUIXamlCTask.xamlNameSpace}.XamlFilePathAttribute"),
- ACR:
> [NUI][XamlBuild] Fix namespace confused issue. 

- src/Tizen.NUI/src/public/Common/BaseHandle.cs
[NUI] remove swigCPtrCopy which is useless
- tested locally with "test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs"
none
> [NUI] remove swigCPtrCopy which is useless

- src/Tizen.NUI/src/public/Images/EncodedImageBuffer.cs
- src/Tizen.NUI/src/public/Images/NativeImageQueue.cs
- src/Tizen.NUI/src/public/Images/NativeImageSource.cs
- src/Tizen.NUI/src/public/Images/PixelBuffer.cs
- src/Tizen.NUI/src/public/Images/PixelData.cs
Since they were BaseHandle, there was some Fatal log printed when we try to use them at worker thread.
For example, PixelBuffer buffer = ImageLoader.LoadImageFromFile() was invalid.
This patch make them as Disposable.
So they will not be registed into Registry.
- ACR:
> [NUI] Make PixelBuffer & PixelData as Disposable

- src/Tizen.NUI/src/internal/Common/Uint16Pair.cs
- src/Tizen.NUI/src/internal/Transition/FadeTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/ScaleTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/SlideTransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/TransitionItem.cs
- src/Tizen.NUI/src/internal/Transition/TransitionItemBase.cs
- src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
- src/Tizen.NUI/src/public/Animation/Animation.cs
- src/Tizen.NUI/src/public/Utility/Capture.cs
After PR #4892 `HasBody()` can be false in `ReleaseSwigCPtr`. So, some class who check double-released might not release native memory. It might occure some leak.
This patch make them to check `Disposed` instead of `HasBody()`.
+
Clean up some codes of `ReleaseSwigCPtr`.
TODO : Also need to check `Disposable.Dispose` function
TODO : Need to check third-party library implementation who use their custom `ReleaseSwigCPtr`
> [NUI] Make ReleaseSwigCPtr didn't check HasBody()

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
When I dynamically changed the borderline, only the padding changed and the window size did not change.
Fix this so that the window size also changes.
- ACR:
> [NUI] Fix bug where window size didn't change when borderline was dynamically changed.

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
GetInputMethodContext() in ReleaseSwigCPtr crashes due to current changes in BaseHandle.
Move DestroyContext() to Dispose to avoid this.
> [NUI] fix tct block issue in text field and editor

- src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
To provide the screen size, NUIApplication.GetScreenSize is added.
- ACR:
> [NUI] Add NUIApplication.GetScreenSize

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/public/Window/Window.cs
- The overlay layer is rendered at the end of rendering order
Signed-off-by: seungho baek <sbsh.baek@samsung.com>
- ACR:
> [NUI] Add GetOverlayLayer in NUI window.

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Currently, the CoreApplication prints the log for improving the performance of ToLower() and ToUpper().
This causes the resource contention. Because creating the thread needs the resource as like the fork() in the linux system.
This request removes the thread creation for removing the resource contention.
> [Applications.Common] Remove log prints in the thread

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
1.  Fix bug where window size didn't change when borderline was dynamically changed
2. Window resizing is performed in one step if possible.
- ACR:
> [NUI][API10] Fixed the border window.

- src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
- src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
Since we create new handle at csharp binder, we should call DeleteHandle function.
Note : Extensions.GetInstanceSafely delete the getted cPtr's reference inside of that function. So we cannot use it.
- ACR:
> [NUI][Scene3D] Fix memory leak issue for Model's Animation

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Since we update ImageView lazy, ImageUrl's lifecycle might not matched what user think.
```
ImageUrl imageUrl = ~~~.GenerateUrl();
ImageView imageView = new ImageView(imageUrl.ToString());
imageUrl.Dispose(); ///< We should allow this situation.
```
To make scene, We allow to call UpdateImage(); synchoronously if we use GeneratedUrl().
- ACR:
> [NUI][API10] Fix ImageUrl.Dispose issue

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
**WID:52614003** [STATISTICAL] Value **_parentWindow_**, which is result of method invocation with possible null return value, is dereferenced in member access expression **_parentWindow.KeyEvent_**
_parentWindow.KeyEvent += OnWindowKeyEvent;_
/src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs **line158**
**WID:52613990** [STATISTICAL] Value **_myGroup_**, which is result of method invocation with possible null return value, is dereferenced in member access expression **_myGroup.GroupPosition_**
_myGroup.GroupPosition + groupHeaderMargin.Start:_
src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs **line 1456**
- ACR:
> [NUI] Fix Navigator & GridLayouter svace issues.

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
There was a flag that prevent state updating while applying style. But the flag seemed to have a bug : when style is disabled, the state updating is never going to be done.
This patch fixes the bug and changes the flag's name to be more contextual: styleApplied -> styleApplying.
- ACR:
> [NUI] Fix NUI button not working when style disabled

- src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs
This request is to prevent the delegate garbage collected. 
To make it ineligible for garbage collection, the patchset increments the reference of the iterator variable.
```
A callback was made on a garbage collected delegate of type 'Tizen.Applications.Common!Interop+Bundle+Ite
at Interop+Service.Main(Int32, System.String[], ServiceAppLifecycleCallbacks ByRef, IntPtr)[0m @NEW_BLOCK
at Tizen.Applications.CoreBackend.ServiceCoreBackend.Run(System.String[])[0m
at Tizen.Applications.CoreApplication.Run(System.String[])[0m
at Tizen.Applications.ServiceApplication.Run(System.String[])[0m
<<< onSigabrt >>>[0m
```
> [Applications.Common] Make it ineligible for garbage collection for delegate

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
Previously, although users sets size with width 0, the width is updated by dali's size calculation (e.g. text calculation) instead of width 0 set by user.
The following patch fixed the above bug.
8033b0ed4a31ebcd9449c2e0c98074247502c9be
By applying the above patch, some size assignment in theme should be fixed to set size height instead of size with width 0.
- ACR:
> [NUI] Fix to use SizeHeight instead of Size with width 0

- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/NUIXamlCTask.cs
- src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlGenerator.cs
During the task of replace Xamarin.Forms with NUI.Xaml of Tizen-CSharp-Samples, the samples' namespace always contains "Tizen", and we would get the error : "NUI" could not be found in Tizen. 
The solution is to add global when constructing related parameters, such as ：
new CodeAttributeDeclaration(new CodeTypeReference($"global::{NUIXamlCTask.xamlNameSpace}.XamlFilePathAttribute"),
- ACR:
> [NUI][XamlBuild][API10] Fix namespace confused issue.

- src/Tizen.NUI.Gadget/Interop/Interop.Libc.cs
- src/Tizen.NUI.Gadget/Interop/Interop.Libraries.cs
- src/Tizen.NUI.Gadget/Interop/Interop.PkgMgrInfo.cs
- src/Tizen.NUI.Gadget/Tizen.NUI.Gadget.csproj
- src/Tizen.NUI.Gadget/Tizen.NUI.Gadget.sln
- src/Tizen.NUI.Gadget/Tizen.NUI/Log.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetEventType.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetLifecycleChangedEventArgs.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetLifecycleState.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetType.cs
The NUIGadget is the UI Gadget model for the NUIApplication. The NUIApplication is able to handle gadgets using the NUIGadgetManager.
The dll file of the gadget that is derived by the NUIGadget should be installed to 'res/allowed' or 'res/global' directory.
If the developer wants to allow it only to a specific application, the developer should install it in the 'res/allowed' directory.
And, the developer adds the allowed application information to the tizen-manifest.xml file.
This feature is for inhouse developers. The NUIGadget is available for platform level signed resource packages.
> [NUI.Gadget] Add NUIGadget class for inhouse developers

- src/Tizen.NUI/src/public/Common/PropertyNotification.cs
- src/Tizen.NUI/src/public/Events/PanGestureDetector.cs
1. Fix PropertyNotification & PanGestureDetector svace issues
- ACR: None
> [NUI] Fix PropertyNotification & PanGestureDetector svace issues

- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
There are some code that are unreachable according to device profile.
It's a configuration on compilation which needs a change in the constant to support different devices.
- ACR:
> [NUI] Disable compiler warnings complaining about theme off in TV profile

- src/Tizen.Applications.Common/Interop/Interop.Libc.cs
- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Unfortunately, the dotnet loader process uses the icu library before calling the OnCreate() method of the CoreApplication class.
It makes a problem about CultureInfo setting if the language is changed before executing an application.
This request uses the environment variable instead of the base util library.
> [Applications.Common] Fix getting default locale

- src/Tizen.NUI.Components/Controls/DatePicker.cs
- src/Tizen.NUI.Components/Controls/Picker.cs
- src/Tizen.NUI.Components/Controls/TimePicker.cs
Previously, HeightSpecifications of Picker, DatePicker, TimePicker are MatchParent.
So the Pickers' SizeHeights are calculated based on their parent's SizeHeight.
This causes the recursive size calculation problem if Picker's parent has WrapContent HeightSpecification. (e.g. Dialog)
Now, the Pickers' SizeHeights are set in DefaultThemeCommon as follows. Picker's SizeHeight is set in DefaultThemeCommon.
DatePicker's Pickers SizeHeights are set in DefaultThemeCommon. TimePicker's Pickers SizeHeights are set in DefaultThemeCommon.
Therefore, Picker does not need to have MatchParent HeightSpecification.
- ACR:
> [NUI] Fix Picker's HeightSpecification

- src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
SceneView's camera is not an instance object anymore. It can be holded by app side.
So, if we dispose it inside of CameraTransition Function, It become sudden dead.
Actually, Dali side camera object still alive, but the NUI.Camera handle is dereferenced. So, If app try to access that camera, crash occured.
> [NUI.Scene3D] Do not dispose camera internally

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
When the size of thumb or track changes, the it should update the position of the thumb properly.
And to prevent unnecessary switch state updating while applying style, upgrade styleApplying flag to int type.
- ACR:
> [NUI] Fix Switch thumb positioning

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
To increase Button width based on the Button's text, Button Theme sets MinimumSize instead of fixed Size.
- ACR:
> [NUI] Fix Button Theme not to set fixed size

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
To follow system font size scale, TextLabel Theme sets FontSizeScale with UseSystemSetting.
- ACR:
> [NUI] Fix TextLabel Theme to set FontSizeScale with UseSystemSetting

- src/Tizen.NUI.Scene3D/src/internal/CameraBindableProperty.cs
- src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Camera.cs
- src/Tizen.NUI.Scene3D/src/public/Controls/Camera.cs
- src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
We might need to backport some properties so we can use Scene3D feature fully
This patch required below dali patches merge first
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/287878
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/287879
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/287880
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/287881
> [NUI.Scene3D] Backport API11 for Scene3D

- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs
- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Components/Controls/TabBar.cs
- src/Tizen.NUI.Components/Controls/TabContent.cs
- src/Tizen.NUI.Components/Controls/TabView.cs
To apply string style during constructing controls, constructors with string style are added.
- ACR:
> [NUI] Add constructors with string style to apply string style

- src/Tizen.NUI/src/public/Theme/Theme.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
* ThemeChanging event: An event called right after the theme changed and before applying it to the view.
* ClearAllAppliedThemes: Since every themes passed by ApplyThemes() are cumulative, user may want to clear all.
* Open Theme.indexer public: This is for C_XAML.
- ACR:
> [NUI] Improve behaviors of ThemeManager and add an event

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
- src/Tizen.NUI.Components/Controls/Extension/SwitchExtension.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
* Button's
IconOrientation bug In the previous code, when the IconOrientation property changed, the LayoutItems() was called and it created a new layout. But in case the button was inside another layout, the behaviour described above caused unexpect look. Therefore I fixed it by changing orientation related properties to the existing layout instead of creating a new layout.
* Improve switch and extension relationship
The switch extension does not register any event handler to the switch components anymore.
- ACR:
> [NUI] Fix button bugs and improve switch.

- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
To support button size set by user, Button's min size is removed.
- ACR:
> [NUI] Fix to remove Button's min size

- src/Tizen.NUI.Components/Controls/Pagination.cs
* Bug: When user changes indicator image url, all indicators turn into unselected look.
- ACR:
> [NUI] Fix Pagination bug

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
SVACE issue:
WID:38318506 [STATISTICAL] Value borderInterface.MinSize, which is result of method invocation with possible null return value, is dereferenced in member access expression borderInterface.MinSize.Width.
- ACR:
> [NUI][API10] Fix SVACE issue.

- src/Tizen.NUI.Components/Controls/Menu.cs
Menu.Content is a container of menu items.
Previously, Menu.Content was displayed even if there is no menu item. Now, Menu.Content is displayed only if menu item exists.
- ACR:
> [NUI] Fix Menu not to show Content if there is no menu item

- src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
- src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
Make API that we can use gltf model file defined camera.
Since Tizen.NUI.Scene3D.Camera is one of View & This camera should be children of SceneView to render the scene, Camera cannot be owned by Model itself.
So, we support only for 'Generate' or 'Apply' camera parameters loaded from gltf model.
> [NUI.Scene3D][API10] Use Model defined camera

- src/Tizen.NUI/src/public/EXaml/EXamlExtensions.cs
1. Fix dispose xaml elements.
```
<A x:Name="xxx" ... >
<A.B>
<C x:Name="xxx"  .../>
</A.B>
</A>
```
In this case, if node C is not the direct child of node A, then node C can't be disposed in DisposeXamlElements function, due to the IsCreateByXaml  property of the parent of node C is false.
- ACR: None.
> [NUI] Fix dispose xaml elements

- src/Tizen.NUI/src/public/Window/Window.cs
Fix SetInputRegion binding function  with correct internal function.
Because previous binded with includedRegion.
> [NUI] Fix set input region binding

- src/Tizen.NUI/src/public/Window/Window.cs
Fix SetInputRegion binding function with correct internal function.
Because previous binded with includedRegion.
> [NUI] Fix set input regine binded api

- src/Tizen.NUI/src/public/Events/LongPressGestureDetector.cs
[NUI] Add Dispose to LongPressGestureDetector and modify ReleaseSwigCPtr.
- ACR:
> [NUI] Add Dispose to LongPressGestureDetector and modify ReleaseSwigCPtr

- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
When if we set View.Size, It will call WidthPolicy / HeightPolicy internal. And then it will call SizeWidth and SizeHeight.
This patch ignore some duplicated size setting each other.
Test for 10,000 color view creation on Ubuntu
before : 1294.67 ms
after : 1159.00 ms
> [NUI] Remove duplicate size setter

- src/Tizen.NUI/src/public/Window/BorderWindow.cs
[NUI] Add getter property about WindowPositionSizeWithBorder and WindowSizeWithBorder
In the case of a border window, the size including the border area is required.
- ACR:
> [NUI] Add getter property about WindowPositionSizeWithBorder and WindowSizeWithBorder

- src/Tizen.NUI/src/public/Common/Layer.cs
Previous MoveAbove / MoveBelow API change only native side layer order.
It didn't apply to the window who hold this layer.
> [NUI] Fix layer MoveAbove/MoveBelow API change window's List

- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
When calling the CreateInstance() method, this patch modifies the set the ignoreCase to true that the case of the className is no checked.
> [NUI.Gadget] Modify NUIGadgetManager.Add() method

- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
* [NUI.Gadget] Add new internal APIs
If the UI gadget developer sets the class name, the application developer can adds a new NUIGadget instance using the NUIGadgetInfo object.
The following APIs are added:
+ NUIGadgetManager.Add(NUIGadgetInfo gadgetInfo); [method]
+ NUIGadgetManager.GetGadgetInfos(); [method]
+ NUIGadgetInfo.ClassName; [property]
> [NUI.Gadget] Add a new internal API (#4976)

- src/Tizen.Applications.Common/Interop/Interop.AppControl.cs
- src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
- src/Tizen.Applications.Common/Tizen.Applications/WindowPosition.cs
- src/Tizen.Applications.UI/Interop/Interop.Application.cs
- src/Tizen.Applications.UI/Tizen.Applications/CoreUIApplication.cs
This request supports to set/get the window position.
The following APIs are added:
- WindowPosition [class]
- AppControl.SetWindowPosition() [method]
- AppControl.GetWindowPosition() [method]
- CoreUIApplication.GetWindowPosition() [method]
The caller application of the AppControl can set the window position to the AppControl instance.
When the target application is starting, the application can get the window position that is set by the caller using the method.
> [Applications.Common / UI] Add new internal APIs

- src/Tizen.NUI/src/internal/Common/WindowViewAddedSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WindowViewAddedSignal.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Window/BorderWindow.cs
- src/Tizen.NUI/src/public/Window/WindowEvent.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/EventPropagationSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/HitTestSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowEventsTest.cs
Since Window.ViewAdded signal required to all common view's creation time,
It will reduce each view's creation time.
And more, ViewAdded signal only works for default windows previously.
Now we make the signal ownership from window.
And additionaly, register custom HitTest signal only if subclass required.
TODO : The role of signal conflict with View.AddedToWindow.
Can we just remove this ViewAdded signal?
TODO : Can we just skip default view constructor's signal connection?
> [NUI] Do not connect default signals when View created

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
use nameof instead of string.
use full name of view as variable.
- ACR:
> [NUI] fix previous patch by coding rules

- src/Tizen.NUI/src/public/Theme/ExternalThemeManager.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
- test/Tizen.NUI.ThemeManager.Samples/TizenThemeChangeSample/TizenThemeChangeSample.cs
- test/Tizen.NUI.ThemeManager.Samples/TizenThemeChangeSample/TizenThemeChangeSample.csproj
- test/Tizen.NUI.ThemeManager.Samples/TizenThemeChangeSample/tizen-manifest.xml
* Remove circular dependency
The NUI theme modules (ThemeManager and ExternalThemeManager) had dependencies to each other. It caused me to switch back and forth between the two modules when reading the code since it did not meet "Seperation of concerns" principle.
This patch makes dependency direction one way: ThemeManager -> ExtenalThemeManager
* Add a sample application to verify functional regressions.
- ACR:
> [NUI] Refactor NUI.ThemeManager

- src/Tizen.NUI/src/internal/XamlBinding/ResourcesExtensions.cs
[STATISTICAL] Value ve.XamlResources, which is result of method invocation with possible null return value, is dereferenced in member access expression ve.XamlResources.MergedResources.
[STATISTICAL] Value ve.XamlResources, which is result of method invocation with possible null return value, is dereferenced in method call ve.XamlResources.TryGetValue()
- ACR:
> [NUI] Fix some SVACE issues.

- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetResourceManager.cs
To support internationalization, the NUIGadgetResourceManager is added.
The developer can set the resource dll and class name using the metadata in the tizen-manifest.xml.
> [NUI.Gadget] Support Internationalization

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
assign a value directly into the property internally may have the potential issue of binding canceling.
to prevent this, add internal property and use them insteadly.
see more detail about issue on below,
https://code.sec.samsung.net/confluence/display/GFX/NUI+Binding+Issue
This patch include below class property changes :
View.IsEnabled
Button.IsSelected
RecyclerViewItem.IsSelected
and all the usage of this properties.
- ACR:
> [NUI] Add internal property to avoid binding canceling on property set

- src/Tizen.NUI/src/public/Window/WindowEvent.cs
[NUI] merge Window event changes of API10
- in API10 Window's event pattern had been changed and has been applied
- to resolve this exception in tizen_6.5(API9) =>
_E/DOTNET_LAUNCHER(11285): log.cc: stdErrRedirect(120) > Unhandled exception.
E/DOTNET_LAUNCHER(11285): log.cc: stdErrRedirect(120) >
E/DOTNET_LAUNCHER(11285): log.cc: stdErrRedirect(120) > System.ArgumentNullException: Value cannot be null. (Parameter 'd')
E/DOTNET_LAUNCHER(11285):    at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(Delegate d)
E/DOTNET_LAUNCHER(11285):    at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate[TDelegate](TDelegate d)
E/DOTNET_LAUNCHER(11285):    at Tizen.NUI.KeyEventSignal.Disconnect(Delegate func) in /home/abuild/rpmbuild/BUILD/csapi-tizenfx-9.0.0.16852 …
> [NUI] merge Window event changes of API10

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Extension/ButtonExtension.cs
- src/Tizen.NUI.Components/Controls/Extension/LottieButtonExtension.cs
- src/Tizen.NUI.Components/Controls/Extension/LottieSwitchExtension.cs
- src/Tizen.NUI.Components/Controls/Extension/SwitchExtension.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI.Components/PreloadStyle/OverlayAnimationButtonStyle.cs
* OnCreateIcon -> ProcessIcon
* OnCreateText -> ProcessText
* OnCreateOverlayImage -> ProcessOverlayImage
* OnCreateThumb -> ProcessThumb
These methods are designed for futher processing of the button's subcomponents.
To better match the design intent, the methods were better renamed: `OnCreateXXX` to `ProcessXXX`.
Also, the parameters and return type were not optimal form and needed refactoring.
```C#
// Before
// Previously, the method returned processed image which can be the given image or a new one.
// The caller doesn't know if the image has replaced to a new one or not.
ImageView OnCreateIcon(Button, ImageView);
// After
// The method returns the boolean result indicating the given reference of image is replaced or not.
bool ProcessIcon(Button, ref ImageView);
```
Most part of …
> [NUI] Refactor ButtonExtension

- src/Tizen.NUI/src/internal/Interop/Interop.View.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
The accessibility mode helps select the right Accessible implementation for a given view. It does not affect controls derived from CustomView (or any of its subclasses), e.g. Tizen.NUI.Components, which already behave in the custom mode. The default mode is kept for Tizen.NUI.BaseComponents. However, this patch add a possibility of opting into the custom mode for controls derived directly from View (e.g. FluxView), and by doing so, to be able to implement accessibility support for them in the C# language.
Dependencies:
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/290142/
- ACR: None
> [NUI][AT-SPI] Add ViewAccessibilityMode

- src/Tizen.NUI/src/public/BaseComponents/View.cs
Since useless HitTest checkup function make performance down for standard cases, Let we make we use custom callback only if GrabTouchAfterLeave case.
> [NUI] Register HitTest callback only if GrabTouchAfterLeave = true

- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
A race condition occurred when two threads subscribed ConnectionManager.ConnectionTypeChanged.
Only the first event subscription register the C# side callback to the native capi.
So the subscription should be protected by lock.
> [Connection] Fix race condition

- src/Tizen.NUI/src/internal/Interop/Interop.FontClient.cs
- src/Tizen.NUI/src/public/Utility/FontClient.cs
This patch adds a new PreCache API to enable pre-caching of fonts and improve the runtime performance of the application.
Pre-caching default fonts and fallback lists can enhance the responsiveness performance by minimizing the calls to FcFontSort and FcFontMatch, during the early stages of boot-up.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/290395/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/290460/
> [NUI] Add Font PreCache API to FontClient

- src/Tizen.NUI/src/internal/Common/Disposable.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/Window/WindowEvent.cs
* Do not try to disconnect callback unless the callback is not null.
* Ensure a signal has valid cptr before calling Connect/Disconnect.
- ACR:
> [NUI] Fix signal bugs in View and Window.

- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
Previously, RelativeLayout calculated the size for TextLabel with Margin incorrectly by calling MeasureChildWithMargins().
Because TextLabel size was decreased by its Margin size incorrectly.
Now, RelativeLayout calculates the size for TextLabel with Margin correctly by calling MeasureChild().
Because TextLabel size is not decreased by its Margin size.
- ACR:
> [NUI] Fix size calculation for TextLabel with Margin in RelativeLayout

- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
ContentPage often serves as a default label in scenarios where Navigator is used, so Screen Reader will ask ContentPage about the accessibility name (text to read) when a Navigator page is pushed. Therefore, it makes sense to try to provide the text from ContentPage.AppBar.Title (if it exists). The application developer can always customize this by setting the AccessibilityName property or adding an AccessibilityRelation.LabelledBy.
- ACR: None
> [NUI][AT-SPI] Override ContentPage.AccessibilityGetName()

- src/Tizen.Content.Download/Tizen.Content.Download/CacheManager.cs
Updates protection level to 'public' for CacheManager class. So that it can be used by applications.
> [Tizen.Content.Download] Update protection level for CacheManager class

- src/Tizen.NUI.Components/Controls/Pagination.cs
- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/Accessibility/IAtspiValue.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
This API allows the application to provide the Screen Reader with a formatted string value rather than the default, floating-point one. This in turn, allows to customize in detail how e.g. slider values are read.
Direct dependencies (DALi and TizenFX ABI changes):
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/291324/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/291323/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/291322/
Indirect dependencies of the above (D-Bus GetReadingMaterial ABI change):
- https://review.tizen.org/gerrit/#/c/platform/upstream/at-spi2-core/+/291274/
- https://review.tizen.org/gerrit/#/c/platform/upstream/at-spi2-atk/+/291336/
- …
> [NUI][AT-SPI] Add IAtspiValue.AccessibilityGetValueText()

- src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
- src/Tizen.NUI/src/public/Application/NUIApplication.cs
To provide the screen size, NUIApplication.GetScreenSize is added.
- ACR:
> [NUI] Add NUIApplicaion.GetScreenSize

- src/Tizen.NUI/src/public/Accessibility/AccessibilityManagerEvent.cs
- src/Tizen.NUI/src/public/Animation.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/PropertyNotification.cs
- src/Tizen.NUI/src/public/StyleManager.cs
- src/Tizen.NUI/src/public/Timer.cs
- src/Tizen.NUI/src/public/WindowEvent.cs
- DA AllApps 일회성 문제 (https://code.sec.samsung.net/jira/browse/TDAF-1706) 수정을 위해 event 관련 방어코드를 추가하였습니다.
- 아래 event 들에 대해서 native handle 을 체크하는것과 event -= 가 먼저 불렸을 경우 Disconnect(null) 이 들어갈수 있는 경우를 막았습니다. 
(done) NUI.Timer.Tick
(done) NUI.StyleManager.StyleChanged
(done) View.TouchEvent
(done) View.KeyEvent
(done) View.RemovedFromWindow
(done) Window.TouchEvent
(done) Window.KeyEvent
(done) Animation.Finished
(done) AccessibilityManager.FocusedViewActivated
(done) PropertyNotification.Notified
(no native signal) ThemeManager.ThemeChanged 
(no native signal) ScrollableBase.Scrolling
(no native signal) ScrollableBase.ScrollOutOfBoundWithDisplacement
(no native signal) ScrollableBase.ScrollAnimationEnded
(no native signal) ScrollableBase.ScrollDragStarted
(no native signal) …
> [NUI] Add defence codes for specific events

- src/Tizen.NUI/src/public/Window/Window.cs
Previously, OverlayLayer was not added to Window's LayersChildren so Layouts inside the OverlayLayer were not calculated.
Now, OverlayLayer is added to Window's LayerChildren to calculate Layouts inside the OverlayLayer.
- ACR:
> [NUI] Add OverlayLayer to Window's LayersChildren to calculate Layout

- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
[STATISTICAL] Value InternalSource, which is result of method invocation with possible null return value, is dereferenced in member access expression InternalSource.Count
[STATISTICAL] Value AppBar, which is result of method invocation with possible null return value, is dereferenced in method call AppBar.PassFocusableViewInsideIfNeeded()
[STATISTICAL] Value temp, which is result of method invocation with possible null return value, is dereferenced in member access expression temp.Width
- ACR:
> [NUI] Fix SVACE issues.

- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
[STATISTICAL] Value InternalSource, which is result of method invocation with possible null return value, is dereferenced in member access expression InternalSource.Count
[STATISTICAL] Value AppBar, which is result of method invocation with possible null return value, is dereferenced in method call AppBar.PassFocusableViewInsideIfNeeded()
[STATISTICAL] Value temp, which is result of method invocation with possible null return value, is dereferenced in member access expression temp.Width
- ACR:
> [NUI][API10] Fix SVACE issues.

- src/Tizen.NUI/src/public/Animation/Animation.cs
Since we already have empty-parameter function named Stop(), Let we remove Stop(EndActions)'s default value so compiler don't feel confuse.
> [NUI] Remove default parameter of Animation.Stop(EndActions)

- src/Tizen.NUI/src/internal/Interop/Interop.GestureOptions.cs
- src/Tizen.NUI/src/public/Events/GestureOptions.cs
This is the time from touch down to touch up to recognize a tap gesture.
If set to 300ms, a touch up after a touch down must occur within 300ms to be recognized as a tap gesture.
- ACR:
> [NUI] Add SetTapRecognizerTime

- src/Tizen.Log/Interop/Interop.Dlog.cs
- src/Tizen/Interop/Interop.Dlog.cs
- test/ElmSharp.Test/Log.cs
- test/ElmSharp.Wearable.Test/TC/Log.cs
Replace dlog_print with dlog_print_dotnet which is used for only csharp api.
- ACR: No API changed
> [Tizen.Log] Replace dlog_print with dlog_print_dotnet

- src/Tizen.NUI/src/public/Window/Window.cs
If the root layer index is not updated and another layer is added first, a problem occurs in calculating the layer index. Something like LowerBelow may not work.
- ACR:
> [NUI] Change the call to GetRootLayer() so that the layer index can be updated.

- src/Tizen.Log/Interop/Interop.Dlog.cs
- src/Tizen.Log/Tizen.Log.csproj
- src/Tizen.Log/Tizen/Log.cs
The CLR automatically converts string into byte array when it invokes native function. In this process, the CLR allocates byte array on heap, which will be a garbage, for every single string. If applications are printing dlog too bursty, those garbage would pile up, consuming too much memory. To reduce those garbage, manually allocates byte array on stack and convert string into that byte array.
- ACR:
> [Tizen.Log] Optimize garbage collection

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
when failed flag is true,
other condition should be ingored.
- ACR:
> [NUI] Fix empty item case crash. wrong bracket conditions.

- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
- src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
To improve instance creation speed, this patch adds the Assembly property to the NUIGadgetInfo.
If the NUIGadgetInfo has the property that is not null, NUIGadgetManager uses it.
> [NUI.Gadget] Add Assembly property to NUIGadgetInfo

- src/Tizen.NUI/src/internal/Common/FrameBuffer.cs
- src/Tizen.NUI/src/internal/Interop/Interop.FrameBuffer.cs
> [NUI] Add GenerateUrl API to FrameBuffer
