src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs

1. Fix issue of call SetBinding in c# code (Same with the patch https://github.com/Samsung/TizenFX/pull/4056)
- ACR:

[NUI][Xaml] Fix issue of call SetBinding in c# code

---

src/Tizen.NUI/src/internal/Interop/Interop.PropertyMap.cs
src/Tizen.NUI/src/public/Common/PropertyMap.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PropertyMapSample.cs

1) Some APIs are added like Keys, Values, Contains, Remove, etc.
2) Check whether key is duplicated or not when inserting/adding some key value pair.
3) This patch is related to the patch in csharp-binder:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/272447/
- ACR:

[NUI] Make PropertyMap look like Dictionary.

---

src/Tizen.NUI.XamlBuild/src/public/EXamlBuild/EXamlContext.cs
src/Tizen.NUI.XamlBuild/src/public/EXamlBuild/EXamlCreateObjectVisitor.cs
src/Tizen.NUI.XamlBuild/src/public/EXamlBuild/EXamlSetPropertiesVisitor.cs
src/Tizen.NUI.XamlBuild/src/public/XamlBuild/NodeILExtensions.cs
src/Tizen.NUI.XamlBuild/src/public/XamlBuild/TypeReferenceExtensions.cs
src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlTask.cs
src/Tizen.NUI/src/internal/EXaml/Action/GetValueAction.cs
src/Tizen.NUI/src/internal/EXaml/Operation/CreateObject.cs

Sync https://github.com/Samsung/TizenFX/pull/4046 from API9.
- ACR:

[NUI][XamlBuild] Fix Xaml issues reported by VD

---

test/NUITizenGallery/tizen-manifest.xml
test/Tizen.NUI.Samples/Tizen.NUI.Samples/tizen-manifest.xml
test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/tizen-manifest.xml

Fix tizen-manifest files for frequently used and managed samples
none

[NUI][TEST] Fix tizen-manifest files for frequently used and managed samples

---

src/Tizen.NUI/src/public/Common/Color.cs

[NUI] Fix comments according to ACR review
- https://github.com/Samsung/TizenFX/pull/2220#pullrequestreview-796119712
- related to https://github.com/Samsung/TizenFX/pull/2220
- related to https://code.sec.samsung.net/jira/browse/TCSACR-391
none

[NUI] Fix comments according to ACR review

---

test/Tizen.NUI.StyleGuide/.vscode/launch.json
test/Tizen.NUI.StyleGuide/Examples/ContentPageExample.cs
test/Tizen.NUI.StyleGuide/Examples/DialogAndAlertDialogExample.cs
test/Tizen.NUI.StyleGuide/Examples/NavigatorExample.cs
test/Tizen.NUI.StyleGuide/Examples/TabViewExample.cs

[NUI][TEST] Add ContentPage, DialogPage, Navigator and TabView examples in StyleGuide
- this sample App is to also verify and test key navigation for NUI.Components
none

[NUI][TEST] Add ContentPage, DialogPage, Navigator and TabView examples in StyleGuide

---

test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/TSView.cs

simple fix of wrong test value check.
- ACR:

[NUI][Test] fix wrong test value checking.

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Theme/ThemeManager.cs

[NUI] Fix to disable ThemeManager in tv profile
- same as https://github.com/Samsung/TizenFX/pull/4121
- already be merged in API9
none

[NUI] Fix to disable ThemeManager in tv profile

---

src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/StickerConsumer.cs
src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/StickerProvider.cs

The Initialized property value is not changed when calling the Deinitialize() API, so app can't receive a valid value.
So I modified to change Initialized value when Deinitialize() is called.

[Sticker] Modified to change initialization flag properly

---

src/Tizen.NUI.Components/Controls/Loading.cs

- Make Play / Pause / Stop methods to public API on API level 10.
- These methods are for Loading animation behavior.
- ACR: TCSACR-485
https://code.sec.samsung.net/jira/browse/TCSACR-483
Added:
- public void Play()
- public void Pause()
- public void Stop()

[NUI][TCSACR-485] Add some methods for Loading

---

src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs

Fixes https://github.com/Samsung/TizenFX/issues/4112
- ACR:

[NUI] Fix IsEnabledProperty name

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

[NUI] change SetPosition(...) as a hidden API for internal use only
none

[NUI] change SetPosition(...) as a hidden API for internal use only

---

src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs

The latest ContentPage UX has been applied.
BackgroundColor has been changed.
CornerRadius and BoxShadow are newly applied.
- ACR:

[NUI] Apply ContentPage UX - BackgroundColor, CornerRadius, BoxShadow

---

src/Tizen.Uix.Sticker/Tizen.Uix.Sticker/StickerProvider.cs

[Sticker] Fix typo in description

---

README.md

Update `README.md`
- Add a section to describe how to use the `tizen` target framework.

[docs] Add `using tizen tfm` section to README.md

---

src/Tizen.NUI/src/public/Window/DefaultBorder.cs
src/Tizen.NUI/src/public/Window/IBorderInterface.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AllAppsSample.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/BorderWindowTest.cs

[NUI] Minimize size is set too large. And code clean up.

[NUI] Minimize size is set too large. And code clean up

---

src/Tizen.NUI.Components/Controls/TabBar.cs
src/Tizen.NUI.Components/Controls/TabButton.cs
src/Tizen.NUI.Components/Controls/TabView.cs
src/Tizen.NUI.Components/Style/TabButtonStyle.cs
src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TabViewSample.cs

The latest TabView UX has been applied.
TabBar and TabButton's Size and BackgroundColor have been updated.
- ACR:

[NUI] Apply TabView UX - TabBar and TabButton Size and BackgroundColor

---

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapterImpl.cs
src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs

- #1643
- #1657
- #2485
- #2498
- #2514
- #2517
- #2887
- #3084
- #3303 
- #3351

[Bluetooth] Fix BluetoothDevice converting issue

---

src/Tizen.NUI.Components/Controls/Menu.cs

Check null pointer of menuStyle in Menu.
- ACR:

[NUI] Fix to null check menuStyle in Menu

---

packaging/csapi-tizenfx.spec
packaging/csapi-tizenfx.spec.in

* [Build] Enable aarch64 build
* Update csapi-tizenfx.spec.in
- ACR:

[Build] Enable aarch64 build (#4134)

---

src/Tizen.NUI.Components/Controls/MenuItem.cs

[NUI] Remove redundant codes in MenuItem

---

test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/FlexibleView/TSFlexibleViewAdapter.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/FlexibleView/TSFlexibleViewHelper.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSPopup.cs

[NUI][TEST] Update TCs of FlexibleView.

---

src/Tizen.NUI/src/internal/XamlBinding/BindingExpression.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
src/Tizen.NUI/src/public/XamlBinding/TypedBinding.cs

…rom API9
Sync the patch https://github.com/Samsung/TizenFX/pull/4056 from API9.
- ACR:

[NUI][Xaml] Sync patch 4056 from API9

---

src/Tizen.NUI/src/internal/XamlBinding/BindingExpression.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
src/Tizen.NUI/src/public/XamlBinding/TypedBinding.cs

[NUI][Xaml]Fix issue of Call SetBinding in C# code

---

src/Tizen.NUI/src/public/Window/BorderWindow.cs
src/Tizen.NUI/src/public/Window/DefaultBorder.cs

[NUI][SVACE] fix svace defect (add null check, replace TopCentor as Vector3 which is same)
none

[NUI][SVACE] fix svace defect (add null check, replace TopCentor as Vector3 which is same)

---

src/Tizen.Multimedia/Tizen.Multimedia.sln

Fix multimedia project build error on window visual studio.

[Multimedia] Fix build error

---

src/Tizen.NUI.Components/Controls/AlertDialog.cs
src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs

The latest AlertDialog UX have been applied.
Sizes and Colors have been changed.
- ACR:

[NUI] Apply AlertDialog UX - Sizes and Colors

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

change drag window resuable to improve performance
N/A

[NUI] DragAndDrop : change drag window reusable

---

src/Tizen.NUI.Components/Controls/DatePicker.cs
src/Tizen.NUI.Components/Controls/Picker.cs
src/Tizen.NUI.Components/Controls/TimePicker.cs
test/Tizen.NUI.StyleGuide/Examples/DatePickerExample.cs
test/Tizen.NUI.StyleGuide/Examples/TimePickerExample.cs

Apply IsEnabled Feature on Picker, DatePicker and TimePicker.
Picker consist of other subsidiary views so it may need to be disabled when picker is disabled at OnEnabled().
currently DatePicker and TimePicker consist of three internal picker so we update IsEnabled property of this picker.
Picker also consist of internal scroller so we update IsEnabled Property of this scroller.
add disable toggle in DatePicker and TimePicker style guide to check disabled state.
- ACR:

[NUI] Apply IsEnabled feature on Pickers.

---

src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs

- change button and check sizes
- change icon size
- set space size between icon and text
- change text color
- ACR:

[NUI] Update Tizen 7.0 UX for Button and Check- sizes and text color

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

Fix accessing invalid null pointer
- ACR:

[NUI] DragAndDrop: fix svace error

---

src/Tizen.Multimedia/Tizen.Multimedia.sln

* [Multimedia] Fix build error
- ACR:

[Multimedia] Fix build error (#4204)

---

src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs

Tizen 7.0 UX does not include all controls.
However, to give the same look and feel to all controls, control theme
whose UX is not defined by Tizen 7.0 is also updated like others.
- ACR:

[NUI] Update control theme whose UX is not defined by Tizen 7.0

---

test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/Navigation/TSAppBar.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/TSCollectionView.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/TSRecyclerView.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/TSSelectionList.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSAlertDialog.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSButton.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSControl.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSDatePicker.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSImageScrollBar.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSLoading.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSPicker.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSProgress.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSScrollableBase.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSScrollbar.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSSlider.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSSwitch.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSTimePicker.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSToast.cs

[NUI][Test] Add TCs of NUI.Components to  improve function coverage.

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

remove previous shadowView before adding new shadowView
- ACR:

[NUI] remove previous shadowView before adding new shadowView

---

src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs

Page animation has been changed from alpha to sliding.
- ACR:

[NUI] Apply Tizen 7.0 UX to Navigator - Page animation

---

src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/EditorWindow.cs
src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodExceptionFactory.cs

Integration master to DevelNUI
- ACR:

Modified to appropriate exception type (#4170)

---

src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs

[NUI] Fix crash on Navigator to check ContentPage.Content correctly

---

src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs

[NUI] Change IsCreateByXaml to virtual

---

src/Tizen.NUI/src/public/Layouting/LayoutItem.cs

[NUI] Fixed svace issue

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
test/NUIDnDSource/NUIDnDSource.cs

Fit drag window to shadow view
- ACR:

[NUI] DragAndDrop: Fit drag window to shadow view

---

src/Tizen.NUI.Components/Controls/Slider.Internal.cs
test/Tizen.NUI.StyleGuide/Examples/SliderExample.cs

- Change the size of Slider bgTrack to enable to touch when the thumb is at the end of the track.
- N/A

[NUI] Modify the size of Slider track

---

src/Tizen.Applications.Common/Interop/Interop.IniParser.cs
src/Tizen.Applications.Common/Interop/Interop.Libraries.cs
src/Tizen.Applications.Common/Tizen.Applications/CultureInfoHelper.cs

There is a performance issue about parsing the xml file. 
To improve the performance about loading default CultureInfo, the CultureInfoHelper uses iniparser instead of xml parser.

[Applications.Common] Fix CultureInfoHelper class

---

src/Tizen.NUI.Components/Controls/Picker.cs

Screen Reader want to read only currently visible items
No API Changes

[NUI] Apply AccessibilityHidden for Picker

---

src/Tizen.NUI.Components/Controls/ScrollableBase.cs

[NUI] fix warnings. add null argument exceptions and comments.

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/MultiWindowDisposeTest.cs.cs

[NUI][TEST] add multi Window dispose test
- to test the issue of https://github.sec.samsung.net/dotnet/NUIBackend/issues/135
none

[NUI][TEST] add multi Window dispose test

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs

[NUI] Add Tizen.Tracer logs at some critical points for app launching performance
- for http://jira.vd.sec.samsung.net/browse/UNI-3105.
- checked whether the added logs are coming with local binary.
none

[NUI] Add Tizen.Tracer logs at some critical points for app launching performance

---

src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs

[NUI] Add Tracer.End() to make a pair with Tracer.Begin()
- revise and modify https://github.com/Samsung/TizenFX/pull/4277
- related to https://github.com/dalihub/tizenfx-stub/pull/5
none

[NUI] Add Tracer.End() to make a pair with Tracer.Begin()

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/NativeImageSourceTest.cs

[NUI][TEST] add sample to use native image

---

src/Tizen.NUI/src/public/Window/BorderWindow.cs
src/Tizen.NUI/src/public/Window/DefaultBorder.cs
src/Tizen.NUI/src/public/Window/IBorderInterface.cs

1. Added OnMaximize() and OnMinimize() APIs so that you can know when Maximize/Minimize is called.
2. Adds a Focusable to the icon.

[NUI] Add Maximize and Minimize related APIs and Add Focusable property to the icon

---

src/Tizen.NUI/src/public/Window/DefaultBorder.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/BorderWindowTest.cs

This patch is making icons(min, max, close, corner) on the window border work.

[NUI][AT-SPI] make window border icons work

---

src/Tizen.Applications.Common/Interop/Interop.AppControl.cs
src/Tizen.Applications.Common/Interop/Interop.IniParser.cs
src/Tizen.Applications.Common/Interop/Interop.Libraries.cs
src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
src/Tizen.Applications.Common/Tizen.Applications/CultureInfoHelper.cs
src/Tizen.Multimedia.Remoting/Interop/Interop.WebRTC.DataChannel.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.Events.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.cs
src/Tizen.System.Feedback/Feedback/Feedback.cs

- Rebase master branch to DevelNUI branch.
- N/A

[NUI] Rebase master branch

---

src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs

1. First use own bindingcontext,if not, then use inherit bindingcontext
- ACR:

[NUI]First use own bindingcontext

---

src/Tizen.NUI.Components/Controls/Button.Internal.cs
src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
src/Tizen.NUI/src/public/Layouting/GridLayout.cs
src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs

This reverts commit 401fdd783df1f139eb2283d453678d69e02fb770.
- ACR:

Revert "[NUI] Support Layout property by ViewStyle"

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

[NUI] Initialize Drag window position and size based on Shadow View

---

src/Tizen.Applications.Common/Interop/Interop.AppCoreUI.cs
src/Tizen.Applications.Common/Interop/Interop.Glib.cs
src/Tizen.Applications.Common/Interop/Interop.Libraries.cs
src/Tizen.Applications.Common/Tizen.Applications.CoreBackend/ICoreTask.cs
src/Tizen.Applications.Common/Tizen.Applications.CoreBackend/ICoreTaskBackend.cs
src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
src/Tizen.Applications.Common/Tizen.Applications/CoreTask.cs
src/Tizen.Applications.Common/Tizen.Applications/GSourceManager.cs
src/Tizen.Applications.Common/Tizen.Applications/TizenUISynchronizationContext.cs
src/Tizen.Applications.Common/Tizen.Applications/UIEventArgs.cs
src/Tizen.Applications.Common/Tizen.Applications/UIEventStatus.cs
src/Tizen.Multimedia.Remoting/Interop/Interop.WebRTC.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaFileSource.cs

[NUI] Integration 6/10

---

src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs

[NUI] Fix duplicated TextChanged event handler

---

src/Tizen.NUI/src/internal/Common/Disposable.cs
src/Tizen.NUI/src/public/Animation/Animation.cs
src/Tizen.NUI/src/public/Common/BaseHandle.cs
src/Tizen.NUI/src/public/Common/StyleManager.cs
src/Tizen.NUI/src/public/CustomView/CustomViewRegistry.cs
src/Tizen.NUI/src/public/Input/InputMethodContext.cs
src/Tizen.NUI/src/public/Input/KeyValue.cs
src/Tizen.NUI/src/public/Layouting/LayoutTransition.cs
src/Tizen.NUI/src/public/Layouting/MeasureSpecification.cs
src/Tizen.NUI/src/public/Visuals/VisualMaps.cs

[NUI] Fix comments according to the document review
- to resolve https://github.com/Samsung/TizenFX/pull/2425#pullrequestreview-796206299
none

[NUI] Fix comments according to the document review

---

src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs

https://code.sec.samsung.net/jira/browse/TCSACR-461
This patch should have been applied in API9, but it was missing.
I made this PR to complete the pending ACR.

[NUI] Open text selection APIs

---

src/Tizen.NUI/src/public/Window/Window.cs

Dispose seems to be missing after creating and using value.

[NUI] Add dispose.

---

src/Tizen.NUI.Components/Controls/Switch.cs

The AT-SPI subtree of `Switch` can be optimized to a single leaf node, i.e. from:
```
[[:1.12:0xb8f74838],[toggle button],[toolkit=nui(dali)],[(class=Switch)(automationId=toggleButton1)],[20,650,182,44],[Toggle1],[(ENABLED)(FOCUSABLE)(SENSITIVE)(SHOWING)(VISIBLE)(HIGHLIGHTED)(HIGHLIGHTABLE)],[]]
[[:1.12:0xb8d238e0],[image],[toolkit=nui(dali)],[(class=ImageView)],[20,650,84,44],[],[(ENABLED)(SENSITIVE)(SHOWING)(VISIBLE)],[]]
[[:1.12:0xb8d241e8],[image],[toolkit=nui(dali)],[(class=ImageView)],[20,650,44,44],[],[(ENABLED)(SENSITIVE)(SHOWING)(VISIBLE)],[]]
```
to
```
[[:1.17:0xb8a957d0],[toggle button],[toolkit=nui(dali)],[(class=Switch)(automationId=toggleButton1)],[20,650,182,44],[Toggle1],[(ENABLED)(FOCUSABLE)(SENSITIVE)(SHOWING)(VISIBLE)(HIGHLIGHTED)(HIGHLIGHTABLE)],[]]
```
because its …

[NUI][AT-SPI] Apply AccessibilityHidden to Switch

---

src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
src/Tizen.Applications.Common/Tizen.Applications/CoreTask.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs

[NUI] master -> develNUI

---

src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs

1. Fix IsSet return false
- ACR: None.

[NUI] Fix IsSet return false

---

src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs

[NUI] DevelNUI => master 

---

src/Tizen.NUI/src/public/Window/BorderWindow.cs

[NUI] Sets the minimum / maximum  size to be resized by RequestResizeToServer.

[NUI] Sets the minimum / maximum size to be resized by RequestResizeToServer.

---

src/Tizen.Multimedia/Interop/Interop.MediaTool.cs
src/Tizen.Multimedia/MediaTool/MediaPacket.cs

* [MediaTool] Add new Create API to support increasing ref count

[NUI] Rebase master --> DevelNUI

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

[NUI] DragAndDrop: Add NotSupportedException for Multi-Window Feature

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs

[NUI] Fix AccessibilityCalculateStatesWrapper

---

src/Tizen.NUI.Components/Controls/Picker.cs

Fix Picker issues
1. issue that does not change the value to a key event.
2. issus that different currentValue with OnValueChanged.
3. issue of moving day scroller geometry from DatePicker abnormally.
No API Changes

[NUI] Fix Picker issues

---

src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.cs

Add missing exception documentation.
Change the initial value of nullable variable to avoid throwing exception.

[WebRTC] Fix DataChannel bug

---

src/Tizen.NUI/src/public/Animation/Animation.cs

Add comments for animation property

---

src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.cs
src/Tizen.Multimedia.Util/ImageUtil/ImageDecoder.cs
src/Tizen.Multimedia.Util/ImageUtil/ImageEncoder.cs
src/Tizen.Multimedia.Util/ImageUtil/ImageFormat.cs
src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Encode.cs

Master to devel n UI

---

test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSViewAccessibility.cs

The API for AccessibilityAttributes has changed with https://github.com/Samsung/TizenFX/pull/4389.
- ACR: None

[NUI][AT-SPI] Update AccessibilityAttributes tests

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs

[NUI] Add new constructor for BorderWindow
```c#
public NUIApplication(ThemeOptions option, IBorderInterface borderInterface)
public NUIApplication(Size2D windowSize, Position2D windowPosition, ThemeOptions option, IBorderInterface borderInterface)
```

[NUI] Add new constructor for BorderWindow

---

src/Tizen.Multimedia.Remoting/WebRTC/WebRTCError.cs

[WebRTC] Fix error value bug

---

src/Tizen.Multimedia.Remoting/Interop/Interop.WebRTC.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.Properties.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCEnums.cs

rebase master to DevelNUI
no API Changes

[WebRTC] Add new APIs for VideoFrameRate and bundle policy (#4381)

---

src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs

Handle error case while WebRTC is started asynchronously.
Fix documentation errors.

[WebRTC] Handle error while WebRTC is started asynchronously

---

src/Tizen.Applications.Common/Interop/Interop.Bundle.cs
src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs

- Add internal API 'Bundle.ImportFromArgv()'
-

Add internal API

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/277709/
- ACR:

[NUI] Make webcontext/cookiemanager static.

---

src/Tizen.NUI/src/public/Widget/WidgetView.cs

some of the docs about widgetView are incorrect.
so i fix them.
- ACR:

[NUI] Correct the signal related document of WidgetView

---

src/Tizen.NUI.Scene3D/Interop/Interop.Libraries.cs
src/Tizen.NUI.Scene3D/Interop/Interop.ModelView.cs
src/Tizen.NUI.Scene3D/Properties/AssemblyInfo.cs
src/Tizen.NUI.Scene3D/Tizen.NUI.Scene3D.csproj
src/Tizen.NUI.Scene3D/Tizen.NUI.Scene3D.sln
src/Tizen.NUI.Scene3D/src/ModelView.cs
src/Tizen.NUI/src/internal/Common/FriendAssembly.cs

1. Add Scene3D assembly
2. Add modelview class
- ACR: None.

[NUI] Add Scene3D assembly

---

src/Tizen.Log/Tizen/Log.cs

Signed-off-by: Youngjae Cho <y0.cho@samsung.com>
- ACR:

[Tizen.Log] Optimize getting filename

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

[NUI] Add MaskingMode property in imageView to use Rendering Time Masking

---

src/Tizen.Log/Tizen/Log.cs

Signed-off-by: Youngjae Cho <y0.cho@samsung.com>
- ACR:

[Tizen.Log] Optimize separator

---

src/Tizen.NUI.XamlBuild/src/public/XamlBuild/CreateObjectVisitor.cs

[XamlBuild] Correct the code format

---

src/Tizen.Log/Tizen/Log.cs

Rebase master to DevelNUI

---

src/Tizen.Applications.Cion/Interop/Interop.CionServer.cs
src/Tizen.Applications.Cion/Tizen.Applications.Cion/ServerBase.cs
src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCSignalingEventArgs.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCSignalingServer.cs

NUI rebase 22134

---

src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionManager.cs

Add feature for route
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-492
<!--
If you can't make the ACR, List all API changes here (or just put None), example:
Added:
Added:
- tizen.org/feature/network.route

[Connection][TCSACR-492] Add feature for route

---

src/Tizen.NUI/src/internal/Interop/Interop.WindowMovedSignal.cs
src/Tizen.NUI/src/internal/Window/WindowMovedSignal.cs
src/Tizen.NUI/src/public/Window/WindowEvent.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/BorderWindowTest.cs

Append window move event
This event occurs when window's position is changed.

[NUI] Append window move evnet

---

src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs

Correct the method names

---

src/Tizen.NUI.Components/Controls/AlertDialog.cs
src/Tizen.NUI.Components/Controls/Dialog.cs
src/Tizen.NUI.Components/Controls/Menu.cs
src/Tizen.NUI.Components/Controls/Popup.cs

This PR applies the new UX to Popup and related controls.
- ACR: None

[NUI][AT-SPI] Do not set Popup's sub-role to "Alert"

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PropertyNotificationTest.cs

[NUI] Add CurrentColor and CurrentScale as hidden API
- Added by the request of GBM
- example code is added in "test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PropertyNotificationTest.cs"
none

[NUI] Add CurrentColor and CurrentScale as hidden API

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

[NUI] Update CurrentSize, CurrentPosition, CurrentColor, CurrentScale's comments
- related to https://github.com/Samsung/TizenFX/pull/4492
- make up for the point of https://github.com/Samsung/TizenFX/pull/4492#issuecomment-1220295874
none

[NUI] Update CurrentSize, CurrentPosition, CurrentColor, CurrentScale's comments

---

src/Tizen.Uix.Tts/Interop/Interop.Tts.cs
src/Tizen.Uix.Tts/Tizen.Uix.Tts/ServiceStateChangedEventArgs.cs
src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs

Add new API for service state information
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-497

[Tts][TCSACR-497] Add new API for service state information

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

[NUI][TSCACR-496] Model ACR

---

src/Tizen.NUI.Scene3D/src/internal/CameraBindableProperty.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Camera.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Camera.cs

[NUI] Add Camera in Tizen.NUI.Scene3D

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

[NUI] Add comment for IsVisible(internal method)
none

[NUI] Add comment for IsVisible(internal method)

---

src/Tizen.NUI.Scene3D/src/public/Controls/Camera.cs

Modify to use Radian for the FoV of Tizen.NUI.Scene3D.Camera
- ACR:

[NUI] Use Radian for Camera FoV

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

[NUI] Add SceneView in Tizen.NUI.Scene3D

---

src/Tizen.NUI.Components/Controls/Picker.cs
src/Tizen.NUI.Components/Controls/TimePicker.cs
src/Tizen.NUI.Components/Style/PickerStyle.cs
src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs

Apply Tizen 7.0 GUI
No API Changes

[NUI] Picker: Apply Tizen 7.0 GUI

---

src/Tizen.Content.MediaContent/Interop/Interop.MediaInfo.cs
src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs

[MediaContent] Change P/Invoke function for thumbnail (#4533)

---

src/Tizen.NUI.Scene3D/src/public/Controls/Camera.cs

- Add Orthographic Size in Camera
- ACR:

[NUI] Modify Scene3D.SceneView and Camera

---

src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.Properties.cs
src/Tizen.Multimedia/Common/Display.cs

[Multimedia] Deprecate constructors related to ElmSharp (#4540)

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs

[NUI] Change Constructor index in SceneView

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
src/Tizen.NUI/src/public/DragAndDrop/DragEvent.cs
test/NUIDnDSource/NUIDnDSource.cs

Add drag and drop APIs
https://code.sec.samsung.net/jira/browse/TCSACR-487
- public static DragAndDrop Instance
- public void StartDragAndDrop(View sourceView, View shadowView, DragData dragData,  SourceEventHandler callback)
- public void AddListener(View targetView, DragAndDropEventHandler callback)
- public void RemoveListener(View targetView, DragAndDropEventHandler callback)

[NUI][TCSACR-487] DragAndDrop: Add drag and drop APIs

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

Add Set/Get IBL Scale Factor for SceneView and Model.
- ACR:

[NUI] Add Set/Get IBL Scale Factor for SceneView and Model

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

[NUI] Add documentation for Scene3D

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

Camera Transition for SceneView
- ACR:

[NUI] Add Camera Transition in SceneView

---

src/Tizen.NUI.Components/Controls/ScrollableBase.cs

[NUI] revert "[NUI] Modify the return value of OnAccessibilityPan()."
- ACR:

[NUI] revert "[NUI] Modify the return value of OnAccessibilityPan()."

---

src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs

Fix missing ObjectDisposedException bug.

[WebRTC] Fix ObjectDisposedException bug

---

src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs

The wrong `MediaSourceType` was set in pinvoke.

[WebRTC] Fix SupportedTransceiverCodecs bug

---

src/Tizen.Multimedia.Remoting/WebRTC/MediaFileSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaNullSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs

Add missing default value.
Fix wrong documentation in TransceiverDirection.

[WebRTC] Fix documentation bugs

---

src/Tizen.Multimedia.Vision/MediaVision/DeepLearningFaceRecognizer.cs

Fix recognize bug when there's no recognized face.

[MediaVision] Fix recognize bug

---

src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs

[NUI] Remove unused code

---

src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Face.cs
src/Tizen.Multimedia.Vision/MediaVision/DeepLearningFaceRecognizer.cs

[MediaVision] Change string marshal logic

---

src/Tizen.NUI.Scene3D/src/public/Controls/Camera.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

To ACR Tizen.NUI.Scene3D.Camera & Tizen.NUI.Scene3D.SceneView
- ACR: TCSACR-517

[NUI] ACR Tizen.NUI.Scene3D.Camera/SceneView

---

src/Tizen.NUI/src/internal/Interop/Interop.WindowIntPair.cs
src/Tizen.NUI/src/internal/Window/WindowIntPair.cs
src/Tizen.NUI/src/internal/Window/WindowMovedSignal.cs
src/Tizen.NUI/src/public/Window/Window.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/BorderWindowTest.cs

[NUI] Supports new native window position data type.
Previous native window data type can not support negative window coordinates.
New native window position data type support that.

[NUI] Support native new window position

---

src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs

[WiFi] Add missing lock

---

src/Tizen.Network.Stc/Interop/Interop.Stc.cs
src/Tizen.Network.Stc/Tizen.Network.Stc/StcStatsFilter.cs

* time_t type has different size on 32bit/64bit. so need to change type of interop method call parameter

[Stc] Fix datatype conversion issue

---

src/Tizen.NUI.Scene3D/src/internal/CameraBindableProperty.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Camera.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Camera.cs

Add new property to control major direction of camera FieldOfView.
It will effort to FieldOfView and OrthographicSize.
reference link : https://developer.apple.com/documentation/scenekit/scncamera/2878134-projectiondirection?language=objc

[NUI.Scene3D] Add ProjectionDirection in Camera

---

packaging/csapi-tizenfx.spec
pkg/Tizen.NET/runtime.json

This PR 
- adds RID for Tizen 7.0.0
- update `tizen.6.5.0-arm64` value which looks like it has to inherit from the previous version.

[Build] Add RID for 7.0.0

---

src/Tizen.NUI/src/public/Window/WindowEvent.cs

[NUI] Fix Apps crash issue when terminated
- change the Window's events codes as following View's events pattern.
- locally tested with RPI4 target.
none

[NUI] Fix Apps crash issue when terminated

---

src/Tizen.Applications.Common/Interop/Interop.ApplicationManager.cs
src/Tizen.Applications.Common/Tizen.Applications/ApplicationRunningContext.cs

To send the termination request without restarting, the method is added.
Adds:
- ApplicationRunningContext.TerminateWithoutRestarting()

[Applications.Common] Add a new internal API

---

src/Tizen.NUI.Components/Controls/Slider.Internal.cs
src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs

- The latest Slider UX for ValueIndicator has been applied. (Based on API10) 
1) `ValueIndicatorImage` has become a child of Thumb.
2) The style of `ValueIndicatorText` is added to the default theme.
3) Updated the position and size for value indicator.
- N/A

[NUI] Apply Tizen 7.0 UX on Slider ValueIndicator

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
src/Tizen.NUI/src/public/Window/Window.cs

[NUI] Change property get/set not to use PropertyValue (patch set3)
none

[NUI] Change property get/set not to use PropertyValue (patch set3)

---

src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs

[NUI] Fix type casting bug
- fix test hub fail, http://10.113.10.113/job/TIZEN_RPI4_CSHARP/5503/artifact/result/TCT_CSHARP/Tizen.NUI.Tests.xml#
none

[NUI] Fix type casting bug

---

src/Tizen.Applications.Badge/Interop/Interop.Badge.cs
src/Tizen.Applications.Badge/Tizen.Applications/BadgeControl.cs

Signed-off-by: SukhyungKang <shine.kang@samsung.com>
change return type of foreach callback for internal
- ACR: None

[Applications.Badge] change return type of foreach callback for internal

---

src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
src/Tizen.NUI.Components/Controls/RecyclerView/CollectionViewBindableProperty.cs
src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs

Minor refactoring.
- Use as type casing.
- Renaming Function.
- Divide long functions to small functions.
- ACR:

[NUI] Minor refactoring CollectionView and RecyclerView

---

src/Tizen.NUI/src/internal/Utility/ColorCutQuantizer.cs

dictionary -> concurrentdictionary for thread-safe
No API Changes

[NUI] Palette use ConcurrentDictionary for thread-safe

---

src/Tizen.NUI.Components/Controls/Picker.cs
src/Tizen.NUI.Components/Controls/ScrollableBase.cs

This is hot-fix for if the velocity has very small value, result is not updated even progress done.
No API Changes

[NUI] Fix picker, scroller animation gives abnormal position value

---

coverage.sh

Fix instrument error when there's no sources to be excluded

[Coverage] Fix bug

---

src/Tizen.NUI.Components/Tizen.NUI.Components.csproj

Include json files
There are no "loading" lottie animation json file, so broken image is shown

[NUI] Include json files

---

src/Tizen.NUI.Components/Controls/Picker.cs

Fix below Err.
Process terminated. A callback was made on a garbage collected delegate of type
No API Changes

[NUI] Picker: Protect delegate from GC

---

src/Tizen.NUI.Components/Controls/ScrollableBase.cs

[NUI] Fix the propertyNotification to be disposed in ScrollableBase
none

[NUI] Fix the propertyNotification to be disposed in ScrollableBase

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityProperties.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Common/PropertyValue.cs
src/Tizen.NUI/src/public/Window/Window.cs

[NUI] Remove debugging code
none

[NUI] Remove debugging code

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

* This should be merged with : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/283196/
* NUI_VISUAL_PROPERTY_CHANGE_X this macro will be deleted after all changes are completed.
* TODO : local test not been done. only Ubuntu tested

[NUI] Change property get/set not to use PropertyValue (patch set5)

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

Copy PR of https://github.com/Samsung/TizenFX/pull/4672

[NUI][API10] Change property get/set not to use PropertyValue (patch5)

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
src/Tizen.NUI/src/internal/Interop/Interop.Animation.cs
src/Tizen.NUI/src/internal/Interop/Interop.PropertyValue.cs
src/Tizen.NUI/src/public/Animation/Animation.cs
src/Tizen.NUI/src/public/Common/PropertyValue.cs

There was some PropertyValue creation during data conversion.
Let we reduce new PropertyValue class creation so GC feel happy

[NUI] Reduce PropertyValue creation during Animation

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
src/Tizen.NUI/src/internal/Interop/Interop.Animation.cs
src/Tizen.NUI/src/internal/Interop/Interop.PropertyValue.cs
src/Tizen.NUI/src/public/Animation/Animation.cs
src/Tizen.NUI/src/public/Common/PropertyValue.cs

There was some PropertyValue creation during data conversion. Let we reduce new PropertyValue class creation so GC feel happy
This patch is copy of https://github.com/Samsung/TizenFX/pull/4674

[NUI][API10] Reduce PropertyValue creation during Animation

---

src/Tizen.NUI.Components/Controls/TabBar.cs
src/Tizen.NUI.Components/Controls/TabView.cs

To help application to customize TabView and TabBar, some methods and properties have been modified.
- ACR:

[NUI] Modify TabView and TabBar to help customizing classes

---

src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs

this is backport commit on DevelNUI.
- ACR:

[NUI] Fix relative layout issue on DefaultLinearItem

---

src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs

This patch removes an unused variable.

[Applications.Common] Remove unused variable

---

src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs

[NUI] Correct code format

---

src/Tizen.NUI/src/internal/Common/Uint16Pair.cs

[NUI] Add native handle null check in Uint16Pair
none

[NUI] Add native handle null check in Uint16Pair

---

src/Tizen.NUI/src/public/Visuals/VisualMaps.cs

There was some missing implement for property for CornerRadiusPolicy.

[NUI] Add CornerRadiusPolicy property for VisualMap

---

src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

Add camera's FieldOfView animated by
Scene3D.SceneView's CameraTransition API.

[NUI.Scene3D] Transition animation with FieldOfView

---

src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs

add null type checking after as operation or change method parameter to not using as.
- ACR:

[NUI] add null type checking after as operation.

---

src/Tizen.NUI/src/public/Window/Window.cs

[NUI] Fixed crash when destroy border window.

[NUI] Fixed crash when destroy border window.

---

src/Tizen.NUI.XamlBuild/src/public/EXamlBuild/EXaml/EXamlAddToDictionary.cs
src/Tizen.NUI.XamlBuild/src/public/EXamlBuild/EXamlCreateObjectVisitor.cs
src/Tizen.NUI.XamlBuild/src/public/EXamlBuild/EXamlSetPropertiesVisitor.cs
src/Tizen.NUI.XamlBuild/src/public/EXamlBuild/Utility/EXamlOperationType.cs
src/Tizen.NUI.XamlBuild/src/public/XamlBuild/CreateObjectVisitor.cs

[NUI][EXaml] Support Dictionary

---

src/Tizen.NUI/src/public/Window/BorderWindow.cs

[NUI] Lets you know if the window is maximized.

[NUI] Lets you know if the window is maximized.

---

src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs

[WiFi] Add lock to _callback_map

---

src/Tizen.NUI.Components/Controls/TabContent.cs
src/Tizen.NUI.Components/Controls/TabView.cs

To help application to customize TabContent, some methods and properties have been modified.
- ACR:

[NUI] Modify TabContent to help customizing class

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

[NUI] Add Skybox in SceneView

---

src/Tizen.NUI/src/public/Common/NUIConstants.cs

[NUI] Add Desktop WindowType
dependency
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/283731/ https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/283891/

[NUI] Add Desktop WindowType

---

src/Tizen.NUI/src/public/Common/BaseHandle.cs

[NUI] Add back trace and debugging msg when native handle is null
none

[NUI] Add back trace and debugging msg when native handle is null

---

src/Tizen.NUI/src/public/Common/BaseHandle.cs

[NUI] Add back trace and debugging msg when SwigCPtr is null
none

[NUI] Add back trace and debugging msg when SwigCPtr is null

---

src/Tizen.NUI/src/public/Window/DefaultBorder.cs

[NUI] Changed from BaseHande to BindableObject, IDispose
- ACR:

[NUI] Changed from BaseHande to BindableObject, IDispose

---

src/Tizen.NUI/src/public/Window/DefaultBorder.cs

[NUI] remove unnecessary dispose code.
- ACR:

[NUI] remove unnecessary dispose code.

---

src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs

Sync the patch from DevelNUI.
- ACR:

[NUI][NUI.Components] Fix SVACE issue in CollectionView.

---

src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/WindowEvent.cs

[NUI] change View and Window events pattern matching with latest NUI
none

[NUI] change View and Window events pattern matching with latest NUI

---

.github/branch-metadata.yml

Update sync settings for API11

[Build] Update to sync API11 to tizen gerrit

---

src/Tizen.NUI/src/internal/WebView/WebContext.cs

[NUI] Update summary of RegisterHttpRequestInterceptedCallback

---

src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

Signed-off-by: seunghobaek <sbsh.baek@samsung.com>
- ACR:

[NUI] Add CameraTransitionFinished in SceneView

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

1. Send 'RedrawInScaleDown' property when we change URL.
2. Send these initialized informations when we create Image

[NUI] Implement missing properties for LottieAnimationView.

---

src/Tizen.NUI.Scene3D/src/internal/CameraBindableProperty.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Camera.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Camera.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

Let we use orthographicSize as native side.
And make it animatable
relative dali patches:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/283315
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/283941
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-demo/+/283942
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/283432
https://github.com/dalihub/dali-test/pull/45

[NUI.Scene3D] OrthographicSize native binding

---

src/Tizen.NUI/src/internal/Interop/Interop.Actor.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

The ScreenPositionSize api gets the screen position and size.
- ACR:

[NUI] Add ScreenPositionSize

---

test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/Tizen.NUI.Components.Devel.Tests.csproj
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSButton.Internal.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSDatePicker.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSPicker.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSProgress.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSScrollableBase.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSSlider.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSTabContent.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSTimePicker.cs

Fix build errors of NUI.Components.Devel base on latest codes.
- ACR:

[NUI][NUI.Components.Devel] Fix build errors of NUI.Components.Devel.

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/internal/Common/Object.cs
src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
src/Tizen.NUI/src/internal/Interop/Interop.Actor.cs
src/Tizen.NUI/src/internal/Interop/Interop.ActorInternal.cs
src/Tizen.NUI/src/internal/Interop/Interop.Animation.cs
src/Tizen.NUI/src/internal/Interop/Interop.PropertyValue.cs
src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/public/Animation/Animation.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Common/PropertyValue.cs

[NUI] Remove useless macros
none

[NUI] Remove useless macros

---

.github/workflows/build-branches.yml
.github/workflows/build-pull-request.yml
.github/workflows/check-api-level.yml
.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml
.github/workflows/deploy-packages.yml
.github/workflows/nightly-release.yml
.github/workflows/postback-pull-request.yml

ubuntu-latest is using ubuntu-22.04, But our workflow is not ready to the latest ubuntu. So specify the version of workflow image to 20.04.

[Build] Use ubuntu-20.04 

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView.cs
src/Tizen.NUI/src/internal/WebViewUrlChangedEventArgs.cs

https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/284834/
- ACR:

[NUI] Add webview API for url,change event.

---

src/Tizen.NUI/src/internal/Interop/Interop.GLView.cs
src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
src/Tizen.NUI/src/public/Common/Matrix.cs
src/Tizen.NUI/src/public/Common/Rectangle.cs

DirectRenderingGLView is for in-house apps.
DirectRenderingGLView allows you to render to a Window directly using OpenGL.

[NUI] Add DirectRenderingGLView

---

src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseHandle.cs

[NUI] Add implicit dispose check
- Add implicit disposed status check code for TouchEvent and PropertySet event handler which is frequently used
none

[NUI] Add implicit dispose check

---

src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs

To improve the performance of calling ToLower() and ToUpper(), the thread prints logs.

[Applications.Common] Improve performance

---

src/Tizen.NUI/Tizen.NUI.csproj

[NUI] fix for PROFILE_TV to be defined and be applied
- it is defined at common.props so should not be overwritten
none

[NUI] fix for PROFILE_TV to be defined and be applied

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Theme/ThemeManager.cs

[NUI] Not set style in PROFILE_TV
none

[NUI] Not set style in PROFILE_TV

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView.cs

https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/285284/
- ACR:

[NUI][Tizen] Add an API for create,window event.

---

src/Tizen.NUI/src/public/Window/Window.cs

Fix svace issue : DF221207-00724 .
- ACR:

[NUI] Fix svace issue (DF221207-00724).

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Common/StyleManager.cs
src/Tizen.NUI/src/public/Input/FocusManager.cs
src/Tizen.NUI/src/public/Theme/DefaultThemeTV.cs
src/Tizen.NUI/src/public/Theme/ThemeManager.cs

[NUI] sync with API10

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Input/FocusManager.cs
src/Tizen.NUI/src/public/Theme/ThemeManager.cs

[NUI] make Theme not be loaded in tv profile
none

[NUI] make Theme not be loaded in tv profile

---

src/Tizen.NUI/src/internal/Common/Registry.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

[NUI] fix the defect that the focus of VitualRemote App is stuck very rarely
- the error occurs when the Registry's weakReference.Target is null
- add some defensive codes to check the null value and Dictionary adding retry
none

[NUI] fix the defect that the focus of VitualRemote App is stuck very rarely

---

src/Tizen.NUI/Tizen.NUI.csproj

1. Remove unused reference 
- ACR:

Remove unused reference 

---

packaging/csapi-tizenfx.spec

[NUI] dummy patch to raise version up

---

src/Tizen.Multimedia.Camera/Camera/CameraSettings.cs
src/Tizen.Multimedia.Camera/Interop/Interop.CameraSettings.cs

Fix pinvoke function call bugs and add internal API for preview frame rotation.

[Camera] Fix bugs for ExtraPreview

---

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
src/Tizen.NUI/src/public/Common/PropertyNotification.cs
src/Tizen.NUI/src/public/Events/PanGestureDetector.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeWithoutEventUnsubscribedTest.cs

[NUI] fix testhub crash issue
- Add PanGesture and PropertyNotification class's Dispose()
- tested OK by sample of DisposeWithoutEventUnsubscribedTest.cs
none

[NUI] fix testhub crash issue

---

src/Tizen.NUI/src/internal/EXaml/Operation/GatherType.cs

[NUI][SVACE] Fix svace(DF221214-00106) issue.

---

src/Tizen.NUI/src/public/Common/BaseHandle.cs

[NUI] fix testhub fail, Add Dispose() in BaseHandle.Reset() where the body was deleted in previous patch
none

[NUI] fix testhub fail, Add Dispose() in BaseHandle.Reset() where the body was deleted in previous patch

---

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs

Fix overflow issue during converting structure
https://github.sec.samsung.net/dotnet/home/issues/435
- ACR:

[Bluetooth] Fix overflow issue

---

src/Tizen.NUI.XamlBuild/src/public/XamlBuild/CompiledConverters/ExtentsTypeConverter.cs

1. Fix extents convert issue 
- ACR:

Fix extents convert issue 

---

test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/Properties/Resources.Designer.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/Properties/Resources.resx
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/Tizen.NUI.Components.Devel.Tests.csproj
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSButton.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSDatePicker.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSImageScrollBar.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSPicker.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSTimePicker.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSToast.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/tizen-manifest.xml

Fixed conflicts issue of PR:4792.
- ACR:

[NUI][NUI.Components.Devel] Fix failed isseus of NUI.Components.Devel.

---

src/Tizen.NUI/src/public/Images/PixelBuffer.cs
src/Tizen.NUI/src/public/Images/PixelData.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/Images/TSImageLoader.cs

Revert patch of PR #4897
This reverts commit 0e6528a5f7c4ae6523b8dd0c19b2c211c31178f3.

[NUI] Revert "Make PixelBuffer & PixelData as Disposable"

---

src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs

The ImportFromArgv() method is changed. 
This request adds descriptions and throwing an exception.

[Applications.Common] Modify ImportFromArgv method of Bundle

---

src/Tizen.NUI/src/public/Window/BorderWindow.cs

If you resize the window several times, there may be a problem with the configure event with the window server.
So avoid resizing the window as many times as possible.
- ACR:

[NUI] Window resizing is performed in one step if possible.

---

src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs

Remove log prints in the thread (#4920)

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

[NUI][API10] Load bvh file format

---

test/Tizen.NUI.Scene3D.Sample/Scene3DSample.cs

1. Collect all private values in upward of source code.
2. Formatting C#
3. MilliSeconds --> Milliseconds
4. Add some comments

[NUI] Apply missing comments for Scene3D demo

---

src/Tizen.NUI/src/public/Theme/ThemeManager.cs

[NUI] Prevent NullReferenceException when creating TextLabel

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

Since we create new handle at csharp binder, we should call DeleteHandle function.

[NUI][Scene3D][API10] Fix memory leak issue for Model's Animation

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/EncodedImageSample.cs

Add sample to use EncodedImageBuffer.

[NUI] Fix ImageUrl.Dispose issue + Add EncodedImageBuffer sample

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

This PR is FrontPorting of #4827

[NUI][Scene3D] Load bvh file format

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

[NUI][Scene3D] FBO MultiSamplingLevel Property for SceneView

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

[NUI][Scene3D][API10] FBO MultiSamplingLevel Property for SceneView

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetLifecycleChangedEventArgs.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetLifecycleState.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetType.cs

The NUIGadget feature is supported from API10. The description of the API version is changed to API10.

[NUI.Gadget] Change API version of NUI.Gadget

---

src/Tizen.NUI.Components/Theme/DefaultTheme.cs
src/Tizen.NUI/src/public/Theme/ThemeManager.cs

[NUI] Disable compiler warnings complaining about theme off in TV profile

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs

[NUI.Gadget] Fix static analysis issue

---

src/Tizen.Uix.Tts/Tizen.Uix.Tts/ExceptionFactory.cs

Raise proper exception for screen reader off error from native library.

[Tts] Raise exception for screen reader off error from native library

---

src/Tizen.NUI.Scene3D/src/public/Controls/Camera.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

[NUI.Scene3D] Remove warning messages

---

src/Tizen.NUI/src/public/Theme/ThemeManager.cs

[NUI] Prevent NullReferenceException when initialize style.

---

src/Tizen.NUI.Components/Controls/TabItem.cs
src/Tizen.NUI.Components/Controls/TabView.cs
test/NUITizenGallery/Examples/TabViewTest/TabViewTestPage.xaml
test/NUITizenGallery/Examples/TabViewTest/TabViewTestPage.xaml.cs
test/NUITizenGallery/Examples/TabViewTest/TabViewWithIconOnlyTestPage.xaml
test/NUITizenGallery/Examples/TabViewTest/TabViewWithIconOnlyTestPage.xaml.cs
test/NUITizenGallery/Examples/TabViewTest/TabViewWithIconTestPage.xaml
test/NUITizenGallery/Examples/TabViewTest/TabViewWithIconTestPage.xaml.cs

To support TabView in xaml, TabItem has been added.
TabView provides Add(TabItem) to add a tab from the given TabItem.
TabItem contains Title, IconURL of a new TabButton in TabView's TabBar
and Content of a new View in TabView's TabContent.
- ACR:

[NUI] Add TabItem to support TabView in xaml

---

src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs

[NUI] Fix switch animation bug

---

src/Tizen.NUI.Components/Controls/Slider.Internal.cs
src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
test/Tizen.NUI.StyleGuide/Examples/SliderExample.cs

- Update Slider ValueIndicatorImage / Text to change its size depending on the content.
- Thumb size uses natural size of its image size.
- Update Slider style guide sample for ValueIndicator
- N/A

[NUI] Fix Slider ValueIndicatorImage and Thumb size

---

src/Tizen.Multimedia.Camera/Camera/Camera.Properties.cs
src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Display.cs
src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroring.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
src/Tizen.Multimedia/Common/Display.cs

fix to set window size properly
(DF230214-00262)

[MediaPlayer] fix to set window size properly

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Camera.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

Change default camera generate API as 3D engine style.
This patch required to merge below 3 patches.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/288491
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/288490
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/288488

[NUI.Scene3D] Change native default camera create API

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
test/NUIDnDSource/NUIDnDSource.cs

DragAndDrop : don't reuse drag window

[NUI] DragAndDrop : don't reuse drag window

---

src/Tizen.NUI.Components/Controls/Loading.cs
src/Tizen.NUI.Components/Controls/Progress.cs
src/Tizen.NUI.Components/Style/LoadingStyle.cs

* Progress
Previously, the Progress did not update the distance of the indeterminate animation on resize.
* Loading
Add a property that can help to set lottie animation image url. This is for using Theme.
- ACR:

[NUI] Fix Progress and improve Loading

---

test/NUITizenGallery/Examples/TabViewTest/TabViewWithIconOnlyTestPage.xaml
test/NUITizenGallery/Examples/TabViewTest/TabViewWithIconTestPage.xaml

Fix bulid error in NUITizenGallery.
Fix typo IconURL->IconUrl
- ACR:

[NUI][NUITizenGallery] fix build error.

---

src/Tizen.NUI/src/internal/Layouting/RelativeLayout.cs

[NUI] fix relative layout to fill regardless of children size.

---

src/Tizen.NUI/src/internal/Interop/Interop.AccessibilityManager.cs
src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs

- ShowInsideFridge() can tell which app is at the top of the layer.
- Dependencies :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/288772/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/288773/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/288774/
- N/A

[NUI] Add ShowInsideFridge function for Accessibility

---

src/Tizen.NUI.XamlBuild/src/public/XamlBuild/CompiledConverters/ExtentsTypeConverter.cs

1. Fix extents convert issue.
- ACR: None.

[XamlBuild] Fix extents convert issue

---

src/Tizen.NUI/src/internal/Common/FriendAssembly.cs

[NUI] Add friend assembly for NUI FLUX
none

[NUI] Add friend assembly for NUI FLUX

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs

When we create ImageView with url, It will create image visual twice. To avoid this situation, make we replace internal url value for creation time.
And also, setup some missing values when we inputed desired size.
Test for load 10,000 ImageView with 50 kind of difference images in Ubuntu
Before : 2,764 ms
After : 1,659 ms

[NUI] Remove duplicate URL settup

---

.github/workflows/check-api-level.yml
.github/workflows/postback-pull-request.yml

update action script methods for the changes on actions/github-script v6

update action script methods

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

This patch is to remove unused field in View. Since View is frequenstly used so it always need to be compact.
- ACR:

[NUI] Remove unused field in View

---

src/Tizen.NUI/src/public/Events/LongPressGestureDetector.cs
src/Tizen.NUI/src/public/Events/PinchGestureDetector.cs
src/Tizen.NUI/src/public/Events/RotationGestureDetector.cs
src/Tizen.NUI/src/public/Events/TapGestureDetector.cs

[NUI] Add Dispose to GestureDetector and modify ReleaseSwigCPtr.

---

.github/workflows/build-pull-request.yml
.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml
.github/workflows/deploy-packages.yml
.github/workflows/nightly-release.yml

Update deprecated actions

---

src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
src/Tizen.NUI.Components/Controls/Navigation/Page.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
src/Tizen.NUI.Components/Utils/NUIWindowExtensions.cs
test/NUITizenGallery/NUITizenGallery.cs
test/Tizen.NUI.StyleGuide/Examples/NavigatorExample.cs
test/Tizen.NUI.StyleGuide/Tizen.NUI.StyleGuide.cs

Apply back navigation modification api10

---

src/Tizen.Nlp/Tizen.Nlp/LanguageDetectedResult.cs
src/Tizen.Nlp/Tizen.Nlp/NamedEntityRecognitionResult.cs
src/Tizen.Nlp/Tizen.Nlp/NaturalLanguageProcess.cs
src/Tizen.Nlp/Tizen.Nlp/PosTagResult.cs
src/Tizen.Nlp/Tizen.Nlp/WordTokenizeResult.cs

Deprecated NLP APIs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-528

[NLP] Deprecated NLP APIs

---

src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs

[NUI] Fix collectionView Selection on Item.

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Camera.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

Load facial blendshape animation from json format.
- ACR:

[NUI.Scene3D] Load facial blendshape animation

---

test/AIAgentLayer/AIAgentLayer.cs

[NUI] AIAgentLayer : fix animation usage issue

[NUI] AIAgentLayer : fix animation usage issue

---

src/Tizen.NUI/src/public/Theme/ExternalThemeManager.cs

[NUI] Change log info to debug in NUI.ThemeManager

---

.github/workflows/nightly-release.yml
.github/workflows/postback-pull-request.yml

Update postback PR

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetResourceManager.cs

* [NUI.Gadget] Add NUIGadgetResourceManager class
To support multi language, a new class is added.
Adds:
- NUIGadgetResourceManager

[NUI.Gadget] Support Internationalization

---

src/Tizen.NUI/src/public/Window/DefaultBorder.cs

[NUI] Remove unnecessary gesture events from DefaultBorder.
- ACR:

[NUI] Remove unnecessary gesture events from DefaultBorder.

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest.cs

Add RotationCompletedAcknowledgement APIs in Window.
The APIs are SetNeedsRotationCompletedAcknowledgement and SendRotationCompletedAcknowledgement

[NUI] Add RotationCompletedAcknowledgement APIs

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

[NUI] DragAndDrop : allow to control shadow view opacity

[NUI] DragAndDrop : allow to control shadow view opacity

---

src/Tizen.Applications.PackageManager/Interop/Interop.Libraries.cs
src/Tizen.Applications.PackageManager/Interop/Interop.PackageManagerInternal.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs

Add APIs for internal
- Tizen.PackageManager.ActivatePackage()
- Tizen.PackageManager.DeactivatePackage()
- ACR: N/A

[Packagemanager] Add APIs for internal

---

src/Tizen.Multimedia.Camera/Camera/Camera.Properties.cs
src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroring.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
src/Tizen.Multimedia/Common/Display.cs

Fix rotation issue for portrait mode

[Multimedia] Fix rotation issue for portrait mode

---

src/Tizen.NUI.Components/Controls/Button.Internal.cs
src/Tizen.NUI.Components/Controls/Button.cs
src/Tizen.NUI.Components/Controls/Extension/ButtonExtension.cs
src/Tizen.NUI.Components/Controls/Extension/LottieButtonExtension.cs
src/Tizen.NUI.Components/Controls/Extension/LottieSwitchExtension.cs
src/Tizen.NUI.Components/Controls/Extension/SwitchExtension.cs
src/Tizen.NUI.Components/Controls/Switch.cs
src/Tizen.NUI.Components/PreloadStyle/OverlayAnimationButtonStyle.cs

* Rename some functions to better match the design intent.
* Extract Helper class to provide common methods used by multiple classes.
- ACR:

[NUI] Refactor ButtonExtension

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

This PR is FrontPort of #4922
- ACR:

[NUI] Add GetOverlayLayer in NUI window.

---

src/Tizen.NUI/src/public/Window/WindowEvent.cs

[NUI] Add interceptTouchEvent at WindowEvent
- ACR:

[NUI] Add interceptTouchEvent at WindowEvent

---

src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/ItemsLayouter.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs

to create customized collectionView and Layouters, some properties must be extendable.
this change includes properties access modifier
which is internal or private to protected or public.
- ACR:

[NUI] refactoring collectionView and Layouters for extended class

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Common/NUIConstants.cs
src/Tizen.NUI/src/public/Window/Window.cs

The new `SetLayout` method allows users to easily snap windows to specific positions and sizes. This feature is allowing users to quickly arrange their windows in a convenient and efficient manner.
DALi:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/290338/
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/290377

[NUI] Introduce WindowLayoutType enum and SetLayout Method

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SpringAnimationSample.cs

Simple sample with custom alpha function

[NUI.Samples] Add sample for spring like animation

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SpringAnimationSample.cs

[NUI.Samples] Fix visual defect for SpringAnimationSample

---

src/Tizen.NUI/src/internal/Interop/Interop.ActorInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

Add helper API to rotate View to lookAt specific position.
It will be helpful if user have some problem to calculate
Orientation property
Note : This API only for change View.Orientation. Not for constraint.
This PR depend on below dali patches :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/290532
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/290533

[NUI] Add view helper API to rotate : LookAt

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Material.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelPrimitive.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/Material.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/MaterialAlphaModeType.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/MaterialTextureType.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelPrimitive.cs

[NUI] Use ModelNode for the child of Model

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebBackForwardList.cs
src/Tizen.NUI/src/internal/WebView/WebHttpRequestInterceptor.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

Related patch at csharp-binder:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/290848/
- ACR:

[NUI] Add a LoadContents API with byte array for WebView.

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebBackForwardList.cs
src/Tizen.NUI/src/internal/WebView/WebHttpRequestInterceptor.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

Related patch at csharp-binder side:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/290876/
- ACR:

[NUI][API10] Add a LoadContents API with byte array for WebView.

---

src/Tizen.NUI/src/internal/Interop/Interop.Rotation.cs
src/Tizen.NUI/src/public/Common/Rotation.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/Common/TSRotation.cs

Add API that we can set Rotation by pitch/yaw/roll + Get Rotation informations as pitch/yaw/roll
Rotation apply order is x, y, and z. (pitch->yaw->roll)
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/291144

[NUI] Rotation class with EulerAngle (pitch/yaw/roll)

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetLifecycleState.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetResourceManager.cs

- Remove an unnecessary space
- Remove an unnecessary semicolon
- Change descriptions

[NUI.Gadget] Clean up

---

src/Tizen.Applications.Common/Interop/Interop.AppControl.cs
src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs

To unset the auto restart setting, a new internal API is added.
Adds:
- AppControl.UnsetAutoRestart()

[Applications.Common] Add an internal API

---

src/Tizen.NUI/src/public/Window/WindowEvent.cs

[NUI] Add defence code for Window.VisibilityChanged event
none

[NUI] Add defence code for Window.VisibilityChanged event

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

This PR s backport of #5078 and #5187
- ACR:

[NUI.Scene3D] Make bvh/facial Animation from string buffer

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs

1. Fix NUIApplication svace issue  (DF230418-00755)
- ACR: None

Fix NUIApplication svace issue 

---

src/Tizen.NUI/src/public/Animation/Animation.cs

1. Change mismatched comment format
2. Change default value of DisconnectAction
3. Add some remarks at EndAction property

[NUI] Fix some comments of Animation class

---

src/Tizen.NUI/src/internal/Interop/Interop.FontClient.cs
src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/Style/TextEditorStyle.cs
src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
src/Tizen.NUI/src/public/Common/NUIConstants.cs
src/Tizen.NUI/src/public/Theme/DefaultThemeCommon.cs
src/Tizen.NUI/src/public/Utility/FontClient.cs

Add major patches related to `GetSystemFonts` API and SystemSettings(Font).
These patches have already been merged into `DevelNUI` and `master`.
Related patches :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/291972/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/291944/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/291973/

[NUI] Add GetSystemFonts in FontClient

---

src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
src/Tizen.NUI/src/public/Animation/Animatable.cs
src/Tizen.NUI/src/public/Common/Property.cs

- arg0형태의 이름을 animatable로 변경
- internal의 public 프로퍼티의 첫글자 소문자를 대문자로 변경

[NUI] Modify property name of Property class

---

src/Tizen.Data.Tdbc/Tizen.Data.Tdbc/Sql.cs

[Tdbc] Fix binding methods

---

src/Tizen.NUI/src/internal/Interop/Interop.Animation.cs
src/Tizen.NUI/src/public/Animation/Animation.cs

Let we allow to animation auto_reversed

[NUI] LoopingMode enum for Animation class

---

src/Tizen.Data.Tdbc.Driver.Sqlite/Tizen.Data.Tdbc.Driver.Sqlite/Connection.cs
src/Tizen.Data.Tdbc.Driver.Sqlite/Tizen.Data.Tdbc.Driver.Sqlite/Statement.cs

Fix static analysis issues
- ACR: N/A

[Tdbc] Fix static analysis issues

---

src/Tizen.Log/Tizen.Log.csproj

[Tizen.Log] Fix gbs build error

---

src/Tizen.NUI/src/internal/Interop/Interop.FocusManager.cs
src/Tizen.NUI/src/public/Input/FocusManager.cs

Binding EnableFocusIndicator and IsFocusIndicatorEnabled
refer : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/292280/
- ACR:

[NUI] Binding EnableFocusIndicator and IsFocusIndicatorEnabled

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

[NUI.Scene3D] Add property for bvh that translate by RootNode or not

---

src/Tizen.Multimedia.Vision/MediaVision/BarcodeGenerator.cs

[MediaVision] Fix Design QR bug

---

src/Tizen.Multimedia.Vision/MediaVision/BarcodeGenerationConfiguration.cs
src/Tizen.Multimedia.Vision/MediaVision/BarcodeGenerator.cs
src/Tizen.Multimedia.Vision/MediaVision/QrConfiguration.cs
src/Tizen.Multimedia.Vision/MediaVision/QrShape.cs

Add internal APIs for Design QR feature.
These APIs are merged in API11(TCSACR-534) already and VD requested that merge these APIs into API10 also.

[MediaVision] Add internal APIs for Design QR feature

---

src/Tizen.NUI/src/public/ViewProperty/Shadow.cs

[NUI] Remove duplicate ?. operator and use using statement

---

src/Tizen.NUI/src/internal/Interop/Interop.Animation.cs
src/Tizen.NUI/src/public/Animation/Animation.cs

[NUI] Add BlendPoint to blend animation of AnimateBetween

---

src/Tizen.NUI/src/public/Events/Gesture.cs

```c++
panGestureDetector.Detected += (s, e) =>
{
if (Gesture.SourceType.Mouse == e.PanGesture.Source)
{
}
else if (Gesture.SourceType.Touch == e.PanGesture.Source)
{
}
};
```
refer :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/292503/
- ACR:

[NUI] Add Touch source type for gesture

---

src/Tizen.NUI.Wearable/src/public/NUIWatchApplication.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs

Fix SVACE issues.

---

src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.TaskbarService.cs
src/Tizen.NUI.WindowSystem/src/public/TaskbarService.cs

We introduce the taskbar-service feature in Tizen.NUI.WindowSystem.Shell (internal)
- ACR: N/A
Added:
Class 
- TaskbarService
APIs
- void SetPlaceType(PlaceType type)
- void SetSize(uint width, uint height)

[NUI.WindowSystem] introduce the taskbar service feature

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/BlendPointSample.cs
test/Tizen.NUI.Scene3D.Sample/Scene3DSample.cs

Let we use blendpoint on Scene3DSample and BlendPointSample

[NUI.Sample] BlendPoint demo

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

Add missing comments on API10. (This comment is exist on API11)
- ACR:

[NUI.Scene3D] Remove build warning

---

test/Tizen.NUI.Scene3D.Sample/Scene3DSample.cs

Let we use blendpoint on Scene3DSample

[NUI.Scene3D.Sample] BlendPoint demo

---

src/Tizen.Data.Tdbc.Driver.Sqlite/Tizen.Data.Tdbc.Driver.Sqlite/Connection.cs
src/Tizen.Log/Tizen.Log.csproj
src/Tizen.Multimedia.Vision/MediaVision/BarcodeGenerator.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetResourceManager.cs
src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.TaskbarService.cs
src/Tizen.NUI.WindowSystem/src/public/TaskbarService.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/BluetoothPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/BrowserPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/DevicePolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/DevicePolicyManager.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/EmailPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/LocationPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/MediaPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/PasswordPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/PasswordQuality.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/PolicyChangedEventArgs.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/StoragePolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/TelephonyPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/UsbPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/WifiPolicy.cs
src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/PrivacyPrivilegeManager.cs

Rebase long pending PRs from master to DevelNUI

[NUI] Rebase master 0515

---

packaging/csapi-tizenfx.spec
packaging/csapi-tizenfx.spec.in
src/Tizen.System.Session/Interop/Interop.Libraries.cs
src/Tizen.System.Session/Interop/Interop.Session.cs
src/Tizen.System.Session/Session/Session.cs
src/Tizen.System.Session/Session/SessionEnums.cs
src/Tizen.System.Session/Session/SessionErrorFactory.cs
src/Tizen.System.Session/Session/SessionEventArgs.cs
src/Tizen.System.Session/Session/SessionStructs.cs
src/Tizen.System.Session/Tizen.System.Session.csproj

Implemented a wrapper for sessiond.  Changes placed into `src/Tizen.System.Session`.
Not applicable
- `int Session.CurrentUID` - Field
- `int Session.MaxUserLength` - Field
- `string Session.EmptyUser` - Field
- `Session Session.GetInstance(int sessionUID)`
- `int sessionObj.SessionUID` - Property
- `IReadOnlyList<string> sessionObj.GetUsers()`
- `string sessionObj.GetCurrentUser()`
- `Task sessionObj.SubsessionAddUserAsync(string userName)`
- `Task sessionObj.SubsessionRemoveUserAsync(string userName)`
- `Task sessionObj.SubsessionSwitchUserAsync(string userName)`
- `void sessionObj.SubsessionEventMarkAsDone(SubsessionEventArgs subsessionEventArgs)`
- `event sessionObj.EventHandler<AddUserEventArgs> AddUserWait`
- `event sessionObj.EventHandler<RemoveUserEventArgs> RemoveUserWait`
- …

Implement libsessiond wrapper

---

packaging/csapi-tizenfx.spec
packaging/csapi-tizenfx.spec.in
src/Tizen.System.Session/Interop/Interop.Libraries.cs
src/Tizen.System.Session/Interop/Interop.Session.cs
src/Tizen.System.Session/Session/Session.cs
src/Tizen.System.Session/Session/SessionEnums.cs
src/Tizen.System.Session/Session/SessionErrorFactory.cs
src/Tizen.System.Session/Session/SessionEventArgs.cs
src/Tizen.System.Session/Session/SessionStructs.cs
src/Tizen.System.Session/Tizen.System.Session.csproj

Second phase of rebase from master to DevelNUI

[NUI]Rebase master 0515 - 2

---

src/Tizen.Applications.Common/Interop/Interop.AppCommon.cs
src/Tizen.Applications.Common/Tizen.Applications/DirectoryInfo.cs

- DirectoryInfo.GetResControlAllowedResource()
- DirectoryInfo.GetResControlGlobalResource()

[Application.Common] Add internal APIs for getting path related resource control

---

src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs

[NUI][API10] Fix a SVACE issue in RecyclerViewItem.cs

---

src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

To avoid useless PropertyValue class creation, let we change to visual use InternalVisual APIs.

[NUI] Let LottieAnimationView use InternalVisual API

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

Component style can change even if the platform theme is disabled
- ACR:

[NUI] Fix theme applied issue

---

src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs

[NUI] Add Comment on the View.VisibilityChanged event

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetResourceManager.cs

If getting string is failed, the resource manager should try to get string from the default satelite assembly.

[NUI.Gadget] Modify NUIGadgetResourceManager

---

src/Tizen.NUI/src/public/Window/BorderWindow.cs
src/Tizen.NUI/src/public/Window/DefaultBorder.cs
src/Tizen.NUI/src/public/Window/IBorderInterface.cs

[NUI] Add moveCompleted and resizeCompleted api on BorderWindow
- ACR:

[NUI] Add MoveCompleted and ResizeCompleted api on BorderWindow

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

[NUI] Fix incorrect calculation of configGestureCount.
- ACR:

[NUI] Fix incorrect calculation of configGestureCount.

---

src/Tizen.NUI/src/internal/WebView/WebContext.cs
src/Tizen.NUI/src/internal/WebView/WebCookieManager.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Unregister callbacks when passed argument is null.

---

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
src/Tizen.NUI/src/public/Common/Container.cs

[NUIComponents] Roll back error modification

---

src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionData.cs
test/Tizen.NUI.Scene3D.Sample/Scene3DSample.cs

Let we remove to access list of MotionData directly,  since this class could be bind from DALi.

[NUI.Scene3D] Deprecate direct accessor to motion value list

---

src/Tizen.Applications.Notification/Interop/Interop.Notification.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/Notification.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationBinder.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationResponseEventType.cs
src/Tizen.Applications.NotificationEventListener/Interop/Interop.NotificationEventListener.cs
src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationEventArgs.cs
src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationEventArgsBinder.cs
src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationEventArgsEnumerations.cs
src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationListenerManager.cs

Add api and property to set and get check box status.
- ACR: None

[Notification/NotificationEventListener] Add check box for notification

---

src/Tizen.Applications.ThemeManager/Tizen.Applications.ThemeManager/ThemeLoader.cs

Clear current theme cache when theme changed
- ACR: N/A

[ThemeManager] Clear current theme cache when theme changed

---

src/Tizen.NUI/src/internal/Interop/Interop.KeyFrames.cs
src/Tizen.NUI/src/public/Animation/KeyFrames.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/TSKeyFrames.cs

1. `GetKeyFrameCount()` to know how many keyframes are added.
2. `GetKeyFrame()` to know the information of specific index.
3. `SetKeyFrameValue()` to change the value for specific index.

[NUI] Add some API for KeyFrames

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Interop/Interop.Application.cs

Fix Application Argv issue in UI Thread.
The input param is missed in this case. This PR is to fix it.

[NUI] Fix application argv issue

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs

[NUI] Remove useless log + Add todo mark about it

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Light.cs
src/Tizen.NUI.Scene3D/src/public/Light/Light.cs

Directional light is one of light option in 3D Graphics.
All fragments receive light from the same direction.
One of the example of Directional Light is sun light.
In this patch, includes Light class that control one of light source, color and direction.
This light class object will be added on SceneView, and every object in the SceneView affect by this light.
SceneView can support up-to 5 activated lights in the same time.
- ACR:

[NUI] Add Directional Light on Scene3D

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableFocus/ScrollableFocusSample.cs

Add LazyFeedHover api for HoverEvent
This api feeds a hover event into the window.
```c++
public class CustomScrollableBase : ScrollableBase
{
public override bool OnWheel(Wheel wheel)
{
base.OnWheel(wheel);
Window window = NUIApplication.GetDefaultWindow();
window.LazyFeedHover();
return true;
}
}
public void Activate()
{
...
var scrollview = new CustomScrollableBase
{
ScrollingDirection = ScrollableBase.Direction.Vertical,
WidthSpecification = LayoutParamPolicies.MatchParent,
HeightSpecification = LayoutParamPolicies.MatchParent,
BackgroundColor = Color.Gray
};
...
}           
```
refer :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/294676/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/294689/
- ACR:

[NUI] Add LazyFeedHover api for HoverEvent

---

src/Tizen.NUI/src/public/Common/Matrix.cs
src/Tizen.NUI/src/public/Common/Matrix3.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/Common/TSMatrix.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/Common/TSMatrix3.cs

Write some comments for Matrix / Matrix3 class.

[NUI] Write comments for Matrix

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

Sets whether the scene will update partial area or full area.
If `PartialUpdate` is true, window will update & render partial area.
If false, full area updated.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/294634
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/294635
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/294637

[NUI] Partial update feature enable/disable for window

---

src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs

- Except for TV and wearable profiles, FontSizeScale values are updated.
- N/A

[NUI] Update FontSizeScale values

---

src/Tizen.NUI.Components/Theme/DefaultTheme.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Theme/ThemeManager.cs

This is cherry-pick of https://github.com/Samsung/TizenFX/pull/5366 to API10
- ACR:

[NUI] Disable ThemeManager preload

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

Binding IsFloatingModeEnabled() api
refer :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/295493/ 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/295494/
- ACR:

[NUI] Binding IsFloatingModeEnabled()

---

src/Tizen.NUI/src/public/Window/BorderWindow.cs

Register OrientationChanged for BorderWindow.
Because if the window is rotated, we need to resize the window by recalculating the border area.
- ACR:

[NUI] Register OrientationChanged for BorderWindow.

---

src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSTextUtils.cs

- The font size scales are changed according to the latest GUI guide.
- Five stages of Font size scale : : 87% -> 100% -> 113% -> 126% -> 140 %
- N/A

[NUI] Update Font size scale again based on the updated guide

---

src/Tizen.NUI/src/internal/Application/Application.cs

[NUI] Fix SVACE issue.

---

src/Tizen.Applications.RemoteView/Tizen.Applications/RemoteView.cs
src/Tizen.Applications.WidgetControl/Tizen.Applications/WidgetControl.cs

[Tizen.Applications] Fix static analysis issues

---

src/Tizen.NUI/src/internal/Common/WeakEvent.cs

* WeakEventProxy : The weak event connecting to a normal event.
- ACR:

[NUI] Add WeakEventProxy class and improve invoke of WeakEvent

---

src/Tizen.NUI/src/internal/Common/ClipboardSignal.cs
src/Tizen.NUI/src/internal/Interop/Interop.Clipboard.cs
src/Tizen.NUI/src/public/Clipboard/Clipboard.cs
src/Tizen.NUI/src/public/Clipboard/ClipboardEvent.cs

Implement the Clipboard singleton class
that allows set and retrieval of data from the clipboard.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/294862/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/295023/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/295519/

[NUI] Add Clipboard

---

src/Tizen.NUI/src/internal/Common/WeakEvent.cs

[NUI] Add non-generic WeakEventProxy

---

src/Tizen.NUI.Components/Controls/Control.cs
src/Tizen.NUI.Components/Controls/Picker.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
src/Tizen.NUI.Components/Controls/ScrollableBase.cs
src/Tizen.NUI/src/internal/Common/EnumHelper.cs
src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
src/Tizen.NUI/src/internal/XamlBinding/BindingExpression.cs
src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/Rendering/VertexBuffer.cs
src/Tizen.NUI/src/public/XamlBinding/BindablePropertyConverter.cs

[NUI] Fix some SVACE issues.

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

Since #5437 PR make visual lazy, we got some error when we try to make animation with "CornerRadius" property.
Until resolve VisualAnimation issue. let we just update visual synchronously.

[NUI] Block lazy Background

---

src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/ExceptionFactory.cs

Raise exception for NotSupportedFeature error

[VoiceControlManager] Raise exception for NotSupportedFeature error

---

src/Tizen.Data.Tdbc.Driver.Sqlite/Tizen.Data.Tdbc.Driver.Sqlite/Connection.cs

Add lock for _recordChanged variable

[NoACR] Add lock for _recordChanged variable

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

[NUI] Make LottieAnimationView do not support bitmap images.

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

[NUI] Set DragWindow Orientation Available

[NUI] Set DragWindow Orientation Available

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs

Add some property to control the mix color of ImageView's image visual

[NUI] Add ImageView.ImageColor property for Image visual's MixColor

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs

The Load() method is added to load the assembly of the NUIGadget.

[NUI.Gadget] Add a new method to load assembly

---

src/Tizen.Multimedia.Remoting/WebRTC/MediaScreenSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCFeatures.cs

Add display feature for video APIs
- MediaScreenSource
- MedisSource.EnableVideoLoopback()
- MediaStreamTrack.Display
- MediaStreamTrack.DisplayMode
- MediaStreamTrack.DisplayVisible
- WebRTC.AddSource
- WebRTC.AddSources
- TCSACR-544

[WebRTC] Add display feature for video APIs

---

src/Tizen.Multimedia.Camera/Camera/CameraCapabilities.cs
src/Tizen.Multimedia.Camera/Camera/CameraDeviceManager.cs
src/Tizen.Multimedia.Camera/Camera/CameraSettings.cs
src/Tizen.Multimedia.Camera/Interop/Interop.Camera.cs
src/Tizen.Multimedia.Camera/Interop/Interop.CameraSettings.cs

Add new APIs for manual focus level, product id and vendor id
- TCSACR-545

[Camera] Add new APIs for manual focus level, product id and vendor id

---

src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Common.cs
src/Tizen.Multimedia.Vision/MediaVision/MediaVisionSource.cs

Add Timestamp API for MediaVisionSource
- TCSACR-546

[MediaVision] Add Timestamp API for MediaVisionSource

---

src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Common/Layer.cs
src/Tizen.NUI/src/public/Input/InputMethodContext.cs
src/Tizen.NUI/src/public/Rendering/Renderer.cs
src/Tizen.NUI/src/public/Rendering/TextureSet.cs
src/Tizen.NUI/src/public/Widget/WidgetView.cs
src/Tizen.NUI/src/public/Window/DefaultBorder.cs

Remove liteweights build warnings when build latest NUI

[NUI] Remove NUI dotnet 6.0 build warnings

---

src/Tizen.Multimedia.Remoting/MediaController/CustomCommandCapabilityUpdatedEventArgs.cs
src/Tizen.Multimedia.Remoting/MediaController/InternalEnums.cs
src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
src/Tizen.Multimedia.Remoting/MediaController/MediaController.Events.cs
src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
src/Tizen.Multimedia.Remoting/MediaController/MediaControllerManager.Events.cs
src/Tizen.Multimedia.Remoting/MediaController/Mode360CapabilityUpdatedEventArgs.cs
src/Tizen.Multimedia.Remoting/MediaController/PlaybackPositionCapabilityUpdatedEventArgs.cs
src/Tizen.Multimedia.Remoting/MediaController/PlaylistCapabilityUpdatedEventArgs.cs
src/Tizen.Multimedia.Remoting/MediaController/SearchCapabilityUpdatedEventArgs.cs
src/Tizen.Multimedia.Remoting/MediaController/SubtitleCapabilityUpdatedEventArgs.cs

Add new capability APIs :
- playback position
- playlist
- client custom
- search
- TCSACR-543

[MediaController] Add new capability APIs

---

src/Tizen.NUI/src/internal/Interop/Interop.MouseReleative.cs
src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/internal/Interop/Interop.WindowMouseRelativeEventSignal.cs
src/Tizen.NUI/src/internal/Window/WindowMouseRelativeEventSignal.cs
src/Tizen.NUI/src/public/Window/MouseRelative.cs
src/Tizen.NUI/src/public/Window/Window.cs
src/Tizen.NUI/src/public/Window/WindowEvent.cs

Add api about RelativeMove
1. PointerConstraintsLock
2. PointerConstraintsUnlock
3. LockedPointerRegionSet
4. LockedPointerCursorPositionHintSet
5. RelativeMoveEvent
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/296968/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/296969/
- ACR:

[NUI] Add api about RelativeMove

---

src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
src/Tizen.NUI/src/public/XamlBinding/Binding.cs

[NUI] Make BindableObject.IsBound public.

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

Supports key event of repeat and delay of each way.
It is based on tizen ecore-wl2 APIs

[NUI] Supports key event of repeat and delay of each way.

---

src/Tizen.Applications.RemoteView/Tizen.Applications/RemoteView.cs

Fix issue for checking return value of Interop

Fix issue for checking return value of Interop

---

src/Tizen.Data.Tdbc.Driver.Sqlite/Tizen.Data.Tdbc.Driver.Sqlite/Connection.cs

Fix static analysis issue
- ACR: N/A

[Tdbc] Fix static analysis issue

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

Sets visibility on/off of cursor
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/297714/ https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/297715/
- ACR:

[NUI] Binding CursorVisibleSet

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

KeyboardGrab : Request grab key events according to the requested device subtype.
KeyboardUnGrab : Request ungrab key events
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/297828/ https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/297829/
- ACR:

[NUI] Binding KeyboardGrab and KeyboardUnGrab

---

src/Tizen.NUI.WindowSystem/Tizen.NUI.WindowSystem.csproj

Remove SupportedProfiles attribute from Tizen.NUI.WindowSystem.csproj
to support all profiles including mobile, wearable, TV, etc.
Added:
- None
Changed:
- None

[NUI.WindowSystem] remove SupportedProfiles attribute

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Light.cs
src/Tizen.NUI.Scene3D/src/public/Light/Light.cs

Add Shadow API for a Directional Light.
The Shadow is available only for a Directional Light that is enabled on SceneView.
And, Shadow's edge can be soften with Percentage Closer Filtering(PCF).
- ACR:

[NUI.Scene3D] Add Shadow for a Directional Light

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionData.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionIndex/BlendShapeIndex.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionIndex/MotionIndex.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionIndex/MotionPropertyIndex.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionIndex/MotionTransformIndex.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionValue.cs

- ACR: [ACR-548](https://code.sec.samsung.net/jira/browse/TCSACR-548)
Added:
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
[Add] Animation GenerateMotionDataAnimation(MotionData motionData)
[Add] void SetMotionData(MotionData motionData)
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionData.cs
[Add] MotionData()
[Add] MotionData(int durationMilliSeconds)
[Add] MotionData(MotionData motionData)
[Add] int Duration { get; set;}
[Add] uint GetMotionCount()
[Add] MotionIndex GetIndex(uint index)
[Add] MotionValue GetValue(uint index)
[Add] void LoadMotionCaptureAnimation(string motionCaptureFilename, Vector3 scale = null, bool synchronousLoad = false)
[Add] void LoadMotionCaptureAnimationFromBuffer(string motionCaptureBuffer, Vector3 scale = null, bool synchronousLoad = false)
[Add] …

[NUI] Public open MotionData

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

Apply constant value for default drag window size
- ACR:

[NUI] Apply constant value for default drag window size

---

src/Tizen.NUI/src/public/Accessibility/IAtspiEditableText.cs
src/Tizen.NUI/src/public/Accessibility/IAtspiSelection.cs
src/Tizen.NUI/src/public/Accessibility/IAtspiTable.cs
src/Tizen.NUI/src/public/Accessibility/IAtspiTableCell.cs
src/Tizen.NUI/src/public/Accessibility/IAtspiText.cs
src/Tizen.NUI/src/public/Accessibility/IAtspiValue.cs

- The descriptions of Accessibility Interfaces were missed because of the urgent tasks.
- Now, need to add them for the next steps.
- N/A

[NUI] Add descriptions of Accessibility Interfaces

---

src/Tizen.Applications.Common/Tizen.Applications.CoreBackend/DefaultCoreBackend.cs
src/Tizen.Applications.Common/Tizen.Applications.CoreBackend/ICoreBackend.cs
src/Tizen.Applications.Common/Tizen.Applications.Exceptions/AppNotFoundException.cs
src/Tizen.Applications.Common/Tizen.Applications.Exceptions/LaunchFailedException.cs
src/Tizen.Applications.Common/Tizen.Applications.Exceptions/LaunchRejectedException.cs
src/Tizen.Applications.Common/Tizen.Applications.Exceptions/OutOfMemoryException.cs
src/Tizen.Applications.Common/Tizen.Applications.Exceptions/PermissionDeniedException.cs
src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Exceptions.cs
src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs
src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
src/Tizen.Applications.Common/Tizen.Applications/AppControlLaunchMode.cs
src/Tizen.Applications.Common/Tizen.Applications/Application.cs
src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfo.cs
src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfoFilter.cs
src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
src/Tizen.Applications.Common/Tizen.Applications/ApplicationRunningContext.cs
src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs
src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
src/Tizen.Applications.Common/Tizen.Applications/CultureInfoHelper.cs
src/Tizen.Applications.Common/Tizen.Applications/DeviceOrientation.cs
src/Tizen.Applications.Common/Tizen.Applications/GSourceManager.cs
src/Tizen.Applications.Common/Tizen.Applications/ReceivedAppControl.cs
src/Tizen.Applications.Common/Tizen.Applications/RecentApplicationControl.cs
src/Tizen.Applications.Common/Tizen.Applications/RecentApplicationInfo.cs
src/Tizen.Applications.Common/Tizen.Applications/SafeBundleHandle.cs
src/Tizen.Applications.Common/Tizen.Applications/TizenSynchronizationContext.cs
src/Tizen.Applications.Common/Tizen.Applications/TizenUISynchronizationContext.cs

This request removes warning messages.

[Applications.Common] Remove warning messages

---

src/Tizen.Applications.Common/Interop/Interop.AppCommon.cs
src/Tizen.Applications.Common/Tizen.Applications.CoreBackend/DefaultCoreBackend.cs
src/Tizen.Applications.Common/Tizen.Applications.CoreBackend/EventType.cs
src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
src/Tizen.Applications.Common/Tizen.Applications/TimeZoneChangedEventArgs.cs

The TimeZoneChangedEventArgs class is added for Time Zone changed event.
- ACR: TCSACR-555
Added:
1. CoreApplication.cs
+ void OnTimeZoneChanged(TimeZoneChangedEventArgs);
+ EventHandler<TimeZoneChangedEventArgs> TimeZoneChanged;
2. TimeZoneChangedEventArgs
+ string TimeZone { get; } // Property
+ string TimeZoneId { get; } // Property
+ void TimeZoneChangedEventArgs(string timeZone, string, timeZoneId); // Constructor

[Applications.Common] Add TimeZoneChanged Event

---

src/Tizen.Applications.Service/Tizen.Applications.CoreBackend/ServiceCoreBackend.cs
src/Tizen.Applications.Service/Tizen.Applications/ServiceApplication.cs

This patch registers and unregister the time zone changed event.

[Applications.Service] Modify ServiceCoreBackend for TimeZone Event

---

src/Tizen.Applications.UI/Tizen.Applications.CoreBackend/UICoreBackend.cs
src/Tizen.Applications.UI/Tizen.Applications/CoreUIApplication.cs

This patch registers and unregister the time zone changed event.

[Applications.UI] Modify UICoreBackend for time zone event

---

src/Tizen.Applications.ComponentBased/Interop/Interop.CBApplication.cs
src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/BaseComponent.cs
src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ComponentStateManger.cs
src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/FrameComponentStateManager.cs
src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ServiceComponentStateManager.cs
src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/WidgetComponentStateManager.cs

This request adds the TimeZoneChanged EventHandler. The component-based application can monitors the time zone changed event using the event handler.
- ACR: TCSACR-556
Added:
- public event EventHandler<TimeZoneChangedEventArgs> TimeZoneChanged;

[ComponentBased] Add TimeZoneChanged EventHandler

---

test/NUIClipboard/Clipboard.cs
test/NUIClipboardDataSelected/ClipboardDataSelected.cs

- test/NUIClipboard
- test/NUIClipboardDataSelected

[NUI] Enhance clipboard sample code

---

src/Tizen.NUI/src/internal/Interop/Interop.DragAndDrop.cs
src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

[NUI] DragAndDrop : Add APIs for Window
- ACR:

[NUI] DragAndDrop : Add APIs for Window

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

DragAndDrop : hide window event handler
- ACR:

DragAndDrop : hide window event handler

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.MotionIndex.cs

Fix unmatched function binding

[NUI.Scene3D] Fix MotionData TCT error

---

src/Tizen.NUI/src/public/Window/WindowEvent.cs

Window window = NUIApplication.GetDefaultWindow(); window.HoverEvent += OnHover;
private void OnHover(object source, Window.HoverEventArgs e) {
// e.Hover.GetState(0); // PointStateType.Motion;
}
- ACR:

[NUI] Add HoverEvent in Window

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/internal/Interop/Interop.Application.cs

[NUI] fix IME window crash issue
- dependency : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/299361/
none

[NUI] fix IME window crash issue

---

src/Tizen.NUI/src/internal/Common/DaliEnumConstants.cs
src/Tizen.NUI/src/internal/Common/Registry.cs
src/Tizen.NUI/src/public/Common/BaseHandle.cs
src/Tizen.NUI/src/public/Utility/Timer.cs

Let we throw exception if same object try to register.

[NUI] Let registry throw exception at error case

---

src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractorError.cs

Fix VD SVACE issue
- imcomplete switch

[ThumbnailExtractor] Fix VD SVACE issue - incomplete switch

---

src/Tizen.System.Feedback/Feedback/Feedback.cs

Below feedback pattern is supported by mapping feedback pattern id number.
- FEEDBACK_PATTERN_WELCOME
- FEEDBACK_PATTERN_AUTO_DOOR_OPEN
- ACR:

[System.Feedback] Add new feedback_pattern

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebViewTextFoundEventArgs.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[Tizen][API10] Add WebView APIs for fullscreen, text found, etc.

---

src/Tizen.NUI.Wearable/src/public/CircularPagination.cs
src/Tizen.NUI.Wearable/src/public/RecyclerView/RecyclerView.cs
src/Tizen.NUI.Wearable/src/public/WearableList.cs

Remove dotnet build warnings for Tizen.NUI.Wearable.
- Add comment for public API
- Remove some unused private value/method

[NUI.Wearable] Remove build warning

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetResourceManager.cs

The visibility of NUIGadgetResourceManager(NUIGadgetInfo info) is changed to 'public'.

[NUI.Gadget] Change visibility of NUIGadgetResourceManager ctor

---

src/Tizen.System.Feedback/Feedback/Feedback.cs

The index of sound theme range is 1 ~ N according to conf file.
This index range should be considered when using feedback theme index getter/setter.
- ACR:

[System.Feedback] Add feedback theme index range description

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
test/NUIDnDSource/NUIDnDSource.cs

[NUI] Add an API to set offset for drag window
- ACR: N/A

[NUI] Add an API to set offset for drag window

---

src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs

1. Public RemoveBinding and ClearBinding
2. Add PropertyChanging invoke for SetValue.
- ACR: None

[NUI] Public RemoveBinding and ClearBinding apis

---

test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/.vscode/launch.json
test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/Program.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/TSPropertyValue.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunit.framework/Api/NUnitTestAssemblyRunner.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunit.framework/Internal/Execution/CompositeWorkItem.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunit.framework/Internal/Execution/ParallelWorkItemDispatcher.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunit.framework/Internal/Execution/SimpleWorkItem.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunit.framework/Internal/Execution/SimpleWorkItemDispatcher.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunit.framework/Internal/Execution/TestWorker.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunit.framework/Internal/Execution/WorkItem.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunit.framework/Internal/Execution/WorkShift.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunit.framework/TUnit/TAsyncThreadMgr.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunitlite/TUnit/TRunner.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/nunitlite/TextRunner.cs

Let we make Devel.Tests.Ubuntu works well under net6.0 version.
Also, add some logics to debug deadlock issue when we try to terminate TCT app hardly.

[NUI][Devel.Tests.Ubuntu] Make it works on net6.0

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest1.cs

Reinforce NUI Sample for window.
It has the sample for testing  window function.
0. Sumarry
- Window는 기능 자체가 Display server, App FW, Sensor FW 등 다른 모듈과의 연동이 많은 관계로 Unit Test가 아닌 Manual Test로 진행해서 확인해야 하는 경우가 많습니다. 
- 따라서, 별도의 Unit Test가 있지만, 기존의 manual test의 테스트 항목을 확대하고 강화 해야 할 필요가 있습니다.
- 추가된 Test Case는 Window CSharp binder의 Code Clean up 및 refactoring에 대한 검증 차원도 포함됩니다.
1. What
- Window.cs에 있는 Function과 Property Test Case를 추가하거나 강화하였습니다. 
- 이번에 새로 추가된 Test에 대한 Function 들입니다.
- SetClass, Raise, Lower, Activate, Show, Hide, 
- Avaiaible Rotation 관련 Functions, Prefered Oritataion 관련 Functions, SetFocus, SetOpaueState, 
- Window Type 및 Notification Level, Screen On/Off, Brightness, Window Size/Position, Partial Update
2. Why
- Unit Test로 확인할 수 없는 부분들을 Menual Test를 통해 확인하기 위함입니다.
3. How
- …

[NUI] Reinforce NUI Sample for window

---

packaging/csapi-tizenfx.spec
packaging/csapi-tizenfx.spec.in

The name of the dotnet_resolving.info file is changed.

[Build] the dotnet_resolving.info file has been renamed

---

src/Tizen.Network.Nsd/Interop/Interop.Nsd.cs
src/Tizen.Network.Nsd/Tizen.Network.Nsd/DnssdService.cs

use g_free() instead of free()
https://github.com/Samsung/TizenFX/pull/5632

[Nsd] Fix ASAN crash

---

src/Tizen.Multimedia.Remoting/MediaController/MediaControlCommand.cs

[MediaController] Fix CustomCommand crash issue

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

[NUI] Add a Window constructor using WindowData

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

same patch as https://github.com/Samsung/TizenFX/pull/5721
none

[NUI] revert 'Make DaliAccessibilityDetachAccessibleObject called at main thread' and check native object

---

src/Tizen.NUI/src/internal/Interop/Interop.WindowData.cs
src/Tizen.NUI/src/public/Application/WindowData.cs

CSharpBinder
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/301025
- ACR:

[NUI] Add FrontBufferRendering in WindowData

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelPrimitive.cs

This PR is to support to build ModelNode Tree after a Model finish to data from file
- ACR:

[NUI] Supports to build ModelNode Tree

---

src/Tizen.NUI.XamlBuild/src/internal/XamlBinding/Element.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/XamlBinding/Element.cs

Let wr ignore some dotnet build warnings at Element.cs

[NUI] Remove build warning due to unusing API

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowFrontBufferRenderingSample.cs

This demo app tests FrontBufferRendering using WindowData.
PR: https://github.com/Samsung/TizenFX/pull/5725
- ACR:

[NUI] Add Front Buffer Rendering Sample

---

src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiEnumerations.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs

Adds internal APIs SetAutoScanMode(...) and HiddenAPConnectAsync(...)
- ACR:
None

[Tizen.Network.WiFi] Add set auto scan mode and hidden connect apis

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

[NUI] Add ModelPivotPoint property

---

.github/workflows/build-branches.yml
.github/workflows/nightly-release.yml
.github/workflows/postback-pull-request.yml

Reverts Samsung/TizenFX#5716
There still is access issue.

Revert "[Actions] Update token to fine-grained"

---

src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/AttachPanel.cs
src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/ContentCategory.cs
src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/EventType.cs
src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/ResultEventArgs.cs
src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/StateEventArgs.cs
src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/StateType.cs

Revert "Deprecating Attach Panel APIs"

---

.github/workflows/nightly-release.yml

[Build] Update token used in nightly-release

---

src/Tizen.NUI/src/public/Window/DefaultBorder.cs

Change the default color of the border.
Light Theme: https://www.figma.com/file/9N4gGNaT8ZjoigHoGHCDkE/GUI-Tizen-8.0---Window-border?type=design&node-id=1945%3A2457&mode=design&t=OdLZVMD41px2Il06-1
- ACR:

[NUI] Change the default color of the border.

---

.github/workflows/nightly-release.yml

Reverts Samsung/TizenFX#5758 to verify updates on Samsung org.

Revert "[Build] Update token used in nightly-release"

---

src/Tizen.Multimedia.Camera/Camera/Camera.Properties.cs
src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroring.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
src/Tizen.Multimedia/Common/Display.cs

Fix to set window size properly. It's already merged in API10.
(DF230214-00262)

[Multimedia] Fix to set window size properly

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.MotionData.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionData.cs

[NUI] Support RootTranslationOnly option for motion capture data

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs

Match valid native API for RemoveModelPrimitive

[NUI.Scene3D][API10] Attach matched interop linker for RemoveModelPrimitive

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs

Match valid native API for RemoveModelPrimitive

[NUI.Scene3D][API11] Attach matched interop linker for RemoveModelPrimitive

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs

[NUI.Scene3D] Attach matched interop linker for RemoveModelPrimitive

---

src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/Window/DefaultBorder.cs

https://github.com/Samsung/TizenFX/pull/5760
https://github.com/Samsung/TizenFX/pull/5776
- ACR:

[NUI] Apply the “Change the default color of the border.” and “Add Dispatch Wheel Events and DispatchPrentWheelEvents” patches to API11.

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs

https://github.com/Samsung/TizenFX/pull/5696
Model.SetColliderMesh() function allows creating and setting a collider mesh on the node of model.
Node of model is selected by name (string).
Collider mesh data consists:
List<Vector3> - list of vertices
List<int> - list of indices (3 indices are a triangle face)

[NUI] Added collider mesh support

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationViewBindableProperty.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

[NUI] Add EnableFrameCache in LottieAnimationView

---

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs

BluetoothProfileType enum does not match native bt_profile_e enum.

[Bluetooth] Fix BluetoothProfileType enum mismatch issue

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

[NUI] Add log for ClearFocus

---

src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/MarshalingObservableCollection.cs
src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/ObservableGroupedSource.cs
src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/ObservableItemSource.cs
src/Tizen.NUI.Physics2D/src/internal/chipmunk/NativeInterop.cs
src/Tizen.NUI.Physics2D/src/internal/chipmunk/cpSpaceDebugDrawOptions.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.MotionData.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionData.cs
src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

Cherry-pick some NUI patches into API11 which need to be released on tizen_8.0

[NUI][API11] Rebase DevelNUI to API11

---

src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/AttachPanel.cs
src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/ContentCategory.cs
src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/EventType.cs
src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/ResultEventArgs.cs
src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/StateEventArgs.cs
src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/StateType.cs
src/Tizen.Applications.PackageManager/Interop/Interop.Libraries.cs
src/Tizen.Applications.PackageManager/Interop/Interop.Package.cs
src/Tizen.Applications.PackageManager/Interop/Interop.PackageManagerInfoInternal.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/PackageCertificate.cs
src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommandsGroup.cs

Rebase master -> DevelNUI

---

.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml

Update docker image for genrating .NET6.0 document

[Build] Update docker image version

---

.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml
src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsData.cs

Master to DevelNUI Integration

---

src/Tizen.Multimedia.Vision/MediaVision/DeepLearningFaceRecognizer.cs
src/Tizen.Multimedia.Vision/MediaVision/VisionFeatures.cs

Change feature key of inference face recognition
http://tizen.org/feature/vision.inference.face 
->
http://tizen.org/feature/vision.inference
http://tizen.org/feature/vision.inference.face_recognition
http://tizen.org/feature/vision.training
http://tizen.org/feature/vision.training.face_recognition
- TCSACR-563

[MediaVision] Change feature key of inference face recognition

---

src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiConfiguration.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs

Add Multiscan and related apis
ACR:
None

[Tizen.Network.WiFi] Add APIs for multi-scanning

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Libraries.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

Let we make new API for Light class for SceneView.
Note : To avoid the changness of native side code minimalize, let we use internal API of NUI.

[NUI.Scene3D] Add AddLight API

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationViewBindableProperty.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

DevelNUI -> Master integration 

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Libraries.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

Revert #5854 PR. We'd better found more good way to fix this issue.
This patch required below dali patch
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/303828
This reverts commit 0cb799167b61395984ee1da9d647f326aad852fa.

[NUI.Scene3D] Revert "Add AddLight API"

---

src/Tizen.Content.MediaContent/Interop/Interop.AudioInfo.cs
src/Tizen.Content.MediaContent/Interop/Interop.MediaInfo.cs
src/Tizen.Content.MediaContent/Interop/Interop.Tag.cs
src/Tizen.Content.MediaContent/Interop/Interop.VideoInfo.cs
src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/AudioInfo.cs
src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Columns.cs
src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfo.cs
src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Tag.cs
src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/TagCommand.cs
src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/VideoInfo.cs

Deprecate underutilized fields
- TCSACR-571

[MediaContent] Deprecate underutilized fields

---

.github/workflows/deploy-packages.yml

- Update deploy-packages action workflow
- `nuget push` with `--skip-duplicate` option
- To prevent deploy fail when pushing the same NuGet.

[Actions] Update deploy packages

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelPrimitive.cs

API11에 추가된 패치 중 누락된 패치 추가(3D 관련)
3D Model의 Child가 0으로 나오는 문제 해결
- ACR:

[Tizen.NUI.Scene3D] Support to build ModelNode Tree

---

src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs

New theme can affect to the views that were not affected by previous theme.
- ACR:

[NUI] Do not check theme applied flag when set ThemeChangeSensitive

---

src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI][API10] Create Context/CookieManager when WebView is created.

---

src/Tizen.NUI/src/public/WebView/WebView.cs

this patch supports cornerRadius in WebView
refer to : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/304770/
- ACR:

[NUI] Support CornerRadius in WebView

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs

To unload the loaded assembly, NUIGadgetManager.Unload() method is added.

[NUI.Gadget] Implement Unload() method

---

src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs

[NUI] Fix CollectionView LinearLayout move overlapped issue

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs

- The mount point is changed to the directory path of the executable file.
(To support using external libraries, the mount point is changed.)
- The environment variable related to resource package IDs is changed to "GADGET_PKGIDS".
- The "RES_PKGIDS" will be removed.

[NUI.Gadget] Modify NUIGadget implementation

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs

- Use LoadFromNativeImagePath() instead of LoadFromStream()

[NUI.Gadget] Change assembly load mothod

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

Related patch at csharp binder:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/305521/
- ACR:

[NUI][API10] Add a WebView API for notifying orientation change.

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

Related patch at csharp binder:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/305517/
- ACR:

[NUI][API11] Add a WebView API for notifying orientation change.

---

src/Tizen.NUI.Components/Controls/Loading.cs

[NUI] Fixing the defect of the outer edge of the rounded image not being smooth in the Loading animation
nothing

[NUI] Fixing the defect of the outer edge of the rounded image not being smooth in the Loading animation

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs

There was leak issue since we don't call FreeHGlobal after AllocHGlobal.
And also, let we Dispose Renderer / Geometry / Shader / TextureSet what NUI create. Those classes memory might give confuse when we test the memory.

[NUI.Sample] Resolve memory leak for DisposeTest sample

---

src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FrameUpdateCallbackTest.cs

Let we bind some more codes that UpdateProxy in dali side already supported.
relative dali patch :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/305265

[NUI] Support FrameUpdateCallback get world transform

---

src/Tizen.Multimedia.Camera/Camera/CameraDeviceManager.cs
src/Tizen.Multimedia.Camera/Interop/Interop.Camera.cs

The P/Invoke function signature was wrong.

[Camera] Fix CameraDeviceManager bug

---

src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs

Add missing deprecation description.
- TCSACR-547

[MediaContent] Add missing deprecation description

---

src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs

[Connection] Use lock for event

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

[NUI] Support to get Marker list information from lottie

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs

Refer tizen application life-cycle : https://docs.tizen.org/application/dotnet/guides/applications/uiapplication/application_lifecycle/
- ACR:

[NUI] Add State property of NUIApplication

---

src/Tizen.NUI/src/internal/Interop/Interop.Rotation.cs
src/Tizen.NUI/src/public/Common/Rotation.cs

https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/307648/
Add Rotation constructor using pitch,yaw,roll
- ACR:

[NUI.Scene3D] Add Rotation constructor using pitch,yaw,roll

---

src/Tizen.NUI/src/internal/Common/WeakEvent.cs

[NUI] WeakEvent : Improve clean-up condition

---

src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs

[NUI][API10] Fix SVACE issue (ViewStyle.cs CopyFrom null check)

---

src/Tizen.NUI/src/public/Common/WeakEvent.cs

[NUI] WeakEvent : Modify invoke param type

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs

[NUI] change Tizen.NUI.State as Tizen.NUI.NUIApplication.States because it is NUIApplication state
nothing

[NUI] change Tizen.NUI.State as Tizen.NUI.NUIApplication.States because it is NUIApplication state

---

src/Tizen.NUI/src/internal/Interop/Interop.GestureOptions.cs
src/Tizen.NUI/src/public/Events/GestureOptions.cs

[NUI] Add SetTapMaximumMotionAllowedDistance
refer
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/308601/ https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/308602/
- ACR:

[NUI] Add SetTapMaximumMotionAllowedDistance

---

src/Tizen.Multimedia.Vision/MediaVision/BarcodeGenerator.cs

Prevent GC of object including unmanaged handle

[MediaVision] Prevent GC of object including unmanaged handle

---

src/Tizen.AIAvatar/src/internal/Common/RestClient.cs
src/Tizen.AIAvatar/src/internal/Uix/TTSLipSyncer.cs
src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/BlendShapePlayer.cs
src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/LipSyncer.cs
src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/MotionPlayer.cs
src/Tizen.AIAvatar/src/public/Avatar/Avatar.cs
src/Tizen.AIAvatar/src/public/Avatar/Controller/AvatarTTS.cs

Fix AIAvatar svace issue
- ACR:

[Tizen.AIAvatar] Fix Svace issue

---

test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/Tizen.NUI.Components.Devel.Tests.csproj
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/TSCollectionView.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSButton.Internal.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Extension/TSLottieButtonExtension.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Extension/TSLottieSwitchExtension.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Extension/TSSwitchExtension.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/PreloadStyle/TSOverlayAnimationButtonStyle.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/tizen-manifest.xml
test/Tizen.NUI.Tests/nunit.framework/nunit.framework.csproj
test/Tizen.NUI.Tests/nunitlite/nunitlite.csproj

1. Fix build errors of Tizen.NUI.Components.Devel.Tests
- ACR: None

[NUI] Fix build errors of Tizen.NUI.Components.Devel.Tests

---

src/Tizen.NUI/src/public/Application/NUIWidgetApplication.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageViewBindableProperty.cs

[NUI] Add IsUsingXaml at NUIWidgetApplication and change AnimatedVectorImageView's property
nothing

[NUI] Add IsUsingXaml at NUIWidgetApplication and change AnimatedVectorImageView's property

---

src/Tizen.NUI.Components/Controls/Popup.cs

Add nullity check for `buttonStyle` when `ApplyStyle()` for `Popup`.
- ACR:

[NUI] Fix svace issue on Popup

---

src/Tizen.NUI.Components/Controls/Popup.cs
src/Tizen.NUI.Wearable/src/public/Title.cs
src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/Tizen.NUI.Components.Devel.Tests.csproj
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/RecyclerView/TSCollectionView.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSButton.Internal.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Extension/TSLottieButtonExtension.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Extension/TSLottieSwitchExtension.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Extension/TSSwitchExtension.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/PreloadStyle/TSOverlayAnimationButtonStyle.cs
test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/tizen-manifest.xml
test/Tizen.NUI.Tests/nunit.framework/nunit.framework.csproj
test/Tizen.NUI.Tests/nunitlite/nunitlite.csproj

[NUI] Rebase develnui 

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs

To release loaded assembly, the Unload() method is added.

[NUI.Gadget] Support Unload() method to release assembly

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs

[NUI] Add IsUsingXaml at NUIApplication and change ImageView's property
Nothing

[NUI] Add IsUsingXaml at NUIApplication and change ImageView's property

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationViewBindableProperty.cs

[NUI] Change LottieAnimationView's property and renaming summary at NUIApplication
Nothing

[NUI] Change LottieAnimationView's property and renaming summary at NUIApplication

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs

[NUI] Change Scrollable property
Nothing

[NUI] Change Scrollable property

---

src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs

[NUI] Change TextEditorBindableProperty property
Nothing

[NUI] TextEditorBindableProperty changes

---

src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs

Refactor bindable properties in TextField

[NUI] TextField BindableProperty refactor

---

src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs

Refactor bindable properties in TextLabel

[NUI] TextLabel BindableProperty refactor

---

src/Tizen.NUI/src/public/Utility/ScrollView.cs
src/Tizen.NUI/src/public/Utility/ScrollViewBindableProperty.cs

[NUI] Change ScrollViewBindableProperty property
Nothing

[NUI] ScrollViewBindableProperty changes

---

src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs

[NUI] Add IsUsingXaml to RemoveFrontInset and RemoveBackInset
nothing

[NUI] Add IsUsingXaml to RemoveFrontInset and RemoveBackInset

---

src/Tizen.NUI/src/public/WebView/WebView.cs
src/Tizen.NUI/src/public/WebView/WebViewBindableProperty.cs

[NUI] Change WebView property
Nothing

[NUI] Change WebView property

---

src/Tizen.NUI/src/public/Widget/WidgetView.cs

[NUI] Change WidgetView property
Nothing

[NUI] Change WidgetView property

---

src/Tizen.NUI/src/public/Window/DefaultBorder.cs

[NUI] Change DefaultBorder property
Nothing

[NUI] Change DefaultBorder property

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
src/Tizen.NUI/src/public/Utility/ScrollView.cs
src/Tizen.NUI/src/public/Utility/ScrollViewBindableProperty.cs
src/Tizen.NUI/src/public/WebView/WebView.cs
src/Tizen.NUI/src/public/WebView/WebViewBindableProperty.cs
src/Tizen.NUI/src/public/Widget/WidgetView.cs
src/Tizen.NUI/src/public/Window/DefaultBorder.cs

[NUI] Integrate IsUsingXaml related patches from DevelNUI
patches =>
Scrollable changes
[NUI] Scrollable and LottieAnimationView adding condition If Using Xaml
[NUI] TextEditorBindableProperty changes (#6086)
[NUI] TextField BindableProperty refactor (#6087)
[NUI] TextLabel BindableProperty refactor (#6094)
[NUI] ScrollViewBindableProperty changes (#6095)
[NUI] Change WebView property (#6097)
[NUI] Change WidgetView property (#6098)
[NUI] Change DefaultBorder property (#6099)
nothing

[NUI] Integrate IsUsingXaml related patches from DevelNUI

---

src/Tizen.NUI/src/public/Common/NUIConstants.cs

[NUI] Add VirtualRemocon and VirtualMouse sub device types
- ACR:

[NUI] Add VirtualRemocon and VirtualMouse sub device types

---

src/Tizen.NUI/src/internal/Utility/Camera.cs
src/Tizen.NUI/src/internal/Utility/CameraBindableProperty.cs
src/Tizen.NUI/src/internal/Utility/GaussianBlurView.cs
src/Tizen.NUI/src/internal/Utility/ItemView.cs
src/Tizen.NUI/src/internal/Utility/ItemViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs
src/Tizen.NUI/src/public/BaseComponents/TableView.cs
src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
src/Tizen.NUI/src/public/Common/Container.cs
src/Tizen.NUI/src/public/CustomView/Spin.cs

[NUI] Add IsXamlUsing flag to Camera, ItemView and etc
Camera.cs
CameraBindableProperty.cs
GaussianBlurView.cs
ItemViewBindableProperty.cs
CustomView.cs
FlexContainer.cs
TableView.cs
VideoView.cs
CanvasView.cs
Container.cs
Spin.cs
nothing

[NUI] Add IsXamlUsing flag to Camera, ItemView and etc

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs

NUI] Fix TV AdPlayer crash issue
nothing

[NUI] Fix TV AdPlayer crash issue

---

src/Tizen.NUI/src/public/Common/NUIConstants.cs

This reverts commit 36e0fc7ebd3b37f71ac216bee74493d93533a350.
Revert "[NUI] Add VirtualRemocon and VirtualMouse sub device types"
- ACR:

Revert "[NUI] Add VirtualRemocon and VirtualMouse sub device types"

---

src/Tizen.NUI/src/public/Utility/AccumulatingVelocityTrackerStrategy.cs
src/Tizen.NUI/src/public/Utility/LeastSquaresVelocityTrackerStrategy.cs
src/Tizen.NUI/src/public/Utility/VelocityTracker.cs
src/Tizen.NUI/src/public/Utility/VelocityTrackerStrategy.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VelocityTrackerSample.cs

This is a utility that calculates velocity from consecutive touch coordinates.
Velocity can be calculated using the motion event coordinates of touch or pan gestures.
``` c++
private void OnPanGestureDetected(object source, PanGestureDetector.DetectedEventArgs e)
{
tracker.AddMovement(e.PanGesture.ScreenPosition, e.PanGesture.Time);
if (e.PanGesture.State == Gesture.StateType.Started)
{
}
else if (e.PanGesture.State == Gesture.StateType.Continuing)
{
}
else if (e.PanGesture.State == Gesture.StateType.Finished || e.PanGesture.State == Gesture.StateType.Cancelled)
{
float panVelocity = (ScrollingDirection == Direction.Horizontal) ? tracker.GetVelocity().X : tracker.GetVelocity().Y;
tracker.Clear();
}
}
```
You can use the tracker that NUI provides by default, or you can use a customTracker …

[NUI] Add VelocityTracker

---

src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs

[Applications.Common] Fix wrong since_tizen tag

---

src/Tizen.NUI/src/internal/Interop/Interop.WidgetView.cs
src/Tizen.NUI/src/internal/Interop/Interop.WidgetViewManager.cs
src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs

*CSharp Binder Split patch : 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/309649/
- ACR:

[NUI] Split WidgetViewer so

---

src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs

[NUI][API11] Add Inset & Cutout Properties

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs

We don't need to ask DALi side always when we want to get the url of image.
Instead, just keep it at NUI View side, and use it.

[NUI] Do not ask DALi to get BackgroundImage url

---

src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapter.cs
src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapterImpl.cs
src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEnumerations.cs
src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs

[NUI] Integration master to DevelNUI

---

src/Tizen.NUI/src/internal/Interop/Interop.InputMethodContext.cs
src/Tizen.NUI/src/public/Input/InputMethodContext.cs

Directly related patches:
https://review.tizen.org/gerrit/#/c/platform/upstream/efl/+/310856/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/311007/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/311015/
Indirectly related patches:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/wayland-extension/+/310855/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/e-mod-tizen-wl-textinput/+/306441/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/e-mod-tizen-wl-textinput/+/310858/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/isf/+/306661/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/isf/+/310859/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/libscl-core/+/310860/ …

[NUI] Add align API to InputMethodContext

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

[NUI] Fix multiscreen exception when IsUsingXaml is false
nothing

[NUI] Fix multiscreen exception when IsUsingXaml is false

---

src/Tizen.NUI/src/internal/Common/FriendAssembly.cs

[NUI] Add FriendAssembly for DA FLUX
none

[NUI] Add FriendAssembly for DA FLUX

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs

[NUI] Fix View preload sequences
nothing

[NUI] Fix View preload sequences

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/public/Window/Window.cs

[NUI] Window.Instance is deprecated and Default is newly added
https://jira.sec.samsung.net/browse/TCSACR-584

[TCSACR-584][NUI] Window.Instance is deprecated and Default is newly added

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/public/Window/Window.cs

Rebase master to DevelNUI
- ACR:

[TCSACR-584] Window.Instance is deprecated and Default is newly added

---

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs

Add BluetoothDevice constructor with remote address
- ACR: None

Add BluetoothDevice constructor with remote address

---

src/Tizen.Applications.PackageManager/Interop/Interop.PackageManager.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManagerClearCacheEventArgs.cs

Add ClearCacheProgressChanged EventHandler
Added:
- ClearCacheProgressChanged { add;, remove; } // Property
- PackageManagerClearCacheEventArgs { PackageId, State } // Class

Add ClearCacheProgressChanged EventHandler

---

src/Tizen.NUI/src/public/Window/Window.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest1.cs

Add sample for window modal and always on top property to Tizen.NUI.Samples.
In addition, the description is added to window modal.
The detail description is added to patch.

[NUI] Add sample and description for window

---

src/Tizen.NUI/src/internal/Common/FriendAssembly.cs

[NUI] Add friend assembly for NUI2
nothing

[NUI] Add friend assembly for NUI2

---

src/Tizen.NUI/src/internal/Common/FriendAssembly.cs

[NUI] Add friend assembly for NUI2.Compatibility
nothing

[NUI] Add friend assembly for NUI2.Compatibility

---

src/Tizen.Multimedia.Remoting/WebRTC/MediaFileSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaMicrophoneSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaNullSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs

* [WebRTC] Change state restriction
- ACR:

[WebRTC] Change state restriction (#6181)

---

src/Tizen.NUI/src/internal/Interop/Interop.RenderEffect.cs
src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Utility/RenderEffect.cs

[NUI] Support View RenderEffect + BackgroundBlurEffect
Dali patch required for this PR:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/313372

[NUI] Support View BackgroundBlurEffect

---

src/Tizen.NUI/src/public/Layouting/GridLayout.cs
src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs

- Make intention revealing names for Some variables. 
- Choosing names that reveal intent can make it much easier to understand.
- N/A

[NUI] Clean code for NUI Layouting

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebViewTextFoundEventArgs.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] merge and sync WebView changes with tizen_7.0
dali patches (should be merged together) =>
[Tizen][Web] Update WebView terminate crash
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/315307 
[Tizen] Add WebView APIs for fullscreen, text found, etc.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/315308 
[Tizen] Add a WebView API for notifying orientation change.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/315309 
[Tizen] Add WebView APIs for fullscreen, text found, etc.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/315313 
[Tizen] TOUCH_FOCUSABLE's default is false so this also should not be set
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/315314 
[Tizen] Apply …

[NUI] merge and sync WebView changes with tizen_7.0

---

src/Tizen.Data.Tdbc/Tizen.Data.Tdbc/DriverManager.cs
src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Commons.cs
src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsInfo.cs

Rebase master 

---

src/Tizen.NUI/src/internal/Interop/Interop.Capture.cs
src/Tizen.NUI/src/public/Utility/Capture.cs

[NUI] Add Exclusive Option for Capture

---

src/Tizen.NUI/src/internal/Interop/Interop.WebCertificate.cs
src/Tizen.NUI/src/internal/WebView/WebCertificate.cs

[NUI] Add WebView Certificate policy decision error get and suspend
dali patches that should be merged together => 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/315630/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-extension/+/315631/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/315632/
nothing

[NUI] Add WebView Certificate policy decision error get and suspend

---

src/Tizen.NUI/src/internal/Interop/Interop.WebCertificate.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebCertificate.cs
src/Tizen.NUI/src/internal/WebView/WebViewTextFoundEventArgs.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] update/sync the latest codes of WebView
nothing

[NUI] update/sync the latest codes of WebView

---

src/Tizen.Multimedia.Remoting/WebRTC/MediaPacketSourceConfiguration.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs

[WebRTC] Add debug log

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

[NUI] Fix TableView TC fail issue
- TCT crash issue, log => E/STDERR  (21795): Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
E/STDERR  (21795):    at Tizen.NUI.BaseComponents.View.Dispose(DisposeTypes type) in Tizen.NUI.dll:token 0x6002b7c+0x591
E/STDERR  (21795):    at Tizen.NUI.BaseHandle.Dispose() in Tizen.NUI.dll:token 0x6000e5c+0xc
E/STDERR  (21795):    at Tizen.NUI.DisposeQueue.ProcessDisposablesIncrementally() in Tizen.NUI.dll:token 0x6000238+0x79
E/STDERR  (21795):    at Tizen.NUI.DisposeQueue.ProcessDisposables() in Tizen.NUI.dll:token 0x6000237+0xd5
E/STDERR  (21795): onSigabrt called
nothing

[NUI] Fix TableView TC fail issue

---

src/Tizen.NUI/src/internal/Common/DefaultItemLayoutProperty.cs
src/Tizen.NUI/src/internal/Common/RenderTask.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Common/Matrix.cs
src/Tizen.NUI/src/public/Common/Matrix3.cs
src/Tizen.NUI/src/public/Common/RelativeVector3.cs
src/Tizen.NUI/src/public/Common/TimePeriod.cs
src/Tizen.NUI/src/public/Common/WeakEvent.cs
src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
src/Tizen.NUI/src/public/Images/ImageUrl.cs
src/Tizen.NUI/src/public/Images/PixelData.cs
src/Tizen.NUI/src/public/Images/PixelFormat.cs
src/Tizen.NUI/src/public/Rendering/VertexBuffer.cs
src/Tizen.NUI/src/public/Theme/ThemeManager.cs
src/Tizen.NUI/src/public/Utility/Capture.cs
src/Tizen.NUI/src/public/Utility/RenderEffect.cs

Found some build warning list by below command
dotnet build /p:BuildWithAnalyzer=True -consoleloggerparameters:NoSummary
Their are too many warnings occurs, let we remove them by multiple phases.

[NUI] Remove various build warnings (phase 1)

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Panel.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Panel.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/Scene3DPanelTest.cs

This PR adds Panel class in NUI.Scene3D.
Panel is a plane to draw 2D UI Contents in 3D Scene.
2D UI Contents are drawn with Offscreen rendering and textured on plane that is located on 3D Scene.
The plane is lit by 3D lighting including IBL and directional light.
- ACR:

[NUI.Scene3D] Add Panel in Scene3D

---

src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Fix the handler's garbage collected exception in WebView
nothing

[NUI] Fix the handler's garbage collected exception in WebView

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/internal/Interop/Interop.WindowBlurInfo.cs
src/Tizen.NUI/src/public/Common/NUIConstants.cs
src/Tizen.NUI/src/public/Window/Window.cs
src/Tizen.NUI/src/public/Window/WindowBlurInfo.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest1.cs

This patch introduces a new Window Blur feature, allowing for advanced customization of window blurring effects. 
Users can configure the blur effect with three primary inputs: BlurType, BlurRadius, and BackgroundCornerRadius.
This new APIs is to request window blur to window manager. 
Next time, behind blur will be added.

[NUI] Supports window blur with some parameters

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

[NUI] Fix TableView TC fail issue again in proper way
- Fix the https://github.com/Samsung/TizenFX/pull/6258 correctly
- This is for https://github.sec.samsung.net/NUI/home/issues/25
- locally applied image has been passed the TCT
nothing

[NUI] Fix TableView TC fail issue again in proper way

---

src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.ScreensaverService.cs
src/Tizen.NUI.WindowSystem/src/public/ScreensaverService.cs
test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.cs

We introduce the screensaver-service feature in Tizen.NUI.WindowSystem.Shell (internal)
- ACR: N/A
Added:
Class
- ScreensaverService
APIs
- None (just create/destroy)

[NUI.WindowSystem] introduce the Screensaver service feature

---

src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs

The AppControl API description has been revised to enhance understanding for developers, making it easier for them to understand

[Tizen.Applications]Enhancement of API description

---

src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
src/Tizen.NUI/src/public/Animation/AlphaFunction.cs
src/Tizen.NUI/src/public/Animation/Animatable.cs
src/Tizen.NUI/src/public/Animation/Animation.cs
src/Tizen.NUI/src/public/Animation/KeyFrames.cs

[NUI] Add more comments
nothing

[NUI] Add more comments

---

src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
src/Tizen.Multimedia/AudioManager/SoundEffect.cs
src/Tizen.Multimedia/Interop/Interop.StreamPolicy.cs

Add new SoundEffect APIs
- TCSACR-593

[AudioManager] Add new SoundEffect APIs

---

src/Tizen.Multimedia.Vision/MediaVision/InferenceFaceDetector.cs
src/Tizen.Multimedia.Vision/MediaVision/InferenceFacialLandmarkDetector.cs
src/Tizen.Multimedia.Vision/MediaVision/InferenceImageClassifier.cs
src/Tizen.Multimedia.Vision/MediaVision/InferenceObjectDetector.cs
src/Tizen.Multimedia.Vision/MediaVision/InferencePoseLandmarkDetector.cs

[MediaVision] Check instance is disposed

---

src/Tizen.NUI/src/public/Animation/Path.cs
src/Tizen.NUI/src/public/Animation/TransitionOptions.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Application/NUIWidgetApplication.cs
src/Tizen.NUI/src/public/ApplicationAnimation/ApplicationTransitionManager.cs
src/Tizen.NUI/src/public/BaseComponents/CameraView.cs
src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
src/Tizen.NUI/src/public/BaseComponents/TableView.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Picture.cs
src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

[NUI] Add comments (2nd patch)
TizenFX/src/Tizen.NUI/src/public/Animation/Path.cs => 7 changes
TizenFX/src/Tizen.NUI/src/public/Animation/TransitionOptions.cs => 1 change
TizenFX/src/Tizen.NUI/src/public/Application/NUIApplication.cs => 23 changes
TizenFX/src/Tizen.NUI/src/public/Application/NUIWidgetApplication.cs => 10 changes
TizenFX/src/Tizen.NUI/src/public/Application/WatchTime.cs => will be deprecated
TizenFX/src/Tizen.NUI/src/public/ApplicationAnimation/ApplicationTransitionManager.cs =>
The 'ApplicationTransitionManager' class was originally a hidden API, and the 'Instance' API was also a hidden API, but it seems that the hidden API attribute was accidentally not applied. Therefore, it does not fall under the ACR case. 
TizenFX/src/Tizen.NUI/src/public/BaseComponents/Style/Selector …

[NUI] Add comments (2nd patch)

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest1.cs

Supports to set window layer to bottom.
The related patches are the belows.
In addition, the more description is added for AlwaysOnTOP
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/318118/ 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/318127/

[NUI] Supports window set bottom

---

src/Tizen.Multimedia.Remoting/WebRTC/MediaCameraSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaCustomSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaFileSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaMicrophoneSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaNullSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaPacketBufferStatusChangedEventArgs.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaPacketSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaPacketSourceConfiguration.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaScreenSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaTestSource.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannelErrorOccurredEventArgs.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCEnums.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCFrameEncodedEventArgs.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCTrackAddedEventArgs.cs

[WebRTC] Improve documentation

---

src/Tizen.Applications.ComponentBased.Port/Tizen.Applications.ComponentBased.Port/ComponentPort.cs
src/Tizen.Applications.ComponentBased.Port/Tizen.Applications.ComponentBased.Port/ComponentTask.cs
src/Tizen.Applications.ComponentBased.Port/Tizen.Applications.ComponentBased.Port/Parcel.cs
src/Tizen.Applications.ComponentBased.Port/Tizen.Applications.ComponentBased.Port/RequestEventArgs.cs

[ComponentBased.Port] Enhance API descriptions

---

src/Tizen.Applications.Preference/Tizen.Applications/Preference.cs
src/Tizen.Applications.Preference/Tizen.Applications/PreferenceChangedEventArgs.cs

[Applications.Preference] Enhance API descriptions

---

src/Tizen.Applications.Service/Tizen.Applications/ServiceApplication.cs

[Applications.Service] Enhance API descriptions

---

src/Tizen.Content.MimeType/Tizen.Content.MimeType/MimeUtil.cs

[Content.MimeType] Enhance API descriptions

---

src/Tizen.Applications.UI/Tizen.Applications/CoreUIApplication.cs

[Applications.UI] Enhance API descriptions

---

src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Port.cs
src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs
src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs

[Applications.RPCPort] Enhance API descriptions

---

src/Tizen.System.Information/Common/Information.cs
src/Tizen.System.Information/Usage/ProcessCpuUsage.cs
src/Tizen.System.Information/Usage/ProcessMemoryUsage.cs
src/Tizen.System.Information/Usage/SystemCpuUsage.cs
src/Tizen.System.Information/Usage/SystemMemoryUsage.cs

[System.Information] Elaborate API description

---

src/Tizen.Core/Tizen.Core/Channel.cs
src/Tizen.Core/Tizen.Core/ChannelObject.cs
src/Tizen.Core/Tizen.Core/ChannelReceivedEventArgs.cs
src/Tizen.Core/Tizen.Core/ChannelReceiver.cs
src/Tizen.Core/Tizen.Core/ChannelSender.cs
src/Tizen.Core/Tizen.Core/Event.cs
src/Tizen.Core/Tizen.Core/EventObject.cs
src/Tizen.Core/Tizen.Core/EventReceivedEventArgs.cs
src/Tizen.Core/Tizen.Core/Task.cs

[Tizen.Core] Enhance API descriptions

---

src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.Events.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.cs

Fix DataChannel event bug
- BufferedAmountLow

[WebRTC] Fix DataChannel event bug

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebViewWebAuthDisplayQREventArgs.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Add WebAuthDisplayQR and Response for QR code passkey in WebView
dali patches =>
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/318953
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/318954
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-extension/+/318955
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/318956
nothing

[NUI] Add WebAuthDisplayQR and Response for QR code passkey in WebView

---

src/Tizen.Account.SyncManager/Tizen.Account.SyncManager/SyncAdapter.cs

Revert "Deprecating Tizen.Account.SyncManager  CancelSyncCallback() API"

---

src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Modified the WebView to hold the instances of WebContext and WebCookieManager
nothing

[NUI] Modified the WebView to hold the instances of WebContext and WebCookieManager

---

src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Manager.cs
src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Pkcs12.cs

Add missing API documentation descriptions.

[Tizen.Security.SecureRepository] Add missing documentation descriptions

---

src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticationExtension.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticationSelectionCriteria.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Authenticator.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorAssertionResponse.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorAttestationResponse.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/ClientData.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/GetAssertionCallbacks.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/HybridLinkedData.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/MakeCredentialCallbacks.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredAssertion.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredAttestation.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredCreationOptions.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredDescriptor.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredParam.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredRequestOptions.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/RelyingPartyEntity.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/UserEntity.cs

Code documentation enhancements adhering to the newest guidelines.
- ACR:

[WebAuthn] Enhance code documentation

---

src/Tizen.Applications.Alarm/Tizen.Applications/Alarm.cs
src/Tizen.Applications.Alarm/Tizen.Applications/AlarmManager.cs

[Tizen.Applications.Alarm] Enhance API descriptions

---

src/Tizen.Applications.Alarm/Interop/Interop.Alarm.cs
src/Tizen.Applications.Alarm/Tizen.Applications/AlarmManager.cs

Adds:
- AlarmManager.CreateAlarmForServiceApp()

[Applications.Alarm] Add an internal API

---

src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebSettings.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

csharp-binder patch:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/320722/
- ACR:

[NUI] Add APIs for setting IME position, cursor theme name.

---

.github/workflows/build-branches.yml
.github/workflows/build-pull-request.yml
.github/workflows/check-api-level.yml
.github/workflows/deploy-packages.yml
.github/workflows/nightly-release.yml

- Update Action according to the change of the default branch name from `master` to `main`.
- This should be merged after the default branch name is changed to `main`.
- Removed `Download Base API Spec` step on build-PR actions.

Update actions for main branch 

---

src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs

Fix wrong descriptions.
- ACR: N/A

[Tizen.Applications] Fix wrong descriptions

---

src/Tizen.NUI/src/internal/Common/FriendAssembly.cs

[NUI] Add NUI FLUX friend assembly
nothing

[NUI] Add NUI FLUX friend assembly

---

src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs

[Tizen.Applications] Fix wrong description

---

packaging/makerid.py
src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs

Rebase main -> DevelNUI

---

src/Tizen.NUI/src/devel/Lite/L.Color.cs
src/Tizen.NUI/src/devel/Lite/L.Shadow.cs
src/Tizen.NUI/src/devel/Lite/L.Vector2.cs
src/Tizen.NUI/src/internal/Common/ControlStateUtility.cs
src/Tizen.NUI/src/public/BaseComponents/ControlState.cs

Rebase DevelNUI -> main

---

src/Tizen.NUI/src/public/Common/NUIConstants.cs

https://github.sec.samsung.net/NUI/OneUIComponents/issues/20
Code related to preload() will be updated later.
No Changes

[NUI] Remove unnecessary PInvoke calls

---

src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
src/Tizen.NUI/src/public/Common/NUIConstants.cs

Rebase DevelNUI->main

---

src/Tizen.NUI/Tizen.NUI.csproj

NUI Language version upgrade for 9.
- ACR:

[NUI] NUI Language version upgrade

---

src/Tizen.NUI/src/public/Common/NUIConstants.cs
src/Tizen.NUI/src/public/Common/Position.cs

- PivotPoint, AnchorPoint, Position 
It related with below issue
https://github.sec.samsung.net/NUI/OneUIComponents/issues/20
No Changes

[NUI] Remove unnecessary PInvoke calls (PivotPoint, AnchorPoint, Position)

---

src/Tizen.NUI/src/public/Common/NUIConstants.cs

Fix error for below PR
https://github.com/Samsung/TizenFX/pull/6543
No Changes

[NUI] Fix wrong params order for ParentOrigin position

---

src/Tizen.NUI/src/public/Animation/Animation.cs

In C#, Task is used for asynchronous task,
and animation is one of useful feature that use this task.
This patch aim to add play method with passing asynchronous task, so that user can handle the animation
more easily and c# friendly.
basic idea is from NUI2 Animation.
- ACR:

[NUI] add asynchronous tasked animation play

---

src/Tizen.NUI/src/public/Utility/GraphicsTypeExtensions.cs
src/Tizen.NUI/src/public/Utility/SpTypeConverter.cs

[NUI] Update dp and sp extension methods and sp converting.

---

packaging/csapi-tizenfx.spec
packaging/maketfm.py
pkg/Tizen.NET/Tizen.NET.nuspec
src/Tizen.NUI.WindowSystem/src/public/QuickPanelClient.cs
src/Tizen.NUI.WindowSystem/src/public/TizenShell.cs

[NUI] Rebase main (22401)

---

.github/workflows/deploy-documents-for-tizen-docs.yml

This PR is to update document template for tizen.org

Update document template for tizen.org

---

src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs

Add missing notifications
- ACR:

[NUI] Notify property changed for the property methods using struct

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs
src/Tizen.NUI/src/devel/Lite/UIColor.cs
src/Tizen.NUI/src/devel/Lite/UICorner.cs
src/Tizen.NUI/src/devel/Lite/UIShadow.cs
src/Tizen.NUI/src/devel/Lite/UIState.cs
src/Tizen.NUI/src/devel/Lite/UIVector2.cs
src/Tizen.NUI/src/internal/Common/Object.cs
src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs
src/Tizen.NUI/src/public/Common/PropertyMap.cs
src/Tizen.NUI/src/public/Common/Vector4.cs

Rename `L.XXX` style to `UIXXX`.
- ACR:

[NUI] Rename struct types

---

src/Tizen.NUI/src/public/Utility/GraphicsTypeExtensions.cs

Fix recursive invoke issue:
https://analysishub.sec.samsung.net/dm/tizen/page/review#PRJID=620&WGID=261331
https://analysishub.sec.samsung.net/dm/tizen/page/review#PRJID=620&WGID=261332
https://analysishub.sec.samsung.net/dm/tizen/page/review#PRJID=620&WGID=261333
https://analysishub.sec.samsung.net/dm/tizen/page/review#PRJID=620&WGID=261334
- ACR:

[NUI] Fix svace issue : infinite recursion

---

.github/CODEOWNERS
.github/workflows/build-pull-request.yml
.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml

[NUI] Rebase from main to DevelNUI

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs

Add C# MarkUp Extension methods for View Properties.
e.g)
View myView = new ().Size(10f, 10f)
.Position(10f, 10f)
.Layout(new LienarLayout)
.Padding(5f, 5f, 5f, 5f)
.BackgroundColor(1f, 1f, 1f, 1f)
Added Properties
- Color
<s>- MinimumSize</s>
<s>- MaximumSize</s>
<s>- Padding</s>
<s>- Margin</s>
<s>- InheritPosition</s>
- ImageShadow
- Borderline
- Opacity
- Scale
<s>- InheritScale</s>
- Visibility
- Sensitive
- IsEnabled
- ClippingMode
- Layout
<s>- Weight</s>
- Focusable
- FocusableChildren
- FocusableInTouch
<s>- KeyInputFocus</s>
<s>- ExcludeLayouting</s>
- VoiceInteractionName
- OffScreenRendering
and few getters for UI struct types.
- Color
- BorderlineColor
- ACR:

[NUI] Add markup extension methods for view properties

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs

[NUI] Remove Offscreen rendering markup methods

---

src/Tizen.NUI/src/internal/Common/FriendAssembly.cs

[NUI] Add friend assembly for FLUX.Extension by request of user
nothing

[NUI] Add friend assembly for FLUX.Extension by request of user

---

.github/workflows/build-branches.yml
.github/workflows/build-pull-request.yml
.gitignore

Try to fix github action build error
nothing

Try to fix github action build error

---

src/Tizen.NUI.Wearable/src/public/Title.cs
src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
test/NUITestSample/CommonUI_Samples/Samples/ContactCard/ClippedImage.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CircularTextSample.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ClippedImage.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs

Let we change custom shader codes as unified-dali-style shader codes.

[NUI] Fix several custom shader could be works at Vulkan backend

---

src/Tizen.NUI/src/internal/Utility/GaussianBlurView.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
src/Tizen.NUI/src/public/BaseComponents/Style/TextEditorStyle.cs
src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
src/Tizen.NUI/src/public/Layouting/GridLayout.cs
src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs

[NUI] Disable xaml in Style & Layouting.

---

.github/workflows/build-branches.yml
.github/workflows/build-pull-request.yml
.github/workflows/check-api-level.yml
.gitignore

Try to fix github Action error
nothing

Try to fix github Action error

---

src/Tizen.NUI.Components/Controls/AlertDialog.cs
src/Tizen.NUI.Components/Controls/AlertDialogBindableProperty.cs
src/Tizen.NUI.Components/Controls/Button.cs
src/Tizen.NUI.Components/Controls/ButtonBindableProperty.cs
src/Tizen.NUI.Components/Controls/ButtonGroup.cs
src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
src/Tizen.NUI.Components/Controls/Control.cs
src/Tizen.NUI.Components/Controls/DatePicker.cs
src/Tizen.NUI.Components/Controls/Dialog.cs
src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
src/Tizen.NUI.Components/Controls/ImageScrollBar.cs
src/Tizen.NUI.Components/Controls/Loading.cs
src/Tizen.NUI.Components/Controls/Menu.cs
src/Tizen.NUI.Components/Controls/MenuBindableProperty.cs
src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
src/Tizen.NUI.Components/Controls/Navigation/AppBarBindableProperty.cs
src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
src/Tizen.NUI.Components/Controls/Navigation/ContentPageBindableProperty.cs
src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs
src/Tizen.NUI.Components/Controls/Navigation/DialogPageBindableProperty.cs
src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
src/Tizen.NUI.Components/Controls/Navigation/Page.cs

[NUI] Disable xaml in AlertDialog, Button, etc in Components.

---

src/Tizen.NUI/src/public/Input/InputMethodContext.cs

[NUI] Fix InputMethodContext callbacks API12

---

src/Tizen.NUI/src/public/Common/BaseHandle.cs
src/Tizen.NUI/src/public/Input/InputMethodContext.cs

[NUI] Fix InputMethodContext callbacks API11

---

src/Tizen.NUI/src/public/Common/BaseHandle.cs
src/Tizen.NUI/src/public/Input/InputMethodContext.cs

[NUI] Fix InputMethodContext callbacks API10

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs
src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
src/Tizen.NUI/src/public/Layouting/GridLayout.cs
src/Tizen.NUI/src/public/Layouting/LayoutDimension.cs
src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
src/Tizen.NUI/src/public/Layouting/LayoutLength.cs
src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
src/Tizen.NUI/src/public/ViewProperty/LayoutExtraData.cs

[NUI] Add LayoutWidth and LayoutHeight to View

---

src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
src/Tizen.NUI.Components/Controls/RecyclerView/CollectionViewBindableProperty.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItemBindableProperty.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItemBindableProperty.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultTitleItem.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultTitleItemBindableProperty.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
src/Tizen.NUI.Components/Controls/ScrollableBase.cs
src/Tizen.NUI.Components/Controls/ScrollableBaseBindableProperty.cs

[NUI] Disable xaml in CollectionView, ScrollableBase, etc in Components.

---

src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Drawable.cs
src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Gradient.cs
src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
src/Tizen.NUI/src/public/Common/Vector4.cs

[NUI] Fix a memory leak in Vector4.

---

src/Tizen.NUI/src/internal/Interop/Interop.PropertyMap.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/Common/PropertyMap.cs
src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
src/Tizen.NUI/src/public/ViewProperty/TextShadow.cs

[Optimization][Issue 23] Set int/float/string/vector/rectangle to propertyMap directly.

---

src/Tizen.NUI.Components/Controls/Tab.cs
src/Tizen.NUI.Components/Controls/TabBindableProperty.cs
src/Tizen.NUI.Components/Controls/TimePicker.cs
src/Tizen.NUI.Components/Controls/Toast.cs
src/Tizen.NUI.Components/Controls/ToastBindableProperty.cs
src/Tizen.NUI.Components/Style/ButtonStyle.cs
src/Tizen.NUI.Components/Style/LoadingStyle.cs
src/Tizen.NUI.Components/Style/PaginationStyle.cs
src/Tizen.NUI.Components/Style/RecyclerViewItemStyle.cs
src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
src/Tizen.NUI.Components/Style/SliderStyle.cs
src/Tizen.NUI.Components/Style/ToastStyle.cs

[NUI] Disable xaml in Style in Components.

---

src/Tizen.NUI.Components/Controls/ImageScrollBar.cs
src/Tizen.NUI.Components/Controls/ScrollBarBindableProperty.cs
src/Tizen.NUI.Components/Controls/Scrollbar.cs
src/Tizen.NUI.Components/Controls/Slider.cs
src/Tizen.NUI.Components/Controls/SliderBindableProperty.cs
src/Tizen.NUI.Components/Controls/Switch.cs
src/Tizen.NUI.Components/Controls/SwitchBindableProperty.cs

[NUI] Disable xaml in Scrollbar, Switch, etc in Components.

---

pkg/Tizen.NET/Tizen.NET.nuspec

Change [Microsoft.NETCore.Platforms](https://www.nuget.org/packages/Microsoft.NETCore.Platforms/) NuGet reference version
from `8.0.11` to `8.0.0-preview.7.23375.6`
The public release of the referenced NuGet package has been delayed,
so we are reverting to the previeous NuGet reference.
related to : https://github.com/Samsung/TizenFX/pull/6549

[Build] Update dependency

---

src/Tizen.NUI.Extension/Internal/ViewPropertySetters.cs
src/Tizen.NUI.Extension/Markup/ViewExtensions.cs
src/Tizen.NUI/src/devel/Common/IPropertySetter.cs
src/Tizen.NUI/src/devel/Common/IToken.cs
src/Tizen.NUI/src/devel/Common/ITokenTable.cs
src/Tizen.NUI/src/devel/Common/PropertySetter.cs
src/Tizen.NUI/src/devel/Common/TokenType.cs
src/Tizen.NUI/src/devel/Lite/UIColor.cs
src/Tizen.NUI/src/internal/Common/EmptyResourceTable.cs
src/Tizen.NUI/src/internal/Common/TokenManager.cs

* UIColor supportes token
* Token table is managed by internal TokenManager
- ACR:

[NUI] UIColor supports token

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Add SetVideoHole() for EFL window
- requested by GBM
- tested in PontusM TV target
- should be released with dali patches =>
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/319698
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/319699
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-extension/+/319700
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/319701
nothing

[NUI] Add SetVideoHole() for EFL window

---

src/Tizen.NUI.Components/Controls/Slider.Internal.cs

[NUI] Fix a crash after xaml is disabled in Style.

---

src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs

[NUI] Add z/depth into Position/Size in ViewStyle.

---

src/Tizen.Core/Tizen.Core/Task.cs

This patch fixes a crash issue related to "A callback was made on a garbage collected delegate of type".

[Tizen.Core] Fix a bug about native handler

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Components/ItemView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Components/ScrollView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliTableView.cs

Fix compile error issue after #6621 patch merged
- After `RulerPtr` removed, we cannot make Dali's ScrollView make stop fixed position.
- Remove unused class and API
- Make custom shader support on Vulkan backend

[NUI.Samples] Fix compile error after unused class removed

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs

[NUI] Add getter of LayoutWidth/Height in view extension

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

[NUI] Fix crash when a layout is set into View.

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

[NUI] Fix issue that disposed PropertyMap is returned in View.

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs

View extensions using UIColor do bind for every input
- ACR:

[NUI] View extensions using UIColor do bind for every input

---

src/Tizen.Core/Tizen.Core/Task.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi.csproj
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs

For integration
main -> DevelNUI

[NUI] Rebase main branch

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
src/Tizen.NUI/src/public/BaseComponents/TableView.cs

[NUI] Remove boxing/unboxing in ImageView, etc.

---

src/Tizen.NUI/src/devel/Lite/UIColor.cs
src/Tizen.NUI/src/internal/Common/FriendAssembly.cs

* Fix UIColor bug in `IsToken`
* Add friend assembly to `Tizen.NUI.OneUI.Components`
- ACR:

[NUI] Fix UIColor bug and add friend assembly

---

.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml

This PR is to update actions because some actions are deprecated.

Update actions to remove a deprecated version

---

src/Tizen.Applications.PackageManager/Interop/Interop.Package.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs

* [PackageManager] add Isupdated
* Fix build error

[PackageManager] add IsUpdated property to Package Class

---

src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs

[NUI] Remove boxing/unboxing in TextEditor.

---

src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs

[NUI] Remove boxing/unboxing in TextField.

---

src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
src/Tizen.NUI/src/public/Common/Container.cs
src/Tizen.NUI/src/public/CustomView/Spin.cs

[NUI] Remove boxing/unboxing in TextLabel, etc.

---

src/Tizen.NUI/src/internal/Utility/Camera.cs
src/Tizen.NUI/src/internal/Utility/CameraBindableProperty.cs
src/Tizen.NUI/src/internal/Utility/GaussianBlurView.cs
src/Tizen.NUI/src/public/WebView/WebView.cs
src/Tizen.NUI/src/public/WebView/WebViewBindableProperty.cs
src/Tizen.NUI/src/public/Widget/WidgetView.cs
src/Tizen.NUI/src/public/Window/DefaultBorder.cs

[NUI] Remove boxing/unboxing in WebView, etc.

---

src/Tizen.NUI.Components/Controls/AlertDialog.cs
src/Tizen.NUI.Components/Controls/AlertDialogBindableProperty.cs
src/Tizen.NUI.Components/Controls/Button.cs
src/Tizen.NUI.Components/Controls/ButtonBindableProperty.cs
src/Tizen.NUI.Components/Controls/ButtonGroup.cs
src/Tizen.NUI.Components/Controls/Control.cs
src/Tizen.NUI.Components/Controls/DatePicker.cs
src/Tizen.NUI.Components/Controls/Dialog.cs
src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
src/Tizen.NUI.Components/Controls/ImageScrollBar.cs
src/Tizen.NUI.Components/Controls/Menu.cs
src/Tizen.NUI.Components/Controls/MenuBindableProperty.cs
src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
src/Tizen.NUI.Components/Controls/Navigation/AppBarBindableProperty.cs
src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
src/Tizen.NUI.Components/Controls/Navigation/ContentPageBindableProperty.cs
src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs
src/Tizen.NUI.Components/Controls/Navigation/DialogPageBindableProperty.cs
src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
src/Tizen.NUI.Components/Controls/Navigation/Page.cs
src/Tizen.NUI.Components/Controls/Pagination.cs
src/Tizen.NUI.Components/Controls/PaginationBindableProperty.cs
src/Tizen.NUI.Components/Controls/ScrollBarBindableProperty.cs

[NUI] Remove boxing/unboxing in Button, etc.

---

.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml
src/Tizen.Applications.PackageManager/Interop/Interop.Package.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs

For integration
main -> DevelNUI

[NUI] Rebase main branch 

---

src/Tizen.NUI/src/internal/Interop/Interop.Shader.cs
src/Tizen.NUI/src/public/Common/PropertyMap.cs
src/Tizen.NUI/src/public/Rendering/Shader.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CircularTextSample.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ClippedImage.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs

Let we make the name of shader class at C# side.
Relative dali patch : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/320746

[NUI](Rendering) Construct shader with name

---

src/Tizen.NUI.Components/Controls/Loading.cs
src/Tizen.NUI.Components/Controls/Picker.cs
src/Tizen.NUI.Components/Controls/PickerBindableProperty.cs
src/Tizen.NUI.Components/Controls/Popup.cs
src/Tizen.NUI.Components/Controls/PopupBindableProperty.cs
src/Tizen.NUI.Components/Controls/Progress.cs
src/Tizen.NUI.Components/Controls/ProgressBindableProperty.cs
src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
src/Tizen.NUI.Components/Controls/RecyclerView/CollectionViewBindableProperty.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItemBindableProperty.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItem.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultLinearItemBindableProperty.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultTitleItem.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultTitleItemBindableProperty.cs
src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
src/Tizen.NUI.Components/Controls/TimePicker.cs
src/Tizen.NUI.Components/Style/LoadingStyle.cs

[NUI] Remove boxing/unboxing in RecyclerView, etc.

---

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
src/Tizen.NUI.Components/Controls/ScrollableBaseBindableProperty.cs
src/Tizen.NUI.Components/Controls/Scrollbar.cs
src/Tizen.NUI.Components/Controls/Slider.cs
src/Tizen.NUI.Components/Controls/SliderBindableProperty.cs
src/Tizen.NUI.Components/Controls/Switch.cs
src/Tizen.NUI.Components/Controls/SwitchBindableProperty.cs
src/Tizen.NUI.Components/Controls/Tab.cs
src/Tizen.NUI.Components/Controls/TabBindableProperty.cs
src/Tizen.NUI.Components/Controls/Toast.cs
src/Tizen.NUI.Components/Controls/ToastBindableProperty.cs

[NUI] Remove boxing/unboxing in ScrollableBase, etc.

---

src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs

AbsolteLayout is fixed to calculate view's size with WrapContent
correctly if child views have proportional position and fixed size.
- ACR:

[NUI] Fix AbsoluteLayout to calculate size with WrapContent

---

.github/CODEOWNERS

[NUI] reorganize the NUI reviwer
nothing

[NUI] reorganize the NUI reviwer

---

src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/Common/NUIConstants.cs

Added EllipsisMode to automatically support auto scroll.
In case of EllipsisMode.AutoScroll,
when the text exceeds the layout, it will automatically scroll with animation.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/320819
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/320820

[NUI] Add EllipsisMode to TextLabel

---

.github/CODEOWNERS
src/Tizen.Applications.UnitedService/Interop/Interop.Libc.cs
src/Tizen.Applications.UnitedService/Interop/Interop.Libraries.cs
src/Tizen.Applications.UnitedService/Interop/Interop.PkgMgrInfo.cs
src/Tizen.Applications.UnitedService/Tizen.Applications.UnitedService.csproj
src/Tizen.Applications.UnitedService/Tizen.Applications.UnitedService.sln
src/Tizen.Applications.UnitedService/Tizen.Applications/Log.cs
src/Tizen.Applications.UnitedService/Tizen.Applications/Service.cs
src/Tizen.Applications.UnitedService/Tizen.Applications/ServiceAssembly.cs
src/Tizen.Applications.UnitedService/Tizen.Applications/ServiceEventType.cs
src/Tizen.Applications.UnitedService/Tizen.Applications/ServiceInfo.cs
src/Tizen.Applications.UnitedService/Tizen.Applications/ServiceLifecycleChangedEventArgs.cs
src/Tizen.Applications.UnitedService/Tizen.Applications/ServiceLifecycleState.cs
src/Tizen.Applications.UnitedService/Tizen.Applications/ServiceManager.cs

[NUI] rebase main

---

src/Tizen.NUI/src/internal/Common/AsyncImageLoader.cs
src/Tizen.NUI/src/internal/Interop/Interop.AsyncImageLoader.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AsyncImageLoaderTest.cs

Let we bind AsyncImageLoader's ImageLoaded signal, so we can make it hidden easly in future.
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/320850

[NUI](Internal) Implement AsyncImageLoader ImageLoaded signal

---

src/Tizen.NUI.Components/Tizen.NUI.Components.csproj

[NUI] Remove NUI.Components not used for tv profile
- https://github.sec.samsung.net/NUI/OneUIComponents/issues/32
https://jira.sec.samsung.net/browse/TCSACR-606

[NUI] Remove NUI.Components not used for tv profile

---

test/NUILayout/Examples/AbsoluteLayoutTest/AbsoluteBoundsMax.cs
test/NUILayout/Examples/AbsoluteLayoutTest/AbsoluteBoundsMin.cs
test/NUILayout/Examples/AbsoluteLayoutTest/AbsoluteBoundsMinMax.cs
test/NUILayout/Examples/AbsoluteLayoutTest/AbsoluteBoundsPropMax.cs
test/NUILayout/Examples/AbsoluteLayoutTest/AbsoluteBoundsPropMin.cs
test/NUILayout/Examples/AbsoluteLayoutTest/AbsoluteBoundsPropMinMax.cs
test/NUILayout/Examples/AbsoluteLayoutTest/AbsoluteMatchMax.cs
test/NUILayout/Examples/AbsoluteLayoutTest/AbsoluteMatchMin.cs
test/NUILayout/Examples/AbsoluteLayoutTest/AbsoluteMatchMinMax.cs

To test MinimumSize and MaximumSize of AbsoluteLayout in NUILayout, those test cases are added.
nothing

[NUI] Add Min/Max of AbsoluteLayout cases in NUILayout

---

.github/workflows/nui-code-style-review.yml

[NUI] Remove github action error part
error is still existed, so remove the whole error part again
nothing

[NUI] Remove github action error part

---

src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs

This PR include improvements related to the following PR:
https://github.com/Samsung/TizenFX/pull/6772
Moved functions to more appropriate locations
Removed unused functions
Added missing descriptions to previously undocumented functions

[NUI] Relocate the function about Font Variations and enhance its explanation

---

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs

Add BluetoothDevice constructor with remote address
- ACR: None

Add BluetoothDevice constructor with remote address (#6165)

---

src/Tizen.NUI/src/internal/Common/SystemFontSizeChangedManager.cs
src/Tizen.NUI/src/internal/Common/SystemFontTypeChangedManager.cs
src/Tizen.NUI/src/internal/Common/SystemLocaleLanguageChangedManager.cs

Minor fixes to sync with API12
https://github.com/Samsung/TizenFX/pull/6771

[NUI] Clean up system manager code

---

src/Tizen.Applications.Common/Interop/Interop.Libraries.cs

libiniparser has been updated to version 4.
- ACR: N/A

[Applications.Common] Update libiniparser so version

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AsyncImageLoaderTest.cs

Add some case that using Palette feature.
Let make user could use Palette's color picking system by this demo

[NUI.Samples] Make AsyncLoaderSample use Palette.

---

src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.InputGesture.cs
src/Tizen.NUI.WindowSystem/src/public/InputGesture.cs
test/Tizen.NUI.WindowSystem.InputGesture/Tizen.NUI.WindowSystem.InputGesture.cs

Add SetGestureGrabMode internal API.
This API needs platform level privilege:
http://tizen.org/privilege/gesturegrab
- ACR:N/A
Added: Internal API
- GestureGrabMode // Property
- public void SetGestureGrabMode(IntPtr data, GestureGrabMode mode)

[NUI] Add SetGestureGrabMode to InputGesture

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebViewOverScrolledEventArgs.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Add OverScrolled in WebView
- dali patches:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/321798
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/321799
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-extension/+/321800
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/321801
nothing

[NUI] Add OverScrolled in WebView

---

src/Tizen.NUI/src/devel/Lite/UIColor.cs
src/Tizen.NUI/src/devel/Lite/UIColorCosntants.cs

Seperate the definition of default constant colors with class itselfs.

[NUI] Define constant color values at seperated files

---

src/Tizen.Applications.Common/Interop/Interop.Libraries.cs
src/Tizen.Applications.Common/Tizen.Applications/RecentApplicationInfo.cs

Rebase main

---

src/Tizen.NUI/src/deprecated/Rendering/Renderer_Deprecated.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewVisuals.cs
src/Tizen.NUI/src/public/BaseComponents/VisualView.cs
src/Tizen.NUI/src/public/Common/Color.cs
src/Tizen.NUI/src/public/Rendering/Renderable.cs

Phase 2 of #6805.
Build warning counts : 1521 -> 1424 (Reduce 97)

[NUI] Reduce build warning CA1805 (Deprecated, BaseComponents, etc)

---

src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs
src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
src/Tizen.NUI/src/public/WebView/WebView.cs
test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSImageView.cs

This enables control corner radius, control radius policy, control squareness to NUI.
The property sets corner values for:
- control's visuals(background, image, shadow)
- offscreen rendered result
- render effect result.
Note: This disables corner values for SceneView, etc  but Eunki will manage it soon.

[NUI] Bind corner radius properties

---

src/Tizen.NUI/src/public/Events/GestureOptions.cs

Remove XML parsing warning after #6828 PR merged.

[NUI](GestureOption) Match parameter name and comment

---

src/Tizen.NUI/src/public/Events/GestureOptions.cs

[NUI](GestureOptions) Add missing comments.
- ACR:

[NUI](GestureOptions) Add missing comments.

---

src/Tizen.NUI/src/internal/Animation/Constraint.cs
src/Tizen.NUI/src/internal/Animation/EqualConstraintWithParentFloat.cs
src/Tizen.NUI/src/internal/Animation/RelativeConstraintWithParentFloat.cs
src/Tizen.NUI/src/internal/Interop/Interop.Rotation.cs
src/Tizen.NUI/src/public/Animation/Animatable.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Common/Property.cs
src/Tizen.NUI/src/public/Common/Rotation.cs

Prepare to implement NUI Constraint feature.
Relative dali patch : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/322491

[NUI] Implement Rotation.Assign + Call Constraint.Remove at Dispose + Minor cleanup

---

src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
src/Tizen.NUI/src/public/Animation/Animatable.cs

This reverts commit b61e9111329191dc5ab0f28412e3fc21b2231134.
public sr 도 통과하고 testhub tct 도 통과했으나 fhub tizen_10.0 release OOBE 에서 crash 가 발생합니다.
우선은 급해서 리버트를 먼저하고 분석 및 수정은 추후에 하겠습니다.
리뷰를 부탁드립니다. 감사합니다.
nothing

Revert "[NUI] Rewrite LowerFirstLetter"

---

src/Tizen.NUI/src/internal/Animation/Constraint.cs
src/Tizen.NUI/src/internal/Animation/ConstraintApplyActionType.cs
src/Tizen.NUI/src/internal/Animation/ConstraintFunction.cs
src/Tizen.NUI/src/internal/Animation/ConstraintTagRanges.cs
src/Tizen.NUI/src/internal/Animation/EqualConstraintWithParentFloat.cs
src/Tizen.NUI/src/internal/Animation/PropertyInputContainer.cs
src/Tizen.NUI/src/internal/Animation/RelativeConstraintWithParentFloat.cs
src/Tizen.NUI/src/internal/Interop/Interop.Constraint.cs
src/Tizen.NUI/src/internal/Interop/Interop.ConstraintFunction.cs
src/Tizen.NUI/src/internal/Interop/Interop.Handle.cs
src/Tizen.NUI/src/internal/Interop/Interop.PropertyInputContainer.cs
src/Tizen.NUI/src/public/Animation/Animatable.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ConstraintWithCustomShaderTest.cs

Let we bind custom constraints generate API.
* Basic demo app using Constraint
Custom shader's effect following mouse cursor position. The effect applied animated position of source View.
And also, use view's `CornerRadius`, `CornerRadiusPolicy`, `CornerSquareness` value as constraint input.
And also, rotate view's orientation follow mouse curosr position.
For now, need to review API and CX level usage.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/322672 (To make CornerRadius as constraint input)
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/322068

[NUI] Bind Constraint with custom function

---

.github/workflows/build-branches.yml
.github/workflows/build-pull-request.yml
.github/workflows/check-api-level.yml
.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml
.github/workflows/deploy-packages.yml
.github/workflows/nightly-release.yml
.github/workflows/postback-pull-request.yml
src/Tizen.Network.WiFiDirect/Interop/Interop.WiFiDirect.cs
src/Tizen.Network.WiFiDirect/Tizen.Network.WiFiDirect/WiFiDirectEnumerations.cs
src/Tizen.Network.WiFiDirect/Tizen.Network.WiFiDirect/WiFiDirectManager.cs
src/Tizen.Network.WiFiDirect/Tizen.Network.WiFiDirect/WiFiDirectManagerImpl.cs
src/Tizen.Network.WiFiDirect/Tizen.Network.WiFiDirect/WiFiDirectPeer.cs

[NUI] Rebase main -> DevelNUI

---

src/Tizen.NUI/src/deprecated/BaseComponents/View_Deprecated.cs
src/Tizen.NUI/src/devel/Lite/UIShadow.cs
src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Common/VisualObjectsContainer.cs
src/Tizen.NUI/src/internal/Transition/TransitionGroupItem.cs
src/Tizen.NUI/src/public/Application/NUIWidgetComponent.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Common/TypeRegistry.cs
src/Tizen.NUI/src/public/ParticleSystem/ParticleEmitter.cs
src/Tizen.NUI/src/public/Utility/Capture.cs
src/Tizen.NUI/src/public/Visuals/AnimatedImageVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualFactory.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/AnimatedImageVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/BorderVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/VisualBase.cs
src/Tizen.NUI/src/public/Window/Window.cs
src/Tizen.NUI/src/public/Window/WindowEvent.cs

After this patch, about 87 CA2000 warnings are remaining in VS.
- ACR:

[NUI] Fix more CA2000 warnings in NUI.

---

src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
src/Tizen.NUI/src/public/Animation/Animatable.cs

Follow up the #6822 and #6840
Let we change the string at native side, not at c# with string builder.
Relative dali patches:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/323372

[NUI] Implement LowerFirstLetter as Native side

---

test/NUIDnDMultiWindow/NUIDnDMultiWindow.cs
test/NUIDnDSource/NUIDnDSource.cs
test/NUIDnDTarget/NUIDnDTarget.cs

[NUI] Refactor app to allow rotation

[NUI] Refactor app to allow rotation

---

src/Tizen.Applications.PackageManager/Tizen.Applications/PackageType.cs

Rebase main to DevelNUI

---

src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs

ManufacturerDataLength
ManufacturerData
Name
ServiceUuidList
ServiceCount

[Bluetooth] Add BluetoothDevice constructor with below:

---

src/Tizen.NUI/src/internal/Common/PropertyHelper.cs

Add Gradient.StartOffset to upper case table

[NUI] Add Gradient.StartOffset to upper case table

---

src/Tizen.NUI/src/internal/Interop/Interop.AlphaFunction.cs
src/Tizen.NUI/src/internal/Interop/Interop.AlphaFunctionSpringData.cs
src/Tizen.NUI/src/public/Animation/AlphaFunction.cs
src/Tizen.NUI/src/public/Animation/AlphaFunctionSpringData.cs
src/Tizen.NUI/src/public/Animation/AlphaFunctionSpringType.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SpringAlphaFunctionTest.cs

Add AlphaFunctionSpringType and AlphaFunctionSpringData to support spring like behavior of Animation by using AlphaFunction.
Related Dali Patches
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/323859
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/323861
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-demo/+/323860
- ACR:

[NUI] Adds Spring Like AlphaFunction for NUI.Animation

---

src/Tizen.NUI/src/internal/Interop/Interop.GradientVisual.cs
src/Tizen.NUI/src/internal/NativeBinding/NDalic.cs
src/Tizen.NUI/src/public/Visuals/GradientVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

You can use conic gradient using Center and StartAngle.
How to Use:
using(PropertyMap map = new PropertyMap())
{
// Do some gradient thing
map.Insert((int)GradientVisualProperty.Center, new PropertyValue(new Vector2(960, 540)));
map.Insert((int)GradientVisualProperty.StartAngle, new PropertyValue(Math));
view.Background = map;
}

[NUI] Introduce Conic Gradient

---

src/Tizen.NUI/src/public/Layouting/LayoutItem.cs

Add MeasureInvalidated event for detecting layout changes.
- ACR:

[NUI] Add measure invalidated event for detecting layout changes

---

src/Tizen.NUI/src/devel/Binding/ViewBindings.cs

[NUI] Add IsEnabled binding property

---

src/Tizen.Multimedia.Recorder/Recorder/Recorder.cs

Add finalizer and modify dispose logic

[Recorder] Add finalizer and modify dispose logic

---

src/Tizen.Multimedia.Recorder/Recorder/Recorder.cs

NUI Integration main -> DevelNUI

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

[NUI][API10] Support to view constructor which we can ignore Relayout

---

src/Tizen.NUI/src/public/Animation/AlphaFunctionSpringType.cs
src/Tizen.NUI/src/public/ViewProperty/InnerShadow.cs
src/Tizen.NUI/src/public/ViewProperty/Shadow.cs

- AlphaFunctionSpringType was not in Tizen.NUI namespace
- InnerShadow.Clone() defined twice. Make it as internal virtual function

[NUI] Fix several compile warning and error

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs
src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

This PR is a temporal PR to revert corner radius bindings to re-enable animation.
We are planning to support Animatable corner radius property on DALi side very soon.

[NUI] Temporal revert for Animatable View corner radius

---

.github/CODEOWNERS
src/Tizen.NUI.Gadget/Interop/Interop.Libc.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetEventType.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
src/Tizen.NUI/src/public/Animation/AlphaFunctionSpringType.cs
src/Tizen.NUI/src/public/ViewProperty/InnerShadow.cs
src/Tizen.NUI/src/public/ViewProperty/Shadow.cs

[NUI] Rebase main->DevelNUI 0516

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SemiParticleSystem.cs

Add simple particle system demo only by using `View`.
Note : This demo use deprecated class - `Renderer`. We should remove it in future.

[NUI.Samples] Add Semi-Particle system

---

src/Tizen.NUI/src/internal/Interop/Interop.VisualFactory.cs
src/Tizen.NUI/src/public/Visuals/VisualFactory.cs
src/Tizen.NUI/src/public/Visuals/VisualFactoryCreationOptions.cs

[NUI][API12] Add creation option to visual factory

---

pkg/Tizen.NET/Tizen.NET.nuspec

Rebase main -> DevelNUI 
No API Changes

[NUI] Rebase main -> DevelNUI 

---

.github/CODEOWNERS

Update CODEOWNERS of Multimedia modules

[Multimedia] Update CODEOWNERS

---

src/Tizen.NUI/src/internal/Common/FriendAssembly.cs

[NUI] Add friend assembly for TV.FLUX.Extension
nothing

[NUI] Add friend assembly for TV.FLUX.Extension

---

.github/CODEOWNERS
src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfo.cs
src/Tizen.Multimedia.Remoting/Interop/Interop.ScreenMirroring.cs
src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroring.cs
src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroringEnums.cs

[NUI] rebase main to DevelNUI
nothing

[NUI] rebase main to DevelNUI

---

src/Tizen.NUI/src/internal/Interop/Interop.TextureSet.cs
src/Tizen.NUI/src/public/Rendering/TextureSet.cs

[NUI] Add RemoveTexture and RemoveSampler in TextureSet

---

src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs

This patch adds to call the CultureInfo.CurrentCulture.ClearCacheData() in the OnTimeZoneChanged() method.

[Applications.Common] Fix OnTimeZoneChanged method

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

Seperate API call by xaml case, and fix crash issue.

[NUI][API12] Fix crash when we use NUI.Layout if IsUsingXaml = false

---

src/Tizen.NUI/src/public/ViewProperty/InnerShadow.cs

[NUI]Fix CA2000 warnings in InnerShadow.

---

src/Tizen.NUI/src/public/Common/Layer.cs

[NUI] Add Ignored property on Layer

---

src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
src/Tizen.NUI/src/internal/WebView/WebSettings.cs

[NUI] Add EnableDragAndDrop method of WebView
dependent dali patches =>
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/326522
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/326523
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-extension/+/326524
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/326525
nothing

[NUI] Add EnableDragAndDrop method of WebView

---

src/Tizen.NUI/src/internal/Interop/Interop.AccessibilitySignal.cs
src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
src/Tizen.NUI/src/public/Accessibility/AccessibilityAction.cs
src/Tizen.NUI/src/public/Accessibility/AccessibilityActionReceivedEventArgs.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityV2.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs

* AccessibilityValue property
* AccessibilityIsScrollable property
* AccessibilityActionReceived event
⚠️ related : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/326559
- ACR:

[NUI] Add AccessibilityValue, IsScrollable, ActionReceived

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs

Remove unused logs in AccessibilityActionReceived event.
- ACR:

[NUI] Remove logs in AccessibilityAction event

---

src/Tizen.NUI/src/public/Visuals/VisualObject/GradientVisual.cs

Add Visuals.GradientVisual Class

[NUI] Add Visuals.GradientVisual Class

---

src/Tizen.Applications.Common/Tizen.Applications/DirectoryInfo.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs

Rebase main branch

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

[NUI] Fix the crash that occurs when excluding the tv profile
nothing

[NUI] Fix the crash that occurs when excluding the tv profile

---

src/Tizen.NUI/src/internal/Animation/Constraint.cs
src/Tizen.NUI/src/public/Animation/Animation.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/public/Common/Layer.cs
src/Tizen.NUI/src/public/RenderEffects/RenderEffect.cs
src/Tizen.NUI/src/public/Rendering/Geometry.cs
src/Tizen.NUI/src/public/Rendering/Renderable.cs
src/Tizen.NUI/src/public/Rendering/Shader.cs
src/Tizen.NUI/src/public/Rendering/Texture.cs
src/Tizen.NUI/src/public/Rendering/TextureSet.cs
src/Tizen.NUI/src/public/Rendering/VertexBuffer.cs
src/Tizen.NUI/src/public/Utility/Timer.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/VisualBase.cs
src/Tizen.NUI/src/public/Window/Window.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs

Let we count some more class's AliveCount values, so Application easy to detect leak of objects more easy

[NUI] Get `AliveCount` for more items

---

src/Tizen.Applications.Notification/Interop/Interop.Notification.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/Notification.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationActiveStyle.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationBinder.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationEnumerations.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationExtensionStyle.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationResponseEventType.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationStyleBinder.cs
src/Tizen.Applications.NotificationEventListener/Interop/Interop.NotificationEventListener.cs
src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationEventArgs.cs
src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationEventArgsBinder.cs
src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationEventArgsEnumerations.cs
src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationEventArgsExtensionStyle.cs
src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationStyleArgsBinder.cs

add extenstyle to support Thumbnail and extension type
- Non-ACR

[Notification] Add Extension style

---

src/Tizen.NUI/src/public/BaseComponents/ViewVisuals.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisualTest.cs
test/Tizen.NUI.VisualTest/VisualTest.cs

Since some application might build app based API12, we should keep API which was exist at API12.

[NUI][VisualObject] Revive VisualObject API which was public before

---

src/Tizen.NUI/src/internal/Common/Disposable.cs
src/Tizen.NUI/src/internal/Common/TouchPoint.cs
src/Tizen.NUI/src/public/Animation/AlphaFunction.cs
src/Tizen.NUI/src/public/Application/WindowData.cs
test/Tizen.NUI.PerformanceTest/PerformanceTest.cs
test/Tizen.NUI.VisualTest/VisualTest.cs

Add more classes that we could Dispose at worker thread.
+
Make some demo dispose items well.

[NUI] More Disposable Dispose at worker thread (TouchPoint / WindowData / Builtin AlphaFunction)

---

src/Tizen.NUI/src/internal/Common/Object.cs
src/Tizen.NUI/src/internal/Interop/Interop.Actor.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/Common/Extents.cs
src/Tizen.NUI/src/public/Layouting/LayoutItem.cs

Binds extents type of property getter/setter for actor.
⚠️ related : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/327727
- ACR:

[NUI] Optimize Padding and Margin of View

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

Solves degraded quality issue of lottie view upscaling animation.
Related dali-toolkit patch : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/327494
- ACR:

[NUI] Enhance quality of scaling up lottie animation view

---

src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs
src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

This reverts commit 9448fa0d7cdc4287c4052ae896b41ae9a964462e.
As corner radius animation patch is merged in dali-toolkit, revert temporal patch.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/326023
- ACR:

Revert "[NUI] Temporal revert for Animatable View corner radius"

---

src/Tizen.NUI/src/internal/Common/NativeImageInterface.cs
src/Tizen.NUI/src/internal/Interop/Interop.NativeImageInterface.cs
src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
src/Tizen.NUI/src/internal/Interop/Interop.NativeImageSource.cs
src/Tizen.NUI/src/internal/Interop/Interop.PixelData.cs
src/Tizen.NUI/src/public/Images/NativeImageQueue.cs
src/Tizen.NUI/src/public/Images/NativeImageSource.cs
src/Tizen.NUI/src/public/Images/PixelData.cs

Let we allow to generate images with pre-multiplied options.
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/328075

[NUI] Support to generate url with premuliplied alpha

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
src/Tizen.NUI/src/public/CustomView/ViewWrapper.cs

It will throw exception when PROFILE_TV defined, and try to call Show() Hide() for CustomView.

[NUI] Register AccessibilityDelegate for CustomView

---

src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs

Let we prepare to create view at preload time if native engine support it.
Relative dali patch
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/328221

[NUI] Prepare to view creation at Preload time

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationScaleTest.cs

[NUI] Vector scale example

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs

[NUI] Seperate OnResume/OnPause override methods and events
nothing

[NUI] Seperate OnResume/OnPause override methods and events

---

src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
src/Tizen.NUI/src/public/Window/Window.cs

To control window content size when ime shown/hidden, Window (and it's LayoutController) should provide several APIs.
* LayoutController.ExtraWidth
* LayoutController.ExtraHeight
* LayoutController.OffsetX
* LayoutController.OffsetY
Also attachable data list added to Window to extend functionality from outside.
- ACR:

[NUI] Add Window properties to react ime show/hide

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs

Sometimes log didn't print at Preload case even if we success to preload

[NUI] Print log relative with Preload at OnApplicationInit

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Common/ProcessorController.cs
src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
test/Tizen.NUI.PerformanceTest/PerformanceTest.cs

- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/328794
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/328795

[NUI][Preload] Get Preinitialized window + Fix several bugs with preload view creation

---

src/Tizen.NUI/src/internal/Interop/Interop.Adaptor.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Common/Adaptor.cs

Let we support to change maximum fps per each frames.
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/329009
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/329010

[NUI][API12] Support NUIApplication.SetMaximumRenderFrameRate

---

src/Tizen.NUI/src/internal/Interop/Interop.Hover.cs
src/Tizen.NUI/src/internal/Interop/Interop.Touch.cs
src/Tizen.NUI/src/public/Events/Hover.cs
src/Tizen.NUI/src/public/Events/Touch.cs

refer
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/329264
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/329263
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/329262
- ACR:

[NUI] Add DeviceName for Hover/Touch event

---

src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs

Suppress nullable reference warnings in struct definition

[NUI] Suppress nullable reference warnings in struct definition

---

src/Tizen.NUI/src/public/Accessibility/Accessibility.cs

[NUI](Accessibility) Fix comments warning for `SetCustomHighlightOverlay`

---

src/Tizen.NUI/src/internal/Interop/Interop.Adaptor.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Common/Adaptor.cs

Let we support to change maximum fps per each frames.
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/329278
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/329279
(Same PR with #7130 )

[NUI] Support NUIApplication.SetMaximumRenderFrameRate

---

src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs

- Add Append/Remove AccessibilityAttribute bindings
- related: https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/329512

[NUI] Add a11y attribute bindings

---

src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs

Add API to remove wifi-manager config.
ACR: https://jira.sec.samsung.net/browse/TCSACR-621
- WiFiManager.RemoveWiFiConfiguration

[Tizen.Network.WiFi] Add API to remove wifi-manager config

---

src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs

Each time PackageManagerSetEvent is called, event is unsubscribe and a new subscribe is executed
If EventHandler has already been added, PackageManagerSetEvent doesn't called
- ACR: NONE

[PackageManager] Minimize the number of event registration when adding EventHandler

---

src/Tizen.NUI/src/public/Common/Rotation.cs
src/Tizen.NUI/src/public/Common/Vector3.cs
src/Tizen.NUI/src/public/Common/Vector4.cs

This PR introduces several static utility methods to the core math classes (`Vector3`, `Vector4`, `Rotation`) to improve the developer experience for 3D computations.
Key changes include:
- __Vector3/Vector4__: Added static `Distance`, `Normalize`, and `Reflect` methods. For `Vector4`, `Distance3` and `Normalize3` were also added for 3D component-specific operations.
- __Rotation__: Added a copy constructor and static `Normalize` and `Inverse` methods. These allow for immutable operations, providing more flexibility in complex calculations.
This change enhances code clarity and convenience for developers working with 3D transformations and vector math.
- ACR:

Add math method public

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/ModelLoadingStatusType.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/Scene3DModelLoadingStatusTest.cs

This PR enhances the `Tizen.NUI.Scene3D.Model` control to provide reliable and consistent feedback on its 3D model loading status. The key improvement ensures that the `ResourcesLoaded` event is fired not only on successful loading but also when loading fails, allowing developers to always determine the outcome.
__Key Changes:__
1. __Reliable `ResourcesLoaded` Event on Failure:__
- Previously, the `Model.ResourcesLoaded` event might not have been consistently emitted if the underlying 3D model resource (e.g., a glTF file) failed to load.
2. __`LoadingStatus` Property as the Source of Truth:__
- With the `ResourcesLoaded` event now firing for both success and failure cases, the `Model.LoadingStatus` property becomes the definitive way to check the outcome within the event handler.
- …

[NUI] Add property to know the model loaded status

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/NativeImageSourceTest.cs

Make we acquire buffer at worker thread.
Also ensure to release buffer after acquire finished.

[NUI.Samples] Upgrade NativeImageSourceTest sample code

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/ModelLoadingStatusType.cs
src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/internal/Interop/Interop.VideoView.cs
src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewSignal.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/public/Common/Rotation.cs
src/Tizen.NUI/src/public/Common/Vector3.cs
src/Tizen.NUI/src/public/Common/Vector4.cs
src/Tizen.NUI/src/public/RenderEffects/BackgroundBlurEffect.cs
src/Tizen.NUI/src/public/RenderEffects/GaussianBlurEffect.cs
src/Tizen.NUI/src/public/RenderEffects/RenderEffect.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FrameUpdateCallbackToggleTest.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/NativeImageSourceTest.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/Scene3DModelLoadingStatusTest.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VideoViewWithOffScreenRenderingTest.cs

Restore develNUI

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetLifecycleState.cs

The PreCreated should be '5'. This patch adjusts the order of the enumeration.

[NUI.Gadget] Fix NUIGadgetLifecycleState enumeration

---

test/Tizen.NUI.Devel.Tests.Ubuntu/nunit.framework/TUnit/TSettings.cs

We don't use network request, but just for remove build warnings.

[NUI.Devel.Tests] Remove build warnings about WebRequest

---

src/Tizen.NUI.Gadget/Tizen.NUI.Gadget.csproj
src/Tizen.NUI.Gadget/Tizen.NUI.Gadget.sln
src/Tizen.NUI.Gadget/Tizen.NUI/IServiceFactory.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
src/Tizen.NUI.Gadget/Tizen.NUI/OneShotService.cs
src/Tizen.NUI.Gadget/Tizen.NUI/OneShotServiceLifecycleChangedEventArgs.cs
src/Tizen.NUI.Gadget/Tizen.NUI/OneShotServiceLifecycleState.cs
src/Tizen.NUI.Gadget/Tizen.NUI/ServiceFactory.cs

Rebase main 250915

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
src/Tizen.NUI.Gadget/Tizen.NUI/OneShotService.cs

- Change life-cycle handling responsibility owner.
- OneShotService -> NUIGadget
- Change to call oneshotservice.
- Change to call before OnPreCreate()

[Tizen.NUI.Gadget] Refactoring about OneShotService lifecycle logic

---

src/Tizen.Network.Nsd/doc/api/Tizen.Network.Nsd.md

- Add service discovery guide with event handling
- Add proper resource cleanup sequence
- Remove deprecated ssdp service
N/A

[NSD] Update Tizen.Network.Nsd doc with usage examples

---

src/Tizen.NUI.XamlBuild/src/internal/XamlBinding/CollectionSynchronizationCallback.cs
src/Tizen.NUI.XamlBuild/src/public/XamlBuild/XamlTask.cs
src/Tizen.NUI/src/public/Template/DataTemplateSelector.cs
src/Tizen.NUI/src/public/Template/ElementTemplate.cs
src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
src/Tizen.NUI/src/public/XamlBinding/CollectionSynchronizationCallback.cs

[NUI] Deprecate XAML related APIs
- XAML is not used, so proceed Deprecated ACR
https://jira.sec.samsung.net/browse/TCSACR-618

[TCSACR-618][NUI] Deprecate XAML related APIs

---

src/Tizen.NUI/src/public/Window/BorderWindow.cs

[NUI] Revert "Register OrientationChanged for BorderWindow."
