src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

To reduce the GC call for each Event getter, let we create Key/Touch only one time for each window, and reuse it.

[NUI] Reuse internally created Key/Touch for Window.GetLastEvent API

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

Add input parameter for bvh animation loader
that we should ignore root position translate or not.
- ACR:

[NUI.Scene3D] Add property for bvh that translate by RootNode or not

---

src/Tizen.NUI/src/internal/Interop/Interop.MouseInOut.cs
src/Tizen.NUI/src/internal/Interop/Interop.WindowMouseInOutEventSignal.cs
src/Tizen.NUI/src/internal/Window/WindowMouseInOutEventSignal.cs
src/Tizen.NUI/src/public/Window/MouseInOut.cs
src/Tizen.NUI/src/public/Window/WindowEvent.cs

You can receive events when the mouse cursor appears or disappears from a window.
If MouseInOut.StateType.In, the mouse cursor entered the window.
If MouseOut.StateType.Out, the mouse cursor exited  the window.
```c++
window.MouseInOutEvent += (s, e) =>
{
Tizen.Log.Info("NUI", $"State {e.MouseInOut.State}");
}
```
- ACR:

[NUI] Add WindowMouseInOutEvent

---

src/Tizen.NUI/src/internal/Interop/Interop.MouseInOut.cs
src/Tizen.NUI/src/internal/Interop/Interop.WindowMouseInOutEventSignal.cs
src/Tizen.NUI/src/internal/Window/WindowMouseInOutEventSignal.cs
src/Tizen.NUI/src/public/Window/MouseInOut.cs
src/Tizen.NUI/src/public/Window/WindowEvent.cs

You can receive events when the mouse cursor appears or disappears from a window.
If MouseInOut.StateType.In, the mouse cursor entered the window.
If MouseInOut.StateType.Out, the mouse cursor exited the window.
```c++
window.MouseInOutEvent += (s, e) =>
{
Tizen.Log.Info("NUI", $"State {e.MouseInOut.State}");
}
```
refer :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/292294/ 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/292295/
- ACR:

[NUI] Add WindowMouseInOutEvent (#5242)

---

src/Tizen.NUI/src/internal/Interop/Interop.Touch.cs
src/Tizen.NUI/src/public/Events/Touch.cs

Binding GetDeviceClass and GetDeviceSubClass
```c++
view.TouchEvent += (s, e) =>
{
if (DeviceClassType.Mouse == e.Touch.GetDeviceClass(0))
{
}
else if (DeviceClassType.Touch == e.Touch.GetDeviceClass(0))
{
}
return false;
}
```
refer :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/292340/
- ACR:

[NUI] Binding GetDeviceClass and GetDeviceSubclass of touch event

---

src/Tizen.NUI.Components/Controls/Button.Internal.cs

When max width of Text is calculated in Vertical alignment, Width of Icon should be ignored, and start & end of Text Padding need be excluded, not top & bottom of Text Padding.
- ACR:

[NUI][API10] Fix the issue that max width of Button Text is incorrect.

---

src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/PrivacyPrivilegeManager.cs

Change-Id: I519abb343b5f4e49d2256a9b0abf69d4fb755632
Mark all Tizen.Security.PrivacyPrivilegeManager APIs as deprecated
ACR: https://code.sec.samsung.net/jira/browse/TCSACR-525

Mark all Tizen.Security.PrivacyPrivilegeManager APIs as deprecated

---

src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/BluetoothPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/BrowserPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/DevicePolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/DevicePolicyManager.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/EmailPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/LocationPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/MediaPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/PasswordPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/PasswordQuality.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/PolicyChangedEventArgs.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/StoragePolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/TelephonyPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/UsbPolicy.cs
src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/WifiPolicy.cs

Deprecate DevicePolicyManager APIs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-539

[DevicePolicyManager] Deprecate DevicePolicyManager APIs

---

src/Tizen.Data.Tdbc.Driver.Sqlite/Tizen.Data.Tdbc.Driver.Sqlite/Connection.cs

If the delete statement is executed, the record can't be returned because the value for the rowid doesn't exist in the database Therefore, in the case of delete, the record is returned to null

[Tdbc] Fix Sqlite update hook

---

src/Tizen.NUI/src/internal/Interop/Interop.FontClient.cs
src/Tizen.NUI/src/public/Utility/FontClient.cs

This patch adds a new FontPreLoad API that preloads font faces.
this can prevents delays on main thread during the inital call of FT_New_Face.
using memoryFontPathList involves loading font buffers into memory. 
And using FT_New_Memory_Face at runtime, which uses more memory but can lead to greater performance improvements.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/292224/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/292534/

[NUI] Add FontPreLoad API to FontClient

---

src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs

Currently, it is impossible to differentiate between the mobile and common profiles.
Until profile differentiation becomes possible, set the default scale for each profile to 1.
* default font size scale of PROFILE_MOBILE = FontSizeScaleLarge
* default font size scale of PROFILE_COMMON = FontSizeScaleNormal

[NUI] fix font size scale issue in fhub

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

Since json file can change not only facial, The name of API is not good.
Instead, Let we change the name of facial API as 'BlendShapeAnimation'. Now user can notify that this API can control all kinds of blendshape.

[NUI.Scene3D] Change the API name for BlendShape morphing

---

src/Tizen.NUI/src/internal/Common/Object.cs
src/Tizen.NUI/src/internal/Interop/Interop.Handle.cs
src/Tizen.NUI/src/public/Animation/Animatable.cs

[NUI] Binds GetCurrentProperty to Animatable class

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Let's believe the cached properties what LottieAnimationView already cached.
Since ImageView.Image is heavy operation, we should call this thing less times.

[NUI] Reduce get/set overhead for some LottieAnimationView properties

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Let's beleve the cached properties what LottieAnimationVIew already cached.
Since ImageView.Image is heavy operation, we should call this thing less times.

[NUI][API10] Reduce get/set overhead for some LottieAnimationView properties

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Previously, we don't cache Url infomation at cached property map when we use SetImage API instead of ResourceUrl property.
Now, let we keep this cache information.
And also, add parameter that we dont want to create new visual when we change this property.

[NUI] Cache url when we call SetImage + Make way to skip visual creation

---

src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

To avoid useless PropertyValue class creation, let we change to visual use InternalVisual APIs.
- ACR:

[NUI][API10] Let LottieAnimationView use InternalVisual API

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs

If a View's DispatchParentTouchEvents is set to false, then parents will not receive a touch event signal either.
- ACR:

[NUI] Add DispatchParentTouchEvent

---

src/Tizen.NUI/src/public/Animation/Animation.cs

That API change the 'EndAction' property.
And also, EndAction input parameter will not works well if
- It's value is EndActions.Discard
- Already finished animation
So, we'd better guide to app developer to use EndAction property instead of Stop(EndActions) API.
- ACR: ACR-540 https://code.sec.samsung.net/jira/browse/TCSACR-540
Deprecated:
- void Stop(EndActions action);

[NUI] Deprecated Animation.Stop(EndActions)

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs

Currently, the public API only allows static attribute values, for example:
```c#
// Initial value:
view.AccessibilityAttributes["current_page"] = CurrentPage;
// Need to update in some other place in code when CurrentPage changes:
view.AccessibilityAttributes["current_page"] = CurrentPage;
```
Due to this difficulty, `Pagination` uses a hack with a static attribute `AccessibilityAttributes["style"] = "pagecontrolbyvalue"` and unnecessarily implementing the `IAtspiValue` interface and passing `SelectedIndex` via `IAtspiValue.AccessibilityGetCurrent`.
However, the attributes are actually already evaluated dynamically on demand in the helper method `AccessibilityGetAttributes` called by the AT-SPI bridge. Therefore, it makes sense to allow associating a key with a functor as well as a …

[NUI][AT-SPI] Add AccessibilityDynamicAttributes

---

src/Tizen.NUI/src/internal/Interop/Interop.Rotation.cs
src/Tizen.NUI/src/public/Common/Rotation.cs

This patch is to add new constructor of Rotation that using Quaternion Vector4 as an input parameter.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/293354/
- ACR:

[NUI] Add new constructor to Rotation by using Quaternion vector4

---

src/Tizen.Applications.Common/Tizen.Applications/CultureInfoHelper.cs

When ini file does not exist, LibIniParser.Load() makes error logs. This patch is to remove this case.

[Applications.Common] Fix file not found exception

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetResourceManager.cs

When getting the resource manager using the current culture info is failed, the NUIGadgetResourceManager tries to get the resource manager using the "default" string. It means using "/res/allowed/<resource>.dll" file.
If getting string is failed, the resource manager should try to get string from the default satelite assembly.

[NUI.Gadget] Modify NUIGadgetResourceManager class

---

src/Tizen.NUI/src/internal/Interop/Interop.FontClient.cs
src/Tizen.NUI/src/public/Utility/FontClient.cs

If sync creation is true, font thread creation guarantees syncronization with the main thread.
The main thread runs the font thread and waits,
and it wakes up upon receiving a notification from the font thread. If it doesn't receive a notification within the specified time, it wakes up due to a timeout.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/293316/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/293373/

[NUI] Add font thread sync creation option

---

src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
src/Tizen.NUI/src/public/Accessibility/IAtspiTable.cs
src/Tizen.NUI/src/public/Accessibility/IAtspiTableCell.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEnum.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs

The purpose of these interfaces is to support Screen Reader operation with tables and grids (`Tizen.NUI.FLUX.Components.GridH` etc.), often in combination with `IAtspiSelection` (already present in TizenFX), for example reading the row and column number when navigating a grid of items, or selecting cells / rows / columns, as specified in the UX guide.
Dependencies (ABI change - need to be merged at the same time):
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/280895/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/280902/
- ACR:

[NUI][AT-SPI] Add IAtspiTable and IAtspiTableCell interfaces

---

src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
src/Tizen.NUI/src/public/Accessibility/IAtspiTable.cs
src/Tizen.NUI/src/public/Accessibility/IAtspiTableCell.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEnum.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs

Note: This is an API10 backport of https://github.com/Samsung/TizenFX/pull/5305.
The purpose of these interfaces is to support Screen Reader operation with tables and grids (`Tizen.NUI.FLUX.Components.GridH` etc.), often in combination with `IAtspiSelection` (already present in TizenFX), for example reading the row and column number when navigating a grid of items, or selecting cells / rows / columns, as specified in the UX guide.
Dependencies (ABI change - need to be merged at the same time):
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/293419/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/293418/
- ACR: None

[NUI][API10][AT-SPI] Add IAtspiTable and IAtspiTableCell interfaces

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
src/Tizen.NUI/src/internal/Interop/Interop.WindowData.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Application/WindowData.cs

The NUIApplication class had to add new constructors whenever the Window class added a new constructor. Because the class has a default window. To simplify this process, WindowData is introduced which contains all the data of the default window.
refer to : 
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/290155
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/290165
The above patches were merged.

[NUI] Introduce WindowData

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

[NUI] Fix incorrect calculation of configGestureCount.
- ACR:

[NUI] Fix incorrect calculation of configGestureCount.

---

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
src/Tizen.NUI/src/public/Common/Container.cs

[NUI] Fix issue of get ScrollableBase instance's Children

---

src/Tizen.NUI/src/public/CustomView/CustomViewRegistry.cs

[STATISTICAL] Value viewType.ToString(), which is result of method invocation with possible null return value, is dereferenced in method call constructorMap.Add()。
- ACR:

[NUI][API10] Fix a svace issue in CustomViewRegistry.cs.

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs

If DispatchHoverEvents sets false, view will not receive any HoverEvent including own. 
If DispatchPrentHoverEvents sets false, the parent view does not receive HoverEvent.
- ACR:

[NUI] Add DispatchHoverEvents and DispatchPrentHoverEvents

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Common/DaliEnumConstants.cs

[NUI] Add Window validation check
- before the dali adaptor and window are not ready, the `Interop.Application.GetWindowsListSize()` gives native crash (dali assert)
- error msg =>
2112.329 D/DOTNET_LAUNCHER(P 9983, T11096): log.h: ~FunctionEntryExitTracker(91) > [90m-DotNETLog:log.cc(80) void writeStringTofile(char*)[0m
2112.329 E/DOTNET_LAUNCHER(P 9983, T11096): log.cc: stdErrRedirect(127) > [31mException: [0m
2112.329 E/DOTNET_LAUNCHER(P 9983, T11096): log.cc: stdErrRedirect(127) > [31mIsAvailable() && "Adaptor not instantiated"[0m
2112.329 E/DOTNET_LAUNCHER(P 9983, T11096): log.cc: stdErrRedirect(127) > [31m thrown[0m
- add validation checking in `GetWindowList()`
none

[NUI] Add Window validation check

---

src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs

[NUI] Skip when the View.BackgroundImage is set with the same value as previous one
none

[NUI] Skip when the View.BackgroundImage is set with the same value as previous one

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

If we skip to set ImageVisualType, or set ImageVisualType as Image, we will try to find best visual by it's file format codes. But previously, we fix the type of visual.
So, instead of some special case like URLs, just make we use Image type.
And also, make _resourceUrl latest value if we success to get url from visual.
Now we can store _resourceUrl even we update the `Image` property.

[NUI] Make subclass of ImageView can use ResourceUrl normally.

---

src/Tizen.NUI/src/internal/Interop/Interop.Actor.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

Current screen extents API calculated by 'Current' properties. That mean, the result of calculation late 1 render-frame. So, we cannot use it during Relayout events.
Now, make internal API so we can get abstract screen extents calculated by event-side properties.
This patch required below patches
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/292839
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/292840
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/292841

[NUI] Make hidden API for calculate screen extents.

---

src/Tizen.Applications.ThemeManager/Tizen.Applications.ThemeManager/ThemeLoader.cs

Clear current theme cache when theme changed
- ACR: N/A

[ThemeManager] Clear current theme cache when theme changed

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

After overhead reducetion patch #5280 merged, Some side effect occured.
Previously we always ask some properties to dali side visual. But now we return cached value in NUI.
Since URL property clear-up all properties, to fit previous logic, let we also clean-up cached properties. (Actually, mark only for this case)

[NUI] Clear old resources cached marker data

---

src/Tizen.NUI/src/internal/Layouting/LayoutController.cs

WID:61196553 [STATISTICAL] Value root.Layout, which is result of method invocation with possible null return value, is dereferenced in member access expression root.Layout.MeasuredHeight
- ACR:

[NUI][API10] Fix a SVACE issue.

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs

Since we don't check validation of ImageView itself during change ImageView properties, it will not throw any exceptions. and it will be crashend when we ProcessOnceEvent invoked.
Normal View property directly access to DALi side. But ImageView property access to DALi side lazy.
Now this throw make app developer easy to find error codes.

[NUI] Exception if someone change disposed ImageView's property

---

src/Tizen.NUI.Components/Theme/DefaultTheme.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Theme/ThemeManager.cs

Because of the dbus issue from tizen theme manager, this patch removed NUI ThemeManager from the preload.
- ACR:

[NUI] Disable ThemeManager preload

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

- Add ModelRoot Property to retrieve root ModelNode of the Model object.
- Change parameter name of AddModelNode and RemoveModelNode to modelNode
- ACR:

[NUI] Add ModelRoot Property in Model class

---

src/Tizen.NUI/src/internal/Interop/Interop.ActorSignal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Window/WindowEvent.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableFocus/ScrollableFocusSample.cs

The Wheel event calls the WheelEvent callback by going back from the last child actor to the parent via hitTest. InterceptWheelEvent checks the wheel event in the parent first. Returning false from interceptWheelEvent allows child actors to receive WheelEvents. If it returns true, the actor will receive a WheelEvent.
for example
```c++
View parent = new View();
View child = new View();
parent.Add(child);
child.WheelEvent += childFunctor;
parent.WheelEvent += parentFunctor;
```
The callbacks are called in the order childFunctor -> parentFunctor.
If you connect InterceptWheelEvent to parentActor.
```c++
parent.InterceptWheelEvent += interceptFunctor;
```
When interceptFunctor returns false, it is called in the same order childFunctor -> parentFunctor. If intereptFunctor returns true, it …

[NUI] Add InterceptWheelEvent

---

src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs

- Except for TV and wearable profiles, FontSizeScale values are updated.
- N/A

[NUI] Update FontSizeScale values

---

src/Tizen.NUI/src/internal/Widget/WidgetImpl.cs
src/Tizen.NUI/src/public/Widget/Widget.cs
test/Tizen.NUI.WidgetViewTest/0.Template/Tizen.NUI.WidgetTest/SimpleWidgetApp.cs
test/Tizen.NUI.WidgetViewTest/0.Template/Tizen.NUI.WidgetViewTest/SimpleWidgetViewApp.cs

Delete the used window so that the window can be deleted normally when deleting the widget. this is for memory leak issue.
- ACR:

[NUI] Delete the used window in widget

---

src/Tizen.NUI.Components/Controls/Menu.cs
src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs

Scrim should block all touch and gesture events.
Therefore, gesture is also not propagated from scrim.
- ACR:

[NUI] Fix not to propagate gesture from scrim

---

src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs

Note: This is an API10 port of https://github.com/Samsung/TizenFX/pull/5386.
This aligns the behaviour of `Components` (derived from `CustomView`), and other controls, with that of `BaseComponents` (and other controls with `ViewAccessibilityMode.Default`, backed by the C++ accessibility implementation), which set the keyboard focus on activation. Please note that in the latter case, the implementation of `View.OnAccessibilityActivated` is unused, and the unrelated method (albeit bearing the same name) `Control::OnAccessibilityActivated` is called:
```cpp
bool Control::OnAccessibilityActivated()
{
if(Toolkit::KeyboardFocusManager::Get().SetCurrentFocusActor(Self()))
{
return OnKeyboardEnter();
}
return false;
}
```
So, in other words, this patch makes C# controls behave in a similar …

[NUI][API10][AT-SPI] Set focus in OnAccessibilityActivated()

---

src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

Synchronizing DALi and NUI cameras' parent.
DALi's SelectCamera() includes unparenting current camera component, and NUI's SelectCamera() simply calls the function.
However, since they manage different objects on each side, NUI's camera is still attached to its parent.
This can be a problem in a situation such as:
// dummy is a View
dummy.Add(defaultCamera);
sceneView.Add(dummy);
sceneView.SelectCamera(1u);
sceneView.SelectCamera(0u);
dummy.Add(defaultCamera);
In NUI side, default camera was never detached from dummy but DALi's SceneView now has both dummy and default camera as its children. (The last line is ignored on NUI side.)

[NUI] Switch camera includes current camera's Unparent()

---

src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs

- The font size scales are changed according to the latest GUI guide.
- Five stages of Font size scale : 87% -> 100% -> 113% -> 126% -> 140 %
- N/A

[NUI] Update Font size scale again based on the updated guide

---

src/Tizen.NUI/src/public/Common/Layer.cs

To notice the visibility changes of Layer, VisibilityChanged event is added to Layer.
- ACR:

[NUI] Add VisibilityChanged event to Layer

---

src/Tizen.NUI/src/internal/Common/RenderTask.cs

RenderTask 는 RenderTaskList에서 삭제하지 않으면 사라지지 않으므로 dispose 될 때 삭제하는 로직을 추가했습니다.
- ACR:

[NUI] Remove RenderTask itself from the RenderTaskList when disposed

---

src/Tizen.NUI/src/internal/Interop/Interop.LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Since we change the value of SetDynamicProperty value in dali side, we need to get correct value from dali.
relative dali patches : 
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/296210

[NUI] Get Lottie ActionId of SetDynamicProperty

---

src/Tizen.NUI/src/public/Window/Window.cs

[NUI] Add logic to check if GetLastTouchEvent() is null.
- ACR:

[NUI] Add logic to check if GetLastTouchEvent() is null.

---

src/Tizen.NUI/src/public/Window/Window.cs

[NUI] Restore FeedHover due to api compatibility issue.
And the null check is done in FeedHover.
revert : https://github.com/Samsung/TizenFX/pull/5411
- ACR:

[NUI] Restore FeedHover due to api compatibility issue.

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

Add new feature about flag that ImageView's image uploading faster.
Previously, NUI has some operations to support some kind of visual transition, or calculate natural size for relayout, or etc.
This patch make a way to user that we need to upload image as soon as possible, don't care about other platform supported features.
relative dali patches :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/295645
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/294405
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/295658

[NUI] Fast track uploading image

---

test/Tizen.NUI.PerformanceTest/PerformanceTest.cs

Previously, we can emit OnAnimationFinished callback during app shutting down. In this case, a lots of bugs can be occured.
Now let we make clean up all BaseHandle Disposed.
And also, remove ImageView's background color which is useless.
- ACR:

[NUI][Samples] Fix exception during shutdown + Remove useless codes

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs

Since we share the same action id for each Play / Pause / etc, we don't need to consider overwrite the action id now.

[NUI] Make Action id as internal static readonly

---

src/Tizen.NUI/src/internal/Common/WeakEvent.cs

* WeakEventProxy : The weak event connecting to a normal event.
- ACR:

[NUI] Add WeakEventProxy class and improve invoke of WeakEvent

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

Prototype codes for Borderline / CornerRadius feature update lazy.
Since we don't need to apply background extra data multiple times, Let we collect all changeness informations + Apply it once.

[NUI] Lazy Update CornerRadius/Borderline

---

src/Tizen.NUI/src/public/Events/Touch.cs

Registry is not required at GetTouchFromPtr()
In the case of an object created from DALi, it is created with new BaseHandle(intPtr, false).
- ACR:

[NUI] Registry is not required at GetTouchFromPtr()

---

src/Tizen.Multimedia.Remoting/Interop/Interop.WebRTC.cs
src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs

Add Mute API for audio track
- TCSACR-542

[WebRTC] Add Mute API for audio track

---

src/Tizen.Multimedia.AudioIO/WavPlayer/WavPlayerError.cs
src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs
src/Tizen.Multimedia.Metadata/MetadataEditor/MetadataEditorError.cs
src/Tizen.Multimedia.Metadata/MetadataExtractor/MetadataExtractorError.cs
src/Tizen.Multimedia.Recorder/Recorder/RecorderExtensions.cs
src/Tizen.Multimedia.Remoting/MediaController/MediaControlEnums.cs
src/Tizen.Multimedia.Remoting/MediaController/MediaControllerError.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCError.cs
src/Tizen.Multimedia.Remoting/WebRTC/WebRTCSignalingServer.cs
src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorderEnums.cs
src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorderError.cs
src/Tizen.Multimedia.Util/ImageUtil/ImageUtilEnums.cs
src/Tizen.Multimedia.Vision/MediaVision/VisionColorSpace.cs

Fix VD SVACE issue
- MediaController(DF230727-02438/02439/02441/02444/02459)
- Recorder(DF230727-02443)
- StreamRecorder(DF230727-02445/02446/02448/02455)
- ImageUtil(DF230727-02447)
- WebRTC(DF230727-02449)
- WavPlayer(DF230727-02451)
- ThumbnailExtractor(DF230727-02454)
- MetadataEditor(DF230727-02456)
- MetadataExtractor(DF230727-02457)
- MediaVision(DF230727-02458)
- MediaPlayer(DF230727-02460)

[Multimedia] Fix VD SVACE issues

---

src/Tizen.NUI/src/internal/Common/RenderTask.cs

[STATISTICAL] Value Application.GetWindowList(), which is result of method invocation with possible null return value, is dereferenced in foreach argument
- ACR:

[NUI] Fix SVACE issue.

---

src/Tizen.NUI/src/internal/Interop/Interop.WindowInsetsChangedSignal.cs
src/Tizen.NUI/src/internal/Window/WindowInsetsChangedSignal.cs
src/Tizen.NUI/src/public/Window/WindowEvent.cs

Window insets are the inner size between window content and window edge.
Window insets are required when status bar, virtual keyboard, or clipboard appears on window to avoid window content obscured by them.
To notify the window insets changes, InsetsChanged event is added to Window.
- ACR:

[NUI] Add InsetsChanged event to Window

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Since #5350 patch will reset previous whole informations when we use ResourceUrl.
So, If user set ResourceUrl set DesiredSize, the desired size informatins disapeared.

[NUI] Fix issue when LottieAnimationView use DesiredSize

---

src/Tizen.NUI/src/internal/Common/WeakEvent.cs
src/Tizen.NUI/src/internal/Common/WeakEventProxy.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs

TextLabel, TextField, TextEditor가 SystemSettings event에 handler를 등록해두어 Dispose콜 없이는 GC가 되지 않던 문제를 수정했습니다. 
* Improve WeakEvent
* Lazy list initialization
* Provide count changed callback methods
* Separate file into WeakEvent and WeakEventProxy
* Fix TextLabel, TextField, TextEditor
* Do not register event handler to the system event directly.
* Instead they use WeakEventProxy to get GCed without Dispose call.
- ACR:

[NUI] Remove strong references of text components regarding events

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Application/NUIWidgetApplication.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FlushApplicationMessageSample.cs

Add new API to relayout & flush update/render thread messages.
It is for advanced app developer.
This API will flush all queued messages and rendering well. But if we call it frequency, it will occure main thread overhead.
Relative dali patch 
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/296629
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/296630
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/297479

[NUI] Applicatoin.FlushUpdateMessage

---

src/Tizen.System.Feedback/Feedback/Feedback.cs

To call below feedback internal API, App should have accurate privilege.
Description and privilege type is added to below API.
- public void SetThemeIndexInternal(FeedbackType type, uint indexOfTheme)
- ACR:

[System.Feedback] Add privilege description to internal API for multi-theme

---

src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs

Due to some legacy app use this internal property, we should revive this legacy property.
It will be removed after all apps change this legacy codes

[NUI] Revive IsBinded API for Xaml

---

src/Tizen.Uix.VoiceControl/Tizen.Uix.VoiceControl/VoiceControlClient.cs

Remove unsupported error type according to the description of native CAPI. 
- ACR: NON-ACR

[VoiceControl] remove unsupported error type

---

src/Tizen.NUI.Components/Tizen.NUI.Components.csproj

[NUI] Make Tizen.NUI.Components not be preloaded in TV profile
none

[NUI] Make Tizen.NUI.Components not be preloaded in TV profile

---

src/Tizen.NUI/src/internal/Common/SystemFontSizeChangedManager.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs

SystemFontSizeChangedManager is a static class which adds user handlers
to the SystemSettings.FontSizeChanged event.
It is similar to SystemFontSizeChanged class but it is a static class
and it also provides Finished event handler invoked last after all
handlers added to the SystemSettings.FontSizeChanged event are invoked.
- ACR:

[NUI] Add SystemFontSizeChangedManager class

---

src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs
src/Tizen.Multimedia.Vision/MediaVision/InferenceType.cs

Remove deprecated API
- InferenceTargetType enum
- Target property
- TCSACR-

[MediaVision] Remove deprecated API - InferenceTargetType

---

src/Tizen.NUI.Components/Controls/Popup.cs
src/Tizen.NUI.Wearable/src/public/Title.cs

fix the issue : Value e.PropertyName, which is result of method invocation with possible null return value, is dereferenced in method call e.PropertyName.Equals()
- ACR:

[NUI] Fix the SVACE issue.

---

src/Tizen.Uix.Tts/Interop/Interop.Tts.cs
src/Tizen.Uix.Tts/Tizen.Uix.Tts/SynthesizedPcmEventArgs.cs
src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs

Add internal method for playing mode and synthesized pcm event.

[Tts] Add new internal API for TTS synthesized PCM

---

src/Tizen.NUI/src/internal/Interop/Interop.Clipboard.cs

ref : 5ca58e74d71e2e91a9b0a8b549b3cffad232f6f9
Make sure that Interop return type is bool
Marshal's bool is mapped to 4byte in default.
So if native-code return boolean type, the datasize is mismatched and make problems

[NUI] Add missing code

---

src/Tizen.Data.Tdbc.Driver.Sqlite/Tizen.Data.Tdbc.Driver.Sqlite/Connection.cs

When the operation type is delete, the empty record will be passed to callback.
- ACR: N/A

[Tdbc] Fix sqlite driver

---

src/Tizen.NUI/src/internal/Interop/Interop.PointerConstraints.cs
src/Tizen.NUI/src/internal/Interop/Interop.WindowPointerConstraintsSignal.cs
src/Tizen.NUI/src/internal/Window/WindowPointerConstraintsSignal.cs
src/Tizen.NUI/src/public/Window/PointerConstraints.cs
src/Tizen.NUI/src/public/Window/WindowEvent.cs

[NUI] Binding PointerConstraintsEvent
```c++
window.PointerConstraintsEvent += OnPointerConstraints;
private void OnPointerConstraints(object sender, PointerConstraintsEventArgs e)
{
//e.PointerConstraints.Position.X
//e.PointerConstraints.Position.Y
//e.PointerConstraints.Locked
//e.PointerConstraints.Confined
}
```
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/298394/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/298506/
- ACR:

[NUI] Binding PointerConstraintsEvent

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

Since GetLastTouchEvent returns all values ​​regardless of touch or hover, it was separated into GetLastTouchEvent and GetLastHoverEvent.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/298755/ https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/298753/ https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/298752/
- ACR:

[NUI] Binding GetLastHoverEvent

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs

Visual look at same value, Visual.MixColor's alpha and Visual.Opacity, we need to synchronize both values.
Since we don't open Visual.Opacity property for View side let we control this value inside of View.

[NUI] Fix ImageColor alpha not applied issue

---

src/Tizen.System.Feedback/Feedback/Feedback.cs
src/Tizen.System.Feedback/Interop/Interop.Feedback.cs

Allows feedback stop according to feedback type.
This is newly added to System.Feedback.
- public void StopTypeInternal(FeedbackType type)
-> It stops current feedback playing according to the feedback type.
- ACR:

[System.Feedback] Add internal API to support feedback stop by feedback type

---

src/Tizen.NUI/src/public/Window/WindowEvent.cs

bug fixed about windowPointerConstraintsEventCallback

[NUI] bug fixed about windowPointerConstraintsEventCallback

---

src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/Window/WindowEvent.cs

These determine whether to send touch and hover motion events or not. This is used when the user does not want to receive motion events.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/299176/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/299177/
- ACR:

[NUI] Binding DispatchTouchMotion and DispatchHoverMotion

---

src/Tizen.NUI/src/public/Widget/Widget.cs

widget need to keep it's instance
- ACR:

[NUI] Add widget list for keeping widget instance

---

src/Tizen.NUI/src/internal/Interop/Interop.VisualFactory.cs
src/Tizen.NUI/src/public/Visuals/VisualFactory.cs

This PR adds VisualFactory.UsePrecompiledShader method.
This method is to precompile visual's shader and make newly created visual use the shaders.
- ACR:

Add VisualFactory.UsePrecompiledShader()

---

src/Tizen.NUI/src/public/Events/Touch.cs
src/Tizen.NUI/src/public/Window/Window.cs

Since we change BaseObject internally when we use
Interop.Window.InternalRetrievingLast~~~Event(~~) function.
This behaviour might occure some error cases when we use Registry system.

[NUI] Do not registry last event items who get retrieved

---

src/Tizen.NUI/src/internal/Interop/Interop.Key.cs
src/Tizen.NUI/src/public/Input/Key.cs
src/Tizen.NUI/src/public/Window/Window.cs

Let we use default key creation API if we only need to use empty key handle.
- ACR:

[NUI] Implement defaut key construct

---

src/Tizen.NUI/src/public/Window/Window.cs

Since we create new DALi handle internally, we also delete them.
But if we mark cMemOwn as false, we dont call deletr autimatically.
The GetLast~~Events are special cases that have there own handle, but not have memory ownership
So we need to call Delete function hardly, by our selfs.
TODO : We need to find more good way to fix this Dispose issue. Currently just remark to user that dont call Dispose for it l.

[NUI] Let us not dispose cached LastEvents

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.MotionIndex.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionData.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionIndex/BlendShapeIndex.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionIndex/MotionIndex.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionIndex/MotionPropertyIndex.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionIndex/MotionTransformIndex.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionValue.cs

1. Fix TCT error #5576
2. Follow some comments fix up as #5452

[NUI.Scene3D] CodeSync MotionData API and documents

---

src/Tizen.NUI.Components/Controls/ScrollableBase.cs

- `ScrollableBase` in some apps is not working well in screen reader on mode.
- Fix to propagate the scroll gesture event all the time.
- N/A

[NUI] Fix the scroll issue on Accessibility

---

src/Tizen.NUI.Components/Controls/TabButton.cs

WID:13452033 [STATISTICAL] Value tabButtonStyle.Icon.Size, which is result of method invocation with possible null return value, is dereferenced in member access expression tabButtonStyle.Icon.Size.Width
WID:13451996 [STATISTICAL] Value tabButtonStyle.Size, which is result of method invocation with possible null return value, is dereferenced in member access expression tabButtonStyle.Size.Width
- ACR:

[NUI] Fix some SVACE issues of null reference.

---

src/Tizen.NUI.Physics2D/src/internal/chipmunk/NativeInterop.cs
src/Tizen.NUI.Physics2D/src/internal/chipmunk/cpSpaceDebugDrawOptions.cs
src/Tizen.NUI.Physics2D/src/public/chipmunk/Body.cs
src/Tizen.NUI.Physics2D/src/public/chipmunk/Space.cs
src/Tizen.NUI.Physics2D/src/public/chipmunk/SpaceRef.cs

fix some SVACE  issues
1,overflow may happen when Intptr.Size * count is 0. WID:12816660. An overflow in the arithmetic expression Intptr.Size * count which is used in Marshal.AllocHGlobal(IntPtr.Size  *  count) may occur. Please use checked arithmetic  to throw IntegerOverflowException in case of overflow instead of possible memory damage.
2,cpSpaceDebugDrawOptions.cs
bufffer size may be 0, element byte size is 108. WID:12806918.Writing 1 element of type Tizen.NUI.Physics2D.Chipmunk.cpSpaceDebugDrawOptions into buffer drawOptionsPtr can exceed its size.
- ACR:

[NUI] Fix some SVACE issues related to methods of Marshal.

---

src/Tizen.NUI/src/public/Common/BaseHandle.cs
src/Tizen.NUI/src/public/Events/Hover.cs
src/Tizen.NUI/src/public/Events/Touch.cs
src/Tizen.NUI/src/public/Events/Wheel.cs
src/Tizen.NUI/src/public/Images/PixelBuffer.cs
src/Tizen.NUI/src/public/Images/PixelData.cs
src/Tizen.NUI/src/public/Input/Key.cs
src/Tizen.NUI/src/public/Window/Window.cs

There are some usecase s.t. we have to call ReleaseSwigCPtr but don't want register to Registry.
For example, PixelBuffer and PixelData dont need to be create only for main thread.

[NUI] BaseHandle without Registry but own memory

---

src/Tizen.NUI/src/internal/Common/Registry.cs

Since NUI use DisposeQueue system instead of GC directly, the lifecycle of WeakReference may need to be alive more times.
If we make trackResurrection as false, WeakReference.Target become null when the item is in DisposeQueue.

[NUI] Consider WeakReference resurrection at Registry.

---

src/Tizen.NUI/src/public/Events/Hover.cs
src/Tizen.NUI/src/public/Events/Touch.cs
src/Tizen.NUI/src/public/Events/Wheel.cs
src/Tizen.NUI/src/public/Input/Key.cs

bug fixed about cMemoryOwn
refer : https://github.com/Samsung/TizenFX/pull/5603
- ACR:

[NUI] bug fixed about cMemoryOwn

---

src/Tizen.NUI/src/public/Input/Key.cs

[NUI] revert default key construct
refer : https://github.com/Samsung/TizenFX/pull/5589/
- ACR:

[NUI] revert default key construct

---

src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextMapHelper.cs
src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TextFitChangedSample.cs

Add a new function to satisfy the UX that
operates TextFit by considering the PointSize and MinLineSize of the text.
For example, TextFit should be able to find the one that fits among [PointSize 24 + MinLineSize 40] or [PointSize 28 + MinLineSize 44].
But the previous TextFit only considers PointSize.
TextFitArray can solve this problem,
and this implemented it to respond to additional requirements without modifying the API.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/299557/ 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/299690/

[NUI] Add TextFitArray

---

src/Tizen.NUI/src/internal/WebView/WebContext.cs
src/Tizen.NUI/src/internal/WebView/WebCookieManager.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

This patch is merged from DevelNUI:
https://github.com/Samsung/TizenFX/pull/5329
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/299804/
- ACR:

[NUI][API10] Unregister callbacks when passed argument is null.

---

src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs

Reference documents : https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/
To refer to XML elements (for example, your function processes specific XML elements that you want to describe in an XML documentation comment), you can use the standard quoting mechanism (&lt; and &gt;).
- ACR:

[NUI] Resolve TextLable build warning

---

src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs
src/Tizen.NUI/src/public/Events/Gesture.cs
src/Tizen.NUI/src/public/Events/LongPressGesture.cs
src/Tizen.NUI/src/public/Events/PanGesture.cs
src/Tizen.NUI/src/public/Events/PinchGesture.cs
src/Tizen.NUI/src/public/Events/RotationGesture.cs
src/Tizen.NUI/src/public/Events/TapGesture.cs

1. PanGesture from Accessibility create new handle in dali csharp side. We need to have memory ownership, but don't need to register it on NUI side. We can ignore it.
2. For Animation and StyleManager, it is possible to use that 'already registered' BaseHandle. But in this case, we should not dispose it by our self.

[NUI] Fix Registry exception for custom view wrapper

---

src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
src/Tizen.NUI/src/public/Accessibility/Accessibility.cs

This is one of the oldest interops and was actually problematic for multiple reasons; the return type didn't match and the third parameter was expected to have exactly the same value in every invocation. While fixing these issues, parsing the status string was moved from C++ to C# for readability.
Dependency: https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/299825/
- ACR: None

[NUI][AT-SPI] Fix Accessibility.Say interop

---

src/Tizen.Applications.Common/Interop/Interop.Libc.cs
src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs

This patch changes using free() to using Marshal.FreeHGlobal().
To avoid crash issues in the asan binary, the library should not use Libc.Free() function directly as possible.

[Applications.Common] Use Marshal.FreeHGlobal() instead of Libc.Free()

---

src/Tizen.NUI/src/internal/Common/RenderTaskList.cs
src/Tizen.NUI/src/public/Window/Window.cs

After patch #5595 merged, there was some hidden bugs occured. This PR is one of portential bug fix.

[NUI] Resolve registry issue for RenderTaskList

---

src/Tizen.Network.Connection/Interop/Interop.Glib.cs
src/Tizen.Network.Connection/Tizen.Network.Connection/CellularProfile.cs
src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
src/Tizen.Network.Connection/Tizen.Network.Connection/IAddressInformation.cs
src/Tizen.Network.Connection/Tizen.Network.Connection/WiFiProfile.cs

Use g_free() instead of free() to avoid ASAN crash.

[Connection] Fix ASAN crash issue

---

src/Tizen.NUI/src/public/Window/Window.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FrameUpdateCallbackTest.cs

Previously, we can only add the root view of FrameUpdateCallback as root layer of window.
Now let we add some API that user can set specific view for given FrameUpdateCallback will use.
This API will be used when we want to optimize callback behaviour.

[NUI] Make AddFrameUpdateCallback with root view

---

src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs

1. Public RemoveBinding and ClearBinding  api
2. Add PropertyChanging invoke for SetValue.
- ACR: None

[NUI] Public RemoveBinding and ClearBinding api

---

src/Tizen.NUI/src/internal/Interop/Interop.LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Implement Flush action. It will be used when user
want to ensure the Lottie property changed applied sequencly.
relative dali patches:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/296160
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/296510

[NUI] Flush action implement for LottieAnimationView

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs

Since View constructor automatically change 'PositionUsesPivotPoint' value as false, some logic might changed when we Register ModelNode newly.

[NUI.Scene3D] Bug fix when we get ModelNode from Model

---

src/Tizen.NUI/src/internal/Common/Disposable.cs
src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
src/Tizen.NUI/src/public/Animation/Animatable.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/Common/BaseHandle.cs
src/Tizen.NUI/src/public/Common/Container.cs

Since C# initialize static values when that namespace / class access first time, We need to access some static values at static Preload() timing.

[NUI] Preload some static values

---

src/Tizen.Multimedia.Remoting/MediaController/MediaControlCommand.cs

Fix CustomCommand crash issue and Add NeedToResponse API(internal)

[MediaController] Fix CustomCommand crash issue

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest.cs
test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Window/TSWindow.cs

Supports set/get full screen window.
The full screen window means the window's size is same of full screen size.
The related DALi's patches are the belows.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/300078/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/300079/
Recently, Taskbar application was added to platform applications.
The Taskbar application is always floating on the home application. The application's window is the highest of the other window.
If the Taskbar application works, the other application window should be resized excepted Taskbar window's size.
The other requirement, some application want their windows are resized with full screen although Taskbar works.
To do that, the window uses full screen option.
The guide is …

[NUI] Supports set/get full screen window

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs

Since View constructor automatically change 'PositionUsesPivotPoint' value as false, some logic might changed when we Register ModelNode newly.

[NUI.Scene3D][API10] Bug fix when we get ModelNode from Model

---

src/Tizen.NUI.Components/Controls/Control.cs

We implement View.Preload() API now. So compiler can feel dizzy which one is Control.Preload() should do.
To avoid this compilation warning, let we add 'new' keyword for it.

[NUI.Components] Remove build warning for Control.Preload()

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/TSView.cs

Let we remove useless error message + Make getter return valid setting value for View.TooltipText property.

[NUI] Make View.TooltipText return valid value

---

src/Tizen.NUI/src/public/Accessibility/Accessibility.cs

Let us minimize the .net core dependency

[NUI] Change Accessibility.cs not to use net6.0 dependency function

---

src/Tizen.NUI/src/internal/Interop/Interop.WidgetView.cs
src/Tizen.NUI/src/public/Widget/WidgetView.cs

WidgetView keep widget instance's size and don't resize even if WidgetView is resized.
- ACR:

[NUI] Add KeepWidgetSize for control widget's size

---

src/Tizen.NUI/src/internal/Common/NativeImageInterface.cs
src/Tizen.NUI/src/internal/Interop/Interop.NativeImageInterface.cs
src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
src/Tizen.NUI/src/public/Images/NativeImageQueue.cs
src/Tizen.NUI/src/public/Images/NativeImageSource.cs

Previously NativeImageQueue.GenerateUrl() binded to invalid csharp API.
It will make some crash. So let we use valid bind API instead.
Required dali patches:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/300505
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/300513

[NUI] Make NativeImageQueue generate valid url

---

src/Tizen.NUI.Components/Controls/ScrollableBase.cs
src/Tizen.NUI/src/public/Common/Container.cs
test/NUITizenGallery/Examples/PerformanceTest/PerformanceTest1Page.xaml.cs

Due to some app's implements, ContentView can be disposed before ScrollBase itself disposed. In this case, ContentView is not null.
So, when we try to call RemovePropertyNotification, it become crashed.
To avoid these cases, let we make DisposeRecursively API makes more safety.
And also, fix some crash issue in PerformanceTest1Page.xaml.cs what can be problem in future.

[NUI] Resolve DisposeRecursively crashed when we dispose scrollbase

---

src/Tizen.NUI/src/internal/Common/Registry.cs

Until resolve all kind of apps fix wrong behavior, let we just print error without exception.

[NUI] Temperary revert exception throw at Registry.

---

src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs

The application may crash if the View is disposed but the Accessibility infrastructure calls one of the View methods. Detaching the NUIViewAccessible proxy object in View.Dispose() should prevent that.
Dependency: https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/300277/
- ACR: None

[NUI][AT-SPI] Detach NUIViewAccessible in View.Dispose()

---

src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs

The application may crash if the View is disposed but the Accessibility infrastructure calls one of the View methods. Detaching the NUIViewAccessible proxy object in View.Dispose() should prevent that.
Dependency: https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/300567/
- ACR: None

[API10][NUI][AT-SPI] Detach NUIViewAccessible in View.Dispose()

---

src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs

The application may crash if the View is disposed but the Accessibility infrastructure calls one of the View methods. Detaching the NUIViewAccessible proxy object in View.Dispose() should prevent that.
Dependency: https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/300568/
- ACR: None

[API11][NUI][AT-SPI] Detach NUIViewAccessible in View.Dispose()

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

void Dispose(bool) can be called from worker thread, when disposing value is false.
To ensure we detach AccessibileObject in main thread, let we remove it at Dispose(DisposeTypes), instead of Dispose(bool)

[NUI] Make DaliAccessibilityDetachAccessibleObject called at main thread

---

packaging/csapi-tizenfx.spec
packaging/csapi-tizenfx.spec.in

Guided by Appfw, vconf daemon does not run at mic stage. So, ```vconf_get_*``` api does not work normally. Therefore, it provides a second chance to read the file when ```vconf_get_*``` is null. So, Create vconf related to .NET as a file in RO location.

[Build] Create vconf related to .NET as a file in RO location

---

packaging/csapi-tizenfx.spec
packaging/csapi-tizenfx.spec.in
packaging/makespec.sh

The name of the ```dotnet_resolving.info``` file is changed. And the vconf creation of runtime_version is incorrect.

[Build] Modify build error for vconf of runtime_version

---

packaging/csapi-tizenfx.spec
packaging/csapi-tizenfx.spec.in

The ```dotnet_resolving.info``` file was not found in the post script.
```
16:24:32,854 INFO  - /bin/touch: cannot touch `/home/abuild/rpmbuild/BUILDROOT/csapi-tizenfx-10.0.0.17777+nui22146-1.aarch64/usr/share/dotnet.tizen/lib/dotnet_resolving.info': No such file or directory
16:24:32,856 INFO  - /var/tmp/rpm-tmp.c7su3V: line 7: /home/abuild/rpmbuild/BUILDROOT/csapi-tizenfx-10.0.0.17777+nui22146-1.aarch64/usr/share/dotnet.tizen/lib/dotnet_resolving.info: No such file or directory
16:24:32,858 INFO  - /var/tmp/rpm-tmp.c7su3V: line 8: /home/abuild/rpmbuild/BUILDROOT/csapi-tizenfx-10.0.0.17777+nui22146-1.aarch64/usr/share/dotnet.tizen/lib/dotnet_resolving.info: No such file or directory
16:24:32,860 INFO  - /var/tmp/rpm-tmp.c7su3V: line 9: …
```

[Build] Fixed an error that could not find the dotnet_resolving.info file

---

src/Tizen.NUI.WindowSystem/src/public/KVMService.cs
src/Tizen.NUI/src/public/Clipboard/ClipboardEvent.cs
test/NUIClipboardDataSelected/ClipboardDataSelected.cs
test/NUIWindowKVMSample/NUIWindowKVMSample.cs

Add new requests for SetSecondarySelection and UnsetSecondarySelection to alternates requests SetSecondarySelction and UnsetSecondarySelction that have typo.
After all caller that typo requests have been removed, the typo request have been removed.
Added:
- void SetSecondarySelection()
- void UnsetSecondarySelection()

[NUI.WindowSystem] Add SetSecondarySelection and UnsetSecondarySelection to fix typo

---

src/Tizen.NUI/src/internal/Common/Registry.cs
src/Tizen.NUI/src/public/Common/BaseHandle.cs

If BaseHandle doesn't have body, the refCPtr value is IntPtr.Zero.
If than, the various cases have wrong registration in future.
To avoid this case, let we ignore to register to registry, and make BaseHandle.registerMe value as false.

[NUI] Do not register when BaseHandle doesn't have body

---

src/Tizen.NUI/src/internal/Common/KeyInputFocusManager.cs
src/Tizen.NUI/src/internal/Common/LinearConstrainer.cs
src/Tizen.NUI/src/internal/Common/ObjectRegistry.cs
src/Tizen.NUI/src/internal/Common/PathConstrainer.cs
src/Tizen.NUI/src/internal/Common/RenderTaskList.cs
src/Tizen.NUI/src/internal/Utility/Builder.cs
src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
src/Tizen.NUI/src/public/Common/PropertyCondition.cs
src/Tizen.NUI/src/public/Common/PropertyNotification.cs
src/Tizen.NUI/src/public/Common/StyleManager.cs
src/Tizen.NUI/src/public/Common/TypeInfo.cs
src/Tizen.NUI/src/public/Common/TypeRegistry.cs
src/Tizen.NUI/src/public/Events/Hover.cs
src/Tizen.NUI/src/public/Events/Touch.cs
src/Tizen.NUI/src/public/Images/EncodedImageBuffer.cs
src/Tizen.NUI/src/public/Images/PixelBuffer.cs
src/Tizen.NUI/src/public/Input/AutofillContainer.cs
src/Tizen.NUI/src/public/Utility/FontClient.cs
src/Tizen.NUI/src/public/Utility/TTSPlayer.cs
src/Tizen.NUI/src/public/Utility/Timer.cs
src/Tizen.NUI/src/public/Visuals/VisualBase.cs
src/Tizen.NUI/src/public/Visuals/VisualFactory.cs
src/Tizen.NUI/src/public/Widget/WidgetView.cs
src/Tizen.NUI/src/public/Window/Window.cs

- Ensure to get 'already registered, or create new one' what we get item from DALi engine
- Let we also ensure create only one items if we use static ::Get() API
- Do not register to Registry if we copy the reference.
- Remove some useless copy constructor.
- Do not register to Registry if we create empty object.

[NUI] Resolve many problems relative with BaseHandle

---

src/Tizen.NUI/src/public/Accessibility/Accessibility.cs

Since we try to resolve some unusual behavior of BaseHandle, the dummyHandle in Accessibility can give us some confuse logs.
Actually, we don't need to hold it as BaseHandle type. we only need this as object type. So, let we make it as object, instead of BaseHandle.

[NUI] Remove basehandle usage at Accessibility static

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

void Dispose(bool) can be called from worker thread, when disposing value is false.
To ensure we detach AccessibileObject in main thread, let we remove it at Dispose(DisposeTypes), instead of Dispose(bool).
To avoid this kind of error in future, let we remove View.Dispose(bool) and let we only use Dispose(DisposeTypes).
Follow : #5674

[NUI][API10] Make DaliAccessibilityDetachAccessibleObject called at main thread

---

packaging/csapi-tizenfx.spec
packaging/csapi-tizenfx.spec.in

Create a dotnet library dir from the post script
```
17:15:40,648 INFO  - /bin/touch: cannot touch `/usr/share/dotnet.tizen/lib/dotnet_resolving.info': No such file or directory
17:15:40,650 INFO  - /var/tmp/rpm-tmp.34KWLT: line 7: /usr/share/dotnet.tizen/lib/dotnet_resolving.info: No such file or directory
17:15:40,652 INFO  - /var/tmp/rpm-tmp.34KWLT: line 8: /usr/share/dotnet.tizen/lib/dotnet_resolving.info: No such file or directory
17:15:40,654 INFO  - /var/tmp/rpm-tmp.34KWLT: line 9: /usr/share/dotnet.tizen/lib/dotnet_resolving.info: No such file or directory
17:15:40,656 INFO  - warning: %post(csapi-tizenfx-10.0.0.17778+nui22146-1.noarch) scriptlet failed, exit status 1
17:15:40,657 INFO  - WARNING: (csapi-tizenfx-10.0.0.17778+nui22146-1.noarch.rpm) Post script failed
```

[Build] Create a dotnet library dir from the post script

---

packaging/csapi-tizenfx.spec
packaging/csapi-tizenfx.spec.in

Set the dotnet_core_runtime_version value to 6.0. The dotnet_core_runtime_version value will be removed from tizenfx. Also, the script that creates the TFM list will be modified.

[Build] Set the dotnet_core_runtime_version value to 6.0

---

src/Tizen.System/Device/DeviceEventArgs.cs
src/Tizen.System/Device/Power.cs
src/Tizen.System/Interop/Interop.Device.cs

Allows using native power internal APIs.
These are newly added to System/Device/Power
- public static void ConfirmWaitCallback(UInt64 wait_callback_id) -> It informs the deviced that it is okay to take actual action to change state.
- public static void CancelWaitCallback(UInt64 wait_callback_id) -> It informs the deviced of that it needs to undo the current transition.
- public static int ChangeState(PowerState state, int timeout_sec) -> It Sends a request for changing power state asynchronously with timeout sec.
- public static int CheckRebootAllowed() -> It checks if reboot is possible on the current device state.
- public static PowerTransitionReason GetWakeupReason() -> It returns power wake up reason.
- public static PowerLockState GetLockState(PowerLock type) -> It returns the …

[System] Add power internal APIs

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

[NUI] revert 'Make DaliAccessibilityDetachAccessibleObject called at main thread' and check native object
- revert https://github.com/Samsung/TizenFX/pull/5674 and
- to fix crash from testhub, ATSPI's native object null check is required
- testhub crash bt =>
11-06 22:59:38.024+0900 F/NUI      (P23231, T23231): BaseHandle.cs: SwigCPtr(656) > SwigCPtr Error! NUI's native dali object is already disposed. OR the native dali object handle of NUI becomes null! 
11-06 22:59:38.024+0900 F/NUI      (P23231, T23231):  process:23231 thread:1, isDisposed:False, isDisposeQueued:True, me:Tizen.NUI.BaseComponents.VectorGraphics.CanvasView
11-06 22:59:38.024+0900 F/NUI      (P23231, T23231): BaseHandle.cs: SwigCPtr(660) > [ERROR] back trace!
11-06 22:59:38.027+0900 F/NUI      (P23231, T23231): …

[NUI] revert 'Make DaliAccessibilityDetachAccessibleObject called at main thread' and check native object

---

.github/workflows/deploy-packages.yml

- `gpr` tool uses nuget utilities which doesn't recognize net6.0 target framework.
- Use dotnet nuget push instead.

[Actions] Fix Deploy to push GitHub Packages

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

Let we allow to get the list of markers what current lottie image has now.
And also, Implement min/max frame index by marker, which is legacy feature of VD FLUX code.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/301038
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/301040
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-extension/+/301039

[NUI] Support to get Marker list information from lottie

---

src/Tizen.NUI.XamlBuild/src/internal/XamlBinding/Element.cs
src/Tizen.NUI/src/public/XamlBinding/Element.cs

Those API was useless if we don't need to invoke those events.
And those try to climb-up to parent root every Add / Remove API.
It will spend heavy time if the scene tree is complex.
Those event handerl are internal, and nobody use them.
So just remove codes.

[NUI.XamlBuild] Remove unused event : Element.DescendantAdded / Removed 

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Current LottieAnimationView implement their own ViewCreation logic.
For example, ImageView.ResourceUrl = ~~ didn't change synchronously option. But LottieAnimationView.ResourceUrl = ~~~ make synchronously option as true hardly.
So, there is no way to make asynchronously load lottie file.
To support it, let we cherry-pick new option of SynchronousLoading.

[NUI] Support LottieAnimationView file load asynchronously

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationTest.cs

There was some bug when we try to get TotalFrame when async load json file.
DALi engine side default total frame number is 0, and NUI is -1. So, if we try to get TotalFrame from dali which is still loading, it will cache the internal total frame as 0. After than, we can never get valid value.
To avoid this problem, we have 2 choice
1. Wait until async load finished, and then get total frame at dali side.
2. Just get 0 for now, and try again when total frame cached as 0.
Solution 1 need some time to resolve it. So now just make 2.

[NUI] Fix TotalFrame getter bug when async load

---

src/Tizen.System.Feedback/Feedback/Feedback.cs
src/Tizen.System.Feedback/Interop/Interop.Feedback.cs

As policies dealing with feedback themes have changed from index to id-base selection, API naming also changed from index to id.
Feedback themes are no longer treated sequentially, also not dependent on index. It is managed through a unique id.
- ACR:

[System.Feedback] Change feedback theme api name index to id

---

src/Tizen.System.Feedback/Feedback/Feedback.cs
src/Tizen.System.Feedback/Interop/Interop.Feedback.cs

Allows getting feedback theme id array supported.
This is newly added to System.Feedback.
- public uint[] GetThemeIdsInternal(FeedbackType type) -> It returns the available id array defined in the conf file according to feedback type.
- ACR:

[System.Feedback] Add internal API to support get ids

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

There was several problem when we call DaliAccessibilityDetachAccessibleObject at Dispose(bool) function
- It will detach accessibility even if view doesn't owned the handle memory
- Dispose(bool) can be called at worker thread (during GC) so we need to check thread here
I make to DaliAccessibilityDetachAccessibleObject function at Dispose(DisposeTypes) that we can ensure it called at main thread clearly.

[NUI] DetachAccessibleObject at Dispose time well

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Let we allow to call SetMinAndMaxFrameByMarker API even if load is not finished. Instead, let we just call some log if the file is not loaded yet.
Plus, Some API (GetContentInfo, GetMarkerInfo) might cache wrong values when we use async load
Before try to get correct value, let we check whether the resource is loaded or not.

[NUI] Change SetMinAndMaxFrameByMarker behavior + Fix some async cases

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

[NUI] Add AliveCount property to get currently living View number
- add only getter as hidden api
- consider the two cases of explicitly disposed case by user and implicitly case by GC.
none

[NUI] Add AliveCount property to get currently alived View number

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs

If ModelNode don't have ModelNod as child, it might have some null handle exception when we DownCast to ModelNode. (For example, user try to get child ModelNode, but failed.)
Currently, a lots of app don't consider ModelNode now. But in future we might need to add something under each ModelNode.
To make Scene3D more safety, let we check null or invalidate, and then get/set the value internally.

[NUI.Scene3D] Fix exception when ModelNode don't have ModelNode as child

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

LottieAnimationView cache both frame range as int, and marker. But two API set same property - PlayRange.
So if some code like below thing was not working well
```
// Let "marker" frame range is 10~20
lottieView.SetMinMaxFrame(30, 40); // play range become 30~40
lottieView.SetMinMaxFrameByMarker(marker); // play range become 10~20
lottieView.SetMinMaxFrame(30, 40); // play range need to be 30~40 again, but it didn't due to the cache.
```
To avoid like above case, let we clean cache explicit parameter.
Also, Let we add some more error check if app use invalid marker (Lottie file not loaded, or marker is invalid.)
In this case, let we just follow minMaxSetTypes.NotSetByUser logic then.

[NUI] Remove old frame range if we set marker + Minor fix up when marker invalid

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

This patch allows to set resolution of rendered result manually.
- ACR:

[NUI] Add SetResolution method to SceneView

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.MotionData.cs
src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionData.cs

This patch allow an option to use only root translation for motion capture data.
- ACR:

[NUI] Support RootTranslationOnly option for motion capture data

---

src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsData.cs

This patch fixes the bug which use wrong handle.
GetTensorsCount should use TensorsInfo handle instead of TensorsData handle.

[NoACR][MachineLearning.Inference] Fix bug using wrong handle

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs

* [NUI] Added collider mesh support
Model.SetColliderMesh() function allows creating and setting a collider mesh on the node of model.
Node of model is selected by name (string).
Collider mesh data consists:
List<Vector3> - list of vertices
List<int> - list of indices (3 indices are a triangle face)
* Modify issue
---------
- ACR:

[NUI] Added collider mesh support (#5782)

---

src/Tizen.Applications.PackageManager/Interop/Interop.Libraries.cs
src/Tizen.Applications.PackageManager/Interop/Interop.Package.cs
src/Tizen.Applications.PackageManager/Interop/Interop.PackageManagerInfoInternal.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/PackageCertificate.cs

Adjust lazy initialization on DependencyFrom, Certificate property. These properties need additional IPC platform internally, so make these property initialized lazily for performance.
- ACR: N/A

[Packagemanager] Fix Tizen.Applications.Package for performance

---

src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommandsGroup.cs

There is a portential problem with the code involving the variable 'e.OldItems'. This variable is the result of a method invocation, and the tool is warning that the method might return a null value, which can cause deferencing a null reference. It might cause to crash or behave unpredictably.
Therefore, to prevent this, the variable 'e.OldItems' should be checked if it is null or not before use.
- No ACR:

Fix defect that is detected by static analisys tool

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Common/DisposeQueue.cs
src/Tizen.NUI/src/internal/Common/ProcessorController.cs
src/Tizen.NUI/src/internal/Interop/Interop.ProcessorController.cs

Let we dispose IDisposable incrementally, not immediately.
It will reduce the main thread blocking during Dispose by GC.
To make the behavior didn't changed as before, let we make
FullGC as defalt. And turn on incremental GC feature if someone need.
Required dali patch : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/302439

[NUI] Dispose queue incrementally

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs

Previous code didn't assume that _resourceUrl value of ImageView was not a latest.
- If we set ImageView by ```Image``` property, the _resourceUrl was updated when cached map updating.
- When we try to get ResourceUrl gettor, we ask to cached map always.
But PropertyValue.Get(out string) might spend long time if the URL length is long. It will make useless string copy, what we can reduce.
Now We make every logic make ensure that _resourceUrl stored valid resource url. If this is validated, we can reduce some C# - Native networking.

[NUI] Make ensure ImageView._resourceUrl is latest

---

src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs

If we never set text into TextLabel before, the result of Text propert getter is always empty. To avoid useless C# - native network, let we just ignore text getter function if we can assume that previous text was empty.

[NUI] Skip text getter when Text never setted before

---

src/Tizen.NUI/src/internal/Common/DisposeQueue.cs
src/Tizen.NUI/src/internal/Common/ProcessorController.cs

If we don't call DisposeQueue.Instance.Initialize(), it might not flush the dispose queue.
Before #5806 and until currently, we didn't allow to call ProcessDisposables() before Initialize(). It might occure memory leak if app try to create & dispose unlimitly before Application start.
To make ensure it, let we make ProcessDisposables() API can be called even if DisposeQueue is not initialized.

[NUI] Make we flush DisposeQueue before app start

---

src/Tizen.NUI/src/internal/Common/DisposeQueue.cs
src/Tizen.NUI/src/internal/Common/ProcessorController.cs
src/Tizen.NUI/src/internal/Interop/Interop.ProcessorController.cs

To keep the backword stability, let we use previous API (CSharp_Dali_new_ProcessorController) call Initialize internally and new API (CSharp_Dali_new_ProcessorController_Without_Initialize) will not call this.
Since that #5806 change the logic of ProcessorController. So some library change the logical flow.
This patch make the logical flow keep same as previous if required.
required dali patch :  https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/302596

[NUI] Add API for ProcessController without Initialize

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

[NUI] DragAndDrop : Allow to get mimetype for Enter and Move events
- ACR:

[NUI] DragAndDrop : Allow to get mimetype for Enter and Move events

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Material.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/Material.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/MaterialDepthIndexRanges.cs

This PR is to add DepthIndex in Material.
The DepthIndex is compatible with Renderer::Property:DepthIndex and it is used to define rendering order in 3D scene.
- ACR:

[NUI] Add DepthIndex in Material

---

src/Tizen.NUI/src/internal/Common/DisposeQueue.cs

We add some logic to dispose items when application created & disposed before application initialized.
But some app just have some issue when some thread dependency items disposed before application started.
To avoid this cases, let we block dispose sync logic and revert we always dispose queue ensure in main thread.

[NUI] Revert dispose synchronously logic when APP is not started

---

src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
src/Tizen.NUI/src/public/Theme/DefaultThemeCommon.cs

Add AnchorColor, AnchorClickedColor Property 
AnchorColor(or AnchorClickedColor) property is
used as the default color of the markup anchor tag.
If there is a color attribute in the markup anchor tag, the markup attribute takes precedence.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/302984/ https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/302985/

[NUI] Add AnchorColor Property

---

src/Tizen.System.Feedback/Feedback/Feedback.cs
src/Tizen.System.Feedback/Interop/Interop.Feedback.cs

Allows sound feedback pattern playing with priority.
This is newly added to System.Feedback.
- public enum FeedbackFlag -> It determines the sound play method.
- public void PlayTypeWithFlagsInternal(FeedbackType type, String pattern, FeedbackFlag flag) -> It plays sound feedback pattern according to the FeedbackFlag value.
- ACR:

[System.Feedback] Add internal API to support sound playing with priority

---

src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs

1.Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
WID:25598476 Writing count elements of type System.IntPtr into buffer unmanagedPointer can exceed its size
SVACE Server Link : https://sa.sec.samsung.net/dm/tizen80/sb2/main/review#PRJID=14&WGID=87615
This may be caused by inconsistent texturesArray length and count.
- ACR: None

Fix svace issue of Marshal.Copy

---

src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs

Previously, PushWithTransition and PopWithTransition did not support Page. It supported either ContentPage or DialogPage.
Now, PushWithTransition and PopWithTransition supports Page as well.
- ACR:

[NUI] Fix Navigator to support Page with Transitions

---

src/Tizen.Multimedia.Remoting/MediaController/MediaControlCommand.cs
src/Tizen.Multimedia.Vision/MediaVision/DeepLearningFaceRecognizer.cs
src/Tizen.Multimedia.Vision/MediaVision/VisionFeatures.cs

Master -> DevelNUI integration 

---

src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationViewBindableProperty.cs
src/Tizen.NUI/src/public/Images/NativeImageQueue.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

Rebase API11 to DevelNUI

---

src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs

This patch solves the problem that text with padding does not work in nui layout.
For text components, the control's padding is used to calculatie size in native, so it should not be set to zero value.
This avoids setting padding to zero when it comes to text layout.
- ACR:

[NUI] Fix text padding issue

---

src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs

1.Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
WID:25598476 Writing count elements of type System.IntPtr into buffer unmanagedPointer can exceed its size
SVACE Server Link : https://sa.sec.samsung.net/dm/tizen80/sb2/main/review#PRJID=38&WGID=87615
This may be caused by inconsistent texturesArray length and count.
- ACR: None

[NUI] Fix svace issue of Marshal.Copy

---

src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
src/Tizen.NUI/src/public/Images/NativeImageQueue.cs

Let we allow to create NativeImageQueue with queue count. Previously, we only allow to create the NativeImageQueue based on the environment value "DALI_TBM_SURFACE_QUEUE_SIZE". (This value is 3 as default)
It will be useful if some user want to reduce the queue count for some cases, not for whole queue.
relative DALi patches :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/303523 https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/303524

[NUI] Support NativeImageQueue creation with queue count

---

src/Tizen.NUI/src/internal/Common/ProcessorController.cs

We have create ProcessorController constructor without initalize as default.
If NUI core want to change this policy, we can initialize at constructor time whenever we want.
But this case code has some error. It didn't create C# side objects and only create native side.
Let we make constructor with initialize works well now.

[NUI] Initialize C# items for ProcessorController if required

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs

Since we don't need to re-create the visual if we only chage the ImageColor property, let we use UpdateProperty Action.

[NUI] Do not recreate visual when we change ImageColor only

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.PropertyMap.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.PropertyValue.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.Vector.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/NDalicPINVOKE.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PropertyMapSample.cs

This PR adds a test code for [the new APIs](https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/303752/) added on Dali PropertyMap.
- some Interop code has brought to Sample to test dali APIs.
- Clicking Test button executes all TCs and it turns green when it's done successfully.
> Test for `CSharp_Dali_Property_Map_Insert_String__SWIG_0` is missing at the moment. This will be updated on the later PR.
button color which looked break on above actually changes to the flat green.

[NUI] Add test for new APIs on PropertyMap

---

src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FrameUpdateCallbackTest.cs

DALi's FrameUpdateCallback have interface whether we need to update scene or not. Previously, we always return it as false.
It might make some render / update timing issue when App is paused.
To make ensure whether we need to update scene or not, Let we override the new API that app can control the return value.
Relative dali patch : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/303947

[NUI] Allow to call FrameUpdate callback return value

---

src/Tizen.NUI/src/internal/Common/FrameBuffer.cs
src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Rendering/Renderer.cs
src/Tizen.NUI/src/public/Rendering/TextureSet.cs

Since now we have a unified pattern to avoid memory leak problem between NUI and Native side handle count problem,
Let we change some mis-implementated codes relative with Texture.

[NUI] Fix some incorrect implements when we get Texture relative items

---

src/Tizen.NUI/src/public/Common/BaseHandle.cs

Add some comments about BaseHandle behaviour.
Since NUI BaseHandle is totally depend on Dali side BaseHandle, We shoild notify ti NUI developer s.t. The mean of Dispose is not matched with usual case. So just add some remarks comment.

[NUI] Add some remarks at BaseHandle class about Dispose

---

src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

There were several problems when we call DaliAccessibilityDetachAccessibleObject at Dispose(bool) function
- It will detach accessibility even if view doesn't own the handle memory
- Dispose(bool) can be called at worker thread (during GC) so we need to check thread here
Make to `DaliAccessibilityDetachAccessibleObject` function at Dispose(DisposeTypes) so that we can ensure it called at main thread clearly.
- N/A

[NUI][API10] DetachAccessibleObject at Dispose time well

---

src/Tizen.NUI/src/public/Layouting/LinearLayout.cs

LinearLayout updates its child's MeasuredSizeWidth 0 correctly but it does not update its child's MeasuredSizeHeight 0 due to the range typo.
The range typo has been fixed so child's MeasuredSizeHeight 0 is also handled correctly.
- ACR:

[NUI] Fix LinearLayout to update its child's MeasuredSizeHeight 0 correctly

---

src/Tizen.NUI/src/internal/Common/ViewImpl.cs
src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs
src/Tizen.NUI/src/internal/Interop/Interop.ImageView.cs
src/Tizen.NUI/src/internal/Interop/Interop.StyleManager.cs
src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Common/StyleManager.cs

Since tizen 7.0, DALI StyleManager is disabled by default. But to support fhub properly, it's needed to provide a way to enable it.
* View/ImageView/Control are created with custom flag `DisableStyleChangeSignals` only when StyleManager is disabled (default)
* Text objects does not process font scale in NUI side when DALI StyleManager is enabled.
- ACR:

[NUI] Provide a way to enable legacy DALI StyleManager

---

src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
src/Tizen.NUI/src/public/Theme/ThemeManager.cs
src/Tizen.NUI/src/public/Xaml/MarkupExtensions/SharedResourcePathExtension.cs

* Add ThemeManager.AppendBaseTheme : It enables outer package to modify base theme
* Add SharedResourcePathExtension for xaml supporting
* Fix the bug that broken images in a theme always overwrite existing settings
* Fix the bug that cloning a view style losts SolidNull information.
- ACR:

[NUI] Add methods to modify base theme for fhub and fix bugs

---

src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs

Let we bind some more codes that UpdateProxy in dali side already supported.
relative dali patch :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/305266

[NUI] Support FrameUpdateCallback get world transform

---

src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs

이미 listen하고 있는 이벤트를 register하려는 경우 다시 event를 register할 필요가 없어 이를 제거한 패치입니다

[Packagemanager] Fix SetPackageManagerEventStatus

---

src/Tizen.Multimedia.Camera/Camera/Camera.cs
src/Tizen.Multimedia.Camera/Camera/CameraDeviceManager.cs
src/Tizen.Multimedia.Camera/Camera/CameraEnums.cs

Add Camera() constructor to select camera device automatically by CameraDeviceManager.
- TCSACR-572

[Camera] Add new Camera constructor for camera device internal selection

---

src/Tizen.NUI/src/internal/Layouting/LayoutController.cs

If you do not check this, all views on layers that do not have a layout set will be searched unnecessarily.
- ACR:

[NUI] Enable relayout only when layout is set for the layer.

---

src/Tizen.NUI/src/internal/Interop/Interop.Capture.cs
src/Tizen.NUI/src/public/Utility/Capture.cs

Add GenerateUrl in capture.
this api for using capture.
related patches:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/306064/ https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/306066/ https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/306067/
- ACR:

[NUI] Add GenerateUrl in Capture

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Since LottieAnimationView.URL property change whole Visual property by itself, CornerRadius / Borderline properties become ignored when we set URL.
```
lav = new LottieAnimationView();
lav.CornerRadius = new Vector4(100.0f, 100.0f, 100.0f, 100.0f);
lav.URL = "~~~.json"; ///< CornerRadius information ignored.
```
To avoid this case, let we ensure to set CornerRadius / Borderline if we set URL

[NUI] Fix error if LottieAnimationView set BackgroundData before set URL

---

src/Tizen.NUI.Wearable/src/public/Title.cs
src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
src/Tizen.NUI/src/public/Common/BaseHandle.cs
src/Tizen.NUI/src/public/Rendering/VertexBuffer.cs

Let we free allocated heap memory by Mashal.
It might cause memory leak issue if user try to use VertexBuffer.
And also, let we also fix FrameBrokerBase implementation that might be the guideline who want to use custom Geometry class.

[NUI] Call Mashal.FreeHGlobal() what we allocated

---

src/Tizen.NUI/src/public/Window/Window.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FrameUpdateCallbackTest.cs

Let we use some global view controllable frameUpdateCallback when user skip to add RootView information.
Previously, we detach the frameUpdateCallback automatically if rootView was disposed. But now, we will never remove callback until user call RemoveFrameUpdateCallback.
relative dali patch :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/305062
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/305126

[NUI] Allow to use null rootView for FrameUpdateCallback

---

src/Tizen.NUI/src/internal/Common/ViewImpl.cs
src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs

Since we don't need to control the ownership of native memory at callback side, let we just keep whole input value memory ownership as false.
relative dali patch :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/305409

[NUI] Make view-wrapper signal input as weak handle

---

src/Tizen.Multimedia.Util/ImageUtil/ImageEncoder.cs
src/Tizen.Multimedia.Util/ImageUtil/ImageUtil.cs
src/Tizen.Multimedia.Util/ImageUtil/ImageUtilEnums.cs
src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Encode.cs
src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Transform.cs
src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.cs

- Remove deprecated API (public static int CalculateBufferSize) 
- Change deprecated native APIs to new one
- TCSACR-579

[ImageUtil] Remove deprecated API

---

src/Tizen.NUI/src/public/CustomView/CustomViewRegistry.cs

[STATISTICAL] Value viewType.ToString(), which is result of method invocation with possible null return value, is dereferenced in method call constructorMap.Add()
- ACR:

[NUI][API11] Fix a SVACE issue.

---

src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs

[NUI] Add backendMode to the DirectRenderingGLView constructor.
refer code :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/306186/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/305990/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/306191/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-demo/+/305991/
- ACR:

[NUI] Add backendMode to the DirectRenderingGLView constructor.

---

src/Tizen.NUI/src/internal/Common/Disposable.cs
src/Tizen.NUI/src/internal/Common/WeakEvent.cs

* Checks that target object is explicitly disposed but not collected yet before invoke
* Consider list item removal/addition while traversing for invoke
* WeakHandler Equal method works well in static case
* Cleanup dead handlers not everytime
- ACR:

[NUI] Fix WeakEvent bugs

---

src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs

WID:36371588 Value source, which was created by as-operator, so can be null, is dereferenced in member access expression source.IncludeDefaultStyle
WID:36385014 Value source, which was dereferenced in member access expression source.SolidNull, is compared with null
- ACR:

[NUI] Fix SVACE issue of null in ViewStyle.

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs

- CastShadow can be used to make an object cast shadow or not.
- ReceiveShadow can be used to make an object be not drawn any shadow on its surface.
- Model and ModelNode have the methods.
- If Model's method is called, it is inherited to its current child ModelNode.
- If ModelNode's method is called, it is only affects the ModelNode itself.
- The ModelNode's property changes do not affect its parent Model's property.
dali-csharp-binder : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/307410/
dali-toolkit : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/307060/
- ACR:

[NUI.Scene3D] Add CastShadow and ReceiveShadow for Model and ModelNode

---

src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

Remove event from global static handler is heavy operation.
We can detach whether the view is disposed or not.
So just check disposed is more chip rather than remove event callback.

[NUI] Do not remove once event when ImageView is dispose

---

src/Tizen.NUI/src/public/Common/Container.cs

There was guard code when we traversal children list. There was some bugs when we traversal disposed item. But now, this bug is not happend.
To make the behavior match with comment, let we recursive the tree even if self is disposed.

[NUI] Make DisposeRecursively() full search of children list even if Disposed

---

src/Tizen.NUI/src/internal/Common/KeyInputFocusManager.cs
src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
src/Tizen.NUI/src/public/Clipboard/Clipboard.cs
src/Tizen.NUI/src/public/Common/StyleManager.cs
src/Tizen.NUI/src/public/Common/TypeRegistry.cs
src/Tizen.NUI/src/public/Input/FocusManager.cs
src/Tizen.NUI/src/public/Utility/FontClient.cs
src/Tizen.NUI/src/public/Utility/TTSPlayer.cs
src/Tizen.NUI/src/public/Visuals/VisualFactory.cs

There was 2 way to get sigletone class - `Get()` method and `Instance` proeprty.
After merge #5683 PR, some singletone class' `Get()` method register registry at that moment. If someone call `Instance` after `Get()` call, the singletone class become GC, due to unknown reason.
To avoid this cases, let we make `Get()` method also use `Instance` property internally, and deprecate that method.
For watch the trends after change the singletone pattern, let we just print error log if some NUI developer implement wrong way in future.

[NUI] Unified native singletone class instance getter

---

src/Tizen.NUI/src/internal/Common/Registry.cs

It is possible that DisposeQueued handle be used as input of GetManagedBaseHandleFromRefObject.
In this case, even if app hold that BaseHandle, it will be Disposed by DisposeQueue. If then the returned item become disposed, and it might breakdown app logics.

[NUI] Resolve the potential issue when DisposeQueued handle get

---

src/Tizen.NUI/src/internal/Common/FrameBuffer.cs
src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Rendering/Renderer.cs
src/Tizen.NUI/src/public/Rendering/TextureSet.cs

Since now we have a unified pattern to avoid memory leak problem between NUI and Native side handle count problem,
Let we change some mis-implementated codes relative with Texture.
Relative PR : #5892

[NUI][API10] Fix some incorrect implements when we get Texture relative items

---

src/Tizen.NUI.Wearable/src/public/Title.cs
src/Tizen.NUI/src/internal/Common/FrameBuffer.cs
src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Common/BaseHandle.cs
src/Tizen.NUI/src/public/Rendering/Renderer.cs
src/Tizen.NUI/src/public/Rendering/TextureSet.cs
src/Tizen.NUI/src/public/Rendering/VertexBuffer.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs

Let we backport some minor memory leak resolve PR what we already merged.
This PR squash 4 different patches.
---
Fix some incorrect implements when we get Texture relative items
Since now we have a unified pattern to avoid memory leak problem between NUI and Native side handle count problem,
Let we change some mis-implementated codes relative with Texture.
(Follow PR #5892)
Add some remarks at BaseHandle class about Dispose
(Follow PR #5893)
Resolve memory leak for DisposeTest sample
There was leak issue since we don't call FreeHGlobal after AllocHGlobal.
And also, let we Dispose Renderer / Geometry / Shader / TextureSet what NUI create. Those classes memory might give confuse when we test the memory.
(Follow PR #5895)
Call Mashal.FreeHGlobal() what we allocated
Let we free allocated …

[NUI][API11] Fix some memory leak codes what already fixed at API12

---

src/Tizen.NUI.Wearable/src/public/Title.cs
src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
src/Tizen.NUI/src/public/Common/BaseHandle.cs
src/Tizen.NUI/src/public/Rendering/VertexBuffer.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs

Let we backport some minor memory leak resolve PR what we already merged.
This PR squash 3 different patches.
---
Add some remarks at BaseHandle class about Dispose
(Follow PR #5893)
Resolve memory leak for DisposeTest sample
There was leak issue since we don't call FreeHGlobal after AllocHGlobal.
And also, let we Dispose Renderer / Geometry / Shader / TextureSet what NUI create. Those classes memory might give confuse when we test the memory.
(Follow PR #5895)
Call Mashal.FreeHGlobal() what we allocated
Let we free allocated heap memory by Mashal.
It might cause memory leak issue if user try to use VertexBuffer.
And also, let we also fix FrameBrokerBase implementation that might be the guideline who want to use custom Geometry class.
(Follow PR #5902)
- ACR:

[NUI][API10] Fix some memory leak codes what already fixed at API12

---

src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/IsUsingXamlTest.cs

[NUI] Add IsUsingXaml
- try to make NUI App's performance in memory and launching speed by separating property usage at runtime.
- tested in PontusM target.
- REMOVE_READONLY macro is for removing `readonly` keyword for BindableProperty instance creation. 
this is for testing how it can enhance the performance even if changing the interface. (Xaml APP need change codes)
- only changing the View's properties and even they are not whole, but only some.
- further code work will be done step by step.
nothing

[NUI] Add IsUsingXaml

---

src/Tizen.System.Storage/Storage/Storage.cs
src/Tizen.System.Storage/Storage/StorageManager.cs

In the previous implementation, no event handler was registered within class Storage when it was registered by storage type.
As a result of that, when the USB (or SD card) was removed, it attempted to obtain the state from outside and provided incorrect information to the application because there is no storage already removed.
It registers event handler within class Storage when event handler was registered by storage type.

[Tizen.System.Storage] Register eventhandler if it is already existed

---

src/Tizen.NUI.Components/Controls/Control.cs

[NUI] Fix manual TCT crash issue only on TV target
- fix the following exception on TV target
`01-01 09:07:09.036+0900 W/Tizen.System.Feedback(P 9174, T 9174): Feedback.cs: IsSupportedPattern(429) > Failed to get supported information. err = -38404095`
`01-01 09:07:09.682+0900 E/DOTNET_LAUNCHER(P 9174, T 9708): log.cc: stdErrRedirect(57) > Unhandled exception. `
`01-01 09:07:10.232+0900 E/DOTNET_LAUNCHER(P 9174, T 9708): log.cc: stdErrRedirect(57) > System.InvalidOperationException: Failed to get supported information`
`01-01 09:07:10.232+0900 E/DOTNET_LAUNCHER(P 9174, T 9708): log.cc: stdErrRedirect(57) >    at Tizen.System.Feedback.IsSupportedPattern(FeedbackType type, String pattern) in /home/abuild/rpmbuild/BUILD/csapi-tizenfx-12.0.0.18257+nui22316/src/Tizen.System.Feedback/Feedback/Fe …

[NUI] Fix manual TCT crash issue only on TV target

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Delegate rootCallback of LottieAnimationView is called by multi threads for lottie dynamic properties.
This causes the following issues.
- Delegate rootCallback of disposed LottieAnimationView can be referenced.
- Local variables in RootCallback is disposed by multi threads.
To resolve the above issues, the followings are done.
- Delegate rootCallback of LottieAnimationView is changed to be static.
- Local variables in RootCallback is not disposed.
- ACR:

[NUI] Fix LottieAnimationView not to reference disposed delegate

---

src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.KVMService.cs
src/Tizen.NUI.WindowSystem/src/public/KVMService.cs
test/NUIWindowKVMSample/NUIWindowKVMSample.cs

Backport GetSourceMimetypes of KVMService to API11
Added:
- List<string> GetSourceMimetypes(void)
- method to get mimetype list that current drag source offered.

[NUI.WindowSystem] Backport GetSourceMimetypes of KVMService to API11

---

src/Tizen.NUI/src/internal/Interop/Interop.Touch.cs
src/Tizen.NUI/src/public/Events/Touch.cs

[NUI] Add SetTime in Touch
refer:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/308797/ 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/308798/
- ACR:

[NUI] Add SetTime in Touch

---

src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs

1. Fix svace issue of buffer exceed size.
WID:42154964 Writing texturesArray.Length elements of type System.IntPtr into buffer unmanagedPointer can exceed its size.
- ACR: None

[NUI] Fix svace issue of buffer exceed size

---

src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs

1. Fix svace issue of buffer exceed size
WID:42154964 Writing texturesArray.Length elements of type System.IntPtr into buffer unmanagedPointer can exceed its size.
- ACR: None

Fix svace issue df240325-00447 240401

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs

In dali-toolkit, control-accessible's State::SENSITIVE has been modified from Actor::Property::SENSITIVE to IsHittable() && GetTouchRequired().
Unlike control-accessible, NUI View's custom Accessibility state of Sensitive still refers Actor::Property::SENSITIVE.
So NUI View with ViewAccessibilityMode.Default's Accessibility state of Sensitive refers IsHittable() && GetTouchRequired().
In contrast, NUI View with ViewAccessibilityMode.Custom's Accessibility state of Sensitive refers Actor::Property::SENSITIVE.
To make them have same Sensitive value, NUI View's custom Accessibility state of Sensitive is modified to use the value from control-accessible.
- ACR:

[NUI] Fix View to use control-accessible State::SENSITIVE

---

src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
src/Tizen.NUI/src/public/Common/Container.cs

This way both View and Layer can use this API.
Note: This is an API10 port of https://github.com/Samsung/TizenFX/pull/6028.
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/309098/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/309099/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/309102/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/widget-viewer-dali/+/309103/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/309100/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/309101/
- ACR: None

[API10][NUI][AT-SPI] Promote ReadingInfoTypes to Container 

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetResourceManager.cs

If getting the resource manager is failed, the NUIGadgeResourceManager tries to get the resource manager from the TwoLetterISOLanguageName of the CultureInfo.

[NUI.Gadget] Fix NUIGadgetResourceManager

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/public/Application/NUIWidgetApplication.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityProperties.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs

[NUI] Add IsUsingXaml flag in properties of View and AnimatedVectorImageView
- this kind of fix will be done for other classes also step by step
- this is for speed up the property usage performance for the APP that is not using bindable properties.
should be nothing

[NUI] Add IsUsingXaml flag in properties of View and AnimatedVectorImageView

---

src/Tizen.NUI/src/internal/Interop/Interop.Touch.cs

[NUI] Change the SetTime of Touch from ulong to uint.
- ACR:

[NUI] Change the SetTime of Touch from ulong to uint.

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityProperties.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs

[NUI] apply IsUsingXaml to View, ImageView, AnimatedVectorImageView and LottieAnimationView
- integration patch of the followings from DevelNUI
https://github.com/Samsung/TizenFX/commit/a81069615fb413c738e8febd3b3234a6ce806502
https://github.com/Samsung/TizenFX/commit/e115d2f8ba7961c0401d1dcc601ec95bd996a214
https://github.com/Samsung/TizenFX/commit/bcf0fae98d826249938e4456a20eabfe25a27505
- this is tesed with https://vdcosmos-hub.sec.samsung.net/build/22201326 in potusm tv.
nothing

[NUI] apply IsUsingXaml to View, ImageView, AnimatedVectorImageView and LottieAnimationView

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs

The mount path of the NUIGadget package is changed to the bin directory.
The NUIGadgetManager can use file name without the directory path.

[NUI.Gadget] Modify NUIGadgetManager Implementation

---

src/Tizen.NUI.Extension/Interop/Interop.RiveAnimationView.cs

Split rive-tizen binder from csharp-binder
Refer :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/309648/
- ACR:

[NUI.Extension] Use rive-tizen so file

---

src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs
src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Commons.cs
src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsData.cs
src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsInfo.cs
src/Tizen.MachineLearning.Train/Tizen.MachineLearning.Train/Model.cs

Backporting recent MachineLearning changes into API10 (tizen-7.0) by cherry-picking these two commits:
- https://github.com/Samsung/TizenFX/pull/5427/
- https://github.com/Samsung/TizenFX/pull/5800/

[NoACR][MachineLearning] Backporting recent changes for API10 (tizen-7.0)

---

src/Tizen.NUI.Components/Controls/AlertDialog.cs
src/Tizen.NUI.Components/Controls/Dialog.cs

Fixed AlertDialog's and Dialog's way of registering and unregistering default label
After this patch was added:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/284764/
The RegisterDefaultLabel() must be called after connecting the View to Window.
This pull request corrects this behaviour in AlertDialog component.
- ACR: none

[NUI][AT-SPI] Fixed Dialog and AlertDialog behaviour

---

src/Tizen.NUI.Components/Controls/AlertDialog.cs
src/Tizen.NUI.Components/Controls/Dialog.cs

Fixed AlertDialog's and Dialog's way of registering and unregistering default label
After this patch was added:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/308422/
The RegisterDefaultLabel() must be called after connecting the View to Window.
This pull request corrects this behaviour in AlertDialog component.
- ACR: none

[API11][NUI][AT-SPI] Fixed Dialog and AlertDialog behaviour

---

src/Tizen.NUI.Components/Controls/AlertDialog.cs
src/Tizen.NUI.Components/Controls/Dialog.cs

Fixed AlertDialog's and Dialog's way of registering and unregistering default label
After this patch was added:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/308327/
The RegisterDefaultLabel() must be called after connecting the View to Window.
This pull request corrects this behaviour in AlertDialog component.
- ACR: none

[API10][NUI][AT-SPI] Fixed AlertDialog behaviour

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs

[NUI] Fix the crash in ubuntu-backend
- View's BindableProperty creation should be prior to use the properties of the View and View's derived class. 
- checked the normal running in ubuntu-backend with tizen_8.0 and API11 code snapshot.
nothing

[NUI] Fix the crash in ubuntu-backend

---

src/Tizen.NUI/src/public/Window/BorderWindow.cs

1.  Fix svace issue for BorderWindow
* WID:49385020 [STATISTICAL] Value borderInterface.MinSize, which is result of method invocation with possible null return value, is dereferenced in member access expression borderInterface.MinSize.Width
* WID:49385028 [STATISTICAL] Value borderInterface.MinSize, which is result of method invocation with possible null return value, is dereferenced in member access expression borderInterface.MinSize.Height
- ACR: None

[NUI] Fix svace issue for BorderWindow

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs

Usually we load image load asynchronously as default.
(The only one except case is lottie.
But most of cases we don't need to consider
set BackgroundImage as Lottie file.)
So, for usual cases, we don't need to apply the informations whether we need to load image synchronously or not.
But previous implementation set `BackgroundImageSynchronousLoading` forcibly.
It might required `BackgroundImage` getter, what we don't need to know.
And also, it doesn't skip this getter/setter logic when the value is same as previous.
To avoid this useless visual creation, let we consider for backgroundImageSynchronousLoading property works well and works faster for usual cases, who don't set this property.

[NUI] Clean BackgroundImage setter logic

---

src/Tizen.NUI/src/internal/Interop/Interop.ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PlaceHolderImageTest.cs

This method allows users to configure the blending of two images(previous and currnet) using alpha values. \
if only the transition effect is set to true, the default values are used. 
however, if options are configured through this API, the effect can be applied with the values desired by the user.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/310863/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/310864/
- ACR:

[NUI] Add SetTransitionEffectOption for ImageView's transition effect

---

src/Tizen.NUI/src/internal/Common/RenderTask.cs
src/Tizen.NUI/src/internal/Interop/Interop.Animation.cs
src/Tizen.NUI/src/internal/Interop/Interop.RenderTask.cs
src/Tizen.NUI/src/public/Animation/Animation.cs

Let we bind the getter of Animation and RenderTask's ID integer.
Also, bind some more API that we added recently.
Required DALI patches :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/311349

[NUI] Add ID value of Animation + Bind more API for RenderTask

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs

The desired size of the image view will be calculated internally. Therefore, the NUI is no longer calculated the desired size for fitting mode.
related patches:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/307711/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/307712/
- ACR:

[NUI] Calculate desired size internally

---

src/Tizen.NUI/src/internal/Interop/Interop.InputMethodContext.cs
src/Tizen.NUI/src/public/Input/InputMethodContext.cs

Added `SetInputPanelPositionAlign` method and `InputPanelAlign` enum to `InputMethodContext`.
This API can be used to set the alignment of a floating IME.
```
public bool SetInputPanelPositionAlign(int x, int y, InputMethodContext.InputPanelAlign align)
```
nui related:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/312028/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/312029/
input method related:
https://quickbuild.tizen.org/build/509510

[NUI] Add align API to InputMethodContext

---

src/Tizen.NUI/src/internal/Common/Registry.cs

It is possible that dispose queued basehandle try to get / register again due to some reason. Like, Native side object is alived but C# side has no reference.
We already to to detect that cases. But if BaseHandle added at DisposeQueue, we cannot avoid to call the Dispose(); after some event loops later, and then Unregister the handle.
To avoid some error cases, let we Unregister the basehandle synchronously and then re-register base on the new BaseHandle.

[NUI] Unregister disposed / disposequeued BaseHandle and register again if need

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

Since DragEvent's GetPosition return new Vector2 class internally, we should keep the positoin with memory ownership.

[NUI][API11] Fix memory leak when DragAndDrop try to get Position

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

Since DragEvent's GetPosition return new Vector2 class internally, we should keep the positoin with memory ownership.

[NUI][API10] Fix memory leak when DragAndDrop try to get Position

---

src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

Since DragEvent's GetPosition return new Vector2 class internally, we should keep the positoin with memory ownership.

[NUI] Fix memory leak when DragAndDrop try to get Position

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs

Since `ControlHandle` could be deleted at GC thread, we should use DisposeQueue here.

[NUI][API10] Fix worker thread handle removal issue

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs

Since `ControlHandle` could be deleted at GC thread, we should use DisposeQueue here.

[NUI][API11] Fix worker thread handle removal issue

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs

Since `ControlHandle` could be deleted at GC thread, we should use DisposeQueue here.

[NUI] Fix worker thread handle removal issue

---

src/Tizen.NUI/src/internal/Utility/ItemViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Common/WeakEvent.cs
src/Tizen.NUI/src/public/Utility/AccumulatingVelocityTrackerStrategy.cs
src/Tizen.NUI/src/public/Utility/VelocityTracker.cs
src/Tizen.NUI/src/public/Utility/VelocityTrackerStrategy.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CanvasViewSample.cs

1. Remove XML parsing error
2. Let we use SafeHandle.Dispose(bool), instead of Dispose() API directly.
3. Add 'new' keyword what we re-define properties intention.
4. Remove unmatched property name with it's proeprty.

[NUI] Remove build warning

---

src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs

[NUI] Fix old value checking issue when IsUsingXaml = false
- when IsUsingXaml is false, the OldValue is not updated so it should not be checked and not be used.
nothing

[NUI] Fix old value checking issue when IsUsingXaml = false

---

src/Tizen.NUI/src/public/Animation/Animation.cs

Their was mis-removal at PR https://github.com/Samsung/TizenFX/pull/4764.
NUI_ANIMATION_PROPERTY_CHANGE_1 macro already works well for every cases.
Now we can always enable them.

[NUI] Remove unused macro

---

src/Tizen.NUI/src/internal/Interop/Interop.Capture.cs
src/Tizen.NUI/src/public/Utility/Capture.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CaptureTest.cs

This PR is to make Capture return ImageUrl.
The GetImageUrl API can be used to get ImageUrl of the captured image.
This API can be used as a replacement for the GetNativeImageSource,
when the app only want to draw the captured buffer by using imageView.
- ACR:

[NUI] Make Capture return ImageUrl

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Common/DisposeQueue.cs
src/Tizen.NUI/src/internal/Common/ProcessorController.cs

Let we don't get the instance of ProcessController at DisposeQueue.
Since DisposeQueue could be works at worker thread, or execute before NUIApplication initialized, we need to check whether ProcessController was initialized or not.

[NUI][API11] Make ProcessController.Initialized check as static + Initialize at Instance getter

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Common/DisposeQueue.cs
src/Tizen.NUI/src/internal/Common/ProcessorController.cs

Let we don't get the instance of ProcessController at DisposeQueue.
Since DisposeQueue could be works at worker thread, or execute before NUIApplication initialized, we need to check whether ProcessController was initialized or not.

[NUI] Make ProcessController.Initialized check as static + Initialize at Instance getter

---

src/Tizen.NUI/src/internal/Common/PropertyHelper.cs

Let we allow to convert PropertyValue by propertyValueConverter when we use AnimateBetween keyword by KeyFrames.
It will be useful when we animate some BackgroundColor or somethings with Integer value.

[NUI] Refine KeyFrames PropertyValues with propertyValueConverter

---

src/Tizen.NUI/Tizen.NUI.csproj
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PropertyTest.cs

[NUI] Avoid boxing,unboxing overhead
- https://learn.microsoft.com/ko-kr/dotnet/framework/performance/performance-tips#boxing-and-unboxing
- this will be done to all of "IsUsingXaml" changes
- remove REMOVE_READONLY_FOR_BINDABLE_PROPERTY macro by ABI break
nothing

[NUI] Avoid boxing,unboxing overhead

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs

Let we make ControlHandle call Dispose(true) always what we are using now.
And also, print some error log when this object GC by worker thread.
+ Write some comments for ControlHandle user.
It should be make more safety development

[NUI] Make ControlHandle dispose always

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Common/Layer.cs

This reverts commit 09f52bc8bdea3e4e50b610c0b6bc18b54104feb4.
This operation is moved to the DALi.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/314664/
- ACR:

Revert "[NUI] If the view had focus when it was unparented, the focus is cleared. (#4654)"

---

src/Tizen.NUI/src/internal/Common/ViewImpl.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs

- `CSharp_Dali_ViewImpl_AccessibilityActivate` was removed in 2018 lol However, at that time, NUI codes couldn't be removed together (Not sure)
- The reason `ViewImpl_AccessibilityActivate` was removed is 
`Remove functions which using internal apis.
Some binding functions use internal apis.
It caused error when dlopen csharp binder.`
- User can use Activated event with `View.AccessibilityActivated`
- N/A

[NUI] Remove the legacy AccessibilityActivate code

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Common/Layer.cs

This reverts commit 09f52bc8bdea3e4e50b610c0b6bc18b54104feb4.
This operation is moved to the DALi.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/314664/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/314958/
- ACR:

Revert "[NUI] If the view had focus when it was unparented, the focusis cleared. (#4654)"

---

src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/ColorVisual.cs
test/NUITizenGallery/Examples/ShadowFrameTest/ShadowFrameTest1Page.xaml
test/NUITizenGallery/Examples/ShadowFrameTest/ShadowFrameTest1Page.xaml.cs

Let we support to BoxShadow and ColorVisual, to ignore rendering inside of View area.
- None is default, same as previous logics.
- CutoutView is cutout render area as bounding box of view. It is faster than CutoutViewWithCornerRadius.
- CutoutWithCornerRadius is cutout render area consider the corner radius of view.
Since BoxShadow use ColorVisual internally and it doesn't consider View's property,
their might be some limitations.
Limitation:
- CutoutViewWithCornerRadius result not be matched if View use BorderlineOffset > -1.0f
- We don't support this property for xaml yet.
Required dali patch :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/314255
Sample result :

[NUI] Support Shadow and ColorVisual cutout policy

---

src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Commons.cs
src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsInfo.cs

This patch changes internal tensor size limit in MachineLearning.Inference.
Tizen Native ML api's max tensor size has been changed to 256.
See also : https://github.com/nnstreamer/nnstreamer/pull/4114, https://github.com/nnstreamer/api/pull/348

[NoACR][MachineLearning.Inference] Change internal tensor size limit

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

[NUI] Add GetLastPanGestureState
Use this when you want to know the status value of a pan gesture.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/315444/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/315445/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/315446/
- ACR:

[NUI] Add GetLastPanGestureState

---

test/Tizen.NUI.Scene3D.Sample/Scene3DSample.cs

Since some useless animation was running internally until GC comes, CPU usage might be increased for this sample.
To avoid useless rendering, let we ensurely dispose not-using animation.

[NUI.Scene3D.Sample] Remove useless looping animation

---

src/Tizen.NUI/src/internal/Interop/Interop.ActorSignal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/Common/AggregatedVisibilityChangedEventArgs.cs
src/Tizen.NUI/src/public/Common/Layer.cs

Add InheritedVisibilityChange Event to detect an Actor's actual visibility is changed or not.
The event is sent when visible property of this View, any of its parents (right up to the root layer), or Window changes.
- ACR:

[NUI] Add InheritedVisibilityChanged Event

---

src/Tizen.NUI/src/internal/Interop/Interop.Actor.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisibilityChangedTest.cs

Until now, VisibilityChangedEventArgs.View return sender itself.
It is useless information for user.
Follow up some other platform's behavior,
( reference : https://developer.android.com/reference/android/view/View#onVisibilityChanged(android.view.View,%20int) ) Let we make VisibilityChangedEventArgs.View return visibility changed view.
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/315475
- https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/315484

[NUI] Make VisibilityChangedEventArgs.View return visibility changed view

---

src/Tizen.NUI/src/internal/Common/VisualObjectsContainer.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/VisualBase.cs

Apply some comments that report at PR #6079
- `Color.A` getter apply `Opacity` changeness
- Make `VisualFittingMode` have no effect for `ColorVisual` and `BorderVisual`
- `GetVisualProperty` return valid value after call `GetCurrentVisualProperty`
- Make `VisualBase` class as abstract. Let we don't allow to call this class constructor.

[NUI] Apply comments at VisualBase (phase 1)

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/ImageVisual.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisualTest.cs

Add SynchrousSizing property - reload as size of visual.
It will be useful when we want to load image as specific size of view,
so the memory is reduced.

[NUI] Bind SynchronousSizing for ImageView / ImageVisual

---

src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextEvent.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelEvent.cs
src/Tizen.NUI/src/public/Common/NUIConstants.cs

* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/315160/
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/315140/
* https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/315818/
* Sync : default, synchronous text loading.
* AsyncAuto : automatically requests an asynchronous text load in OnRelayout.
* AsyncManual : users should manually request rendering using the async text method.
* All text rendering processes (update/layout/render) are performed asynchronously in AsyncAuto and AsyncManual.
* RequestAsyncRenderWithFixedSize : Requests asynchronous rendering of text with a fixed size.
* RequestAsyncRenderWithFixedWidth : Requests asynchronous text rendering with a fixed width.
The height is determined by the content of …

[NUI] Async text feature

---

src/Tizen.AIAvatar/src/Lipsync/LipSyncer.cs
src/Tizen.AIAvatar/src/Lipsync/VowelConverter/VowelConverter.cs

[NUI] Fix SVACE defects
- WID:5011810 [DELEGATE.STATISTICAL] Value lipKeyFrames, which is result of method invocation with possible null return value, is dereferenced in method call .Invoke()
- WID:5011820 [STATISTICAL] Value vowelClassifier, which is result of method invocation with possible null return value, is dereferenced in method call vowelClassifier.GetStepTime()
nothing

[NUI] Fix SVACE defects

---

test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSNativeImageQueue.cs

Let we use BGRA8888 format to keep legacy behavior.

[NUI.Devel.Tests] Do not use ColorFormat.RGBA, which might the behavor will be changed

---

src/Tizen.Multimedia/Common/Display.cs
src/Tizen.NUI.WindowSystem/Tizen.NUI.WindowSystem.sln
src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.EcoreWl2.cs
src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.KVMService.cs
src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.QuickPanelClient.cs
src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.QuickPanelService.cs
src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.SoftkeyClient.cs
src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.SoftkeyService.cs
src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.TaskbarService.cs
src/Tizen.NUI.WindowSystem/src/public/KVMService.cs
src/Tizen.NUI.WindowSystem/src/public/QuickPanelClient.cs
src/Tizen.NUI.WindowSystem/src/public/QuickPanelService.cs
src/Tizen.NUI.WindowSystem/src/public/SoftkeyClient.cs
src/Tizen.NUI.WindowSystem/src/public/SoftkeyService.cs
src/Tizen.NUI.WindowSystem/src/public/TaskbarService.cs
src/Tizen.NUI/src/public/Window/Window.cs
src/Tizen/Tizen.Common/IWindowProvider.cs
test/Tizen.NUI.WindowSystem.InputGenerator/Tizen.NUI.WindowSystem.InputGenerator.sln
test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.cs
test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.sln

[NUI] Add IWindowProvider to be used as a common window interface across different modules
- move Tizen.Multimedia.Common.IWindowProvider to Tizen.Common.IWindowProvider.
- The Window is used not only for Multimedia but also in other places (such as WindowSystem), so this change seems to be right.
- This will be review requested to Multimedia team and Window System team.
- ACR will be done and the link will be updated soon.
- The QuickPanel sample could not be tested because there is no mobile target for the tizen_9.0 version (e.g., no TM1, no FHUB).
https://jira.sec.samsung.net/browse/TCSACR-586

[TCSACR-586][NUI] Add IWindowProvider to be used as a common window interface across different modules

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

NUI should not dispose the return value of dynamic property callback.
- ACR:

[NUI] Fix lottie dynamic property crash

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

Add RelativeMotionGrab and RelativeMotionUnGrab
**[요청사항]**
1. MCF의 Gesture Connection을 지원하기 위해 (참고: https://confluence.sec.samsung.net/pages/viewpage.action?pageId=741952374)
아래와 같이 ecore_wl2 API를 추가하였습니다. NUI API로 지원 부탁드려도 될까요?
```
EAPI Eina_Bool ecore_wl2_window_relative_motion_grab(Ecore_Wl2_Window *win);
EAPI Eina_Bool ecore_wl2_window_relative_motion_ungrab(Ecore_Wl2_Window *win);
```
2. MC App의 요청사항으로 grab하고자 하는 edge를 argument로 추가하였습니다. 
NUI API로 지원 부탁드립니다.  
```
boundary enum: ECORE_WL2_POINTER_BOUNDARY_TOP/RIGHT/BOTTOM/LEFT
EAPI Eina_Bool ecore_wl2_window_relative_motion_grab(Ecore_Wl2_Window *win, Ecore_Wl2_Pointer_Boundary boundary);
EAPI Eina_Bool ecore_wl2_window_relative_motion_ungrab(Ecore_Wl2_Window *win);
```
**[구현내용]**
추가된 ecore api를 window에서 호출할 수 있도록 바인딩 합니다. …

[NUI] Add RelativeMotionGrab and RelativeMotionUnGrab

---

src/Tizen.NUI/src/internal/Interop/Interop.WebCertificate.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebCertificate.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Integrate the the applied modifications related to WebView from the previous version (API11) into the current version
- this should be merged with the dali patches below.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/316467
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/316468
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/316469
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-extension/+/316470
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-extension/+/316471
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/316472
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/316473
nothing

[NUI] Integrate the the applied modifications related to WebView from the previous version (API11) into the current version

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/CaptureFinishedEventArgs.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
src/Tizen.NUI/src/internal/Interop/Interop.ImageUrl.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/Scene3DCaptureTest.cs

This PR is to add capture to the Scene3D SceneView.
User can get a captured scene of SceneView with input Camera.
- ACR:

[NUI.Scene3D] Add capture to Scene3D.SceneView

---

src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FrameUpdateCallbackTest.cs

Let we allow to FrameUpdateCallback get and set Orientation.
Required dali patch : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/316498

[NUI] Binding FrameUpdateCallbackInterface change Orientation

---

src/Tizen.NUI/src/public/Window/Window.cs

[NUI] Add missing privilege comments
https://jira.sec.samsung.net/browse/TCSACR-596

[TCSACR-596][NUI] Add missing privilege comments

---

.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml

This PR is to update `deploy-documents` workflow using `tizendotnet/tizenfx-build-worker:2.5` to avoid docfx issues where some APIs are not filtered out.

Update deploy documents workflow

---

src/Tizen.NUI/src/internal/Common/EventThreadCallback.cs
src/Tizen.NUI/src/internal/Common/ProcessorController.cs
src/Tizen.NUI/src/internal/Interop/Interop.EventThreadCallback.cs
src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/internal/Interop/Interop.ProcessorController.cs
src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs

Since Disposable.ReleaseSwigCPtr doesn't do anything, we should implement it each class.
But FrameUpdateCallbackInterface didn't implemen it.
Relative dali patch : https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/317106

[NUI] Bind FrameUpdateCallback native release API

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebViewWebAuthDisplayQREventArgs.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Add WebAuthDisplayQR and Response for QR code passkey in WebView
should be merged with the following dali patches.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/317132
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/317133 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-extension/+/317134 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/317135 
nothing

[NUI] Add WebAuthDisplayQR and Response for QR code passkey in WebView

---

src/Tizen.NUI/src/internal/Interop/Interop.Property.cs
src/Tizen.NUI/src/public/Common/Property.cs
test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Common/TSProperty.cs

Since those usecase break some logic, let we decide to deprecate the componentewise logic.
Instead just create new property index - like COLOR_RED, SIZE_HEIGHT.
Relative dali patches (Not mandatory)
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/317090
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/317091
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/317087

[NUI] Deprecate Dali::Property constructor with componentwise

---

src/Tizen.NUI/src/internal/Interop/Interop.DragAndDrop.cs
src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
src/Tizen.NUI/src/public/DragAndDrop/DragEvent.cs
test/NUIDnDMultiWindow/NUIDnDMultiWindow.cs
test/NUIDnDSource/NUIDnDSource.cs

- Allow to set multi-mimetypes for source client (use DragInfo)
- Target client receive source's mimetypes from source client when Enter, Move, Leave
- Target client can set mimetype to receive
- Refactoring code for readability
**[dali-adaptor]**
- patch : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/316807/
**[dali-csharp-binder]**
- patch : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/316808/

[NUI] Add multi-mimetype feature for Drag and Drop

---

.github/workflows/build-pull-request.yml
.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml

Update deprecated actions for DevelNUI

Update deprecated actions for DevelNUI

---

src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs

[NUI] rebase master

---

src/Tizen.NUI/src/internal/Interop/Interop.VisualFactory.cs
src/Tizen.NUI/src/public/Visuals/VisualFactory.cs

shader precompile 시 원하는 옵션을 추가할 수 있는 기능입니다.
아래 패치들이 반영되어야 정상동작합니다.
1. Visual Factory Refactoring
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/315396/
2. Precompile option 추가 기능
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/316058/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/315273/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/316877/
https://github.com/Samsung/TizenFX/pull/6298
3. npatch shader 추가
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/316798/
4. CanclePrecompile 관련 버그 수정 패치
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/316966/
- ACR:

[NUI] AddPrecompileShader() for precompile shader

---

src/Tizen.System/Device/DeviceEventArgs.cs

Power related EventArgs classes were used at internal APIs in Power.cs module.
These classes and all properties(attributes) should be treated as internal API code.
Thus, this patch is necessary.
- ACR:

[System] Add handling code for internal APIs

---

src/Tizen.Core/Interop/Interop.TizenCore.cs

To release the native handle properly, the tizen_core_task_destroy() must be called.

[Core] Fix a bug about releasing the task

---

src/Tizen.Core/Tizen.Core/ChannelObject.cs
src/Tizen.Core/Tizen.Core/Event.cs
src/Tizen.Core/Tizen.Core/Task.cs

The received object in the callback function should not be released.

[Tizen.Core] Fix double free issues

---

src/Tizen.Core/Tizen.Core/ChannelObject.cs

The problem is that if the setter of ChannelObject's Data Property is called twice in a row, the previous data will not be removed. To prevent this, this patch is made it so that when the setter is called, the previous data is erased.

[Tizen.Core] Fix memory leak

---

src/Tizen.Core/Tizen.Core/Event.cs
src/Tizen.Core/Tizen.Core/Task.cs

The native handle should not be null before calling Dispose() method.

[Tizen.Core] Fix managing native handle of Event

---

src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
src/Tizen.NUI/src/public/BaseComponents/TextMapHelper.cs

Fixed a problem where the Offset and BlurRadius options of Outline did not exist in the member variable of Text.Outline Struct.

[NUI] Add Outline Offset and BlurRadius at struct Outline

---

src/Tizen.Core/Tizen.Core/Task.cs

The Run() & Quit() methods of Task do not throw InvalidOperationException.

[Core] Remove wrong descriptions

---

src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs

- DeleteCameraProperty has been used for the case that should use DeleteCamera.
- ACR:

[NUI.Scene3D] Fix miss used method in SceneView

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/ImageVisual.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisualTest.cs

Let we add property for change sampling mode when we change
desired size of given image.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-core/+/317969
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/317993
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/317992
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-demo/+/318001

[NUI] Support ImageView and ImageVisual the SamplingMode

---

src/Tizen.Core/Tizen.Core/ChannelReceiver.cs
src/Tizen.Core/Tizen.Core/ChannelSender.cs
src/Tizen.Core/Tizen.Core/Task.cs

This pull request modifies the descriptions and codes of methods as follows:
- The ChannelReceiver.Receive() can throw the InvalidOperationException. 
- The ChannelSender.Send() can throw ArgumentException and InvalidOperationException.
- The Task.Post(action) cannot throw ArgumentException.
- The Task.Post(action) can throw InvalidOperationException.
- The Task.AddChannelReceiver() can throw InvalidOperationException.
- The Task.AddEvent() can throw InvalidOperationException.
- The Task.EmitEvent() can throw InvalidOperationException.
- The Task.Run() can throw InvalidOperationException.
- The Task.Quit() can throw InvalidOperationException.

[Core] Modify exceptions

---

src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentInfo.cs
src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentManager.cs
src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentRunningContext.cs

[ComponentBased.ComponentManager] Enhance API descriptions

---

src/Tizen.System.MediaKey/Tizen.System/MediaKey.cs

[System.MediaKey] Enhance API descriptions

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs

The developers want to check whether the assembly is alive or not. This patch provides the NUIGadgetAssembly for inhouse developers.
- ACR: Non-ACR

[NUI.Gadget] Export NUIGadgetAssembly class for inhouse developers

---

src/Tizen.Log/Tizen/Log.cs

The descriptions of the classes and methods of Tizen.Log are updated for the 'summary' tag. Clarified summaries where appropriate and made sure they are 50+ characters in length.
- ACR:

Tizen.Log: update descriptions of log class/methods

---

src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/BaseComponent.cs
src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ComponentBasedApplication.cs
src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/FrameComponent.cs
src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ServiceComponent.cs
src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/WidgetComponent.cs

[Applications.ComponentBased] Enhance API descriptions

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Added an option to select the web engine type in the WebView constructor
- Previously, the web engine was fixed and selected for all DALi/NUI APPs in dali.sh, but now it can be chosen in the constructor.
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/318339/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/318340/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/318341/
nothing

[NUI] Added an option to select the web engine type in the WebView constructor

---

src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
src/Tizen.NUI/src/internal/Interop/Interop.NativeImageSource.cs
src/Tizen.NUI/src/public/Images/NativeImageQueue.cs
src/Tizen.NUI/src/public/Images/NativeImageSource.cs
src/Tizen.NUI/src/public/Images/TbmQueueImageSource.cs
src/Tizen.NUI/src/public/Images/TbmSurfaceImageSource.cs

Let we make some class that could create NativeImageSource / NativeImageQueue with raw-buffer-handle of tbm_surface_h / tbm_queue_h.
It will be used for some advanced tizen platform developer.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/318356

[NUI] Support Tbm dependency image source

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetLifecycleChangedEventArgs.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetResourceManager.cs

[NUI.Gadget] Enhance API descriptions

---

src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEnums.cs

Doxygen of Tizen.System.Settings has been updated.

Add doxygen for Tizen.System.SystemSettings

---

src/Tizen.NUI/src/internal/Interop/Interop.WebUserMediaPermissionRequest.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebUserMediaPermissionRequest.cs
src/Tizen.NUI/src/internal/WebView/WebViewUserMediaPermissionRequestEventArgs.cs
src/Tizen.NUI/src/internal/WebView/WebViewWebAuthDisplayQREventArgs.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Add WebAuthDisplayQR, Response and MediaPermission
- should be merged together =>
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/318391/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/318392/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-extension/+/318393/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/318394/
nothing

[NUI] Add WebAuthDisplayQR, Response and MediaPermission

---

src/Tizen.Applications.Notification/Interop/Interop.Notification.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/Notification.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationBinder.cs
src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationManager.cs

Add property and API for do not disturb all
internal api.
during the do not disturb app(dnd app) is running, notification viewer is not launched.
if the dnd app is terminated, notification viewer is launched.
if posted notification type is pairing type, request to terminate dnd app.
it's terminated launch notification viewer.

[Notification] Add PairingType for do not disturb app

---

src/Tizen.Applications.Notification/Tizen.Applications.Notifications/Notification.cs
src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationEventArgsBinder.cs

notification viewer is not launched properly when pairing type is set.
check the key to do not add extra data.

[Notification] fix notification when pairing type is set

---

src/Tizen.Multimedia.AudioIO/Interop/Interop.WavPlayer.cs
src/Tizen.Multimedia.AudioIO/WavPlayer/WavPlayer.cs

Add new internal API for play audio with repetitions

[AudioIO] Add new internal API for play audio with repetitions

---

src/Tizen.System.Feedback/Feedback/Feedback.cs
src/Tizen.System/Device/Battery.cs
src/Tizen.System/Device/Display.cs
src/Tizen.System/Device/Haptic.cs
src/Tizen.System/Device/IR.cs
src/Tizen.System/Device/Led.cs
src/Tizen.System/Device/PerformanceController.cs
src/Tizen.System/Device/Power.cs

Add more detailed API descriptions to the modules below.
- Tizen.System.Device
- Tizen.System.Feedback
- ACR:

[Tizen.System] Enhance API description

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/WebView/WebView.cs
test/Tizen.NUI.Scene3D.Sample/Scene3DSample.cs

Let we support CornerRadius and Borderline feature to SceneView.
Note that those features are available only if UseFramebuffer = true;
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/318377
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/318385

[NUI.Scene3D] Support SceneView CornerRadius and Borderline Property applied

---

src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiConfiguration.cs

https://jira.sec.samsung.net/browse/TNINE-4096

[Tizen.Network.WiFi] Fix heap-use-after-free issue on ASAN image

---

src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

Since protected level make runtime error for TV FLUX project, let we revert it as internal again.

[NUI] Revert ApplyCornerRadius access level as internal

---

src/Tizen.NUI/src/internal/WebView/WebContext.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Add remove WebContext callbacks when disposed
- fix the crash issue : A callback was made on a garbage collected delegate of type 'Tizen.NUI!Tizen.NUI.WebContext+WebContextHttpRequestInterceptedProxyCallback::Invoke'
none

[NUI] Add remove WebContext callbacks when disposed

---

src/Tizen.NUI/src/internal/Common/PropertyHelper.cs

Since dali_2.3.41, MixColor property animate by Vector4 type. But NUI animation property helper doesn't apply those changeness.
To match the previous behavior, let we make BackgroundColor and BoxShadow.Color animate by Color class well.

[NUI] Fix Animation issue for Background and BoxShadow color

---

src/Tizen.Security/Tizen.Security/Privilege.cs

Enhance documentation description according to guidelines.

[Tizen.Security] Enhancements of API description

---

src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn.csproj
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Authenticator.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorAssertionResponse.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorGetAssertionStorage.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorMakeCredentialStorage.cs
src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorStorage.cs

In certain situations it should be possible to make concurrent MakeCredential/GetAssertion calls. Therefore the authenticator being busy is no longer checked in the C# API. Instead, concurrent calls are unconditionally forwarded and it is now up to the native API whether it will honor the request or return an error.
Additionally, this pull request fixes an error in AuthenticatorAssertionResponse data marshalling.
- No public API changes

[WebAuthn] Enable concurrent Authenticator requests where supported by the native API

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs

Fix a typo error from resourced to resource.
- ACR: None

[NUI.Gadget] Fix a description typo

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs

Change visibility of the NUIGadgetInfo.Assembly to public
- ACR: N/A

[Tizen.NUI.Gadget] Change visibility of the NUIGadgetInfo.Assembly to public

---

src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs

1. Fix typo error (navtive -> native)
2. Vector2 is already nullable class. We don't need to make it as Vector2? type.

[NUI] Remove build warnings at DragAndDrop + TextConstants

---

src/Tizen.NUI/src/internal/Common/VersionCheck.cs
src/Tizen.NUI/src/internal/Interop/Interop.DragAndDrop.cs
src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
src/Tizen.NUI/src/internal/Interop/Interop.PropertyMap.cs
src/Tizen.NUI/src/internal/Interop/Interop.VisualFactory.cs
src/Tizen.NUI/src/internal/Utility/EnvironmentVariable.cs

Ensure some native binded API which bool return add MarshalAs(UnmanagedType.U1 ) keyword.

[NUI] Ensure UnmanagedType.U1 mark add for bool return type

---

src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
src/Tizen.NUI/src/internal/Interop/Interop.GestureDetector.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/Events/GestureDetector.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FeedGestureSample.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FeedNestedPanGestureSample.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FeedNestedPanGestureSampleVertical.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FeedTapAndLongPressGestureSample.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FeedTapAndPanGestureSample.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GeometryTouchEvent.cs

새로운 geometry touch/gesture event 전파 방식입니다.
SetGeometryHittestEnabled(true)를 하게 되면 새로운 이벤트 전파방식으로 동작합니다.
touch 이벤트는 geometry 기준으로 전파가 되며 gesture는 해당 터치 이벤트를 받아 인식하게 됩니다. 
그래서 터치이벤트를 받아 consume하게 되면 더이상 터치 이벤트가 전달되지 않아 하위의 뷰에서 제스처도 인식할 수 없습니다.
참고 페이지
https://confluence.sec.samsung.net/display/GFX/%5B2024+tizen%5D+New+Touch+and+Gesture
**hittest를 통해 hit되는 actor를 찾는 과정**
- 기존 방식 
-  Scene Tree의 Root에서 시작하여 Child에 대해 hittest를 진행합니다.
-  hit되는 actor에 대해 갱신해 나가면서 최종 마지막으로 hit된 actor를 찾습니다.
-  hit된 actor의 부모로 이벤트가 전파가 됩니다. 
-  InterceptTouchEvent도 hit된 actor의 부모에서만 가능합니다.
- 신규 방식
- Scene Tree의 Root에서 시작하여 Child에 대해 hittest를 진행합니다.
- hittest를 진행할 때 parent의 영역을 벗어나는 Child는 더이상 hit되지 못합니다.
- hit되는 actor들에 대해서 list에 저장합니다.
- 이렇게 작성된 list의 순서에 의해 InterceptTouchEvent 처리 및 이벤트를 전파합니다.
**Touch 이벤트가 전파되는 …

[NUI] Geometry Touch / Gesture Event

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs

The gadget mount path will be changed to the 'bin/.res_mount'. If it's applied, the NUIGadgetManager can remount the resources.

[NUI.Gadget] Use bin directory

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabelEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs

For now, let we just check for View, ImageView, TextLabel, TextField, TextEditor

[NUI] Block native callback if view is disposed or disposing

---

src/Tizen.System/Device/Battery.cs
src/Tizen.System/Interop/Interop.Device.cs

To support using device_battery_get_power_source(), this battery powersource property addition is necessary. Below enum and property are added.
- public enum BatteryPowerSource
-> It represents the battery power source charger type.
- BatteryPowerSource Battery.PowerSource { get; } // Property
-> It is possible to get the battery power source type as the BatteryPowerSource enum value.

[Tizen.System.Device] Add battery power source property

---

src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs

https://jira.sec.samsung.net/browse/TNINE-4885
- ACR:

[WiFi] Fix heap-buffer-use-after-free issue on ASAN

---

src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebSettings.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

csharp-binder patch:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/320722/
- ACR:

[NUI] Add APIs for setting IME position, cursor theme name.

---

src/Tizen.NUI/src/internal/Common/ViewImpl.cs
src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewWrapperImpl.cs

After PR #6419 merged, some director callback parameter not matched with dali-csharp-binder.
We also need to remove delegater 26, 28, and 29 at binder level.

[NUI] Match ViewImpl Connector parameter with csharp binder

---

src/Tizen.NUI/src/internal/Common/ViewImpl.cs
src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewWrapperImpl.cs

After PR #6419 merged, some director callback parameter not matched with dali-csharp-binder.
We also need to remove delegater 26, 28, and 29 at binder level.

[NUI][API12] Match ViewImpl Connector parameter with csharp binder

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs

`_assembly` must be reset to null after calling `Unload()`.
- ACR: N/A

[NUI.Gadget] Modify NUIGadgetAssembly unload logic

---

src/Tizen.NUI/src/public/Window/WindowEvent.cs

Block native callback if window is disposed or disposing
- ACR:

[NUI] Block native callback if window is disposed or disposing

---

src/Tizen.NUI/src/public/Input/InputMethodContext.cs

Block native callback if InputMethodContext is disposed
- ACR:

[NUI] Block native callback if InputMethodContext is disposed

---

src/Tizen.NUI/src/internal/Common/FriendAssembly.cs

An experimental external NUI library Tizen.NUI.OneUI has been introduced and it needs to access NUI internals.
- ACR:

[NUI] Add Tizen.NUI.OneUI as friend assembly

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

View provides methods to attach extra data (that is not bindable property) from the outside.
- ACR:

[NUI] Prepare extra space to View to attach objects from external

---

src/Tizen.NUI/src/public/Common/BaseHandle.cs
src/Tizen.NUI/src/public/Window/WindowEvent.cs

Ref : https://github.sec.samsung.net/NUI/OneUIComponents/issues/6
* Make Windows's native event callbacks not collected before native window is released.
* Add guard for window callbacks to check disposal.
- ACR:

[NUI] Make Window events safe while window is being collected

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

Ref : https://github.sec.samsung.net/NUI/OneUIComponents/issues/5
When a View becomes a target for GC and enters the dispose queue, the signal reference it had as a member may not be valid anymore.
```C#
void StartTest()
{
for (var i = 0; i < 1000; i++)
{
var view = new View();
view.AccessibilityGestureInfoReceived += (s, e) => {};
view.AccessibilityDescriptionRequested += (s, e) => {};
view.AccessibilityNameRequested += (s, e) => {};
view.AccessibilityReadingSkipped += (s, e) => {};
view.AccessibilityReadingPaused += (s, e) => {};
view.AccessibilityReadingResumed += (s, e) => {};
view.AccessibilityReadingCancelled += (s, e) => {};
view.AccessibilityReadingStopped += (s, e) => {};
}
Timer gctimer = new Timer(100);
gctimer.Tick += (s, e) =>
{
FullGC();
return false;
};
gctimer.Start();
} …
```

[NUI] Access managed fields only when explicit view disposal

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationViewDynamicPropertyTest.cs

Let us remove `DynamicProperty` callbacks if URL changes.
So far, we discard the callbacks if the visual was changed. But, the callbacks, which NUI stored, were not removed and remained alive whenever we changed the URL.
Let us ensure their removal when the URL changes (~= Visual Changed)
+
To avoid race conditions, let's add a lock feature before changing `InternalSavedDynamicPropertyCallbacks` (Since we can access this dictionary from various threads.)
TODO : There are some cases where we don't want to destroy registered callbacks. They will remain active in the future.
We make relative sample at `LottieAnimationViewDynamicPropertyTest.cs`. Let we pass `Test4` case show dynmaic property well.

[NUI] Remove DynamicProperty callback if URL changed + Make more thread safe enough

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationViewDynamicPropertyTest.cs

This PR is cherry-pick of #6504
Let us remove DynamicProperty callbacks if URL changes. So far, we discard the callbacks if visual was changed. But, the callbacks, which NUI stored, were not removed and remained alive whenever we changed the URL.
Let us ensure their removal when URL changed (~= Visual Changed)
+
To avoid race condition, let we add lock feature before change `InternalSavedDynamicPropertyCallbacks` (Since we can access this dictionary from various threads.) and make `weakReferencesOfLottie` as `ConcurrentDictionary` type.
Note : Since we need to iterate by `InternalSavedDynamicPropertyCallbacks.Keys` we need to use lock, instead of `ConcurrentDictionary`.
TODO : There are some cases where we don't want to destroy registered callbacks. They will remain active in the future. …

[NUI][API12] Remove DynamicProperty callback if URL changed + Make more thread safe enough

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationViewDynamicPropertyTest.cs

This PR is cherry-pick of #6504
Let us remove DynamicProperty callbacks if URL changes. So far, we discard the callbacks if visual was changed. But, the callbacks, which NUI stored, were not removed and remained alive whenever we changed the URL.
Let us ensure their removal when URL changed (~= Visual Changed)
+
To avoid race condition, let we add lock feature before change `InternalSavedDynamicPropertyCallbacks` (Since we can access this dictionary from various threads.) and make `weakReferencesOfLottie` as `ConcurrentDictionary` type.
Note : Since we need to iterate by `InternalSavedDynamicPropertyCallbacks.Keys` we need to use lock, instead of `ConcurrentDictionary`.
TODO : There are some cases where we don't want to destroy registered callbacks. They will remain active in the future. …

[NUI][API11] Remove DynamicProperty callback if URL changed + Make more thread safe enough

---

src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationViewDynamicPropertyTest.cs

This PR is cherry-pick of #6504
Let us remove DynamicProperty callbacks if URL changes. So far, we discard the callbacks if visual was changed. But, the callbacks, which NUI stored, were not removed and remained alive whenever we changed the URL.
Let us ensure their removal when URL changed (~= Visual Changed)
+
To avoid race condition, let we add lock feature before change `InternalSavedDynamicPropertyCallbacks` (Since we can access this dictionary from various threads.) and make `weakReferencesOfLottie` as `ConcurrentDictionary` type.
Note : Since we need to iterate by `InternalSavedDynamicPropertyCallbacks.Keys` we need to use lock, instead of `ConcurrentDictionary`.
TODO : There are some cases where we don't want to destroy registered callbacks. They will remain active in the future. …

[NUI][API10] Remove DynamicProperty callback if URL changed + Make more thread safe enough

---

src/Tizen.Applications.Common/Interop/Interop.RPCPort.cs
src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs

main -> DevelNUI

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs

- the exception occurring is replaced with an error log, because there is no guide for the application and because the application using this API will immediately crash if an exception occurs.
- https://github.sec.samsung.net/NUI/OneUIComponents/issues/7
nothing

[NUI] the exception occurring is replaced with an error log

---

src/Tizen.NUI/src/internal/Interop/Interop.PropertyValue.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/Common/PropertyValue.cs

Since NUI Vector2 / Vector3 / Vector4 are managed classes, create and dispose them might give overhead sightly.
If some memory/performance critical path don't want to create useless temperal Vector234 classes when we get/set PropertyValue, we need to support it.
Relative dali patch:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/316151

[NUI] Support PropertyValue set/get without create new Vector2/3/4

---

src/Tizen.NUI/src/internal/Interop/Interop.PropertyValue.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/Common/PropertyValue.cs

This is cherry-pick patch of #6513
Since NUI Vector2 / Vector3 / Vector4 are managed classes, create and dispose them might give overhead sightly.
If some memory/performance critical path don't want to create useless temperal Vector234 classes when we get/set PropertyValue, we need to support it.
Relative dali patch:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/316158

[NUI][API12] Support PropertyValue set/get without create new Vector2/3/4

---

src/Tizen.Network.WiFi/Interop/Interop.Libraries.cs
src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs

Implement API for getting MAC address of connect. This API implements C# api for CAPI _wifi_manager_tdls_get_connected_peer_
- ACR: NA
Its an internal API
- Added:
Property
static public string TDLSConnectedPeer
#6480
#6481

[Network.WiFi] Implement API to get MAC of TDLS connected peer

---

src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs

Adding View property that enables/disables offscreen rendering.
The view draws at offscreen buffer as itself a root node(subtree). The cached result may reduce repetitive render calls by occasion.
User can define the draw's refresh rate(RefreshAlways or RefrashOnce), or disable offscreen rendering(None).
The new property can be used as follows:
`View.OffScreenRendering = View.OffScreenRenderingType.RefreshOnce`

[NUI] Add View.OffScreenRendering property

---

src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Add WebView FeedMouseWheel as hidden api
- should be released with the following dali patches:
[Tizen] Add WebView FeedMouseWheel as hidden api
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/316591
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/316592
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-extension/+/316593
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/316594
- Add some logs in NUICoreBackend.Exit() by request from GBM
nothing

[NUI] Add WebView FeedMouseWheel as hidden api

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

NUI 외부 라이브러리에서 백그라운드를 토큰 형식으로 지원하기 위해 아래와 같은 기능을 추가했습니다.
<ins>설명</ins>
백그라운드를 토큰으로 지원하려면 백그라운드 변경에 대한 노티를 받을 수 있어야 함.
`View`는 bindable object를 상속하는 구조로 `PropertySet` 이벤트를 제공하고 있어 토큰 구현에 사용할 수 있음.
그런데 백그라운드는 서로 다른 프로퍼티간 상호 수정이 일어나는 구조임.
* BackgroundColor
* BackgroundImage
* Background
* ClearBackground()
이런 구조에서, 기존에 제공하던 `PropertySet` 이벤트는 아래의 이유로 사용하기 어려움이 있음
* BackgroundColor가 설정된 경우 BackgroundImage가 리셋되지만 BackgroundImage가 변경되었다는 노티를 받을 수 없음
* Clear의 경우엔 백그라운드 속성이 리셋됨에도 불구하고 변경 노티를 받을 수 없음
이를 해결하기 위해 `_background`라는 매직 키워드를 사용하여 백그라운드가 어떤 식으로든지 변경되었다는 노티 줄 수 있도록 조치하여 internal 구현에서 활용할 수 있게 함
- ACR:

[NUI] Notify background change with magic keyword

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FlushApplicationMessageSample.cs

Let we keep Idler callback list as membery of internal Application class, and allow to remove them during idler callback execute.
- We don't garentee that `Delegate` function emit time matched with `AddIdle` function call.
- We don't allow to add same `Delegate` function multiple times.  Until now, `Delegate` emitted as the number of `AddIdle` function call.

[NUI] Support RemoveIdle API for NUIApplication + Use unified idler callback

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FlushApplicationMessageSample.cs

Let we keep Idler callback list as membery of internal Application class, and allow to remove them during idler callback execute.
- We don't garentee that `Delegate` function emit time matched with `AddIdle` function call.
- We don't allow to add same `Delegate` function multiple times.  Until now, `Delegate` emitted as the number of `AddIdle` function call.

[NUI][API12] Support RemoveIdle API for NUIApplication + Use unified idler callback

---

src/Tizen.NUI/src/internal/Interop/Interop.WebDeviceList.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebDeviceList.cs
src/Tizen.NUI/src/internal/WebView/WebSettings.cs
src/Tizen.NUI/src/internal/WebView/WebViewDeviceConnectionChangedEventArgs.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Add WebView DeviceListGet,SetDefaultAudio
- added by GBM user's request
- dali patches
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/317009
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/317011
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-extension/+/317012
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/317013
nothing

[NUI] Add WebView DeviceListGet,SetDefaultAudio

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/ImageVisual.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/EncodedImageSample.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisualTest.cs

Since ImageUrl's reference should be hold on image visual, we should generate image visual synchronously, not on Processor time.
+
Minor code clean up applied
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/315535

[NUI] Create ImageVisual synchronously if AlphaMaskURL use generated ImageUrl

---

src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs

BindableObject does not create property dictionary for Xaml disabled case.
- ACR:

[NUI] BindableObject creates property dictionary on demand

---

src/Tizen.NUI/src/internal/NativeBinding/NDalic.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Common/Color.cs

* Do not convert Vector4 to Color when initializing static colors
* Eventually, static colors should be created by r, g, b values by c# code, not getting from DALi
* Preload static colors
- ACR:

[NUI] Optimize static field of Color class

---

src/Tizen.NUI/src/internal/Common/ControlStateUtility.cs
src/Tizen.NUI/src/public/BaseComponents/ControlState.cs

ControlState was implemented inefficently on the memory and the performance. This patch purposed to reduce inefficency by using bitflags on the state instead of string list. [https://github.sec.samsung.net/NUI/OneUIComponents/issues/15]
long type bitmask will be represent each states,
1 1 1 1 1
O S D P F
Normal   : 0L
Focused  : 1L
Pressed  : 2L
Disabled : 4L
Selected : 8L
Other    : 16L
and All  : 31L
This concept is based on VisualState of NUI2,
https://github.sec.samsung.net/dotnet/nui2/blob/main/src/Tizen.NUI2.Components/Base/ViewState.cs but we had to modified few states to keep backward compatibility of NUI ControlState.
- ACR:

[NUI] Refactoring ControlState to use bitmask

---

src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs

Add new parcel methods to support new types (u8, u16, u32, u64) in tidl

[Tizen.Applications.RPCPort] Add new methods to support new types in tidl

---

packaging/makerid.py

Before :
```
9.0.0:8.0.0:7.0.0:6.5.0:6.0.0:5.5.0:5.0.0:4.0.0:10.0.0
```
After :
```
10.0.0:9.0.0:8.0.0:7.0.0:6.5.0:6.0.0:5.5.0:5.0.0:4.0.0
```

[Build] Modified the RIDs sorted in descending order

---

src/Tizen.NUI/src/public/Visuals/VisualObject/ImageVisual.cs

Latest version use AlphaMaskUrl, instead of AlphaMaskURL.
Let we match the name of property so application don't be confused.

[NUI][API12] Match property name of ImageVisual.AlphaMaskUrl with latest version

---

src/Tizen.NUI/src/public/Visuals/VisualObject/VisualBase.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisualTest.cs

Since transform data is kind of renderer property internally, we don't need to re-create them.
Let we use UpdateProperty action for this case.
Required dali patch (merged) :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/316868/4/dali-toolkit/internal/visuals/visual-base-impl.cpp

[NUI] Do not re-create visual if we change only transform

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs

[NUI] Fix the issue where the AppControlReceived event handler is not being called
- GBM issue: DF250104-00684
- comments: 
1. OnAppControlReceived() 동작 검토 부탁드립니다. 
2. NUICoreBackend의 OnAppControl()까지 호출된걸로 봐서 저희 쪽 동작은 제대로 진행되었습니다. OnAppControlReceived()는 Backend의 OnAppControl()안에서 호출해주고 있습니다. NUIApplication안에서 AddEventHandler()를 호출하지 않으면 호출되지 않는 구조로 되어있는것으로 보입니다.
3. Hello, OnAppControl was called but OnAppControlReceived wasn't called,
could you please check?
[LN: 1110218] [04-01-2025 03.45.55.594]    18420.908 W/AMD     (P  602, T  602): launch_manager.cc: StartApp(42) > StartApp: appid=com.samsung.tv.mycontents caller_pid=1433 caller_uid=5001
[LN: 1110506] [04-01-2025 03.45.55.612]    18420.926 I/APP_CORE(P 2555, T 2555): appcore-ui-plugin.c: __raise_win(786) > …

[NUI] Fix the issue where the AppControlReceived event handler is not being called

---

test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Images/TSNativeImageSource.cs

- We MUST call ReleaseBuffer after call AcquireBuffer
- We MUST call AcquireBUffer before call ReleaseBuffer
If not, exception or deadlock will occured.

[NUI.Devel.Tests] Fix mis-implements for NativeImageSource TCT

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

- Fix AppControlReceived key duplicated error: DF250107-00093 =>
```
Exception !!! : [com.samsung.tv.csfs] [608] EXCEPTION [031mException !!!:System.ArgumentException: An item with the same key has already been added. Key: AppControlReceived
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) in System.Private.CoreLib.dll:token 0x6006ada+0x1a0
at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value) in System.Private.CoreLib.dll:token 0x6006acd+0x0
at Tizen.NUI.NUICoreBackend.AddEventHandler[TEventArgs](EventType evType, Action`1 handler) in Tizen.NUI.dll:token 0x6000102+0x0
at Tizen.Applications.CoreApplication.Run(String[] args) in Tizen.Applications.Common.dll:token 0x60000c4+0x59
at …
```

[NUI] Fix AppControlReceived key duplicated error

---

src/Tizen.NUI/src/devel/Lite/L.Color.cs
src/Tizen.NUI/src/devel/Lite/L.Shadow.cs
src/Tizen.NUI/src/devel/Lite/L.Vector2.cs

Introduce the value type of color, vector2 and shadow. They will replace existing reference types gradually.
- ACR:

[NUI] Add value type: color, vector2, shadow

---

src/Tizen.NUI/src/internal/Common/ControlStateUtility.cs
src/Tizen.NUI/src/public/BaseComponents/ControlState.cs

All State is not registered state,
but it is pre-defined FullMask state same as 0UL Normal.
- ACR:

[NUI] Fix exceptional All state case

---

src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

Fix WebView delegate GC error
- exception: 
```
E/DOTNET_LAUNCHER(32637): log.cc: stdErrRedirect(57) > Process terminated. A callback was made on a garbage collected delegate of type 'Tizen.NUI!Tizen.NUI.BaseComponents.WebView+internalWebViewDeviceListGetCallback::Invoke'.
E/DOTNET_LAUNCHER(32637): log.cc: stdErrRedirect(57) >    at Tizen.NUI.NDalicPINVOKE.ApplicationMainLoop(System.Runtime.InteropServices.HandleRef)
E/DOTNET_LAUNCHER(32637): log.cc: stdErrRedirect(57) >    at Tizen.NUI.Application.MainLoop()
E/DOTNET_LAUNCHER(32637): log.cc: stdErrRedirect(57) >    at Tizen.NUI.NUICoreBackend.Run(System.String[])
E/DOTNET_LAUNCHER(32637): log.cc: stdErrRedirect(57) >    at Tizen.Applications.CoreApplication.Run(System.String[])
E/DOTNET_LAUNCHER(32637): log.cc: stdErrRedirect(57) >    at …
```

[NUI] Fix WebView delegate GC error

---

src/Tizen.NUI/src/public/BaseComponents/ControlState.cs

[NUI] fix controlstate contains check null exceptions

---

src/Tizen.NUI/src/public/Common/PropertyValue.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/AnimatedImageVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/BorderVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/ColorVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/ImageVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/NPatchVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/TextVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/VisualBase.cs

Let we add 'using' mark for temperally used `PropertyValue`.
Optimize PropertyMap.Add() API if it is prepared
It is kind of next-step. So current PR could be keep going on.

[NUI] Reduce managed PropertyValue creation for VisualObject

---

src/Tizen.NUI/src/public/Common/NUIConstants.cs
src/Tizen.NUI/src/public/Common/Position.cs
src/Tizen.NUI/src/public/Common/Vector2.cs
src/Tizen.NUI/src/public/Common/Vector3.cs
src/Tizen.NUI/src/public/Common/Vector4.cs

It related with below issue.
https://github.sec.samsung.net/NUI/OneUIComponents/issues/20
No Changes

[NUI] Remove unnecessary PInvoke calls related with axis

---

src/Tizen.NUI/src/internal/Common/Object.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs

It needs to check exception when invoke native method.
- ACR:

[NUI] Check exception from native when get background color

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Common/NUIConstants.cs
src/Tizen.NUI/src/public/Common/Position.cs
src/Tizen.NUI/src/public/Common/Vector2.cs
src/Tizen.NUI/src/public/Common/Vector3.cs
src/Tizen.NUI/src/public/Common/Vector4.cs

Apply preload for static values
No Changes

[NUI] Preload static values

---

src/Tizen.NUI/src/devel/Base/DevelView.cs
src/Tizen.NUI/src/devel/Base/State.cs
src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

Introduce the value type of ControlState. It replaces ControlState implementation.
- ACR:

[NUI] Add value type: control state

---

src/Tizen.NUI/src/devel/Base/ViewState.cs
src/Tizen.NUI/src/public/BaseComponents/ControlState.cs

Since `State` already preseved as property name of `View` so the struct class should be renamed : `ViewState`
- ACR:

[NUI] Rename State to ViewState

---

src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
src/Tizen.NUI/src/public/BaseComponents/TableView.cs

Some of APIs are already deprecated but showed in API guilde.
This PR make the deprecated APIs to hidden.
The APIs are deprecated by follow items:
CustomView : https://jira.sec.samsung.net/browse/TCSACR-370, https://jira.sec.samsung.net/browse/TCSACR-402
FlexContainer : https://jira.sec.samsung.net/browse/TCSACR-324
ImageView : https://jira.sec.samsung.net/browse/TCSACR-464
Scrollable : https://jira.sec.samsung.net/browse/TCSACR-588, https://jira.sec.samsung.net/browse/TCSACR-397
TableView : https://jira.sec.samsung.net/browse/TCSACR-402
- ACR:

[NUI] Adds version tag or Hides deprecated APIs

---

src/Tizen.NUI/src/public/BaseComponents/ControlState.cs

Fix null reference error when calling `Equals` method for `ControlState`
- ACR:

[NUI] Handles null argument ControlState.Equals

---

src/Tizen.NUI/src/internal/Interop/Interop.VideoView.cs
src/Tizen.NUI/src/public/BaseComponents/VideoView.cs

If Underlay=false is set, the tbm buffer of the media packet is displayed on the screen as is.
So, if the video content is rotated, it is displayed on the screen as rotated.
1. Setting IsAutoRotationEnabled to true automatically rotates video content.
2. If you set IsLetterBoxEnabled to true, it will display the video content proportionally on the screen.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/317900
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/317901
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/317903
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-extension/+/317902
Added =>
(property) public bool IsAutoRotationEnabled
(property) public bool IsLetterBoxEnabled

[NUI] Add IsAutoRotationEnabled, IsLetterBoxEnabled

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs

* Mark up extensions are moved to Tizen.NUI.Extension project
* Namespace : `Tizen.NUI.Markup` -> `Tizen.NUI.Extension`
* Add BackgroundImage
- ACR:

[NUI] Move markup methods to Tizen.NUI.Extension

---

src/Tizen.NUI/src/devel/Common/DevelFrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FrameUpdateCallbackTest.cs

Let we allow to use FrameUpdateCallbackInterface could use UIVector2 and UIColor so we can reduce GC call at render thread.
Require dali patch :
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/318520

[NUI] Make FrameUpdateCallback could use UIVector2 and UIColor

---

src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
test/NUITizenGallery/Examples/GridTest/GridTest5.cs
test/NUITizenGallery/Examples/GridTest/GridTest5Page.xaml
test/NUITizenGallery/Examples/GridTest/GridTest5Page.xaml.cs

Previously, if a cell has multiple ColumnSpacing or RowSpacing with Stretch Expand, its column or row does not occupy Expand space if the column or row is empty.
e.g. Child2 begins the beginning of the GridLayout without preserving the empty space for Row 1, Column 0.
GridLayout Width 400.
Child1 Row 0, Column 0, ColumnSpan 2, HorizontalStretch Expand
Child2 Row 1, Column 1, ColumnSpan 1, HorizontalStretch None, Width 100
\-------------------------------------
|||||||||||||||Child1||||||||||||||||
\-------------------------------------
||Child2||                          |
\-------------------------------------
Now, it has been fixed to make the column or row occupy Expand space even though the column or row is empty.
To do so, virtual edges for the column or row have Stretch Expand. It …

[NUI] Fix GridLocations to preserve empty space for Stretch Expand

---

src/Tizen.NUI/src/internal/Common/ViewSignal.cs

- Reduce error log print.
- Limit trace call stack depth at 5, when the exception case of ViewSignal Disconnect by the request of GBM.
nothing

[NUI] Reduce error log by the request of user

---

src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/ViewProperty/LayoutExtraData.cs

If an application does not use Layout, then View's variables used for Layout waste memory.
To remove those wasted memory, those variables are moved to the new internal class LayoutExtraData and it is not allocated if Layout is not used.
- ACR:

[NUI] Extract View variables for Layout to remove wasted memory

---

src/Tizen.NUI/src/devel/Lite/UIColor.cs

Provide implicit conversion to `Color` from `UIColor` for users who want to use UIColor for Color type API.
- ACR:

[NUI] Provide implicit conversion to Color from UIColor

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs
src/Tizen.NUI/src/devel/Lite/UICorner.cs

`UICorner` includes a flag indicating whether the values are relative to its target box size.
- ACR:

[NUI] UICorner includes a relative flag

---

src/Tizen.NUI/src/internal/Common/RenderTask.cs
src/Tizen.NUI/src/internal/NativeBinding/NDalic.cs
src/Tizen.NUI/src/public/Events/PanGestureDetector.cs
src/Tizen.NUI/src/public/Utility/FontClient.cs

[Optimization] Remove redundant PInvoke call for NUI constants.

---

src/Tizen.NUI/src/public/Input/InputMethodContext.cs

This PR makes InputMethodContext's signal callbacks not collected before native InputMethodContext gone.
Unlike other classes, InputMethodContext's callbacks are not removed from the static dictionary until it is disposed.
Because eventReceivedEventCallback is called from unmanaged code although it is disconnected.
- ACR:

[NUI] Make InputMethodContext's signal callbacks not collected

---

src/Tizen.NUI/src/devel/Lite/UIExtents.cs

Fix build warning for UIExtents
- ACR:

[NUI] Fix build warning for UIExtents

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/ViewProperty/LayoutExtraData.cs

Minimum/Maximum Width/Height are added to View markup methods to be used by the layout to size the view within its parent layout container. Unlike existing Minimum/MaximumSize, the newly added markup methods provide float.
- ACR:

[NUI] Add Minimum/Maximum Width/Height to View markup methods

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/ViewProperty/LayoutExtraData.cs

Margin is added to View markup method to be used by the layout to size and position the view within its parent layout container. Padding is added to View markup method to be used by the layout to size and position the child views within the layout container.
- ACR:

[NUI] Add Margin and Padding to View markup methods

---

src/Tizen.NUI/src/internal/Interop/Interop.InputMethodContext.cs
src/Tizen.NUI/src/public/Input/InputMethodContext.cs

To support full screen mode of the input panal.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/318558
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/318559
```
/**
* @typedef Ecore_IMF_Input_Hints
* @brief Enumeration for defining the types of Ecore_IMF Input Hints.
* @since 1.12
*/
typedef enum
{
ECORE_IMF_INPUT_HINT_NONE                = 0,        /**< No active hints @since 1.12 */
ECORE_IMF_INPUT_HINT_AUTO_COMPLETE       = 1 << 0,   /**< Suggest word auto completion @since 1.12 */
ECORE_IMF_INPUT_HINT_SENSITIVE_DATA      = 1 << 1,   /**< Typed text should not be stored. @since 1.12 */
ECORE_IMF_INPUT_HINT_MULTILINE           = 1 << 2,   /**< Multiline text @since 1.18 */
+   ECORE_IMF_INPUT_HINT_FULLSCREEN_MODE     = 1 << 3,   /**< The …
```

[NUI] Add FullScreenMode to InputMethodContext

---

src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
src/Tizen.NUI/src/public/Layouting/GridLayout.cs
src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs

In some codes, dictionary variables' getter does not check if the key exists in the dictionary.
This causes an exception by accessing key's value which does not exist.
This PR resolves the above cases.
- ACR:

[NUI] Fix dictionary variables to support non UsingXaml case

---

src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs

[NUI] Fix a crash when applying ViewStyle.

---

src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs

Let we make view creation method that we can ignore DALi engine side Relayout feature.
It will be useful when we can assume that
- This view always be exist under Layout
- ResizePolicy don't need
- Relayout event not required
- Internal visuals, or VisualObjects don't use FittingMode.
- Text are not be used
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/319564

[NUI] Support to view constructor which we can ignore Relayout

---

src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

This patch is to fix failed TC in TCT.
- ACR: None

[NUI] Fix the issue that Style Property Getter does not work.

---

src/Tizen.NUI.Extension/Internal/ViewPropertySetters.cs
src/Tizen.NUI.Extension/Markup/ViewExtensions.cs
src/Tizen.NUI/src/devel/Common/IToken.cs
src/Tizen.NUI/src/devel/Common/ITokenTable.cs
src/Tizen.NUI/src/devel/Lite/UIColor.cs
src/Tizen.NUI/src/devel/Lite/UIExtents.cs
src/Tizen.NUI/src/devel/Lite/UIShadow.cs
src/Tizen.NUI/src/devel/Lite/UIVector3.cs
src/Tizen.NUI/src/internal/Common/EmptyResourceTable.cs
src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs
src/Tizen.NUI/src/public/Common/PropertyMap.cs
src/Tizen.NUI/src/public/ViewProperty/Shadow.cs

* Provide BoxShadow getter
* UIColor getter returns token value properly
* Color
* BackgroundColor
* BoxShadow
* BorderlineColor
* Size and Position receives UIVector3 instead of UIVector2
* Provide implicit convertion from UIVector2 to UIVector3
- ACR:

[NUI] Refine View extension methods

---

src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
src/Tizen.NUI/src/devel/Binding/BindingExtensions.cs
src/Tizen.NUI/src/devel/Binding/BindingProperty.cs
src/Tizen.NUI/src/devel/Binding/BindingSession.cs
src/Tizen.NUI/src/devel/Binding/TwoWayBindingProperty.cs
src/Tizen.NUI/src/devel/Binding/ViewBindings.cs
test/Tizen.NUI.StyleGuide/Tizen.NUI.StyleGuide.cs

The binding in NUI cause performance and memory issue, so we plan to deprecate them by setting IsUsingXaml disable.
This patch is aim to introduce new style of binding, which do not causing performance and memory seriously, and user can add binding property on existing view class, so that we do not need to add every property to bindable.
- ACR:

[NUI] Introduce new binding style.

---

src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs

It is possible that `Model.GenerateMotionAnimation` return null if input indecies are not exist in current model.
Until now, we just `Register` to Registry forcibly, and check `HasBody()` But in this case, `Tizen.Log.Error("NUI", $"We try to register BaseHandle dont have body! input type:{baseHandle.GetType()}\n");` will print error log, which might not be helpful to application user.
To avoid that useless error printing,
Let we check the Animation class's body first before register to Registry.

[NUI.Scene3D] Check HasBody before Register at GeneratedMotionAnimation

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs

The gadget resources will be mounted to 'bin/.res_mount/gadget'.

[NUI.Gadget] Modify resource path

---

src/Tizen.NUI/src/public/Application/WindowData.cs
src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Picture.cs
src/Tizen.NUI/src/public/Common/Rectangle.cs
src/Tizen.NUI/src/public/Common/Size2D.cs

[NUI] Fix memory leaks in Size2D & Rectangle.

---

src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityProperties.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs

[NUI] Remove boxing/unboxing in View.

---

src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs
src/Tizen.NUI/src/public/Layouting/GridLayout.cs
src/Tizen.NUI/src/public/Layouting/LayoutDimension.cs
src/Tizen.NUI/src/public/Layouting/LayoutLength.cs
src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
src/Tizen.NUI/src/public/ViewProperty/LayoutExtraData.cs

Since IsFixedValue and comparing operators are provided, LayoutDimensionMode is not necessary. So it is removed. Instead, const float WrapContent and MatchParent are added to be used for assigning or comparing WrapContent and MatchParent.
e.g. value assignment
LayoutDimension layoutWidth = LayoutDimension.MatchParent;
e.g. value comparison
if (layoutWidth == LayoutDimension.WrapContent)
- ACR:

[NUI] Remove LayoutDimensionMode from LayoutDimension

---

src/Tizen.NUI/src/internal/Common/SystemFontSizeChangedManager.cs
src/Tizen.NUI/src/internal/Common/SystemFontTypeChangedManager.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/Theme/DefaultThemeCommon.cs

Each text component's call to the system API takes a lot of time.
Especially for FontType, initialization of FontConfig occurs natively and consumes most of the time.
This patch updates through static classes only when a specific value is needed.
TODO: manager should handle all events.

[NUI] Minimize system settings API calls in Text

---

src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/Common/PropertyValue.cs
src/Tizen.NUI/src/public/Common/Size.cs

[NUI] Remove DALi instance from Size

---

src/Tizen.NUI/src/devel/Lite/UIRect.cs
src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
src/Tizen.NUI/src/public/Layouting/AbsoluteLayoutFlags.cs

[NUI] Add AbsoluteLayout APIs for LayoutBounds and LayoutFlags

---

src/Tizen.NUI/src/internal/Interop/Interop.Renderer.cs
src/Tizen.NUI/src/public/Rendering/Renderer.cs

Until now, geometry and shader was mendentory.
But if developper try to derive the class, this give some bad experience.
So let we allow to create renderer without geometry or shader.

[NUI](Rendering) Create Renderer constructor without Geometry and Shader

---

src/Tizen.NUI/src/devel/Binding/BindingExtensions.cs
src/Tizen.NUI/src/devel/Binding/BindingSession.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

1) Return value is not checked.
2) Null parameter is not checked.
- ACR:

[NUI] Fix some warnings in NUI.

---

src/Tizen.NUI/src/public/Animation/Animation.cs

This reverts commit c9cb5922a4eb67ea5b632ee3285256b9e66bd1ea.
OneUI have their own TypedAnimation so this animation is not neceesary.
- ACR:

Revert "[NUI] add asynchronous tasked animation play"

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GraphicsTypeTest.cs

`WidthSdpecification` --> `WidthSpecification`
`HeightSdpecification` --> `HeightSpecification`
`Disdpose()` --> `Dispose()`

[NUI.Samples] Fix compile error due to some typo error fix

---

src/Tizen.Network.WiFi/Tizen.Network.WiFi.csproj
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs

**Description of Change**
Remove thread local support in Tizen.Network.WiFi
**Reason of change:**
Until Tizen 5.0, wifi-manager handles were supported only as thread locals, so the WiFi C# API was implemented so.
However, starting from Tizen 6.0, wifi-manager was modified to remove this restriction, so there is no longer need to use Post().
So, this is being removed.
**API Changes**
ACR: None
**Related**
#6659

[Tizen.Network.WiFi] Remove thread local support 

---

src/Tizen.Network.WiFi/Tizen.Network.WiFi.csproj
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs

**Description of Change:**
Remove thread local support in Tizen.Network.WiFi
**Reason of change:**
Until Tizen 5.0, wifi-manager handles were supported only as thread locals, so the WiFi C# API was implemented so.
However, starting from Tizen 6.0, wifi-manager was modified to remove this restriction, so there is no longer need to use Post().
So, this is being removed.
**API Changes:**
ACR: None
**Related:**
#6659

[Tizen.Network.WiFi] Remove thread local support

---

src/Tizen.NUI/src/public/Layouting/LayoutLength.cs

LayoutLength is fixed not to take invalid float values such as non-finite values, float.MinValue, float.MaxValue. If user wants to use float.MinValue or float.MaxValue, then int.MinValue or int.MaxValue are suggested.
nothing

[NUI] Fix LayoutLength not to take invalid float values

---

src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs

Not to block GC of child views, Dictionary taking child views is removed from AbsoluteLayout.
nothing

[NUI] Fix AbsoluteLayout not to use Dictionary taking child views

---

src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/Layouting/LayoutItem.cs

Add a virtual method of `View` to get notified on derieve class when it's size and position changed by NUI layouting.
- ACR:

[NUI] Notify view size and position updated by layout.

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs

[NUI] Fix marpkup null type error

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

Previously, Padding of text objects such as TextLabel, TextField, TextEditor was not applied if Padding was set after those objects were added to Layout View.
e.g. The following did not work
var textLabel = new TextLabel();
absoluteLayoutView.Add(textLabel);
textLabel.Padding = padding;
Now, the above problem has been resolved by not clearing Padding of those text objects.
Padding of those text objects is managed by native.
- ACR:

[NUI] Fix to apply text objects' padding after added to view

---

src/Tizen.NUI/src/public/BaseComponents/ImageView.cs

Until now, we don't request image visual update if desired size changed.
The result of desired size applied and not have big difference. So we need to re-load the image if desired size changed

[NUI](ImageView) Create new visual if DesiredWidth/DesiredHeight changed

---

test/NUILayout/Examples/LinearLayoutTest/LinearHMatchMargin.cs
test/NUILayout/Examples/LinearLayoutTest/LinearHMatchMarginPadding.cs
test/NUILayout/Examples/LinearLayoutTest/LinearHSizeMargin.cs
test/NUILayout/Examples/LinearLayoutTest/LinearHSizeMarginPadding.cs
test/NUILayout/Examples/LinearLayoutTest/LinearVMatchMargin.cs
test/NUILayout/Examples/LinearLayoutTest/LinearVMatchMarginPadding.cs
test/NUILayout/Examples/LinearLayoutTest/LinearVSizeMargin.cs
test/NUILayout/Examples/LinearLayoutTest/LinearVSizeMarginPadding.cs

In LinearLayout cases of NUILayout, LinearLayout is a child of AbsoluteLayout.
To apply Margin of LinearLayout as a child of AbsoluteLayout, AbsoluteLayout.SetLayoutBounds is added.
nothing

[NUI] Apply Margin to LinearLayout cases in NUILayout

---

.github/workflows/nui-code-style-review.yml

[NUI] Try to fix github action error
it is said that the error was caused by github authentication access issue, but I don't know.
so I just try to use another script instead of `github.rest.issues.createComment()`
nothing

[NUI] Try to fix github action error

---

src/Tizen.NUI/src/internal/Common/SystemLocaleLanguageChangedManager.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs

Every time we set Translatable text,
system LocaleLanguage API is called, which creates overhead.
This patch updates through static classes only when a specific value is needed.

[NUI] Minimize system LocaleLanguage API calls in Text

---

src/Tizen.NUI/src/internal/Interop/Interop.VisualObject.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/Common/Layer.cs
src/Tizen.NUI/src/public/Common/PropertyMap.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/VisualBase.cs
src/Tizen.NUI/src/public/Window/GLWindow.cs
src/Tizen.NUI/src/public/Window/Window.cs

Reduce some build warnings at VisualObjects
- Remove CA1030
- Disable warning for CA2000 for several codes
- Fix unmatched binding function
- Remove CA1001 : Make VisualTransformInfo as disposable
Total the number of build warnings : 1851 -> 1818
Build command : dotnet build /p:NuiRoslynAnalysis=true

[NUI] Reduce build warnings at VisualObjects

---

src/Tizen.NUI/src/public/Layouting/LayoutItem.cs

Previously, ExcludeLayouting case sets layout size only if Width/HeightSpecification is negative value.
If Width/HeightSpecification is negative value, then it is either MatchParent or WrapContent instead of fixed size value. Therefore, calculated layout size should be set to view size.
Now, LayoutWidth/Height is used instead of Width/HeightSpecification. Width/HeightSpecification sets view size if it is fixed size value. Unlike Width/HeightSpecification, LayoutWidth/Height does not set view size although it is fixed size value. View size is set by Layout.
Therefore, the condition that LayoutWidth/Height is not fixed size value is not the same with the condition that Width/HeightSpecification is not fixed size value since view size may not be set.
To make the condition same as before, …

[NUI] Fix SetSize of ExcludeLayouting with LayoutWidth/Height

---

src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs

Typo of padding top + end is fixed to top + bottom.
- ACR:

[NUI] Fix AbsoluteLayout typo in calculating Padding size

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

If a view.Layout.IsPaddingHandledByNative is true, then the view.Padding setter sets view.Padding instead of view.Layout.Padding. Because the padding is applied by DALi instead of NUI Layout.
In the same way, view.Padding getter gets view.Padding instead of view.Layout.Padding if view.Layout.IsPaddingHandledByNative is true.
- ACR:

[NUI] Fix to check IsPaddingHandledByNative for Padding getter

---

src/Tizen.NUI/src/internal/Interop/Interop.BackgroundBlurEffect.cs
src/Tizen.NUI/src/public/RenderEffects/RenderEffect.cs

This enables CreateBackgroundBlurEffect(blurRadius) an additional argument, whether to blur once or always.
Default behavior is to refresh every frame(always).
Note: Since RenderEffect instances are immutable(no getter), the option is only applicable at creation.
Needs to be merged after following DALi patches:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/321580
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/321582

[NUI] Add background blur effect option: blur once

---

src/Tizen.NUI/src/internal/Common/SystemFontSizeChangedManager.cs
src/Tizen.NUI/src/internal/Common/SystemFontTypeChangedManager.cs
src/Tizen.NUI/src/internal/Common/SystemLocaleLanguageChangedManager.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs

Every time we set Translatable text,
system LocaleLanguage API is called, which creates overhead.
This patch updates through static classes only when a specific value is needed.

[NUI] Minimize system LocaleLanguage API calls in Text 

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
src/Tizen.NUI/src/public/Layouting/LinearLayout.cs

[NUI] Exclude layouting on invisible children

---

src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
src/Tizen.NUI/src/public/Layouting/GridLayout.cs
src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs

After Xaml is disabled, there are boxing/unboxing objects in Getter/Setter in Layouting, these could be removed.
- ACR:

[NUI] Remove code about boxing/unboxing in Layouting.

---

src/Tizen.NUI.Extension/Markup/TextEditorExtensions.cs
src/Tizen.NUI.Extension/Markup/TextFieldExtensions.cs
src/Tizen.NUI.Extension/Markup/TextLabelExtensions.cs
src/Tizen.NUI.Extension/Markup/ViewExtensions.cs
src/Tizen.NUI/src/devel/Lite/UIColor.cs
src/Tizen.NUI/src/internal/Common/Object.cs
src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs

* Remove internal UIColor constructor with vector4 type. (It caused wrong use of `new UIColor(0xFFFFFF)`)
* Add predefined colors: Yellow, Cyan, Magenta, Gray
- ACR:

[NUI] Remove UIColor constructor with vector4 and etc.

---

src/Tizen.NUI/src/internal/Utility/ColorCutQuantizer.cs

Until now, We use some static pointer at `ColorCutQuantizer` class.
Since we could create that class at worker thread freely, we should not access static pointer without any locking points.
And also, those static values should not be static.
To fix this issue, let we make `ColorCutQuantizer.Vbox` hold it's parent, and remove static keyword.

[NUI.Palette] Make Palette.GenerateAsync() thread safe

---

src/Tizen.NUI/src/internal/Rendering/RendererProperty.cs
src/Tizen.NUI/src/public/Rendering/Renderable.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AsyncImageLoaderTest.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CircularTextSample.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ClippedImage.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RendererUpdateAreaTest.cs

Let we use latest `Renderable` class, instead of `Renderer`.

[NUI.Samples] Make NUI Samples use Renderable instead Renderer

---

src/Tizen.NUI/src/devel/Lite/UICorner.cs
src/Tizen.NUI/src/devel/Lite/UIExtents.cs
src/Tizen.NUI/src/devel/Lite/UIRect.cs
src/Tizen.NUI/src/devel/Lite/UIState.cs
src/Tizen.NUI/src/devel/Lite/UIVector2.cs
src/Tizen.NUI/src/devel/Lite/UIVector3.cs

Made following IEquatable and immutable
* `UICorner`
* `UIExtents`
* `UIRect`
* `UIState`
* `UIVector2`
* `UIVector3`
- ACR:

[NUI] Implement IEquatable for primitive structures and make them immutable

---

src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs

When the label's `HeightSpecification` is wrap content, the result of `GetHeightForWidth()` is used to calculate the text height.
The previous behavior simply used `NaturalSize`,
so it could not guarantee the behavior of the case below.
```
var label = new TextLabel
{
Text = "Something long long text...",
WidthSpecification = LayoutParamPolicies.WrapContent,
HeightSpecification = LayoutParamPolicies.WrapContent,
MaximumSize = new Size(400, 400),
Padding = new Extents(25, 25, 10, 10),
MultiLine = true,
};
```

[NUI] Fix height calculation of TextLabelLayout

---

src/Tizen.NUI/src/devel/Lite/UICorner.cs

Fix wrong equality check logic in `UICorner` and override `ToString` method to check value inside.
⚠️ depends: https://github.sec.samsung.net/NUI/OneUIComponents/pull/259
- ACR:

[NUI] Fix wrong equality check of UICorner

---

src/Tizen.NUI/Tizen.NUI.csproj

Let we use `analyzers.props` what `Global.ruleset` defined already.
For NUI csproj hijack, let we don't import duplicated property settings
Build warning : 1523 -> 1407 (Reduce 116)

[NUI] Apply Global.ruleset what TizenFX using

---

src/Tizen.NUI/src/deprecated/Rendering/FilterModeType_Deprecated.cs
src/Tizen.NUI/src/deprecated/Rendering/Geometry_Deprecated.cs
src/Tizen.NUI/src/deprecated/Rendering/Shader_Deprecated.cs
src/Tizen.NUI/src/deprecated/Rendering/TextureType_Deprecated.cs
src/Tizen.NUI/src/devel/Lite/UIExtents.cs
src/Tizen.NUI/src/devel/Lite/UIShadow.cs
src/Tizen.NUI/src/devel/Lite/UIVector3.cs
src/Tizen.NUI/src/internal/Common/DaliEnumConstants.cs
src/Tizen.NUI/src/internal/Common/FrameBuffer.cs
src/Tizen.NUI/src/internal/Common/RenderBufferFormat.cs
src/Tizen.NUI/src/internal/Common/RenderTask.cs
src/Tizen.NUI/src/internal/Interop/Interop.ItemFactory.cs
src/Tizen.NUI/src/internal/Utility/ItemFactory.cs
src/Tizen.NUI/src/public/Animation/Animatable.cs
src/Tizen.NUI/src/public/Common/NUIConstants.cs
src/Tizen.NUI/src/public/Layouting/MeasureSpecification.cs
src/Tizen.NUI/src/public/Layouting/MeasuredSize.cs
src/Tizen.NUI/src/public/ParticleSystem/Particle.cs
src/Tizen.NUI/src/public/Rendering/Texture.cs
src/Tizen.NUI/src/public/Rendering/TextureUploadProperties.cs
src/Tizen.NUI/src/public/Utility/AccumulatingVelocityTrackerStrategy.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
src/Tizen.NUI/src/public/Window/WindowBlurInfo.cs
test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Common/TSRenderTask.cs

- CA1707: Remove the underscores from member name
- CA2211: Non-constant fields should not be visible
- CA1815: {Strut} should override the equality (==) and inequality (!=) operators
- CA1720: Identifier 'Double' contains type namew
Build warning counts 1524 -> 1426 (Reduce 98)
Build command : dotnet build /p:NuiRoslynAnalysis=true

[NUI] Reduce more build warnings : CA1707, CA2211, CA1815, CA1720

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs

Remove unused extension method `Self` from NUI extension.
- ACR:

[NUI] Remove unused NUI extension

---

src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs

Previously BackgroundExtraData did dispose its disposable members which can be also used outside of this view. So it caused problems, for example it could dispose static color member such as Color.Black
- ACR:

[NUI] Fix wrong disposal bug

---

src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs

Since DRGLView's rendering callback invoked at render thread, we need to keep those delegate at least 1 frame until those delegate will never be called at native side.
We have good internal class for this case, named `RenderThreadObjectHolder`.

[NUI] Keep DRGLView delegate at least 1 frame rendering

---

src/Tizen.NUI/src/public/Events/GestureOptions.cs
src/Tizen.NUI/src/public/Events/PanGestureDetector.cs

This sets MinimumTouchesRequired and MaximumTouchesRequired when creating a PanGesture.
- ACR:

[NUI] Add SetPanGestureMinimumTouchesRequired and SetPanGestureMaximumTouchesRequired() to GestureOptions.

---

src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebDeviceList.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
src/Tizen.NUI/src/internal/WebView/WebDeviceList.cs
src/Tizen.NUI/src/internal/WebView/WebSettings.cs
src/Tizen.NUI/src/internal/WebView/WebViewDeviceConnectionChangedEventArgs.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

(WebView) Update and sync all the latest patches related to WebView that have been modified so far
- Add SetVideoHole() for EFL window
- Fix WebView delegate GC error
- Add WebView DeviceListGet,SetDefaultAudio
- Add FeedMouseWheel as hidden api
- Add some logs in NUICoreBackend.Exit() by request from GBM
- dali patches: 
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-adaptor/+/322117
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/322137
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-extension/+/322143
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/322145
nothing

[NUI] Update and sync all the latest patches related to WebView that have been modified so far

---

src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
src/Tizen.NUI/src/public/Animation/Animatable.cs

Reduce string creation by `Tizen.NUI.Animation.AnimateTo()`
- Prune unnecessary case
- Unsafe char[] access to avoid string creation
Unit test done in the local but I wish it could be fully tested on various scenario.
**More desirable case is to implement this logic in the native side.**

[NUI] Rewrite LowerFirstLetter

---

src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

ChangeLayoutSiblingOrder will change layout sequence of parent layout,
so current view layout does not need to be layout group.
- ACR:

[NUI] Fix layout sibiling order changes by RaiseToTop and LowerToBottom

---

src/Tizen.NUI.Extension/Markup/ViewExtensions.cs
src/Tizen.NUI/src/devel/Lite/UICorner.cs
src/Tizen.NUI/src/devel/Lite/UIExtents.cs
src/Tizen.NUI/src/devel/Lite/UIShadow.cs
src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs

Remove `Default` field from UI structs except UIColor
- ACR:

[NUI] Remove Default field from UI structs except UIColor

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ConstraintWithCustomShaderTest.cs

Their was conflict issue in dali side, both DecoratedVisualRenderer and Control has same name as animatable.
To fix this issue, we should seperate the name as unique.
After now, we sould access to View's CornerRadius by string "viewCornerRadius".
Relative dali patch:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/322738

[NUI.Samples] Change corner radius source name as "ViewCornerRadius"

---

.github/workflows/build-branches.yml
.github/workflows/build-pull-request.yml
.github/workflows/check-api-level.yml
.github/workflows/deploy-documents-for-tizen-docs.yml
.github/workflows/deploy-documents.yml
.github/workflows/deploy-packages.yml
.github/workflows/nightly-release.yml
.github/workflows/postback-pull-request.yml

As of April 15th, Github actions no longer supports Ubuntu 20.04.
For more details, see https://github.com/actions/runner-images/issues/11101
This PR is to update the workflows to use Ubuntu 22.04 instead.

Bump Ubuntu version in github actions to 22.04

---

.github/workflows/nui-code-style-review.yml

Add missing jobs #6848
Also, bump-up the version as 24.04, not 22.04
(24.04 is latest)

[NUI] Bump Ubuntu version in github action to 24.04

---

src/Tizen.NUI/src/internal/Common/SystemFontSizeChangedManager.cs
src/Tizen.NUI/src/internal/Common/SystemFontTypeChangedManager.cs
src/Tizen.NUI/src/internal/Common/SystemLocaleLanguageChangedManager.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/AdvancedTextVisual.cs

There was some exception throwing at some targets s.t. SystemSettings not supported.
If then, we should not do anything after those exception occured.

[NUI] Catch exception when Tizen.System.SystemSettings throw exception

---

src/Tizen.NUI.Components/Controls/ScrollableBase.cs

Previously, ScrollableBase Layout did not respect MaximumSize so the Size property value might be bigger than actual rendered size on screen if MaximumSize is smaller than Size property value. Because actual rendered size respects MaximumSize in DALi.
Now, ScrollableBase Layout respects MaximumSize so the Size property value and actual rendered size on screen are the same.
- ACR:

[NUI] Fix ScrollableBase Layout to respect MaximumSize

---

src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs

When KeyEvent is triggered frequently, a cache can reduce the peak value of memory usage.
- ACR:

[NUI] Add a cache for key event in View.

---

src/Tizen.NUI/src/public/Layouting/FlexLayout.cs

Not to block GC of child views, Dictionary taking child views is removed from FlexLayout.
- ACR:

[NUI] Fix FlexLayout not to use Dictionary taking child views

---

src/Tizen.NUI/src/internal/Common/ControlStateImpl.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs

Hide `UIState` as internal and rename it `ControlStateImpl`.
- ACR:

Hide UI state

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Components/DefaultRuler.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Components/FixedRuler.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Components/Ruler.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Components/RulerDomain.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Components/RulerPtr.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Components/ScrollView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliTableView.cs

After remove unused codes #6621 and #6670 Ruler was removed.
But the ruler was useful when we use ScrollView at Tizen.NUI.Sample.
To make the demo app works well, let we implement it only inside the demo components.

[NUI.Samples] Revive Ruler at Tizen.NUI.Samples

---

src/Tizen.NUI/src/internal/Interop/Interop.BackgroundBlurEffect.cs
src/Tizen.NUI/src/internal/Interop/Interop.RenderEffect.cs
src/Tizen.NUI/src/public/RenderEffects/BackgroundBlurEffect.cs
src/Tizen.NUI/src/public/RenderEffects/RenderEffect.cs

This PR enables mutable RenderEffect. Previously, we could only create an immutable RenderEffect.
This PR opens RenderEffect::Activate(); and RenderEffect::Deactivate(); to public,
while creating a new public class BackgroundBlurEffect with public properties and functions.

[NUI] Bind mutable background blur effect with public functions

---

src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
src/Tizen.NUI/src/internal/Interop/Interop.GradientVisual.cs
src/Tizen.NUI/src/internal/NativeBinding/NDalic.cs
src/Tizen.NUI/src/internal/XamlBinding/NUIConstantExtension.cs
src/Tizen.NUI/src/public/Visuals/GradientVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualConstants.cs

Add StartOffset of GradientVisual.
Start offset is the offset value that shifts the starting position of the gradient.
0.0 is start position of gradient, 1.0 is end position of gradient.
It is possible to set the startOffset outside the [0, 1] range.
For example, you can animate it from 0.5 to 1.5.
How to use:
Animation anim = new Animation(1000);
anim.AnimateTo(bgView, "gradient.StartOffset", 1.0f);
anim.Play();

[NUI] Add StartOffset of GradientVisual

---

test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RendererUpdateAreaTest.cs

We should match shader uniform's value type and
registered value type.
Unfortunatly, UIVector2 become Vector3 when we make it input of PropertyValue.

[NUI.Samples] Fix rendering bugs at RendererUpdateAreaTest

---

src/Tizen.NUI/src/internal/Interop/Interop.MaskEffect.cs
src/Tizen.NUI/src/public/RenderEffects/RenderEffect.cs

Introduce MaskEffect
MaskEffect is a fragment shader that applies a masking operation using a source view.
It controls the visibility of the target view based on alpha or luminance values from the mask source.
The effect supports transform and scale for flexible mask positioning.
How to use:
targetView.SetRenderEffect(RenderEffect.CreateMaskEffect(sourceView));
targetView.ClearRenderEffect();
OR
// target view, mask mode, positionX, positionY, scaleX, scaleY
targetView.SetRenderEffect(RenderEffect.CreateMaskEffect(sourceView, RenderEffect.MaskMode.Luminance, 0.0f, 0.0f, 1.0f, 1.0f));
targetView.ClearRenderEffect();

[NUI] Introduce MaskEffect

---

src/Tizen.NUI/src/internal/Animation/Constraint.cs
src/Tizen.NUI/src/public/Common/PropertyArray.cs
src/Tizen.NUI/src/public/Events/Wheel.cs
src/Tizen.NUI/src/public/Utility/Capture.cs
src/Tizen.NUI/src/public/Visuals/AnimatedImageVisual.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/AnimatedImageVisual.cs
src/Tizen.NUI/src/public/Window/MouseInOut.cs
src/Tizen.NUI/src/public/Window/MouseRelative.cs

Meanwhile some memory leaks are fixed. For example, Vector2.Dispose is not called in Wheel constructor.
- ACR:

[NUI] Fix some CA2000 warnings in NUI.

---

src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs
src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
src/Tizen.NUI/src/public/ViewProperty/InnerShadow.cs
src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/InnerShadowSample.cs

Let we make property for InnerShadow.
It will be used when we want to render the shadow inset the view.
Also, Let we make Borderline as top of views, not to touch visual directly. It will be rendered above the inner shadow now.
* How to use
UIExtents = Inset length of each direction's shadow.
BlurRadius = Radius of shadow. Same as BoxShadow usage.
Color = Color of shadow, Same as BoxShadow usage.
```cs
// InnerShadow for top-left
view.InnerShadow = new InnerShadow(new UIExtents(20.0f, 0.0f, 20.0f, 0.0f), blurRadius, color);
// InnerShadow for inset
view.InnerShadow = new InnerShadow(new UIExtents(20.0f), blurRadius, color);
```
* Sample code scene

[NUI] Implement InnerShadow + Bind Control Borderline and remove relative codes.

---

src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs

Added RenderScale to prevent text rendering quality degradation when scaling up with View.Scale.
https://github.com/wonrst/NUI-Text/blob/main/render_scale_tpk/res/render_scale.gif?raw=true
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/321715
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/321716

[NUI] Add RenderScale to TextLabel

---

src/Tizen.NUI/src/internal/Interop/Interop.VisualFactory.cs
src/Tizen.NUI/src/public/Visuals/VisualFactory.cs
src/Tizen.NUI/src/public/Visuals/VisualFactoryCreationOptions.cs

We need to make some way to create `ImageVisual` forcibly even if it is animation images.
For now, let we make the property to change internal creation options.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/324608

[NUI] Add creation option to visual factory

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityStatesV2.cs
src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityV2.cs

Make enum to be used as a flag.
```C#
SetAccessibilityStatesV2(GetAccessibilityStatesV2.Busy | GetAccessibilityStatesV2.Checked);
```
- ACR:

[NUI] Make AccessibilityStatesV2 flag enum

---

src/Tizen.NUI/src/deprecated/BaseComponents/View_Deprecated.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

- Uses different way to handle user-defined renderables and system-generated renderables.
- AddRenderable, GetRenderableAt, RemoveRenderable, and RenderableCount are only used for user-defined renderables.
- GetEffectiveRenderableAt, and EffectiveRenderableCount are used for system-generated renderables for example image visual of imageView.
- User cannot add or remove effectiveRenderable.
- ACR:

[NUI] Make View.AddRenderable/RemoveRenderable handle only user defined renderables

---

src/Tizen.Network.WiFiDirect/Interop/Interop.WiFiDirect.cs
src/Tizen.Network.WiFiDirect/Tizen.Network.WiFiDirect/WiFiDirectEnumerations.cs
src/Tizen.Network.WiFiDirect/Tizen.Network.WiFiDirect/WiFiDirectManager.cs
src/Tizen.Network.WiFiDirect/Tizen.Network.WiFiDirect/WiFiDirectManagerImpl.cs
src/Tizen.Network.WiFiDirect/Tizen.Network.WiFiDirect/WiFiDirectPeer.cs

**Description of Change**
Add new wifi-direct C# APIs for following CAPIs
```
int wifi_direct_add_vsie(wifi_direct_vsie_frames_e frame_id, const char *vsie_str);
int wifi_direct_get_vsie(wifi_direct_vsie_frames_e frame_id, char **vsie_str);
int wifi_direct_remove_vsie(wifi_direct_vsie_frames_e frame_id, const char *vsie_str);
int wifi_direct_get_peer_vsie(char *mac_address, char **vsie);
int wifi_direct_get_connecting_peer_info(wifi_direct_discovered_peer_info_s **peer_info);
int wifi_direct_accept_connection(char *mac_address);
int wifi_direct_reject_connection(char  #*mac_address);
```
**API Changes**
- ACR: NA
These are internal APIs, They are being backported from API Level 13.
Added:
- enum WiFiDirectVsieFrameType
- string Vsie {get; }
- void AddVsie(WiFiDirectVsieFrameType frameId, …

[Tizen.Network.WiFiDirect] Add VSIE and connection related APIs

---

src/Tizen.NUI/src/internal/Common/NativeImageInterface.cs
src/Tizen.NUI/src/internal/Interop/Interop.CameraActor.cs
src/Tizen.NUI/src/internal/Interop/Interop.GLView.cs
src/Tizen.NUI/src/internal/Interop/Interop.Gesture.cs
src/Tizen.NUI/src/internal/Interop/Interop.InputMethodOptions.cs
src/Tizen.NUI/src/internal/Interop/Interop.LongPressGesture.cs
src/Tizen.NUI/src/internal/Interop/Interop.NativeImageInterface.cs
src/Tizen.NUI/src/internal/Interop/Interop.PanGestureDetector.cs
src/Tizen.NUI/src/internal/Interop/Interop.ParticleEmitter.cs
src/Tizen.NUI/src/internal/Interop/Interop.PinchGesture.cs
src/Tizen.NUI/src/internal/Interop/Interop.RotationGesture.cs
src/Tizen.NUI/src/internal/Interop/Interop.Stage.cs
src/Tizen.NUI/src/internal/Interop/Interop.TapGesture.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewImplSignal.cs
src/Tizen.NUI/src/internal/Utility/Camera.cs
src/Tizen.NUI/src/public/Events/Gesture.cs
src/Tizen.NUI/src/public/Events/LongPressGesture.cs
src/Tizen.NUI/src/public/Events/PanGesture.cs
src/Tizen.NUI/src/public/Events/PinchGesture.cs
src/Tizen.NUI/src/public/Events/RotationGesture.cs
src/Tizen.NUI/src/public/Events/TapGesture.cs
src/Tizen.NUI/src/public/ParticleSystem/ParticleEmitter.cs
src/Tizen.NUI/src/public/Window/Window.cs

[NUI] Remove interop APIs that are not implemented in csharp-binder.

---

src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs

When adding a text label to the nui layout in AsyncAuto mode,
async rendering is automatically requested according to the constraint policy.
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/326320
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/326321
When used as shown below, APIs with overhead such as NaturalSize and HeightForWidth are not called on the main thread.
```csharp
var view = new View () { Layout = new LinearLayout(){} };
var label = new TextLabel
{
Text = "Hello world",
WidthSpecification = LayoutParamPolicies.WrapContent,
HeightSpecification = LayoutParamPolicies.WrapContent,
RenderMode = TextRenderMode.AsyncManual,
};
view.Add(label);
```

[NUI] Add async condition to text label layout

---

src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs

In dali-csharp-binder, API is CSharp_Dali_Model_MeshHitSignal_Disconnect, while in csharp interop, API is CSharp_Dali_MotionData_MeshHitSignal_Disconnect.
- ACR:

[NUI.Scene3D] Fix an API mismatch issue in Interop.Model.

---

src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

To resolve ABI break, let we revert AddRenderable return uint, instead of void

[NUI] Make AddRenderable return uint

---

src/Tizen.NUI/src/internal/Interop/Interop.BackgroundBlurEffect.cs
src/Tizen.NUI/src/internal/Interop/Interop.GaussianBlurEffect.cs
src/Tizen.NUI/src/internal/Interop/Interop.RenderEffect.cs
src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/RenderEffects/BackgroundBlurEffect.cs
src/Tizen.NUI/src/public/RenderEffects/GaussianBlurEffect.cs
src/Tizen.NUI/src/public/RenderEffects/RenderEffect.cs

Bind `View.GetRenderEffect();` in order to ease explicit `.Dispose();` of an effect.
Add `GaussianBlurEffect` and some public apis(`Refresh()`, `IsActivated()` for `RenderEffect`) / (Get/Set blur downscale factor)
Relative DALi patches are:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/325249
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/323236
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/326024
Add finished signals of blur effects(`GaussianBlurEffect` and `BackgroundBlurEffect`)
Relative DALi patches are:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/325249
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/326662
- ACR:

[NUI] Add GaussianBlurEffect and blur effect signals

---

src/Tizen.Applications.Common/Tizen.Applications/DirectoryInfo.cs

This pach fixes bugs about common data paths.
The following APIs are changed.
- DirectoryInfo.CommonData
- DirectoryInfo.CommonCache
- DirectoryInfo.CommonSharedData
- DirectoryInfo.CommonSharedTrusted

[Applications.Common] Fix wrong implementation

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

If a view's LayoutDirection is changed, then its all descendants which
follow the view's LayoutDirection should update layout.
- ACR:

[NUI] Fix to update layout when LayoutDirection is changed

---

src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

To enable overriding behavior of Raise* and Lower* methods, the following protected virtual hooks are added.
- OnRaiseToTop
- OnLowerToBottom
- OnRaise
- OnLower
- OnRaiseAbove
- OnLowerBelow
- ACR:

[NUI] Add protected virtual hooks for Raise* and Lower* methods

---

src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Layouting/LayoutItem.cs

DALi has a bug that setting Size property with 0 does not work. However, setting SizeWidth or SizeHeight property with 0 works. So in NUI Layout, size is updated by setting SizeWidth and SizeHeight properties.
- ACR:

[NUI] Fix Layout to set size with 0

---

src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs

The implementation of the CreatePackage method and ExpansionPackageName property are modified. While caling the Interop.Package.PackageInfoGetName(), the native function calls cynara functions to check the privilege of the caller process. It causes a delay issue of the package creation.
- ACR: N/A

[PackageManager] Modify Package class

---

src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs

`AccessibilityNameRequested` and `AccessibilityDescriptionRequested` don't allow null string return. (Occur crash)
- ACR:

[NUI] Accessibility event return should not null

---

src/Tizen.NUI.MarkdownRenderer/src/internal/MarkdownStyleDefaults.cs
src/Tizen.NUI.MarkdownRenderer/src/internal/MarkdownUI/UICode.cs
src/Tizen.NUI.MarkdownRenderer/src/internal/MarkdownUI/UIContainer.cs
src/Tizen.NUI.MarkdownRenderer/src/internal/MarkdownUI/UIHeading.cs
src/Tizen.NUI.MarkdownRenderer/src/internal/MarkdownUI/UIList.cs
src/Tizen.NUI.MarkdownRenderer/src/internal/MarkdownUI/UIQuote.cs
src/Tizen.NUI.MarkdownRenderer/src/internal/MarkdownUI/UITable.cs
src/Tizen.NUI.MarkdownRenderer/src/internal/MarkdownUI/UIThematicBreak.cs
src/Tizen.NUI.MarkdownRenderer/src/internal/MarkdownUIBuilder.cs
src/Tizen.NUI.MarkdownRenderer/src/public/MarkdownStyle.cs

Add `CommonStyle.ItemPadding`:
Adds cell padding to the layout of the Markdown document. 
This provides more consistent and predictable behavior than the previous `CommonStyle.Margin`.
Removing `CommonStyle.Margin` because it is obsolete due to ItemPadding. 
If in the future we need separate Margins for each UI blocks, 
we will add separate Styles. (like `ThematicBreakStyle.Margin`)
Add Top and Bottom margins to `ListStyle` and Item.
This also provides more consistent spacing than the previous behavior.

[Markdown] Update markdown style

---

src/Tizen.NUI.Components/Tizen.NUI.Components.csproj

[NUI] Recover NUI.Components in tv profile
- By TCSACR-606, NUI.Components has been deprecated in tv profile only.
- Because, it is deprecated ACR, so the package should not be removed.
- The remove ACR will be processed after the future 2 versions of tizen release.
nothing

[NUI] Recover NUI.Components in tv profile

---

src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs
src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs

Sometimes the callback object for the unmanaged API released by GC before the unmanaged API returns.
Add GC.KeepAlive() to prevent this issue.
N/A

[PackageManager] Add GC.KeepAlive() for interop callback object

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Theme/ThemeManager.cs

For the other frameworks using NUI as a foundation and uses its own theme manager other than NUI's, the option that disable NUI ThemeManager is needed.
- ACR:

[NUI] Disable default theme manager

---

src/Tizen.NUI/src/internal/Common/RenderTask.cs
src/Tizen.NUI/src/internal/Common/RenderTaskList.cs

Make `RenderTask` code use latest implements which no memory leaks.
Also, let we ensure to call `RemoveTask` only from the render task list where it comes from.

[NUI] Clean-up the implements of RenderTask / RenderTaskList

---

src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
test/NUIGLView/NUIDirectRenderingGLViewSample/DirectRenderingGLViewSample.cs

To guard ABI Break, let just keep `RenderCallbackInput.Size` as `Size2D` type. Instead, make new API to get float type size of each values.

[NUI][DRGLView] Make `RenderCallbackInput.SizeWidth` and `RenderCallbackInput.SizeHeight` as float type

---

src/Tizen.NUI/src/internal/Interop/Interop.NDalic.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.CubeTransitionEffect.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.Item.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.ItemContainer.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.ItemFactory.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.ItemIdContainer.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.ItemLayout.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.ItemRange.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.ItemView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/NDalicPINVOKE.cs
test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/NativeBinding/TSNDalic.cs

- Seperated ItemView & CubeTransitionEffect from NUI.
- Remove an unused Interop API CSharp_Dali_NewItemLayout.
It is related to the patch in binder side:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/327238
- ACR:

[NUI] Make NUI.Samples use its own binder lib.

---

src/Tizen.NUI/src/internal/View/ViewAccessibilityData.cs
src/Tizen.NUI/src/public/Accessibility/AccessibilityActionReceivedEventArgs.cs

Some accessibility action requires target of accessibility highlight target view.
- ACR:

Add access target in AccessibilityActionRecievedEventArgs

---

src/Tizen.NUI/src/internal/View/ViewEventRareData.cs
src/Tizen.NUI/src/internal/View/ViewGestureData.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewLiteProperty.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs

* Fields moved to `ViewGestureData`
* panGestureDetector
* longGestureDetector
* pinchGestureDetector
* tapGestureDetector
* rotationGestureDetector
* Fields moved to `ViewEventRareData`
* interceptWheelHandler
* interceptWheelCallback
* wheelEventHandler
* wheelEventCallback
* interceptTouchDataEventHandler
* interceptTouchDataCallback
* layoutDirectionChangedEventHandler
* layoutDirectionChangedEventCallback
* hitTestResultDataCallback
* dispatchTouchEvents
* dispatchParentTouchEvents
* dispatchHoverEvents
* dispatchParentHoverEvents
* dispatchWheelEvents
* dispatchParentWheelEvents
* dispatchGestureEvents
* dispatchParentGestureEvents
* DisallowInterceptTouchEvent
* DisallowInterceptWheelEvent
* isThemeChanged
* backgroundImageSynchronousLoading
* enableControlState
- ACR:

[NUI] Move rarely used `View` fields to the separate object and etc.

---

src/Tizen.NUI/src/public/Common/BaseHandle.cs

Adds internal methods that can handle ownership of native pointer.
- ACR:

[NUI] Add methods to move ownership of native handle

---

src/Tizen.NUI/src/public/BaseComponents/View.cs

Since Extents.Zero is static variable, it should not be disposed.
- ACR:

[NUI] Fix not to dispose Extents.Zero

---

src/Tizen.NUI/src/internal/Layouting/Interop/Interop.FlexLayout.cs
src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
src/Tizen.NUI/src/public/Layouting/LayoutItem.cs

FlexLayout requires MarkDirty if child layout's layout properties are changed.
e.g. MarkDirty is required if child layout's Width/HeightSpecification is changed.
- ACR:

[NUI] Add FlexLayout.MarkDirty to recalculate children

---

src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/InnerShadowSample.cs

Depth index of children determine the order of rendering. But for micro optimization, we could set
all children of the view has the same rendering order. If then, we can setChildrenDepthIndexPolicyType.Equal.
Usually if we know that every childrens are not overlapps each other, and has multiple rendering options. (e.g InnerShadow, Shadow, BorderlineWidth).

[NUI] Bind `ChildrenDepthIndexPolicy`

---

src/Tizen.NUI/src/public/WebView/WebView.cs

The callstack:
Process terminated. A callback was made on a garbage collected delegate of type 'Tizen.NUI!Tizen.NUI.BaseComponents.WebView+JavaScriptMessageHandler::Invoke'.
at Tizen.NUI.NDalicPINVOKE.ApplicationMainLoop(System.Runtime.InteropServices.HandleRef)
at Tizen.NUI.Application.MainLoop()
at Tizen.NUI.NUICoreBackend.Run(System.String[])
at Tizen.Applications.CoreApplication.Run(System.String[])
at Tizen.NUI.NUIApplication.Run(System.String[])
at Tizen.TV.FLUX.FluxApplication.Run(System.String[])
at Tizen.TV.Service.CNCapsule.Program.Main(System.String[])
DotNET onSigabrt called on com.samsung.tv.cnvoice-assistant / DN_ce-assistant(20535) onSigabrt called
The reason might be that a local variable is gc-ed, but it is still used in unmanaged code, according to [1] and [2].
[1] …

[NUI] Fix a crash When WebView.EvaluateJavaScript is called frequently.

---

src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
src/Tizen.NUI/src/public/Window/Window.cs

Window insets are the inner size between window content and window edge.
Window insets are required when status bar, virtual keyboard, or clipboard appears on window to avoid window content obscured by them.
To provide the current window insets changes, GetInsets is added to Window.
- ACR:

[NUI] Add GetInsets to Window

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/Application/NUIWidgetApplication.cs

Since it is hard to determine whether current application set `IsUsingXaml` value as false or not, let we print log if it is changed.
Default is true so, if the log not printed, mean they using xaml now..

[NUI] Print log when IsUsingXaml property changed

---

src/Tizen.NUI/src/internal/Application/Application.cs
src/Tizen.NUI/src/internal/Common/ProcessorController.cs
src/Tizen.NUI/src/public/Application/NUIApplication.cs

To make ensure we can call Awake(), we should initialize this instance at mainthread at least once.

[NUI] Call ProcessorController.Initialize at application OnInit time

---

src/Tizen.NUI/src/internal/Common/Object.cs
src/Tizen.NUI/src/internal/Interop/Interop.Extents.cs
src/Tizen.NUI/src/internal/Interop/Interop.Vector2.cs
src/Tizen.NUI/src/internal/Interop/Interop.Vector3.cs
src/Tizen.NUI/src/public/Common/Extents.cs
src/Tizen.NUI/src/public/Common/Vector2.cs
src/Tizen.NUI/src/public/Common/Vector3.cs

Add internal API to reset all fields in Vector2, Vector3 and Extents to resue them.
- ACR:

[NUI] Add resets APIs for Vector2/3 and Extents

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/Common/BaseHandle.cs

Since it is relative with Appfw callback, we must not touch ThemeManager at preload time.

[NUI] Do not call `ThemeManager` constructor at Preload case

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs
src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
src/Tizen.NUI/src/public/BaseComponents/TextField.cs
src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
src/Tizen.NUI/src/public/BaseComponents/View.cs

Let we make them determine by NUI preload user, not platform itself.

[NUI] Do not create `BaseComponents` at NUI.preload time

---

src/Tizen.NUI/src/internal/View/ViewAccessibilityData.cs

- Updates the Target assignment logic in the `AccessibilityActionReceivedEventArgs` initialization to use the `GetManagedBaseHandleFromRefObject` method instead of `GetManagedBaseHandleFromNativePtr`.
- This method includes additional checks and handling mechanisms, such as null pointer validation, weak reference management, and disposal tracking, to ensure robustness and consistency in handling native-to-managed object bindings.

[NUI][A11y] Update `Target` of Action arguments to use reference object

---

src/Tizen.NUI/src/internal/Interop/Interop.VideoView.cs
src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VideoViewWithOffScreenRenderingTest.cs

This PR introduces a frame interpolation feature to the `VideoView` control, enabling smoother visual transitions between video frames on OffScreen rendering.
- VideoView.SetNativeImageSourceForCurrentFrame(NativeImageSource nativeImageSource)
- A new internal method that sets the `NativeImageSource` for the current video frame.
- This frame is used by the underlying native layer to perform interpolation with the previous frame.
- Requires `VideoView.Underlay` to be `true`.
- VideoView.FrameInterpolationInterval` (Property)
- A new `float` property to get or set the duration (in seconds) for the frame interpolation animation.
- The interpolation factor will animate from 0.0 to 1.0 over this interval.
- Must be non-negative.
This API allows developers to enhance video playback quality by …

[NUI] SetNativeImageSourceForCurrentFrame

---

src/Tizen.NUI/src/internal/Interop/Interop.View.cs
src/Tizen.NUI/src/internal/Interop/Interop.ViewSignal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/RenderEffects/BackgroundBlurEffect.cs
src/Tizen.NUI/src/public/RenderEffects/GaussianBlurEffect.cs
src/Tizen.NUI/src/public/RenderEffects/RenderEffect.cs

Related dali patches are: [329433](https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/329433) [329434](https://review.tizen.org/gerrit/c/platform/core/uifw/dali-csharp-binder/+/329434)
Visual demo results at: [link](https://confluence.sec.samsung.net/spaces/GFX/pages/1032560551/25?focusedCommentId=1433537593#comment-1433537593)
Precondition: `View.OffScreenRendering` should be set to `OffScreenRenderingType.RefreshOnce`
Includes minor description updates at `RenderEffect`.
- ACR:

[NUI] Extract View's ImageUrl from offscreen rendering output

---

src/Tizen.NUI/src/public/Application/NUIApplication.cs

Let we write some more informations about `NUIApplication.Exit()` API usage. Since we need to completely processed all pending jobs before main loop finished, we need to doing real-terminate process at idler time.

[NUI] Write comments for `NUIApplication.Exit()`

---

test/Tizen.NUI.Devel.Tests.Ubuntu/Tizen.NUI.Devel.Tests/testcase/public/TSView.cs

[NUI.Devel.Tests] Let we use `AccessibilityStatesV2` flag instead of struct

---

src/Tizen.NUI/src/public/WebView/WebView.cs

[NUI] Check if WebView is disposed when EvaluateJavaScript is called.

---

src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetLifecycleState.cs
src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs

This patch adds a OnPreCreate() method that can perform pre initialzation. 
NUIGadget Viewer developers can control Gadget by calling Load(), CreateInstance(), PreCreate(), and Create().
Added:
- void NUIGadget.OnPreCreate();
- NUIGadget NUIGadgetManager.CreateInstance(string resourceType, string className, bool useDefaultContext);
- void NUIGadgetManager.PreCreate(NUIGadget gadget);
- void NUIGadgetManager.Create(NUIGadget gadget);
- NUIGadgetLifecycleState.PreCreated // Enumeration

[NUI.Gadget] Add OnPreCreate() Method

---

src/Tizen.NUI/src/public/Layouting/LayoutItem.cs

The initial values of padding and margin of LayoutItem is static value Extents.Zero not to allocate memory for zero extents.
If so, those padding and margin should not be disposed.
Like View, LayoutItem is fixed not to dispose padding and margin.
- ACR:

[NUI] Fix LayoutItem not to dispose padding and margin

---

src/Tizen.NUI/src/internal/Common/ViewShadowType.cs
src/Tizen.NUI/src/internal/Common/VisualObjectsContainer.cs
src/Tizen.NUI/src/internal/Interop/Interop.VisualObjectsContainer.cs
src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
src/Tizen.NUI/src/public/BaseComponents/ViewVisuals.cs
src/Tizen.NUI/src/public/ViewProperty/InnerShadow.cs
src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
src/Tizen.NUI/src/public/Visuals/VisualObject/VisualBase.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/InnerShadowRadiusTest.cs
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ShadowNeumorphismTest.cs

This PR introduces the ability to add multiple shadows to a single `View`, significantly enhancing the flexibility and expressiveness of NUI-based UIs. Developers can now layer different shadow effects to achieve sophisticated visuals, such as the popular neumorphism design style.
- __New Public API `View.AddShadow()`__: A simple and intuitive method `AddShadow(Shadow shadow)` has been added to the `View` class. This allows developers to append `Shadow` or `InnerShadow` objects to a view. Multiple calls to `AddShadow()` will stack the shadow effects, enabling complex layered visuals.
- __Enhanced `Shadow` and `InnerShadow` Classes__: Both `Shadow` and `InnerShadow` classes now include a `GetShadowVisual()` method. This method internally creates and configures a `ColorVisual` with …

[NUI] Adds AddShadow method in View for multiple Shadows on a View

---

src/Tizen.NUI/src/internal/WebView/WebContext.cs
src/Tizen.NUI/src/public/WebView/WebView.cs

A crash occurs in the following case:
1) Create 2+ WebView instances in an app.
2) Do something on WebViews.
3) Dispose WebView instances--> the crash occurs.
The reason is that WebContext would be disposed twice. But WebContext is a singleton in DALi side.
WebContext would have an invalid pointer when it is disposed the second time.
- ACR:

[NUI] Fix crash issue when WebView is disposed.

---

src/Tizen.NUI/src/public/Window/BorderWindow.cs

Padding can be used as is using BorderLineThickness.
- ACR:

[NUI] Remove unnecessary padding calculations from the BorderWindow.

---

src/Tizen.NUI.Gadget/Tizen.NUI/OneShotService.cs

In Run method, `TizenCore.Spawn` can return null value.
Therefore, check if the `_task` value is null before _task.Post()
- ACR: N/A

[Tizen.NUI.Gadget] Improve task creation error handling

---

src/Tizen.Applications.Common/Tizen.Applications/Application.cs
src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs

Allow empty string input to change to default user 
Initialization of Applications.Current.DirectoryInfo managed by static because the value of DirectoryInfo may change after RemountSubsession

[Applications] Fix RemountSubsession

---

src/Tizen.NUI.WindowSystem/src/public/TaskbarService.cs

Remove unnecessary window type checks on init TaskbarService

[NUI.WindowSystem] TaskbarService: remove useless checker
