- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaDatabase.cs
- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
- src/Tizen.Content.MediaContent/doc/api/Tizen.Content.MediaContent.md
Added "content.scanning.others" feature tags to related methods.
- ACR: http://suprem.sec.samsung.net/jira/projects/TCSACR/issues/TCSACR-125
The "content.scanning.others" feature related methods(which are MediaDatabase.ScanFile, MediaInfoCommand.Add, and MediaInfoCommand.AddAsync) work differently now based on whether the specified feature is supported.
> [MediaContent] Added "content.scanning.others" feature tags to related methods.

- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaContentError.cs
Added NotSupportedException to be thrown when the feature is not supported.
- ACR: ttp://suprem.sec.samsung.net/jira/projects/TCSACR/issues/TCSACR-125
> [MediaContent] Added NotSupportedException to be thrown when the feature is not supported.

- src/Tizen.Uix.TtsEngine/Interop/Interop.TtsEngine.cs
- src/Tizen.Uix.TtsEngine/Tizen.Uix.TtsEngine/TtsEngine.cs
Fix invalid marshalling code in Tizen.Uix.TtsEngine
Because of invalid marshalling, the tts engine made using .net API occurs stack overflow error.
This change fixes this bug.
> [TtsEngine] Fix invalid marshalling

- src/ElmSharp/ElmSharp/Widget.cs
Focus Chain gets lost due to the malfunction of calling SetFocus(false).
Eventually, the focus is missing forever on the app. 
This change is about adding an exeption logic to make focus chain normalized.
> [ElmSharp] Add exception logic to Widget.SetFocus()

- src/Tizen.System.Information/RuntimeInfo/RuntimeInfoEventHandler.cs
- src/Tizen.System.Information/RuntimeInfo/TvProductHelper.cs
Restore converted key before calling a callback.
Callback provides invalid string key if it is converted.
> [Information] Restore converted key before calling a callback

- src/ElmSharp/ElmSharp/Widget.cs
- src/ElmSharp/Interop/Interop.Elementary.cs
Focus Chain gets lost due to the malfunction of calling SetFocus(false).
Eventually, the focus is missing forever on the app.
We created an internal API to return the initial focus state to the same state as when the App was first launched. This change is about adding an exeption logic to make focus chain normalized.
> [ElmSharp] Changed Widget.SetFocus() internal routine

- src/Tizen.NUI/src/public/BaseComponents/View.cs
If parentChildren count is empty, return 0
Fix SiblingOrder return value
> [NUI] Fix SiblingOrder return value

- src/Tizen.NUI/src/internal/WidgetApplication.cs
- src/Tizen.NUI/src/public/UIComponents/Button.cs
Value widget, which was created by as-operator, so can be null,
is dereferenced in method call widget.GetIntPtr()
Value value, which is result of method invocation with possible null return value,
is dereferenced in method call value.Get()
Fix svace issue
> [NUI] Fix svace issue

- src/Tizen.System/Device/Battery.cs
- src/Tizen.System/Device/Led.cs
Signed-off-by: lokilee73 <changjoo.lee@samsung.com>
Apply fixes based on static analysis results
Bugs about thread safety were detected
Bugs Fixed
Kona WorkItemID : DF180112-01404
Checker: NO_LOCKSTAT
File: /Device/Battery.cs
Line: 285
Kona WorkItemID : DF180112-01407
Checker: NO_LOCKSTAT
File: /Device/Led.cs
Line: 216
> [Device] add lock for global variable of led and battery

- src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationStyleBinder.cs
[Notification] Fix handle leak
- After the duplicated Bundle object is used, Dispose is called to release the unmanaged resource.
> [Notification] Fix handle leak

- src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationStyleBinder.cs
Fix handle leak
After the duplicated Bundle object is used, Dispose is called to release the unmanaged resource.
> Fix handle leak

- src/Tizen.Uix.SttEngine/Interop/Interop.SttEngine.cs
- src/Tizen.Uix.SttEngine/Tizen.Uix.SttEngine/SttEngine.cs
- src/Tizen.Uix.TtsEngine/Interop/Interop.TtsEngine.cs
- src/Tizen.Uix.TtsEngine/Tizen.Uix.TtsEngine/TtsEngine.cs
Fix invalid marshalling code in Tizen.Uix.TtsEngine and Tizen.Uix.SttEngine.
Because of invalid marshalling, the tts and stt engines made using .net API occur stack overflow error.
This change fixes this bug.
> [TtsEngine/SttEngine] Fix invalid marshalling

- src/Tizen.NUI/src/public/BaseComponents/View.cs
Signed-off-by: dongsug.song <dongsug.song@samsung.com>
[NUI] Add protected codes to avoid the crash when the IntPtr of key is 0
[NUI] Add protected codes to avoid the crash when the IntPtr of key is 0
N/A
N/A
> [NUI] Add protected codes to avoid the crash when the IntPtr of key is 0

- src/ElmSharp/ElmSharp/Background.cs
[ElmSharp] Changed Background widget Color property internal implementation to Widget BackgroundColor property
There are two ways for setting background color to Background widget. (Color & BackgroundColor property)
Two properties are almost same for Background widget but internal implementation is different.
I changed Background widget Color property internal implementation to Widget BackgroundColor property.
> [ElmSharp] Changed Background widget Color property internal implementation

- src/Tizen.Multimedia/Common.Internal/ObjectKeeper.cs
- GChandle must be freed.
- Handles could be leaked if the object is not disposed manually.
> [Multimedia] Fixed possible memory leak.

- src/Tizen.Multimedia/AudioManager/AudioDevice.cs
- src/Tizen.Multimedia/AudioManager/AudioManager.cs
- src/Tizen.Multimedia/AudioManager/AudioManagerError.cs
- src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
- src/Tizen.Multimedia/AudioManager/AudioVolume.cs
- src/Tizen.Multimedia/AudioManager/MaxVolumeLevel.cs
- src/Tizen.Multimedia/AudioManager/VolumeLevel.cs
- src/Tizen.Multimedia/Interop/Interop.Device.cs
1. Adding null event handler - it should be prevented because if no handler is added before, then no need to register the native callback.
2. Renames error validation method to ThrowIfError for readability.
3. some minor code improvements
> [Multimedia] Fixed minor issues and clean codes in AudioManager.

- src/Tizen.System.Storage/Interop/Interop.Storage.cs
- src/Tizen.System.Storage/Storage/Storage.cs
- src/Tizen.System.Storage/Storage/StorageDevice.cs
- src/Tizen.System.Storage/Storage/StorageManager.cs
Change-Id: Ic5af889a8bcc40b3667081e0ec8088df697006ee
Signed-off-by: pr.jung <pr.jung@samsung.com>
- Add ExtendedInternal on StorageArea
- Add StorageDevice enumerations
- Add SetChangedEvent and UnsetChangedEvent on StorageManager class for storage_set_changed_cb and storage_unset_changed_cb apis
- N/A
Added:
- ExtendedInternal = Interop.Storage.StorageArea.ExtendedInternal,
- public enum StorageDevice
{ 
ExternalSDCard = Interop.Storage.StorageDevice.ExternalSDCard,
ExternalUSBMassStorage = Interop.Storage.StorageDevice.ExternalUSBMassStorage,
ExtendedInternalStorage = Interop.Storage.StorageDevice.ExtendedInternalStorage,
}   
- public static void SetChangedEvent(StorageArea type, EventHandler handler)
- public static void UnsetChangedEvent(StorageArea type, EventHandler handler)
N/A …
> [Storage] Add new enum and new methods

- src/Tizen.NUI/src/internal/Registry.cs
[NUI] IntPtr is not Null always, null should be IntPtr.Zero
[NUI] IntPtr is not Null always, null should be IntPtr.Zero
None
None
> [NUI] IntPtr is not Null always, null should be IntPtr.Zero

- src/Tizen.Multimedia/Interop/Interop.EvasObject.cs
- src/Tizen.Multimedia/Interop/Interop.Libc.cs
- src/Tizen.Multimedia/Interop/Interop.MediaTool.cs
- src/Tizen.Multimedia/MediaTool/AudioMediaFormat.cs
- src/Tizen.Multimedia/MediaTool/ContainerMediaFormat.cs
- src/Tizen.Multimedia/MediaTool/MediaFormat.cs
- src/Tizen.Multimedia/MediaTool/MediaPacket.Lock.cs
- src/Tizen.Multimedia/MediaTool/MediaPacket.cs
- src/Tizen.Multimedia/MediaTool/MediaPacketVideoPlane.cs
- src/Tizen.Multimedia/MediaTool/TextMediaFormat.cs
- src/Tizen.Multimedia/MediaTool/VideoMediaFormat.cs
- Use out variable.
- Validate enum with util method.
- MediaPacket.Lock now uses a field of MediaPacket not MediaPacket it self.
- And minor code improvement.
> [Multimedia] Code cleaning of MediaTool.

- packaging/csapi-tizenfx.spec.in
- packaging/makespec.sh
- packaging/version.txt
Remove version check for dali native package from packaging/csapi-tizenfx.spec
> [Build] Remove dali native version check from rpm spec

- src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
When Tizen.System.SystemSettings caller try to remove event handler event if there is no event handler
in SystemSettings Key,
There will be log "There is no event handler" with "Tizen.System.SystemSettings" tag.
> [SystemSettings] Change remove event handler for all of keys.

- src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
Signed-off-by: sungrae jo <seongrae.jo@samsung.com>
Fix lock issue
Possible missing lock before accessing to the _handle variable.
> [Stt] Fix lock issue

- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
WiFiManagerImple class has only single instance, but in multi-thread environment, race condition occurs when checking if the instance is null
- Add lock before checkint if the instance is null
> [Tizen.Network.WiFi] Use lock on checking if instance is null

- src/Tizen.Applications.MessagePort/Tizen.Applications.Messages/MessagePort.cs
To get remote app id regardless of the remote-port name
Changed:
- public void Listen()
- If remote port is not valid it can't get remote appid on C# API,
Because it is different from native implementation, we should provide backward compatibility
> [Tizen.Applications.MessagePort] Remove checking name of remoteport

- src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/AttachPanelInternal.cs
Remove static instance.
- Created AttachPanel instance is removed because of wrongly created AttacPanel's instance.
None
- The bug is fixed.
- There is no behavioral change. Even removing static instance, it couldn't affect to the AttachPanel's behavior.
> [AttachPanel] Remove static instance (related #85)

- src/Tizen.NUI/src/internal/Registry.cs
Widget Application can't get thread id because it works in different process
So Registry need to avoid in this case
> [NUI] Fix widget application crash issue

- src/Tizen.System.Usb/Usb/UsbManager.cs
Add NotSupportedException
- None
Changed:
- NotSupported.ThrowIfFailed => Interop.ErroCode.NotSupported.ThrowIfFailed
When CAPI object is null, it returns NotSupportedException
> [System][Usb] apply NotSupportedException

- src/Tizen.NUI/src/internal/Application.cs
- src/Tizen.NUI/src/internal/DaliEnumConstants.cs
- src/Tizen.NUI/src/internal/FrameBuffer.cs
- src/Tizen.NUI/src/internal/ManualPINVOKE.cs
- src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
- src/Tizen.NUI/src/internal/Registry.cs
- src/Tizen.NUI/src/internal/VersionCheck.cs
- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
- src/Tizen.NUI/src/public/BaseComponents/TableView.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Container.cs
- src/Tizen.NUI/src/public/FocusManager.cs
- src/Tizen.NUI/src/public/Layer.cs
- src/Tizen.NUI/src/public/UIComponents/Popup.cs
- src/Tizen.NUI/src/public/Window.cs
This reverts commit 7aa84bbdff8f176b5c67907129dd90e85cfae36b.
- ACR: 
Added:
Changed:
> Revert "[NUI] Make GetParent() protected (#165)"

- build.cmd
- build.sh
- build/build.proj
- build/pack.csproj
Use dotnet-cli instead of nuget.exe to remove mono dependency.
> [Build] Remove mono dependency

- src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecError.cs
Fix error enum bug
- InvalidOperation was defined as InvalidParameter. So fix it to valid type.
> [MediaCodec] Fix error enum bug

- src/ElmSharp/ElmSharp/EvasObject.cs
GetTextBlockGeometryByLineNumber method of EvasObejct is obsolete.
> [ElmSharp] GetTextBlockGeometryByLineNumber is obsolete

- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
Dispose() of WiFiAP and ConnectionProfile calls the corresponding destroy function of native capi.
Each handle is set to zero only when the Interop call is successful
> [Connection][WiFi] Assign zero to Handle only when Interop.Destroy()

- src/Tizen.NUI/src/internal/ActivatedSignalType.cs
- src/Tizen.NUI/src/internal/KeyboardEventSignalType.cs
- src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs
- src/Tizen.NUI/src/internal/ManualPINVOKE.cs
- src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/InputMethodContext.cs
1.Refractor ImfManager as a normal class and deprecate it.
2.Add InputMethodContext class to instead of ImfManager.
3.Add GetInputMethodContext api for TextField/TextEditor.
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-143
Added:
TextField.cs:
- InputMethodContext TextField.GetInputMethodContext()
TextEditor.cs:
- InputMethodContext TextEditor.GetInputMethodContext()
InputMethodContext.cs:
- Add new InputMethodContext class.
Changed:
- Change ImfManager as obsoleted class.
> [NUI] Refractor ImfManager to InputMethodContext

- src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
- src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
add API to set audio-only mode
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-138 
Added:
- IsAudioOnly { get; set;} // Property
N/A
> [MediaPlayer] add API to set audio-only mode

- src/Tizen.Security/Tizen.Security/Privilege.cs
Add security.privacy_privilege feature and deprecate redundant API
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-142
- Added security.privacy_privilege feature to:
GetPrivacyDisplayName
GetPrivacyPrivilegeStatus
- Deprecate:
GetPrivacyPrivilegeStatus
If the value of the feature security.privacy_privilege is false then it returns NotSupported exception.
> [Privilege] Add privacy feature and deprecate redundant API

- src/ElmSharp/ElmSharp/Layout.cs
- Rollback bug fix for TCT
- This should not be applied. It is only for version 5.0.
- Change return value from IntPtr.Zero to null
> [ElmSharp] Fix BoxReomve issue

- pkg/Tizen.NET.nuspec
- pkg/runtime.json
Add missing RIDs of Tizen platform. 
- tizen.4.0.0-x86 and tizen.5.0.0-x86, tizen.5.0.0-armel
This is temporary solution, it will be removed when https://github.com/dotnet/corefx/pull/29684 is merged.
> [Build] Add RIDs of Tizen platform to Tizen.NET nuget

- src/Tizen.NUI/src/public/Window.cs
Connect NUI.Window touch event to dali root layer touch event
need to support Motion event (mouse drag)
dali stage's touch motion is never comming, so change the NUI.Window touch event to connect with dali root-layer's touch event
None
None
None
> [NUI] Connect NUI.Window touch event to dali root layer touch event

- src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut/ShortcutManager.cs
- src/Tizen.Applications.Shortcut/interop/Interop.Shortcut.cs
Change the native API to sync.
shortcut_add_to_home -> shortcut_add_to_home_sync
shortcut_add_to_home_widget -> shortcut_add_to_home_widget_sync
shortcut_remove_from_home -> shortcut_remove_from_home_sync
- Crash occured when native code is abnormal.
There was a problem with DotNet_TCT.
> [Shortcut] Update add, delete func

- src/ElmSharp/ElmSharp/EcoreEvent.cs
- src/ElmSharp/Interop/Interop.Ecore.cs
Fix the wrong signature of EcoreEventCallback delegate.
The return type of delegate should be boolean type.
The registered Ecore events invoke without unexpected stop.
None
The registered Ecore events invoke without unexpected stop.
> [ElmSharp] Fix EcoreEventCallback delegate

- src/Tizen.NUI/src/internal/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutGroupWrapper.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutGroupWrapperImpl.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutItemPtr.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutItemWrapper.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutItemWrapperImpl.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutLength.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutMeasureSpec.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutPINVOKE.cs
- src/Tizen.NUI/src/internal/Layouting/LayoutSize.cs
- src/Tizen.NUI/src/internal/Layouting/MeasuredSize.cs
- src/Tizen.NUI/src/internal/ManualPINVOKE.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
from =>
Layouting support in NUI
Change-Id: I3d6f688d869faa81c34385db37feceb1d8c1d0c0
m.umar@partner.samsung.com
from =>
Added LayoutGroup and LayoutItem classes in NUI.
This was done by using bindings wrapper classes for LayoutItem,
LayoutGroup, LayoutMeasureSpec, LayoutLength, and LayoutMeasuredSize.
Change-Id: I19e28bdff59a62cf1c8e8711f50f9f0e8f1c119a
m.umar@partner.samsung.com
None
ACR will be done
These will be public opened in tizen_5.0 after ACR done. 
Before ACR, be hidden as inhouse API by adding '[EditorBrowsable(EditorBrowsableState.Never)]'.
None
> [NUI] Add NUI-Layout

- src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
- src/Tizen.NUI/src/public/BaseComponents/TableView.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseHandle.cs
Add ChildAdded, ChildRemoved, PropertySet events.
TableView.CellPosition class's rowIndex, columnIndex, rowSpan, columnSpan are name changed as Pascal case, and they are all just struct in dali native, so no connection with TableView instance.
making them as read-only properties.
ACR is under progress
None
http://suprem.sec.samsung.net/jira/browse/TCSACR-148
None
> [NUI] Add ChildAdded, ChildRemoved, PropertySet events

- src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/AttachPanel.cs
In public attach-panel API attach_panel_add_content_category(), under CAMERA content, 
Camera app should not be launched if video call is active. To check the status of the video call,
Telephony API (telephony_call_get_type) is called, and telephony privilege is necessary to use telephony API.
List of API changes
API:  public void AddCategory(ContentCategory category, Bundle extraData)
Description: add http://tizen.org/privilege/telephony to use camera content category.
- ACR: TCSACR-150
Added:
- added http://tizen.org/privilege/telephony privilege requirement in API description
/// <privilege>http://tizen.org/privilege/camera</privilege>
+        /// <privilege>http://tizen.org/privilege/telephony</privilege>
/// <privilege>http://tizen.org/privilege/recorder</privilege>
/// …
> [TCSACR-150] Add telephony privilege to use telephony API.

- src/Tizen.NUI/src/internal/AsyncImageLoader.cs
- src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
- src/Tizen.NUI/src/internal/TypeRegistry.cs
- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/PixelBuffer.cs
- src/Tizen.NUI/src/public/Texture.cs
- src/Tizen.NUI/src/public/TransitionData.cs
- src/Tizen.NUI/src/public/VisualBase.cs
Some apis are using DALi internal APIs.
Clean up these wrong apis to prevent future errors.
Signed-off-by: minho.sun <minho.sun@samsung.com>
Remove some apis which are using DALi internal APIs.
- http://suprem.sec.samsung.net/jira/browse/GRE-823
- ACR: Will be prepared.
Removed public APIs which need ACR:
[ViewImpl.cs]
- void AccessibilityActivate() 
- void KeyboardEnter()
- bool EmitKeyEventSignal(Key arg0)
Removed internal APIs which don't need ACR:
[AsyncImageLoader.cs]
- AsyncImageLoader(SWIGTYPE_p_Dali__Toolkit__Internal__AsyncImageLoader impl) : this(NDalicPINVOKE.new_AsyncImageLoader__SWIG_2(SWIGTYPE_p_Dali__Toolkit__Internal__AsyncImageLoader.getCPtr(impl)), true)
[TypeRegistry.cs]
- …
> [NUI] Remove apis which are using internal APIs

- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfileManager.cs
Methods which have no parameter cannot throw ArgumentException.
Therefore ArgumentException description of those APIs need to be removed.
TCSACR-155
http://suprem.sec.samsung.net/jira/browse/TCSACR-156
> [Connection][TCSACR-156] Remove ArgumentException

- src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
- Crash was occured because callback handler was invoked after garbage colleciton.
> [Tizen.Multimedia.Util] Fix callback function lifecycle bug

- src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
BluetoothGattCharacteristic.ValueChanged event always calls back
with a Byte array containing only the first byte of the actual
value. This problem is caused by marshaling the byte array from
the unmanaged C code.
Signed-off-by: Arumoy Biswas <arumoy.b@samsung.com>
Manual marshaling is done in the constructor of ValueChangedEventArgs.
N/A
- ACR: N/A
N/A (Bug fix patchset)
> [Tizen.Network.Bluetooth] Fix ValueChanged callback function bug

- src/Tizen.NUI/src/internal/ManualPINVOKE.cs
- src/Tizen.NUI/src/public/Window.cs
Changed the parameters' type of KeyboardRepeatInfo APIs
-  'double' type -> 'float' type
- N/A
-  ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-152
Changed:
-  bool SetKeyboardRepeatInfo(double rate, double delay) => bool SetKeyboardRepeatInfo(float rate, float delay)
-  bool GetKeyboardRepeatInfo(out double rate, out double delay) => bool GetKeyboardRepeatInfo(out float rate, out float delay)
Changed the parameters' type of SetKeyboardRepeatInfo / GetKeyboardRepeatInfo in Window.cs
- 'double' type -> 'float' type
> [NUI] Change Parameter type of KeyboardRepeatInfo APIs

- src/Tizen.System/Device/Haptic.cs
there is a minor typo in the docs, catch (c# keyword) is spelled with a capital C
no bug listed for that 
no api changes
no behavioral changes
> typo correction

- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/PlaylistCommand.cs
- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/StorageCommand.cs
- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/TagCommand.cs
- Native FW was changed to return error when there's no matched record with playlistId.
So, C# layer should catch the exception to handle it correctly.
> [MediaContent] Added exception handling to catch p/invoke error return

- src/Tizen.Network.Connection/Interop/Interop.Connection.cs
Some APIs which has typo has been deprecated since tizen 4.0.
This patch replaces thease APIs with proper APIs.
- deprecated API: connection_set_ethernet_cable_state_chaged_cb
connection_unset_ethernet_cable_state_chaged_cb
- New API: connection_set_ethernet_cable_state_changed_cb
connection_unset_ethernet_cable_state_changed_cb
- N/A
- N/A
- N/A
> [Connection] Remove deprecated API

- src/ElmSharp/ElmSharp/Spinner.cs
Apply 'vertical' style to Spinner 
- Current abnormal looks on TV
- After applying 'vertical' style on TV
- None
> [ElmSharp] Fix Spinner Style on TV

- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
When an exception in Initialize() happens, GetHandle() is called recursively because s_threadName is not initialized.
> [WiFi] Fix infinite recursion

- src/Tizen.Multimedia.Vision/MediaVision/MovementDetector.cs
- src/Tizen.Multimedia.Vision/MediaVision/PersonAppearanceDetector.cs
- src/Tizen.Multimedia.Vision/MediaVision/PersonRecognizer.cs
- src/Tizen.Multimedia.Vision/MediaVision/SurveillanceEngine.cs
Signed-off-by: Tae-Young Chung <ty83.chung@samsung.com>
- TC is sometimes block because of issue that callback was made on a garbage collected delegate.
- To fix it, declare the member variable for callback.
> [MediaVision] Fix an issue that callback was made on a garbage collected delegate

- src/ElmSharp/ElmSharp/Widget.cs
``` c#
public void SetNextFocusObject(EvasObject next, FocusDirection direction)
```
To allow null value on next parameter, `null` means reset to default
None
None
None
> [ElmSharp] Fix SetNextFocusObject issue

- src/Tizen.Multimedia/Common.Internal/RotationFlip.cs
- src/Tizen.Multimedia/Interop/Interop.MediaTool.cs
- src/Tizen.Multimedia/MediaTool/MediaPacket.cs
Add APIs for rotation and flip. 
Rotation and flip are in same enum at native fw. But, Rotation and Flips enums are already used in Multimedia so we use it.
- TCSACR-174
( It's related with Native ACR-1214.)
Added:
- Rotation { get; set; } // Property
- Flip { get; set; } // Property
> [Multimedia.MediaTool] Add APIs for rotation and flip

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- Prevent creating child Layout automatically in View
- When View is created without new Layout System, LayoutItem should not be created automatically.
- N/A
- Only give children a layout if parent is an explicit layout container
> [NUI] Fix only to give children a layout in an explicit layout

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfo.cs
Some applications may have multiple value for one key.
We use dictionary for application metadata, this can cause an exception.
This fix prevents above exception, but this will cause different
behavior with native API.
N/A
N/A
N/A
> [Applications] Fix a bug when getting application metadata info

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
[NUI] Avoid raising InputMethodContext reference count
Change-Id: I25e89f41daa41008c81ae1b46fbb82c75a98a011
DF180814-00130
N/A
N/A
> [NUI] Avoid raising InputMethodContext reference count

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
Revert "[NUI] Avoid raising InputMethodContext reference count (#459)"
This reverts commit 12a3196fd3f43186573416bf818acaea2254a44c.
the patch makes 100% crash when the SearchAll app ends. 
need to investigate root cause. (now reverting for VD release)
the patch makes 100% crash when the SearchAll app ends. 
need to investigate root cause. (now reverting for VD release)
N/A
N/A
> Revert "[NUI] Avoid raising InputMethodContext reference count (#459)"

- src/Tizen.Security.TEEC/Interop/Interop.Errors.cs
- src/Tizen.Security.TEEC/Tizen.Security.TEEC.csproj
- src/Tizen.Security.TEEC/Tizen.Security.TEEC/Libteec.cs
Signed-off-by: Igor Kotrasinski <i.kotrasinsk@partner.samsung.com>
Check for enablement of http://tizen.org/feature/security.tee before initializing a context. Return a 'not supported' error if it's disabled.
None.
None.
Disabling security.tee feature will cause any attempts to initialize a TEE context to return an error.
> [Tizen.Security.TEEC] Check for TEE feature when creating context

- src/Tizen.Applications.Common/Tizen.Applications/LocaleChangedEventArgs.cs
- src/Tizen.Applications.Common/Tizen.Applications/LowBatteryEventArgs.cs
- src/Tizen.Applications.Common/Tizen.Applications/LowMemoryEventArgs.cs
- src/Tizen.Applications.Common/Tizen.Applications/RegionFormatChangedEventArgs.cs
Fix typo at property description.
`intformation` -> `information`
- N/A
- N/A
- N/A
> [Tizen.Applications] Fix typo

- build/GlobalSuppressions.cs
- build/analyzers.props
- build/common.props
Add GlobalSuppresions.cs file to suppress analyzer warnings on global scope.
> [Build] Add GlobalSuppresions file for TizenFX global scope

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
[NUI] Add BackgroundResourceLoaded,ResourceLoaded events as internal API
N/A
internal events are added, so No ACR is required.
internal event EventHandler<ResourceLoadedEventArgs> ResourceLoaded
internal event EventHandler<BackgroundResourceLoadedEventArgs> BackgroundResourceLoaded
N/A
> [NUI] Add BackgroundResourceLoaded,ResourceLoaded events as internal API

- src/ElmSharp/ElmSharp/GenList.cs
Adds ScrollbarVisiblePolicy to GenList
N/A
Added:
- GenList.HorizontalScrollBarVisiblePolicy { get; set; } // Property
- GenList.VerticalScrollBarVisiblePolicy { get; set; } // Property
None
> [ElmSharp] Adds ScrollbarVisiblePolicy to GenList

- tools/scripts/CodeChecker/main.py
Fix code checker to add warnings only between diff hunk lines.
The code checker used to take one more line as the range of diff hunk lines.
- Fix coner case that adds warning at the out of range.
- N/A
- N/A
> [Tools] Fix code checker

- src/ElmSharp/ElmSharp/Widget.cs
- src/ElmSharp/Interop/Interop.Elementary.cs
Focus is missing when `ElmSharp.SetFocus(false)` is set to an object.
This change applies the work around for clearing focus.
- N/A
- N/A
- When `ElmSharp.SetFocus(false)` is called, the focus is reset to the Window.
> [ElmSharp] Fix Focus Clearing issue

- src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
when source is MediaStreamSource, ObjectKeeper is not active.
so garbage collector sometimes collects callback in use.
this patch is to avoid that case.
> [MediaPlayer] Fix not to set callback in case of using MedaiStreamSource

- src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
Apply GC.SuppressFinalize() in Dispose() method.
The 'disposing' parameter of Dispose() virtual method is also
used for its implementation according to the common usage.
> [AudioManager] Apply GC.SuppressFinalize()

- src/Tizen.Security.PrivacyPrivilegeManager/Interop/Interop.PrivacyPrivilegeManager.cs
- src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security.PrivacyPrivilegeManager.sln
- src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/PermissionRequestResponse.cs
- src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/PrivacyPrivilegeManager.cs
- src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/RequestResponseEventArgs.cs
- src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/RequestResponseMultipleEventArgs.cs
C# bindings for checking & requesting multiple privileges using single API call
- TCSACR-184
(It's related Native ACR-1253.)
Method:
```csharp
public static IEnumerable<CheckResult> CheckPermissions(IEnumerable<string> privileges);
public static Task<RequestMultipleResponseEventArgs> RequestPermissions(IEnumerable<string> privileges);
```
Event:
```csharp
public RequestResult Result { get; internal set; }
public string Privilege { get; internal set; }
```
Property:
```csharp
public PermissionRequestResponse Response { get; }
```
Property:
```csharp
public CallCause Cause { get; internal set; }
public IEnumerable<PermissionRequestResponse> Responses { get; internal set; }
```
> [PrivacyPrivilegeManager] Add new API for checking & requesting multiple privileges

- build.sh
- packaging/csapi-tizenfx.spec
- packaging/csapi-tizenfx.spec.in
- tools/scripts/timeout.sh
Remove retry and timeout command from build.sh. 
This scripts are used in gbs build only. 
- ACR: N/A
> [Build] Remove retry command from build.sh

- build.sh
- packaging/csapi-tizenfx.spec
- packaging/csapi-tizenfx.spec.in
- tools/scripts/timeout.sh
Remove retry and timeout command from build.sh.
This scripts are used in gbs build only.
- ACR: N/A
> [Build] Remove retry command from build.sh (#572)

- src/Tizen.Applications.PackageManager/Interop/Interop.PackageManager.cs
- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Lock internal handle before set/unset event callback
Since native API is not thread-safe, managed code should lock
SafePackageManager handle object before set/unset event callback.
N/A
> [Packagemanager] Lock internal handle before set/unset event callback

- src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
- src/Tizen.NUI/src/public/Window.cs
Add WindowPositionSize property for atomic "move" and "resize" of window.
(in-house only)
- ACR:
> [NUI] Add WindowPositionSize property

- src/Tizen.WebView/Tizen.WebView/SmartCallbackArgs.cs
This patch removes unused API from SmartCallbackArgs.
It will be re-landed when it is needed.
- ACR: N/A
Removed:
- int SmartCallbackArgs.GetAsInteger()
- int SmartCallbackArgs.GetAsDouble()
- int SmartCallbackArgs.GetAsBoolean()
> [WebView] Remove unused API

- src/Tizen.Network.WiFi/Tizen.Network.WiFi/InvalidKeyException.cs
- src/Tizen.Network.WiFi/Tizen.Network.WiFi/NowInProgressException.cs
- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiErrorFactory.cs
- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
- src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
- Add NowInProgressException
- Add InvalidKeyException
- Modification of reference
+ WiFiAP.ConnectAsync() can throw NowInProgressException and InvalidKeyException
+ WiFiAP.ConnectWpsAsync() can throw NowInProgressException and TimeoutException
+ WiFiAP.ConnectConnectWpsWithoutSsidAsyn() can throw NowInProgressException and TimeoutException
+ WiFiManager.ActivateAsync() can throw NowInProgressException
+ WiFiManager.ActivateWithPickerAsync() can throw NowInProgressException
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-203
> [TCSACR-203][WiFi] Add new Exceptions

- src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
Signed-off-by: kibak.yoon <kibak.yoon@samsung.com>
Fix pause policy bug because of mismatched enum index.
SensorPausePolicy enum description is also fixed properly.
None
> Fix pause policy bug because of mismatched enum index (#601)

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Window.cs
1.There's a crash issue on this patch, so reverted it.
The first commit reverts commit ba1de14b8e93135435897c31ebec91bbc6701879.
2. ResizePolicy UseNaturalSize mapped to WrapContent
- N/A
> [NUI] ResizePolicy UseNaturalSize mapped to WrapContent

- src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs
- src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
- It should be 'protected virtual'
Signed-off-by: Junghoon Park <jh9216.park@samsung.com>
Change visibility from private to protected virtual
Changed:
- private void Dispose(bool disposing) => protected virtual void Dispose(bool disposing)
> [Applications] [ProxyBase,StubBase] Fix visibility for method 'Dispose'

- .gitignore
- tools/scripts/CodeChecker/PRManager.py
Use regexp in CodeChecker for parsing the unified diff lines
- ACR: N/A
> [Build] Use regexp in CodeChecker for parsing the unified diff lines

- src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
- src/Tizen.NUI/src/internal/VersionCheck.cs
- src/Tizen.NUI/src/public/NUIApplication.cs
[NUI] Revert "Workaround of Vulkan backend csfs crash issue (#630)"
This reverts commit 88dfb69c07810dc9ec5ae8cdb0340600f7aa323a.
- this crash issue is solved by csfs' change
N/A
> [NUI] Revert "Workaround of Vulkan backend csfs crash issue (#630)"

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
Fix to find non-public constructor by using
CreateInstance(Type type, bool nonPublic) method
with nonPublic=true option.
> [Bluetooth] Fix GetProfile API issue

- src/ElmSharp/ElmSharp/EvasObject.cs
This PR is to modify EvasObjectRealized event triggering time
- ACR: None
> [ElmSharp] Modify EvasObjectRealized event triggering time

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
To avoid ArgumentNullException, we have to check the args before calling
base.Run().
This patch is for checking args parameter before calling base.run().
Currently, if args is null, ArgumentNullException can be occurred.
- ACR: Not Required
> [Applications] Fix static analysis issue

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
If args is null, throwing ArgumentNullException is occurred.
The null check logic is unnecessary. It's removed.
This patch checks the length of args before copying args.
Checking the length of args is added instead of unnecessary check null logic.
- ACR:Not required
> [Applications] Modify args handling

- src/Tizen.Applications.WatchApplication/Tizen.Applications.CoreBackend/WatchCoreBackend.cs
- src/Tizen.Applications.WidgetApplication/Tizen.Applications.CoreBackend/WidgetCoreBackend.cs
- Set SynchronizationContext on WidgetCoreBackend.Run
- Set SynchronizationContext on WatchCoreBackend.Run
Fix https://github.com/Samsung/TizenFX/issues/628
- ACR:
> [Application] Fix SynchronizationContext issue

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Reverts Samsung/TizenFX#659
It cause behavior change
and It is **NOT** issue throwing exception when args was null
If you want to allow null reference on args, 
please fix below code
https://github.com/Samsung/TizenFX/blob/e3ef2c83139d7f3985809aa2ac5be8a740b520dd/src/Tizen.Applications.Common/Tizen.Applications/Application.cs#L121-L124
> Revert "[Applications] Fix static analysis issue"

- src/Tizen.Pims.Calendar/Tizen.Pims.Calendar/CalendarStructs.cs
Just added a null check before using the variable.
- ACR:
> [Calendar] Fix svace defect  WGID#14567

- src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
- src/Tizen.NUI/src/internal/WebView.cs
This API provides a method of c# delegate injection to JavaScript
- ACR:
> [NUI] Add |AddJavaScriptInterface| API for WebView

- src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
The GATT write value requested callback's parameter order was wrong.
Because of this, the application gets abnormal information.
The Native API's  callback function is next.
https://developer.tizen.org/development/api-references/native-application?redirect=https://developer.tizen.org/dev-guide/5.0.0/org.tizen.native.mobile.apireference/group__CAPI__NETWORK__BLUETOOTH__GATT__SERVER__MODULE.html#gafe3d11f3bf2c628152ee5b5d5342177a
typedef void (*bt_gatt_server_write_value_requested_cb) (const char *remote_address,
int request_id, bt_gatt_server_h server,
bt_gatt_h gatt_handle, bool response_needed, int offset,
const char *value, int len, void *user_data);
- ACR: No ACR
> [Bluetooth] Fix the wirte value request callback's parameter order (#678)

- src/ElmSharp/ElmSharp/ColorSelector.cs
- src/ElmSharp/ElmSharp/ColorSelectorItem.cs
- src/ElmSharp/ElmSharp/ContextPopup.cs
- src/ElmSharp/ElmSharp/ContextPopupItem.cs
- src/ElmSharp/ElmSharp/Elementary.cs
- src/ElmSharp/ElmSharp/FlipSelector.cs
- src/ElmSharp/ElmSharp/FlipSelectorItem.cs
- src/ElmSharp/ElmSharp/GenGrid.cs
- src/ElmSharp/ElmSharp/GenGridItem.cs
- src/ElmSharp/ElmSharp/GenItem.cs
- src/ElmSharp/ElmSharp/GenList.cs
- src/ElmSharp/ElmSharp/GenListItem.cs
- src/ElmSharp/ElmSharp/Hoversel.cs
- src/ElmSharp/ElmSharp/HoverselItem.cs
- src/ElmSharp/ElmSharp/Index.cs
- src/ElmSharp/ElmSharp/IndexItem.cs
- src/ElmSharp/ElmSharp/ItemObject.cs
- src/ElmSharp/ElmSharp/List.cs
- src/ElmSharp/ElmSharp/ListItem.cs
- src/ElmSharp/ElmSharp/MultiButtonEntry.cs
- src/ElmSharp/ElmSharp/MultiButtonEntryItem.cs
- src/ElmSharp/ElmSharp/NaviItem.cs
- src/ElmSharp/ElmSharp/Naviframe.cs
- src/ElmSharp/ElmSharp/Popup.cs
- src/ElmSharp/ElmSharp/PopupItem.cs
- src/ElmSharp/ElmSharp/Toolbar.cs
- src/ElmSharp/ElmSharp/ToolbarItem.cs
- test/ElmSharp.Test/TestRunner.cs
Added API for `parent` of `ItemObject`
- public EvasObject ItemObject.Parent { get; internal set; }
- protected ItemObject(IntPtr handle, EvasObject parent)
- public FlipSelectorItem(string text, EvasObject parent)
- public IndexItem(string text, EvasObject parent)
Added API for new event for automation test.
- public event Elementry.ItemObjectRealized
> [ElmSharp] Added Parent property to ItemObject and new event for automation test

- src/ElmSharp/ElmSharp/EcoreMainloop.cs
EcoreMainloop.PostAndWakeUp behavior is changed
- as is 
it synchronously called when called on main loop thread
- to be
it called asynchronously when called on main loop thread
fixes : https://github.com/Samsung/TizenFX/issues/694
> [ElmSharp] Fix EcoreMainloop PostAndWakeUp behavior

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothServerSocket.cs
AcceptStateChanged callback is not invoked in application. Because the static callback is not added by default.
- ACR: N/A
> [Bluetooth] Fix the socket callback issue

- src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
- src/Tizen.Multimedia/Interop/Interop.StreamPolicy.cs
Add **HasStreamOnDevice** method to AudioStreamPolicy class. This functionality has already exist in NativeAPI since Tizen 3.0.
It checks whether if any stream from the current AudioStreamPolicy is using the device.
- ACR: TCSACR-220
> [AudioManager] Add HasStreamOnDevice method to AudioStreamPolicy

- src/ElmSharp/ElmSharp/EvasObject.cs
- src/ElmSharp/ElmSharp/EvasObjectEvent.cs
- src/ElmSharp/ElmSharp/Image.cs
- src/ElmSharp/ElmSharp/SmartEvent.cs
* Dispose SmartEvent object on LoadAsync method with using block
* When SmartEvent was disposed, remove from EventLifeTracker to quickly released by GC
* Fix https://github.com/Samsung/TizenFX/issues/719
None
> [ElmSharp] Fix memory leak on Image.LoadAsync method

- src/ElmSharp.Wearable/ElmSharp.Wearable/CircleDatetimeSelector.cs
- src/ElmSharp.Wearable/ElmSharp.Wearable/CircleSpinner.cs
I add obsolete and remark for marker API because efl will not support marker in CircleDateTime and CircleSpinner.
- ACR: N/A
> [Elmsharp.Wearable][Non-ACR] Add obsolete and remark for marker API

- src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
- src/Tizen.NUI/src/public/Key.cs
The  user can get 'LogicalKey' and 'KeyPressed' information of Key Event.
These will be public opened in tizen_5.5 after ACR done. Before ACR, need to be hidden as inhouse API.
Added:
- public string LogicalKey
- public string KeyPressed
> [NUI] Add to get LogicalKey and KeyPressed

- src/Tizen.NUI/src/internal/WebView.cs
JavaScriptMessageHandler delegate instances are collectable by GC,
so the concrete root for those instants are needed.
- ACR:
> [NUI] Fix NUI.WebView concerned with GC

- src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/PasswordPolicy.cs
This property was included in TCSACR-211. The API has not been opened yet and used yet. so It does not create new ACR. (This is confirmed)
Fix typo of property name in PasswordPolicy.
MinimunLength -> MinimumLength
- ACR: TCSACR-211
> [DevicePolicyManager] Fix typo of property name

- src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerPlaylist.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaControlPlaylist.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
1. Remove useless SavePlaylist() method call.
2. Fix return type of foreach callback function and its behavior.
* It's merged in master branch already.
> [MediaController] Remove useless method call and fix the bug of foreach method

- src/Tizen.WebView/Interop/Interop.ChromiumEwk.Settings.cs
- src/Tizen.WebView/Tizen.WebView/Settings.cs
[WebView] [TCSACR-219] Add WebView Settings API
Signed-off-by: basavarajps <basavaraj.ps@samsung.com>
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-219
> [WebView] [TCSACR-219] Add WebView Settings API

- src/Tizen.Multimedia.Util/ImageUtil/ImageUtil.cs
Deprecate useless `CalculateBufferSize` method.
C# API allocate buffer in managed memory with the size returning in native.
- TCSACR-241
> [ImageUtil] Deprecate useless CalculateBufferSize

- src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
[MediaPlayer] Modify the pre-condition of streaming function
Extend pre-condition include READY state so that the application could get buffering progress more earlier just right after calling Prepare.
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-242
Changed :
Added PlayerState.Ready State
public DownloadProgress GetDownloadProgress()
> [MediaPlayer] Modify the pre-condition of streaming function

- src/Tizen.WebView/Interop/Interop.Eina.cs
- src/Tizen.WebView/Tizen.WebView/BackForwardList.cs
Signed-off-by: yh106.jung <yh106.jung@samsung.com>
We cannot invoke eina_list_count because it is inline, so this patch replaces eina_list_* with eina_iterator_*.
- ACR:
> [WebView] Replace eina_list_* with eina_iterator_*

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView.cs
- src/Tizen.NUI/src/internal/WebViewPageLoadErrorEventArgs.cs
- src/Tizen.NUI/src/internal/WebViewPageLoadErrorSignal.cs
- src/Tizen.NUI/src/internal/WebViewPageLoadEventArgs.cs
- src/Tizen.NUI/src/internal/WebViewPageLoadSignal.cs
- src/Tizen.NUI/src/public/NUIConstants.cs
Add Properties
* CACHE_MODEL
* COOKIE_ACCEPT_POLICY
* USER_AGENT
* JAVASCRIPT_ENABLED
* LOAD_IMAGE_AUTOMATICALLY
* DEFAULT_TEXT_ENCODING_NAME
* DEFAULT_FONT_SIZE
Add Signals
* PageLoadErrorSignal
Add Methods
* Suspend
* Resume
* ClearCookies
- ACR:
> [NUI] Implement WebView APIs

- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
PackageManagerEventCallback could be lost in
multi-thread environment. So we need to add lock not to lost it.
> [PackageManager] Fix thread safety issue

- src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/CodeGrantAuthorizer.cs
- src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ImplicitGrantAuthorizer.cs
This commit fixes documentation issues found in PR #849
> [OAuth2] Remove reference to AuthorizeAsync method from documentation

- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Folder.cs
- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfo.cs
- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/QueryArguments.cs
- src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Storage.cs
- src/Tizen.Multimedia.Metadata/MetadataExtractor/Metadata.cs
- src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.Events.cs
- src/Tizen.Multimedia/AudioManager/AudioManager.cs
- src/Tizen.Multimedia/Interop/Interop.Device.cs
Suppress CS0618(Type or member is obsolete) warnings due to internal reference
- ACR:
> [Build] Suppress CS0618 warnings due to internal reference

- src/Tizen.NUI.Xaml/src/internal/Xaml/CreateValuesVisitor.cs
| Code | XAML |
| -- | -- |
| public MyClass() | \<MyClass \/\> |
| public MyClass(MyType1 para1 = "para1") | \<MyClass \/\>or\<MyClass\>\<x:Arguments\>\<MyType1\>para1\<MyType1\/\>\<\/x:Arguments\>\<MyClass\/\> |
| public MyClass(MyType1 para1, MyType2 para2 = "para2") | \<MyClass\>    \<x:Arguments\>\<MyType1\>para1\<\/MyType1\>\<\/x:Arguments\>\<\/MyClass\>or\<MyClass\>    \<x:Arguments\>        \<MyType1\>para1\<\/MyType1\>        \<MyType2\>para2\<\/MyType2\>    \<\/x:Arguments\>\<\/MyClass\> |
| public MyClass(MyType1 para1 = "para1", MyType2 para2 = "para2") | \<MyClass \/\>or\<MyClass\>    \<x:Arguments\>        \<MyType1\>para1\<\/MyType1\>    \<\/x:Arguments\>\<MyClass\/\>or\<MyClass\>    \<x:Arguments\>        \<MyType1\>para1\<\/MyType1\>        \<MyType2\>para2\<\/MyType2\>  …
> [NUI] To support constructor with default parameters

- src/Tizen.Applications.Common/Interop/Interop.ApplicationManager.cs
The component ID element was added on the rua_rec structure.
The RecentApplicationInfo is not working fine. If an application uses the class, it will be crashed.
- ACR:
> [Applications][Common] Fix RuaRec structure

- src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
| Code | XAML |
| -- | -- |
| public MyClass() | \<MyClass \/\> |
| public MyClass(MyType1 para1 = "para1") | \<MyClass \/\>or\<MyClass\>\<x:Arguments\>\<MyType1\>para1\<MyType1\/\>\<\/x:Arguments\>\<MyClass\/\> |
| public MyClass(MyType1 para1, MyType2 para2 = "para2") | \<MyClass\>    \<x:Arguments\>\<MyType1\>para1\<\/MyType1\>\<\/x:Arguments\>\<\/MyClass\>or\<MyClass\>    \<x:Arguments\>        \<MyType1\>para1\<\/MyType1\>        \<MyType2\>para2\<\/MyType2\>    \<\/x:Arguments\>\<\/MyClass\> |
| public MyClass(MyType1 para1 = "para1", MyType2 para2 = "para2") | \<MyClass \/\>or\<MyClass\>    \<x:Arguments\>        \<MyType1\>para1\<\/MyType1\>    \<\/x:Arguments\>\<MyClass\/\>or\<MyClass\>    \<x:Arguments\>        \<MyType1\>para1\<\/MyType1\>        \<MyType2\>para2\<\/MyType2\>  …
> [NUI] Support constructor with default parameter

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
If the interval is less than or equal to zero, or greater than integer
maximum value, ArgumentException is occurred.
To avoid ArgumentException, we have to check whether the interval value is less than zero or NOT.
> [Applications.Common] Add an exception

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
If the interval is less than or equal to zero, or greater than integer
maximum value, ArgumentException is occurred.
To avoid ArgumentException, we have to check whether the interval value is less than zero or NOT.
> [Applications.Common] Add an exception 

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
[NUI] Temporary checking if Lottie file is set in ImageView
None
> [NUI] Temporary checking if Lottie file is set in ImageView

- src/Tizen.NUI/src/internal/ContentReceivedSignalType.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ContentReceivedSignalType.cs
- src/Tizen.NUI/src/internal/Interop/Interop.InputMethodContext.cs
- src/Tizen.NUI/src/public/InputMethodContext.cs
- Added an API to set the allowed MIME type to deliver to the input panel.
- Added a callback to receive the content of the input method URI. 
Added:
- public event EventHandler<ContentReceivedEventArgs> ContentReceived { add; remove; }
- public void SetMIMEType(string mimeType);
- public class ContentReceivedEventArgs : EventArgs {}
> [NUI] Add to set MIME type to the input panel and its callback

- src/Tizen.NUI/src/internal/Interop/Interop.Key.cs
- src/Tizen.NUI/src/public/Key.cs
Change-Id: I5aa3680b81cc62d6718aa0f21a08bc7c74b8826b
- Provide to use 'KeyString' for a clearer meaning instead of 'KeyPressed'
Added:
- public string KeyString { get; }
> [NUI] Add KeyString in Key.cs

- src/ElmSharp/ElmSharp/ContextPopup.cs
- src/ElmSharp/Interop/Interop.Elementary.CtxPopup.cs
According to native API changes, `ElmSharp.ContextPopup.IsAvailableDirection` has been obsoleted.
- ACR: ACR-319
```
elementary: remove deprecated API
Following API was deprecated from 2.4.
- elm_ctxpopup_direction_available_get (ACR-319)
```
Obsoleted:
- bool ElmSharp.ContextPopup.IsAvailableDirection
> [ElmSharp] Obsolete ContextPopup.IsAvailableDirection

- internals/src/EflSharp/EflSharp/Circle/MoreOption.cs
- internals/src/EflSharp/EflSharp/Circle/RotarySelector.cs
Now, EoWrapper does not have constructor with parameter IntPtr.
Instead, EoWrapper has constructors with paramater ConstructingHandle
and WrappingHandle.
Since ConstructingHandle is created internally, the constructor with
parameter ConstructingHandle should be used for internal usage.
Instead, constructor with parameter WrappingHandle should be used to use
C native handle (i.e. eo pointer in C).
- ACR:
> [EflSharp] Fix constructor of MoreOption and RotarySelector

- src/Tizen.Multimedia/AudioManager/AudioDeviceType.cs
Add Network type to Tizen.Multimedia.AudioDeviceType enumeration.
- ACR: TCSACR-263
> [AudioManager] Add 'Network' audio device type

- src/Tizen.PhonenumberUtils/Tizen.PhonenumberUtils/PhonenumberUtilsEnumerations.cs
Changed the name of Taiwan and Hong Kong to "Chinese Taiwan" and "Chinese Hong Kong" as per request in the Enum.
> change province name in language enum

- src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
- src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs
- src/Tizen.Multimedia.MediaPlayer/Player/AudioOffload.cs
- src/Tizen.Multimedia.MediaPlayer/Player/EqualizerBand.cs
- src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
- src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
- src/Tizen.Multimedia.MediaPlayer/Player/PlayerFeatures.cs
- src/Tizen.Multimedia.MediaPlayer/Player/PlayerTrackInfo.cs
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-262
If you can't make the ACR, List all API changes here (or just put None), example:
Added:
- public class AudioOffload
- public bool IsEnabled
- public bool IsActivated
- public IEnumerable<MediaFormatAudioMimeType> SupportedFormats
- public AudioOffload AudioOffload
Changed:  : the error case is added. when audio offload is set, invalid operation occurs for the below APIs
(AudioEffect.cs)
public EqualizerBand this[int index]
public void Clear()
public int Count
public Range BandLevelRange
public bool IsAvailable
(EqualizerBand.cs)
public int Level
public int Frequency
public int FrequencyRange
(Player.Properties.cs)
public AudioLatencyMode AudioLatencyMode
public bool ReplayGain
public bool AudioPitchEnabled
public float …
> [MediaPlayer] add APIs to use AudioOffload

- src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
- src/Tizen.Multimedia/Interop/Interop.StreamPolicy.cs
Add two properties to AudioStreamPolicy.
These properties are to set a specific built-in device when the system has multiple devices of the same built-in device type.
- ACR: TCSACR-269
> [AudioManager] Add properties for the preferred device

- src/Tizen.Applications.Common/Interop/Interop.AppControl.cs
- src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
This property is for getting and setting a component ID.
<class>
AppControl
<property>
+ string ComponentID { get; set; }
- ACR: TCSACR-277
> [Applications.Common] Add a new property of AppControl

- src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WindowInternal.cs
- src/Tizen.NUI/src/public/Window.cs
Change rotation APIs from internal to public.
- AddAvailableOrientation, RemoveAvailableOrientation, SetPreferredOrientation, GetPreferredOrientation
This will be public opened in tizen_5.5 after ACR done. Before ACR, need to be hidden as inhouse API.
- ACR:
> [NUI] Change rotation APIs from internal to public

- src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentManager.cs
To prevent null reference exception, checking a parameter is necessary.
> [ComponentBased.ComponentManager][Adds an exception handling]

- src/Tizen.Multimedia/AudioManager/AudioDucking.cs
- src/Tizen.Multimedia/Interop/Interop.Ducking.cs
Fix crash issue when callback is invoked from native.
- SafeHandle cannot be used in callback parameter from unmanaged.
> [AudioManager] Changed handle type to marshal from unmanaged

- src/Tizen.NUI/src/internal/Application.cs
- src/Tizen.NUI/src/public/Window.cs
- Modify GetWindowList for getting Native Ptr
- Set Window name when creating window using window name
- ACR:
> [NUI] Modify GetWindowList for getting Native Ptr

- src/Tizen.Network.IoTConnectivity/Tizen.Network.IoTConnectivity/RemoteResource.cs
Change-Id: I5f9ba403661e32f2f6ed807318cc937b8137cfc9
Signed-off-by: Semun Lee <semun.lee@samsung.com>
Dictionary for native callbacks was not properly managed. key of the dictionary was not static but dictionary was static. 
Changed to use ConcurrentDictionary instead of Dictionary and make the dictionary not to be static.
N/A
> [IoTConnectivity] Fix wrong callback management

- packaging/PlatformFileList.txt
- src/Tizen.Network.Stc/Tizen.Network.Stc.sln
Description of Changes
1. [Network.Stc] Add project dependencies in Solution file
This patch adds dependencies of Tizen and Tizen.log project so that Tizen.Network.Stc can build standalone.
2. [Network.Stc] Update PlatformFileList
This patch adds "Tizen.Network.Stc.dll" in PlatformFileList.txt.
> [Network.Stc] Fix Build issue and Update PlatformFileList

- src/Tizen.NUI/src/public/Key.cs
- Should return 'ret' value of string type. It was changed probably by a mistake.
- N/A
> [NUI] Fix the return value of logicalKey

- src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs
- src/Tizen.Multimedia.MediaPlayer/Player/AudioOffload.cs
- src/Tizen.Multimedia.MediaPlayer/Player/EqualizerBand.cs
- src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
- src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
- src/Tizen.Multimedia.MediaPlayer/Player/PlayerTrackInfo.cs
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-284
▶Change
It works even though AudioOffload is enabled.
(AudioEffect.cs)
public bool IsAvailable
-----------------
▶Change
InvalidOperation will be removed and NotAvailableException will be returned instead of it.
(AudioEffect.cs)
public EqualizerBand this[int index]
(EqualizerBand.cs)
public int Level
public int Frequency
public int FrequencyRange
(Player.Properties.cs)
public AudioLatencyMode AudioLatencyMode
(PlayerTrackInfo.cs)
public int GetCount()
-----------------
▶Change
if AudioOffload is enabled, NotAvailableException is returned instead of InvalidOperation exception.
(AudioEffect.cs)
public void Clear()
public int Count
public Range BandLevelRange
(Player.Properties.cs)
public bool ReplayGain
public bool …
> [MediaPlayer] change the error code related with AudioOffload

- src/Tizen.NUI/src/public/PropertyBuffer.cs
[NUI] Removing PropertyBuffer.SetData()'s obsolete attribute before adding new replacing API
None
> [NUI] Removing PropertyBuffer.SetData()'s obsolete attribute

- src/Tizen.Network.Connection/Interop/Interop.Connection.cs
- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
Native capi, capi-network-connection is revised for multi-thread safety.
ConnectionInternalManager used ManagedThreadId to initialize and deinitialize connection capi because connection capi managed handles as thread local and there was a crash issue when C# GC tries to deinitialize the handle used by C#.
For now, capi-network-connection handles this issue.
https://review.tizen.org/gerrit/#/c/platform/core/api/connection/+/203344/
> [Tizen.Network.Connection] Init/deinit without ManagedThreadId

- src/Tizen.Telephony/Tizen.Telephony/Modem.cs
- src/Tizen.Telephony/Tizen.Telephony/Sim.cs
Change privlevel and privilege of non-resettable device IDs  
- IMEI, MEID and ICCID are not getting by 3rd party application anymore. 
- The partner privlevel application can read these information with new privilege as http://tizen.org/privilege/securesysteminfo.
- For an application with API version 6 or higher, 
if an application doesn't have http://tizen.org/privilege/securesysteminfo privilege, it sets with empty string.
- For an application with API version lower than 6. 
if an application has http://tizen.org/privilege/telephony privilege, it sets with a pseudo value.
- ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-288
> Apply TCSACR-288 Tizen.Telephony

- src/Tizen.Network.IoTConnectivity/Tizen.Network.IoTConnectivity/RemoteResource.cs
We should prevent the crash in next exception case.
Unhandled exception.
System.Collections.Generic.KeyNotFoundException: The given key '2' was not present in the dictionary.
at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
at Tizen.Network.IoTConnectivity.RemoteResource.NativePutResultCallbackHandler(IntPtr resource, Int32 err, Int32 requestType, IntPtr responseHandle, IntPtr userData)
- ACR:
> [IoTConnectivity] Handle the exception for getting Dictionary item

- test/NUITestSample/NUITestSample/examples/text-test2.cs
- Remove to use "IME_F31" in NUI test sample
- N/A
> [NUI] Remove IME_F31 PredictiveString in NUI sample

- src/Tizen.NUI/src/internal/WidgetApplication.cs
- src/Tizen.NUI/src/public/NUIWidgetApplication.cs
Add new constructor for multi widget.
Previously, NUIWidgetApplication had constructor for single widget.
Now, we can support multi widget so add constructor for this.
Added:
- public NUIWidgetApplication(Dictionary<System.Type, string> widgetTypes) : base(new NUIWidgetCoreBackend())
> [NUI] NUIWidgetApplication constructor for multi widget

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- HeightSpecification of View opens public in API level 6.
- Please have a look at TCSACR-278
- N/A
> [NUI] Remove 'EditorBrowsable' to HeightSpecification

- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Do not restrict Layouts to their parent size at most unless
explictly requested to MatchParent
Needed so a layout can to scroll within it's smaller parent, otherwise larger child would be restricted to parents size.
Change-Id: Id2d84601a9b1d2956636b6d5f9334eefb5f0e9c0
- ACR:
> [NUI] Layouts not restricted to parents size as default

- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
Change-Id: I3e900c09df94d19b93d35d5bf947a99cefd5337b
Previously CustomViews returned zero for NaturalSize.
Now return the size set if NaturalSize not overridden.
In the case of Controls derived from CustomView that have their size explicitly set via the View API, that size is returned as the NaturalSize, not the size that may have been set internally by native code.
- ACR:
> [NUI] NaturalSize returns size set instead of Zero for CustomViews

- src/Tizen.NUI.Components/Attributes/ViewAttributes.cs
- src/Tizen.NUI.Components/Controls/DropDown.cs
Change-Id: I8f03e40985b58715b7f80fe2a84bb508a0346608
Fix crash that occurs if Padding attribute not set in DropDownButtonAttributes.
> [NUI] Fix attributes crash when Padding not set

- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference.csproj
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference.sln
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Commons.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/SingleShot.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsData.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsInfo.cs
If machine_learning.inference is false or does not exist, or NNStreamer
installed on target device, NotSupportedException occurs when calling
the C# API of MachineLearning Inference.
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>
* No API Changes
> [NoACR][MachineLearning.Inference] NotSupportedException support

- src/Tizen.WebView/Interop/Interop.ChromiumEwk.cs
- src/Tizen.WebView/Tizen.WebView/Chromium.cs
This patch adds Chromium.SetArguments that can be used to set
Chromium's commandline switches.
> [WebView] Add Chromium.SetArguments

- src/Tizen.NUI/src/internal/Layouting/Interop/Interop.FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Change-Id: Ie661294a155fb4cf971ddb96bba30472fb80168b
Below Fixes for FlexLayout
Fix Interops returning IntPtrs instead of floats
Fix measured child size when natural size zero.
Add Undefined constant map WrapContent to
example FlexListExample.cs -> https://github.com/dalihub/nui-demo/tree/flexList
- ACR:
> [NUI] FlexLayout Interop and Undefined fixes

- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
#516 # Description of Change ###
LayoutGroup measuring child without using the parent's padding.
Resulted in LinearLayout not reducing the childs size when padding applied to parent
Issue #2 of Layouts bug reported.
- ACR:
> [NUI] Padding bug in LayoutGroup fixed

- src/Tizen.NUI/src/public/BaseComponents/View.cs
Change-Id: I80a4e1166f35e4c09c116916262ac965de54b048
When setting the WidthSpecification or HeightSpecification with an exact value
the Size.Width or Size.Height is set but this in turns triggers a callback which
sets Size(width,height) but uses the stored height or width value which may not be
the set Width or Height Specification hence sets them to 0;
- ACR:
> [NUI] Prevent Height and Width specs being overwritten

- src/Tizen.NUI/src/internal/CustomAlgorithmInterface.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ImageLoading.cs
- test/NUITestSample/NUITestSample/examples/GetOriginalImageSizeTest.cs
[NUI] Workaround: fix CustomAlgorithmInterface crash error occurred only in emulator, will be removed later after a proper solution is found
- fix CSharp_Dali_GetOriginalImageSize spelling error.
- add "GetOriginalImageSizeTest.cs" as sample APP.
Nothing
> [NUI] Workaround: fix CustomAlgorithmInterface crash error

- src/Tizen.Sensor/Tizen.Sensor/EventArgs/AutoRotationSensorDataUpdatedEventArgs.cs
- src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
- src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
Add auto-rotation sensor API to c # API internally
- ACR:
> [Sensor] Add rotation sensor internal API

- src/Tizen.NUI/src/public/LongPressGestureDetector.cs
- src/Tizen.NUI/src/public/PanGestureDetector.cs
- src/Tizen.NUI/src/public/PinchGestureDetector.cs
- src/Tizen.NUI/src/public/RotationGestureDetector.cs
- src/Tizen.NUI/src/public/TapGestureDetector.cs
Support adding multiple callback to gesture event.
Previously, developer can add only one callback function to gesture detected event.
Now, can add multiple callback to gesture event.
> [NUI] Support adding multiple callback to gesture

- src/Tizen.NUI/src/public/Window.cs
[NUI] Add NoOrientationPreference
Add NoOrientationPreference to WindowOrientation enum.
It is used to unset the preferred orientation with SetPreferredOrientation.
API Changes
Nothing
> [NUI] Add NoOrientationPreference

- src/ElmSharp/ElmSharp/Elementary.cs
- src/ElmSharp/ElmSharp/PreloadedWindow.cs
- src/ElmSharp/ElmSharp/Window.cs
This PR enables two more preloading options on `PreloadedWindow`.
- Preloading widgets which are used when initializing Xamarin Forms Tizen platform renderers.
- `Entry`
- `Scroller`
- `Box`
- `Label`
- `GenList`
- `Button`
- `Check`
- `Naviframe`
- `Slider`
- `Spinner`
- `ProgressBar`
- `GestureLayer`
- `Polygon`
- `Image`
- Preloading events which are used at application launching time.
- `PreloadedWindow.BackButtonPressed`
N/A
> [ElmSharp] Add more preloading components

- src/Tizen.Applications.WidgetApplication/Interop/Interop.Widget.cs
- src/Tizen.Applications.WidgetApplication/Tizen.Applications/WidgetType.cs
Fix https://github.com/Samsung/TizenFX/issues/1150
- ACR:
> [Application] Fix widget instance id bug

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
When using GridLayout view with ScrollableBase, it cannot be scrolled.
It cauesd by wrong height measurement and it only happend when setting
WrapContent to layout view.
Save measurement result when using WrapContent.
NONE
> [NUI] Fixed GridLayout scrolling issue

- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
If a child is added to a different layout the transition finished
animation can cause it to be removed from the new parent.
Cause : The removal animation is added to the stack, the add animation is added to
the stack.  Animations are run.  When animations finish the itemRemovalQueue is run, this
removes the child as the removal code added it to the itemRemovalQueue.
Fix : In the case of replacement, set a flag on the child so the removal code can excluded it
from the itemRemovalQueue.
Change-Id: Ib7da9e446c990258c8415e584bbb624dae4d6fa5
- ACR:
> [NUI] Fix reparenting of Child bug

- src/Tizen.NUI/src/public/Timer.cs
[NUI] Add dispose checking in just a few methods of Timer class
- DF191218-00096 defect seems to be caused by the wrong handling of object which has been disposed, specially Timer object.
- Adding defensive check routine whether the Timer object is disposed or not.
- Just added in a few methods of Timer class so that there will be no overhead.
nothing
> [NUI] Add dispose checking in just a few methods of Timer class

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
[NUI] Fix AlphaMaskUrl setting order problem
- adding private variable of _alphaMaskUrl.
- if _alphaMaskUrl is set once, AlphaMaskUrl property is added always in PropertyMap of UpdateImage()
nothing
> [NUI] Fix AlphaMaskUrl setting order problem

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs
[NUI] Fix Tizen.NUI.Samples crash error when it is terminated
- When NUIApplication is terminated, Dispose() is not needed, but Exit() needs to be called.
nothing
> [NUI] Fix Tizen.NUI.Samples crash error when it is terminated

- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Currently, GridLayout measures only first child for calculation so other child cannot layout its children.
Now, GridLayout measures whole child so they can layout its children.
NONE
> [NUI] Measure whole child in GridLayout

- src/Tizen.NUI/src/public/Animation.cs
[NUI] Fix Animation Dispose() to make local variable of Animation instance make working properly
- NUI Animation class is binding to DALi native Animation class.
- Animation class inherits from BaseHandle class so it has a reference count.
- In NUI side, if the Animation class is instanced in local scope, it is disposed automatically by DisposeQueue. Here the reference count of native DALi Animation is decreased and it will be managed by smart pointer so this is not a matter in NUI side.
- NUI Animation Dispose() need care only the events which are connected to native DALi, so event handlers of Finished and ProgressReached are certainly disconnected.
- Animation which has been created as local variable will work properly. (ex: if LoopCount is set to 100 and it is even local variable, it …
> [NUI] Fix Animation Dispose() to make local variable of Animation instance make working properly

- src/Tizen.Applications.WidgetApplication/Interop/Interop.Widget.cs
- src/Tizen.Applications.WidgetApplication/Tizen.Applications/WidgetType.cs
* Fix widget instance id bug
* Update Introp method name
- ACR:
> [Application] Fix widget instance id bug (#1197)

- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI/src/public/Visuals/TextVisual.cs
* Fix ths issue that the VisualMap does not tranform
* Fix TextVisual crash issue
- ACR:
> [NUI] Fix visual bugs

- src/ElmSharp/ElmSharp/Elementary.cs
- src/ElmSharp/ElmSharp/PreloadedWindow.cs
- src/ElmSharp/ElmSharp/Window.cs
This PR applies two more preloading options on PreloadedWindow which has already been applied on  https://github.com/Samsung/TizenFX/pull/1255.
- Preloading widgets which are used when initializing Xamarin Forms Tizen platform renderers.
- Preloading events which are used at application launching time.
- N/A
> [ElmSharp] Apply preloading on API7

- src/ElmSharp/ElmSharp/Elementary.cs
- src/ElmSharp/ElmSharp/PreloadedWindow.cs
- src/ElmSharp/ElmSharp/Window.cs
This PR applies two more preloading options on PreloadedWindow which has already been applied on  https://github.com/Samsung/TizenFX/pull/1255.
- Preloading widgets which are used when initializing Xamarin Forms Tizen platform renderers.
- Preloading events which are used at application launching time.
- N/A
> [ElmSharp] Add preloading on API8

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Previously, children in FlexLayout were not measured but just returning NaturalSize.
To support nested Layout, FlexLayout also should measure Layout of its children.
Now, FlexLayout measures its children and it also can fix MatchParent issue in FlexLayout.
NONE
> [NUI] Measure Child's Layout in FlexLayout

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationComponentType.cs
Adds:
- ComponentBasedApplication
From Tizen 5.5, platform supports a new application model that is component-based application.
ComponentBasedApplication is added on ApplicationComponentType.
- ACR: TCSACR-304
Added:
- ApplicationComponentType.ComponentBasedApplication // enumeration
> [Applications.Common] Add a new element on ApplicationComponentType

- src/Tizen.Applications.Common/Tizen.Applications/ApplicationComponentType.cs
Adds:
- ComponentBasedApplication
From Tizen 5.5, platform supports a new application model that is component-based application.
ComponentBasedApplication is added on ApplicationComponentType.
- ACR: TCSACR-304
Added:
- ApplicationComponentType.ComponentBasedApplication // enumeration
> [Applications.Common] Add a new element of ApplicationComponentType

- src/ElmSharp/ElmSharp/GestureLayer.cs
- src/ElmSharp/Interop/Interop.Elementary.GestureLayer.cs
Fix internal implementation related with GetstureLayer native callback
- ACR: None
> [ElmSharp] Fix GestureLayer native callback return type

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
NumberOfPage was draft property to know how many pages user wants.
For now, NumberOfPage is replaced to the count of container children.
PageWidth was draft property to know how big one page is.
For now, PageWidth will be automatically set to width of ScrollableBase.
NONE
> [NUI] Remove draft property in ScrollableBase

- src/ElmSharp/ElmSharp/PreloadedWindow.cs
This PR adds 2 more widgets for warming up at preloading step.
- `ElmSharp.Radio`
: helps [Tizen.Wearable.CircularUI.Forms.Radio](https://samsung.github.io/Tizen.CircularUI/api/Tizen.Wearable.CircularUI.Forms.Radio.html) to be created **3.08ms** faster at the first creation time.
`Invoke OnElementChanged` time: 25.601ms → 22.517ms (▽3.08) 
- `ElmSharp.Index`
: helps[Tizen.Wearable.CircularUI.Forms.IndexPage](https://samsung.github.io/Tizen.CircularUI/api/Tizen.Wearable.CircularUI.Forms.IndexPage.html) to be created **8.44 ms** faster at the first creation time.
`Invoke OnElementChanged` time: 31.56ms → 23.12ms (▽8.44)   
- N/A
> [ElmSharp] Add widgets for warming up at preloading step

- src/Tizen.NUI/src/internal/Layouting/Interop/Interop.FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Previously, margin of chilren in FlexLayout was ignored because it was not set to FlexNode of children.
Now, when adding child to View which using FlexLayout, we pass margin of child and set it to FlexNode of child.
NONE
> [NUI] Fix margin bug in FlexLayout

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Previously, padding of parent and margin of child are not concerned when measure child size.
For now, When child use MatchParent,
the size of child will be ParentSize - ParentPadding - childMargin.
And when child use WrapContent,
the size of child will be GrandchildSize + childPadding.
Also Weight will be use only ParentSize - ParentPadding - childMargin size for measuring.
NONE
> [NUI] Use padding & margin to meausre size in Layout

- src/Tizen.NUI/src/public/InputMethodContext.cs
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-306
> [NUI] Deprecate InputMethodContext public constructor

- src/Tizen.Multimedia/AudioManager/AudioDevice.cs
- src/Tizen.Multimedia/AudioManager/AudioDeviceOptions.cs
- src/Tizen.Multimedia/AudioManager/AudioDeviceState.cs
- src/Tizen.Multimedia/AudioManager/AudioDeviceStateChangedEventArgs.cs
- src/Tizen.Multimedia/AudioManager/AudioManager.cs
It is related to TCSACR-302 that is to remove deprecated API rejected by PM. Instead, we made a decision to apply editorbrowsable attribute to 'never' for those API.
> [AudioManager] Apply EditorBrowsableState.Never for deprecated API

- packaging/csapi-tizenfx.spec
- Set smack labels of symbol files (debug package)
This fixes a pdb loading problem on debugging.
> [Build] Set smack labels of symbol files

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Previously, page moves the width of ScrollableBase in SnapToPage mode.
Now, Center of Page will be aligned with Center of ScrollableBase.
And User can set min/max scroll distance by setting ScrollAvailableArea.
NONE
> [NUI] Change PageToSnap Behavior

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- If new WidthSpecification and HeightSpecification values are same
as the previous ones, then no need to request layout again.
- So, added to check that the new size width and height are different from the old ones.
- N/A
> [NUI] Check the previous width and height specifications

- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Create internal callback delegate once for prevent invoking callback
after garbage-collected in unmanaged code.
N/A
> [Packagemanager] Fix creating internal callback delgate

- src/ElmSharp.Wearable/ElmSharp.Wearable/Preload.cs
- src/ElmSharp/ElmSharp/PreloadedWindow.cs
This PR suggests to invoke ElmSharp.Wearable preloading method by using reflection on `ElmSharp`.
`ElmSharp.Wearable` preloads widgets which enhance the application startup time.
- `CircleDateTimeSelector` :  ▽24.13ms on `CircleDateTimeSelectorRenderer`
- `CircleSurface`, `CircleProgressBar`, `CircleSlider`, `MoreOption` : ▽5ms or ▽26ms(with `ToolbarItem`) on `CirclePageRenderer`
- `CircleScroller` : ▽6.53ms on `CircleScrollViewRenderer`
- `CircleSpinner` : ▽9.21ms on `CircleStepperRenderer`
- N/A
> [ElmSharp] Add ElmSharp.Wearable preloading

- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
If layout owner is null, cannot remove owner from it's parent.
Check owner is null.
NONE
> [NUI] check layout owner is null when removing childLayout

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SiblingOrderTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
[NUI] Add SiblingOrder Sample
SiblingOrder can set the order of mine in the sibling list owned by parent.
the lower value of SiblingOrder means it goes lower to the bottom so that it will be covered by higher valued siblings. 
(Vise versa, if SiblingOrder goes to high, the object will be up to the top which can be said as a screen.)
if new added sibling has same value with previously existed sibling, the existed siblings, which have higer value than new sibling, will get +1 and will be rearranged. 
(this means the new added sibling will be placed right under the old sibling that has same SiblingOrder value)
Therefore, SiblingOrder will be automatically set as parent's ChildCount + 1 when child itself is added to parent by "Add()".
nothing
> [NUI] Add SiblingOrder Sample

- src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorder.cs
-Tizen.Multimedia.StreamRecorder.StreamRecorder()
Signed-off-by: Hyunsoo Park <hance.park@samsung.com>
feature is added. (http://tizen.org/feature/multimedia.streamrecorder.record)
So related APIs are modified.
- ACR:TCSACR-305
(https://code.sec.samsung.net/jira/browse/TCSACR-305)
> [StreamRecorder] Handle NotSupportedException as new feature added

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Previously, Scrolling was working wierdly when scrolling to first item.
Scrolling to first item was so so slow but scrolling to last item was fine.
This is because when calculation for scroll distance is wrong.
So, fix the equation.
NONE
> [NUI] Fix scrolling

- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
1. Remove ClearBackgound operate when setting BackgroundImage, otherwise blink issue exists.
- ACR:
> [NUI] Remove ClearBackgound operate when setting BackgroundImage

- src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Commons.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/DataReceivedEventArgs.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Pipeline.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/SingleShot.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/StateChangedEventArgs.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsData.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsInfo.cs
This patch newly provides interfaces to create and execute stream pipeline with neural network.
Pipeline and its related classes support the following functionalities:
- Create a stream pipeline with NNStreamer plugins and GStreamer plugins.
- Interfaces to start/stop/destroy the pipeline.
- Interfaces to get the state of the pipeline and register callback method.
- Interfaces to push data to the pipeline from the application.
- Interfaces to pull data from the pipeline to the application.
- Interfaces to control the stream of the pipeline using switches and valves.
ACR
- [TCSACR-300](https://code.sec.samsung.net/jira/browse/TCSACR-300)
Signed-off-by: Jaeyun <jy1210.jung@samsung.com>
> [MachineLearning.Inference] Pipeline class to execute neural network stream

- src/Tizen.NUI/src/public/Color.cs
Create color object from Hex Color Code (string).
1. Code with "#", it will be remove.
2. Without alpha channel, alpah channel will be set 1.0f.
3. Working both. Lowercase and uppercase,
"#FF0000FF" - Good
"#ff0000ff" - Good
"FF0000FF"  - Good
"FF0000"    - Good
"FF"        - Bad  ( too short )
NONE
> [NUI] Create Color from Hex Color Code

- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
When using wrap_content to match it's height or width to child count,
the result of measure was not applied again so it wasn't changed.
Update measure result after children are added.
NONE
> [NUI] Fix grid layout measurement

- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Currently, panning is working even if there is popup over component.
As workaround, add PanGestureDetector to Popup to prevent panning.
Additionally, add View to ScrollableBase which is to interrupt touching during scrolling.
NONE
> [NUI] Interrupt pan when popup is popped

- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Previously, Remove child manually so missing few steps.
Now, use RemoveChild func for removing.
NONE
> [NUI] Remove Child in Layout View using RemoveChild func

- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Prevously, opposite dimension of choosen grid orientation was not measured correctly.
It just followed parent's size even if measure mode is not "Exactly".
Now, following measure mode.
NONE
> [NUI] Measure opposite dimension correctly in GridLayout

- src/Tizen.NUI.Components/Controls/Popup.cs
Popup should be always on top of layer when popup is posted.
And should consume all touch,hover because it is on top.
Set Touch/Hover consume to true.
NONE
> [NUI] Consume Touch/Hover when popup is posted

- src/Tizen.NUI.Components/Controls/Control.cs
1. HasFocus always return true during OnFocusGained or OnFocusLost.
- ACR:
> [NUI.Components] Fix focus state can't reach issue

- src/Tizen.NUI.Components/Controls/Pagination.cs
- According to GUI guide, Pagination normal indicator opacity should be 50%.
- Updated the opacity.
- N/A
> [NUI] Update Pagination indicator opacity

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Controls/Tab.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CheckBoxSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
* Fix ControlState propagation to false.
* Fix typo in class name : ControlStateChagedInfo -> ControlStateChangedInfo
* Enhance ControlStateChangeInfo to have InputMethod property.
* Remove combined ControlState handling in Selector: It needs to be well-designed first.
* Fix test/Tizen.NUI.Samples compile errors.
- ACR:
> [NUI] Fix ControlState issues.

- src/Tizen.NUI.Wearable/src/public/CircularPagination.cs
- The  normal indicator of CircularPagination should have 50% opacity, and the focused one should have 100% opacity.
- N/A
> [NUI] Update CircularPagination opacity

- src/ElmSharp/ElmSharp/PreloadedWindow.cs
This PR is adds internal API (`PreloadedWindow.PeekInstance()`) to retrieve the global `PreloadedWindow` instance. 
None
> [ElmSharp] Adds PeekInstance to PreloadedWindow

- src/Tizen.NUI/src/internal/Application.cs
- src/Tizen.NUI/src/internal/WidgetImpl.cs
- Fix GetWindow() using GetManagedBaseHandleFromNativePtr
- ACR:
> [NUI] Fix some API to use GetManagedBaseHandleFromNativePtr

- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
`View.Layout` is set by `LayoutGroup.AddChildToLayoutGroup()`
1.When layout is set before child added
```
Tizen.NUI.LayoutGroup.AddChildToLayoutGroup() Line 164
Tizen.NUI.LayoutGroup.OnChildAddedToOnwer() Line 265
Tizen.NUI.BaseComponent.View.Add() Line 152
```
2.When layout is set after child added
```
Tizen.NUI.LayoutGroup.AddChildToLayoutGroup() Line 164
Tizen.NUI.LayoutGroup.OnAttachedToOwner() Line 466
Tizen.NUI.LayoutItem.AttachToOnwner() Line 168
Tizen.NUI.BaseComponentsView.SetLayout() Line 110
Tizen.NUI.BaseComponentsView.set_Layout() Line 2214
```
This means children's Layout is alreay assinged on `LayoutController.Process()`.
So, we don't need to assign layout again.
> [NUI] remove unnecessary code to assign children layout

- src/Tizen.NUI/src/public/Key.cs
This patch will reduce method call.
e.g.
```
Tizen.NUI.Key.set_keyString()
Tizen.NUI.Key.set_KeyString()
```
==>
```
Tizen.NUI.Key.set_keyString()
```
> [NUI] remove redundant private properties for Tizen.NUI.Key

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Extension/ButtonExtension.cs
- src/Tizen.NUI.Components/Controls/Extension/LottieButtonExtension.cs
- src/Tizen.NUI.Components/Controls/Extension/LottieSwitchExtension.cs
- src/Tizen.NUI.Components/PreloadStyle/OverlayAnimationButtonStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
`ConstrolState` can be changed by API or Input(`Tizen.NUI.Key` and
`Tizen.NUI.Touch`). it means `ConstrolState` is not always related to
Input method. some Controls need it to use state changed effect. however,
not all controls require that. if we need some property to change state,
we can add it to Style Extension classes.
Also, this patch rename `View.StateChagedEvent` recommended by Framework Design Guidelines.
(https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/)
> [NUI] remove input method dependency from View.ControlState

- src/Tizen.NUI/src/public/XamlBinding/SizeTypeConverter.cs
1. Fix the issue that size receives 2 parameters from xaml
- ACR:
> [NUI] Fix the issue that size receives 2 parameters from xaml

- src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs
Wrong key string value of MV_INFERENCE_TARGET_DEVICE.
In NativeACR, MV_INFERENCE_TARGET_DEVICE_TYPE is added.
This patch fix it.
Signed-off-by: Tae-Young Chung <ty83.chung@samsung.com>
- ACR: Non-ACR
> [MediaVision] Fix wrong key string value

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
When user set maximum size or minimum size instaed of size and specification,
it means that user want to use natural size of component and makes it bigger than minimum and smaller than maximum.
Currently, when using text, it lays whole text on one line and returns its size as natural size even if multiline is enabled.
So, we need to calculate HeightForWidth with MaximunWidth to know candidate height of multiline text.
Use GetHeightForWidth / GetWidthForHeight size as suggested minimun size.
NONE
> [NUI] Change suggested minimun size in Layout.

- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/PreloadStyle/DefaultTheme.cs
- src/Tizen.NUI.Components/PreloadStyle/WearableTheme.cs
- src/Tizen.NUI.Components/Style/Theme.cs
- src/Tizen.NUI/src/public/InputMethodContext.cs
- Removed the initialized size of Loading visual.
- Added the default size value on Loading PreloadStyle.
- Modified InputMethodContext description slightly.
- N/A
> [NUI] Update the default size of Loading

- src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
- src/Tizen.NUI.Wearable/src/public/WearableStyle/CircularProgressStyle.cs
https://code.sec.samsung.net/confluence/pages/viewpage.action?pageId=159871325
- Add CircularProgress class to Tizen.NUI.Wearable
- CircularProgress class is used to show the ongoing status with a circular bar in Wearable device.
- N/A
> [NUI] Add CircularProgress to Wearable components

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/VisualConstants.cs
FittingMode does not need the required size anymore.
and new fittingMode is added for ImageView.
- CENTER : Image fills inside using original width & height.
- FILL   : Image filles whole width & height. this fitting mode don't  maintain aspect ratio
- ACR:
> [NUI] Refactorying FittingMode for ImageView

- src/ElmSharp/Interop/Interop.Libc.cs
This PR fix the size of internal `SystemTime64` struct for considering based OS arch (64bit or 32bit). Unlike 64bit, native (C) `long` size = 4 byte on the 32 bit machine. So, we should use `IntPtr` instead of `long`.
> [ElmSharp] Update the SystemTime internal struct

- src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
Call TrySetProperty first and then TrySetValue to keep the code logic consistent whether it is through xaml or code.
> [NUI] SetProperty first then SetValue

- src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionManager.cs
Some properties can throw NotSupportedException and UnauthorizedAccessException, but that is not described in API documents.
WiFiState, BluetoothState, EthernetState and CellularState
ConnectionItem.Type and ConnectionItemState
> [Connection] Update documents for state/type

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
The manufacture data can be filled without NULL termination.
Because it is the byte array type. So we should define it as
IntPrt instead of string to avoid the buffer overflow.
Exception !!!: System.Runtime.InteropServices.COMException (0x8007007A): The data area passed to a system call is too small.
at System.StubHelpers.ValueClassMarshaler.ConvertToNative(IntPtr dst, IntPtr src, IntPtr pMT, CleanupWorkListElement& pCleanupWorkList)
at Tizen.Network.Bluetooth.BluetoothAdapterImpl.GetBondedDevices()
at Tizen.Network.Bluetooth.BluetoothAdapter.GetBondedDevices()
- ACR:
> [Bluetooth][Non-ACR] Fix the crash in GetBondedDevices API

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Previously, ScrollTo moved pan position including the ScrollableBase's
current position.
e.g. ScrollTo(360, true); //moves by 360
ScrollTo(0, true); //moves by 360 again based on current position
The argument position is the new pan position. So the new position of
ScrollableBase becomes (-position).
To move ScrollableBase's position to (-position), it moves by
(-position - currentPosition).
- ACR:
> [NUI] Fix ScrollTo to move pan position to the argument position

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
This patchset is to avoid ArgumentNullException error. There are some
cases to come NULL variable from Native API.
BluetoothAdapterImpl.cs: RegisterDiscoveryStateChangedEvent(258) > Discovery state changed callback is called
Unhandled exception.
System.ArgumentNullException: Value cannot be null. (Parameter 'ptr')
at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr ptr, Int32 len)
at Tizen.Network.Bluetooth.BluetoothUtils.ConvertStructToDiscoveredDevice(BluetoothDiscoveredDeviceStruct structDevice)
at Tizen.Network.Bluetooth.BluetoothAdapterImpl.<RegisterDiscoveryStateChangedEvent>b__45_0(Int32 result, BluetoothDeviceDiscoveryState state, IntPtr deviceInfo, IntPtr user
- ACR:
> [Bluetooth][Non-ACR] Add NULL check logic for Marshal.PtrToStringAnsi

- src/Tizen.NUI.Components/Controls/Control.cs
When a NUI.Component.Control class was extended, the default style
was not loaded well.
This was because searching style logic was executed with not whole base classes
but only with the inherited class.
> [NUI][Style] Fix style loading issue when extending control classes

- src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs
- src/Tizen.NUI.Wearable/src/public/Title.cs
To resolve CA1802 of StyleCop in Tizen.NUI.Components and
Tizen.NUI.Wearable, static readonly is replaced with const.
- ACR:
> [NUI] Resolve CA1802 of StyleCop

- src/Tizen.NUI.Components/Controls/RecyclerView/LinearLayoutManager.cs
- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- src/Tizen.NUI.Wearable/src/public/Popup.cs
- src/Tizen.NUI.Wearable/src/public/WearableList.cs
To resolve CA1823 of StyleCop in Tizen.NUI.Components and
Tizen.NUI.Wearable, unused variables are removed.
'isNeedAnimation' in CircularPagination.cs is not removed because it is
marked as 'TODO'.
- ACR:
> [NUI] Resolve CA1823 of StyleCop

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI.Components/Controls/DropDown.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
- src/Tizen.NUI.Components/Controls/ImageScrollBar.cs
- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/Controls/Pagination.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI.Components/Controls/Tab.cs
- src/Tizen.NUI.Components/Controls/Toast.cs
- src/Tizen.NUI.Wearable/src/public/CircularPagination.cs
- src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
- src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
- src/Tizen.NUI.Wearable/src/public/CircularSlider.cs
- src/Tizen.NUI.Wearable/src/public/Popup.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
`CreateViewStyle` is alternative method of `GetViewStyle`.
To resolve CA1721, please use `CreateViewStyle` instead.
```
warning CA1721: The property name 'ViewStyle' is confusing given the existence of
method 'GetViewStyle'. Rename or remove one of these members.
```
`GetViewStyle` should be deprecated(or removed) if there is no
compatibility issue.
- ACR:
> [NUI] introduce CreateViewStyle that is alternative to GetViewStyle

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
- Duplicated Padding accumulation is removed.
- Use `MeasureChildWithMargins` to consider Margin.
No logical changes.
- ACR:
> [NUI] cleanup MeasureChild Methods

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Previously, ScrollableBase used "ClippingModeType.ClipToBoundingBox" to clip children but it made wrong output when rotating ScrollableBase.
To fix this issue, change clipping mode to ClippingModeType.ClipChildren .
NONE
> [NUI] Change ScrollableBase clipping mode

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/CheckBox.cs
- src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI.Components/Controls/DropDown.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
- src/Tizen.NUI.Components/Controls/ImageScrollBar.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/Progress.cs
- src/Tizen.NUI.Components/Controls/RadioButton.cs
- src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Components/Controls/SelectButton.cs
- src/Tizen.NUI.Components/Controls/SelectGroup.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI.Components/Controls/Tab.cs
- src/Tizen.NUI.Wearable/src/public/WearableList.cs
This would fix CA1051 warnings which indicates that
"Do not declare visible instance fields".
This patch restores the diff in
409a8ccea4f26cd7ca4db8e2549e81aac09121a2
except the modification on opened API.
- ACR:
> [NUI] replace field declaration with property

- src/Tizen.NUI/Tizen.NUI.csproj
- src/Tizen.NUI/src/public/Window.cs
Add Feature to support opengles.surfaceless_context
This feature is used to check whether multi-window is supported.
https://code.sec.samsung.net/jira/browse/TCSACR-298
- ACR:
> [NUI] Add Feature for multi window

- src/Tizen.NUI/src/public/NUIWidgetApplication.cs
For apply multiple class of Widget, this API need to open public
https://code.sec.samsung.net/jira/browse/TCSACR-299
> [NUI] Constructor of NUIWidgetApplication is opened public in API level7

- src/Tizen.Security/Interop/Interop.Privilege.cs
- src/Tizen.Security/Tizen.Security/Privilege.cs
Remove deprecated API
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-320
Remove:
- public static bool GetPrivacyPrivilegeStatus(string privilege)
This changes may have confliction with https://github.com/Samsung/TizenFX/pull/1561.
> [Security] Remove deprecated API

- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Wearable/src/public/WearableList.cs
- src/Tizen.NUI/src/internal/GaussianBlurView.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Previously, user should make container for ScrollableBase to contain
children in ScrollableBase and it brought inconvenience to user.
For now, ScrollalbleBase creates its ContentContainer in Constructor so
user doesn't need to add container.
And ScrollableBase overrides Add/Remove function to add/remove child
to/from ContentContainer even if user call ScrollableBase.Add/Remove.
Plus, user can access to children of ContentContainer through
ScrollableBase.Children property and also can acess to Layout too.
Finally, if user want to change property of ContentContainer, they can
use getter of ContentContainer property.
NONE
> [NUI] ScrollableBase usage improvement

- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
- src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
- src/Tizen.NUI.Wearable/src/public/CircularSlider.cs
Use `Style` property instead of `viewStyle` field.
- ACR:
> [NUI] replace viewStlye with Style

- src/Tizen.NUI.Components/Controls/DropDown.cs
Remove needless delegate and use `EventHandler` instead.
Also, this patch will Fix CA1715.
- ACR:
> [NUI] remove needless delegate for eventhandler

- src/Tizen.NUI.Components/Controls/DropDown.cs
use `ArgumentNullException(string paramName, string message);`
instead of `ArgumentNullException(string paramName);`.
`ArgumentNullException(string message);` doesn't exist.
Also, fixes CA2208
- ACR:
> [NUI] use proper constructor of ArgumentNullException

- src/Tizen.NUI.Components/Controls/SelectGroup.cs
Since `SelectGroup.ItemGroup` is initialized in `SelectGroup` constructor, it
should not be assigned by api user.
Also, this fixes `CA2227: Collection properties should be read only`.
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2227?view=vs-2019
- ACR:
> [NUI] remove SelectGroup.ItemGroup setter

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/DropDown.DropDownItemView.cs
- src/Tizen.NUI.Components/Controls/DropDown.cs
- src/Tizen.NUI.Components/Controls/Tab.cs
- src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
Setting ControlState is now allowed only in the derived class of View.
- ACR:
> [NUI] Change View.ControlState setter to protected

- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Please refer dali patch
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/234639/
Modified to get string as integer by this patch.
- ACR:
> [NUI] Change to get PropertyValue by integer

- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.Helper.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleViewLayoutManager.cs
- src/Tizen.NUI.Components/Style/ButtonStyle.cs
- src/Tizen.NUI.Components/Style/ControlStyle.cs
- src/Tizen.NUI.Components/Style/SliderStyle.cs
- src/Tizen.NUI.Wearable/src/public/WearableStyle/CircularProgressStyle.cs
IDisposable is implemented to class containing disposable class instance
in Tizen.NUI.Components and Tizen.NUI.Wearable to resolve CA1001 of
StyleCop.
Extension classes in Tizen.NUI.Components are not included to this patch
because it has OnDispose() method similar to Dispose().
- ACR:
> [NUI] Implement IDisposable to class containing disposable class

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Wearable/src/public/WearableList.cs
- src/Tizen.NUI/src/public/AlphaFunction.cs
Previously, scrolling uses same alphafunction so scrolling is always
getting slow as same rate even if the velocity of panning is different.
Now, we use deceleration fomular and generating alphafunction using
velocity and deceleration rate.
deceleration 0.99 is fast deceleration and 0.998 is normal.
NONE
> [NUI] Deceleration of scrolling

- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
- src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleViewLayoutManager.cs
Since LayoutManager handle mLayout is not constructed by FlexibleView,
mLayout is not disposed but its member handles are cleared.
- ACR:
> [NUI] Fix not to dispose LayoutManager in FlexibleView

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
Exception is occured on BluetoothLeDevice constructor if GATT not supported.
BluetoothGattClient.StaticConnectionStateChanged += (s, e) =>
Remove exception throw logic on the event handler StaticConnectionStateChanged for consistency
> [Bluetooth][Non-ACR] Fix LeDevice constructor exception issue

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
Exception is occured on BluetoothLeDevice constructor if GATT not supported.
BluetoothGattClient.StaticConnectionStateChanged += (s, e) =>
Remove exception throw logic on the event handler StaticConnectionStateChanged for consistency
> [Bluetooth][Non-ACR] Fix LeDevice constructor exception issue (#1765)

- src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
.net framework provide two kinds of current `CultureInfo`s. 
They are designed to represent a different kind of culture info,
First is `CurrentCultureInfo`, it is representing `region/format` information, it is provide by `SystemSettings.LocaleCountry` on tizen
Second is `CurrentUICultureInfo` it is representing `Language` information, it is provide by `SystemSettings.LocaleLanguage` on tizen
So, we should update `CurrentUICultureInfo` when Locale was updated
and we should update `CurrentCultureInfo` when RegionFormat was Changed
https://wpf.2000things.com/2013/02/25/763-the-difference-between-currentculture-and-currentuiculture/
https://stackoverflow.com/questions/329033/what-is-the-difference-between-currentculture-and-currentuiculture-properties-of
- ACR:
> [Application] Separating Language changing logic and Region changing logic

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
* This fixes the issue that a checkbox selection can not be unselected.
* Note that this is temporary solution, it need to be fixed after
the Selector priovides priority among the states.
- ACR:
> [NUI] Fix Button state issue

- src/Tizen.NUI.Components/Controls/RecyclerView/GridRecycleLayoutManager.cs
Orientation of GridRecyclerLayoutManager was reversed.
Now, Orientaion matches the direction of items listed in RecyclerView.
NONE
> [NUI] Fix orientaion of GridRecycleLayoutManager

- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
Restore LayoutManager property to public because user needs public setter to set
LayoutManager.
NONE
> [NUI] Restore setter of LayoutManager property to public

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI.Components/Controls/DropDown.DropDownItemView.cs
- src/Tizen.NUI.Components/Controls/Extension/LottieButtonExtension.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- src/Tizen.NUI.Components/Controls/Tab.cs
- src/Tizen.NUI.Components/PreloadStyle/OverlayAnimationButtonStyle.cs
- src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
- src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/Constants.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/StateValueCollection.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
You can define your own control states. first, declare ControlState variable
and initialize using  `ControlState.Create`.
```
public class MyButton : Button {
...
ControlState MyState = ControlState.Create("MyState");
...
}
```
And assign to `View.ControlState`.
```
void OnStateChanged(...) {
ControlState = MyState;
}
```
If you want to assign the value of custom state to `Selector`, use
`Add(ControlState state, object value)`.
```
Selector<string> textSelector = new Selector<string>();
textSelector.Add(ControlState.Pressed, "Pressed!");
textSelector.Add(MyState, "MyText");
```
or
```
Selector<string> textSelector = new Selector<string>()
{
{ ControlState.Pressed, "Pressed!" },
{ MyState, "MyText" }
};
```
To implement your own combined control states, you can use the `+` or `+=` …
> [NUI] add ControlState class to support combined and custom state

- src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
This patch fixes such code working well.
```
ControlState a = ControlState.Normal + ControlState.Selected;
a == ControlState.Selected; // This should be true.
```
- ACR:
> [NUI] Fix ControlState equality issue.

- src/Tizen.NUI/src/public/VisualMaps.cs
* Previously, VisualMap.OutputVisualMap returns a visual map without transform data.
It causes misunderstanding frequently.
Now it returns full visual map including transform data.
* Fix VisualMap.OutputVisualMap to create new PropertyMap everytime to
prevent increasing map size.
- ACR:
> [NUI] Fix VisualMap.OutputVisualMap

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- Change wrong comment of PositionUsesPivotPoint.
- DALi native default is true, but NUI's default is false.
none
> [NUI] Change wrong comment of PositionUsesPivotPoint

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
- src/Tizen.NUI.Components/Controls/Extension/SwitchExtension.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Previously, when a Switch is selected by code, the thumb is not moved to left/right.
```
var switchButton = new Switch()
{
IsSelected = true,
}
```
Thumb is moved only if the user touches the switch area or presses return key.
This patch fixes this problem and to do that, it needed to change belows,
* Switch does not listen Touch/Key event anymore to detect selection changed
Instead it uses ControlState changed event which is clearer.
* Button produces more complicate combined state such as "SelectedPressed".
* Clean up the code that is redundant in Selector.GetValue().
- ACR:
> [NUI] Fix Switch selection bug.

- src/Tizen.NUI/src/public/NUIWidgetApplication.cs
if application use null dictionary for creating NUIWidgetApplication,
we need to throw exception.
- ACR:
> [NUI] add exception code for NUIWidgetApplication

- pkg/Tizen.NET/runtime.json
Add runtime identifiers for arm64
- ACR:
> [Build] Add tizen-arm64, tizen.6.0.0-arm64 RIDs to runtime.json

- src/Tizen.NUI/src/public/VisualMaps.cs
This reverts commit 8936e6f1a0ea487b3c9fe1a18f4d3887c7d12bf9.
SVG is not displayed on TV.
- ACR:
> Revert "[NUI] Fix VisualMap.OutputVisualMap (#1794)"

- src/Tizen.NUI/src/internal/XamlBinding/PositionTypeConverter.cs
- src/Tizen.NUI/src/public/XamlBinding/SizeTypeConverter.cs
1. Fix Position type converter error when Position get 2 parameters in XAML
- ACR:
> [NUI] Fix Position type converter error when Position get 2 parameters in XAML

- src/Tizen.NUI.Components/Controls/Loading.cs
This fixes size effect of #1797
- ACR:
> [NUI] Fix Size issue of Loading

- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Previously, children of GridLayout inherits top position of parents so if
positionY of GridLayout is not 0, the children are also moved same size.
Now, they don't inherit top position of parents.
NONE
> [NUI] Fix GridLayout logic

- src/Tizen.NUI/src/internal/Application.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ActorSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
- src/Tizen.NUI/src/internal/Interop/Interop.NDalic.cs
- src/Tizen.NUI/src/internal/Interop/Interop.PushButton.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ViewImplSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WindowFocusSignalType.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WindowInternal.cs
- src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
- src/Tizen.NUI/src/internal/WindowFocusSignalType.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/UIComponents/PushButton.cs
- src/Tizen.NUI/src/public/Window.cs
Remove some internal APIs after some deprecated APIs removed in DALi native code
- ACR: N/A
> [NUI] Remove non-touch related deprecated APIs

- src/Tizen.NUI/src/internal/Interop/Interop.ViewWrapperImpl.cs
- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
> [NUI] Sync ViewWrapper director arguments to dali-csharp-binder

- src/Tizen.Applications.Common/Interop/Interop.ApplicationManager.cs
- src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
Signed-off-by: SukHyung, Kang <shine.kang@samsung.com>
Add app manager attach/detach window API for internal
- ACR: Non-ACR
<!--
If you can't make the ACR, List all API changes here (or just put None), example:
Added:
- public static void AttachWindow(string parentAppId, string childAppId)
- public static void DetachWindow(string applicationId)
> [Applications] Add app manager attach/detach window API for internal

- src/Tizen.NUI/src/internal/BackKeyManager.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
View can subscribe back key event using BackKeyEvent event handler.
When user adds BackKeyEvent callback to View, view is listed as Subscriber of BackKeyManager.
After that, if back key is comming,
BackKeyManager will find top view among back key subscribers which has Visibility and IsOnWidnow property are true.
The top view will emit its BackKeyEvent.
*** Notice ***
It is based on Window KeyEvent so make sure you don't use Window KeyEvent and View KeyEvent.
After binding backkey event from DALi, user can use Window/View KeyEvent
with BackKeyEvent.
NONE
> [NUI] BackKeyEvent Proptotype

- src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
- src/Tizen.NUI/src/internal/XamlBinding/ResourcesExtensions.cs
- src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs
Support the different file name of Xaml.
- ACR:
> [NUI] Support the different file name of Xaml

- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
By default, item size should be respected.
- ACR:
> [NUI] make xxxStretchProperty default value as StretchFlags.None

- src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
GridLayout child margin was ignored...
- ACR:
> [NUI] respect GridLayout child margin

- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Before commit c04eaacb3186b0ea9e499d7a930b10e074134d32, child was added
from left to right by default. but now they are added from top to
bottom.
This patch reverts auto-placement rule to keep backward compatibility.
- ACR:
> [NUI] make GridLayout.Orientation default value as Horizontal

- src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
Column/row of GridLayout child should be compared to max column/row count which
is decided by auto-placement of GridLayout.
- ACR:
> [NUI] use correct max column/row count in validation of child column/row

- src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
The result is reversed. `totalHorizontalExpand` should be used in
horizontal orientation.
- ACR:
> [NUI] fix wrong total expand value in expanded size calculation

- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SliderSample.cs
To replace nested types (CA1034 of StyleCop), the followings are added.
- class SliderValueChangedEventArgs
- class SlidingFinishedEventArgs
- event EventHandler<SliderValueChangedEventArgs> in Slider class
- event EventHandler<SlidingFinishedEventArgs> in Slider class
The followings are deprecated.
- class ValueChangedArgs in Slider class
- class SlidingFinishedArgs in Slider class
- event EventHandler<ValueChangedArgs> in Slider class
- event EventHandler<SlidingFinishedArgs> in Slider class
- ACR:
> [NUI] Add public types to replace nested types of Components.Slider

- src/Tizen.NUI.Components/Controls/Switch.cs
To replace nested types (CA1034 of StyleCop), the following is added.
- event EventHandler<SelectedChangedEventArgs> in Switch class
The followings are deprecated.
- class SelectEventArgs in Switch class
- event EventHandler<SelectEventArgs> in Switch class
- ACR:
> [NUI] Add public types to replace nested types of Components.Switch

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Extension/ButtonExtension.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedImageViewTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ButtonSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CubeTransitionEffectSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GridLayoutSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ItemViewDemo/ItemViewSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LoadingSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ProgressSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PropertyNotificationTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollBarSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SiblingOrderTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TabSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ToastSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WearablePopupTest.cs
To replace nested types (CA1034 of StyleCop), the following is added.
- class ClickedEventArgs
- event EventHandler<ClickedEventArgs> in Button class
The followings are deprecated.
- class ClickEventArgs in Button class
- event EventHandler<ClickEventArgs> in Button class
- ACR:
> [NUI] Add public types to replace nested types of Components.Button

- src/Tizen.NUI/src/public/Window.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AddFrameRenderedCallbackTest.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CaptureTest.cs
Change for AddFrameRenderedCallback to maintain the reference of user callback
- Fix for the already merged patch : https://github.com/Samsung/TizenFX/pull/1811
- http://wiki.vd.sec.samsung.net/pages/viewpage.action?pageId=4213716
- Using Dictionary to maintain native callback reference so that it is not to be garbage collected
- Small fix added : CaptureTest code's build error is fixed
none
> [NUI] Change for AddFrameRenderedCallback to maintain the reference

- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
There are 4 cases.
1. Fixed or MatchParent Width and Height
: Use fixed or parent size
2. Fixed or MatchParent Width and WrapContent Height
: Get Height for Width using GetHeightForWidth() API
3. WrapContent Width and Fixed or MatchParent Height
: Get Width for Height using GetNaturalSize() API because there is no
overrided GetWidthForHeight function in TextLabel.
4. WrapContent Width and Height
: Get Width and Height using GetNaturalSize() API
Padding will be automatically applied by DALi TextLabel.
NONE
> [NUI] Create Layout only for TextLabel

- src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcTag.cs
- https://code.sec.samsung.net/jira/browse/TFDF-10927
- It seems that the callback is missing from the constructor in API7 branch
Signed-off-by: Jihoon Jung <jh8801.jung@samsung.com>
> [NFC][Non-ACR] Fix NFC Csharp TC failed issue

- src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
- src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/VisualView.cs
* Control always be a hit actor for touching, but the scrollbar does not need to be.
- ACR:
> [NUI] Scrollbar inherits VisualView instead of Control

- src/Tizen.NUI/src/public/WindowEvent.cs
Fix Window.FocusChanged event problem
- csharp-binder's signal callback handler's type has been changed for multi-window
- change the FocusChanged event type according to the dali's Window signal handler
none
> [NUI] Fix Window.FocusChanged event problem

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI.Components/Controls/SelectButton.cs
- src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
* Previously, the View did not support ControlState so that selector values are not applied to the View.
* Introduce a new property EnableControlState.
If this property is set to true, the View can have a touch related ControlState (such as Pressed) when touch.
By default, it is false in View, true in Control.
Note that if the value is true, the View will be a touch receptor.
- ACR:
> [NUI] Enable selectors work in View : EnableControlState

- .github/workflows/pull_request.yaml
In docs of Github Actions
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
> [Build] Use GITHUB_TOKEN in Pull Request workflow

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Previously when velocity is 0, ScrollAnimationFinished callback is not
working so touch interrupt view is not disappear.
Now, ScrollAnimation is started even if velocity is 0.
NONE
> [NUI] Fix scroll item touch issue

- src/Tizen.NUI/src/public/WindowEvent.cs
Workaround : windowSize should be valid pointer from dali, but currenlty it is fixed and is not Uint16Pair class.
will be fixed later.
none
> [NUI] Workaround : Fix TCT fail issue

- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/Size.cs
- src/Tizen.NUI/src/public/Size2D.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ViewSizeWidthPropertySetTest.cs
Fix ResizePolicy error when setting View.Size.Width or Height
- If view.Size2D.Width is set, the View.HeightResizePolicy is set as Fixed wrongly
- Fixing this error by using View's SizeWidth/SizeHeight properties which are independent to each other
- Sample APP and test codes are also verified
none
> [NUI] Fix ResizePolicy error when setting View.Size.Width or Height

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/.vscode/launch.json
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/.vscode/tasks.json
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.code-workspace
Add VS Code setting files for Ubuntu
- Some setting files are added for VS Code Ubuntu working
- .Net Core Extension Pack needs be installed in Code
- in console, 
cd test/Tizen.NUI.Samples/Tizen.NUI.Samples
code Tizen.NUI.Samples.code-workspace
ctrl + shift + p (command pallete)
restore (select .NET restore all projects)
set some break point in the source code by F9
F5 (run debugging)
none
> [NUI] Add VS Code setting files for Ubuntu

- src/Tizen.Applications.Alarm/Interop/Interop.Alarm.cs
Use IntPtr instead of long type to match struct size
> [Tizen.Applications.Alarm] Use IntPtr instead of long type

- src/Tizen.NUI/src/internal/Interop/Interop.KeyboardRepeatSettingsChangedSignal.cs
- src/Tizen.NUI/src/internal/KeyboardRepeatSettingsChangedSignal.cs
- src/Tizen.NUI/src/public/WindowEvent.cs
- This signal is emitted when the values of keyboard repeat, such as delay and rate,
are changed globally.
- N/A
> [NUI] Add KeyboardRepeatSettingsChanged event

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/.vscode/launch.json
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Program.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
[NUI] Change VS Code settings in Ubuntu
- change to use .Net Core 3.1
- move to dotnet core 3.1 =>
1. download pkg for Ubuntu : https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.302-linux-x64-binaries
2. install downloaded pkg : 
```
$ mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.1.302-linux-x64.tar.gz -C $HOME/dotnet
$ export DOTNET_ROOT=$HOME/dotnet
$ export PATH=$PATH:$HOME/dotnet
```
3. remove previously installed nupkg : 
`$ sudo rm -rf ~/.nuget/`
4. do dotnet restore : 
```
$ cd {your tizenfx path}/test/Tizen.NUI.Samples/Tizen.NUI.Samples
$ dotnet clean
$ dotnet restore
$ dotnet build Tizen.NUI.Samples.csproj
```
OR you can do restore in VS Code command palette (ctrl+shift+p) => restore All projects
none
> [NUI] Change VS Code settings in Ubuntu

- src/Tizen.NUI/src/public/PropertyMap.cs
[NUI] Workaround : Add Clear() when new PropertyMap()
- workaround : when do "new PropertyMap().Add(xxx, xxx).Add(xxx, xxx)", it has garbage values sometimes. this will be fixed later.
none
> [NUI] Workaround : Add Clear() when new PropertyMap()

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
To get the scroll position given to ScrollTo, ScrollPosition is added.
ScrollPosition is the position in the opposite direction to the position
of ContentContainer.
To get the current scroll position, ScrollCurrentPosition is added.
ScrollCurrentPosition is the position in the opposite direction to the
current position of ContentContainer.
- ACR:
> [NUI] Add ScrollPosition and ScrollCurrentPosition to ScrollableBase

- src/Tizen.NUI.Components/Utils/Selector.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
To track property changes of Selector class, Selector constructor with
SelectorChangedCallback is added internally.
This is the same method applied to Color class.
By using this constructor, ColorSelector class also tracks property
changes internally.
- ACR:
> [NUI] Add Selector constructor with SelectorChangedCallback internally

- src/Tizen.NUI.Components/Controls/Pagination.cs
To support setting indicator color of Pagination, IndicatorColor and
SelectedIndicatorColor properties are added.
- ACR:
> [NUI] Add IndicatorColor and SelectedIndicatorColor to Pagination

- src/Tizen.NUI/src/public/PropertyMap.cs
[NUI] Remove workaround, Fix PropertyMap().Add() problem
- Remove workaround : https://github.com/Samsung/TizenFX/pull/1894
- The native PropertyMap object is deleted by GC, When using like this : new PropertyMap().Add(xxx).Add(xxx);
- Fix to maintain swigCPtr in the scope of Add() method
none
> [NUI] Remove workaround, Fix PropertyMap().Add() problem

- src/Tizen.Applications.Common/Interop/Interop.RPCPort.cs
- src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
- src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Port.cs
- src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs
Support synchronous connection requests and private file sharing
To support synchronous connection requests, ConnectSync() is added.
To support private file sharing, ShareFile() and UnshareFile() are added.
When the application calls ShareFile() method, platform will grant a temporary permission to the target application for files and revoke it when the target application is terminated or UnshareFile() method is called.
The target application doesn't have read permission of the directory that is obtained by caller's data path(Tizen.Applications.DirectoryInfo.Data). The developer should open the file path with read only mode directly. Because, platform grants read permission to the passed file path.
- ACR: TCSACR-362
<!--
If you can't make the ACR, List all API changes here (or just put …
> [RPCPort][ACR] Support synchronous connection requests and private file sharing

- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
In comment, if developer sets negative value to Row/ColumnSpacing, it
will change to 0.
But it isn't so fix this error.
- ACR:
> [NUI] Row/Column Spacing Underflow correction

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
- test/NUITestSample/NUITestSample/examples/text-test.cs
- To limit input to maximum characters in TextEditor,
added MaxLength property and MaxLengthReached signal
- N/A
> [NUI] Add MaxLength property and signal to TextEditor

- src/Tizen.NUI.Components/Controls/Scrollbar.cs
- src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
- src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
To get the scroll position given to ScrollTo or Update, ScrollPosition
is added.
To get the current scroll position in the middle of ScrollTo or Update
animation, ScrollCurrentPosition is added.
- ACR:
> [NUI] Add ScrollPosition and ScrollCurrentPosition to ScrollbarBase

- src/Tizen.NUI/src/internal/Interop/Interop.ViewImplSignal.cs
- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- Currently OnAccessibilityTouch is unused and unnecessary in AccessibilityManager.
So, removed the internal API and its C# binding not to make confused.
- N/A
> [NUI] Remove OnAccessibilityTouch binding

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/DropDown.cs
- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/Controls/Notification.cs
- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- Added the default trait of Accessibility attribute
to several Tizen.NUI.Components
: Button, DropDown, Loading, and ScrollableBase
- If Accessibility turns on, screen reader would read these components name.
- N/A
> [NUI] Add the default Accessibility attribute trait

- src/Tizen.NUI/src/public/BaseComponents/View.cs
[NUI] Restore Size2D's minus value as zero when Layout is null
- to back out this patch : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/226385/  
- Size2D is also used to set Layout size specification so it can be minus value.
- TV FLUX discards minus value of Size2D.Width or Size2D.Height so Size2D's values need be restored as zero when NUI.Layout is NULL
- TV FLUX also has it's own Layout, so NUI needs to maintain its behaviour.
none
> [NUI] Restore Size2D's minus value as zero when Layout is null

- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
[NUI] Fix TCT fail
- Add casting to resolve the exception of the TCT fail
- Exception : execute case Tizen.NUI.Components.Tests # Tizen.NUI.Components.Tests.PopupTests.TitleHeight_SET_GET_VALUE...(FAIL)
System.InvalidOperationException Nullable object must have a value.
none
> [NUI] Fix TCT fail

- src/Tizen.NUI.Components/Controls/Slider.Internal.cs
- src/Tizen.NUI.Components/Controls/Slider.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SliderSample.cs
SlidingStarted event is added to Slider, which was missing while SlidingFinished event already exists.
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-363
> [NUI] Add SlidingStarted event to Slider

- src/Tizen.NUI/src/internal/Xaml/TypeConversionExtensions.cs
Since commit 97c4baea0ef21936602db814fd2a9177ddf6e673, TypeConverter of
Properties has not worked. this patch will fix this issue.
Test Code:
```cs
public class TestClass
{
[TypeConverter(typeof(MyTypeConverter))]
public int TestProperty { get; set; }
public class MyTypeConverter : TypeConverter, IExtendedTypeConverter
{
object IExtendedTypeConverter.ConvertFromInvariantString(string value, IServiceProvider serviceProvider)
{
...
...
return value;
}
...
}
}
```
- ACR:
> [NUI] restore TypeConverter support for Properties

- src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Commons.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/CustomFilter.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Pipeline.cs
This PR newly add `CustomFilter` class and more functionality  to MachineLearning module.
Detailed items are as below.
* Add SNPE(i.e. Snapdgragon Neural Processing Engine) to NNFWType enum.
* Add CPUSIMD to HWType enum.
* Add CustomFilter class to easily manipulate the tensors data as a simple user-level method.
* Add the property getter/setter of the node in NNStreamer pipeline.
* ACR: TCSACR-365
* Remove the code which throws OutOfMemoryException
* Update the wrong API version and comments.
* Use 'CPUNeon = CPUSIMD' since both of them have the same enum value.
* Use predefined delegate `Func` instead of `delegate`
* Use the name 'Create()' of `CustomFilter` class instead of `Register()` since it is more natural.
* Support generic type for property getter function of the node in …
> [MachineLearning.Inference] Add CustomFilter class and more functionality  to MachineLearning module.

- src/Tizen.NUI/src/public/NUIApplication.cs
The LayoutController is not created when created window at the PreLoad time,
because the Stage does not exist yet.
This operation causes a problem that the layout does not work.
https://github.com/Samsung/TizenFX/blob/9094590d0debe5bd4d9806eee79849132efbaf6a/src/Tizen.NUI/src/public/Window.cs#L51-L57
- ACR:
> [NUI] Fix NUI Layout issue

- src/Tizen.NUI/src/internal/Interop/Interop.Texture.cs
- src/Tizen.NUI/src/public/Texture.cs
Create Texture using TbmSurface to draw.
This feature is added for FrameBroker.
- ACR:
> [NUI] Add internal api to create Texture using TbmSurface

- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Since `StyleSheet` is used in Dali with the JSON file format, this rename will
avoid name confusion.
- ACR:
> [NUI] rename from styleSheet to styleName

- src/Tizen.NUI/src/public/Color.cs
Add color constructor which is initialized by System.Drawing.Color.
When we test something, we always feel our Color class has not enough
color list.
In System.Drawing.Color, there is a ton of predefined colors.
So, added new constructor which can initialized by System.Drawing.Color.
NONE
> [NUI] Add color constructor

- src/Tizen.NUI/src/internal/Interop/Interop.Hover.cs
- src/Tizen.NUI/src/public/Hover.cs
This reverts commit 86de072d0845bb610130f14e9e5d593c4faaa46d.
- ACR:
> Revert "[NUI] Provide binding after HoverEvent class pimpling (#1917)"

- src/Tizen.NUI/src/internal/Interop/Interop.Wheel.cs
- src/Tizen.NUI/src/public/Wheel.cs
This reverts commit fb31cb7e5cd8d7ff50d74316227002d619940860.
- ACR:
> Revert "[NUI] Provide binding after WheelEvent class pimpling (#1927)"

- src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
[NUI] Fix Components.Switch Thumb animation defect
- Fix https://code.sec.samsung.net/jira/browse/TDAF-1171
- When the switch thumb is animated, sometimes it's position is fixed so stucked in the middle of track
- Change EndAction of animation as StopFinal
none
> [NUI] Fix Components.Switch Thumb animation defect

- src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
- src/Tizen.NUI.Components/res/Theme/Tizen.NUI.Components_Tizen.NUI.Theme.Common.xaml
- src/Tizen.NUI/src/public/BaseComponents/View.cs
* Change ControlState propagation sequence
* Remove setting border property in default switch style
This fixes an error of the following code,
```
protected override void OnCreate()
{
//...
var button = new Switch();
button.SelectedChanged += OnSelected;
root.Add(button);
}
void OnSelected(object target, SelectedChangedEventArgs args)
{
if (args.IsSelected)
{
(target as Switch).IsSelected = false;
}
}
```
- ACR:
> [NUI] Fix Switch bugs

- src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
- src/Tizen.NUI/src/public/Xaml/XamlServiceProvider.cs
In xaml, root element is now able to be instantiated by parameterized
constructor.
```cs
namespace NUIXamlTemplate1
{
public class TestClass
{
public TestClass([Parameter(nameof(PropertyForConstructor))] string propertyForConstructor)
{
PropertyForConstructor = propertyForConstructor;
}
public string PropertyForConstructor { get; }
}
}
```
```xaml
<local:TestClass
xmlns:local="clr-namespace:NUIXamlTemplate1;assembly=NUIXamlTemplate1"
PropertyForConstructor="test property"
>
</local:TestClass>
```
```cs
protected override void OnCreate()
{
base.OnCreate();
Window.Instance.KeyEvent += OnKeyEvent;
View root = new View();
Window.Instance.GetDefaultLayer().Add(root);
TestClass testClass;
using (var reader = …
```
> [NUI] add support for parameterized constructor in xaml

- internals/src/Tizen.Peripheral/Tizen.Peripheral.csproj
Install Tizen.Peripheral to all profiles temporarily, 
TizenFX does not support dummy assemblies for internal modules now.
- ACR:
> [Build] Install Tizen.Peripheral to all profiles temporarily

- src/ElmSharp/Interop/Interop.Elementary.cs
Interop.Elementary.elm_transit_paused_get always returns true although
elm_transit_paused_get actually returns EINA_FALSE.
Since C and C# use 4 bytes for boolean but C++ uses 1 byte for boolean,
this may cause that the boolean return value is not passed correctly.
To resolve this issue, [return: MarshalAs(UnmanagedType.U1)] is inserted
to the declaration of elm_transit_paused_get in Interop.Elementary.cs.
This patch refers 98c70851b1b1d640295768e6050c90ed61889e7c
- ACR:
> [ElmSharp] Fix elm_transit_paused_get to return boolean correctly

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- Current implementation, the scroll of ScrollableBase will be finished only when Gesture.StateType is Finished.
- However, by the hw, it can be Cancelled.
Signed-off-by: seungho <seungho@seungho.tn.corp.samsungelectronics.net>
> [NUI] Make Scrollable finish when Gesture.StateType is Cancelled

- src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
> [NUI] Switch do not animate on selection when it is not on Window

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Making MeasureCallback return a struct is causing the .NET runtime on
Windows 10 messes up with argument values. We changed the signature of
MeasureCallback on Dali::Toolkit to make the return value be an out
parameter.
The detailed explanation of what's the problem can be found at [1].
Moreover, we declare MeasureCallback as Cdecl, as it is declared this
way in the C++ header file.
[1] https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/242665/
none
> [NUI] Update MeasureCallback interface for latest Dali::Toolkit

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Test Code:
```cs
FlexLayout flexLayout = new FlexLayout();
flexLayout.WrapType = FlexLayout.FlexWrapType.Wrap;
```
- ACR:
> [NUI] correct logical operator in enum validation

- src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
This reverts commit 87dc2534f824b8c35a6961a32a15dfd3a85131a5.
- ACR:
> Revert "[NUI] Add ControlStateTypeConverter for xaml (#2002)"

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
[TDAF-1221] issue
1. If the size of ScrollableBase is changed, maxScrollDistance update is required.
maxScrollDistance: Maximum range that ScrollableBase can scroll
2. Change maxScrollDistance by calling OnSCrollingChildRelayout at OnMeasure when size changes.
3. Currently, maxScrollDistance is updated based on ContentContainer size only.
Change this to be modified even if the ScrollableBase size is changed
- ACR:
> [NUI] Fix ScrollableBase maxScrollDistance issue

- src/ElmSharp.Wearable/Interop/Interop.Eext.MoreOption.cs
`Interop.Elementary.eext_more_option_opened_get` always returns true although `elm_transit_paused_get` actually returns EINA_FALSE.
Since C and C# use 4 bytes for boolean but C++ uses 1 byte for boolean, this may cause that the boolean return value is not passed correctly.
To resolve this issue,` [return: MarshalAs(UnmanagedType.U1)] `is inserted to the declaration of `eext_more_option_opened_get`.
None
> [ElmSharp] Fix elm_more_option_open_get to return bool correctly

- internals/src/Tizen.Peripheral/Tizen.Peripheral/Adc.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Gpio.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/I2c.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Pwm.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Spi.cs
- internals/src/Tizen.Peripheral/Tizen.Peripheral/Uart.cs
Signed-off-by: Ernest Borowski <e.borowski@samsung.com>
Move all classes to it's own namespaces.
Rename classes:
Adc -> AdcChannel
Gpio -> GpioPin
I2c -> I2cDevice
Spi -> SpiDevice
Pwm -> PwmPin
Uart -> SerialPort
Move class:
1.
```csharp
public class Tizen.Peripheral.I2cDevice (class):
public I2cDevice(int bus, int address) (constructor);
public void Close() (method);
public void Read(byte[] dataOut) (method);
public void Write(byte[] data) (method);
public byte ReadRegisterByte(byte register) (method);
public void WriteRegisterByte(byte register, byte data) (method);
public ushort ReadRegisterWord(byte register) (method);
public void WriteRegisterWord(byte register, ushort data) (method);
public void Dispose() (method);
```
to `Tizen.Peripheral.I2c` namespace
2. 
```csharp
public class …
```
> Tizen.Peripheral move all classes to it's namespaces.

- packaging/maketfm.py
> [Build] Fix wrong relative path in maketfm.py

- src/Tizen.NUI/src/public/BaseHandle.cs
If Dispose is already called, the log is displayed unnecessarily.
- ACR:
> [NUI] Delete unnecessary log in BaseHandle

- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/SelectButton.cs
To add Switch.SelectedChanged event with using SelectedChangedEventArgs,
SelectedChangedEventArgs is added to public.
- ACR:
> [NUI] Add class SelectedChangedEventArgs to public

- internals/docs/toc.md
Signed-off-by: Ernest Borowski <e.borowski@samsung.com>
Update toc so documentation will properly display Tizen.Peripherial.* namespaces.
> [Peripheral] Update toc needed by namespace change.

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpControlImpl.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs
- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
I/DOTNET_LAUNCHER( 1322): System.Runtime.InteropServices.COMException
(0x8007007A): The data area passed to a system call is too small.
(0x8007007A) at System.StubHelpers.ValueClassMarshaler.ConvertToNative
(IntPtr dst, IntPtr src, IntPtr pMT, CleanupWorkListElement& pCleanupWorkList)
> [Bluetooth][Non-ACR] Fix Track data converting logic

- src/Tizen.NUI/src/internal/FrameBroker/DefaultFrameBroker.cs
- src/Tizen.NUI/src/public/TransitionAnimations/TransitionAnimations.cs
- src/Tizen.NUI/src/public/TransitionOptions/TransitionOptions.cs
- test/Tizen.NUI.Seamless/NUISimpleCallee/NUISimpleCallee.cs
- test/Tizen.NUI.Seamless/NUISimpleCaller/NUISimpleCaller.cs
- Set the default X value to be set even if it is not SlideIn.
- Set the parameter 'toProvider' value of 'SendLaunchRequest' to true.
For FrameBroker, this value must be set to true.
- Update sample code : Add Event callback
- Need to check
* This sample is currently not working normally in wearable.
* Backward animation is not performed.
- ACR:
> [NUI] Modify seamless bug & update sample

- src/Tizen.NUI/src/public/Utility/TextPageUtil.cs
add check remainLength and init totalPageCnt value
- ACR: NONE
> [NUI] Bug fixed about TextPageUtil

- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/Style/LoadingStyle.cs
- Currently, Size2D is not working well because of duplicated size properties.
- Fixed both Size and Size2D to work well in Loading
- N/A
> [NUI] Fix Size2D to work correctly in Loading

- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
This will fix DA-NUI build error.
Please revert this patch after the DA build error is fixed.
- ACR:
> [NUI] Make Selector.StateValueList public temporarily

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
Add properties for:
EnableEditing
- ACR:
> [NUI] TextField/TextEditor: Add EnableEditing properties

- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
This is tempopary error fix to sync with fhub-nui without full build.
- ACR:
> [NUI] Change type of Selector.StateValueList to IList

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/DaliEnumConstants.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
This reverts commit 663cf117fbee9589ef6b1eda3c26eef902641836.
TCT Tizen.NUI.Components fail.
Tizen.NUI.Components.Tests.ScrollableBaseTests.Layout_SET_GET_VALUE
Tizen.NUI.Components.Tests.ScrollableBaseTests.ScrollTo_GET_VALUE
- ACR:
> Revert "[NUI] fix ScrollableBase wrong size issue (#2126)"

- src/Tizen.NUI/src/internal/ViewSignal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
[NUI] Add defensive code for ViewSignal Disconnect()
- the following exception couldn't be reproduced so this defensive code is added.
Exception !!! : [com.samsung.tv.csfs] [] EXCEPTION Exception !!!: System.NullReferenceException: Object reference not set to an instance of an object.
at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate[TDelegate](TDelegate d)
at Tizen.NUI.ViewSignal.Disconnect(Delegate func)
at Tizen.NUI.BaseComponents.View.DisConnectFromSignals()
at Tizen.NUI.BaseComponents.View.Dispose(DisposeTypes type)
at Tizen.TV.FLUX.FluxView.Dispose(DisposeTypes type)
- Add back trace and thread check in ViewSignal.Disconnect().
- Add null setting in callback delegate.
none
> [NUI] Add defensive code for ViewSignal Disconnect()

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- Rollback default ContentsContainer layout (AbsoluteLayout)
- Set false the value of SetPositionByLayout of the AbsoluteLayout
> [NUI] fix ScrollableBase layout properties

- src/Tizen.Network.WiFi/Tizen.Network.WiFi/ConnectionStateChangedEventArgs.cs
The parameter, apHandle of ConnectionStateChangedEventArgs() is freed by caller (native api).
Therefore, cloned handle should be used to create new WiFiAP instance.
> [WiFi] Use cloned apHandle

- src/Tizen.NUI/src/internal/Application.cs
- src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
- VD Kona : DF200922-00146
- Anlayze the log when the problem is reproduced,
after inserting the try-catch block with log.
Co-authored-by: dongsug-song <35130733+dongsug-song@users.noreply.github.com>
- ACR:
> [NUI] Add try-catch block in New function (#2119)

- src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
ArgumentException will be thrown when column,row is a negative value other than AutoColumn/AutoRow.
- ACR:
> [NUI] change Column, Row default value from -1 to AutoColumn, AutoRow

- src/Tizen.NUI/src/public/Gesture.cs
- src/Tizen.NUI/src/public/Hover.cs
- src/Tizen.NUI/src/public/Key.cs
- src/Tizen.NUI/src/public/LongPressGesture.cs
- src/Tizen.NUI/src/public/PanGesture.cs
- src/Tizen.NUI/src/public/PinchGesture.cs
- src/Tizen.NUI/src/public/RotationGesture.cs
- src/Tizen.NUI/src/public/TapGesture.cs
- src/Tizen.NUI/src/public/Wheel.cs
No need to do Registry.GetManagedBaseHandleFromNativePtr().
- ACR: NONE
> [NUI] No need to do Registry.GetManagedBaseHandleFromNativePtr().

- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
In some profile, not all 3 theme files exists.
So the patch checks file existance not to make error messages.
- ACR:
> [NUI] Do not make error message when the profile theme file is not found

- src/Tizen.NUI/src/public/GLWindow.cs
Change orientation angle in GLWindow. It is same with NUI.Window.
GLWindow has window orientation angle enum type. It is different to NUI.Window.
This patch is for convienent both GLWindow and NUI.Window.
In addition, To be adjusted buffer commit by GLWindow application, the renderFrame callback function is changed.
This interface is not public, so, need not care for ACR.
> [NUI] change orientation angle in GLWindow

- src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs
- src/Tizen.NUI.Components/Controls/SelectGroup.cs
To support selecting multiple SelectButtons in SelectGroup,
bool EnableMultiSelected is added to SelectGroup.
By adding EnableMultiSelected in SelectGroup, RadioButtonGroup does not
need to implement its logic to prevent selecting multiple RadioButtons.
- ACR:
> [NUI] Add EnableMultiSelected to SelectGroup

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ThemeResourceSample.cs
This patch will fix build error caused by conflict between global::System.XXX
and Tizen.System.XXX namespace.
- ACR:
> [NUI] fix ThemeResourceSample build error

- src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
- src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
- src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
This patch fixes following build warnings and coding recommandations for Shadow.
* Fill missing API descriptions.
* Do not call overridable methods in constructors. (CA2214)
* Remove trailing white spaces.
* Remove unnecessary parentheses. (IDE0047)
- ACR:
> [NUI] Fix bulid warnings in Shadow

- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
> [NUI] fix a CA1507 warning

- src/Tizen.NUI/src/public/Theme/Theme.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
This patch fixes build warnings and Roslynator suggestions in Theme and ThemeManager.
CA2208 Instantiate argument exceptions correctly
CA1062 Validate arguments of public methods
IDE0044 Add readonly modifier
IDE0005 Remove unnecessary import
RCS1171 Simplify lazy initialization
- ACR:
> [NUI] Fill missing descriptions and fix build warnings for Theme

- src/Tizen.NUI/src/internal/Xaml/RegisterXNamesVisitor.cs
fix a CA2200 warning from RegisterXNamesVisitor.cs
- ACR:
> [NUI] fix a CA2200 warning

- src/Tizen.NUI/src/public/Animation.cs
[NUI] Add Animation Finished callback debug log temporarily
- To do debugging for the rare case when Finished event handler is not called.
none
> [NUI] Add Animation Finished callback debug log temporarily

- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
[NUI] Fix exception defect when LanguageChanged event has come
- LocaleLanguageChanged event should be unsubscribed when TextLabel, TextField, TextEditor are disposed.
none
> [NUI] Fix exception defect when LanguageChanged event has come

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Simple Test
```cs
//Default value test
bool Default_ExcludeLayouting = view.ExcludeLayouting; // False
FlexLayout.PositionType Default_FlexPositionType = FlexLayout.GetFlexPositionType(view); //Relative
// FlexPositionType test depending on ExcludeLayouting
view.ExcludeLayouting = true;
FlexLayout.PositionType FlexPositionType = FlexLayout.GetFlexPositionType(view); //Absolute
// ExcludeLayouting test depending on FlexLayout.SetFlexPositionType
FlexLayout.SetFlexPositionType(view, FlexLayout.PositionType.Relative);
bool ExcludeLayouting = view.ExcludeLayouting; // False;
```
- ACR:
> [NUI] synchronize View.ExcludeLayouting and FlexLayout.PositionType

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
`childrenCount` is added to count children that have false ExcludeLayouting.
And `CellPadding` is now respected regardless of exactly mode.
This patch will fix the following bugs.
1. In some cases, when CellPadding is set, children are misaligned.
2. If CellPadding is set and last child set ExcludeLayouting to true,
CellPadding is added to the end of items.
For more information on the issues, please see the comment of this
pull request.
- ACR:
> [NUI] fix CellPadding bugs on LinearLayout

- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Sicne the margin of FlexLayout will be handled by the parent layout,
we don't need to re-assign margin in `OnMeasure`.
- ACR:
> [NUI] remove unnecessary code that flex margin is assigned to flexlayout

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableBaseOutOfBoundSample.cs
This patch is to trigger ScrollOutOfBound event as pan gesture state,
and add pan direction & displacement into ScrollOutOfBound event.
Bound of ScrollOutOfBoundEventArgs is removed, because displacement
can be used for checking Top/Bottom.
none
> [NUI] Add direction & displacement into ScrollOutOfBound event.

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedImageViewTest.cs
The setter of AnimatedImageView.URLs was removed to resolve CA2227.
Therefore, the setter of AnimatedImageView.URLs in sample code is also
removed.
- ACR:
> [NUI] Fix not to use setter of AnimatedImageView.URLs

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
A property EnableOverShootingEffect is added. default is false.
And shadow would be raised to top when effect appears.
- ACR:
> [NUI] Enable/Disable overshooting effect for ScrollableBase.

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollableBaseOutOfBoundSample.cs
This patch is to add ScrollOutOfBoundWithDisplacement event,
and provide more information for ScrollOutOfBoundWithDisplacement
event handler.
Meanwhile old APIs of ScrollOutOfBound is not removed.
- ACR:
> [NUI] Add ScrollOutOfBoundWithDisplacement event.

- src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
[NUI] Fix wrong AnimationState after VectorAnimatedImageView playing stopped
none
> [NUI] Fix wrong AnimationState after VectorAnimatedImageView playing stopped

- src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
- To fix the build warning, replaced `Count()` method with `Any()` method
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1827
- N/A
> [NUI] Fix a build warning CA1827

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Wearable/src/public/WearableStyle/CircularPaginationStyle.cs
- src/Tizen.NUI/src/public/NUIConstants.cs
- src/Tizen.NUI/src/public/StyleManager.cs
- src/Tizen.NUI/src/public/Theme/ThemeManager.cs
- src/Tizen.NUI/src/public/Xaml/MarkupExtensions/NUIResourcePathExtension.cs
StyleManager uses dali singleton service which is not initialized in PreLoad().
Previously in Preload(), ThemeManager got framework resource path via static constant in StyleManager,
which leaded to initialize StyleManager instance that is not valid in PreLoad().
So this patch moved framework resource path constant to the constant file.
- ACR:
> [NUI] Fix not to get framework path via StyleManager

- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
when dismiss popup, the shadow does not disappear.
-An error occurs after changing the parent to GetParent ().
-layer of converting View is null.
- ACR:
> [NUI] Modify popup dismiss bug

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
- src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
- src/Tizen.NUI/src/public/VisualConstants.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ControlSample.cs
The CornerRadiusPolicy indicates whether the CornerRadius value is relative or absolute.
The default policy is absolute, which means the CornerRadius is an absolute float length.
If the policy is relative, the CornerRadius can have percentage value between 0.0f to 1.0f,
that is relative to the smaller of view's width and height.
- ACR:
> [NUI] Introduce CornerRadiusPolicy to View

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- ClipChildren clipping mode uses stencil buffer.
- But, scrollableBase is always pretended as rectangular shape so we can change it to ClipToBoundingBox that uses scissor.
- Usually, Scissor is better than stencil buffer for the performance. 
> [NUI] Change clipping mode of ScrollableBase

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
- src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/GridLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
This patch introduces `IterateLayoutChildren()` method that return
an enumerable collection of the child layouts that affected by parent
layout.
Independent children will be measured in `OnMeasureIndependentChildren()`.
By using `IterateLayoutChildren()`, we can remove the codes that check
whether child layout exclude from layout flow in `OnMeasure`. and api
users don't need to check `View.ExcludeLayouting` property in custom layouts.
- ACR:
> [NUI] separate layouting logic of the independent children

- src/Tizen.NUI/src/internal/ItemView.cs
- src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
- src/Tizen.NUI/src/public/Renderer.cs
- src/Tizen.NUI/src/public/Shader.cs
- src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
- src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
[NUI] Suppress CA1716, CA1052, CA1034 for deprecated APIs
- Since the detected classes will be deprecated, CA1716 warning message is suppressed.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1716
- This is conflict resolving patch for https://github.com/Samsung/TizenFX/pull/2374
none
> [NUI] Suppress CA1716, CA1052, CA1034 for deprecated APIs

- src/Tizen.NUI/src/internal/Application.cs
- src/Tizen.NUI/src/public/NUIApplication.cs
- When preload application, the show is called before the appcore is created.
- Call the window show at OnInit and notify the app core
- ACR:
> [NUI] Call show winodw on ApplicationInit

- src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
- Current implementation, we didn't check whether the Owner Property is null or not in the Layout method.
- This patch add null check of it to avoid null exception
> [NUI] Null check of Owner property of LayoutItem for Independent View.

- src/Tizen.NUI/src/internal/Disposable.cs
- src/Tizen.NUI/src/public/BaseHandle.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/TransitionOptions/TransitionOptions.cs
[NUI] Fix CA1063
- https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1063
- Every unsealed type that declares and implements the IDisposable interface must provide its own protected virtual void Dispose(bool) method. Dispose() should call Dispose(true), and the finalizer should call Dispose(false). If you create an unsealed type that declares and implements the IDisposable interface, you must define Dispose(bool) and call it. For more information, see Clean up unmanaged resources (.NET guide) and Dispose pattern.
if ACR is needed, I will raise new ACR request soon.
> [NUI] Fix CA1063

- src/Tizen.NUI/src/internal/DaliEventHandler.cs
- src/Tizen.NUI/src/public/Accessibility/AccessibilityManagerEvent.cs
> [NUI] Rename EventHandler WithReturnType to end in EventHandler

- src/Tizen.NUI/src/internal/Camera.cs
- src/Tizen.NUI/src/public/InputMethodContext.cs
- src/Tizen.NUI/src/public/UIComponents/ScrollViewEvent.cs
[NUI] Fix CS0108
https://docs.microsoft.com/ko-kr/dotnet/csharp/language-reference/compiler-messages/cs0108
'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
A variable was declared with the same name as a variable in a base class. However, the new keyword was not used. This warning informs you that you should use new; the variable is declared as if new had been used in the declaration.
https://code.sec.samsung.net/jira/browse/TCSACR-394
> [NUI] Fix CS0108

- src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
- src/Tizen.NUI/src/public/ImageLoading.cs
- src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
[NUI] Fix CA1054
- https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1054
- This rule splits the parameter name into tokens based on the camel casing convention and checks whether each token equals "uri", "Uri", "urn", "Urn", "url", or "Url". If there is a match, the rule assumes that the parameter represents a uniform resource identifier (URI). A string representation of a URI is prone to parsing and encoding errors, and can lead to security vulnerabilities. If a method takes a string representation of a URI, a corresponding overload should be provided that takes an instance of the Uri class, which provides these services in a safe and secure manner.
if ACR is needed, I will raise new ACR request soon.
> [NUI] Fix CA1054

- src/Tizen.NUI.Components/Controls/Control.cs
> [NUI] Initialize feedback only when the Feedback property is true

- src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
- src/Tizen.NUI/src/internal/NUICoreBackend.cs
stringDelegate registration is aledy called from the constructor.
- ACR:
> [NUI] Remove RegisterCallback function

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
ScrollBar.Unparent() is not working.
ScrollBar.Unparent() -> ScrollableBase.Remove(view)
Remove() of ScrollableBase is overridden to be removed based on ContentContainer.
ScrollBar Add
https://github.com/Samsung/TizenFX/blob/5b0849a02bda32613c9476a2b360464ed4e8e2fd/src/Tizen.NUI.Components/Controls/ScrollableBase.cs#L382
ScrollBar Remove
https://github.com/Samsung/TizenFX/blob/5b0849a02bda32613c9476a2b360464ed4e8e2fd/src/Tizen.NUI.Components/Controls/ScrollableBase.cs#L720
- ACR:
> [NUI] Fix ScrollBar Unparent bug

- src/Tizen.NUI/src/internal/Interop/Interop.ImageView.cs
- src/Tizen.NUI/src/internal/Interop/Interop.View.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WidgetView.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WidgetViewManager.cs
- src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
- src/Tizen.NUI/src/internal/NDalic.cs
- src/Tizen.NUI/src/public/Renderer.cs
- src/Tizen.NUI/src/public/WidgetView.cs
[NUI] Add internal and hidden APIs which are currently used
- Add internal and hidden APIs which are currently used. otherwise removing them causes build errors.
- Let users to use proper APIs by deleting these deprecated APIs
- User can be informed that these are deprecated and should not be used by warning messeges during build time.
none
> [NUI] Add internal and hidden APIs which are currently used

- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
[NUI] Fix the behavior as for View.BackgroundImage to be cleared when null set
- Change the behavior of View.BackgroundImage property from API9
- https://code.sec.samsung.net/jira/browse/GRE-2078
none
> [NUI] Fix the behavior as for View.BackgroundImage to be cleared when null set

- src/Tizen.NUI/src/public/BaseComponents/Style/Constants.cs
`ControlStates` enum will be removed in API10.
We can use `ControlState` class instead.
- ACR:
> [NUI] Add Obsolete Attribute for ControlStates enum

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/NavigatorSample.cs
Pages pushed into Navigator are disposed if Navigator is disposed.
To override Dispose() in Navigator, two dictionaries are required to
remove disposed navigator from dictionary.
TODO: Needs to consider how to remove disposed window from dictionary.
- ACR:
> [NUI] Override Dispose() in Navigator

- src/Tizen.NUI.Components/Controls/Pagination.cs
If IndicationSize is null,  CreateIndicator() will crash.
- ACR:
> [NUI] Fix the crash issue when IndicatorSize is null(Pagination).

- src/Tizen.NUI/src/internal/Application.cs
- src/Tizen.NUI/src/internal/DaliEventHandler.cs
Some callback and functions from DALi expected the calling convention to
be cdecl, this commit makes it right. The amd64 platforms this is rarely
a problem since arguments are passed through CPU registers, but in x86
this leads to stack corruption.
none
> [NUI] Use correct calling convention

- src/Tizen.NUI/src/internal/PropertyRangeManager.cs
- src/Tizen.NUI/src/internal/XamlBinding/MergedStyle.cs
Fix Svace issues for PropertyRangeManager.cs and MergedStyle.cs
- ACR:
> [NUI] Fix Svace issues

- src/Tizen.NUI/src/internal/DaliEnumConstants.cs
- src/Tizen.NUI/src/public/VisualConstants.cs
- src/Tizen.NUI/src/public/XamlBinding/Internals/IDynamicResourceHandler.cs
CA1716: Identifiers should not match keywords
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1716
- Change one hidden API. no ACR
- Since two enums are public APIs, Added suppress messages for CA1716 build warning, not fix them.
- ACR:
> [NUI] Fix CA1716 build warning

- src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Do not reset internal event callback. This can cause unexpected result
when user add event handler during package installation.
(user may not be able to listen the package event completely.)
N/A
> [Packagemanager] Fix registering internal event callback

- src/Tizen.NUI.Components/Controls/Loading.cs
- src/Tizen.NUI.Components/Style/LoadingStyle.cs
This fixes null pointer exception in Loading when running following sample,
```C#
var loading1 = new Loading(new LoadingStyle
{
Size = new Size(100, 100),
Position = new Position(0, 100),
Images  = imageArray
});
```
Plus, this patch removes redundant behaviors when applying a style to a Loading component.
All components copies a default style to the component properties when it is created.
When copying a style, all bindable properties defined in the style class that is not null value are copied to the component properties,
so it is important to keep null value for the property that is not set by user.
Hence this patch removes code that allocates empty list object in the getter of ImageList bindable property.
- ACR:
> [NUI] Fix null exception in Loading and improve code

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
I/DOTNET_LAUNCHER (P 2613, T 2617): Unhandled exception.
I/DOTNET_LAUNCHER (P 2613, T 2617): System.Runtime.InteropServices.COMException (0x8007007A):
The data area passed to a system call is too small.
I/DOTNET_LAUNCHER (P 2613, T 2617):  (0x8007007A)
I/DOTNET_LAUNCHER (P 2613, T 2617):    at System.StubHelpers.ValueClassMarshaler.ConvertToNative(IntPtr dst, IntPtr src,
IntPtr pMT, CleanupWorkListElement& pCleanupWorkList)
I/DOTNET_LAUNCHER (P 2613, T 2617):    at Tizen.Network.Bluetooth.BluetoothAdapterImpl.GetBondedDevices()
I/DOTNET_LAUNCHER (P 2613, T 2617):    at Tizen.Network.Bluetooth.BluetoothAdapter.GetBondedDevices()
I/DOTNET_LAUNCHER (P 2613, T 2617):    at Tizen.Network.Bluetooth.Tests.BluetoothAdapterTests.GetBondedDevices_RETURN_LIST_OF_DEVICES()
in …
> [Bluetooth][Non-ACR] Fix unhandled exception in GetBondedDevices()

- src/Tizen.NUI.Components/Utils/Selector.cs
- src/Tizen.NUI/src/internal/ActivatedSignalType.cs
- src/Tizen.NUI/src/internal/Alignment.cs
- src/Tizen.NUI/src/internal/Any.cs
- src/Tizen.NUI/src/internal/Application.cs
- src/Tizen.NUI/src/internal/Builder.cs
- src/Tizen.NUI/src/internal/ConnectionTrackerInterface.cs
- src/Tizen.NUI/src/internal/EventThreadCallback.cs
- src/Tizen.NUI/src/internal/KeyboardEventSignalType.cs
- src/Tizen.NUI/src/internal/KeyboardResizedSignalType.cs
- src/Tizen.NUI/src/internal/LanguageChangedSignalType.cs
- src/Tizen.NUI/src/internal/Model3dView.cs
- src/Tizen.NUI/src/internal/NUIWindowInfo.cs
- src/Tizen.NUI/src/internal/ObjectRegistry.cs
- src/Tizen.NUI/src/internal/PageTurnView.cs
- src/Tizen.NUI/src/internal/PropertyRangeManager.cs
- src/Tizen.NUI/src/internal/SWIGTYPE_p_CallbackBase.cs
- src/Tizen.NUI/src/internal/SWIGTYPE_p_Dali__CallbackBase.cs
- src/Tizen.NUI/src/internal/SWIGTYPE_p_Dali__FunctorDelegate.cs
- src/Tizen.NUI/src/internal/SignalObserver.cs
- src/Tizen.NUI/src/internal/SlotObserver.cs
- src/Tizen.NUI/src/internal/StatusSignalType.cs
- src/Tizen.NUI/src/internal/TouchPoint.cs
- src/Tizen.NUI/src/internal/TouchPointContainer.cs
- src/Tizen.NUI/src/internal/Uint16Pair.cs
- src/Tizen.NUI/src/internal/ViewImpl.cs
- src/Tizen.NUI/src/internal/WatchApplication.cs
- src/Tizen.NUI/src/public/Property.cs
> [NUI] Remove since_tizen tag for internal APIs

- src/Tizen.NUI/src/public/DirectionBias.cs
CA1712: Do not prefix enum values with type name
The name can not be changed becuase this enum is publicly open.
Suppress warning messages.
- ACR:
> [NUI] Fix build warning CA1712

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
> [NUI] remove unused measure specification size properties of View class

- src/Tizen.NUI/src/public/BaseComponents/View.cs
> [NUI] remove redundant private field in View class

- .gitignore
- coverage.sh
_This script uses a repository in Samsung internals_
steps for calculating the coverage of a specific module:
1. **Instrument**
./coverage.sh -i [Module Name]     ( ex: ./coverage.sh -i Tizen.Applications.Common )
2. **Change runtime assemblies with instrumented one**
./coverage.sh -c [Module Name]    ( emulator or target device should be connected via sdb connection before )
3. **Run TCT**
4. **Generate Report**
./coverage.sh -r [Module Name]     ( report will be generated in Artifacts/coverage/[Module Name] directory )
> [Build] Add coverage.sh script

- src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
Device is not bonded : System.NullReferenceException: Object reference not set to an instance of an object.
at System.SpanHelpers.IndexOf(Byte& searchSpace, Byte value, Int32 length)
at System.String.Ctor(SByte* value)
at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr ptr)
at Tizen.Network.Bluetooth.BluetoothUtils.ConvertStructToDeviceClass(BluetoothDeviceStruct device)
at Tizen.Network.Bluetooth.BluetoothAdapterImpl.GetBondedDevice(String address)
at Tizen.Network.Bluetooth.BluetoothAdapter.GetBondedDevice(String address)
- ACR:
> [Bluetooth][Non-ACR] Fix unhandled exception in GetBondedDevice()

- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
Since we can take the size value using `Size2DProperty`, we don't need to
save Size2D value in local value.
It will save a bit of memory.
- ACR:
> [NUI] use Size2DProperty for GetNaturalSize() instead of local field

- src/Tizen.NUI/src/internal/Disposable.cs
- src/Tizen.NUI/src/public/BaseHandle.cs
- src/Tizen.NUI/src/public/CustomViewRegistry.cs
- src/Tizen.NUI/src/public/InputMethodContext.cs
- src/Tizen.NUI/src/public/KeyValue.cs
- src/Tizen.NUI/src/public/Layouting/LayoutTransition.cs
- src/Tizen.NUI/src/public/Layouting/MeasureSpecification.cs
CA1051: Do not declare visible instance fields
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1051
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-396
> [NUI] Deprecate visible instance fields [CA1051]

- src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
This patch will fix bug that `GridLayout.ColumnSpan` and `GridLayout.RowSpan`
doesn't work in xaml.
For more information of the issue, please refer to https://github.com/Samsung/TizenFX/pull/2468.
- ACR:
> [NUI] add type check validation in ApplyPropertiesVisitor

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
If we change size2D by using Size2DProperty, size specification is not
changed. this patch will fix that issue.
Here is sample code:
```cs
View view = new View();
view.Size2D = new Size2D(100, 50);
Tizen.Log.Error("NUI", $"WidthSpecification : {view.WidthSpecification}, HeightSpecification : {view.HeightSpecification}");
View view2 = new View();
view2.SetValue(View.Size2DProperty, new Size2D(100, 50));
Tizen.Log.Error("NUI", $"WidthSpecification : {view2.WidthSpecification}, HeightSpecification : {view2.HeightSpecification}");
```
Before:
```
WidthSpecification : 100, HeightSpecification : 50
WidthSpecification : -2, HeightSpecification : -2
```
After:
```
WidthSpecification : 100, HeightSpecification : 50
WidthSpecification : 100, HeightSpecification : 50
```
- ACR:
> [NUI] change size specification in changed callback of bindable property

- src/Tizen.NUI/src/internal/Layouting/Interop/Interop.FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
In `FlexLayout`, when we add new view, the existing view shrink.
but when removed they are in shrinked state. they should change back.
To fix this issue, this patch remove internal child(child of yoga
layout) when child view of `FlexLayout` is removed.
For now, `OnChildRemove` API will work correctly.
Thanks Aman Jeph for the report.
- ACR:
> [NUI] remove internal child properly when child view of FlexLayout is removed

- src/Tizen.NUI/src/internal/Layouting/RelativeLayout.cs
- src/Tizen.NUI/src/public/Layouting/RelativeLayout.cs
For now child's `Margin` and RelativeLayout's `Padding` work correctly.
Here is Sample xaml code:
```xaml
<View  x:Class="ThemeResourceDemo.XamlPage"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
x:Name="Parent"
Padding="50,50,50,50"
BackgroundColor="0.99,0.99,0.33,1">
<View.Layout>
<RelativeLayout/>
</View.Layout>
<View x:Name="RedRect"   BackgroundColor="1,0,0,1" WidthSpecification="100" Margin="0, 100, 0, 0"
RelativeLayout.FillVertical="true" RelativeLayout.BottomRelativeOffset="1.0"/>
<View x:Name="GreenRect" BackgroundColor="0,1,0,1"
RelativeLayout.FillHorizontal="true" RelativeLayout.FillVertical="true"
RelativeLayout.LeftTarget="RedRect" RelativeLayout.LeftRelativeOffset="1.0"
RelativeLayout.RightRelativeOffset="1.0" …
```
> [NUI] respect margin and padding for relative layout

- src/Tizen.NUI/src/internal/FrameBroker/DefaultFrameBroker.cs
- src/Tizen.NUI/src/public/Animation.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/XamlBinding/Transition.cs
Fix CA1819.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1819
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-395
> [NUI] Fix CA1819 : Properties should not return arrays

- src/Tizen.NUI/src/internal/Interop/Interop.WidgetViewManager.cs
- src/Tizen.NUI/src/public/NUIApplication.cs
- src/Tizen.NUI/src/public/WidgetViewManager.cs
WidgetViewManager provide API for delete widgetView instead TerminateWidget().
TerminateWidget() will be deprecated.
- ACR:
> [NUI] Add API for delete widgetView

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
before, ImageView calculate desired size using GetOriginalImageSize()
but this api does not consider rotate value
so i changed it
- ACR:
> [NUI] fix bug when setting desired size in ImageView

- src/Tizen.NUI/src/internal/Camera.cs
- src/Tizen.NUI/src/internal/ItemView.cs
- src/Tizen.NUI/src/internal/RenderTask.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/TableView.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Container.cs
- src/Tizen.NUI/src/public/CustomView/Spin.cs
- src/Tizen.NUI/src/public/Layer.cs
- src/Tizen.NUI/src/public/Window.cs
- src/Tizen.NUI/src/public/XamlBinding/Interactivity/DataTrigger.cs
- src/Tizen.NUI/src/public/XamlBinding/Trigger.cs
Property names should not match get methods
https://docs.microsoft.com/ko-kr/dotnet/fundamentals/code-analysis/quality-rules/ca1721
- ACR:
> [NUI] Fix CA1721 warnings (#2541)

- src/Tizen.NUI/src/internal/Interop/Interop.WebBackForwardList.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebContext.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebCookieManager.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebBackForwardList.cs
- src/Tizen.NUI/src/internal/WebContext.cs
- src/Tizen.NUI/src/internal/WebCookieManager.cs
- src/Tizen.NUI/src/internal/WebSettings.cs
- src/Tizen.NUI/src/internal/WebView.cs
Originally only WebView is used to add new APIs, it will become
bigger, and be hard to maintain.
This patch is to move some related APIs into a class like WebContext,
WebSettings, etc.
And it also adds some new APIs like WebBackForwardList, etc.
- ACR:
> [NUI] Add some new APIs like Context, Settings, etc.

- src/Tizen.NUI/src/internal/Interop/Interop.WebBackForwardList.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebContext.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebCookieManager.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebBackForwardList.cs
- src/Tizen.NUI/src/internal/WebContext.cs
- src/Tizen.NUI/src/internal/WebCookieManager.cs
- src/Tizen.NUI/src/internal/WebSettings.cs
- src/Tizen.NUI/src/internal/WebView.cs
Originally only WebView is used to add new APIs, it will become
bigger, and be hard to maintain.
This patch is to move some related APIs into a class like WebContext,
WebSettings, etc.
And it also adds some new APIs like WebBackForwardList, etc.
- ACR:
> [NUI] Add some new APIs like Context, Settings, etc. (#2419)

- src/Tizen.NUI/src/internal/XamlBinding/MergedStyle.cs
Fix svace issue for MergeStyle
- ACR:
> [NUI] Fix svace issue for MergeStyle

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
- src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextField.cs
- src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
The value of FontSizeScale will be used for multiplying the given PointSize.
If FontSizeScale.UseSystemSetting, will use the SystemSettings.FontSize internally.
- Added (hidden):
float Tizen.NUI.BaseComponents.TextLabel.FontSizeScale { set; get; }
float Tizen.NUI.BaseComponents.TextField.FontSizeScale { set; get; }
float Tizen.NUI.BaseComponents.TextEditor.FontSizeScale { set; get; }
struct Tizen.NUI.FontSizeScale { public const float UseSystemSetting = -1.0; }
> [NUI] Add FontSizeScale property in TextLabel, TextField and TextEditor

- src/Tizen.NUI/src/internal/Common/Disposable.cs
- src/Tizen.NUI/src/public/Common/BaseHandle.cs
- src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
- 'disposedThis' blocks the release of memory.
- modified by this patch.
-> https://github.com/Samsung/TizenFX/pull/2381
- ACR:
> [NUI] Fix Dispose memory leak issue

- src/Tizen.NUI.Components/Controls/Control.cs
- src/Tizen.NUI.Components/Style/ControlStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
- src/Tizen.NUI.Wearable/src/internal/Theme/DefaultTheme.cs
- src/Tizen.NUI.Wearable/src/public/CircularPagination.cs
- src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
- src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
- src/Tizen.NUI.Wearable/src/public/CircularSlider.cs
To use package theme creator multiple times after it registered,
it needs to register the instance itself, as so the singleton pattern introduced for it.
- ACR:
> [NUI] Improve package theme creator

- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
> [NUI] Fix Selector bug and add new clone method

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView.cs
- src/Tizen.NUI/src/internal/WebViewScrollEdgeReachedEventArgs.cs
- src/Tizen.NUI/src/internal/WebViewScrollEdgeReachedSignal.cs
1) ScrollPosition, ScrollSize, ContentSize properties are added.
2) ScrollBy is added.
3) ScrollEdgeReached events are notified when scrolled to edge.
4) Support program argument in WebView constructor to control chromium scroll options.
- ACR:
> [NUI] Support scroll in WebView.

- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
Video hole is used for playing videos with high quality in WebView.
This patch is to add a VideoHoleEnabled property.
- ACR:
> [NUI] Add a VideoHoleEnabled property into WebView.

- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Register a callback when Layout is first used.
- ACR:
> [NUI] Change LayoutController process

- src/Tizen.NUI/src/internal/Common/RenderTask.cs
- src/Tizen.NUI/src/internal/Utility/Camera.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/TableView.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/Common/Container.cs
- src/Tizen.NUI/src/public/Common/Layer.cs
- src/Tizen.NUI/src/public/XamlBinding/Interactivity/DataTrigger.cs
- src/Tizen.NUI/src/public/XamlBinding/Trigger.cs
CA1721: Property names should not match get methods
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1721
- ACR:
> [NUI] Fix CA1721 warnings of Public APIs

- src/Tizen.NUI/src/public/Application/NUIApplication.cs
Since libcapi-appfw-tizen-theme.so has not released to the binary yet,
the related code should be disabled.
- ACR:
> [NUI] Disable Tizen Theme Manager code

- src/Tizen.NUI/Tizen.NUI.csproj
* This enables building Tizen.NUI as a reference in Visual Studio
project.
Removed ProjectReference of Tizen.Applications.ThemeManager from Tizen.NUI.csproj
none
> [NUI] Removed old dependency in Tizen.NUI.csproj

- src/Tizen.NUI.Components/Controls/Scrollbar.cs
There was a copy & paste error in vertical scroll position calculator in a scrollbar.
- ACR:
> [NUI] Fix vertical scrollbar position bug

- src/Tizen.WebView/Interop/Interop.ChromiumEwk.Context.cs
- src/Tizen.WebView/Interop/Interop.ChromiumEwk.InterceptRequest.cs
- src/Tizen.WebView/Tizen.WebView.sln
- src/Tizen.WebView/Tizen.WebView/Context.cs
- src/Tizen.WebView/Tizen.WebView/RequestInterceptor.cs
This patch adds internal APIs to support request intercept.
Plus, adds APIs for remote inspect.
- ACR:
> [WebView] Support request intecept

- src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsData.cs
- src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsInfo.cs
* [MachineLearning.Inference] Update the version number of the shared library
This patch updates the version number of the nnstreamer library.
* libcapi-nnstreamer.so.0 -> libcapi-nnstreamer.so.1
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>
* [MachineLearning.Inference] Remove the name comparision in TensorsInfo.Equals()
Since the name of the TensorsInfo is not used when negociating the
pipeline, the name comparison in TensorsInfo.Equals() should be removed.
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>
* [MachineLearning.Inference] Add Clone() to TensorsInfo class for deep copy
It is not a common case but developers can modify the TensorsInfo after
creating the TensorsData. Because of this reason, TensorsData should
have a hard-copied instance of the TensorsInfo …
> [MachineLearning.Inference][Non-ACR] Fix the potential bug (#2547)

- src/Tizen.NUI/src/public/Input/InputMethodContext.cs
[NUI] Deprecate swigCMemOwn which is not used
https://code.sec.samsung.net/jira/browse/TCSACR-394
> [NUI][ACR] Deprecate swigCMemOwn which is not used

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
This commit fixes a bug where it was possible to select multiple radio
buttons from one RadioButtonGroup in accessibility (screen reader) mode.
OnAccessibilityActivated() contained code copied from OnKey(). However,
some classes derived from Button override OnKey(), e.g. SelectButton
makes sure that other buttons in the group are unselected if necessary.
Rather than overriding OnAccessibilityActivated() in derived classes, it
is better to invoke OnKey() instead, in order to reduce code
duplication.
Note: this change matches the corresponding logic in DALi Toolkit, where
OnAccessibilityActivated() is implemented in terms of OnKeyboardEnter().
- ACR: None
- Added: None
- Changed: None
> [NUI] Delegate Button.OnAccessibilityActivated() to OnKey()

- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
[NUI] Enable Window.ViewAdded event
- Previously, Window.ViewAdded event was blocked by memory leak
- This is enabled again by the request from Appium
- This change has beend checked locally and there was no memory leak (normal)
- https://code.sec.samsung.net/jira/browse/GRE-2226
none
> [NUI] Enable Window.ViewAdded event

- src/Tizen.NUI.Components/Tizen.NUI.Components.csproj
Tizen.NUI.preload -> 30
Tizen.NUI.Components.preload ->31
The Tizen.NUI.Componentes is preloaded after the NUI is preloaded.
- ACR:
> [NUI] Change Tizen.NUI.Components sequence

- src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
> [NUI] Fix AccessibilityManager's unsafe conversion to View from IntPtr

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
Since the pushed views are added to NavigationPages and are disposed in
Navigator.Dispose(), the CA2000 in Navigator is false alarm.
To remove the CA2000 false alarm, SuppressMessage for CA2000 is added.
- ACR:
> [NUI] Remove CA2000 false alarm in Navigator

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
To calculate its children (i.e. Page) size correctly, Navigator sets
AbsoluteLayout to its Layout.
- ACR:
> [NUI] Set Navigator Layout

- src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
Default touchable area is view's size.
TouchArea can reset the view's touchable area.
This is usefull when the view is small, but it should have a larger touch area.
for example
View view = new View();
view.Size = new Size(10, 10);
view.TouchEvent += OnTouchEvent;
view.TouchArea = new Size2D(200, 200);
The view is small, If you want to set the touch area to a larger area,
you can use the TouchArea property.
- ACR:
> [NUI] Add TouchArea property.

- src/Tizen.NUI/src/internal/Common/DaliEventHandler.cs
Since T, U, R are commonly used as generic type parameter names and not
to do ACR, StyleCop CA1715 warning messages in DaliEventHandler.cs are
removed.
- ACR:
> [NUI] Remove StyleCop CA1715 warning messages

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Add ScrollPosition in ScrollEventArgs.
Current Position property in ScrollEventArgs is position of
ContentContainer which is negative.
user controls scrollableBase via ScrollTo and other API with
positive position of pan not ContentContainer so user must convert
current Position Property to use.
By this patch, we provide positive ScrollPosition which represent
position of scroll pan, so no need to convert value for using it.
No API Changes.
> [NUI] : Add ScrollPosition in ScrollEventArgs for user convenience.

- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
If Layout is a LayoutItem then it could be a View that handles it's own padding.
Let the View keeps it's padding.  Still store Padding in Layout to reduce code paths.
- ACR:
> [NUI] Create TextLayout when parent has layout

- src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
The crash issue occurred when C library released memory for string attribute.
So I modified to use Malshal class instead of GCHandle.
There is no need for ACR.
> [Inputmethod] Fix the crash issue when setting PreEditString's attribute

- src/Tizen.NUI/src/public/Input/InputMethodContext.cs
- InputPanelLanguage.Alphabet enumeration can be changed
according to OSD language.
- For instance, if OSD language is not Latin alphabet, such as Korean and Arabic,
IME default language would change to English.
If OSD language is Latin alphabet, such as French and Spanish,
IME default language would be OSD language itself.
- N/A
> [NUI] Update InputPanelLanguage enum description

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
* Button text ellipsis when the text is longer than the button width.
* Switch thumb can get control state changed callback from parent.
* Button IconPadding is ignored when the icon is not exist.
* Button TextPadding is ignored when the text is not exist.
- ACR:
> [NUI] Button text ellipsis enabled and etc.

- src/Tizen.NUI.Components/Controls/TabBar.cs
- src/Tizen.NUI.Components/Controls/TabButton.cs
- src/Tizen.NUI.Components/Controls/TabButtonGroup.cs
TabButton does not change its state to unselected if button or key is
unpressed while its state is selected.
Previously, TabButton invoked duplicate SelectedChanged if button or key
is unpressed while its state is selected.
Now, TabButton does not invoke duplicate SelectedChanged if button or
key is unpressed while its state is selected.
- ACR:
> [NUI] Fix TabButton not to invoke duplicate SelectedChanged

- src/Tizen.NUI/src/internal/Interop/Interop.Capture.cs
- src/Tizen.NUI/src/public/Capture.cs
Some devices those have old gpu driver cannot use NativeImageSource for Capture.
This patch adds more option to use captured buffer with uri directly
> [NUI] Make possible to capture on the old driver devices.

- src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
- src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs
This patch creates the thread lock for event handlers and removes other useless thread locks.
- No ACR
> [Tts/Stt] Use thread lock only when add and remove event handler

- src/Tizen.NUI.Components/Controls/Progress.cs
- Should have added null check for indeterminateImage instance
- N/A
> [NUI] Fix NUI.Components test case fail

- src/Tizen.NUI.Components/Controls/TabBar.cs
- src/Tizen.NUI.Components/Controls/TabButton.cs
- src/Tizen.NUI.Components/Style/TabButtonStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultTheme.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
To apply the latest TabButton UX, TabButtonStyle class is added.
TabButtonStyle.TopLine and TabButtonStyle.BottomLine are displayed when
TabButton is pressed or selected.
TabButtonStyle.PaddingIcon is applied as Padding when Icon or Icon with
Text is displayed.
TabButtonStyle.PaddingText is applied as Padding when only Text is
displayed.
TabButtonStyle.IconTextPadding is applied as Padding between Icon and
Text.
- ACR:
> [NUI] Add TabButtonStyle class with the latest TabButton UX

- src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
* Selector implements ICollection to get priority of items.
* property getters don't throw an exception.
- ACR:
> [NUI] Selector class implements ICollection and etc.

- src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
args[0] value is this.
->Tizen.NUI, Version=4.0.0.0, Culture=neutral, PublicKeyToken=eba370b203a2e242
So can't set using argument value.
ex) dotnet run --width 100 --height --100
- ACR:
> [NUI] Fix argument issue when launch application on ubuntu

- src/Tizen.NUI/src/internal/Application/Application.cs
- src/Tizen.NUI/src/public/Window/Window.cs
If call Window.Instance before initializing, Window.Instance is always null
- ACR:
> [NUI] Fix Window.Instance null issue

- src/Tizen.NUI/src/public/Common/PropertyMap.cs
Add extension method to help use `PropertyMap` class
Currently, NUI developer have to create a temporary `PropertyValue` object to set a value on `PropertyMap` like below
``` c#
temp = new PropertyValue((int)panelLayout);
outputMap.Add("PANEL_LAYOUT", temp);
temp.Dispose();
PropertyValue temp = new PropertyValue(alphaFunction);
animator.Add("alphaFunction", temp);
temp.Dispose();
```
But, now easily can set with primitive value like below
``` c#
outputMap.Add("PANEL_LAYOUT", (int)panelLayout);
animator.Add("alphaFunction", alphaFunction);
```
And also easily inlining a propertMap build code without wasted memory 
``` c#
FontStyle = new PropertyMap().Add("weight", new PropertyValue("light")),
```
`new PropertyValue("light")` is disposable object and no more used after create `PropertyMap` …
> [NUI] Add extension method to help use PropertyMap class

- src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
add null check,
It can try to layout the view that has already been released.
- ACR:
> [NUI] Add null check in LayoutController.Process

- src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/Common/Vector4.cs
- src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
- src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
Note that, only X value of Vector4 will be applied to the view until dali support it.
- ACR:
> [NUI] Change CornerRadius type to Vector4 from float

- src/Tizen.NUI/src/internal/Common/StringToVoidSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.StringToVoidSignal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
This commit must be merged first: https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/256117/
This pull request allows to return result to caller of Dali::Signal<>::Emit() by first parameter.
In this case Bridge implemented inside dali is the caller.
This pull request also remove Emit function from C# api.
Emit function should be used only by Bridge and there is
no reason to allow call of this function from C# api.
NONE
> [NUI][AT-SPI] Improve StringToVoid implementation

- src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AppBarSample.cs
To enhance usability, some APIs are added and removed as follows.
Title and Actions are added to set these properties with constructor.
SetTitle(), AddActions() and RemoveActions() are removed because the
above Title and Actions cover theses methods.
Comment's indentation is also fixed.
- ACR:
> [NUI] AppBar code refactoring

- src/Tizen.WebView/Interop/Interop.ChromiumEwk.Context.cs
- src/Tizen.WebView/Interop/Interop.ChromiumEwk.InterceptRequest.cs
- src/Tizen.WebView/Tizen.WebView.sln
- src/Tizen.WebView/Tizen.WebView/Context.cs
- src/Tizen.WebView/Tizen.WebView/RequestInterceptor.cs
This patch is cherry-picked from API8.
This patch adds internal APIs to support request intercept.
Plus, adds APIs for remote inspect.
Signed-off-by: yh106.jung <yh106.jung@samsung.com>
- ACR:
> [WebView] Support request intercept

- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
using List<T> Data Structure is redundant in MeasureFirst case,
and it makes worse sometimes for searching indexed item's position.
In MeasureFirst, every item has same size,
thus we can calculate it's position in linear or grouped cases.
- ACR:
> [NUI] Optimizing item positioning on MeasureFirst

- src/Tizen.NUI.Components/Controls/Navigation/DialogPage.cs
To pass touch event when DialogPage's Scrim is disabled, DialogPage's
EnableControlState is set to be false.
- ACR:
> [NUI] Fix to pass touch event when DialogPage's Scrim is disabled

- src/Tizen.NUI/src/internal/Xaml/XamlParser.cs
1. Fix gather assembly for xaml
- ACR:
> [NUI] Fix gather assembly for xaml

- src/Tizen.NUI/src/internal/Interop/Interop.WebCertificate.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebHttpAuthHandler.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebCertificate.cs
- src/Tizen.NUI/src/internal/WebView/WebHttpAuthHandler.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebViewCertificateReceivedEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewCertificateReceivedSignal.cs
- src/Tizen.NUI/src/internal/WebView/WebViewHttpAuthRequestedEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewHttpAuthRequestedSignal.cs
This patch is to implement ssl certificate & http authentication
of WebView.
- ACR:
> [NUI] Implement certificate & authentication APIs of WebView.

- src/Tizen.NUI/src/internal/Interop/Interop.WebConsoleMessage.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebHttpRequestInterceptor.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebPageLoadError.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebConsoleMessage.cs
- src/Tizen.NUI/src/internal/WebView/WebHttpRequestInterceptor.cs
- src/Tizen.NUI/src/internal/WebView/WebPageLoadError.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebViewConsoleMessageReceivedEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewConsoleMessageReceivedSignal.cs
- src/Tizen.NUI/src/internal/WebView/WebViewFormRepostPolicyDecidedEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewHttpRequestInterceptedEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewHttpRequestInterceptedSignal.cs
This patch is to implement WebView APIs for http request
interceptor, console message and page loading error.
- ACR:
> [NUI] Implement APIs for request interceptor, console message, etc

- src/Tizen.NUI/src/internal/Interop/Interop.WebContextMenu.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebContextMenuItem.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebContextMenuItemList.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebPasswordData.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebSecurityOrigin.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebSecurityOriginList.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebContextMenu.cs
- src/Tizen.NUI/src/internal/WebView/WebContextMenuItem.cs
- src/Tizen.NUI/src/internal/WebView/WebContextMenuItemList.cs
- src/Tizen.NUI/src/internal/WebView/WebPasswordData.cs
- src/Tizen.NUI/src/internal/WebView/WebSecurityOrigin.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebViewContextMenuCustomizedEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewContextMenuCustomizedSignal.cs
- src/Tizen.NUI/src/internal/WebView/WebViewContextMenuItemSelectedEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewContextMenuItemSelectedSignal.cs
This patch is to implement context menu APIs of webview.
It is related to the patch at csharp-binder side:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/254415/
- ACR:
> [NUI] Implement context menu APIs of webview.

- src/Tizen.NUI/src/internal/Interop/Interop.WebHitTest.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebHitTestResult.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
This patch is to implment hit test APIs of webview.
It is related to the patch at csharp-binder side:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/254359/
- ACR:
> [NUI] Implement hit test APIs of webview.

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/ItemSizingStrategy.cs
Currently CollectionView only support MeasureFirst,
and MeasureAll need to be implemented.
before this feature is ready,
make setter internal to disallow unimplemented mode.
- ACR:
> [NUI] set Internal SizingStrategy to hide MeasureAll option.

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
propagate BindingContext to chlidren and descendant recursively
for applying binding on DataTemplate.
- previously
RecyclerItemView
|_ Child View - BindingContext Propagated
|_ GrandChild View BindingContext Not Propagated
- from now on
RecyclerViewItem
|_ Child View - BindingContext Propagated
....
|_ Descendant View - BindingContext Propagated.
Yet user has to set IsCreateByXaml true for using SetBinding() in cs code,    
will be renamed IsBinded property with automatically set by SetBinding().
> [NUI] Propgate BindingContext recursively on RecyclerViewItem.

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
currently create two collectionView can be aborted while
accessing padding of layouter style.
use "using" keyword as GetViewStyle simply Copy the original
ViewStyle and will be disposed by using keyword,
but it occurs crash as CopyFrom only new the parent and copy
all existing values.
This looks issue on CopyFrom but to fix collectionView issue quickly,
remove using keyward on first step.
Need to discuss more regarding the issue.
- ACR:
> [NUI] fix crash on collecitonView which looks like bug action..

- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
- test/NUITestSample/NUITestSample/examples/AtspiTest.cs
This patch is for removing following build warnings.
(1) Do not nest type SayFinishedEventArgs. Alternatively,
change its accessibility so that it is not externally visible.
(2) Only FlagsAttribute enums should have plural names
- ACR:
> [NUI][ATSPI] remove build warning messages

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/ItemSelectionMode.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/CollectionViewGridSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/CollectionViewLinearSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewGridGroupSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CollectionViewDemo/Group/CollectionViewLinearGroupSample.cs
Change names in ItemSelectionMode
SingleSelection and MultipleSelections overlapped "Selection" keyward
with their enum name.
Removing Unnecessary keyward from enum members,
and adding Suppress condition to avoid CA1720 warnings.
Single is class Identifier name but there are no harm to using name
Single in a member of enum.
Single allow deselection by clicking selected item again,
but we have another demands who want to act single selection like radio,
which always have one single selected item after once selected.
this Singlelways for that demands,
even click again on selected item, item will not deselected,
and will not occurs any SelectionChanged events.
- ACR:
> [NUI] Refactoring itemSelectionMode names and adding SingleAlways

- src/ElmSharp/ElmSharp/EcoreEvent.cs
Fix EcoreEvent handler logic which does not remove event handler properly.
When event handler is removed from `On`, it should also be removed from the inner list containing handlers
so it does not try removing at `Dispose()` again.
- None
> [ElmSharp] Fix EcoreEvent

- src/Tizen.NUI.Components/Utils/Utility.cs
Setting a value to method parameter does not work unless the method
parameter is defined with out keyword.
Not to confuse users, setting null to method parameter is removed.
- ACR:
> [NUI] Fix Utility.Dispose not to set null to method parameter

- src/Tizen.NUI/src/internal/Interop/Interop.GLWindow.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
- src/Tizen.NUI/src/public/Window/GLWindow.cs
Add GLWindow rendering mode.
It has two mode as continuous and on demand.
If the mode is continuous, the rendering user callback is called continuously.
If the mode is on demand, the rendering user callback is called by call renderOnce().
- ACR:
> [NUI] Add GLWindow Rendering mode

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
- src/Tizen.NUI.Components/Controls/Navigation/Page.cs
This is ACR patch to make Page Navigation APIs public.
This pull request includes properties and methods of Navigator and Page
classes.
NavigationPages are not going to be public not to make List<T> public
API.
To cover the usage of NavigationPages, the following APIs are added.
- public int PageCount
- public Page GetPage(int index)
- public int IndexOf(Page page)
- ACR: TCSACR-417
> [NUI] Make Page Navigation APIs public

- src/Tizen.NUI/src/internal/EXaml/Operation/SetProperty.cs
> [NUI] Fix contradictory code in SetProperty

- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AlertDialogSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DialogSample.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/MenuSample.cs
Not to provide List property to users, NavigationPages is removed from
Navigator class.
Instead of NavigationPages.Count, PageCount is added to Navigator class.
- ACR:
> [NUI] Replace NavigationPages.Count with PageCount

- src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
- src/Tizen.NUI.Components/Style/DefaultGridItemStyle.cs
- src/Tizen.NUI.Components/Theme/DefaultThemeCommon.cs
…ultGridItem.
TextLabel property is commonly named Label so the name Caption can makes
confusing.
Change Caption to Label on DefaultGridItem and its style,
and change CaptionRelativeOrientation property to LabelOrientationType.
this patch also @fix the Tizen.NUI.Samples build error.
- ACR:
> [NUI] Change property name Caption to Label and related names on DefaultGridItem

- src/Tizen.NUI.Components/Style/ButtonStyle.cs
- src/Tizen.NUI.Components/Style/DatePickerStyle.cs
- src/Tizen.NUI.Components/Style/DefaultGridItemStyle.cs
- src/Tizen.NUI.Components/Style/DefaultLinearItemStyle.cs
- src/Tizen.NUI.Components/Style/DefaultTitleItemStyle.cs
- src/Tizen.NUI.Components/Style/ImageScrollBarStyle.cs
- src/Tizen.NUI.Components/Style/LoadingStyle.cs
- src/Tizen.NUI.Components/Style/Navigation/AppBarStyle.cs
- src/Tizen.NUI.Components/Style/PaginationStyle.cs
- src/Tizen.NUI.Components/Style/PickerStyle.cs
- src/Tizen.NUI.Components/Style/ProgressStyle.cs
- src/Tizen.NUI.Components/Style/RecyclerViewItemStyle.cs
- src/Tizen.NUI.Components/Style/SliderStyle.cs
- src/Tizen.NUI.Components/Style/SwitchStyle.cs
- src/Tizen.NUI.Components/Style/TabButtonStyle.cs
- src/Tizen.NUI.Components/Style/TimePickerStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
The duplicate documentation of BindableObject.CopyFrom is replaced with
inheritdoc.
- ACR:
> [NUI] Replace duplicate documentation of CopyFrom with inheritdoc

- src/Tizen.NUI/src/public/Common/BaseHandle.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
Deprecate BaseHandle.PropertySet and Add BindableProperty.PropertyChanged
PropertySet has been added before the NUI XAML is added.
PropertySet is duplicated of PropertyChanged so it can be deprecated.
BindableProperty class is parent of BaseHandle class, so PropertyChanged is better to be used.
https://code.sec.samsung.net/jira/browse/TCSACR-413
> [NUI] Deprecate BaseHandle.PropertySet and Add BindableProperty.PropertyChanged

- src/Tizen.NUI/src/internal/WebView/WebView.cs
> [NUI] Fix crash issue when favicon is null.

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
ItemsLayouter is nullable handle so it is checked before it is
dereferenced.
- ACR:
> [NUI] Fix not to dereference nullable handle ItemsLayouter

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
nullable members need to be check it is null or not,
and carefully null set after disposing.
- ACR:
> [NUI] fix nullable member access code to prevent future crash.

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
nullable members need to be check it is null or not,
and carefully null set after disposing.
- ACR:
> fix nullable member access code to prevent future crash.

- src/Tizen.NUI/src/internal/Interop/Interop.WebPolicyDecisionMaker.cs
- src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebPolicyDecisionMaker.cs
- src/Tizen.NUI/src/internal/WebView/WebView.cs
- src/Tizen.NUI/src/internal/WebView/WebViewResponsePolicyDecidedEventArgs.cs
- src/Tizen.NUI/src/internal/WebView/WebViewResponsePolicyDecidedSignal.cs
Originally new window policy is not needed, actually response policy is needed.
This patch is to rename functions related to policy decision.
The patch related to csharp-binder :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/257751/
- ACR:
> [NUI] Rename functions, variables, etc related to policy decision.

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
- src/Tizen.NUI.Components/Controls/Button.cs
- src/Tizen.NUI.Components/Controls/Dialog.cs
- src/Tizen.NUI.Components/Controls/Popup.cs
- src/Tizen.NUI.Components/Controls/SelectButton.cs
- src/Tizen.NUI.Components/Controls/Switch.cs
- src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEnum.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
Replace class AccessibilityStates with enum flag.
Requires:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/256381/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/257412/
Simplify usage of AccessibilityStates. This change also reduce number of interops required to support States.
None
Changed:
- Replaced AccessibilityStates class with enum flag
> [NUI][AT-SPI] Simplify AccessibilityStates

- src/Tizen.NUI.Components/Controls/Pagination.cs
Add support value interface in pagination widget.
Old implementation in screen-reader reads information by analyzing
widget structures. This causes problem with pagination widget in nui
library as this one may have multiple "visual" elements that are inside
containers. As a result nui pagination widget always have two
children.
This problem was solved by using value interface to inform screen-reader
about number of visual elements and position of selected one.
NONE
> [NUI][AT-SPI] Add Value interface to Pagination

- src/Tizen.NUI.Components/Controls/Button.Internal.cs
- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
[NUI] Change OnAccessibilityActivated() access modifier
- Change OnAccessibilityActivated() access modifier to use in FH.NUI which includes NUI package
- Split NotifyPropertyChangedAndRequestLayout() into equivalent two methods, because when using PropertySet event, the changed PropertyName comes as NotifyPropertyChangedAndRequestLayout
none
> [NUI] Change OnAccessibilityActivated() access modifier

- .github/workflows/deploy-documents.yml
Add a github workflow to deploy documents in https://samsung.github.io/TizenFX/
This workflow uses the DocFX with https://github.com/TizenAPI/TizenFX-Docs configurations.
> [Build] Add a github workflow to deploy documents

- .github/workflows/deploy-documents-for-tizen-docs.yml
- .github/workflows/deploy-documents.yml
Use tizenfx-build-worker 2.0 to use DocFX 2.56.1 version
> [Build] Downgrade tizenfx-build-worker to 2.0

- src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
- src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
Dependencies:
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/256959/ (merged)
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/258012/ (merged)
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/257536/ (merged)
This is meant to be used by applications that start before DBus is available.
```
static void Main(string[] args)
{
Accessibility.BridgeDisableAutoInit();
// Rest of application code
}
// When DBus is available
Accessibility.BridgeEnableAutoInit();
```
- ACR: None
> [NUI][AT-SPI] Add API for blocking automatic Bridge initialization

- src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
- src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
- src/Tizen.NUI/src/public/Visuals/VisualMaps.cs
Add borderline properies for view
- BorderlineWidth (float, default = 0.0f)
: Width of the borderline
- BorderlineColor (Vector4, default = Color.Black)
: Color of the borderline
- BorderlineOffset (float, default = 0.0f)
: Relative position offset from 'Real' borderline of visual.
== 0.0f then half is inside, and half is outside of visual.
== -1.0f then all borderline will be rendered inside of visual.
== 1.0f then all borderline will be rendered outside of visual.
These three properties are animatable
If it is ImageView, this property only allow to ImageView.Property.IMAGE.
Otherwise, allow to View.Property.BACKGROUND.
Also, current version only works when Border is not setup.
- ACR:
> [NUI] Add Borderline Properties

- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
> [NUI] fix disposing crash when layouter is null

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Previously, in LinearLayout, LayoutParamPolicies.MatchParent sets child
size to its parent size.
Now, in LinearLayout, LayoutParamPolicies.MatchParent calculates the
remaining space of parent and fills child in the remaining space of
parent.
There are 2 cases to fill child in the remaining space of parent.
1. MatchParent (both with or without weight)
- If child has MatchParent specification, then child is filled in the
remaining space of parent.
2. Specification 0 with weight
- If child has zero specification and weight is greater than 0, then
child is filled in the remaining space of parent proportional to its
weight.
- ACR:
> [NUI] Fix MatchParent to fill remaining space in LinearLayout

- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
> [NUI] fix disposing crash when layouter is null (#3050)

- src/Tizen.NUI.Components/Controls/Navigation/ContentPage.cs
- src/Tizen.NUI.Components/Controls/TabView.cs
Currently, WidthSpecification and HeightSpecification are updated
internally.
e.g.
In the beginning, WidthSpecification = LayoutParamPolicies.MatchParent;
After size calculation, WidthSpecification = 1280;
Until the above issue is resolved, ContentPage and TabView changes its
size calculation logic to calculate its MatchParent children size
correctly.
- ACR:
> [NUI] Calculate correct MatchParent size for ContentPage and TabView

- src/Tizen.NUI/src/public/Images/ImageLoading.cs
[NUI] Revert ImageLoading's access modifier
- In API6 ~ API8, this has been "public class", not "public static class".
- To support not-rebuilt API6~API8's Application, this is reverted bact to "public class".
none
> [NUI] Revert ImageLoading's access modifier

- src/Tizen.NUI/src/internal/Interop/Interop.DrawableGroup.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/DrawableGroup.cs
- test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CanvasViewSamsple.cs
This feature can add and control multiple Drawable objects.
Since this class inherits Drawable, user can use Drawable's Opacity and Transformation methods.
[Dependancy]
dali-adaptor: https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/257538/
dali-csharp-binder: https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/257607/
- ACR: No ACR
> [NUI] VectorGraphics: Add DrawableGroup Class

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
The followings have been fixed to calculate LinearLayout's MatchParent
children correctly.
- MatchParent child layout is calculated only if LinearLayout has
positive Specification or MatchParent.
- MatchParent child layout's margin is not shared with other MatchParent
child layouts.
e.g.
LinearLayout has size 100.
Child layout1 is MatchParent and its margin is 20.
Child layout2 is MatchParent and its margin is 0.
Then, child layout1's size is 30 and child layout2's size is 50.
- Setting Width/HeightSpecification has been removed because
Width/HeightSpecification should preserve the value set by user.
- Typo has been fixed. e.g. width, height
- ACR:
> [NUI] Fix to calculate LinearLayout's MatchParent children correctly

- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
Canvasview manages drawables as a list so that added drawables
used in canvasview are not released by gc.
- ACR:no acr
> [NUI] CanvasView: Manage added drawables as a list

- src/Tizen.NUI/src/internal/Interop/Interop.Drawable.cs
- src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Drawable.cs
Add BoundingBox property that uses Dali::CanvasRenderer::Drawable::GetBoundingBox api.
+)The float type Rectangle class is not ready yet.
Therefore, it transmits data in Vector4 class.
This type should later be changed to the appropriate data type.
dependancy patch
dali-adaptor : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/257837/
dali-csharp-binder : https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/257846/
- ACR:no acr
> [NUI]CanvasView: Add BoundingBox property

- src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
If recursive dependency exists between LinearLayout and its child
layout, then error log is printed.
To give more log info for recursive dependency in LinearLayout, parent
and child Owner info are added.
- ACR:
> [NUI] Add more log info for recursive dependency in LinearLayout

- src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
Up to now, both ResizePolicyType and LayoutParamPolicies are supported.
Originally, ResizePolicyType is for a view whose parent view does not
have Layout.
In contrast, LayoutParamPolicies is for a view whose parent view has
Layout.
However, ResizePolicyType can be used as LayoutParamPolicies as well
internally.
This makes users confused which one they need to use in each case.
Not to confuse users, ResizePolicyType is deprecated.
Instead, LayoutParamPolicies can be used to set the size of a view
relative to its parent or children.
Specifically, LayoutParamPolicies.MatchParent and
LayoutParamPolicies.WrapContent work with parent view which does not
have Layout as how ResizePolicyType.FillToParent and
ResizePolicyType.FitToChildren work.
- ACR: TCSACR-425
> [NUI] Deprecate ResizePolicyType

- src/Tizen.NUI.Components/Controls/Navigation/AppBar.cs
SetAccessibilityConstructor() is added in OnIintialize().
AccessibilityHighlightable is set to be true in Initialize().
- ACR:
> [NUI][ATSPI] Accessibility support for AppBar

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
Since AlertDialog is a container, it is not needed to be highlightable.
- ACR:
> [NUI][ATSPI] Not highlightable for AlertDialog

- src/Tizen.NUI.Components/Controls/TabBar.cs
- src/Tizen.NUI.Components/Controls/TabButton.cs
- src/Tizen.NUI.Components/Controls/TabContent.cs
- src/Tizen.NUI.Components/Controls/TabView.cs
SetAccessibilityConstructor() is added in OnInitialize() of TabView,
TabBar, TabButton, and TabContent.
AccessibilityHighlightable is set to be true in Initialize() of
TabButton.
- ACR:
> [NUI][ATSPI] Accessibility support for TabView components

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- [TDAF-1430] ScrollableaBase Child remove issue
If the ScrollableBase has one child, it does not need to move the page
- ACR:
> [NUI] Fix ScrollableBase Remove issue

- src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
[NUI] Disable desired size when image loading fail
When ImageLoading is failed, GetOriginalImageSize() returns zero size.
In this case, Calculating for fittingMode is able to make error because it use invalid size.
To avoid this problem, i added this patch.
- ACR: NONE
> [NUI] Disable desired size when image loading fail

- src/Tizen.NUI.Components/Controls/AlertDialog.cs
Actions are center aligned in AlertDialog.
- ACR:
> [NUI] Fix to set Actions center aligned in AlertDialog

- src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/ItemsLayouter.cs
- src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
> [NUI] fix layouter and cache clearing when property changed

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
https://github.sec.samsung.net/dotnet/NUIBackend/issues/56
- Stop scroll animation when ScrollTo() is called during scrolling
- Stop scroll animation when changing ScrollDirection
- ACR:
> [NUI] Fix ScrollableBase animation issue

- src/Tizen.NUI.Components/Controls/Notification.cs
Notification creates its own Window.
Not to cover the existing view behind Notification Window, Notification
Window's BackgroundColor is set to be transparent.
- ACR:
> [NUI] Set Notification Window transparent

- src/Tizen.NUI.Components/Controls/ScrollableBase.cs
- The function 'StopScroll()' must be called immediately by ScrollTo().
- ACR:
> [NUI] Fix Scrolling position issue by animation

- src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityProperties.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
This property was used to control automatic emission of the
BoundsChanged event. However, we no longer emit this event, so this
property serves no purpose.
Not to be confused with AT-SPI state Animated which is still available.
- ACR: None
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/258789/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/259070/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/258790/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/258788/
> [NUI][AT-SPI] Remove AccessibilityAnimated

- src/Tizen.NUI/src/public/Images/ImageLoading.cs
[NUI] Fix ABI break for API8 NUI image
- GetOriginalImageSize() was Hidden API and it was changed as to use default parameter in API9.
- This caused ABI break for tizen_6.0 application which references API9 NUI dll.
- Revert back to API8's GetOriginalImageSize() method form.
none
> [NUI] Fix ABI break for API8 NUI image

- src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
- src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
This property is already provided in TextField.
TextEditor also needs a property that controls the options of the input method.
* Below patch should be applied first.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/258649/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/258650/
> [NUI] Add InputMethodSettings property to TextEditor

- src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
- src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
> [NUI][Xaml] Fix issue that BindingContext can't be used in C# code （JIRA 2296）

- src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
Previously, Navigator's animation did not keep the final state.
e.g. Opacity from 1 to 0 animation did not keep opacity 0 when the
animation was finished.
Now, Navigator's animation keeps the final state.
Previously, hidden Pages did not have actually hidden visibilities.
e.g. When the peek Page was hidden by newly pushed Page, the hidden
Page's visible state was true.
Now, hidden Pages have actually hidden visibilities.
- ACR:
> [NUI] Fix Navigator's animation and Page's visible state

- src/Tizen.NUI/src/internal/Accessibility/AccessibilityDoGestureSignal.cs
- src/Tizen.NUI/src/internal/Interop/Interop.DoGestureSignal.cs
- src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
- In dali, the property is originally bool type.
- So, `Consumed` property should be bool value, just same as dali.
Changed the type and its binding.
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/259004
- N/A
> [NUI] Change the type of Consumed property for GestureInfo

- src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
- src/Tizen.NUI/src/public/BaseComponents/View.cs
- src/Tizen.NUI/src/public/Common/NUIConstants.cs
This patch is necessary to the following patch.
"[NUI] Deprecate ResizePolicyType"
It is impossible that LayoutParamPolicies.WrapContent supports both
ResizePolicyType.UseNaturalSize and FitToChildren.
Therefore, LayoutParamPolicies.WrapContent does not support
ResizePolicyType.UseNaturalSize nor FitToChildren.
Instead, LayoutParamPolicies.WrapContent makes View fit to its children
only if the View sets its Layout.
In the same way, LayoutParamPolicies.MatchParent does not support
ResizePolicyType.FillToParent.
Instead, LayoutParamPolicies.MatchParent makes View fill to its parent
only if the View sets its Layout.
If View uses LayoutParamPolicies.WrapContent or MatchParent while it
does not set its Layout, then the View does not fit to its children nor
fill to its parent.
Instead, …
> [NUI] Fix to require Layout to fit to children or fill to parent
